### ISSUE TITLE
Invalid CSS

### ISSUE THREAD

**Issue by mrichman** [Compass/compass#1]
I ran my CSS against the W3C validator (http://jigsaw.w3.org/css-validator/validator), and got the following error:

Property overflow-x doesn't exist in CSS level 2.1 but exists in [css3] :  hidden 

This occurs on line 176 of the screen.css generated by the compass framework for Blueprint:

/\* line 97, ../../../../../../../Library/Ruby/Gems/1.8/gems/chriseppstein-compass-0.6.5/frameworks/blueprint/stylesheets/blueprint/modules/_grid.sass */
- html .column, \* html div.span-1, \* html div.span-2, \* html div.span-3, \* html div.span-4, \* html div.span-5, \* html div.span-6, \* html div.span-7, \* html div.span-8, \* html div.span-9, \* html div.span-10, \* html div.span-11, \* html div.span-12, \* html div.span-13, \* html div.span-14, \* html div.span-15, \* html div.span-16, \* html div.span-17, \* html div.span-18, \* html div.span-19, \* html div.span-20, \* html div.span-21, \* html div.span-22, \* html div.span-23, \* html div.span-24 { overflow-x: hidden; }

**Comment by whicks1** [comment]
I agree, the blueprint grids are overflow happy, & setting to hidden is not always the desired effect.  Can this be abstracted out into a mixin unto itself?

**Comment by chriseppstein** [comment]
This property was added in blueprint 0.8 and I don't fully understand what it is trying to achieve. My goal is to have the blueprint port stay as true to blueprint proper as makes sense. I'm not inclined to make a change just to silence a validation error that is valid in css3 and likely harmless in css2 (browsers discard properties they don't understand).

What, if any, real issue does this cause?

**Comment by chriseppstein** [comment]
Ok. I waited 5 days for further comments. Closing this issue.
