### ISSUE TITLE
An app with Compass will not run if Haml is installed on the server

### ISSUE THREAD

**Issue by endymion** [Compass/compass#10]
Compass requires haml version 2.1 which is only available currently in haml-edge.  But Compass will happily load haml version 2.0 and not haml-edge version 2.1 if Haml is installed.  Then the app won't run.  The existence of Haml 2.0 on a server should not prevent a Compass app from running.

It's frustrating to descend into DLL Hell when I try to deploy, since Compass isn't necessary in production.  The CSS has already been generated and Compass is irrelevant to the production server.  Yet Compass is the only thing stopping me from deploying.  Very frustrating.

Is there a workaround for using Compass on servers where Haml is already installed?  I have the option of installing my own local haml-edge but I do not have the option of uninstalling the existing Haml 2.0.

**Comment by chriseppstein** [comment]
I assume your running a rails application environment. It's not "best practice" to check in your generated css in such environments. But assuming you do not agree with me, I still think it's incredibly dangerous to run with a different version of haml in development than in production. I recommend that you either freeze your haml-edge gem in vendor or install it in your production environment. Existing apps will be unaffected by the presence of the haml-edge gem, but compass will pick it up if it sees it.

I, too, look forward to the next stable release of haml so that we can simplify the dependencies. Hopefully it will be soon.

**Comment by chriseppstein** [comment]
If you're only using compass in development, you can also do two other things:
1. Use compass in standalone mode without the rails integration. In an existing rails project, you can just delete the config/initializers/compass.rb and then run compass --watch to compile your stylesheets.
2. Conditionally run compass by wrapping the contents of config/initializers/compass.rb in a block that checks the current rails environment.

**Comment by endymion** [comment]
Thank you for the suggestions, I really appreciate it.  I like the idea of Compass but if it depends on an edge version of something else and that dependency causes deployment problems then Compass isn't something that I would depend on in production.  So thanks for the suggestions for ways to use it during development only.  I solved my deployment problem by removing Compass from the project, since I don't have the option of removing the Haml gem from the deployment environment.  If I continue to tinker with Compass then I'll just use it in development to trigger Sass.  I do like that --watch feature.

You can reproduce the problem very easily.  "gem install haml"  Then try to run that sample Rails app.  If you have both haml and haml-edge then Compass will load haml and then complain that it requires haml 2.1.  If you have the ability to totally control what gems are installed in your production environment then that's no problem but Compass won't work on hosting environments that provide Haml and then don't let you mess with your GEM_PATH.  That sounds like a niche thing but Dreamhost is one of those hosts and they're popular enough to be relevant.

**Comment by chriseppstein** [comment]
I explicitly tested the case of having both gems installed, but I will retest. It shouldn't break if both are there and if that's the case, then a patch will be forthcoming. If it's not reproducible in a simple app with just haml and compass installed, then there must be something else that is requiring haml. Can you show me what your gem configuration in your environement looks like? It could be that you're setting the dependency incorrectly and causing the wrong version to get picked up.

**Comment by endymion** [comment]
I really appreciate your assistance, I know that you're a busy guy.  I'm trying to repay Karma by contributing my own gem to the world for doing layouts, which will be compatible with Compass.

To start out my day today, I decided to add Compass back into that problem project that has to go to Dreamhost, to help you to troubleshoot any possible haml/haml-edge incompatibility.  I re-ran compass --rails to add config/compass.config and config/initializers/compass.rb, and it WORKED.  It deploys to the problem server and it runs.  ZOMG now I'm so confused.

I think you can maybe mark this issue closed because I think maybe I was totally wrong.  I'm going to continue tinkering with it today to try to reproduce the haml/haml-edge incompatibility that caused me so much grief last night.

Either way, Compass is really neat.  Thank you for making it and for releasing it so that I can use it.
