### ISSUE TITLE
[feature request / mixin] custom normalize

### ISSUE THREAD

**Issue by stryju** [Compass/compass#1001]
Hey.

i've created a mixin to generate custom normalize.css based on the elements you really need ( if you want to exclude some elements - do it )

it's located [here](https://github.com/stryju/normalize_custom.scss)

what do you think about including it as a mixin in compass?

best,
tom

**Comment by mirisuzanne** [comment]
I really like parts of your approach here. I think this would be a great influence on our current reset module, and it would be great if you were willing to work on integrating the two? 

I haven't had a chance to look real close, so I may have more questions later, but here's a few thoughts:
1. Your `in-list()` function is duplicating (half) the functionality of the Sass function `index()`.
2. We can't tie our releases directly to another project (normalize). That doesn't stop us from using their approach and giving credit (like we do with (other) Eric Meyer's reset), it just means we might make changes and update on a different schedule. It won't be a direct port.
3. I think we should tie this together with the current reset in a DRY way, so you have options: mixins or placeholders for both a simple normalization and a more complete reset.

**Comment by stryju** [comment]
i'd like to give back to the community, so hell yeah! that'd be a pleasure :D
1. totally missed the `index()` function - that's why the `in-list()` is there
2. well, i'm willing to keep it up-to-date, but it's up to You
3. i think placeholders are damn _sexy_ - i'd go with placeholders :D

**Comment by mirisuzanne** [comment]
Glad you're so excited to help! Point 2 is not a matter of keeping it up to date exactly, it's a matter of promising that we will stick with them on all decisions. This is a different project. We may decide differently on some things. Placeholders _are_ sexy, that's what I love about your approach. But you need mixins when you start overriding the cascade, so keeping both available (and united) will give us a very powerful module of reset tools.

**Comment by stryju** [comment]
sure thing - when do we start?

**Comment by mirisuzanne** [comment]
Clone yourself a copy of Compass and dive in! 

I think the key is to tie in with what we already have as well as possible. We can break backwards compatibility in small ways if needed, but let's avoid it when possible. I'm available to look at what you're doing and answer questions whenever you need.

**Comment by stryju** [comment]
take a look [here](https://github.com/stryju/compass/commit/f3ca3ea579177395840a927ca30f64496c708d35) for custom reset - contact me with any feedback you got ;-)

**Comment by chriseppstein** [comment]
link is borken

**Comment by stryju** [comment]
uh - removed the repo :(

will probably re-do it, if the interest is still there :-)
