### ISSUE TITLE
Sprite image ordering

### ISSUE THREAD

**Issue by superbland** [Compass/compass#1002]
Compass used create a sprite image, ordering the images by file name (I just upgraded, but sorry I'm not sure what version I was on previously). Although it was slightly hackish, if I wanted to have them be inserted in a particular order (e.g. to manually write background-position: 0px bottom;) I could simply add "z-" to the front of the file name and be sure it would be at the end of the file.

As far as I can tell, Compass now inserts files into a sprite based on file size, going from biggest to smallest. To me this makes less sense, and I would appreciate once again having some kind of control over the ordering, if I need it.

**Comment by hagenburger** [comment]
I already implemented such a thing while I was experimenting with sprites for an iPhone website in normal and Retina resolution. Therefore it must have the same order. The code is here:

https://github.com/hagenburger/compass/commit/c472664b55269547de7231b7788ffb11c065e3ca

**Comment by superbland** [comment]
Cool thanks, I'll check this out!

**Comment by scottdavis** [comment]
@hagenburger did you want to make a PR for that change?

**Comment by hagenburger** [comment]
It’s in https://github.com/hagenburger/compass/commit/c472664b55269547de7231b7788ffb11c065e3ca. It needs to be updated and tested. I can’t work on this right now as I’m both ill and in China :(

**Comment by krisbulman** [comment]
This would be a nice improvement, doing the check for ordering differences between two sprite maps is not obvious if you need them to match (retina sprites) http://github.com/krisbulman/retina-sprite-mapper/blob/master/sass/_retina-sprites.scss#L94

**Comment by robwierzbowski** [comment]
Related requests: https://github.com/chriseppstein/compass/issues/690

+1 from me. With predictable sorting based on names you can reduce the css needed for high pixel density image sprites to a background-image  and background-size declaration.

**Comment by notethis** [comment]
+1

**Comment by chrisforrette** [comment]
I'd like to +1 this as well.

I'm trying to generate a sprite for an animation sequence for a bunch of numbered files and it mashes them all together backwards.

**Comment by scottdavis** [comment]
This is already implemented in master

**Comment by skug** [comment]
As the work on v0.13 is still ongoing: is there a way to patch a vertical layout order by filename in the current stable release with an extension mechanism so it can be easily shared on different clients via project version control? You mentioned that it would be possible to write an own layout class in https://github.com/chriseppstein/compass/issues/690#issuecomment-8548102 but it seems, thats only the case with v0.13 as the base... 
(I could not find a way to overwrite such a core behavior, but it could also be my lack of ruby know-how...)

**Comment by simasalmani** [comment]
@hagenburger It was really helpfull, Thank you.
