### ISSUE TITLE
Better error message for compiling individual stylesheets

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#1004]
Currently says:

> You must compile individual stylesheets from the project directory.

Should probably say:

> Couldn't find the compass configuration file. When compiling individual stylesheets, you need to first change your current directory to the project directory.

**Comment by sethburtonhall** [comment]
I have been troubleshooting this for a long time. I am working with a WP install and it is driving me crazy. Am I supposed to change the http_path in my config file?

**Comment by scottdavis** [comment]
actually where this error is thrown the new message you propose doesn't make any sense. I think error checking and validation in the compiler need to be addressed.

**Comment by chriseppstein** [comment]
This shouldn't be an issue anymore

**Comment by upngo** [comment]
This would've saved me some time today, eventually found a blog telling me something similar. 

But disagree with disagree with second part of message as the config.rb file might not be in the same folder as the project directory.

> Couldn't find the compass configuration file. When compiling individual stylesheets, you need to first change your current directory to the **directory your config.rb file is in**
