### ISSUE TITLE
Ability to disable sprite generation to speed up development

### ISSUE THREAD

**Issue by satazor** [Compass/compass#1006]
In large projects with a lot of images/sprites to be generated, one must wait a LOT of time in order to preview their changes.
It would be useful to have a configuration to disable sprite generation, outputing the full image path instead of the sprite path + background-position's.

This would absolutely improve the development process.

**Comment by Nilegfx** [comment]
as i know, with the latest compass "Version: 0.12.2". The sprite parser will not update the sprite image (the one which contains all sprite images) if you didn't update your (images/icons) folder. if you did update your folder images with a new image (only in this case) it will parse the main sprite image again. 

my second suggestion is to install "Oily PNG" gem. as the last part in this documentation recommends whom in your case. 
http://compass-style.org/help/tutorials/spriting/#performance

**Comment by satazor** [comment]
@Nilegfx I already have Oily png installed but is still damn slow.. It can take up to 10minutes to complete on a relatively big sprite.

Gonna see if it gets improved with 0.12.2 though..

**Comment by Nilegfx** [comment]
I'm using the Command line directly without any helper tool like (Scout, Compass.app , etc.. ) so i can watch and track the actual compiling errors.

so if you are doing so, check the command after you save the sass/scss file and tell me what is says.

another thing: Try to Uninstall the oily png extension and check the process.

3: How many images you try to sprite ? how big (size) the final png image is?

try to give us a good brief  about the environment you working with (mac or windows, how many images you want to sprite, command line logs.. etc) so we can share the experiences better.

**Comment by satazor** [comment]
@Nilegfx this issue is somewhat related to #897
Here is a console screenshot of the compilation process: http://cl.ly/image/2M0v251Y0e46
I am running Windows7 64 bits with Ruby 187 and compass 0.12.2
I uninstalled oily png and installed it again.. here is the log:

```
Fetching: oily_png-1.0.2.gem (100%)
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
Successfully installed oily_png-1.0.2
1 gem installed
Installing ri documentation for oily_png-1.0.2...

No definition for oily_png_canvas_steps_residues

No definition for oily_png_canvas_steps

No definition for oily_png_canvas_resample_nearest_neighbor_bang

No definition for oily_png_decode_png_image_pass

No definition for oily_png_encode_png_image_pass_to_stream

No definition for oily_png_color_compose_quick

No definition for oily_png_color_r

No definition for oily_png_color_g

No definition for oily_png_color_b

No definition for oily_png_color_a

No definition for oily_png_compose_bang

No definition for oily_png_replace_bang
Installing RDoc documentation for oily_png-1.0.2...

No definition for oily_png_canvas_steps_residues

No definition for oily_png_canvas_steps

No definition for oily_png_canvas_resample_nearest_neighbor_bang

No definition for oily_png_decode_png_image_pass

No definition for oily_png_encode_png_image_pass_to_stream

No definition for oily_png_color_compose_quick

No definition for oily_png_color_r

No definition for oily_png_color_g

No definition for oily_png_color_b

No definition for oily_png_color_a

No definition for oily_png_compose_bang

No definition for oily_png_replace_bang
```

I can see some errors but it says that the library gets successfully installed.

As you can see in the screenshot, compass is generating the sprite several times for each image within the sprite directory.

**Comment by Nilegfx** [comment]
this is not the normal process, do you have any concerns about upgrading your ruby version ? if you don't so Upgrade and lets see.

in the other issue #897 I see that you declare your sprite different than me. i prefer to declare it with @mport "folder/*.png"; way.

We can walk through this issue together on messenger or skype if you like. this will be faster and effective. 

Send me your MSN or skype account.

**Comment by satazor** [comment]
Skype account: andrecruz_triworks

**Comment by scottdavis** [comment]
this seems to be an outstanding issue with windows if you can provide a sample project and the os specs ill try to get a vm set up

**Comment by darren131** [comment]
I'm having a similar/the same issue. My sprite image i being recreated each time I make a change to any of my .scss files.

I'm running compiling Compass/Sass using Codekit. Codekit using Sass v3.2.1 and Compass 0.12.2

This is my config file:

``` ruby
# Set this to the root of your project when deployed:
http_path = "/"
css_dir = "stylesheets"
sass_dir = "stylesheets/scss"
images_dir = "images"
javascripts_dir = "javascript"

output_style = :nested
environment = :development
```

This is how I'm generateing my sprites:

``` sass
$s-sprite-dimensions: true;
$sprite-clean-up: false;
// Sprite vars
@import "s/*.png";
@import "blog/*.png";
@include all-s-sprites;
@include all-blog-sprites;
```

Any advice, help, etc would be outstanding!

Thanks

**Comment by scottdavis** [comment]
This should be fixed on master
