### ISSUE TITLE
The output for sprite's classes don't have commas separating them

### ISSUE THREAD

**Issue by JAW-Dev** [Compass/compass#1009]
The output for sprite's classes don't have commas separating them. 
i.e  
    .social-sprite, .facebook .social-facebook { background: url('../images/social-sa0a291a87f.png') no-repeat; }
    .facebook .social-facebook { background-position: 0 -3648px; }

**Comment by scottdavis** [comment]
Going to need more specific information. Can you provide gist of the source sass.
