### ISSUE TITLE
compass watch has load errors

### ISSUE THREAD

**Issue by resistorsoftware** [Compass/compass#1013]
My local gem list shows bootstrap-sass is present and available.

LoadError on line ["161"] of /Users/fizzbuzz/.rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.2/lib/compass/configuration/data.rb: cannot load such file -- bootstrap-sass

I am using RVM to provide Ruby 1.9.3. The compass config.rb file is in a subdirectory of my Sinatra app, and has compass has not previously had load errors on require like this. 

Any clues as to why Compass is having trouble finding gems?

**Comment by scottdavis** [comment]
Try the new listen branch
