### ISSUE TITLE
Sinatra Integration Tutorial is missing Compass.sass_engine_options

### ISSUE THREAD

**Issue by oscherler** [Compass/compass#1017]
In http://compass-style.org/help/tutorials/integration/, the `sass` call is missing the `Compass.sass_engine_options` parameter, resulting in the following error if you try to `@import "compass/reset";`:

> Sass::SyntaxError at /css/screen.css
> File to import not found or unreadable: compass/reset.

Instead of

```
get '/stylesheets/:name.css' do
  content_type 'text/css', :charset => 'utf-8'
  scss(:"stylesheets/#{params[:name]}" )
end
```

it should be

```
get '/stylesheets/:name.css' do
  content_type 'text/css', :charset => 'utf-8'
  scss(:"stylesheets/#{params[:name]}", Compass.sass_engine_options)
end
```

**Comment by etagwerker** [comment]
I was having the same problem and I solved it with your fix. Thank you!
