### ISSUE TITLE
Box Shadow: none

### ISSUE THREAD

**Issue by merbjedi** [Compass/compass#102]
I have a need to specify box-shadow: none in one of my styles. However, the `+box-shadow(none)` didnt like this. Is there a better way?

I had to just revert to using standard duplicated CSS3 styles:

```
box-shadow: none
-moz-box-shadow: none
-webkit-box-shadow: none
```

**Comment by mirisuzanne** [comment]
I've been using +box-shadow("transparent") or +box-shadow(rgba(0,0,0,0)) to pull this off, but I agree that this could be useful. Or maybe +remove-box-shadow(). I'll take a look at patching that.

**Comment by chriseppstein** [comment]
Allow box shadow to be turned off by @include box-shadow(none). Closed by 909fb92ad35f92cebf6240a7bb4b48294ce2e5aa.

**Comment by DavidOliver** [comment]
Think this still needs to be added to the docs.

**Comment by mirisuzanne** [comment]
Can you file a separate issue, or even better, submit a patch yourself? Thanks!
