### ISSUE TITLE
error compiling: array size too big for `sprite'

### ISSUE THREAD

**Issue by jerseycheese** [Compass/compass#1022]
This error has come out of nowhere and is preventing us from compiling and closing out a project.  It seems as if any usage of sprite() is throwing the error, but here's an example of how it's being used throughout our stylesheet:

background: sprite($icons, name-of-file, $offset-x: 5px, $offset-y: 12px) no-repeat #e9e9e9;

Thanks for any help!

**Comment by jerseycheese** [comment]
I should mention:

OSX 10.7.4
Sass 3.2.1 (Media Mark)
Compass 0.12.2 (Alnilam)

**Comment by scottdavis** [comment]
how many images are in this sprite?

**Comment by jerseycheese** [comment]
About 40 or so.

**Comment by jerseycheese** [comment]
There were about 80 originally but I took a bunch out thinking it was the amount of images throwing the error.  But it's still choking.

**Comment by mndonx** [comment]
I'm working on this project with jerseycheese. I just created a fresh scss file, added in about 40 lines of code that compiles fine (no sprites). Then I add just one line like: 

<code>background: sprite($icons, png-name, $offset-x: 100%, $offset-y: 0) no-repeat;</code> 
or
<code>@include sprite-replace-text-with-dimensions($icons, png-name);</code>

Ruby crashes and I have to force quit from Activity Monitor. I'm not getting a good log message from LiveReload or Console. 

Strangely other similar files (on similar projects) do not choke -- and this just started happening a few days ago on this file. It's happening to both of us, on different machines. 

Any thoughts on further ways to troubleshoot? This happened once before to me, and went away when I reinstalled ruby and gems. That didn't help this time around. 

OSX 10.8 (just upgraded from 10.7 yesterday)
Live Reload 2.3.20
Compass 0.12.2 (Alnilam)
Sass 3.2.1 (Media Mark)
System Ruby 1.8.7 (also tried using Ruby 1.9.2p320)

**Comment by scottdavis** [comment]
im curious if you have a corrupted png file can you get a full stack trace?

**Comment by mndonx** [comment]
Indeed, this was the issue. It wasn't easy to find (had to use process of elimination), but there was a corrupt PNG in there. Any suggestions on how to locate it in the future if it happens again?

**Comment by scottdavis** [comment]
if you have a full stack trace I can probably make it catch the exception if i know what im looking for

**Comment by mndonx** [comment]
Sorry - I'm not sure what a full stack trace is. Or rather - how to produce one in this instance.

**Comment by mndonx** [comment]
And by the way, thank you for pointing me in the right direction without much info to go on! I appreciate your time.

**Comment by stereoscott** [comment]
Just wanted to say thank you for documenting this issue! I got the same error today and a quick search led me here. I had a corrupted png file in my sprite folder, and once I located the culprit :sweat: I was able to re-save it and then the sprite generation was working fine. :thumbsup:  Thanks again!

**Comment by mndonx** [comment]
:) Glad this helped!

**Comment by davilious** [comment]
Actually it also helped a lot :+1:
