### ISSUE TITLE
grid-background renders incorrectly in Chrome

### ISSUE THREAD

**Issue by davidpett** [Compass/compass#1023]
using the grid-background mixin in Chrome results in the gutter spacing being off and shifting the grid a few pixels for the middle columns.

Renders fine in Safari and Firefox.

**Comment by mirisuzanne** [comment]
I'm guessing this only happens in fluid-background cases? Chrome is awful with sub-pixel rounding on backgrounds. This is a browser bug, but it would not be bad to document it in Compass.

**Comment by davepenfold** [comment]
I've submitted a bug report to Chromium

https://code.google.com/p/chromium/issues/detail?id=152706
