### ISSUE TITLE
@include user-select(none) should prefix -moz for Firefox

### ISSUE THREAD

**Issue by kylemacfarlane** [Compass/compass#1025]
For whatever reason Firefox has non-standard behaviour when `-moz-user-select` is set to `none` and it also turns off selection in inputs and it's not possible to override it. However passing the value `-moz-none` seems to make Firefox behave the same as other browsers.

Also is there also any chance of getting `user-drag` added to this module?

EDIT: Documentation on the values: https://developer.mozilla.org/en-US/docs/CSS/user-select

**Comment by mirisuzanne** [comment]
Does `user-drag` exist anywhere outside of webkit? I don't see it mentioned anywhere else.

**Comment by mirisuzanne** [comment]
Closed by 36f87c003f - I need to run tests once Rubygems Dependency API is back up, then I can pull it into master (and possibly add it to stable as well).
