### ISSUE TITLE
Text overflow ellipsis for Firefox 4, 5 & 6 doesn't work.

### ISSUE THREAD

**Issue by MoOx** [Compass/compass#1026]
The trick with an XML doesn't work since Firefox 4 (-moz-binding was removed).

We should remove this solutions for something better.
Here are some js fallback I made. It support multilines overflow ellipsis !

http://jsfiddle.net/MoOx/M53nB/

**Comment by mirisuzanne** [comment]
Whatever we do, it should be toggled by the mozilla legacy-support variable.

**Comment by MoOx** [comment]
This issue is kind of stupid. Since Firefox 4, there is auto update. So, I think we can forget that problem.
Maybe we can create a multilines overflow helper with an js extension ?
