### ISSUE TITLE
How to specify certain sass files to be watch or compiled using command line tool.

### ISSUE THREAD

**Issue by neekey** [Compass/compass#1027]
I'm new to Compass, and it seems like Compass will compile all files in directory `scss` to `stylesheets`, what if I just want part of the files in `sass` to be compiled?

**Comment by krisbulman** [comment]
You can compile singe (or multiple) files by specifying the project path:

```
compass watch /path/to/project /path/to/project/style.scss
```

or alternatively, use a relative path: 

```
compass watch ./ sass/style.scss
```

To add an additional file to the compile list, simply add it's file path at the end

```
compass watch ./ sass/style.scss sass/style2.scss
```

The same should work with compass compile
