### ISSUE TITLE
Programmatically compile sass files

### ISSUE THREAD

**Issue by johnkchow** [Compass/compass#1028]
I'm generating sass files in runtime as some of the variable values are set from the DB. However, my sass template file imports from 'compass/css3', and there doesn't seem to be a straightforward way of compiling a sass string with this dependency. I understand that I can call `Sass.compile(string)` for a sass string without the dependency. 

In this article (http://www.krautcomputing.com/blog/2012/03/27/how-to-compile-custom-sass-stylesheets-dynamically-during-runtime/), the author basically uses sprockets in a round-about way to achieve what I'm trying to do, but I don't want to be writing unnecessary files. I just want to pass a sass string in, and get a css string out. Any ideas?

**Comment by scottdavis** [comment]
Take a look at the compiler class you will need to set the sass load path to include compass and call the engine directly. This is not one of the use cases we currently support, since it involves a non standard use.
