### ISSUE TITLE
Image Measuring

### ISSUE THREAD

**Issue by iammerrick** [Compass/compass#103]
I spoke with you Chris briefly on Twitter. He mentioned to put this here. Essentially the ability for compass to measure background images if you don't pass in parameters.

Thanks for all your hard work. This project is amazing.

**Comment by chriseppstein** [comment]
I did this for the `pretty-bullets` mixin. What others should have it?

**Comment by iammerrick** [comment]
Sound awesome. I think a measure image function would be cool. I wish I knew Ruby so I could pitch in. I'm working on that... But something like:

Code:

@include measure_image(myimage.jpg); 

Result:
// Returns image width and height.
width: 243px;
heigh: 100px; 

Thanks for all your hard work on this project. I use it every day now. Very useful stuff.

**Comment by chriseppstein** [comment]
compass already has image-width("myimage.jpg") and image-height("myimage.jpg"). I [use those on pretty-bullets now](http://github.com/chriseppstein/compass/blob/master/frameworks/compass/stylesheets/compass/utilities/lists/_bullets.scss#L27). But I'm curious if there's another place that you thought they should be used.

**Comment by chriseppstein** [comment]
and, of course, you can use them directly:

```
div
  width: image-width("adsf.jpg")
  height: image-height("adsf.jpg")
```

**Comment by chriseppstein** [comment]
closing

**Comment by iammerrick** [comment]
You are awesome. Thanks!
