### ISSUE TITLE
Compile error (Sass::SyntaxError on line 83 of c: Invalid CSS after "": expected expression (e.g. 1px, bold), was "= #000")

### ISSUE THREAD

**Issue by kavithaLK** [Compass/compass#1030]
Seems to happen irrespective of the project 

I see one unresolved thread elsewhere too (http://www.sencha.com/forum/showthread.php?153060-Compass-Sass-setup).

Thanks for looking into this.

Sass::SyntaxError on line 83 of c: Invalid CSS after "": expected expression (e.g. 1px, bold), was "= #000"
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.8.17/frameworks/compass/stylesheets/compass/_reset.sass:1
  C:/GrailsWS/Account/compile/web-app/test/screen.sass:7
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/scss/parser.rb:925:in `expected'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/script/lexer.rb:193:in`expected!'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/script/parser.rb:450:in `assert_expr'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/script/parser.rb:49:in`parse'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/script/parser.rb:140:in `parse'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/script.rb:32:in`parse'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/engine.rb:830:in `parse_script'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/engine.rb:593:in`parse_property'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/engine.rb:544:in `parse_line'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/engine.rb:456:in`build_tree'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/engine.rb:475:in `append_children'
  org/jruby/RubyArray.java:1620:in`each'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/engine.rb:474:in `append_children'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/engine.rb:465:in`build_tree'
  org/jruby/RubyArray.java:1620:in `each'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/engine.rb:458:in`build_tree'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/engine.rb:475:in `append_children'
  org/jruby/RubyArray.java:1620:in`each'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/engine.rb:474:in `append_children'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/engine.rb:330:in`_to_tree'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/engine.rb:257:in `to_tree'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/tree/visitors/perform.rb:142:in`visit_import'
  org/jruby/RubyKernel.java:2109:in `send'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/tree/visitors/base.rb:37:in`visit'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/tree/visitors/perform.rb:18:in `visit'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/tree/visitors/perform.rb:144:in`visit_import'
  org/jruby/RubyArray.java:2339:in `collect'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/tree/visitors/perform.rb:144:in`visit_import'
  org/jruby/RubyKernel.java:2109:in `send'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/tree/visitors/base.rb:37:in`visit'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/tree/visitors/perform.rb:18:in `visit'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/tree/visitors/base.rb:53:in`visit_children'
  org/jruby/RubyArray.java:2339:in `collect'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/tree/visitors/base.rb:53:in`visit_children'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/tree/visitors/perform.rb:27:in `visit_children'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/tree/visitors/perform.rb:39:in`with_environment'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/tree/visitors/perform.rb:26:in `visit_children'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/tree/visitors/base.rb:37:in`visit'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/tree/visitors/perform.rb:47:in `visit_root'
  org/jruby/RubyKernel.java:2109:in`send'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/tree/visitors/perform.rb:18:in`visit'
  org/jruby/RubyKernel.java:2109:in `send'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/tree/visitors/perform.rb:7:in`visit'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/tree/root_node.rb:20:in `render'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/engine.rb:300:in`_render'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/haml-3.1.7/vendor/sass/lib/sass/../sass/engine.rb:247:in `render'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.8.17/lib/compass/actions.rb:71:in`compile'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.8.17/lib/compass/compiler.rb:50:in `run'
  org/jruby/RubyArray.java:1620:in`each'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.8.17/lib/compass/compiler.rb:49:in `run'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.8.17/lib/compass/commands/update_project.rb:20:in`perform'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.8.17/lib/compass/commands/stamp_pattern.rb:19:in `perform'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.8.17/lib/compass/commands/base.rb:15:in`execute'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.8.17/lib/compass/commands/project_base.rb:19:in `execute'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.8.17/lib/compass/exec.rb:242:in`do_command'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.8.17/lib/compass/exec.rb:57:in `perform!'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.8.17/lib/compass/exec.rb:40:in`run!'
  c:/jruby-1.6.8/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.8.17/bin/compass:8:in `(root)'
  org/jruby/RubyKernel.java:1087:in`load'
  c:/jruby-1.6.8/bin/compass:23:in `(root)'

**Comment by roboshoes** [comment]
I'm having the exact same porblem. If anyone knows something about it, please let me know! Thank you!

**Comment by roboshoes** [comment]
Ok, I just played around with it for a bit and what helped mit is to unistall compass and sass and reinstall sass and compass.

```
gem uninstall compass
```

I had a different version of compass installed so that didn't work right away.  I needed to 

```
gem uninstall chriseppstein-compass
```

then 

```
gem unistall sass
gem install sass
gem install compass
```

I don't know - I just poked around and that did the trick (I really have now idea :) )

Anyways - maybe that helps you.

**Comment by scottdavis** [comment]
it helps greatly if you post a gist of the sass causing the error

**Comment by scottdavis** [comment]
any update?

**Comment by roboshoes** [comment]
sorry for the delay. I will look into it as soon as I can. Don't have the source with me right now.

**Comment by niallthompson** [comment]
I am also getting a similar error. I'm using Codekit to compile. It is up to date: Compass 0.12.2 & Sass 3.2.2

Compass was unable to compile one or more files in the project: 

```
error style.scss (Line 78 of _page.scss: Invalid CSS after "...idth(t, 4, 5)}%": expected expression (e.g. 1px, bold), was ";")
```

overwrite style.css 

(This action was triggered by a change to _page.scss)

Here is the code that generates the error:

.element {
  width: #{gs-width(t, 4, 5)}%;
}   

Any help would be appreciated

Niall

**Comment by chriseppstein** [comment]
Use units or string addition/interpolation.

**Comment by yogurt-island-331** [comment]
Hi I am having this issue and tried uninstall and install, but it didn't work.
