### ISSUE TITLE
Sprite path imports don't work on Windows

### ISSUE THREAD

**Issue by nex3** [Compass/compass#1036]
From nex3/sass#522.

It looks like https://github.com/chriseppstein/compass/blob/v0.12.2/lib/compass/sprite_importer.rb#L78 is using `Dir[]`, which doesn't work properly with forward slashes on Windows. See nex3/sass@3ee3411077b1df9d6747d71ab8bf4ab4506917aa.

**Comment by scottdavis** [comment]
Oh wow that totally evaded me I bet this will solve the weird problems we have been seeing in widows

**Comment by scottdavis** [comment]
@nex3 does Dir#glob suffer form the same problem? or would you recommend Dir#entries?

**Comment by ventrebleu** [comment]
I guess I have the same issue with my nested folders and trying to use the Sprite feature.
How can I get it fixed?
(this apparently goes beyond my knowledge)

**Comment by scottdavis** [comment]
fixed 58babac

**Comment by ventrebleu** [comment]
Thanks Scott!
