### ISSUE TITLE
"Extend Directives" Error when using sprites within extension @media bubbling

### ISSUE THREAD

**Issue by yahreen** [Compass/compass#1037]
I am using Breakpoint for Sass (https://github.com/canarymason/breakpoint) and attempting to also include a Compass sprite within an @media bubble and receive the following error:

`error assets /scss/style.scss (Line 411 of *.png: Extend directives may only be used within rules.)`

Here is my Sass code:

```
$icons-sprite-dimensions: true;
@import "icons/*.png";

.social-1 {
    a {
        @include icons-sprite("social-fb-mobile");

        @include breakpoint($breakpoint-lg) {
            @include icons-sprite("social-fb-desktop");
        }
    }
}
```

**Comment by ghost** [comment]
Did you find another way of achieving what you needed? I'm having the same issue and found I could use some other sprite mixins to get around the error, however it doesn't seem to play nice when sprite-spacing, sprite-position, or sprite-layout options come into play (the background position is wrong):

```
@include sprite-background-position($sprite-map, 'logo');
@include sprite-dimensions($sprite-map, 'logo');
```

I'll put some code up later

**Comment by yahreen** [comment]
No it's been deprecated, you simply just can't do it anymore.

**Comment by mistermann87** [comment]
You could use it like this:

```
@include breakpoint($breakpoint-lg) {
    & {      
        @include icons-sprite("social-fb-desktop");
    }
}
```
