### ISSUE TITLE
I'd like the option to remove the fingerprint from the generated sprite

### ISSUE THREAD

**Issue by philipwalton** [Compass/compass#1038]
I'm using Rails, which automatically adds cache-busting fingerprints to asset files when deploying to production. As a result, the auto-fingerprinting Compass does on the generated sprite isn't helpful and is actually an inconvenience. 

The problem is compounded because I'm using version control.

Basically, the first version of the file gets generated and I add it to my VCS. Then, once I make changes, the second version overwrites the first version but uses a different filename, so the original version is lost. I have to add/remove both files on every change

A much better workflow would be to generate a file and just overwrite it when there are changes. The VCS would detect the changes (like it does for any file) and you could easily revert to an old version if needed.

It would be great if there were a config option for the fingerprint. It would default to `on` but could be easily turned off if you didn't want it.

**Comment by krisbulman** [comment]
add this to your config

asset_cache_buster :none

**Comment by scottdavis** [comment]
If you remove the fingerprint that compass adds you lose the ability to know when the sprite needs to be regenerated. Our hand are tied on this since sprockets currently has no way to ask for a hash for a group of files.

You can use a the callbacks that compass has for sprites if you want to automate removing from version control but, honestly best practice is to not check in the generated sprites but there source files.

**Comment by philipwalton** [comment]
@scottdavis I'm not sure I follow. Couldn't you just compare the modification time of the sprite and its source files? If any of the source files has been modified more recently than the sprite, just replace it. Why do you need a hash of the group of files?

**Comment by scottdavis** [comment]
Sure but where do I store that information between compiles. That is exactly what the compass hash is for

Also mtime isn't reliable

**Comment by scottdavis** [comment]
It's also important to remember compass working with rails is not the main goal of compass and we don't like making changes just to make rails integration more seamless. You are welcome to supply a patch with tests for us to review but, honestly something like this would be very low on my todo list
