### ISSUE TITLE
Heroku Support

### ISSUE THREAD

**Issue by yfeldblum** [Compass/compass#104]
Heroku is a PaaS provider whose interesting feature, in terms of compatibility with Compass, is that it mounts your Rails app on a read-only filesystem but mounts a read-write tmp directory within it. So that means that writing to tmp is ok, but writing anywhere else will raise. Additionally, Heroku will reboot your app every time you push new code.

Can there be an option for Compass to cache compiled CSS to somewhere within the tmp directory, and to serve files from that directory using Rack::Static? Additionally, can there be an option to compile once during application startup and then not watch for changes anymore (but again compile to the tmp dir and continue serving with Rack::Static)?

Because the easiest solution currently for Rails3 on Heroku is to use standalone rather than Rails project type, and to include compiled CSS in the repo rather than .gitignore-ing the compiled CSS.

**Comment by chriseppstein** [comment]
Compass and Sass have all the features they need to support a read-only file system. It seems you are unaware of them, so please contact the mailing list for support if a basic google query doesn't answer your question.

http://www.google.com/search?q=sass+heroku

**Comment by yfeldblum** [comment]
Chris, thanks for the response. There certainly is plenty of information out there. My feature request is for standard Compass configuration options, and documentation about them in the readme or wiki, to support deployment on read-only filesystems. I was hoping that Heroku deployment, which is currently more difficult and not on the "golden path", can be both easy and on the "golden path".

**Comment by chriseppstein** [comment]
It's a wiki, so please feel free to edit it and provide some useful information there. We're in the process of porting away from the wiki, but if you add it now, we'll make sure it gets moved. I don't see a need for official product support on our end.
