### ISSUE TITLE
Unprefixed linear gradient declarations are wrong.

### ISSUE THREAD

**Issue by cscott** [Compass/compass#1041]
As noted at https://developer.mozilla.org/en-US/docs/CSS/linear-gradient#History_of_the_syntax the meaning of the first (direction) parameter to a linear gradient declaration has changed for the unprefixed standardized form of the syntax.

In particular, there are two changes which compass currently fails to make:

a) the preferred 'native' syntax is "to left" not "left".  They are opposites, and should be parsed and interconverted.  For example, both (new-style):

``` scss
@include background(linear-gradient(to right, transparent, currentColor 100%));
```

and (old-style):

``` scss
@include background(linear-gradient(left, transparent, currentColor 100%));
```

should emit (note difference between prefixed versions and final line):

``` css
  background: -webkit-gradient(linear, 0% 50%, 100% 50%, color-stop(0%, transparent), color-stop(100%, currentColor));
  background: -webkit-linear-gradient(left, transparent, currentColor 100%);
  background: -moz-linear-gradient(left, transparent, currentColor 100%);
  background: -o-linear-gradient(left, transparent, currentColor 100%);
  background: linear-gradient(to right, transparent, currentColor 100%);
}
```

b) when using degree-based notation, the standardized form uses 0deg = north while the prefixed nonstandard form uses 0deg=east.  So if using degree-based direction, the degree needs to be rotated 90 degrees between the prefixed and unprefixed versions of the gradient.  This change is trickier, as it potentially introduces a backward incompatibility in compass, unless you're willing to stick with the "wrong" degree origin indefinitely.

**Comment by rdj** [comment]
See #965

**Comment by mirisuzanne** [comment]
This is a duplicate.
