### ISSUE TITLE
Cannot @extend sprite classes

### ISSUE THREAD

**Issue by ProLoser** [Compass/compass#1047]
Maybe I'm wrong, but I seem to be unable to @extend a sprite-generated class. I'm not using @media at all. Is this currently possible?

For `help.png` this is what I'm doing:

```
@import "compass/utilities";
$blue-spacing: 20px;
@import "../images/blue/*.png";
@include all-blue-sprites(true);


.help {
   @extend .blue-help;
}
```

**Comment by silvenon** [comment]
I did a quick test and it worked fine for me. Are you sure that is the correct class name?

**Comment by ProLoser** [comment]
I was wrong, I was stupid enough to forget to import the sprites into the file I was trying to extend in.
