### ISSUE TITLE
log() math function not working

### ISSUE THREAD

**Issue by lunelson** [Compass/compass#1049]
Just running a new install of compass today, testing math functions.
Everything I've tested so far works but the expression `log(5) * 1px` returns the following:

`Syntax error: Undefined operation: "log(5) times 1px".`

Others such as `pi()` or `pow(3,2)` are returning the expected output however

**Comment by scottdavis** [comment]
try `logarithm` i think log is a sass core function

**Comment by scottdavis** [comment]
verified http://compass-style.org/index/functions/

log is not a function of compass

**Comment by krisbulman** [comment]
Yet the docs state it as a math helper http://compass-style.org/reference/compass/helpers/math/

**Comment by scottdavis** [comment]
Seems the documentation is incorrect
