### ISSUE TITLE
[PATCH] Optional background image with gradients

### ISSUE THREAD

**Issue by will** [Compass/compass#105]
It's useful to give a background image in addition to the gradients, but there is no way to do this with compass currently without writing your own gradients

This is my proposed solution: http://github.com/will/compass/commit/aed94001504137419df430e0a852914deac9538a

Episode 11 of doctype shows why you'd want to do this, adding noise to gradients: http://doctype.tv/websql

**Comment by chriseppstein** [comment]
haven't forgot about this, but after the conversion to scss, this doesn't apply anymore so it'll have to wait till the next release.

**Comment by will** [comment]
I've updated it to use image_url, as ericam suggested, and put it back on what is currently your master. It's at http://github.com/will/compass/commit/4b6b49a78142a73f82eace817cf4cd535b1e4639

**Comment by chrisdrackett** [comment]
ah, I was just looking for this :)

**Comment by chriseppstein** [comment]
This will be in rc5.
