### ISSUE TITLE
Updated to OS X ML 10.8.2 and watch stopped working.

### ISSUE THREAD

**Issue by digerata** [Compass/compass#1052]
I am using rb-fsevent 0.9.2 and compass 0.12.2.  Compass starts up with no errors and waits for changes.  Making any changes and compass is silent.

Here is an example session:

[Mike@MikesBookPro eRaise] $ compass watch

> > > Compass is watching for changes. Press Ctrl-C to Stop.
> > > ^C
> > > [Mike@MikesBookPro eRaise] $ compass watch
> > > Change detected at 13:53:58 to: screen.sass
> > > overwrite css/screen.css 
> > > Compass is watching for changes. Press Ctrl-C to Stop.

I updated to 10.8.2 a couple days ago and this is the first I have noticed the problem.

I saw some references to guard/listen being a replacement?  I installed listen 0.5.3 and didn't see any change in behavior.

**Comment by scottdavis** [comment]
This is a known issue dup #732

**Comment by scottdavis** [comment]
try listen branch
