### ISSUE TITLE
CLI options docs

### ISSUE THREAD

**Issue by sindresorhus** [Compass/compass#1056]
Couldn't find any documentation of the CLI options.

https://github.com/chriseppstein/compass/blob/stable/lib/compass/exec/global_options_parser.rb
https://github.com/chriseppstein/compass/blob/stable/lib/compass/exec/project_options_parser.rb

**Comment by scottdavis** [comment]
its pretty much the worse pile of noodles on the planet. That entire section is do for a rewrite one rainy day

**Comment by sindresorhus** [comment]
Hope it's going to rain soon :p

**Comment by chriseppstein** [comment]
Like all good command lines, it it self documenting: `compass -h` or `compass <command> -h`
