### ISSUE TITLE
Compile error with phrase 'radial-gradient' as property value

### ISSUE THREAD

**Issue by ghost** [Compass/compass#1059]
I seem to have stumbled upon a strange bug that I can't figure out. Start with
the follow code: 

```
@mixin linear-gradient($a) {
  background-image: -webkit-linear-gradient($a);
  background-image:    -moz-linear-gradient($a);
  background-image:      -o-linear-gradient($a);
  background-image:     -ms-linear-gradient($a);
  background-image:         linear-gradient($a);
}
@mixin radial-gradient($a) {
  background-image: -webkit-radial-gradient($a);
  background-image:    -moz-radial-gradient($a);
  background-image:      -o-radial-gradient($a);
  background-image:     -ms-radial-gradient($a);
  background-image:         radial-gradient($a);
}

.foo { 
  @include linear-gradient((red, blue)); 
}
.bar { 
  @include radial-gradient((red, blue)); 
}
```

That along with all of my other mixins work just fine with the regular Sass
compiler. But, in trying to switch over to `compass watch`, I get an error
only on the radial-gradient mixin.

Given:

```
@mixin radial-gradient($a) {
  background-image: -webkit-radial-gradient($a);
  background-image:    -moz-radial-gradient($a);
  background-image:      -o-radial-gradient($a);
  background-image:     -ms-radial-gradient($a);
  background-image:         radial-gradient($a);
}
.bar { 
  @include radial-gradient((red, blue)); 
}
```

I get: 

```
error scss/style.scss (Line 6: wrong number of arguments (1 for 2) for `radial-gradient')
Sass::SyntaxError on line ["6"] of /path/to/project/style.scss: wrong number of arguments (1 for 2) for `radial-gradient'
```

If you comment out the last line which uses the unprefixed version, it works
fine. If you change the last, unprefixed version to something else (say
`-test-radial-gradient`), it works fine.  The `linear-gradient` mixin works
fine. It's as if it's seeing the `radial-gradient` _value_ as the
`radial-gradient` _mixin_. But, by that logic, I would assume it would do the
same for linear-gradient.  

By the way, this happens whether compass is imported or not. I _am_ new to Compass as opposed to plain old Sass, so I hope it's just something stupid that I'm missing. But, I'm stumped.
- Compass version: 0.12.2
- Sass version: 3.2.1

**Comment by scottdavis** [comment]
Why define your own gradient mixins when compass provides these for you at no cost?

**Comment by ghost** [comment]
I'll give them a shot. I had planned to anyway. This is just the result of me
dipping my toe in by trying my existing mixins for prefixes with the Compass
compiler instead of just Sass. I made them take just a single argument so I'm
just writing the same value I'd give to the standardized property rather than
having to remember new arguments and their order. I see that using gradients
within the background mixin seems to do this pretty well.  

I would still consider this a bug though given that this works fine:

```
@mixin linear-gradient($x) {
    background: linear-gradient($x);
}
.foo {
    @include linear-gradient( (red, blue) );
}
```

But, this throws an error that doesn't seem to make sense contextually:

```
@mixin radial-gradient($x) {
    background: radial-gradient($x);
}
.foo {
    @include radial-gradient( (red, blue) );
}
```

In case anybody cares…

**Comment by scottdavis** [comment]
you are going to run in to conflicts if your functions have the same name as compass functions and mixins
