### ISSUE TITLE
typo in font-face mixin example

### ISSUE THREAD

**Issue by rvr** [Compass/compass#106]
in the example code it has:
font-files("this.woff"...

it should be:
font_files("this.woff"... (underscore, not dash)

**Comment by chriseppstein** [comment]
grrr. In Sass 3 you can use dashes in place of underscores for ruby-defined functions. Sometimes I forget.

**Comment by rvr** [comment]
i know how it is. and i spotted the problem pretty quickly, since it didn't match the comments at the top of the file. but we have an intern trying to learn some of this stuff, and it was throwing him for a loop.

**Comment by chriseppstein** [comment]
the next release requires sass 3. So now I'm right. :P

**Comment by rvr** [comment]
ah, to have the power to alter reality by changing the source code.
