### ISSUE TITLE
Error using font-face mixin

### ISSUE THREAD

**Issue by ZorGleH** [Compass/compass#1061]
Hi, I'm trying to use the `font-face` mixins like this:

``` sass
+font-face("Bitstream Vera sans Mono", font-files("veramono-webfont.eot", "veramono-webfont.ttf", "veramono-webfont.svg"), true)
```

But it gives me this:

``` zsh
NoMethodError on line ["220"] of /home/gdubourg/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/gems/1.9.1/gems/compass-0.12.2/lib/compass/sass_extensions/functions/urls.rb: undefined method `[]' for true:TrueClass
```

Am I misusing it?
Thanks.

**Comment by mirisuzanne** [comment]
Yep. See (the docs)[http://compass-style.org/reference/compass/css3/font_face/#mixin-font-face]: "$eot is required by IE, and _is a relative location of the eot file_."

Don't list the eot file with the others, pull it out and list it where you have `true`.

**Comment by ZorGleH** [comment]
Thank you, that works great. Would be helpful to put it in the example page.

**Comment by rcstr** [comment]
i had the same problem! thanks

**Comment by tembamazingi** [comment]
Thank you!
