### ISSUE TITLE
image-url reverts back to css dir

### ISSUE THREAD

**Issue by muhammad-saleh** [Compass/compass#1063]
Dears,
Sometimes when I compile the files images are ok and next time they're all disappeared
later I found out that image-url returns the css path not the images one so I get broken http requests

And after I do a compile again images refers to the images directory again
ex: once they appear (compiled) background:url("../img/logo.png")
      and when broke they appear background:url("../css/logo.png")

OS: Microsoft Windows 8 RTM
Sass: Sass 3.2.1 (Media Mark)
Compass: Compass 0.12.2 (Alnilam)

**Comment by krisbulman** [comment]
This sounds like #989 although I can't confirm with Windows 8

**Comment by Anahkiasen** [comment]
Personally for me this happens when I compile from a partial. When I compile from the main stylsheet the paths are correct.

**Comment by muhammad-saleh** [comment]
Yes. after trying now it happens when I compile from a partial so I guess it's a duplicate of #989
