### ISSUE TITLE
column-break mixins undefined?

### ISSUE THREAD

**Issue by stoplion** [Compass/compass#1067]
I'm seeing the column-break-x mixins in the [docs](http://compass-style.org/reference/compass/css3/columns/), but am getting a `Undefined mixin 'column-break-before'` whenever I try to use them. All other column mixins work fine, just the columns-break-x ones..

**Comment by krisbulman** [comment]
I can confirm this as well, but only in --pre, 12.2 works. 

``` ruby
@import "compass/css3/columns";
h2.before {@include column-break(inside);}
```

returns 'Undefined mixin 'column-break'

**Comment by krisbulman** [comment]
This also works in stable.. so the question is, where does the pre version, 13.0 actually come from? (what commit)

Checking out the --pre version locally, the columns-break mixin doesn't even exist.

```
../gems/compass-0.13.alpha.0/frameworks/compass/stylesheets/compass/css3/_columns.scss
```

gist of this file: https://gist.github.com/3982299

Just checking the dates on the commits: --pre 13.0 alpha is actually older than 12.2 _facepalm_

0.12.2 June 24, 2012
0.13.alpha.0 May 6, 2012

**Comment by mirisuzanne** [comment]
Yes, that's true. The master branch has been updated more recently and includes all the changes in 0.12.2, but there has not been a new gem released.
