### ISSUE TITLE
Pre-release is older than stable release (12.2)

### ISSUE THREAD

**Issue by krisbulman** [Compass/compass#1068]
http://rubygems.org/gems/compass

 0.12.2 June 24, 2012
 0.13.alpha.0 May 6, 2012

This was affirmed after checking 12.2's _columns.scss, which contains column-break() mixins, but 13.alpha.0 doesn't. 

Can we get a new pre-release gem that's ahead of stable 12.2? 

**EDIT** Confirmed this is the case by @ericam in #1067

**Comment by mirisuzanne** [comment]
+1

**Comment by scottdavis** [comment]
Ill try to get another pre out this week

**Comment by francescopellegrini** [comment]
+1

**Comment by Saturate** [comment]
+1

**Comment by krisbulman** [comment]
Are there any blockers for the new pre-release that we could focus on specifically?

**Comment by mirisuzanne** [comment]
I'm not sure what's blocking, though #965 is pretty important to get out asap.

**Comment by scottdavis** [comment]
#965 is blocking atm. I can prob do a prerelease without it but its kind of a big deal.

**Comment by mirisuzanne** [comment]
I vote we get another alpha out right away, to get people off the current one, then bump again as soon as we have gradients fixed.

**Comment by krisbulman** [comment]
+1 for early release then bump when gradients are fixed, the existing new features are a must have.. also willing to bet there are a lot of people using existing pre which makes them even more outdated than 12.2 stable.

**Comment by krisbulman** [comment]
This is no longer the case since 0.13.alpha.2 released on Feb 7, 2013. Closing ticket.
