### ISSUE TITLE
relative_assets=true doesn't work when project_type = :standalone

### ISSUE THREAD

**Issue by spovich** [Compass/compass#107]
Using 0.10.0.rc1, all my image tags in the generated CSS files are like url("/images/site.jpg"), rather than url("images/site.jpg") with a config.rb like so:

<pre>
# Require any additional compass plugins here.
project_type = :stand_alone

# Set this to the root of your project when deployed:
http_path = "/"
sass_dir = "sass"
css_dir = "scripts"
javascripts_dir = "scripts"

output_style = :compact
line_comments = false

# To enable relative paths to assets via compass helper functions. Uncomment:
relative_assets = true
</pre>

**Comment by chriseppstein** [comment]
Not a bug, please contact the mailing list for support.
