### ISSUE TITLE
Add reset of Firefox's button padding

### ISSUE THREAD

**Issue by elado** [Compass/compass#1074]
Buttons in FF get extra inner padding, the solution is: 

```
button::-moz-focus-inner { padding:0; border:0; }
```

Can you please add it to the reset file?

**Comment by scottdavis** [comment]
We don't do any resting of buttons in our reset. We could consider optional form resets, but I think that's a larger feature request.

**Comment by elado** [comment]
I thought that the role of reset is to make things look the same on all browsers, am I wrong?
FF has this weird extra padding that makes buttons look different than on webkit and others.

**Comment by mirisuzanne** [comment]
Most form styles are different across browsers. Forms are a major pain, and there are different views on what should/shouldn't be reset about them. I would love to see a robust form-reset module, but it would have to be an optional addition, not a part of the default reset.

**Comment by krisbulman** [comment]
There's a project called formalize which aims to do normalize forms, but IMO there's a lot of cruft there. It does fix button inconsistencies though. 

https://github.com/nathansmith/formalize/blob/master/assets/css/_formalize.sass
