### ISSUE TITLE
Make 'master' branch default, link to 'stable' in readme

### ISSUE THREAD

**Issue by krisbulman** [Compass/compass#1078]
From what I understand, the reason Compass is set to 'stable' as the default branch is because the stable code is faster to browse that way. https://github.com/chriseppstein/compass/pull/1070#issuecomment-9983010

But since the [recommended patch process is against master](http://compass-style.org/help/tutorials/contributing/#patches), it's confusing for new contributors to patch against a non-default branch, causing a lot of pull requests from the stable branch. 

Perhaps this can be circumvented by setting the default branch to 'master' and linking to the 'stable' branch from the readme.md which appears on the front page of the repo anyway.

i.e. https://github.com/chriseppstein/compass/tree/stable

**Comment by silvenon** [comment]
:+1:

**Comment by krisbulman** [comment]
If this doesn't happen, or until it does happen. Perhaps the docs should be updated in this section http://compass-style.org/help/tutorials/contributing/#setting-up-git on how to switch to the master branch before writing any patches. 

Something like:

Download your git repo:

```
git clone git@github.com:your_username/compass.git
```

Set up a remote to the main repo:

```
cd compass
git remote add upstream git://github.com/chriseppstein/compass.git
```

Update your local copy from the remote repo:

```
git fetch upstream
```

Checkout the master branch:

```
git checkout -b master origin/master
```

Merge in any upstream changes:

```
git merge upstream/master
```

**Comment by chriseppstein** [comment]
IMO, the main issue here was how far apart stable and master were. I want bug fixes to be submitted against stable, and new features against master. I want people who are just browsing the code to browse the code they are  using and not the version they will use in the future. So want to keep stable as the default branch.
