### ISSUE TITLE
sprite-file returning absolute path

### ISSUE THREAD

**Issue by brewster1134** [Compass/compass#1079]
tjhe documentation for `sprite-file($map, $sprite)` says it returns a relative path, however for me it is returning an absolute path.

is there a different mixin available to get the relative path of the original sprite image in the image directory to be used with an img tag?

**Comment by scottdavis** [comment]
I think this is another case where the docs and the implemented code do not match 

https://github.com/chriseppstein/compass/blob/stable/lib/compass/sass_extensions/functions/sprites.rb#L82

**Comment by scottdavis** [comment]
I think what you need would be a `sprite-file-url` function but, this would create a problem because its assumed that you can store the raw sprite images outside of the scope of your images folder.

**Comment by scottdavis** [comment]
fixed by 8b964f2
