### ISSUE TITLE
How to use the latest Compass from git instead of the gem versions?

### ISSUE THREAD

**Issue by oskarrough** [Compass/compass#1085]
Hi,

How would you best install and run Compass on os x if you want to run the latest code directly pulled from Git instead of the less frequently updated gems?

**Comment by Anahkiasen** [comment]
Simply go to your `gems` folder, empty the compass folder, and git clone the repo with the same folder name.

**Comment by mirisuzanne** [comment]
The docs for [using Compass while under development](http://compass-style.org/help/tutorials/contributing/#running-local-code) list a few more options as well.

**Comment by oskarrough** [comment]
Thank you both.
@Anahkiasen, I tried doing that but that gives me the following error when trying to use Compass:

```
sudo git checkout master
Branch master set up to track remote branch master from origin.
Switched to a new branch 'master'
mosumgaard at localhost in /Library/Ruby/Gems/1.8/gems/compass on master*
$ compass --help
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- listen (LoadError)
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `require'
    from ./bin/../lib/compass/watcher/project_watcher.rb:1
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `require'
    from ./bin/../lib/compass/watcher.rb:3
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `require'
    from ./bin/../lib/compass.rb:33
    from ./bin/../lib/compass.rb:32:in `each'
    from ./bin/../lib/compass.rb:32
    from bin/compass:20:in `require'
    from bin/compass:20
    from bin/compass:8:in `fallback_load_path'
    from bin/compass:19

```

**Comment by mirisuzanne** [comment]
It sounds like you are missing some dependencies. That's the problem with the simple copy/paste method. I would check the doc instructions and build the gem locally or handle it through bundler.

**Comment by scottdavis** [comment]
You need to run `bundle` once checked out and use `bundle exec compass`. if you dont have the bundle command you need to run `bundle install bundler` then repeat the above.

**Comment by scottdavis** [comment]
that should install all dependencies. but i dont recomend checking compass out to you gem folder instead you should create a gemfile in your project using bundler. http://gembundler.com/
