### ISSUE TITLE
Compass Not Watching Partials

### ISSUE THREAD

**Issue by joshrainwater** [Compass/compass#1087]
Apologies if this has been mentioned already.

I'm having an issue with compass watch not actually watching my partials in the same directory as the main style.scss. It seems to be watching the folder itself, and will update properly when changes are made to the scss files, but it won't reimport the partials and recompile either with compass watch or compass compile. Maybe I'm missing something?

**Comment by scottdavis** [comment]
Try using the master branch this has been fix just not released yet.

**Comment by scamden** [comment]
i'm still seeing this issue in 0.12.2, is that not the most recent version?
