### ISSUE TITLE
NoMemoryError when PNG spritemap folder contains a JPEG-encoded file

### ISSUE THREAD

**Issue by paulkoegel** [Compass/compass#1088]
A designer sent me a .png file that was actually JPEG-encoded. although i hadn't included the file anywhere in the css (but had already copied it to the icons folder for my spritemap), i kept running into NoMemoryError on page loads in dev mode and on rake assets:precompile.
it would be good if the error message was a bit clearer. Thanks you!

**Comment by scottdavis** [comment]
Can you post a full stack trace please I can't easy catch the NoMemoryError since I'm guessing ruby crashes right after its thrown. Also, i want to point out that you can't just rename a JPEG file to .png and have it work.

**Comment by paulkoegel** [comment]
hey scott,

thanks for checking this out!
well aware that the spritemap can't handle various image formats, least of all JPEG. also know that renaming the file doesn't help since it was encoded in the wrong format (JPEG instead of PNG).

here's a link to the image that breaks things for me: [http://i.imgur.com/Y3pWE.jpg](http://i.imgur.com/Y3pWE.jpg)

when i run the file command on it i get:
$ file icon.png
=> JPEG image data, JFIF standard 1.02
(photoshop can't open it either b/c the file extension doesn't fit the file's format, after renaming it to .jpg it opens fine in PS).

### My system specs

OSX Mountain Lion
Ruby: 1.9.3-p194
Rbenv
Rails-3.2.2
compass-0.12.2
oily_png-1.0.2 (removing it from the Gemfile didn't help)
chunky_png-1.2.6

### Server log error

ActionView::Template::Error (failed to allocate memory)

should you need more info than the following, please let me know.

### Rake assets precompile

<pre>
$ rake assets:precompile --trace
[...irrelevant standard output]
** Invoke assets:precompile:all (first_time)
** Execute assets:precompile:all
** Invoke assets:precompile:primary (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Invoke tmp:cache:clear (first_time)
** Execute tmp:cache:clear
** Execute assets:precompile:primary
ruby(18989,0x7fff72f4b180) malloc: *** mmap(size=225111426413363200) failed (error code=12)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
ruby(18989,0x7fff72f4b180) malloc: *** mmap(size=225111426413363200) failed (error code=12)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
rake aborted!
failed to allocate memory
  (in /Users/paul/somag/repo/app/assets/stylesheets/demo.css.sass)
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/chunky_png-1.2.6/lib/chunky_png/canvas.rb:87:in `initialize'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/chunky_png-1.2.6/lib/chunky_png/canvas.rb:87:in `new'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/chunky_png-1.2.6/lib/chunky_png/canvas.rb:87:in `initialize'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/chunky_png-1.2.6/lib/chunky_png/image.rb:23:in `initialize'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.2/lib/compass/sass_extensions/sprites/engines/chunky_png_engine.rb:13:in `new'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.2/lib/compass/sass_extensions/sprites/engines/chunky_png_engine.rb:13:in `construct_sprite'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.2/lib/compass/sass_extensions/sprites/sprite_methods.rb:62:in `generate'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.2/lib/compass/sass_extensions/functions/sprites.rb:122:in `sprite_url'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.2/lib/compass/sass_extensions/sprites/sprite_map.rb:72:in `method_missing'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.2/lib/compass/sass_extensions/sprites/sprite_map.rb:63:in `to_s'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/script/list.rb:44:in `block in to_s'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/script/list.rb:44:in `map'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/script/list.rb:44:in `to_s'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/perform.rb:297:in `visit_prop'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/perform.rb:98:in `visit'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/base.rb:53:in `map'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/perform.rb:107:in `block in visit_children'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/perform.rb:119:in `with_environment'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/perform.rb:106:in `visit_children'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/perform.rb:318:in `visit_rule'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/perform.rb:98:in `visit'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/base.rb:53:in `map'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/perform.rb:107:in `block in visit_children'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/perform.rb:119:in `with_environment'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/perform.rb:106:in `visit_children'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/perform.rb:203:in `visit_if'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/perform.rb:98:in `visit'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/perform.rb:206:in `visit_if'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/perform.rb:98:in `visit'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/perform.rb:225:in `block in visit_import'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/perform.rb:225:in `map'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/perform.rb:225:in `visit_import'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/perform.rb:98:in `visit'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/base.rb:53:in `map'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/perform.rb:107:in `block in visit_children'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/perform.rb:119:in `with_environment'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/perform.rb:106:in `visit_children'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/perform.rb:126:in `visit_root'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/perform.rb:98:in `visit'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/visitors/perform.rb:7:in `visit'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/tree/root_node.rb:20:in `render'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/engine.rb:315:in `_render'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.2.2/lib/sass/engine.rb:262:in `render'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-rails-3.2.5/lib/sass/rails/template_handlers.rb:106:in `evaluate'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/tilt-1.3.3/lib/tilt/template.rb:76:in `render'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/context.rb:177:in `block in evaluate'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/context.rb:174:in `each'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/context.rb:174:in `evaluate'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/processed_asset.rb:12:in `initialize'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/base.rb:241:in `new'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/base.rb:241:in `block in build_asset'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/base.rb:262:in `circular_call_protection'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/base.rb:240:in `build_asset'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/index.rb:89:in `block in build_asset'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/caching.rb:19:in `cache_asset'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/index.rb:88:in `build_asset'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/base.rb:163:in `find_asset'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/index.rb:56:in `find_asset'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/bundled_asset.rb:16:in `initialize'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/base.rb:244:in `new'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/base.rb:244:in `build_asset'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/index.rb:89:in `block in build_asset'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/caching.rb:19:in `cache_asset'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/index.rb:88:in `build_asset'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/base.rb:163:in `find_asset'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/index.rb:56:in `find_asset'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/actionpack-3.2.2/lib/sprockets/static_compiler.rb:20:in `block in compile'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/base.rb:212:in `block in each_logical_path'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/base.rb:200:in `block (2 levels) in each_file'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/base.rb:190:in `each'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/base.rb:190:in `each_entry'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/base.rb:198:in `block in each_file'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/base.rb:197:in `each'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/base.rb:197:in `each_file'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/base.rb:210:in `each_logical_path'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/actionpack-3.2.2/lib/sprockets/static_compiler.rb:18:in `compile'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/actionpack-3.2.2/lib/sprockets/assets.rake:56:in `internal_precompile'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/actionpack-3.2.2/lib/sprockets/assets.rake:70:in `block (3 levels) in <top (required)>'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/task.rb:205:in `call'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/task.rb:205:in `block in execute'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/task.rb:200:in `each'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/task.rb:200:in `execute'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/task.rb:158:in `block in invoke_with_call_chain'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/task.rb:144:in `invoke'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/actionpack-3.2.2/lib/sprockets/assets.rake:60:in `block (3 levels) in <top (required)>'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/task.rb:205:in `call'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/task.rb:205:in `block in execute'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/task.rb:200:in `each'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/task.rb:200:in `execute'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/task.rb:158:in `block in invoke_with_call_chain'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/task.rb:144:in `invoke'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/application.rb:116:in `invoke_task'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/application.rb:94:in `block (2 levels) in top_level'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/application.rb:94:in `each'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/application.rb:94:in `block in top_level'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/application.rb:88:in `top_level'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/application.rb:66:in `block in run'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/application.rb:63:in `run'
/Users/paul/.rbenv/versions/1.9.3-p194/bin/rake:32:in `<main>'
Tasks: TOP => assets:precompile:primary
rake aborted!
Command failed with status (1): [/Users/paul/.rbenv/versions/1.9.3-p194/bin...]
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/file_utils.rb:53:in `block in create_shell_runner'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/file_utils.rb:45:in `call'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/file_utils.rb:45:in `sh'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/file_utils_ext.rb:39:in `sh'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/file_utils.rb:80:in `ruby'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/file_utils_ext.rb:39:in `ruby'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/actionpack-3.2.2/lib/sprockets/assets.rake:12:in `ruby_rake_task'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/actionpack-3.2.2/lib/sprockets/assets.rake:21:in `invoke_or_reboot_rake_task'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/actionpack-3.2.2/lib/sprockets/assets.rake:29:in `block (2 levels) in <top (required)>'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/task.rb:205:in `call'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/task.rb:205:in `block in execute'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/task.rb:200:in `each'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/task.rb:200:in `execute'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/task.rb:158:in `block in invoke_with_call_chain'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/task.rb:144:in `invoke'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/application.rb:116:in `invoke_task'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/application.rb:94:in `block (2 levels) in top_level'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/application.rb:94:in `each'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/application.rb:94:in `block in top_level'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/application.rb:88:in `top_level'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/application.rb:66:in `block in run'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling'
/Users/paul/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rake/application.rb:63:in `run'
/Users/paul/.rbenv/versions/1.9.3-p194/bin/rake:32:in `<main>'
Tasks: TOP => assets:precompile
</pre>

**Comment by scottdavis** [comment]
@wvanbergen is there a reason why this wouldn't be throwing the `ChunkyPNG::SignatureMismatch` i catch in the engine class?

https://github.com/chriseppstein/compass/blob/master/lib/compass/sass_extensions/sprites/engines/chunky_png_engine.rb#L17

**Comment by wvanbergen** [comment]
I tested the file on imgur with the latest version of ChunkyPNG using this script:

``` ruby
require 'chunky_png'
ChunkyPNG::Image.from_file('./test.png')
```

And I get the expected error message:

```
/Users/willem/Code/chunky_png/lib/chunky_png/datastream.rb:102:in `verify_signature!': PNG signature not found! (ChunkyPNG::SignatureMismatch)
    from /Users/willem/Code/chunky_png/lib/chunky_png/datastream.rb:74:in `from_io'
    from /Users/willem/Code/chunky_png/lib/chunky_png/datastream.rb:66:in `block in from_file'
    from /Users/willem/Code/chunky_png/lib/chunky_png/datastream.rb:66:in `open'
    from /Users/willem/Code/chunky_png/lib/chunky_png/datastream.rb:66:in `from_file'
    from /Users/willem/Code/chunky_png/lib/chunky_png/canvas/png_decoding.rb:53:in `from_file'
    from ./test.rb:4:in `<main>'
```

So I am not quite sure what is going on here.

**Comment by scottdavis** [comment]
Im not really sure we can do to solve this so closing it for now.
