### ISSUE TITLE
Inconsistent directory separator usage (sprite_load_path)

### ISSUE THREAD

**Issue by vargabalazs** [Compass/compass#1089]
I use win7.

Some config params is accept \ for directory separator, but sprite_load_path does not allow it.

Example:
images_dir = "site\public_download\images"

I use Compass v0.13.alpha.0

Allowed usage:
sprite_load_path = ['site/public_download/images']

Disallowed usage:
sprite_load_path = ['site\public_download\images']

Error text:
No files were found in the load path matching "icons/*.png". Your current load paths are: site\public_download\images

**Comment by scottdavis** [comment]
Can you try using the latest master branch I'm pretty sure this is already fixed
