### ISSUE TITLE
min-height typo

### ISSUE THREAD

**Issue by kolya-ay** [Compass/compass#109]
In file compass/utilities/general/_min.sass must be:

```
=hacked-minimum(!property, !value)
    min-#{!property}= !value
    // !value is for IE. Reverse order
    +bang-hack(!property, "auto", !value)
```

Also:
- Do you really think, that min-width hack works for every browser?
- Consider to add import compass/utilities/general/_min.sass to compass/utilities/_general.sass

**Comment by chriseppstein** [comment]
I think this was mostly fixed already but please verify in the next release.

If it doesn't work, please file a bug with the details of what browser it doesn't work in.

I have added this file to be imported by general.scss.
