### ISSUE TITLE
width/min-width overriding with blueprint/liquid.sss

### ISSUE THREAD

**Issue by mjonuschat** [Compass/compass#110]
The current blueprint/_liquid.sass doesn't allow to override the width und min-width and push/pull calculations.

I send a pull request, the fix is in commit  329107c447cb9f3ebdeb5f4616d781abf7510684 in my fork.

**Comment by chriseppstein** [comment]
[Blueprint] Allow liquid grid constants to be overridden. Closed by ec681c87a3de49a752a37e87dbc5e08c8867833a.
