### ISSUE TITLE
$sprite-spacing affects sprite-position() calculations

### ISSUE THREAD

**Issue by wootfox** [Compass/compass#1103]
I'm having a hard time finding out if anyone else has this issue...

I'm using $sprite-spacing in conjunction with sprite-position($map, $sprite, [$offset-x], [$offset-y]).

The issue is that sprite-position() returns the position for the _original_ image in the sprite. However, $sprite-spacing adds transparent space above and below each image before it gets added to the sprite image.

So now all of the sprite-position() calculations are incorrect (with or without the $offset-x/y values) as each images height in the sprite is now ($sprite-spacing + the original image height + $sprite-spacing).

I feel like the sprite-position() function should take $sprite-spacing into account when doing it's calculations.

**Comment by wootfox** [comment]
So no-one else is having this issue?

**Comment by Saturate** [comment]
I might have had this problem, but I am not sure. A code example would be great.

**Comment by wootfox** [comment]
I define spacing for a sprite using `$<map>-spacing`
e.g. `$foo-spacing: 10px;`

Then I'm using this function to generate the code for my sprites:

``` sass
// Fix for compass issue with @extend being used inside @media
// From: https://github.com/nex3/sass/issues/456
@mixin get-sprite($map, $sprite, $sprite-map-url, $offset-x, $offset-y) {
  $repeat: no-repeat;
  $sprite-map: $sprite-map-url;

  // http://compass-style.org/reference/compass/helpers/sprites/#sprite-file
  $sprite-image: sprite-file($map, $sprite);

  // http://compass-style.org/reference/compass/helpers/sprites/#sprite-url
  //$sprite-map: sprite-url($map);

  // http://compass-style.org/reference/compass/helpers/sprites/#sprite-position
  $sprite-position: sprite-position($map, $sprite, $offset-x, $offset-y);

  // Outputs background
  background: $sprite-map $sprite-position $repeat;
}
```

The problem is that the `$sprite-position` calculations don't include the extra spacing added by `$<map>-spacing`

Does that make more sense?

**Comment by aworkz** [comment]
Yes, having the same problem. 
This was my issue:

```
$sprite-mysprite: sprite-map("mysprite/*.png");
$mysprite-spacing: 10px;
```

`@include mysprite-sprite(image);` would return `background-position: 0 -401px;`

`background-position: sprite-position($sprite-mysprite, image, 0, 0);` would return `background-position: 0 -331px;`

Looks like a problem calculating the offset value.

**Comment by briantully** [comment]
same issue here. is there any workaround for this or is $sprite-spacing simply unusable at this point?

**Comment by scottdavis** [comment]
Do me a favor make me an example of what you expect to work, the expected outcome, and the outcome that is currently being generated. Bonus points if i can look at it in a browser also

**Comment by wootfox** [comment]
@scottdavis I'll have a go this weekend and get back to you.

**Comment by dlim-dlim** [comment]
@wootfox @aworkz @briantully When you define the variable for sprite-map, in addition to passing in your *.png path, also try passing in the variable $spacing along with your spacing value as a 2nd param like so:

$icons-spacing: 5px;
$icons-sprite: sprite-map("icons/*.png", $spacing: 5px);

**Comment by aworkz** [comment]
Worked great, thanks!
Is this how it's intended to be used or is it a workaround?
Either way it saves me the trouble every time I add/remove an image in the sprite. :smile: 

Btw, I actually used the variable instead of repeating the value:

``` scss
$icons-spacing : 10px;
$icons-sprite  : sprite-map("icons/*.png", $spacing: $icons-spacing);
```

**Comment by dlim-dlim** [comment]
Even better. Yeah, I found myself in the same position. Haven't seen this explicitly mentioned in the official Compass Sprite docs but noticed this implementation after much browsing on the web and lots of trial and error.

**Comment by briantully** [comment]
Thank you d-lim and aworkz!

**Comment by wootfox** [comment]
So finally had some time to look into this again and doing what @aworkz (via @d-lim) suggested works.

Thanks all!
