### ISSUE TITLE
compass watch not working anymore on master

### ISSUE THREAD

**Issue by Anahkiasen** [Compass/compass#1105]
For some reason since the Listen branch was merged on master I can't seem to make `compass watch` work. This happens both at home on Windows 7 and at work on Mac OS X. In both environments I have the Listen gem installed, latest.

Compass compiles fine, it even compiles when I first startup `watch` if no files are found but from there it doesn't actually _watch_ per se. If I change something after that, Compass doesn't react.

Problem is it doesn't show any error or anything. Just, it doesn't see my changes.

**Comment by scottdavis** [comment]
Mac OS X version?

**Comment by Anahkiasen** [comment]
10.7.5

**Comment by scottdavis** [comment]
@ericam is it still working for you?

**Comment by mirisuzanne** [comment]
Yes, on 10.8.2

**Comment by silvenon** [comment]
I have the same problem. I'm on Ubuntu 12.10.

**Comment by emilbayes** [comment]
I have the same problem, I'm on OS X 10.8.2

**Comment by scottdavis** [comment]
Is this still an issue?

**Comment by Anahkiasen** [comment]
I don't know I'd have to try again. I stopped using the dev version from Compass because I had problems with the version of Sass it requires (besically I have Sass `--pre` and Compass doesn't recognizes it) so I just use stable with the `framework` folder from the `master` repo manually copied.
I'll try again.

**Comment by DavidOliver** [comment]
Same problem for me now that I've updated from an older compass 0.13.alpha to 0.13.alpha.2 (Ubuntu 10.10).

Using `compass watch --trace` (adding the trace option) seems to fix it for me.

**Comment by DavidOliver** [comment]
Correction: it's not the `--trace` option that fixes it for me, but leaving off the `.`

`compass watch .` doesn't work.

`compass watch` does work.

**Comment by Lisaj** [comment]
I have same problem on windows 7. Star compass watch with path not work.
Using compass 0.13.alpha.2

**Comment by scottdavis** [comment]
@Lisaj can you give me the ruby version you are using

**Comment by Lisaj** [comment]
I use ruby 1.9.3.

**Comment by scottdavis** [comment]
Are all of you trying to run `compass watch .` ?

**Comment by Lisaj** [comment]
Run "compass watch ." not work for me. I must run "compass watch"
I have same problem on windows 7 and 8.

**Comment by scottdavis** [comment]
why are you trying to run `compass watch .` out of curiosity?

**Comment by DavidOliver** [comment]
In my case, it was just what I'd always done and it worked before I updated. I see the Help page does not have the `.`.

**Comment by scottdavis** [comment]
regardless should be fixed in the 0.13.alpha.4
