### ISSUE TITLE
Blueprint constants stay at default values even when grid values are customized

### ISSUE THREAD

**Issue by dlo** [Compass/compass#1109]
`$blueprint-grid-outer-width` and `$blueprint-container-size` are still set to the default values of 40px and 950px, respectively, even when customizing the grid system.

I have

``` sass
@import "blueprint/grid";
$blueprint-grid-width: 50px;
$blueprint-grid-margin: 30px;
$blueprint-grid-columns: 12;
```

I would expect `$blueprint-grid-outer-width` to be 80 and `$blueprint-container-size` to be 930.

**Comment by boriskaiser** [comment]
Set variables always before importing.

``` ruby
$blueprint-grid-width: 50px;
$blueprint-grid-margin: 30px;
$blueprint-grid-columns: 12;
@import "blueprint/grid";
```

**Comment by dlo** [comment]
Aha! Thanks. :thumbsup:
