### ISSUE TITLE
Enumerate function outputting strange strings [v0.10.0.rc2 and SCSS]

### ISSUE THREAD

**Issue by aaronrussell-x** [Compass/compass#111]
Given this:
    #{enumerate(".grid", 1, $cols, "_")} {@include grid_unit_base}

I would expect:
    .grid_1, .grid_2, .grid_3 #etc...

However, it is returning:
    .grid"_"1, .grid"_"2, .grid"_"3, #etc...

In addition, I have tried:
    #{enumerate(".grid", 1, $cols, _)} {@include grid_unit_base}

Which returns:
    .grid_1, .grid_2, .grid_3, #etc...

I'm not sure if this is an issue with the enumerate function or something to do with SASS's handling of strings, but thought I'd raise it here first.

**Comment by chriseppstein** [comment]
I'll investigate tonight. Thanks. Once `@extend` is added to sass for sass 3, we won't even need this function anymore.

**Comment by nex3** [comment]
Chris: Make sure to use `#value` when getting at the value of a SassScript string in a function. `#to_s` depends on the quotedness.

Aaron: As a short-term workaround, you can use `unquote("_")` in place of `"_"`.

**Comment by chriseppstein** [comment]
Thanks nathan, I'll get that fixed asap.

**Comment by chriseppstein** [comment]
fixed.
