### ISSUE TITLE
Compass doesn't detect changes behind symbolic links

### ISSUE THREAD

**Issue by mgol** [Compass/compass#1110]
My config is that I have the `styles` folder within which I have a symlink named `other` to a directory containing another `main.scss`. In my `styles/main.scss` file I have `@import other/main.scss`. It doesn't matter if I invoke watch using:

```
$ compass watch --trace .
```

or:

```
$ compass watch --trace styles/main.scss styles/other/main.scss
```

changes in the second file are not detected.
My `config.rb` file:

```
http_path = "/"
css_dir = "styles"
sass_dir = "styles"
images_dir = "static/img"
javascripts_dir = "."
fonts_dir = "static/fonts"
output_style = :expanded
relative_assets = false
```

I use OS X 10.8.2, my compass version is 0.12.2.

**Comment by mgol** [comment]
This seems similar to a SASS issue: https://github.com/nex3/sass/issues/17

**Comment by scottdavis** [comment]
try the latest master

**Comment by nex3** [comment]
I believe this is caused by guard/listen#71.

**Comment by scottdavis** [comment]
Yep this is caused by listen
