### ISSUE TITLE
compass does not parse /

### ISSUE THREAD

**Issue by samccone** [Compass/compass#1111]
try 10/5px ... it is rendering 10/5px

works fine in interactive mode... bombs on watch 

Compass 0.12.1 (Alnilam)
osx 10.8.1

**Comment by Anahkiasen** [comment]
You need to do `10 / 5px` if I recall correctly.

**Comment by samccone** [comment]
@Anahkiasen I tried that also, still is bombing

**Comment by ry5n** [comment]
Try surrounding the expression in parentheses. See http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#division-and-slash

If I had to guess why it works in interactive mode, it would be because it's not in a `property: value` declaration there.

**Comment by scottdavis** [comment]
Also just for future reference any parsing error you receive is not compass
issue it's a sass issue. Compass is a library for sass.

**Comment by samccone** [comment]
@ry5n yup that is it, thanks :dancer:
