### ISSUE TITLE
"Grouped" sprites within sprite-map (aka, vertical & horizontal sprites within same map)

### ISSUE THREAD

**Issue by ghost** [Compass/compass#1113]
First off, thank you IMMENSELY for the work you guys have put into this awesome tool.  I am a compass evangelist and will continue to be until you create something cooler.

So in working with sprites, I've found cases where it would be helpful to group similar icons in a single horizontal row within a vertically-generated sprite map.

Example:  You've got 16px by 16px icons for Facebook, Linkedin & Twitter.  For the Facebook icon, you have an icon for a hover state that would be logical to place horizontally-adjacent to the basic icon.  It would look like this:

[FB]  [FB]
[LI]
[TW]

My thought was that you could reference icons into "groups" that would automatically be generated perpendicular to the direction your sprite map is generated.

Thanks for your consideration guys!

**Comment by scottdavis** [comment]
You could create a custom layout class to do this.  

https://github.com/chriseppstein/compass/tree/master/lib/compass/sass_extensions/sprites/layout
