### ISSUE TITLE
Vertical align in inline-block mixin 

### ISSUE THREAD

**Issue by kierzniak** [Compass/compass#1114]
Why the property $alignmen from inline-block mixin is not assigned to vertical-align in $legacy-support-for-ie block?

```
@mixin inline-block($alignment: $inline-block-alignment) {
  @if $legacy-support-for-mozilla {
    display: -moz-inline-stack; }
  display: inline-block;
  @if $alignment and $alignment != none {
    vertical-align: $alignment; }
  @if $legacy-support-for-ie {
    *vertical-align: auto;
    zoom: 1;
    *display: inline; } 
}
```

**Comment by mirisuzanne** [comment]
Then it would appear only when IE support is turned on. this way it appears for any browser. Unless there is a reason it should only be used with IE, the current way is correct.

**Comment by shaneafsar** [comment]
However, when legacy support is turned on, doesn't `*vertical-align: auto` always trump the vertical-align declaration for IE7 and below (since the IE hack occurs after the "alignment" block)?
