### ISSUE TITLE
Bypass Sprite Generation

### ISSUE THREAD

**Issue by isoceles** [Compass/compass#1117]
Is there a way to bypass sprite generation in the config file? My compiles are taking 5+ mins and it has slowed down my productivity so much that I'd like to just disable it. I'm surprised it generates them on every save. Shouldn't it only regenerate them if there was a change or an added image? Any help would be appreciated.

**Comment by oskarrough** [comment]
+1 - installing oily_png didn't help much for me.

**Comment by scottdavis** [comment]
which version of compass are you using this issue should be fixed in the current master branch

**Comment by isoceles** [comment]
compass (0.12.2) and I also installed oily_png

**Comment by piouPiouM** [comment]
Do you use CodeKit?
I ask this question because it is frequently involved, with the issue https://github.com/bdkjones/CodeKit/issues/297 for example.

**Comment by isoceles** [comment]
Yes. I do use CodeKit and I actually posted on that thread already.  bdkjones said I can add a line to my Compass config.rb file that bypasses the sprite generation, but I can;t seem to find that line of code.

**Comment by piouPiouM** [comment]
@isoceles oh, I had not seen your comment, sorry!
I thought CodeKit because I have colleagues who are in the same situation (whereas everything works when they use the shell).

**Comment by isoceles** [comment]
I just wanted to see if anyone knows of a way to disable this? The Codekit creator said  "You can add a line to your Compass config.rb file that bypasses the sprite generation." which you can find on this thread https://github.com/bdkjones/CodeKit/issues/297

 I have yet to find this in the documentation anywhere.

**Comment by seafoox** [comment]
I've tried to add the following line in my config.rb file, but doesn't change anything: it continus to use sprite assets.

``` ruby
environment = :development 
```

@scottdavis can you please share with us the how to do to bypass the sprite generation during the development ?

**Comment by scottdavis** [comment]
If you are using compass (0.12.2) you will need to upgrade for this to work properly. Compass does not regenerate a sprite unless its signature changes.

https://github.com/chriseppstein/compass/blob/stable/lib/compass/sass_extensions/sprites/sprite_methods.rb#L79-L81

If you are having this issue with Codekit it is probably related to the way they are calling compass and they should fix the issue on their end.
