### ISSUE TITLE
Variables cannot be changed from within a for loop

### ISSUE THREAD

**Issue by chrisinajar** [Compass/compass#1118]
If you define a variable in a function, you cannot change it from within a for loop. Example code is below.

```
@mixin test-mixin(val) {
  left: test-function(val);
}

@function test-function($var) {
  $inner-var: "Wrong!";

  @for $i from 1 through 1 {
    $inner-var: "It worked!";
  }

  @return $inner-var;
}


body {
  @include test-mixin('woot');
}
```

If i replace the line inside the for loop with a return statement then the correct value appears, so I know the loop is running.

**Comment by mirisuzanne** [comment]
This is an issue for [Sass](https://github.com/nex3/sass), not Compass.

**Comment by chrisinajar** [comment]
Oops, I had this and the phpsass report open in tabs, clicked on the wrong one. Sorry about that!
