### ISSUE TITLE
Feature Request: Spritesheet output filename/disable generated hash

### ISSUE THREAD

**Issue by mrphilipandrews** [Compass/compass#1121]
It would be useful to have a setting to specify the output filename of a generated spritesheet or a setting to disable the unique hash in the filename. 
I'm loading the spritesheet via javascript. Everytime I update a sprite I need to change the spritesheet url in the js file which is really annoying.

**Comment by mrzmyr** [comment]
you can use the callback `on_stylesheet_saved` to rename the file:

``` ruby
on_sprite_saved do |filename|
    if File.exists?(filename)
        FileUtils.mv filename, filename.gsub(%r{-s[a-z0-9]{10}\.png$}, '-sprite.png')
    end
end
```

But i guess it would be a good idea to have such like that in the config file.

**Comment by scottdavis** [comment]
If you remove the hash the sprite will regenerate every time you compile. What I recommend is use a callback and **copy** the file to the desired static name so that you will not have long compile times.
