### ISSUE TITLE
background-clip mixin doesn't support the "text" option in rc3

### ISSUE THREAD

**Issue by tdreyno** [Compass/compass#113]
I'm building some mixins to accomplish this effect:
http://trentwalton.com/2010/04/06/css3-background-clip-font-face/

Unfortunately this only works in Webkit right now, so if that's an issue, I understand.

Here's a patch:
http://github.com/tdreyno/compass/commit/f036a00a519754b942c63e5879d68d0b88047d44

**Comment by chriseppstein** [comment]
I prefer to keep things that only work in 1 browser engine out. There's very little win over doing it yourself. Once we have broader support or it's in the spec. we can add it.
