### ISSUE TITLE
File to import not found or unreadable: blueprint

### ISSUE THREAD

**Issue by solars** [Compass/compass#1130]
I switched my rails 3.1 app to rails 3.2, using compass-rails
This is in my application.css.scss: https://gist.github.com/ce651b0b42aa35e2ccce

Now when I hit a page, I get:

Syntax Error: File to import not found or unreadable: blueprint
Load path: <...>/app/assets/stylesheets

How can I solve that?

**Comment by Anahkiasen** [comment]
Blueprint is not part of Compass anymore.

**Comment by solars** [comment]
I think the docs don't mention this then?

How should I install it in this case? Do I have to completely rewrite the layout as I did it through compass using blueprint?

**Comment by Anahkiasen** [comment]
Well you should be able to install it via [the gem](http://rubygems.org/gems/blueprint-rails) no ?

**Comment by solars** [comment]
yes, but right now I used all the variables etc that compass has set up (http://compass-style.org/reference/blueprint/grid/) so I have to completely rewrite everything I think

**Comment by mirisuzanne** [comment]
The Blueprint Compass module still exists, it has just been moved out of the core into a gem of it's own: http://compass-blueprint.org/
