### ISSUE TITLE
Column break related mixins have the incorrect name

### ISSUE THREAD

**Issue by cimmanon** [Compass/compass#1136]
The mixins Compass provides to specify column breaks for the Multi-column layout module (columns) uses the incorrect property name:
- `column-break-before` should be `break-before`
- `column-break-inside` should be `break-inside`
- `column-break-after` should be `break-after`

The specification lists the property name change occurred on December 17, 2009 (see: http://www.w3.org/TR/css3-multicol/#column-breaks)

Would providing both the older and current property name be appropriate?  Or should the old property name be dropped all together?

**Comment by mirisuzanne** [comment]
This has already been fixed in the master branch by f2e65c4c6 among others.
