### ISSUE TITLE
compass oily_png not working with ruby 1.8.7 or 1.9.3

### ISSUE THREAD

**Issue by philipbeel** [Compass/compass#1142]
compass throws an error when trying to run with the following setup:

ruby (1.8.7 or 1.9.3)
compass (0.12.2)
oily_png (1.0.2)
chunky_png (1.2.6 or 1.2.7)

In the config.rb file I am calling:

require 'oily_png'
sprite_engine = :oily_png

This results in an error when running "compass watch project/"

NameError on line 21 of /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass/sass_extensions/sprites/sprite_methods.rb: (eval):1:in `init_engine': uninitialized constant Compass::SassExtensions::Sprites::OilyPngEngine

A similar ticket (https://github.com/chriseppstein/compass/issues/1006) was closed because the issue had been fixed in master. But when switching to this branch the project does not run at all, and throws different errors not related to oily_png

Is there anything I need to modify to make this work on the stable branch, or does this require a fix from the oil_png code?

**Comment by oskarrough** [comment]
As per [the documentation](http://compass-style.org/help/tutorials/spriting/) you shouldn't need to declare the presence of oily png. Does it work if you leave those two lines out?

**Comment by philipbeel** [comment]
When I run "compass watch project/ --time" I get no noticeable speed improvements. Based on these benchmarks: https://gist.github.com/611255 I thought it would make more of a difference.

**Comment by scottdavis** [comment]
This is wrong:

In the config.rb file I am calling:

``` ruby
require 'oily_png'
sprite_engine = :oily_png
```

oly_png is loaded automatically if it is available to require

https://github.com/chriseppstein/compass/blob/stable/lib/compass/sass_extensions/sprites/engines/chunky_png_engine.rb#L1-L5

You may also want to upgrade the compass version a lot of things have changed to make sprites much faster
