### ISSUE TITLE
Support for scss code formatting before conversion

### ISSUE THREAD

**Issue by tomgenoni** [Compass/compass#1143]
With multiple developers working on the same Sass codebase it would be nice if Compass provided a way to format the code of the saved .scss file before it was converted. Something like:

```
 watch "sass/*/**" on_file_save do
       sass-convert --from scss --to scss ...
 end
```

This would ensure consistent formatting.

**Comment by scottdavis** [comment]
you can do this yourself with callbacks http://compass-style.org/help/tutorials/configuration-reference/#callbacks
