### ISSUE TITLE
Getting error when using @include <map>-sprite(<spritename>) in Media Query

### ISSUE THREAD

**Issue by ezmiller** [Compass/compass#1147]
Hi I have some code using SASS/COMPASS that attempts to get the position of a sprite inside of a media query like so:

```
@import "icons/*.png";

.fb-link { 
    @include icons-sprite(facebook_icon);
    @include breakpoint(laptop) { @include icons-sprite(facebook_icon_desktop); }
    @include breakpoint(desktop) { background-position: icons-sprite-position(facebook_icon_desktop); }
}
```

Breakpoing is a mixin that looks like this: 

```
@mixin breakpoint($point) {
  @if $point == desktop {
    @media (min-width: 1600px) { @content; }
  }
  @else if $point == laptop {
    @media (min-width: 1280px) { @content; }
  }
  @else if $point == netbook {
    @media (max-width: 1024px)  { @content; }
  }
}
```

The error I am getting, that I am having a hard time understanding is as follows: 

> DEPRECATION WARNING on line 257 of icons/*.png:
>   @extending an outer selector from within @media is deprecated.
>   You may only @extend selectors within the same directive.
>   This will be an error in Sass 3.3.
>   It can only work once @extend is supported natively in the browser.

I find this language confusing because as far as I understand, I am not using an @extend; but also it is not clear to me why I should not be able to @extend inside of a media query, even if I were. Anyhelp would be great!!!

**Comment by scottdavis** [comment]
`You may only @extend selectors within the same directive.` 

its trying to extend a class outside of the `@media` selector which isn't possible. So what your trying to do isn't possible you will need to more the sprite import inside the `@media` selector if you what that to work.

**Comment by ezmiller** [comment]
@scottdavis thanks for the response. I am trying to understand what you said, and I think I get it. I guess what is happening is that the sprite import dumps out a bunch of classes which then my attempt to @include in the media query involves @extend-ing.  And for some reason that is not allowed?  Ok, so if that is the case, I am just wondering how the solution you suggested would work? Would it not end up creating a huge number of unnecessary and repetetive classes, the very thing that SASS is designed to avoid? What's the best practice way to achieve what I'm trying to do, which is basically to use COMPASS/SASS to manage sprites within a responsive design?

**Comment by micahgodbolt** [comment]
I have been trying to work on a solution to this problem as well. The issue is that the foldername-sprite mixin contains an extend which applies the actual background image to all of the sprite classes using that spritemap.

What I would like to see is an option to turn that extend off and rather just include the background property with the selector itself, in whatever directive it happens to be in.

The current solution is to either call the foldername-sprite mixin outside of any media query and then hide it until the media query that you need it (pretty annoying, but doable.). The other solution is to use the sprite() function which will output the proper background properties for whatever sprite-map and sprite you pass to it.

**Comment by scottdavis** [comment]
why not just reimport the sprite within the media query? it shouldn't slow anything down since its already generated.

**Comment by micahgodbolt** [comment]
@scottdavis is it possible to @import "sprites/*" from inside a media query? 

The solution I ended up choosing was to just overwrite the @include folder-sprites(spritename){ } mixin after calling @import "sprites/*" and rewrite it to just set the background property, rather than extending. Sure, it's a little more code, but it sure is simpler to implement.

**Comment by scottdavis** [comment]
I don't know why it wouldn't be possible.

**Comment by vladyn** [comment]
Can you please give a code example. I tried to do my imports within the media queries, but this error persist. 

In my case I have imported image, which takes advantages on Compass Sprites

**Comment by scottdavis** [comment]
are you putting 

``` scss
@import "icons/*.png";
```

inside a media query? can you post the code you are having errors with can't help if I'm blind :)

**Comment by vladyn** [comment]
@import "mac/_.png";
@import "mac2.0/_.png";

is my case

**Comment by scottdavis** [comment]
sorry what i ment was can you give me some runable sass example that recreates the problem. showing me the imports doesn't allow me to help you any.

**Comment by vladyn** [comment]
Beside these two rows I have further down in the code a lot of includes inside media queries like: 

``` javascript
@media (min-width:1025px) {
    button.back-btn {
        &:hover {
            background-color:none;
            @include mac-sprite('back-btn-sel');
        }
    }
    .mac-button:hover {
        @include background(radial-gradient(center center, color-stops($mac-button-hover-color-start, $mac-button-hover-color-end)));
    }
}
```

The first two lines, importing image obviously producing sprite name **mac-sprite**

**Comment by scottdavis** [comment]
you need todo your `@import` inside the media query also

**Comment by vladyn** [comment]
Yes, I see your point and after I did that for some reason I'm still getting this persistent error: 

```
error sass/app.scss (Line 176 of *.png: You may not @extend an outer selector from within @media.
```

...and this is weird as on this line I have nothing to do with any extends, includes or media queries.
