### ISSUE TITLE
Problem with font-face compilation

### ISSUE THREAD

**Issue by ccorman** [Compass/compass#1152]
Hello :) First, sorry if my english is bad, i am french.
Here is the problem: i write a font-face include in my scss file, like that:

@include font-face("Enhanced Dot Digital", font-files("font/enhanced_dot_digital.ttf"));

and then, when it compiles it, i got this in my css file:

@font-face {
  font-family: "Enhanced Dot Digital";
  src: url('///fonts/font/enhanced_dot_digital.ttf') format('truetype');
}

and the problem is that it's not the good path, for my font (which is font/enhanced_dot_digital.ttf), and i think that's why it's not working. But i can't take the '///fonts' off, and i don't know what's the origine of this. Can you help me please :/?

**Comment by scottdavis** [comment]
This kind of question would be better addressed on the google group http://groups.google.com/group/compass-users
