### ISSUE TITLE
provide a "random" function

### ISSUE THREAD

**Issue by lanterndev** [Compass/compass#1154]
I'm playing with css animations and realized it would be handy to be able to specify a random number within a certain range from sass. Would it make sense for compass to expose a `random` function for this use case?

**Comment by lanterndev** [comment]
Only just saw you added this. Thanks! Look forward to using it in the next release.

**Comment by scottdavis** [comment]
its in the pre-release `gem install compass --pre`

**Comment by lanterndev** [comment]
nice!
