### ISSUE TITLE
Omit units for zero values

### ISSUE THREAD

**Issue by nschonni** [Compass/compass#1157]
A zero value in CSS is the same no mater the units. 
This could improve the resulting stylesheet size
https://github.com/stubbornella/csslint/wiki/Disallow-units-for-zero-values

**Comment by scottdavis** [comment]
This would have to be done in sass and not compass.

**Comment by krisbulman** [comment]
moved to sass queue https://github.com/nex3/sass/issues/649

**Comment by nschonni** [comment]
Thanks you're probably right that it is better dealt with in the core, but I think some of the Compass defaults variables should be corrected too. Ex: `$default-box-shadow-v-offset: 0px !default;`

**Comment by scottdavis** [comment]
I would open another ticket that specifically states your last comment. You are correct they should be changed. The problem might be when it comes when you perform math functions and you need to specify a unit. 

example:
Setting `0px` creates a sass integer of `0` with the unit `px` allowing me to take that default and add to it without specifying a unit.

**Comment by nschonni** [comment]
Here are a few that don't involve variables and shouldn't affect any math operations.
Examples:
- [ ] https://github.com/chriseppstein/compass/blob/stable/examples/compass/src/compass.scss#L14
- [ ] https://github.com/chriseppstein/compass/blob/stable/examples/compass/src/compass.scss#L24
- [ ] https://github.com/chriseppstein/compass/blob/stable/examples/css3/src/main.scss#L108

Blueprint
- [ ] https://github.com/chriseppstein/compass/blob/stable/frameworks/blueprint/stylesheets/blueprint/_ie.scss#L45

Compass
- [ ] https://github.com/chriseppstein/compass/blob/stable/frameworks/compass/stylesheets/compass/typography/lists/_inline-list.scss#L6-L7
- [ ] https://github.com/chriseppstein/compass/blob/stable/frameworks/compass/stylesheets/compass/utilities/sprites/_sprite-img.scss#L49
- [ ] https://github.com/chriseppstein/compass/blob/stable/frameworks/compass/stylesheets/compass/utilities/sprites/_sprite-img.scss#L54
- [ ] https://github.com/chriseppstein/compass/blob/stable/frameworks/compass/stylesheets/compass/utilities/tables/_borders.scss#L18-L19
- [ ] https://github.com/chriseppstein/compass/blob/stable/frameworks/compass/stylesheets/compass/utilities/tables/_borders.scss#L22
- [ ] https://github.com/chriseppstein/compass/blob/stable/frameworks/compass/stylesheets/compass/utilities/tables/_borders.scss#L30
- [ ] https://github.com/chriseppstein/compass/blob/stable/frameworks/compass/stylesheets/compass/utilities/tables/_borders.scss#L33

**Comment by scottdavis** [comment]
Wow nice list

**Comment by nschonni** [comment]
I can do a PR, but what branch should it be against?
