### ISSUE TITLE
how to support ie6+ ?

### ISSUE THREAD

**Issue by freshlhy** [Compass/compass#1158]
i'am from China, Internet Explorer 6 usage is still about 20% in china, so i have to support it.  and i want to use compass with blueprint in rails, but i can't any instructions to config it, can anyone help me?  thanks a lot!

**Comment by scottdavis** [comment]
blueprint has moved to https://github.com/Compass/compass-blueprint. Also its better to ask these type of questions on our google group https://groups.google.com/forum/?fromgroups#!forum/compass-users.
