### ISSUE TITLE
compass watch [from master] fails to detect changes on Ubuntu

### ISSUE THREAD

**Issue by StanAngeloff** [Compass/compass#1159]
I've got an interesting case where a new project using Compass from [master](/chriseppstein/compass/commit/5204c8168a) fails to detect changes to `.scss` files on save.

For full reference, here is my [complete set up](https://gist.github.com/4706813). I invoke Compass using:

``` shell
$ vendor/.bin/compass watch 'assets/styles/'
>>> Compass is watching for changes. Press Ctrl-C to Stop.
```

To the best of my abilities, I have tracked this down to two places:
- `project_watcher.rb::create_sass_watchers(..)` creates two watchers using the following globs:
  
  ```
  ./*.s[ac]ss
  ./**/*.s[ac]ss
  ```
- `project_watcher.rb::listen_callback(..)` is fired immediately after saving a watched file, however the `files` list contains the updated paths relative to the project path, but without `./` in front. When each watcher is `match?`ed, the file is rejected as the glob failed.

Poor-man debugging attached:

```
$ vendor/.bin/compass watch 'assets/styles/'
[puts create_sass_watchers::filter = ] ./*.s[ac]ss
[puts create_sass_watchers::children = ] ./**/*.s[ac]ss
>>> Compass is watching for changes. Press Ctrl-C to Stop.
[puts listen_callback::files = ] default.scss
```

I am happy to provide more debugging information is needed.

**Comment by scottdavis** [comment]
I'm curious if this has todo with listen not being able to watch things outside of the current directory

**Comment by scottdavis** [comment]
I make a special case to verify that you arnt using an absolute path outside of the project
https://github.com/chriseppstein/compass/blob/master/lib/compass/watcher/watch.rb#L23-L25
but, i never take into account the relative `../../` so I'm guessing i need to detect this and not add it to the watch path

**Comment by scottdavis** [comment]
Maybe I'm confusing myself but im pretty sure 

`add_import_path '../../components/normalize.scss/'` has something todo with it

**Comment by StanAngeloff** [comment]
@scottdavis: I don't think the relative path in `add_import_path` has anything to do with it as it [gets filtered](https://github.com/chriseppstein/compass/blob/master/lib/compass/watcher/project_watcher.rb#L54) early on -- it is outside of the `project_path`. I can confirm commenting that line in `config.rb` does **not** help.

> I'm curious if this has todo with listen not being able to watch things outside of the current directory

Listen invokes the callback, but Compass' watchers don't accept the file as none of the globs match it -- so IMHO Listen is OK.

**Comment by scottdavis** [comment]
Guess I should install compass on my Ubuntu machine and take it for a spin. I hate these sort of bugs

**Comment by StanAngeloff** [comment]
In my limited knowledge, I'd say Compass needs to use the same technique of converting an absolute to relative path as seen in the [Listen project](https://github.com/guard/listen/blob/master/lib/listen/directory_record.rb#L193). At present Compass is using [`relative_path_from`](https://github.com/chriseppstein/compass/blob/master/lib/compass/watcher/project_watcher.rb#L55) which returns `.` for the current directory (whereas Listen strips it off).

**Comment by scottdavis** [comment]
give that a try

**Comment by StanAngeloff** [comment]
Mm, this is very odd, but it doesn't work quite as I hoped. Once `relative_to_base` is called, the returned path is empty as the base and the path are the same. Then when `File.join` is used to append the `SASS_FILTER`, it joins an empty path with a string using the `File::SEPARATOR`. So the result is an absolute path like `/*.s[ac]ss`.
That then confuses `Compass::Watcher::Watch.verify!` throwing `"Only paths relative to the project can be watched"`.

Perhaps a `File.join` shim can be used which would drop all `empty?` elements?

**Comment by scottdavis** [comment]
More importantly why are the paths the same?

**Comment by StanAngeloff** [comment]
I've [created a repository](https://github.com/StanAngeloff/compass-1159) which reproduces the issue. To try it out:

``` terminal
$ cd /tmp
$ git clone git://github.com/StanAngeloff/compass-1159.git
$ cd compass-1159
$ make install
  # Everything is installed locally via Bundler so
  # no worries your environment will get cluttered with unnecessary packages.
$ vendor/.bin/compass watch assets/styles
  Only paths relative to the project can be watched
```

I hope this helps. Let me know if I can do anything else to help.

**Comment by scottdavis** [comment]
Ok ill look into this in a bit

**Comment by scottdavis** [comment]
Talk about hard to write a test for .... but i think i got it fixed

**Comment by StanAngeloff** [comment]
Thank you Scott, that seems to have nailed it for my particular case. `compass watch` is now detecting changes properly.

There is an issue when I install the `rb-inofity` gem in the VM, but my guess is it has something to do with the Listen gem and not directly related to Compass. Reverting to polling seems to solve the issue for me. Not ideal, but would do for now.
