### ISSUE TITLE
CSS Gradients assume background-image use

### ISSUE THREAD

**Issue by chrisdrackett** [Compass/compass#116]
For webkit at least, gradients can be used for much more like border-image or list-style-image:

http://webkit.org/blog/175/introducing-css-gradients/

would be nice to have this in compass :)

**Comment by chriseppstein** [comment]
You've seen this much, I guess:
http://compass-style.org/docs/reference/compass/css3/gradient/

so you're asking to have compass support for the non-background uses, right?

There's no benefit to be had until at least two major rendering engines support it. Is there support for it beyond webkit?

**Comment by mirisuzanne** [comment]
Any gradient-supporting browser should (supposedly) take a gradient anywhere that an image is accepted. I'd love to see that tested.

**Comment by chriseppstein** [comment]
FYI: I'd like to hold off on new features like this until after v0.10.

**Comment by chrisdrackett** [comment]
This is also an issue if you want to use multiple backgrounds on a single element and one of those backgrounds is a gradient: http://github.com/chriseppstein/compass/issues/#issue/105

**Comment by mirisuzanne** [comment]
The issue looks the same, but the solutions in compass end up fairly different. I have in mind several ideas to this that should combine to give us the flexibility we need - including some new functions as well as adjustments to the mixins themselves. But as Chris said, implementation will have to wait til after the v0.10 release.

**Comment by mirisuzanne** [comment]
Ok, if we're going to start working on this, the goals should be as follows:
1. you can set an arbitrary (or large) number of gradients and/or other images.
2. they can be applied to any property that accepts images. That is:
   - background-image
   - border-image
   - list-style-image
   - content property
3. they can be set in any order, and should stack in the order they are set. (This is different from the current implementation that requests "gradient, image" and returns "image, gradient").

Not sure that we can hit them all perfectly, but it's good to have goals.

**Comment by chriseppstein** [comment]
@ericam. I have a plan. Consider it done.

**Comment by mirisuzanne** [comment]
You are a true hero of the people, Mr. Eppstein.

**Comment by chriseppstein** [comment]
It took more ruby than sass, but it's working: https://github.com/chriseppstein/compass/compare/ff375489f65f580ac0f2...a0f5b5a6aea307d
