### ISSUE TITLE
Dynamic imports?

### ISSUE THREAD

**Issue by NickHeiner** [Compass/compass#1167]
Is there any way to do dynamic imports as described in this StackOverflow question?

http://stackoverflow.com/questions/14782954/dynamic-imports-for-scss

**Comment by scottdavis** [comment]
No. Sass doesn't allow this.

For future reference questions like this are best asked on the google group

**Comment by NickHeiner** [comment]
Ok, good to know.

Would you be amenable to a PR implementing this?

**Comment by scottdavis** [comment]
You would have to open an issue with sass its a language limitation
