### ISSUE TITLE
Border-image support

### ISSUE THREAD

**Issue by chrisdrackett** [Compass/compass#117]
I didn't notice when writing my last ticket, but compass also doesn't seem to have—that I could find—support for border-image.

**Comment by chriseppstein** [comment]
on the css3-v2 branch

**Comment by chriseppstein** [comment]
or not.

**Comment by scottdavis** [comment]
done: 3d23b36f6397bd01f0c8a6bf14122730aa5e86b3

**Comment by darkwoods-** [comment]
IE is a pain in the ass!
