### ISSUE TITLE
ArgumentError: different prefix on compass watch

### ISSUE THREAD

**Issue by wizardlyhel** [Compass/compass#1170]
I am getting the following error when I tried to do compass watch:

ArgumentError on line 730 of /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/pathname.rb: different prefix: "/" and "src"

This is running sass-3.2.5 and compass-0.13.alpha.2.

When I change compass back to version 0.12.2, I can properly compass watch again.

**Comment by scottdavis** [comment]
I just reverted a commit that may be causing this. can you try compass from the master branch?

**Comment by scottdavis** [comment]
Also can you post your config.rb i just pushed another fix that should fix this but i want to make sure.

**Comment by wizardlyhel** [comment]
I haven't had the chance to try the compass from master branch yet.

Here is the config.rb I have.

# 

require 'pathname'

// Require any additional compass plugins here.
// Set this to the root of your project when deployed:

http_path = "/"
css_dir = "."
sass_dir = "scss"
images_dir = "i"
javascripts_dir = "js"
// To enable relative paths to assets via compass helper functions. Uncomment:
relative_assets = true
project_path = "src"

if environment != :production
        sass_options = {:debug_info => true}
end

npm_root = `npm -g root`.strip
base_path = Pathname.new(npm_root).join("blah", "blah", "blah", "blah")
add_import_path  base_path.to_s

#

**Comment by wizardlyhel** [comment]
I just test the compass in master branch with my project and it is working properly. Thank you.
