### ISSUE TITLE
Compass does not comapile the SCSS files on local server

### ISSUE THREAD

**Issue by patriotbg** [Compass/compass#1172]
HI ,

I have an issue with compiling the SCSS files of my project on our local server.
I have mapped (Windows 8) the working folder of my project. Then I told comapss to watch the folder. In the begining the compass i compiling the scss files to css files. But sometimes   when I save my SCSS files it stop compiling them. I need to STOP watch the folder nad re- WATCH it again. And this is repeating all the time. Is anybody can help with this bug ?

PS. I think that my PC is loosing connection with the local server for a while and in meanwhile the compass is loosing connecton forever with the watched folder.

**Comment by scottdavis** [comment]
I'm not sure what to tell you other then to restart the watcher

**Comment by patriotbg** [comment]
Hi,
Tha is what I'm doing. But I need to restart the watcher to often . And this is time consuming. Is any other ideas what to do ?

**Comment by scottdavis** [comment]
try using polling? use `compass watch --poll`

**Comment by patriotbg** [comment]
here is the error that I received when I start "Clean & Compile": "Input/output error - Y:/static/games/.sass-cache/907a7bdff31011ce3c647501fb38822e72230bf4"  
where Y is mapped drive

**Comment by scottdavis** [comment]
did you try polling? you may want to move this conversation to the google group
