### ISSUE TITLE
Compass::SpriteException on line ["84"]  : Sprite Path not found issue on Windows 8

### ISSUE THREAD

**Issue by IbnSaeed** [Compass/compass#1174]
Compass version : 0.12.2 (Alnilam)
Sass version : 3.2.5 (Media Mark)
ruby version : 1.9.3 p385

OS: Windows 8 Pro

I am trying to create sprites for my icons. All my icons are under : 
project -> images -> icons -> [all my icons files are here in png format]

Code inside my .scss file is :

```
@import "compass";
@import "icons/*.png";
@include all-icons-sprites;
```

```
Compass::SpriteException on line ["84"] of d: No files were found in the load path matching "icons/*.png". Your current load paths are: D:\UniServer\www\project/images
```

Here is my config.rb:

```
http_path = "/"
css_dir = "css"
sass_dir = "sass"
images_dir = "images"
javascripts_dir = "javascripts"

output_style = :expanded
relative_assets = true
line_comments = false
```

**Comment by scottdavis** [comment]
try `"icons\*.png"

**Comment by scottdavis** [comment]
I currently don't have a copy of windows 8 so I can't test this myself
