### ISSUE TITLE
Changelog for 0.13.alpha.2

### ISSUE THREAD

**Issue by krisbulman** [Compass/compass#1175]
I don't see a changelog for 0.13.alpha.2 on http://beta.compass-style.org/CHANGELOG/

Are there docs around updating this? Not sure where to look for changelog.

**Comment by scottdavis** [comment]
docs arnt updated yet its in the repo

**Comment by scottdavis** [comment]
https://github.com/chriseppstein/compass/blob/master/doc-src/content/CHANGELOG.markdown
