### ISSUE TITLE
eot font format output not optimal

### ISSUE THREAD

**Issue by alicexyl** [Compass/compass#1176]
Not sure if someone mentioned this before, but output for eot format should be:

```
src: url('<eot font url>?#iefix') format('embedded-opentype'),
```

instead of:

```
src: url('<eot font url>?#iefix') format('eot'),
```

See [this post](http://www.fontspring.com/blog/fixing-ie9-font-face-problems) for a good explanation of this.

**Comment by pastinepolenta** [comment]
Any solution for this? IE doesn't load the font with the wrong format, so I cannot use the compass font-face...

**Comment by mirisuzanne** [comment]
How are you getting that output? If you pass the eot file as its own argument outside of `font-files()` (which is how the mixin is designed), everything works fine. That said, I also see where the wrong naming might originate. I'll fix our end if you fix yours. :)

``` scss
// eot should be passed as its own argument
@include font-face($name, $font-files,  $eot, $weight, $style);
```

**Comment by pastinepolenta** [comment]
seems that the line:
$font-files: font-url($iefont) unquote("format('eot')"), $font-files; 
on compass / frameworks / compass / stylesheets / compass / css3 / _font-face.scss 
is wrong

Edit: yes I am using the EOT outside of the font-file.

**Comment by mirisuzanne** [comment]
Removed the only compass mention of "embedded-opentype" in e5d2b67d856f9c73157.

**Comment by pastinepolenta** [comment]
Sorry , I don't understand. Should it be "embedded-opentype" instead of "eot" ? "eot" doesn't work in explorer 9

http://www.w3.org/TR/css3-fonts/#descdef-src

**Comment by mirisuzanne** [comment]
oh, I read that backwards. Sorry.

**Comment by pastinepolenta** [comment]
I think the problem is on the _font-face.scss  not on  lib/compass/sass_extensions/functions/font_files.rb

**Comment by mirisuzanne** [comment]
466a677
