### ISSUE TITLE
Compiling a single file will always rewrite Sprite Images

### ISSUE THREAD

**Issue by michaelgilley** [Compass/compass#1184]
When compiling a single file (`$ compass compile [/path/to/file.scss]`) the --force flag is automatically set to true. This causes all sprite files to be regenerated unnecessarily causing longer compile times.

See 6d6e1ca0e3d97ee7758ccdebc5c6ec0558d2fa7c.

**Comment by michaelgilley** [comment]
I'd suggest this not be implied. If someone needs to overwrite the file then they should explicitly use the `--force` flag. E.g., `$ compass compile myfile.scss --force`.

**Comment by chriseppstein** [comment]
This seems fine to me, can you make a PR against stable?

**Comment by michaelgilley** [comment]
Done.

**Comment by bdkjones** [comment]
Question: what are the implications of this change? Do I need to ensure that the CSS file does not exist before calling:

```
compass compile [path/to/file.scss]
```

Or will Compass still overwrite any previous CSS file that exists at the output location for this file?

**Comment by michaelgilley** [comment]
Compass will write/overwrite the CSS file as expected but only IF the scss
fill has been changed. Previously, it was overwriting regardless of no
changes.

**Comment by bdkjones** [comment]
How does Compass know if the file's been changed if I'm not using the --watch command? Does it keep a cached version of the file's last state?

**Comment by michaelgilley** [comment]
Yes. I'm not familiar enough to comment on how this mechanism works
(haven't dove into it) but compass stores a cached version of each file in
the .sass-cache dir.

**Comment by michaelgilley** [comment]
Yes. I'm not familiar enough to comment on how this mechanism works
(haven't dove into it) but compass stores a cached version of each file in
the .sass-cache dir.

Chris can speak more to this.

I have noticed, though, whenever I edit a file that will compile to the
same result (such as add or remove comment lines) the output in the CLI
looks like this:

$ compass compile
identical assets/css/main.css
