### ISSUE TITLE
Sprite / Image error floods my harddisk

### ISSUE THREAD

**Issue by BernhardBehrendt** [Compass/compass#1194]
I'm working with spritemap and  got images by a Designer. 
Seems one or more images let compass freeze completely and flood my Harddisk.
After a few minutes my SSD Disk was so full that the System crashed.

I made a short example:

It's just that little snippet here which causes the crash
body{
 $test:sprite-map('icons/*.png');
 background-color:#ff00ff;
 height:image-height(sprite-file($test, 'hinzufuegenBild-default'));
 @include sprite-bg('hinzufuegenBild-default', $test, $test, 10px, true);
}

I also made a complete testcase which can be downloaded here:
http://playground.appstack.io/example.zip

Also if I work with image functions e.g. 
height:image-height(sprite-file($test, 'hinzufuegenBild-default'));

I get that instead of 12px
786440px

**Comment by scottdavis** [comment]
Sounds like you designer is giving you bad files. i would suggest talking to them and ensuring that they are giving you properly formed png files.

**Comment by scottdavis** [comment]
We have seen this problem before and it comes down to either you are running an older version of compass that doesn't detect this and/or you are getting invalid png files
