### ISSUE TITLE
Bug in horizontal-list

### ISSUE THREAD

**Issue by mwesten** [Compass/compass#12]
Line 49 of  compass/utilities/lists/_horizontal_list.sass now states:
    +horizontal-list-item-container
and this generates the error:
    Sass::SyntaxError on line 49 of /Library/Ruby/Gems/1.8/gems/chriseppstein-compass-0.6.12/frameworks/compass/stylesheets/compass/utilities/lists/_horizontal_list.sass: Undefined mixin 'horizontal-list-item-container'.
I think it should be: 
    +horizontal-list-container

**Comment by jeroenvandijk** [comment]
I can confirm this too. I just rebuild edge (0.6.12) to make sure I wasn't using an old version.

Btw, is there a way to add a patch to these issues?

**Comment by marcenuc** [comment]
I have already sent a pull request for http://github.com/marcenuc/compass/commits/5868c2e4e19ff2b0d12e326aaa6961f6674575ef

**Comment by chriseppstein** [comment]
Fixed in 0.6.13.
