### ISSUE TITLE
Staleness_checker.rb freaks out on delete

### ISSUE THREAD

**Issue by imathis** [Compass/compass#120]
I was refactoring my stylesheets and deleted a partial (perhaps before removing the line where it was being included) I was running `compass -w` at the time, which killed the process and generated this error:

FSSM::CallbackError on line 90 of /Library/Ruby/Gems/1.8/gems/haml-3.0.0.beta.3/lib/sass/plugin/staleness_checker.rb: delete - /path_to_file/_partials.sass: No such file or directory - /path_to_file/_partials.sass
Run with --trace to see the full backtrace

It took me a bit to realize that watch had stopped, but when I fired it back up, everything was being compiled just fine. I don't know if that's the intended behavior, but it seems inelegant. I figured I'd post it incase you'd like to change this behavior.

**Comment by chriseppstein** [comment]
this is fixed in haml now.
