### ISSUE TITLE
Converting string to list with `_compass_list()`

### ISSUE THREAD

**Issue by joeyhoer** [Compass/compass#1204]
While trying to figure out how to turn a string into a list with Compass (e.g `"a b c"` would become a list with a length of 3… essentially `[a, b, c]`, but of course, a list isn't really an array). I think I may have come across a bug.

The `_compass_list()` function appears to be exactly what I'm looking for. According to the documentation: "Returns a list object from a value that was passed. This can be used to unpack a space separated list that got turned into a string by sass before it was passed to a mixin." However, in practice, the function simply wraps the string in a list (e.g. `"a b c"` becomes `["a b c"]`).

https://github.com/chriseppstein/compass/blob/stable/lib/compass/sass_extensions/functions/lists.rb#L47

If it's a bug, it should be a simple fix - something like `.split` - right? If it's not a bug, could you please clarify what the function does in the documentation?

**Comment by chriseppstein** [comment]
this is a private function and I intend to remove it. Please do not depend on it.
