### ISSUE TITLE
Hook to influence the destination and filename of the file on compile

### ISSUE THREAD

**Issue by F21** [Compass/compass#1206]
Currently, if I have my project like so:

```
/scss
   /folder1
      /one.css
   /folder2
     /two.css
```

This results in

```
/compiled-css
   /folder1
      /one.css
   /folder2
     /two.css
```

However, I might want to have the result compiled into:

```
/compiled-css
   /one.blah.css
   /two.css
```

I understand that the `on_stylesheet_saved` can be used to move files around after the stylesheet is saved, but this doesn't sound very efficient.

It would be nice if there's a hook similar to `asset_cache_buster`, to optionally pass the source and destination through a function, which then returns with a string of the final destination.

Not sure if this is more appropriate for SASS or Compass, so do let me know :)

**Comment by scottdavis** [comment]
This is pretty "edge" case i would simply recommend using the callback to move things around since this is the only time this has ever come up
