### ISSUE TITLE
use normalize.css  instead of  reset.css

### ISSUE THREAD

**Issue by Mustapha-elouafi** [Compass/compass#1217]
I don't understand why you don't use normalize instead of reset.css 

@necolas said: 

It supports a wide range of browsers (including mobile browsers) and includes CSS that normalizes HTML5 elements, typography, lists, embedded content, forms, and tables.

someone can explain ? 
thanks.

**Comment by scottdavis** [comment]
https://github.com/chriseppstein/compass/pull/819
