### ISSUE TITLE
Compass rc3, haml 3, rc1, rails3 beta 3 => can't require 'compass' in compass.rb initializer

### ISSUE THREAD

**Issue by kevmoo** [Compass/compass#122]
I might be trying too many cutting edge technologies.

require 'compass' blows up with "no such file" in compass.rb (in rails initilizers)

Help?

gem 'rails', '3.0.0.beta3'
gem 'haml', '3.0.0.rc.1'
gem 'compass', '0.10.0.rc3'

**Comment by chriseppstein** [comment]
sounds like a corrupt install. can you verify that lib/compass.rb exists in wherever "bundle show compass" tells you it is?

**Comment by kevmoo** [comment]
Good catch! The dir under my ~/.bundle dir doesn't exist (I nuked it trying to get things to work)

Suggestions how to reinstall?

**Comment by kevmoo** [comment]
I nuked compass out of my local spec/cache dirs

Using the system gem now -> all is good

Thanks!
