### ISSUE TITLE
[Question] Any tips to optimise compilation duration?

### ISSUE THREAD

**Issue by kud** [Compass/compass#1223]
Hello,

I use to use grunt-contrib-compass with livereload, and I noticed that compass takes a little time to compile.

I can have lots of scss, sprites or just almost nothing, it takes the same time, like ~3s of compilation (and so to reload my page via livereload).

Do you have any tips to optimise the compilation to take less time?

I already do not import @compass but I choose all functions/mixins/whateverelse I need. But if you have any advise...?

Or maybe find a way to optimise the core itself? (I know, it ain't so easy).

Thank you.

**Comment by scottdavis** [comment]
You may want to ask on our google group https://groups.google.com/forum/?fromgroups#!forum/compass-users

**Comment by kud** [comment]
I could understand the closing of the ticket as it's not really a bug and it's more a question so yes, its place is on Google Groups.

Though, I'm not a newbie with compass and the more I use it, the more I find it really slow. In fact, my ticket could have been called "Please optimise compass compilation" but it's true I have no idea how.

I will ask those questions on google groups so. Thank you.

**Comment by scottdavis** [comment]
I'm not sure what we can do to "optimize" I'm running about 12,000 lines of sass in my big project on an SSD and my compile time is ~2 seconds

**Comment by kud** [comment]
Yep, I understand. I've no idea too. Thank you anyway.

On 21 March 2013 12:36, Scott Davis notifications@github.com wrote:

> I'm not sure what we can do to "optimize" I'm running about 12,000 lines
> of sass in my big project on an SSD and my compile time is ~2 seconds
> 
> Sent from my iPhone
> 
> On Mar 21, 2013, at 4:44 AM, Erwann Mest notifications@github.com
> wrote:
> 
> > I could understand the closing of the ticket as it's not really a bug
> > and it's more a question so yes, its place is on Google Groups.
> > 
> > Though, I'm not a newbie with compass and the more I use it, the more I
> > find it really slow. In fact, my ticket could have been called "Please
> > optimise compass compilation" but it's true I have no idea how.
> > 
> > I will ask those questions on google groups so. Thank you.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/chriseppstein/compass/issues/1223#issuecomment-15231651
> .

## 

_Erwann Mest_

kud.io
