### ISSUE TITLE
Min-Height

### ISSUE THREAD

**Issue by shoxty** [Compass/compass#123]
I found that the min-height fix doesn't work in IE 6. To get the min-height fix to work in all browsers I found instead of doing this:

min-height: 400px;
height: 400px !important;
height: auto;

Do this:

min-height: 400px;
height: auto !important;
height: 400px;

The CSS has to be exactly in that order to work, min-height then height auto important followed by the height. I've been using this method for a very long time now and it works every time. Hope you find this useful.

**Comment by chriseppstein** [comment]
This is already fixed in v0.10.

**Comment by thedarkone** [comment]
Chris, I think you are mistaken. Please, do investigate this.

**Comment by chriseppstein** [comment]
I guess I misread. Here's the patch for the next release: http://github.com/chriseppstein/compass/commit/842d39ebe0fe0f60c58a3611c1fac6fa91f4a329
