### ISSUE TITLE
Image corrupted when after project created/Windows

### ISSUE THREAD

**Issue by simongcc** [Compass/compass#1233]
Using 0.12.2 under Windows 8

I am new to Ruby and Compass, not sure if I have made anything wrong.
I created project with this command

The first time I found that problem is by creating my own Extension for test.
Then I try
compass create test13 --using blueprint/link_icons

Those link_icons are all corrupted after creation. (All of them)

Things have tried:
change image from png to gif or vice versa
reinstall compass
reboot system to see if it is memory problem or Windows's problem

Not sure what happen, does it related to
"Write files in binary mode to avoid data corruption when installing images on windows. Fixes Issue #39" ?

![compass-create-project-gif-img-corrupt](https://f.cloud.github.com/assets/1510274/313730/45b5f18a-97b7-11e2-9371-701f9d5c5c35.jpg)

**Comment by scottdavis** [comment]
I think this is fixed in the alpha 0.13 the watcher will not work in 0.12 on windows.

**Comment by simongcc** [comment]
I see, is the 0.13 available now?

The watcher you mean is the file update watcher?
0.12.2 's watcher works fine in windows, when scss file update, it write to css file without problem fortunately.
So far I have just encountered image corrupt problem.

BTW, as you have mentioned about alpha 0.13, I would also like to know about...:
Because I would like the project follow a custom config.rb
When "create project with extension", could I let Compass also to use a custom config.rb in 0.13?
Because the current practice is config.rb have to be put in folder first and then install the extension. So that the extension will follow the config.rb (path/folder name) and so on.

Much thanks.

**Comment by scottdavis** [comment]
Yes use gem install compass --pre you will also need the compass-blueprint gem

**Comment by simongcc** [comment]
Thanks, I have tried 0.13.Alpha2, the image corruption problem is gone in Windows 8.

Because I am a novice, just note here for someone who might have the same wondering.
After installing the compass-blueprint gem in gems default installation folder, you may have to use by:

1
Since it is now installed as an extension (the most rightful way to use)
compass create YOUR_PROJECT -r compass-blueprint --using blueprint
compass create YOUR_PROJECT -r compass-blueprint --using blueprint/link_icons (patterns inside)

according to the current online document, "-r compass-blueprint" switch is required currently and might be improved in the future. Since the installation name is "compass-blueprint" and register name is "blueprint", it took me a while to figure it out to use. Hope can help someone else.

OR (before I figure it out the above)

2
 When install "compass-blueprint gem", currently I have to manually put in "frameworks" folder to get it recognized by compass.  Because Ruby Gem install it in gems location by default.
Q: Normal in this version, right?

OR

3
using "load" switch to specify the framework location
eg. compass create YOUR_PROJECT --using blueprint --load C:\Ruby193\lib\ruby\gems\1.9.1\gems\compass-blueprint-0.0.1\framework\blueprint
