### ISSUE TITLE
compass watch causes recursively creating css / config.rb folder

### ISSUE THREAD

**Issue by chrisl8888** [Compass/compass#1234]
Would anyone know why would compass to recursively create a config.rb file in each of child folder?

It also generates css files for each file in it's each child folder. 
##### Steps to reproduce this issue:
- Create a compass project
- create several sub folders within sass/scss folder
- place scss files in sass folder and files inside sass folders
- perform compass watch --debug-info
###### Ruby version

<code>
% ruby -v
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]
</code>
###### Gems used:

<code>
bundler (1.3.4)
chunky_png (1.2.7)
classifier (1.3.3)
compass (0.12.2)
directory_watcher (1.4.1)
fast-stemmer (1.0.2)
fssm (0.2.10)
jekyll (0.12.1)
kramdown (0.14.2)
liquid (2.4.1)
maruku (0.6.1)
modular-scale (1.0.6)
oily_png (1.1.0)
posix-spawn (0.3.6)
pygments.rb (0.4.2, 0.3.7)
rake (10.0.3)
sass (3.2.6, 3.2.5)
sassy-math (1.5)
syntax (1.0.0)
yajl-ruby (1.1.0)
zen-grids (1.3, 1.2)
zurb-foundation (3.2.5)
</code>

**Comment by scottdavis** [comment]
Need to know OS and ruby version please

**Comment by chrisl8888** [comment]
Ubuntu 12.04 

<code>
% ruby -v  
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]
</code>

**Comment by scottdavis** [comment]
can you post your compass config also

**Comment by jpfuentes2** [comment]
I'm having the same issue as @chrisjlee

### Here's my configuration/environment:

```
λ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.8.3
BuildVersion:   12D78

λ rbenv version
1.9.3-p327 (set by /Users/jfuentes/code/speakeasy/.ruby-version)

λ cat config/compass.rb 
http_path = "/"
css_dir = "public/css"
sass_dir = "app/views/sass"
images_dir = "public/images"
javascripts_dir = "public/js"
output_style = :expanded
relative_assets = false
line_comments = true

λ cat .gems | sort
better_errors -v 0.7.0
compass -v 0.12.2
cuba -v 3.1.0
cuba-contrib -v 3.1.0
cutest -v 1.2.0
foreman -v 0.62.0
git-deploy -v 0.5.4
haml -v 4.0.0
mandrill-api -v 1.0.15
mechanize -v 2.0.1
mysql2 -v 0.3.11
rack -v 1.5.2
rack-protection -v 1.5.0
rack-test -v 0.6.2
sass -v 3.2.7
secure_headers -v 0.3.0
shotgun -v 0.9
thor -v 0.14.6
unicorn -v 4.6.2
whenever -v 0.5.0
```

### Here's the workflow

``` shell
λ tree app/views/sass/
app/views/sass/
├── app.scss
├── base.scss
├── colors.scss
├── mixins.scss
└── survey.scss

0 directories, 5 files

λ compass watch
>>> Compass is polling for changes. Press Ctrl-C to Stop.
>>> Change detected at 23:29:53 to: survey.scss ## saved survey.scss file in editor
identical public/css/app.css 
identical public/css/base.css 
identical public/css/colors.css 
identical public/css/mixins.css 
overwrite public/css/survey.css 
^C

# Now we have a newly created config.rb
λ ls -la app/views/sass/config.rb 
-rw-r--r--  1 jfuentes  staff  156 Apr  4 23:29 app/views/sass/config.rb
```

**Comment by metalmatze** [comment]
I've got the same problem as @chrisjlee on Arch Linux.

``` bash
$ ruby -v
ruby 2.0.0p0 (2013-02-24 revision 39474) [x86_64-linux]
```

The compass config in the project is

``` ruby
http_path = "/"
css_dir = "."
sass_dir = "sass"
images_dir = "img"
javascripts_dir = "js"

output_style = :expanded

# relative_assets = true
line_comments = false
```

**Comment by metalmatze** [comment]
I just figured out that my issue was caused from sublime's livereload package.

**Comment by jpfuentes2** [comment]
Oh wow, I feel stupid! I think I have the same problem as @MetalMatze.

**Comment by ramonvictor** [comment]
I've had the same problem on Windows 7. 
After disabling LiveReload everything works fine.
Thanks guys, I couldn't realize it was the problem.

**Comment by chrisl8888** [comment]
Wow. Thanks everyone. I'll try that out.

**Comment by RafaelVidaurre** [comment]
Same problem here LiveReload wass busting my nuts. Thanks!
