### ISSUE TITLE
The background-clip mixin documentation should note that the value "text" only works in webkit browsers

### ISSUE THREAD

**Issue by colinwren** [Compass/compass#1236]
The "text" value for the `background-clip` property is only supported in webkit browsers and the [general philosophy](https://github.com/chriseppstein/compass/blob/stable/CONTRIBUTING.md#general-philosophy) states:

> By default, Compass supports as many browsers as it can. Where it can't it progressively enhances. Where it degrades, the documentation should make a note. Deviation from this requires an excellent reason.

It should be included in the documentation that the "text" value isn't supported in Firefox or IE.

Also see a [#113](https://github.com/chriseppstein/compass/issues/113) where @chriseppstein says the "text" value shouldn't be supported due to lack of support.

**Comment by mirisuzanne** [comment]
This has already been fixed on the master branch: https://github.com/chriseppstein/compass/blob/master/frameworks/compass/stylesheets/compass/css3/_background-clip.scss
