### ISSUE TITLE
error while trying to compile documentation

### ISSUE THREAD

**Issue by ghost** [Compass/compass#1241]
I went trough the steps to compile documentation but with nanoc3 I get an error : 

```
There was a NoMethodError while loading compass.gemspec: 
undefined method `today' for Date:Class from
  /home/damaru/documents/web/compass/compass.gemspec:6:in `block in <main>'
```

not sure what would be the next step to resolve that. 

thanks

**Comment by scottdavis** [comment]
I just updated the gemfile for the docs re pull and bundle and it should work

**Comment by scottdavis** [comment]
Also the date issue is solved by not using ruby 2.0

**Comment by ghost** [comment]
Hum I think it's my bad, I tried to use nokogiri 1.5.9 - I'll tried to compile the doc with ruby 1.8.
My first try was with ruby 1.9, but I had trouble installing nokogiri 1.4.4, so I tried to bundle with nokogiri 1.5.9 which at least finished the bundler. 
So the compass documentation would need to be compiled with ruby 1.8? or 1.9 should work? Not sure why nokogiri 1.5.9 wouldn't work?

**Comment by scottdavis** [comment]
i pushed a fix for the gemfile issue last night so all should be good now
