### ISSUE TITLE
Custom watch action doesn't detect changes on mac

### ISSUE THREAD

**Issue by smmurf** [Compass/compass#1256]
That's my config.rb file:

```
http_path = "/"
css_dir = "css"
sass_dir = "src"
images_dir = "i"
javascripts_dir = "js"

relative_assets = true

line_comments = false

watch "src/blocks/*/*" do |project_dir, relative_path|
  puts relative_path
  if File.exists?(File.join(project_dir, relative_path))
    puts "File size of #{relative_path} is: #{File.size(File.join(project_dir, relative_path))}"
  end
end
```

It's just debugging, so I do nothing serious here. The problem is that watch doesn't detect any changes until I save config.rb with my editor.

Looks very strange, I can add or remove files, but I see that watch detected it only after I save config. Even if there's no changes in config, I have to Cmd+S to detect any changes to files in src/blocks/[block name]/[block file]

Mac OS X 10.7.5
ruby 1.8.7
Compass 0.12.2 (Alnilam)

**Comment by scottdavis** [comment]
Try the latest alpha the watcher has been completely overhauled

**Comment by smmurf** [comment]
Thank you!

Looks like in Compass 0.13.alpha.4 (Markab) it works as I expect. That's great! Thank you again.
