### ISSUE TITLE
Removing old webkit gradient support in 0.13.alpha3 causes gradients generated with Compass to fail in old Android and iOS versions

### ISSUE THREAD

**Issue by kristerkari** [Compass/compass#1257]
Looks like the old webkit syntax for CSS3 gradients [was recently dropped from Compass](https://github.com/chriseppstein/compass/commit/395c7be629875a92b5d7432e5f170f96b41c8970) with 0.13.alpha3.

Older Android and iOS versions support only the old webkit gradient syntax [[link, see partial support]](http://caniuse.com/#feat=css-gradients&agents=android,ios_saf). There is still a huge amount of people using those OS versions [[link]](http://developer.android.com/about/dashboards/index.html), so I would suggest to still keep the old syntax in Compass.

**Comment by scottdavis** [comment]
I had surveyed a bunch of users via twitter and they where all in support of dropping the syntax. Im open to re-adding it as a non default.

**Comment by cimmanon** [comment]
I guess your Twitter respondents aren't still using Gingerbread ;-).

**Comment by kristerkari** [comment]
@scottdavis re-adding as disabled would be nice, but it wouldn't be a bad idea to enable it by default.

I'm usually ok with dropping support for old stuff, but the fact is that almost half of all Android users still use version 2.X, and that number is only slowly going down. The projects I'm working for are so big, that dropping support for the old gradient format will affect millions of users, and that is why it is not an option in my case.

**Comment by chriseppstein** [comment]
I'll see what I can do to bring the old syntax back.

**Comment by chriseppstein** [comment]
@kristerkari yes, it will be off by default going forward.

**Comment by kristerkari** [comment]
Nice, thanks!

**Comment by drewwells** [comment]
For context, 41% of Android and 1% of iOS users need this syntax support.

http://developer.android.com/about/dashboards/index.html
https://developer.apple.com/devcenter/ios/checklist/ (login required)
![chart](https://f.cloud.github.com/assets/239123/744737/30c19246-e403-11e2-831b-dc0b7181ee6c.png)

**Comment by piouPiouM** [comment]
Thx @chriseppstein to try to bring the old syntax back!

**Comment by aronwoost** [comment]
:+1: Android 2.x is very alive.

**Comment by chriseppstein** [comment]
Fixed by #1751.
