### ISSUE TITLE
$firefox2-ellipsis needs to be set for < 3.6

### ISSUE THREAD

**Issue by john-griffin** [Compass/compass#126]
0.10.0.rc5 has introduced the $firefox2-ellipsis variable which needs be set to true to enable the moz-binding fix. This is also needs to be set to true to support all Firefox versions prior to 3.6 (not just Firefox 2 ie 3.5.9).

Can this variable be renamed so it's clearer or can the moz-binding fix remain in by default?

**Comment by chriseppstein** [comment]
Hmm. what's a good name then?

**Comment by john-griffin** [comment]
err it's tricky isn't it :) options:

$firefox35-and-prior-ellipsis
$firefox35-and-lower-ellipsis
$firefox35-and-before-ellipsis
$firefox35-and-older-ellipsis
$firefox35-or-older-ellipsis
$firefox35-or-prior-ellipsis
$firefox35-or-lower-ellipsis
$firefox35-or-before-ellipsis
$pre-firefox36-ellipsis

What do you think?

**Comment by chriseppstein** [comment]
I'm thinking `$use-mozilla-ellipsis-binding`.

**Comment by chriseppstein** [comment]
[Compass Core] Rename -ellipsis to -mozilla-ellipsis-binding to be more accurate. Closed by c3c0d8a1e812d787cca039e9e8389580176272ad.
