### ISSUE TITLE
Compass.sass_engine_options confuses nanoc

### ISSUE THREAD

**Issue by gpakosz** [Compass/compass#1260]
When integrating Compass within nanoc, people typically do

``` ruby
filter :sass, Compass.sass_engine_options
```

or even

``` ruby
filter :sass, Compass.sass_engine_options.merge(:syntax => item[:extension].to_sym)
```

So far so good, except that `Compass.sass_engine_options` returns new instances of `Sass::Importers::Filesystem` and `Compass::SpriteImporter` at each invocation as shown by https://github.com/chriseppstein/compass/blob/stable/lib/compass/configuration/adapters.rb#L70-L72

I won't go into detailing nanoc's internals but nanoc tries to figure out if the `Rules` file changed since the last time an item was compiled by computing a "rule memory". Computing the rule memory relies on `#inspect`, see https://github.com/nanoc/nanoc/blob/master/lib/nanoc/base/compilation/rules_collection.rb#L190-198

That said, neither `Sass::Importers::Filesystem` nor `Compass::SpriteImporter` implements `#inspect` and the stock `Object#inspect` prints the importers' memory address in the result. That precise behavior confuses nanoc which believes the `Rules` file has changed since the last Sass+Compass item compile; because the "inspect dump differs by the importer's memory address"

Still with me? From that point, it means every item filtered with Sass+Compass is recompiled every time you invoke `nanoc compile`. Because every time, nanoc incorrectly believes the `Rules` file has changed in between compiles. Then, as soon as you introduce cache busting into the picture, that causes a recompile of almost every site item, each time you invoke `nanoc compile`.

This can be worked around from within nanoc, see https://gist.github.com/gpakosz/5420177

Another solution would be: Compass provides its own subclass of `Sass::Importers::Filesystem` with an implementation of `#inspect` that just prints `@root`. Same for idea for `Compass::SpriteImporter`. In fact, print out whatever feels right but that doesn't change between successive `Compass.sass_engine_options` invocations.

I don't know if Compass is willing to change its implementation in order to accomodate nanoc's implementation peculiarities, but at least I detailed the "issue" right here :)

Regards!

cc @ddfreyne

**Comment by denisdefreyne** [comment]
Changing Sass/Compass’ `#inspect` would solve the problem, but I’m not sure whether it is the best way to go. (I’m also not sure whether the best place to discuss it is here, but we’ll see!)

Some more context:

nanoc serialises every rule invocation by passing a “spy” item rep through each rule, and recording whatever is called. The `filter :foo, :bar => some_function(123)` statement would be turned into something like `[ :filter, :foo, { :bar => 456 } ]`.

A problem arises when non-serialisable objects are used in rules, though: lambdas and IOs are not serialisable and cannot be YAML-serialised, JSON-serialised or `Marshal.dump`ed. The “best” approach chosen at the time was to `inspect` the arguments to `#filter`, which always produces a string and can therefore always be serialised.

Of course, this has undesirable effects when serialising objects that include their memory location, which is what the default `#inspect` does.

Modifying Sass/Compass’s `#inspect` would solve the problem, but I think we should brainstorm on how to tackle this issue in a different manner that does not involve modifying `#inspect`.

**Comment by scottdavis** [comment]
I would post this on nanoc's issue tracker to get them to fix it on their side. I highly doubt we will make a change to inspect.

**Comment by chriseppstein** [comment]
It seems like a custom implementation of dump and load for the importers would be better for Marshal compatibility than changing `#inspect`. There's no reason these classes should be hostile to serialization.

[Marshal Docs](http://ruby-doc.org/core-2.0/Marshal.html)

**Comment by denisdefreyne** [comment]
`#inspect` was preferred over `Marshal.dump` because of non-serialisable objects being passed around (mostly lambdas).

I’ll move this over to the nanoc issue tracker and figure out a solution there!

**Comment by denisdefreyne** [comment]
@chriseppstein You can close this issue.
