### ISSUE TITLE
Compass watch eating too much CPU

### ISSUE THREAD

**Issue by Somebi** [Compass/compass#1263]
SASS: >>> Compass is polling for changes. Press Ctrl-C to Stop.

I'm using:
Distributor ID: Ubuntu
Description:    Ubuntu 12.10
Release:        12.10
Codename:       quantal

Is there a way to configure compass watch to poll with lesser interval? Why it's so CPU intensive? I'm watching few files...

**Comment by scottdavis** [comment]
compass version?

**Comment by Somebi** [comment]
Compass 0.12.2 (Alnilam)

**Comment by chriseppstein** [comment]
It's strange that it's resorting to polling instead of using filesystem watching via inotify.

**Comment by scottdavis** [comment]
Its also on 0.12 and fssm has had some bad regressions.

**Comment by Somebi** [comment]
Closing this one as well. https://github.com/chriseppstein/compass/issues/1270#issuecomment-17015418
