### ISSUE TITLE
problem invoking compass from ant

### ISSUE THREAD

**Issue by stephanlindauer** [Compass/compass#1269]
when i invoke compass from ant on my ubuntu machine with this target

```
<target name="commpass.compile">
    <exec executable="bash">
        <arg value="compass" />
        <arg value="compile" />
        <arg value="css/" />
    </exec>
</target>
```

i get:

commpass.compile:
     [exec] /usr/local/bin/compass: line 9: require: command not found
     [exec] /usr/local/bin/compass: line 11: version: command not found
     [exec] /usr/local/bin/compass: compass: line 15: syntax error near unexpected token `('
     [exec] /usr/local/bin/compass: compass: line 15:`  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding'
     [exec] Result: 2

**Comment by chriseppstein** [comment]
This is not a compass bug. Compass does not provide an ANT build file, but I know that people _have_ successfully used compass with ANT. Perhaps seek support from the ANT community.

**Comment by AuroreEteve** [comment]
I have the same issue running compass by ruby with a windows command line. I am not using ant for it, but have the same issue.
How do you success resolving it ? Thanks

**Comment by stephanlindauer** [comment]
what i did is just setup a .sh-file that executed that line... if you find something that is less of a workaround - let me know! ;)
