### ISSUE TITLE
404 error when requesting the documentation pages without trailing slash

### ISSUE THREAD

**Issue by cakebaker** [Compass/compass#127]
Just a minor issue I encountered while accessing the new documentation: when I access any documentation page (e.g. http://compass-style.org/docs) without a trailing slash I get a 404 error page.

**Comment by chriseppstein** [comment]
I'll see if I can set up a redirect.

**Comment by chriseppstein** [comment]
Fixed. http://github.com/chriseppstein/compass-style.org/commit/e72686c1cca6b4eb70e30eeac2999b729bb6d337
