### ISSUE TITLE
Sometimes watch feature prints out empty css

### ISSUE THREAD

**Issue by Somebi** [Compass/compass#1270]
Using this version:
Sass 3.2.7 (Media Mark)
Compass 0.12.2 (Alnilam)

Just getting blank css file, after few attempts to re-save .scss file it's ok.

Looks like a bug. Don't know how you can reproduce it on your side.

Another bug with the watch itself. Some times it's blind to recent changes. Have to re-save few times to force it accept the changes inside file.

Guess something is really bad inside watch module.
- It's eating too much CPU
- Blind to changes sometimes
- Return blank css sometimes

Thanks.
Will help any way i can, with the information you'll request.

**Comment by scottdavis** [comment]
What file system?

**Comment by Somebi** [comment]
Distributor ID: Ubuntu
Description: Ubuntu 12.10
Release: 12.10
Codename: quantal

**Comment by Somebi** [comment]
Oh sorry didn't understand you at first. Ubuntu is on ext4 partition.

**Comment by scottdavis** [comment]
Are you mounting a ssh or some other type of remote file system?

**Comment by Somebi** [comment]
Nope, don't think so. I'm renting a server. Not sure whether it's virtual or not.

Here is the list of what is mounted atm:

root@mydomain:~# cat /etc/mtab
rootfs / rootfs rw 0 0
/dev/root / ext4 rw,relatime,errors=remount-ro,user_xattr,barrier=1,data=ordered 0 0
none /dev/pts devpts rw,nosuid,noexec,relatime,mode=600 0 0
none /proc proc rw,nosuid,nodev,noexec,relatime 0 0
none /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
none /proc/sys/fs/binfmt_misc binfmt_misc rw,nosuid,nodev,noexec,relatime 0 0
none /sys/fs/fuse/connections fusectl rw,relatime 0 0
none /run tmpfs rw,nosuid,noexec,relatime,size=202840k,mode=755 0 0
none /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
none /run/shm tmpfs rw,nosuid,nodev,relatime 0 0
none /run/user tmpfs rw,nosuid,nodev,noexec,relatime,size=102400k,mode=755 0 0
/dev/sda2 /home ext4 rw,relatime,user_xattr,barrier=1,data=ordered 0 0

**Comment by Somebi** [comment]
root@mydomain:~# df
Filesystem     1K-blocks     Used Available Use% Mounted on
rootfs          20907056  2693604  17164876  14% /
/dev/root       20907056  2693604  17164876  14% /
none              202840      236    202604   1% /run
none                5120        0      5120   0% /run/lock
none             1014180        0   1014180   0% /run/shm
none              102400        0    102400   0% /run/user
/dev/sda2      466381632 13751988 429285416   4% /home

**Comment by Somebi** [comment]
If anything else is required. Let me know.

**Comment by scottdavis** [comment]
And. You are developing remotely on this server? Lets say using an editor or are you mounting the file system over FTP or ssh?

**Comment by Somebi** [comment]
Yeah i'm sitting in terminal via ssh. Using putty on Windows.

**Comment by Somebi** [comment]
.scss files are sychronized via winSCP, via ssh tunel. Editing .scss files on windows via sublime text 2.

**Comment by scottdavis** [comment]
I'm curious if its an issue with mtimes this Linda issue has popped up before but it may possibly be fixed with the new watcher in 0.13 you may want to give "gem install compass --pre" a shot

**Comment by Somebi** [comment]
Just a moment. I'll try it out.

**Comment by Somebi** [comment]
Yes, the issue with CPU usage is gone. Will check the rest a bit later. New version asked for:

 Please run the following to satisfy the dependency:
    gem install --version '~> 0.9' rb-inotify

And now it seems it's using native inotify. Triggering only when file have been changed as i understand.

SASS: >>> Compass is watching for changes. Press Ctrl-C to Stop.

Thanks. :)
