### ISSUE TITLE
Compass eating 100% CPU around 30~ seconds from start

### ISSUE THREAD

**Issue by Somebi** [Compass/compass#1271]
It's after installing Compass 0.13.alpha.4 (Markab) and inotify gem.

I had problems with high CPU usage, when polling was used instead of inotify.

How to debug compass? I'll post his activity when it's using 100% of cpu.

**Comment by Somebi** [comment]
When using watch feature.

**Comment by Somebi** [comment]
![Proof link](http://img13.imageshack.us/img13/2138/87847229.png)

**Comment by Somebi** [comment]
It's considered as a bug? Inserted in the fix plan?

**Comment by Somebi** [comment]
Hmm the watch seems to eat cpu again.

**Comment by Somebi** [comment]
Now it's not. It's very strange. I saw it was overloading server hdd, over 33mb/sec for 1 compass process... There is definitely some infinite loop inside code, related to IO.

**Comment by scottdavis** [comment]
you may want to report this to the guard/listen guys since that is what we use for the watcher in 0.13 maybe they can help get this debugged

**Comment by scottdavis** [comment]
ping @thibaudgg

**Comment by thibaudgg** [comment]
I @Somebi polling can become a CPU intensive if you got a lot of file in your watched folder (as it scans all files every 1s), what was in your watched folder?

PS: I files scanning take more than 1s, it'll scan all the time...

**Comment by Somebi** [comment]
I'm not using polling anymore. Only inotify. It's not polling for changes if i'm not wrong. It's trigger handlers when file is modified. I have default scss setup created by sass, there is only few import files in that folder. Overall 3 files in a watching directory.

I want to debug to a log file and post it in dropbox, to link it here. How do i do that?

**Comment by thibaudgg** [comment]
Are you using the last version of `Listen` and `rb-inotify`? @scottdavis last version of Compass are using Listen ~> 1.0 right?

**Comment by Somebi** [comment]
rb-inotify (0.9.0)
listen (0.7.3)

Updated, haven't noticed it in the list of gems.

**Comment by Somebi** [comment]
Updated listen to the lastest version. Will see whether it helped or not.

**Comment by scottdavis** [comment]
@thibaudgg i just pushed the 1.0.0 listen change last night its not a gem yet I can release a gem later today for alpha 5 if it helps.

**Comment by Somebi** [comment]
listen (0.7.3) didn't helped, will try to update compass then.

**Comment by Somebi** [comment]
Hmm how to install compass from repository sources? gem install compass seems to installing stable version only. No make file inside git cloned folder. Some help required here.

**Comment by scottdavis** [comment]
you can use bundler and get the git target 

```
gem 'compass', :git => 'https://github.com/chriseppstein/compass.git'

```

http://gembundler.com/#getting-started

**Comment by Somebi** [comment]
I don't get it. It's only usable inside ruby app? bundle list shows \* compass (0.13.alpha.4.46ce009 46ce009)
but gem list doesn't. As i understand both are ruby gem managers, but bundle gems are only scoped to ruby apps?
So can be used only inside ruby scripts? Or i'm missing something?

**Comment by Somebi** [comment]
I need to be able to access compass from terminal. Having symlinks in bin folder. So i can spawn process inside nodejs.

**Comment by Somebi** [comment]
How everything is complicated...
bundle show compass
/home/compass/bundle/ruby/1.9.1/bundler/gems/compass-46ce00936862
Then i found actual compiled binary of compass inside:
/home/compass/bundle/ruby/1.9.1/bundler/gems/compass-46ce00936862/bin/compass

Now i have to manually add symlink or there is a way to do it via bundler?

Thanks.

**Comment by Somebi** [comment]
root@beckend:/home/compass# ln -s /home/compass/bundle/ruby/1.9.1/bundler/gems/compass-46ce00936862/bin/compass /usr/bin/compass
root@beckend:/home/compass# compass -v
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- compass (LoadError)
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
        from /usr/bin/compass:20:in `block in <main>'
        from /usr/bin/compass:8:in`fallback_load_path'
        from /usr/bin/compass:19:in `<main>'
root@beckend:/home/compass#

**Comment by scottdavis** [comment]
Have node.js call out to a `bundle exec compass` with a gemfile that locks the compass version.

**Comment by Somebi** [comment]
Ok thanks i'll try that out.

**Comment by chriseppstein** [comment]
@Somebi any luck testing this?

**Comment by Somebi** [comment]
Naah i have dropped SASS for a while. :)

Using clean css instead.

Using only when required some complex, repeatable styling, like complex gradient/shadowed buttons with hover/active etc states. For example bootstrap buttons styling.

**Comment by dmitry-yakimenko** [comment]
I had *.psd file in img/icon folder which used to generate sprites.

**Comment by snario** [comment]
Just for anyone that ends up here, I had `compass watch <dir>` pointing to a directory that did not exist yet which caused `ruby` to go nuts and eat up my CPU.

**Comment by pere5** [comment]
sass --watch src/main/resources/private/sass:src/main/resources/public/stylecheets
this command eats 99% of my cpu on mac.

 ruby   100,0

**Comment by chriseppstein** [comment]
Try upgrading the `listen` gem that sass uses to watch directories.

**Comment by pere5** [comment]
@chriseppstein thank you, sudo gem install listen seems to have sovled it

**Comment by pere5** [comment]
@chriseppstein Quick feedback, it wasn't solved. Eventually solved it by using Grunt watch to run a "sass --update ..."

**Comment by kayhadrin** [comment]
I've done the same workaround

**Comment by BossLevel** [comment]
Me too :(
