### ISSUE TITLE
Documentation: "Compass Cross-Browser Support Configuration" missing in navigation

### ISSUE THREAD

**Issue by benebun** [Compass/compass#1272]
Hi,

something that always throws me off with compass' reference is that some pages aren't listed in any navigation and can just be found by searching.

Sorry if I'm missing something but one such example seems to be the [Compass Cross-Browser Support Configuration](http://compass-style.org/reference/compass/support/).

IMHO this could be listed in the vertical navigation on the left?

Cheers

**Comment by Anahkiasen** [comment]
It's quickly linked here : http://compass-style.org/reference/compass/css3/ in the intro

**Comment by chriseppstein** [comment]
I have added this page to the side nav. It was the only such page not being shown in the side navs. This will be changed when we launch 0.13

**Comment by chriseppstein** [comment]
Closed by c44d824359f3861587596630c4acae6a7edd65b7

**Comment by benebun** [comment]
Thanks! I guess I must have been mistaken about it concerning more pages. Must have been the same one at different times.
