### ISSUE TITLE
Easier support for generating multiple output formats

### ISSUE THREAD

**Issue by acdha** [Compass/compass#1275]
I have main.scss and would like to produce both main.css (for easier development/testing) and main.min.css, ideally without requiring separate compile passes or manually renaming files. This becomes particularly useful when using sprites where the image processing overhead becomes significant (#897 adds a complication as using `compass compile foo.min.scss` will still reprocess all of the sprites as if `--force` was specified).

Currently, I'm using an approach where `main.min.scss` uses `@import "main"` so my build process can run `compass compile` twice with the development and production environments but that ends up regenerating the output files multiple times and causes a full scan of the sprite sources as well. It'd be really nice if there was some way to say "Process main.scss a single time and save the result to main.css using the normal output style and main.min.css using the compressed output style"

**Comment by scottdavis** [comment]
This is a limitation of sass not an issue with compass. You may want to start that discussion on the sass issue list.

**Comment by acdha** [comment]
@scottdavis The upstream position is that this is something which should be handled by the caller (i.e. compass):

https://github.com/nex3/sass/issues/507

I'm currently using make to correctly specify the output styles but this is somewhat expensive until #897 closes.
