### ISSUE TITLE
Warnings emitted to stdout; corrupts stylesheet

### ISSUE THREAD

**Issue by jpap** [Compass/compass#1276]
When a warning is issued, it's output to stdout (in Compass::Logger.log) instead of stderr.

The warning is silently included in the stylesheet, when using tools like Brunch (via sass-brunch), causing a corrupt stylesheet.

Brunch is using sass via command line and quiet mode.  Quiet mode doesn't appear to be reflected in the logger at all either.

I'm a fan and user of Compass 0.12.2 (Alnilam).

jpap

**Comment by chriseppstein** [comment]
ok. we'll use stderr for this.

**Comment by chriseppstein** [comment]
I think this should be fixed in the latest 1.0 alpha releases. Please reopen with steps to reproduce if it's not.
