### ISSUE TITLE
http_generated_images_path default value

### ISSUE THREAD

**Issue by rinatio** [Compass/compass#1280]
`http_generated_images_path` doesn't point to `http_path + "/" + generated_images_dir` by default although documentation says it does. It isn't true unless you set `relative_assets` to `true`

**Comment by mzgajner** [comment]
I can confirm this, using 0.12.2. Any problems are easy to fix by manually setting `http_generated_images_path`, but still.

**Comment by chriseppstein** [comment]
Seems to be working in 1.0.0.alpha.17
