### ISSUE TITLE
compass watch not working anymore in 0.13.alpha.4

### ISSUE THREAD

**Issue by julien-c** [Compass/compass#1281]
Hi,

compass watch works fine in `0.12.2`, but fails silently (does nothing) in `0.13.alpha.4`

I'm on Mac OS X 10.7.5, running ruby 2.0, `listen 0.7.3` (and `1.0.3`), `rb-fsevent 0.9.3`.

Best,
Julien

**Comment by scottdavis** [comment]
try using the current master branch and see if you have the same problem

**Comment by julien-c** [comment]
@scottdavis How can I do that? Using `gem`? Thanks for your help (ruby noob here)

**Comment by Anahkiasen** [comment]
As far as I know, as I've encountered the same problem a while back, it stopped working since the `listen` branch merge.

**Comment by julien-c** [comment]
I tried upgrading listen to `1.1.0` (which was just released) but it fails as well.

**Comment by scottdavis** [comment]
@julien-c i would use bundler:
http://gembundler.com/v1.3/git.html

**Comment by Anahkiasen** [comment]
I have the same problem manually checking out the master branch personally.

**Comment by scottdavis** [comment]
can you guys post screen grabs of the terminal or any stack traces you encounter. I don't have any issues running on 10.7 with ruby 2.0

**Comment by Anahkiasen** [comment]
That's the thing, there isn't any stack trace, it just doesn't notice when a change is made in the files. It has no problem compiling apart from that, if I do `compass compile` it compiles fine, and when I do `compass watch` it compiles fine the first time if no file is here. Just, it doesn't actually _watch_.

**Comment by scottdavis** [comment]
Re you mounting over a remote connection or working in a drop box folder? what happens if you force polling?

**Comment by Anahkiasen** [comment]
No, basic environment, one ruby, latest sass, latest compass, basic Compass configuration file. What do you mean by "force polling" ?

**Comment by julien-c** [comment]
@scottdavis `compass watch --poll` doesn't work for me either.

**Comment by scottdavis** [comment]
@Anahkiasen `compass watch --poll`

**Comment by scottdavis** [comment]
@julien-c whats in your compass config file and what directory are you running the watcher from?

**Comment by julien-c** [comment]
``` ruby

# Folders ---------------------------------------------------------- /

project_path     = "./public/app/"
css_dir          = "css"
sass_dir         = "../../app/stylesheet"
fonts_dir        = "fonts"
images_dir       = "img"
javascripts_dir  = "js"

# Options ---------------------------------------------------------- /

output_style     = :nested
preferred_syntax = :scss
line_comments    = false
relative_assets  = true
# sass_options     = {:debug_info => true}

# Extensions ------------------------------------------------------- /

require 'susy'

```

Running from the project's root directory.

**Comment by scottdavis** [comment]
Well you problem is that your sass directory lives outside of the project root. Sadly its a limitation of the new version of compass. Mostly due to the usage of the listen library.

**Comment by scottdavis** [comment]
This is the offending line of code: https://github.com/chriseppstein/compass/blob/master/lib/compass/watcher/project_watcher.rb#L40

**Comment by Anahkiasen** [comment]
I'm afraid it doesn't work better on projects where the sass folder is in the right place :

``` ruby

# Folders ---------------------------------------------------------- /

project_path     = "./public/app/"
css_dir          = "css"
sass_dir         = "sass"
fonts_dir        = "fonts"
images_dir       = "img"
javascripts_dir  = "js"

# Options ---------------------------------------------------------- /

output_style     = :nested
preferred_syntax = :scss
line_comments    = false
relative_assets  = true
# sass_options     = {:debug_info => true}

# Extensions ------------------------------------------------------- /

require 'susy'
```

**Comment by scottdavis** [comment]
remove `project_path     = "./public/app/"` and try it

**Comment by chriseppstein** [comment]
joy.

**Comment by Anahkiasen** [comment]
Well if I remove that... it doesn't find any Sass files, which is logical, because Compass now looks for the `sass` and `css` folder where the config file is located. And I'd like it to stay here, otherwise LiveReload can't find it and plus I prefer my config files to be at the root with all the rest.

**Comment by chriseppstein** [comment]
Try this setting instead:

project_path = File.join(File.dirname(**FILE**), "public/app")

**Comment by Anahkiasen** [comment]
Hm doesn't seem to be working either – it compiles fine, it just doesn't watch.

**Comment by scottdavis** [comment]
anything that sits above the project path is not able to be watched by the new watcher at this time. I've been messing around with ways to fix this that don't involve watching `/`

**Comment by Anahkiasen** [comment]
Well in my case it's not watching above the project path, it's watching under :

```
| config.rb
| public
| -- app
| ---- css
| ---- sass
```

**Comment by scottdavis** [comment]
Grr ok ill look into this in a bit

**Comment by timkelty** [comment]
And update on this?

I have my watched files below my project root, and it still doesn't work for me.
I've also tried running compass from master with no change.

I'm running compass watch from the root of this:

```
| config
| -- compass.rb
| public
| ---- css
| ---- sass
```

`config/compass.rb`:

```
# Paths
project_path    = "./public"
css_dir         = "assets/css"
javascripts_dir = "assets/js"
sass_dir        = "assets/scss"
images_dir      = "assets/img"
fonts_dir       = "assets/fonts"
```

**Comment by timkelty** [comment]
I've also tried `project_path` as `project_path = File.join(File.dirname(__FILE__), "../public")`

**Comment by timkelty** [comment]
Got it to work!
`project_path = File.realpath(File.join(File.dirname(__FILE__), "../public"))`

Using realpath seemed to get it working.

**Comment by vladipus** [comment]
I've met the same difficulties making compass watch actually work. I've switched to using the custom watchr-based scripts, using this tutorial: http://spin.atomicobject.com/2011/07/12/phonegap-with-haml-scss-and-coffeescript/
