### ISSUE TITLE
Calling sprite-url() generates sprite again

### ISSUE THREAD

**Issue by verlok** [Compass/compass#1285]
Hi,
we've noticed that calling the sprite-url() helper makes compass to generate the sprite one more time.

This, plus the usage of any(https://github.com/AdamBrodzinski/Retina-Sprites-for-Compass/blob/master/_retina-sprites.scss) retina sprite generator, increases the build time in production (passing the --force parameter) up to half an hour.

If the sprite-url() helper would be fixed, the time of the build could diminish by an half.

**Comment by scottdavis** [comment]
Its a double edged sword in order to create a sprite url it needs a sprite to be generated. Also, it shouldn't be generated unless it is outdated or the force option is being passed. I have very specific test cases for this so I'm pretty confident that it is working correctly. Can you provide a small example redo that is showing the problem. It may be an implementation problem.

**Comment by scottdavis** [comment]
I just tried there demo using the latest alpha build.

```
[sdavis@Scotts-iMac:demo (master)]$ compass clean
   remove .sass-cache/
   remove css/main.css
   remove images/sprites/buttons-s0a96fceffe.png
   remove images/sprites-retina/buttons-sd2e6693141.png
[sdavis@Scotts-iMac:demo (master)]$ compass compile
   create images/sprites/buttons-s0a96fceffe.png
   create images/sprites-retina/buttons-sd2e6693141.png
unchanged images/sprites/buttons-s0a96fceffe.png
unchanged images/sprites-retina/buttons-sd2e6693141.png
unchanged images/sprites/buttons-s0a96fceffe.png
unchanged images/sprites-retina/buttons-sd2e6693141.png
unchanged images/sprites/buttons-s0a96fceffe.png
unchanged images/sprites-retina/buttons-sd2e6693141.png
   create css/main.css
[sdavis@Scotts-iMac:demo (master)]$ compass compile
unchanged scss/main.scss
[sdavis@Scotts-iMac:demo (master)]$
```

Every thing seems to be working correctly

**Comment by scottdavis** [comment]
The fact that you are passing force is going ot make every sprite call to sprite-url regenerate when its called so I would suggest running without force.
