### ISSUE TITLE
Sprites not generating while using compass via sass command line

### ISSUE THREAD

**Issue by Subash** [Compass/compass#1287]
I am using the following command to use compass

```
sass watch file.scss:file.css --compass

```

``` scss

@import "compass";
@import "icons/*.png";
@include all-icons-sprites;

```

But I am getting

```
Compass::SpriteException: No files were found in the load path matching "icons/*.png". Your current load paths are: ./images
  Use --trace for backtrace.
```

My directory structure

```
style.scss
icons
---png images
```

I think Compass should save generated sprite image inside the icons folder and also look for sass loaded paths for @imports.

https://github.com/sbspk/Prepros/issues/9

**Comment by chriseppstein** [comment]
The path to the images is relative to your images directory so your structure should be:

```
project_root
  images
    icons
      *.png
  sass
    style.scss
```

and you can then invoke like:

`sass watch --compass sass/file.scss:css/file.css`

**Comment by Subash** [comment]
The problem is I have no config.rb file and no compass project.

**Comment by petervanderdoes** [comment]
If you don;t want to create a config.rb then `compass watch --help`  is your friend.
