### ISSUE TITLE
Absolute paths not supported in configuration

### ISSUE THREAD

**Issue by miracle2k** [Compass/compass#129]
This is primarily interesting when setting path option from the command line:

```
$ compass compile --css-dir /tmp src/print.sass
directory tmp/
compile src/print.sass
create tmp/print.css
$ ls tmp/
print.css
```

.

**Comment by chriseppstein** [comment]
This feature will have to wait until after v0.10 is released.

**Comment by chriseppstein** [comment]
This was actually implemented quite a while ago and I forgot to update this issue.

**Comment by maxbeatty** [comment]
It may be helpful to note that absolute paths should be specified with <foo>-path instead of <foo>-dir

http://groups.google.com/group/sass-lang/browse_thread/thread/a738f9cff292b62a
