### ISSUE TITLE
+font-face() doesn't work on IE8

### ISSUE THREAD

**Issue by kraftwer1** [Compass/compass#1292]
```
+font-face("entypo", font-files("entypo/entypo_normal.woff", woff, "entypo/entypo_normal.ttf", truetype, "entypo/entypo_normal.svg", svg), "entypo/entypo_normal.eot")
```

Any idea? It works in IE10 and in Chrome. I double-checked that the fonts exist and the paths are correct.

**Comment by techmagus** [comment]
What is the CSS output?  Your font-face mixin is probably different from mine, so the CSS output would be able to help.

**Comment by kraftwer1** [comment]
It turned out that the .eof file was broken...
