### ISSUE TITLE
Calculate contrast-color($color) using YIQ luma value

### ISSUE THREAD

**Issue by mattdrose** [Compass/compass#1296]
Right now contrast-color($color) uses lightness from the hsl value to figure out what a good contrasting color would be. The problem is that some colors are perceived as darker than others, so you end up with inconsistent readability if used to calculate font color.

[W3C](http://www.w3.org/TR/AERT#color-contrast) suggests that you use YIQ's luma value (the Y) to calculate contrasting colors. This calculates the perceived brightness by the human eye. 

I've created an example to show how it's more accurate in calculating a contrasting color.

[Gist](https://gist.github.com/mattdrose/5638599)
[Codepen Example](http://codepen.io/mattdrose/pen/uLrGC)

Thoughts?

**Comment by chriseppstein** [comment]
This is already on master. See:
- https://github.com/chriseppstein/compass/blob/master/frameworks/compass/stylesheets/compass/utilities/color/_contrast.scss#L29
- https://github.com/chriseppstein/compass/blob/master/frameworks/compass/stylesheets/compass/utilities/color/_brightness.scss#L9-L11

**Comment by mattdrose** [comment]
Did I actually just suggest something that you added yesterday? [Current Status](http://media.giphy.com/media/oXB0K4oFw3fck/original.gif)

**Comment by chriseppstein** [comment]
Well, it was added a couple months ago, but I refactored it yesterday :)
