### ISSUE TITLE
haml-edge dependency doesn't exist

### ISSUE THREAD

**Issue by typerlc** [Compass/compass#13]
Current compass version (0.6.13) has a dependency to haml-edge 2.1.12.  Where does this exist?  I can only find haml-edge 2.1.0

**Comment by hsa** [comment]
I just did a gem install:

<pre>
<code>
$ gem install haml-edge
Successfully installed haml-edge-2.1.16
</code>
</pre>

**Comment by typerlc** [comment]
That worked.  Thanks.  I guess then, the install doco needs to be updated to say this.

**Comment by chriseppstein** [comment]
haml edge is hosted on rubyforge, some older versions of gem don't handle cross-server dependencies. By adding http://gems.github.com/ to you gem server list and not specifying --source for the gem install, you should have installation success. We should update the wiki and blog posts to reflect this, so I'm going to leave this issue open until they do.

**Comment by cartab** [comment]
I added http://gems.github.com/ to my gem server list, and I actually get

# gem install haml-edgeERROR:  could not find gem haml-edge locally or in a repository

Not sure whats going on.

**Comment by chriseppstein** [comment]
haml edge is hosted on rubyforge. compass is hosted on github.

I have:

```
$ gem sources
*** CURRENT SOURCES ***

http://gems.rubyforge.org/
http://gems.github.com/

$ sudo gem install haml-edge --no-ri
Successfully installed haml-edge-2.1.24
1 gem installed
Installing RDoc documentation for haml-edge-2.1.24...
```

I don't have enough details to diagnose your issue.

**Comment by chriseppstein** [comment]
I think this works, closing.
