### ISSUE TITLE
compass 0.10.0 on rails

### ISSUE THREAD

**Issue by arta** [Compass/compass#130]
Hi, 

when I run:
$ compass --rails -f blueprint . --css-dir=public/stylesheets/compiled --sass-dir=app/stylesheets

I get:
WARNING: This interface is deprecated. Please use the new subcommand interface.
See `compass help` for more information.

But compass help is not helpful in this respect (at least I cannot find out what am I supposed to to do).

So, how do I integrate compass 0.10.0 with an existing rails project?

thanks,
martin

**Comment by chriseppstein** [comment]
The main page on the new docs should get you going:
http://compass-style.org/docs/

**Comment by arta** [comment]
Thanks, Chris, that works.
It brings - hopefully a related - question: before, compass would automatically compile the stylesheets, now it doesn't unless I run $ compass watch. Am I missing something?
thanks,
martin

**Comment by chriseppstein** [comment]
Compass doesn't compile stylesheets in a rails app -- Sass does. Compass just helps configure it appropriately. Of course, you can always use `compass compile` or `compass watch` too.

**Comment by arta** [comment]
Ok. So, before installing compass 0.10.0 I didn't need to run 'compass watch' to recompile the stylesheets. After installing compass 0.10.0 I do, why is that?

**Comment by chriseppstein** [comment]
You don't, but you can. just like before.

**Comment by arta** [comment]
If I don't run 'compass watch' and I make a change to a stylesheet, it's not recompiled.

**Comment by chriseppstein** [comment]
re-opening. I've got two reports now of issues getting stylesheets to compile in rails.

here's some debug info: https://gist.github.com/6f73664191cd98a38705

it's like `Sass::Plugin.options` gets reset at some point.

**Comment by chriseppstein** [comment]
mcmoyer self-reports that he had an intializer that is resetting Sass::Plugin.options. @arta, do you set sass::plugin.options = {...} somewhere?

**Comment by arta** [comment]
Not exactly, but maybe something that has a similar effect.

It's haml_sass initializer to be able to use compass/sass/haml on heroku (I hope I will post the code block correctly):

```
# adapted from 
# http://github.com/pedro/hassle/issues/closed#issue/4 (follow Mislav's code)

require 'haml/helpers/action_view_mods'
require 'haml/helpers/action_view_extensions'
require 'haml/template'
require 'sass'
require 'sass/plugin'

Rails::Configuration.class_eval do
  attr_writer :heroku

  def initialize
    super
    @heroku = !!ENV['HEROKU_TYPE']
  end

  def heroku?
    @heroku
  end
end

Sass::Plugin.options[:template_location] = {
  "#{Rails.root}/app/styles" => Rails.configuration.heroku??
    "#{Rails.root}/tmp/stylesheets" : "#{Rails.root}/public/stylesheets"
}

if Rails.configuration.heroku?
  # add Rack middleware to serve compiled stylesheets from "tmp/stylesheets"
  Rails.configuration.middleware.insert_after 'Sass::Plugin::Rack', 'Rack::Static',
    :urls => ['/stylesheets'], :root => "#{Rails.root}/tmp"
end
```

**Comment by chriseppstein** [comment]
Ya. :template_location coming out of compass is now an array of arrays instead of a hash. You'll need to tweak this initializer.

**Comment by arta** [comment]
:) ... dunno how exactly. I'm confused, this looks like a hash to me: 

http://github.com/nex3/haml/blob/master/lib/sass/plugin/rails.rb, lines 4-9

Any suggestion? Thx.

**Comment by chriseppstein** [comment]
Yes. a hash and an array of pairs are both supported by the sass api. an array of pairs should be used when order matters.

**Comment by arta** [comment]
:) I'm just trying to follow you here: http://github.com/chriseppstein/compass/commit/5d0454dc022813884aad5208923c5cd2b954366b

**Comment by arta** [comment]
Chris, it doesn't make sense to me. Even after following the http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html I don't understand what's the point of offering hash (when loading order matters) and how to use the 2-element arrays instead. Because I don't know what the key "#{Rails.root}/app/styles" in :template_locations represents. Can you tell me how this part should be re-written using the arrays so it works?

```
Sass::Plugin.options[:template_location] = {
  "#{Rails.root}/app/styles" => Rails.configuration.heroku? ?
    "#{Rails.root}/tmp/stylesheets" : "#{Rails.root}/public/stylesheets"
}
```

Should the :template_location and :css_location be configured separately?

thx,
martin

**Comment by chriseppstein** [comment]
This snippet will change your generated css location for all path entries:

```
Sass::Plugin.options[:template_location] = Sass::Plugin.options[:template_location].map do |sass_dir, css_dir|
  [sass_dir, Rails.configuration.heroku? ? "#{Rails.root}/tmp/stylesheets" : "#{Rails.root}/public/stylesheets"]
end
```

**Comment by chriseppstein** [comment]
I should point out that if you set the css dir in your compass configuration, you wouldn't need to do this at all.

```
css_dir = defined?(Rails) && Rails.configuration.heroku? ? "tmp/stylesheets" : "public/stylesheets"
```

**Comment by arta** [comment]
Thanks. Just to make sure I understand what is happening. From the variable sass_dir, it looks like the snippet is deciding where to write the .sass files. All this time I thought we wanted to decide where to place the .css files. Aren't the .css files the ones that are written to the file system in runtime? (which is what Heroku doesn't allow)

**Comment by arta** [comment]
Chris, 

it all works now, I used your suggestion but had to put it in the initializer (the compass config file didn't recognize .heroku?). So the relevant part of the initializer looks like this:

```
Sass::Plugin.options[:css_location] = [
  Rails.configuration.heroku? ? "#{Rails.root}/tmp/stylesheets" : "#{Rails.root}/public/stylesheets"
]
```

And compass/sass works on Heroku. 

And the edits of stylesheet templates update the css files automatically (loading [:template_location] with a hash was what caused the problem in this department)

Thanks for your help,
martin

**Comment by arta** [comment]
Hi Chris,
FYI, the initializer as tweaked here doesn't work with rails 2.3.8 - Sass writes files to public and the site crashes on Heroku. When I revert to 2.3.5, it works. Any suggestions?
Thanks,
martin

PS. ... all the running to stay in place ... :)

**Comment by chriseppstein** [comment]
I've not tried upgrading to 2.3.8 yet. But really, it shouldn't be hard to tweak the sass config to write to tmp.

**Comment by arta** [comment]
I didn't write the code, it's mix'n match from several sources. I do not have much experience/knowledge with programming (rails including). I looked briefly inside rails, but didn't spot any promising path.
