### ISSUE TITLE
  # Returns boolean if sprite has a parent

### ISSUE THREAD

**Issue by Nilegfx** [Compass/compass#1304]
I'm search for a way to make a sprite image from a sprite image so i can include small sprite maps into one big sprite image. I ended up with this def in "sprites.rb" file. can you explain the use of this one please and what do you mean by the comment ?

# Returns boolean if sprite has a parent
  def sprite_does_not_have_parent(map, sprite)
    sprite = convert_sprite_name(sprite)
    verify_map map
    verify_sprite sprite
    Sass::Script::Bool.new map.image_for(sprite.value).parent.nil?
  end

**Comment by chriseppstein** [comment]
Sprites of sprites won't be supported. Sprites are complicated enough as it is. But I do want to make it easier to construct a sprite from many different folders.
