### ISSUE TITLE
Use sass's vendored version of Listen.

### ISSUE THREAD

**Issue by foiseworth** [Compass/compass#1306]
Compass requires ~> 1 and Sass requires ~> 0.7. I'm not a ruby expert and I'm unsure if their is an easy method for overcoming this?

``` ruby
/Users/andrew/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:1193:in `block in activate_dependencies': can't satisfy 'listen (~> 1.0.0)', already activated 'listen-0.7.3' (Gem::LoadError)
    from /Users/andrew/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:1185:in `each'
    from /Users/andrew/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:1185:in `activate_dependencies'
    from /Users/andrew/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:1167:in `activate'
    from /Users/andrew/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:48:in `gem'
    from /Users/andrew/.rvm/gems/ruby-2.0.0-p195/bin/compass:22:in `<main>'
    from /Users/andrew/.rvm/gems/ruby-2.0.0-p195/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/andrew/.rvm/gems/ruby-2.0.0-p195/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by foiseworth** [comment]
Looks like @chriseppstein has already started the fix for this on the Sass repo:

https://github.com/nex3/sass/pull/777

**Comment by foiseworth** [comment]
Compass will need to be upgraded to listen 1.1 to support Chris's fix

**Comment by chriseppstein** [comment]
I'm on it. will be fixed today.

**Comment by pshemek** [comment]
Hi, isn't it fixed yet? I'd need to use listen (1.2.3) in my gemset (Middleman app) but I can't...

**Comment by scottdavis** [comment]
@chriseppstein

**Comment by ghost** [comment]
I'm also having troubles with this. Compass 0.13.alpha.4 seems incompatible with guard-compass for similar reasons.

```
Bundler could not find compatible versions for gem "listen":
  In Gemfile:
    compass (~> 0.13.alpha.4) ruby depends on
      listen (<= 0.9.9) ruby

    guard-compass (>= 0) ruby depends on
      listen (1.3.1)
```

**Comment by metaskills** [comment]
The latest Sass master has vendored Listen 1.0 and removed the dependency. Just FYI.

**Comment by aaronjensen** [comment]
seems like compass should vendor as well, yeah? too many people use guard along side compass, i know this prevents us from upgrading.

**Comment by chriseppstein** [comment]
Once sass has embedded listen, I will piggy back on that. We don't need it embed it twice.

**Comment by chriseppstein** [comment]
For reference: https://github.com/nex3/sass/commit/ac6158528adac1298d2a7e30ab50b2796f632acb

**Comment by io41** [comment]
Compass should really nail down what version(s) of sass it works with. Anytime sass upgrades in a compass-incompatible way, we have a broken compass installation. For automated installations that use compass, they currently have to manually lock down the sass version that's to be installed to avoid it braking compass every time there's an upgrade (rather than just installing compass and letting sass get installed as a requirement).

**Comment by chriseppstein** [comment]
@io41 The compass gemspec dictates what versions of sass it is compatible with. I'm not sure what you are doing that allowing compass to run with an incompatible sass version.

`Gemfile`:

``` ruby
source :rubygems
gem 'compass'
```

$ bundle

```
Fetching gem metadata from http://rubygems.org/.............
Fetching additional metadata from http://rubygems.org/..
Resolving dependencies...
Using chunky_png (1.3.0)
Using fssm (0.2.10)
Installing sass (3.2.14)
Installing compass (0.12.3)
Using bundler (1.5.0.rc.2)
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

Or the latest prerelease:

```
source :rubygems

gem 'compass', '1.0.0.alpha.18'
```

```
$ bundle
Resolving dependencies...
Using rake (10.1.1)
Using chunky_png (1.3.0)
Using multi_json (1.9.0)
Using sass (3.3.0)
Using compass-core (1.0.0.alpha.17)
Using compass-import-once (1.0.2)
Using json (1.8.1)
Using rb-fsevent (0.9.4)
Using ffi (1.9.3)
Using rb-inotify (0.9.3)
Using rb-kqueue (0.2.2)
Using listen (1.1.6)
Using compass (1.0.0.alpha.18)
Using bundler (1.5.0.rc.2)
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
$  bundle exec compass create updatedsass
directory updatedsass/
directory updatedsass/sass/
directory updatedsass/stylesheets/
   create updatedsass/config.rb
   create updatedsass/sass/screen.scss
   create updatedsass/sass/print.scss
   create updatedsass/sass/ie.scss
   create updatedsass/stylesheets/ie.css
   create updatedsass/stylesheets/print.css
   create updatedsass/stylesheets/screen.css

<snip/>

$  bundle exec compass watch
$  bundle exec compass watch updatedsass
The source :rubygems is deprecated because HTTP requests are insecure.
Please change your source to 'https://rubygems.org' if possible, or 'http://rubygems.org' if not.
>>> Compass is watching for changes. Press Ctrl-C to Stop.
     info updatedsass/sass/print.scss was modified
overwrite stylesheets/print.css
^C
Happy Styling!
```

So as far as I know, compass has "nailed down" sass versions support. If you have a specific support issue or bug, please provide details.

**Comment by manuelmeurer** [comment]
Now that `sass` 3.3.3 is out, can you cut a new `compass` release depending on it and remove the `listen` dependency?

**Comment by io41** [comment]
@chriseppstein nice one! We were using v0.12.2 which did not have it locked down yet.
