### ISSUE TITLE
Refresh 2 times

### ISSUE THREAD

**Issue by jduarte** [Compass/compass#131]
Hi there,

First of all I gotta admit, compatible scss with CSS files are great because they allow smoother development cycles and ... Compass 0.10 is really great.

But I'm having a small issue, I need to refresh my browser 2 times instead of one to generate the CSS file, any idea of what this might be?

Using compass 0.10.0 in Mac OS X

Thanks and keep up the great work

**Comment by chriseppstein** [comment]
I assume you're using rails. In which case, this is likely a haml bug if it is one.

**Comment by chriseppstein** [comment]
Can I close this?

**Comment by chriseppstein** [comment]
I have no other reports of this and it's unlikely that it could be a compass bug. Please file a new bug with exact steps to reproduce if you continue to have issues.
