### ISSUE TITLE
image-width and image-height doesn't work for generated images

### ISSUE THREAD

**Issue by fedotxxl** [Compass/compass#1324]
My generated images (sprites) and original images are placed in different folders. How can I get width/height of generated image?

**Comment by micahgodbolt** [comment]
You use image-width(sprite-file($map, $sprite))

from http://compass-style.org/reference/compass/helpers/sprites/#sprite-file
sprite-file($map, $sprite)

"Returns the relative path (from the images directory) to the original file used when construction the sprite. This is suitable for passing to the image-width and image-height helpers."

**Comment by dadmin** [comment]
1. As I understand `sprite-file($map, $sprite)` returns path to source image - not generated one.
2. (doesn't concerns this ticket) I've got a problem with `sprite-file($map, $sprite)` - it returns absolute path to the source image, not relative one =(

**Comment by scottdavis** [comment]
This is fixed on master there have been functions added to get the dimensions of a sprite. https://github.com/chriseppstein/compass/blob/master/lib/compass/sass_extensions/functions/sprites.rb#L18-L35
