### ISSUE TITLE
Rails support confusion

### ISSUE THREAD

**Issue by mikexstudios** [Compass/compass#133]
I'll preface by saying I'm a rails noob so this may be obvious, but it wasn't obvious to me at first. The docs page: http://compass-style.org/docs/ states that to add compass to rails, just run: 
    compass init rails /path/to/myrailsproject

So, I ran that and then tried to start script/server which errored: 
    ...
    initializers/compass.rb:3: undefined method `add_project_configuration' for Compass:Module (NoMethodError)
    ...

It took me a little while to realize that I had to add:
    config.gem 'compass'
to environment.rb.

Is this a bug in the compass-rails install script? Or is this something obvious to people who use rails?

Using compass 0.10.0 and rails 2.3.5.

**Comment by chriseppstein** [comment]
I'll update the docs.

**Comment by chriseppstein** [comment]
fixed. The documentation that is printed out after running the command has been improved.
