### ISSUE TITLE
Copy properties from one class to another

### ISSUE THREAD

**Issue by ghost** [Compass/compass#1330]
It'd be nice to have defined mixin to copy/Inherit properties from one class to another. eg:

.article-post {
  border: 2px ridge crimson;
  @include border-radius(10px);
  color : red;
  background-color : blue;
}

I want the almost same properties in my other class, so it would be nice to have something like:

.div-news {
  @include properties(.article-post); // Calling properties defined in .article-post
  border: 2px solid green; // Overwriting from previous property
}

I know this can be achieved with defining a separate Mixin, or using both classes in the HTML class, but this will be Father of all mixins, if I can copy properties of other classes defined previously. Now I can call other class and have its property in it like:

.copier-class {
  @include properties(.div-news); // Calling properties defined in .div-news
  font-size : 1.5em;
}

Like so, these properties could be copied to another class

.last-class {
  @include properties(.copier-class);
  text-transform : uppercase;
}

**Comment by Anahkiasen** [comment]
Isn't that what the native `@extend` does in essence ?

**Comment by ghost** [comment]
Indeed, it was the thing I have been looking for. This project needs serious documentations and easy navigation to docs (I have been looking for it whole day and only Helper I found was enumerate).

**Comment by chriseppstein** [comment]
Compass is a framework on top of Sass. It does not document the Sass language. Please familiarize yourself with the language facilities of Sass here: http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html
