### ISSUE TITLE
Going crazy Less+Scss at same time

### ISSUE THREAD

**Issue by shanimal** [Compass/compass#1331]
I was delighted to find that when I first installed CodeKit I could import Less files into my Scss files?!!! I just installed the update and this doesn't seem to be the case anymore.

Maybe I was imagining things, but if I was... my imagination is brilliant!

**Comment by chriseppstein** [comment]
I have no idea how this would work, but if it did, you should contact codekit, not compass.

**Comment by shanimal** [comment]
seems like it could work if there was some kind of layer that stored variables, functions etc...

but right, wrong project. apologies etc... thank you.
