### ISSUE TITLE
Compilation feature to redirect output for sprites.

### ISSUE THREAD

**Issue by roydukkey** [Compass/compass#1332]
This is a request for a feature similar to the current `compass compile --css-dir "data/compass"`. In the same way `--css-dir` works, the redirection of sprite outputs should be available.

In cases, it would be valuable to change the image directory from the command. `compass compile --css-dir "data/compass" --sprite-dir "data/compass/image"`

Likewise, this setting should be available in the `config.rb`, as there is currently, `sass_dir` & `css_dir`.

**Comment by piouPiouM** [comment]
In your `config.rb`, the `generated_images_dir` option should meet your needs.
From the command line, use the option `--generated-image-path`.

See the [configuration reference](http://compass-style.org/help/tutorials/configuration-reference/) for more information.

**Comment by roydukkey** [comment]
I'm afraid that doesn't work. `--generated-image-path` isn't available with the `compass compile` command.

```
compass compile "style/test.sass" --trace --debug-info --generated-image-path ".sass-cache"

Error: invalid option: --generated-image-path

Usage: compass compile [path/to/project] [path/to/project/src/file.sass ...] [options]

...
```
