### ISSUE TITLE
Incompatibility with Sass 3.3 Alpha

### ISSUE THREAD

**Issue by Snugug** [Compass/compass#1339]
I'm attempting to use Compass with Sass 3.3.alpha, version controlled through Bundler and I can't. When using Compass 0.12.2, I get no dependency issues but I get Compass errors. When using Compass 0.13.alpha, I get Bundler dependency issues:
### Bundler

```
gem 'sass', '~>3.3.0.alpha.198'
gem 'compass', '>=0.12.2'
```
### Error

```
/Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches/browser_support.rb:1:in `require': no such file to load -- sass/script/node (LoadError)
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches/browser_support.rb:1
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:2:in `require'
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:2
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1:in `each'
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass/sass_extensions.rb:9:in `require'
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass/sass_extensions.rb:9
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass.rb:5:in `require'
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass.rb:5
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass.rb:4:in `each'
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass.rb:4
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/bin/compass:20:in `require'
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/bin/compass:20
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/bin/compass:8:in `fallback_load_path'
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/bin/compass:19
    from /usr/local/bin/compass:23:in `load'
    from /usr/local/bin/compass:23
```
### Bundler

```
gem 'sass', '~>3.3.0.alpha.198'
gem 'compass', '~>0.13.alpha.4'
```
### Error

```
Resolving dependencies...
Bundler could not find compatible versions for gem "sass":
  In Gemfile:
    compass (~> 0.13.alpha.4) ruby depends on
      sass (~> 3.2.5) ruby

    sass (3.3.0.alpha.198)
```

**Comment by gerryster** [comment]
I am having the exact same "no such file to load -- sass/script/node" issue with version 3.3.0.alpha.212.

**Comment by dmackerman** [comment]
Same here. Bummer because SASS 3.3.0 alpha is required to get source maps working properly, AFAIK.

Update: 

Seems that these 2 versions work together. 

```
gem 'sass', '3.3.0.alpha.149'
gem 'compass', '0.12.2'
```

**Comment by riddla** [comment]
This combination is finally working for me to bring Compass and SASS Sourcemaps together:

## Gemfile

```
gem 'sass', '3.3.0.alpha.149'
gem 'compass', '0.12.2'
gem 'compass-sourcemaps', "~> 0.12.2.sourcemaps.57a186c"
```

## Compass config.rb

```
sass_options = {:sourcemap => true}
```

**Comment by gerryster** [comment]
Interesting, although I had the same node problem with this combination:

``` ruby
gem 'sass', '3.3.0.alpha.212'
gem 'compass, '0.12.2'
gem 'compass-sourcemaps', "~> 0.12.2.sourcemaps.57a186c"
```

**Comment by patrick-wc** [comment]
Thanks a lot @riddla that setup worked for me (Windows 7).

**Comment by jeffbyrnes** [comment]
@riddla that combination was no good for me, unfortunately. Haven't had time to try out @gerryster's combo though.

**Comment by teameh** [comment]
The following worked fine for me on Windows 7 and OSX 10.8.4

```
sass: 3.3.0.alpha.222
compass: 0.13.alpha.4
compass-sourcemaps: 0.12.4.sourcemaps.a4836f1
```

All installed with `sudo gem install {GEMNAME} --verbose --pre` 

config.rb looks like: 

```
sass_options = {:sourcemap => true}
enable_sourcemaps = true 
```

**Comment by thomaswelton** [comment]
Thanks @riddla that worked for me.

**Comment by Snugug** [comment]
Just as a clarification, the proposed solution specifically does not work with Bundler for version control. IMO, it needs to work under Bundler version control in order to work, and currently Compass 0.13.alpha.4 _is not compatible with Sass >3.2_ under version control.

**Comment by RaphaelDDL** [comment]
@riddla 's solution worked as well for generating the maps when using `compass watch`.  :+1: 

The only problem now lies within compass sprites:

```
WARNING: Couldn't determine public URL for "someIconSpriteFolder/*.png" while generating
sourcemap.
  Without a public URL, there's nothing for the source map to link to.
  Custom importers should define the #public_url method.

ArgumentError on line ["500"] of C: different prefix: "C:/" and "D:/path/to/my/cssFolder"
```

When using something like this:

```
  @import "compass/utilities/sprites";
  $someIconSpriteFolder-spacing: 25px;
  @import "someIconSpriteFolder/*.png";
  @include all-someIconSpriteFolder-sprites;
```

I just tested and _seems_ it has nothing to do with project using sass is on D: while ruby/sass/compass are on C:. With project on C:, the `#public_url` error persists. But the `ArgumentError` does not O.o

**Comment by zemd** [comment]
@Snugug while gem in rubygems is not updated, for providing bundler work correctly there should be set gem dependency from github:

```
gem 'compass', :git => 'https://github.com/chriseppstein/compass.git', :branch => 'master'
```

**Comment by gisu** [comment]
Can anybody from the team release a new --pre gem? Would be a help when other Members in the Team working with the newest compass version.

**Comment by audsKu** [comment]
@riddla thank you. That combo works for me as well.

**Comment by chriseppstein** [comment]
This is all working now.

**Comment by jmuheim** [comment]
I have similar issues with sass-rails and compass-rails. Did anyone get this to work in a Rails app?

**Comment by ngottlieb** [comment]
Upgrading to Compass 0.12.3 solved the problem for me.
