### ISSUE TITLE
Can't make sprites from image that has name starting with number

### ISSUE THREAD

**Issue by hrsetyono** [Compass/compass#1342]
Hi, when I tried making sprites from a PNG that starts with number (example: 001.png), it returns this error:

`Compass::Error on line ["92"] of C: Sprite file names must be legal css identifi
ers. Please rename 001.png`

If if rename 001.png to something else, it works fine. But it will be a problem when I have a whole set of icons that starts with its size like `32_edit.png` or `32_delete.png`

I use a very basic code:

```
@import "my-icons/*.png";
@include all-my-icons-sprites;
```

It seems compass prevents it because it could produce `css` class name that start with number like `.001{...}`. But the generated `css` already has `.my-icons-` prefix, so it shouldn't be a problem right?

**Comment by scottdavis** [comment]
Correct, this is a limitation of sass vars internally starting with a number. We may address this in the future but for now it's a low priority

**Comment by hrsetyono** [comment]
@scott Thanks for the reply :)

By the way, It would be good if symbol in file's name is also allowed.

Just now, I'm trying to create retina sprites, but all my retina icons contain `@2x` which cause error for the reason as above.
