### ISSUE TITLE
Add webp support for created sprites

### ISSUE THREAD

**Issue by tinganho** [Compass/compass#1345]
I would like to have the created sprites to have webp support

**Comment by scottdavis** [comment]
You are welcome to make an extension that adds this support but we as the core team don't have any other plans outside of supporting PNG's.

**Comment by tinganho** [comment]
I would like to create such an extension. But I think creating this compass extension will be very hard for me? Since Compass controls all sprites functionality? Or could you give some info how to do such an extension?
