### ISSUE TITLE
linear-gradient IE10 and prefixed/old version

### ISSUE THREAD

**Issue by geniou** [Compass/compass#1351]
Hi,

I searched in the issues and I'm wondering if I'm really the first one with this problem:

As far as I understood the IE10 supports linear-gradient out of the box. They are supporting the standard without any prefix - e.g. `background-image: linear-gradient(to bottom, red, green);` - the direction has to be like this `to <side-or-corner>`. Unfortunately old browsers with prefix and CSS3Pie seems to rely on the old, deprecated version of the direction, e.g. `background-image: -webkit-linear-gradient(top, red, green);`.

Documentation: https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient

Is there a way to have this behavior in compass? So there needs to be a translation of the direction e.g. between `to bottom` to `top` for the prefixed versions.

Nils.

**Comment by mirisuzanne** [comment]
You're not the first. This has already been implemented for 0.13 - currently in alpha.

**Comment by geniou** [comment]
Thanks for the fast response. Looking forward to this feature.
