### ISSUE TITLE
Legacy IE support not working

### ISSUE THREAD

**Issue by miraff** [Compass/compass#1356]
Hi!

I am using Compass 0.12.2

I am importing Compass like this:

```
@import "compass";
```

I set up the watcher like this:

```
sass --watch project:project --compass
```

I am writing my code in .scss file like this:

```
@include background-image(linear-gradient(#ffffff, #f0f1f2 180px, #f0f1f2));
```

What it will generate from it is this:

```
background-image: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(0%, #ffffff), color-stop(180px, #f0f1f2), color-stop(100%, #f0f1f2));
  background-image: -webkit-linear-gradient(#ffffff, #f0f1f2 180px, #f0f1f2);
  background-image: -moz-linear-gradient(#ffffff, #f0f1f2 180px, #f0f1f2);
  background-image: -o-linear-gradient(#ffffff, #f0f1f2 180px, #f0f1f2);
  background-image: linear-gradient(#ffffff, #f0f1f2 180px, #f0f1f2);
```

What is the problem:

It does not generate IE compatible code, no gradients, filters, nothing. As you can see it only generates css for modern browsers (webkit, moz, ...). I searched this problem online, but I am under the impression that this should work out of the box and for some strange reason it does not work for me. Could anyone help me with this please?

**Comment by Anahkiasen** [comment]
Did you enable the `$legacy-support-for-ie` variable ?

**Comment by miraff** [comment]
Thanks for such a quick reply, yes I tried probably all from this page:

http://compass-style.org/reference/compass/support/

I wrote it like this:

```
@import "compass";
$legacy-support-for-ie: true;
```

**Comment by miraff** [comment]
I also tried:

```
$experimental-support-for-mozilla: false;
```

And that indeed worked, it was no longer generating -moz- prefixes.
No idea what to try now.

**Comment by miraff** [comment]
Got more info, the only IE related prefix that is being generated is for border-radius and it is the -ms-. But -ms- is still not generated for gradients.

```
@include border-radius(99px);
```

```
-webkit-border-radius: 99px;
-moz-border-radius: 99px;
-ms-border-radius: 99px;
-o-border-radius: 99px;
border-radius: 99px;
```

I also tried some online js fiddle with scss support and my below declaration worked there fine.

```
@include background(linear-gradient(#ffffff, #f0f1f2 180px, #f0f1f2));
```

It produced this with the -ms- in there:

```
background: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(0%, #ffffff), color-stop(180px, #f0f1f2), color-stop(100%, #f0f1f2));
background: -webkit-linear-gradient(#ffffff, #f0f1f2 180px, #f0f1f2);
background: -moz-linear-gradient(#ffffff, #f0f1f2 180px, #f0f1f2);
background: -o-linear-gradient(#ffffff, #f0f1f2 180px, #f0f1f2);
background: -ms-linear-gradient(#ffffff, #f0f1f2 180px, #f0f1f2);
background: linear-gradient(#ffffff, #f0f1f2 180px, #f0f1f2);
```

**Comment by miraff** [comment]
Found this thread, might be relevant:

https://github.com/chriseppstein/compass/issues/1333

Will try installing compass alpha

**Comment by miraff** [comment]
Installed the latest alpha, even did this:

```
@import "compass";
@import "compass/support";
@charset "utf-8";

$legacy-support-for-ie: true;
$legacy-support-for-ie6: true;
$legacy-support-for-ie7: true;
$legacy-support-for-ie8: true;
$experimental-support-for-microsoft: true;
```

And still not working. On top of that, now the -ms- prefix on border-radius is not generating - which it was on stable release.

**Comment by mirisuzanne** [comment]
Nothing here is broken (except how long 0.13 is taking). Looking for the -ms- prefix is a terrible way to check IE support. There's no need for -ms- on gradients if you use the new official syntax, and the alpha does that. There is also no need for -ms- on border-radius — which is why it was removed. It was there in stable _in case_ we would need it. We don't. IE went straight from no-support to official support, without ever prefixing. 

You have to check the caniuse.com tables to see what should work, and compare that with what you see working, before you can say that IE-support is broken.

**Comment by miraff** [comment]
Thanks for clearing it up for me Eric. Had no idea IE went with official no-prefix in the end. But I should have emphasized I am more in need of the old IE filter declarations. Not sure if they are part of Compass default or not. Trying to be IE8+ compatible with my projects at the moment.

**Comment by mirisuzanne** [comment]
Compass does not generally support old proprietary features (like old IE filters) in the CSS3 module. You can use [CSS Pie](http://compass-style.org/reference/compass/css3/pie/) to achieve some additional tricks in old-IE, but it comes with a performance cost. In most cases I recommend letting the IE8/9 dwindling user-base live without gradients. Compatible != identical.
