### ISSUE TITLE
dynamic sass functions for sprite_width and sprite_height

### ISSUE THREAD

**Issue by designerdean** [Compass/compass#1357]
The Compass sprite feature lets you dynamically set the width and height in each generated class with:

```
$icons-sprite-dimensions: true;
```

However, it doesn't seem there is a way to dynamically grab the height and width of each icon to be used in a variable. Am I wrong?

For instance:

```
$height: icon-sprite-height;
$width: icon-sprite-width;

.icon-sprite {
  height: $height/2; // divide height by 2
  width: $width/2; // divide width by 2
}
```

This way, it would be quite easy to have retina support.

**Comment by scottdavis** [comment]
Already on master and in the current alpha.

**Comment by designerdean** [comment]
Are you sure? I see in the documentation where you can get the width and height for a specific image (http://compass-style.org/help/tutorials/spriting/#sass_functions):

```
$height: icon-sprite-height(some_icon);
$width: icon-sprite-width(some_icon);
```

But this requires you to specify a certain icon. This doesn't help if you have varying icon sizes. In addition, this doesn't work:

```
$height: icon-sprite-height;
$width: icon-sprite-width;
```

BTW, I'm using Compass 0.13.alpha.4

**Comment by scottdavis** [comment]
Just the function without passing in a sprite

**Comment by scottdavis** [comment]
May need to add
'()'

**Comment by designerdean** [comment]
See the attached screenshot. I've tried it both ways. My directory name where the original icon images are found is called "markers".

![screenshot](https://f.cloud.github.com/assets/729893/932115/e9e4a928-0039-11e3-8923-4905a6368f77.jpg)

**Comment by piouPiouM** [comment]
If you want to retrieve the width of the sprite map, the correct syntax is:

``` scss
@import "markers/*.png";
@include all-markers-sprites;

$width: sprite-width($markers-sprites);

// …
```

Compass store the sprite map in a variable `$<map>-sprites` after importing images (eg `@import "<map>/*.png"`).
