### ISSUE TITLE
Compass.configure_sass_plugin! wipes out any existing template locations

### ISSUE THREAD

**Issue by jfirebaugh** [Compass/compass#136]
If you use Sass::Plugin.add_template_location prior to calling Compass.configure_sass_plugin!, any template locations added are wiped out by compass. Instead compass should be merging template locations into the Sass configuration using add_template_location.

**Comment by chriseppstein** [comment]
Yes, you're right. But the add_template_location was just introduced (and it was my idea ;) -- so I haven't yet had time to start using it.

As a work around, please consider adding some calls to `add_import_path` in your compass config.

**Comment by chriseppstein** [comment]
[Rails] When configuring the Sass::Plugin, don't overwrite existing template locations. Closed by 869e0bfac784e061ae2e10e3275d726fcea13269.
