### ISSUE TITLE
Spacing between images within sprite

### ISSUE THREAD

**Issue by JamyGolden** [Compass/compass#1363]
I'm trying to create a 1px or 2px transparent gap between the various images within a sprite.

When you zoom in/out in a browser you can see a tiny bit of the image above or below or next to desired image. I can get around this by doing this: `$icon-layout: diagonal;`. However that can really increase the file size of the sprite. So I'm hoping a 1px or 2px gap will fix the problem.

**Comment by mirkovnemanja** [comment]
Hello,

before generate sprites put this line

$sprites-spacing: 2px;

**Comment by JamyGolden** [comment]
Thanks a lot!

**Comment by mirkovnemanja** [comment]
No problem :)

**Comment by jednano** [comment]
1. Where is `$sprites-spacing` documented? I can't find it.
2. This doesn't work for me.

**Comment by killerbytes** [comment]
it means `$<map>-spacing`
http://compass-style.org/help/tutorials/spriting/customization-options/
