### ISSUE TITLE
Deprecated Sass functionality used in Compass spriting

### ISSUE THREAD

**Issue by aramando** [Compass/compass#1369]
I'm getting the following warning when compiling my Compass project:

```
DEPRECATION WARNING on line 209 of species-detail/icon-*.png:
  @extending an outer selector from within @media is deprecated.
  You may only @extend selectors within the same directive.
  This will be an error in Sass 3.3.
  It can only work once @extend is supported natively in the browser.
```

lines 206-211 of the magic stylesheet referred to look like this:

``` scss
// Extends the sprite base class and set the background position for the desired sprite.
// It will also apply the image dimensions if $dimensions is true.
@mixin species-detail-sprite($name, $dimensions: $species-detail-sprite-dimensions, $offset-x: 0, $offset-y: 0) {
  @extend #{$species-detail-sprite-base-class};
  @include sprite($species-detail-sprites, $name, $dimensions, $offset-x, $offset-y)
}
```

**Comment by scottdavis** [comment]
are you sure the deprecation isn't caused by this line `@extend #{$species-detail-sprite-base-class};`

**Comment by aramando** [comment]
I assume that it is. Sorry if this wasn't clear enough, but those lines of scss are from the spriting stylesheet that Compass auto-generates and then usually holds in memory, although to see the code causing the warning I saved it do disk using  `compass sprite "species-detail/icon-*.png"`. In other word, Compass is currently relying on deprecated Sass syntax.

**Comment by scottdavis** [comment]
you must be trying to use the sprite inside a `@media` query which the only way i can think of that this warning would be shown.

**Comment by aramando** [comment]
Ah, yes I was. So is this no longer supported (if it ever was)?

As it happens I have since changed to using the `sprite()` helper instead of `@include species-detail-sprite` so that I can control positioning, so this is no longer a problem for me anyway.
