### ISSUE TITLE
Syntax error: Mixin \"xxx\" does not accept a content block.

### ISSUE THREAD

**Issue by ghost** [Compass/compass#1371]
The code is:
@mixin button() {
    display: block;
    text-decoration: none;
    @content;
}
.alert {
    @include button {
        color: #f00;
    }
}

and it has a error like title

**Comment by cimmanon** [comment]
Are you certain you aren't redefining your mixin elsewhere?  That code compiles fine for me.

**Comment by ghost** [comment]
At last, I reinstall SASS and it can work.

2013/9/5 cimmanon notifications@github.com
