### ISSUE TITLE
Disable cache busting

### ISSUE THREAD

**Issue by simonrenoult** [Compass/compass#1374]
Hi,

Compass uses cache busting on sprites which is nice, however this behavior is compulsory and the only way to delete these hashes it is to create your own function and add it to the "flow", as shown here : http://stackoverflow.com/questions/9183133/how-to-turn-off-compass-sass-cache-busting

Could this behavior be configurable ?

**Comment by scottdavis** [comment]
It's not a cache buster in the sense of the web it's a uniqueness  hash. It's how compass tracks changes to the sprite file so that we know if it needs to be recompiled

**Comment by ADDeveloper** [comment]
Please insert an option for generate sprite file without uniqueness id and update css generated too.
or
Please use another mechanism for knowing which file to recompile.
