### ISSUE TITLE
Submit gem to rubyforge

### ISSUE THREAD

**Issue by pointlessone** [Compass/compass#14]
I found a project on rubyforge but no gems on there. Why not submit gem there?

**Comment by chriseppstein** [comment]
The plan is to host the stable gem there and the development gem on github. The account is a placeholder until I get around to it. Maybe I can do it for the 0.8 release.

**Comment by adamsalter** [comment]
Github gems are no more. I've since learnt that you can create 'prerelease' gems with a special version string:

http://rubygems.rubyforge.org/rdoc/Gem/Version.html

I'm changing all my old github gems back to normal syntax... `ERROR:  could not find gem compass locally or in a repository` ;)

**Comment by Mange** [comment]
You could move it to Gemcutter instead. It should be a bit easier, and it seems like Gemcutter might take over gem hosting from Rubyforge.

**Comment by chriseppstein** [comment]
The compass gem is already on gemcutter:

http://gemcutter.org/gems/compass

This is where I'll posting new releases.

**Comment by Mange** [comment]
Sorry, I see what the problem was now. I was trying to install 0.8.15, which does not exist on gemcutter. When I upped the version number everything worked.
