### ISSUE TITLE
Malformed version number string 0.11..alpha.0.c9b05cb

### ISSUE THREAD

**Issue by tricomsol** [Compass/compass#140]
while updating my gem with bundle install which fetches latest compass from git repo i am getting this error here is the trace output 

  from /home/hemant/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/site_ruby/1.8/rubygems/version.rb:173:in `new'
        from /home/hemant/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/site_ruby/1.8/rubygems/version.rb:173:in`create'
        from /home/hemant/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/site_ruby/1.8/rubygems/specification.rb:1366:in `version='
        from /home/hemant/.bundle/ruby/1.8/bundler/gems/compass-dcbe0c41f22c777e90babfa80d61f78dfdea41b2-master/compass.gemspec:6
        from /home/hemant/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/site_ruby/1.8/rubygems/specification.rb:425:in`initialize'
        from /home/hemant/.bundle/ruby/1.8/bundler/gems/compass-dcbe0c41f22c777e90babfa80d61f78dfdea41b2-master/compass.gemspec:4:in `new'
        from /home/hemant/.bundle/ruby/1.8/bundler/gems/compass-dcbe0c41f22c777e90babfa80d61f78dfdea41b2-master/compass.gemspec:4

**Comment by chriseppstein** [comment]
fixed by cebd685
