### ISSUE TITLE
runaway ruby process on compass compile

### ISSUE THREAD

**Issue by tsargent** [Compass/compass#1401]
I'm suddenly encountering a runaway Ruby process when I try to compile my sass files:

```
20808:project tsargent$ compass compile
   remove .sass-cache/ 
   remove stage/assets/css/icons.css 
   remove stage/assets/css/reset_extra.css 
   create stage/assets/css/icons.css 
   create stage/assets/css/reset_extra.css 
Killed: 9
20808:project tsargent$ 
```

... where "Killed: 9" is me killing the Ruby process.  Any advice on how to debug this?

**Comment by chriseppstein** [comment]
Put some `@warn` directives in your code. you probably have an infinite loop somehow.
