### ISSUE TITLE
Installing on windows

### ISSUE THREAD

**Issue by iagowp** [Compass/compass#1402]
First of all, im sorry if this is not the proper place, or its a repeated issue, but i couldnt find anything related.

when i use gem install compass, i get the folowing:
ERROR:  Could not find a valid gem 'compass' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect retur
ned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (
https://s3.amazonaws.com/production.s3.rubygems.org/latest_specs.4.8.gz)

And i have no idea why, any thoughts?

**Comment by er1z** [comment]
Haven't you blocked the Ruby's process in firewall?

It's almost definitely a problem with your Internet connection or configuration.

**Comment by stansidel** [comment]
It's an issue with the SSL certificates on your machine. This article helped me with the issue - http://railsapps.github.io/openssl-certificate-verify-failed.html. The solution for Windows is given in the end of the article.

**Comment by iagowp** [comment]
Yeah, it was ssl, thank you.

**Comment by ajilon-ww** [comment]
Thanks a lot. Sorted out my issue.
