### ISSUE TITLE
compass watch error with Compass 0.13.alpha.7 update

### ISSUE THREAD

**Issue by ninjasort** [Compass/compass#1406]
Errno::EACCES on line 1039 of /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/fileutils.rb: Permission denied - /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.7/frameworks/compass/stylesheets/.listen_test
Run with --trace to see the full backtrace

**Comment by ninjasort** [comment]
Updated PATH with path to ruby gem dir from homebrew.

**Comment by Anahkiasen** [comment]
How did you fix that ? I have Ruby installed with RVM, I'm getting the same thing :

```
overwrite css/styles.css
Errno::EACCES on line ["1143"] of /Users/anahkiasen/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/fileutils.rb: Permission denied - /Users/anahkiasen/.rvm/gems/ruby-2.0.0-p247@develop/gems/compass-0.13.alpha.9/frameworks/compass/stylesheets/.listen_test
Run with --trace to see the full backtrace
```

**Comment by ninjasort** [comment]
Try checking your PATH to make sure ruby is getting the right gems from rvm.

**Comment by dgsunesen** [comment]
I'm experiencing the same problem. What exactly should you put in the paths file to make it work?

**Comment by ninjasort** [comment]
I'm pretty sure you want to have the path to ruby and ruby gems. If you `pwd ruby` and `pwd compass` you should make sure that they're in your PATH. `echo $PATH` 

For example, mine are in `/usr/local/bin:/usr/local/opt/ruby/bin`

**Comment by DanielaValero** [comment]
Hi, I am having this same problem and my paths are properly set, 

get this:

Errno::EACCES on line ["1143"] of /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb: Permission denied - /Library/Ruby/Gems/2.0.0/gems/compass-0.13.alpha.12/frameworks/compass/stylesheets/.listen_test

Do you have an idea about what can it be?

**Comment by DanielaValero** [comment]
Have this version: Compass 0.13.alpha.12

**Comment by DanielaValero** [comment]
Fixed, it was the permissions of this folder: /Library/Ruby/Gems/

**Comment by scottdavis** [comment]
dup #1497
