### ISSUE TITLE
`gem install compass -v '0.13.alpha.7'` fails

### ISSUE THREAD

**Issue by mgol** [Compass/compass#1408]
I cannot install the latest alpha of Compass:

``` bash
$  ruby --version
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin12.4.0]
$  gem --version
2.0.3
$  gem install compass -v '0.13.alpha.7'
ERROR:  While executing gem ... (NoMethodError)
    undefined method `size' for nil:NilClass
```

EDIT: to clarify, I'm on OS X 10.8.5, ruby is installed via Homebrew.

**Comment by chriseppstein** [comment]
This appears to be an issue with your ruby environment?

```
➜  ~  rbenv version
2.0.0-p247 (set by RBENV_VERSION environment variable)
➜  ~  gem -v
2.0.3
➜  ~  gem install compass -v '0.13.alpha.7'
Fetching: compass-0.13.alpha.7.gem (100%)
    Compass is charityware. If you love it, please donate on our behalf at http://umdf.org/compass Thanks!
Successfully installed compass-0.13.alpha.7
1 gem installed
```

**Comment by mgol** [comment]
@chriseppstein Could you point me to any direction what could possibly be wrong? I didn't create any custom environments, I've just used default Homebrew packages; if their package is broken, could you tell in what way by the error message?

**Comment by mgol** [comment]
Reported to Homebrew as I just used the defaults: https://github.com/mxcl/homebrew/issues/23253

**Comment by mgol** [comment]
OK, you were right it has to be sth with my install. A weird error, though. Thanks for help!
