### ISSUE TITLE
css3/transition mixins do not properly unquote comma-separated parameters

### ISSUE THREAD

**Issue by triplepoint** [Compass/compass#141]
while the "transition-property" mixin does properly unquote($properties), the "transition-duration", "transition-timing-function", and "transition-delay" do not unquote() the $duration, $function, and $delay parameters, respectively.

**Comment by chriseppstein** [comment]
I'll add unquote()'s. But there's no need to pass a string.

**Comment by chriseppstein** [comment]
[Compass Core] Don't suggest putting some values in quotes unecessarily, and unquote them if the user has.
Closed by ed35a3eb2443fc9bbbe59f30b8a57f23f6ed958f.  Closed by ed35a3eb2443fc9bbbe59f30b8a57f23f6ed958f.
