### ISSUE TITLE
css3/gradient does not apply the background image in the correct order

### ISSUE THREAD

**Issue by triplepoint** [Compass/compass#142]
The css3/gradient package allows for an optional image to be passed, and the example says it will "yields a linear gradient on top of a background image".  

However the order of generated css background elements puts the optional image first, which results in the gradient being behind the image.  The correct result should put the optional image at the end of the comma-separated background values, so that the generated gradients are above the image.

This is true for both linear-gradient and radial-gradient.

**Comment by imathis** [comment]
Good catch, I'll have a look at that. Thanks.

**Comment by chriseppstein** [comment]
Actually, it's the comment that should be changed. The mixin works fine if you use an image with an alpha layer.

**Comment by triplepoint** [comment]
Ah, right, it's a question of which is the transparency: the image or the gradient.  I was doing it the other way.

**Comment by chriseppstein** [comment]
Ya. the docs need to be correctly and we need to get a proper example that exemplifies this. Leaving the bug open until that is addressed.

**Comment by chriseppstein** [comment]
[Docs] This documentation was incorrect.
Closed by 00b437ae8da5195c15975dc1c43ace9a31e4429a.
