### ISSUE TITLE
Compass do not specify the proper directory to place the  .listen_test file

### ISSUE THREAD

**Issue by stavnstrup** [Compass/compass#1421]
When running the following command

```
 compass watch --trace
```

I get the output seen below. Compass do not depends on listen - Sass does, but without Compass, Sass with a --watch option works just fine.

I am using Compass 0.13.alpha10, Sass 3.3.0rc1 and ruby 1.9.3p448. 

> > > Compass is watching for changes. Press Ctrl-C to Stop.
> > > Errno::EACCES on line ["1140"] of /usr/lib/ruby/1.9.1/fileutils.rb: Permission denied - /var/lib/gems/1.9.1/gems/compass-0.13.alpha.10/frameworks/compass/stylesheets/.listen_test
> > >   /usr/lib/ruby/1.9.1/fileutils.rb:1140:in `open'
> > >   /usr/lib/ruby/1.9.1/fileutils.rb:1140:in`rescue in block in touch'
> > >   /usr/lib/ruby/1.9.1/fileutils.rb:1136:in `block in touch'
> > >   /usr/lib/ruby/1.9.1/fileutils.rb:1134:in`each'
> > >   /usr/lib/ruby/1.9.1/fileutils.rb:1134:in `touch'
> > >   /var/lib/gems/1.9.1/gems/listen-1.1.6/lib/listen/adapter.rb:221:in`works?'
> > >   /var/lib/gems/1.9.1/gems/listen-1.1.6/lib/listen/adapter.rb:182:in `block in usable_and_works?'
> > >   /var/lib/gems/1.9.1/gems/listen-1.1.6/lib/listen/adapter.rb:182:in`each'
> > >   /var/lib/gems/1.9.1/gems/listen-1.1.6/lib/listen/adapter.rb:182:in `all?'
> > >   /var/lib/gems/1.9.1/gems/listen-1.1.6/lib/listen/adapter.rb:182:in`usable_and_works?'
> > >   /var/lib/gems/1.9.1/gems/listen-1.1.6/lib/listen/adapter.rb:49:in `block in select_and_initialize'
> > >   /var/lib/gems/1.9.1/gems/listen-1.1.6/lib/listen/adapter.rb:47:in`each'
> > >   /var/lib/gems/1.9.1/gems/listen-1.1.6/lib/listen/adapter.rb:47:in `select_and_initialize'
> > >   /var/lib/gems/1.9.1/gems/listen-1.1.6/lib/listen/listener.rb:272:in`initialize_adapter'
> > >   /var/lib/gems/1.9.1/gems/listen-1.1.6/lib/listen/listener.rb:264:in `setup'
> > >   /var/lib/gems/1.9.1/gems/listen-1.1.6/lib/listen/listener.rb:64:in`start!'
> > >   /var/lib/gems/1.9.1/gems/compass-0.13.alpha.10/lib/compass/watcher/project_watcher.rb:31:in `watch!'
> > >   /var/lib/gems/1.9.1/gems/compass-0.13.alpha.10/lib/compass/commands/watch_project.rb:48:in`perform'
> > >   /var/lib/gems/1.9.1/gems/compass-0.13.alpha.10/lib/compass/commands/base.rb:18:in `execute'
> > >   /var/lib/gems/1.9.1/gems/compass-0.13.alpha.10/lib/compass/commands/project_base.rb:19:in`execute'
> > >   /var/lib/gems/1.9.1/gems/compass-0.13.alpha.10/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
> > >   /var/lib/gems/1.9.1/gems/compass-0.13.alpha.10/lib/compass/exec/sub_command_ui.rb:15:in`run!'
> > >   /var/lib/gems/1.9.1/gems/compass-0.13.alpha.10/bin/compass:30:in `block in <top (required)>'
> > >   /var/lib/gems/1.9.1/gems/compass-0.13.alpha.10/bin/compass:44:in`call'
> > >   /var/lib/gems/1.9.1/gems/compass-0.13.alpha.10/bin/compass:44:in `<top (required)>'
> > >   /usr/local/bin/compass:23:in`load'
> > >   /usr/local/bin/compass:23:in `<main>'

**Comment by tsi** [comment]
I get the exact same issue

**Comment by ghost** [comment]
I have the same issue on Linux Mint 15 and 16. The error does not occur if I use ruby1.8.

**Comment by dcorb** [comment]
Same here

**Comment by ghost** [comment]
I don't know where the error comes from but after I cd to "/var/lib/gems" and ran chmod 775 -R \* the issue seems to be solved now on my machine. Now I can use COMPASS and Guard with the Ruby version 1.9.1 without any errors. I don't know if I broke something else though but it's working.

**Comment by thomasbachem** [comment]
Same issue here with Compass 1.0.0.alpha.17:

```
>>> Compass is watching for changes. Press Ctrl-C to Stop.
Errno::EACCES on line ["1143"] of /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb: Permission denied - /Library/Ruby/Gems/2.0.0/gems/compass-core-1.0.0.alpha.16/stylesheets/.listen_test
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1143:in `open'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1143:in `rescue in block in touch'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1139:in `block in touch'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1137:in `each'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1137:in `touch'
  /Library/Ruby/Gems/2.0.0/gems/listen-1.1.6/lib/listen/adapter.rb:221:in `works?'
  /Library/Ruby/Gems/2.0.0/gems/listen-1.1.6/lib/listen/adapter.rb:182:in `block in usable_and_works?'
  /Library/Ruby/Gems/2.0.0/gems/listen-1.1.6/lib/listen/adapter.rb:182:in `each'
  /Library/Ruby/Gems/2.0.0/gems/listen-1.1.6/lib/listen/adapter.rb:182:in `all?'
  /Library/Ruby/Gems/2.0.0/gems/listen-1.1.6/lib/listen/adapter.rb:182:in `usable_and_works?'
  /Library/Ruby/Gems/2.0.0/gems/listen-1.1.6/lib/listen/adapter.rb:49:in `block in select_and_initialize'
  /Library/Ruby/Gems/2.0.0/gems/listen-1.1.6/lib/listen/adapter.rb:47:in `each'
  /Library/Ruby/Gems/2.0.0/gems/listen-1.1.6/lib/listen/adapter.rb:47:in `select_and_initialize'
  /Library/Ruby/Gems/2.0.0/gems/listen-1.1.6/lib/listen/listener.rb:272:in `initialize_adapter'
  /Library/Ruby/Gems/2.0.0/gems/listen-1.1.6/lib/listen/listener.rb:264:in `setup'
  /Library/Ruby/Gems/2.0.0/gems/listen-1.1.6/lib/listen/listener.rb:64:in `start!'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/watcher/project_watcher.rb:31:in `watch!'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/commands/watch_project.rb:48:in `perform'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/commands/base.rb:18:in `execute'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/commands/project_base.rb:19:in `execute'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.0.alpha.17/bin/compass:30:in `block in <top (required)>'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.0.alpha.17/bin/compass:44:in `call'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.0.alpha.17/bin/compass:44:in `<top (required)>'
  /usr/bin/compass:23:in `load'
  /usr/bin/compass:23:in `<main>'
```

**Comment by scottdavis** [comment]
I can't find reference to `.listen_test` in the compass code base or the sass codebase anyone feel like doing some research on listen and how we can fix this?

**Comment by MoOx** [comment]
Just go the same exact same issue as @thomasbachem (after a system gem update, not sure if it's related), there is no .listen_test file.

**Comment by scottdavis** [comment]
dup: #1497
