### ISSUE TITLE
Mozilla gradients should not put the $start value in quotes

### ISSUE THREAD

**Issue by triplepoint** [Compass/compass#143]
The sass mixin:
@include linear-gradient( color-stops(rgba(64,64,64,0.5), #000), "top" );

generates the mozilla gradient:
background-image: -moz-linear-gradient("top", rgba(64, 64, 64, 0.5) 0%, #000000 100%);

Where it should generate:
background-image: -moz-linear-gradient(top, rgba(64, 64, 64, 0.5) 0%, #000000 100%);

Mozilla gradients appear to fail when 'top' is in quotes.

**Comment by triplepoint** [comment]
The mixin:
@include linear-gradient( color-stops(rgba(64,64,64,0.5), #000), top );

functions appropriately.  The examples all show the 'top' in quotes.  Is this a SASS vs SCSS distinction, or are the examples incorrect?

**Comment by chriseppstein** [comment]
Well, really, you shouldn't put the value you passed in quotes, but I'll throw in an unquote() on our end.

**Comment by chriseppstein** [comment]
Ah. well it would probably help if the docs didn't tell you to do it wrong.

**Comment by chriseppstein** [comment]
[Compass Core] Don't suggest putting some values in quotes unecessarily, and unquote them if the user has.
Closed by ed35a3eb2443fc9bbbe59f30b8a57f23f6ed958f.  Closed by ed35a3eb2443fc9bbbe59f30b8a57f23f6ed958f.
