### ISSUE TITLE
RGBA with variable not compiling

### ISSUE THREAD

**Issue by alexcican** [Compass/compass#1434]
Using SASS I can do:

```
$brand-colour: #333;
background: rgba($brand-colour, .1);
```

But this doesn’t get compiled with Compass. The background property is discarded. Any ideas?

**Comment by lolmaus** [comment]
Works for me (Compass 0.12.2 (Alnilam)).

**Comment by alexcican** [comment]
@lolmaus thanks, it works now :)

**Comment by lolmaus** [comment]
Keep calm and do `compass clean`. :D
