### ISSUE TITLE
No compile time error when attempting to extend a class which doesn't exist

### ISSUE THREAD

**Issue by ghost** [Compass/compass#1437]
Situation:

Using a style named ".class" which contains some CSS rules, attempting to create a new class named ".extension" which "@extends .class;", but accidentally type "@extends .clas;"

Expected behaviour: Compass throws a compile time error stating that you may not extend a class which does not exist

Actual behaviour: No error reported, compiles and pulls nothing in to ".extension"

**Comment by lolmaus** [comment]
When i extend a non-existing selector, i get this:

> WARNING on line 2 of SASS code: ".foo" failed to @extend ".bar".
>  The selector ".bar" was not found.
>  This will be an error in future releases of Sass.
>  Use "@extend .bar !optional" if the extend should be able to fail.

**Comment by scottdavis** [comment]
Compass is a framework built on top of sass i would suggest reporting this error to the sass issue tracker: http://github.com/nex3/sass/issues
