### ISSUE TITLE
Installing v0.10.1 produces only load errors

### ISSUE THREAD

**Issue by hphoeksma** [Compass/compass#144]
As the title said: I tried to install compass 0.10.1 using sudo gem install compass.
It all seemed to go well but when wanting to see the version, load errors appear.
Anyone a suggestion on how to fix this? I am working on Mac 10.6.3

Thanks.

**Comment by chriseppstein** [comment]
I cannot reproduce this. Can you please try re-installing? If you can still reproduce the issue, please provide the steps you are doing.

**Comment by hphoeksma** [comment]
Hi Chris, don't know what went wrong. Just managed to get it all back after reinstalling ruby...
Thanks for your concern though :-)
