### ISSUE TITLE
Compass does not respond at all !

### ISSUE THREAD

**Issue by merianos** [Compass/compass#1443]
Hello,

Ignore the following message.

THE PROBLEM SOLVED. I had made a file called compass.cab for auto starting the compass with just a click, and then that file conflicted with compass gem.

I own a Windows 7 system, and without any modification, I am faced with an issue on campass.

I have the compass installed for a couple of months now, and it work fine, but today, sadenly it stoped from responding at all.

What I am doing:

I am moving on the directory that contains the config.rb
Then, I initiating my cmd to point in this directory
Then, I run the command : compass watch
Finally there is no response.

I also have try compass help, compass version and compass compile, and again, I cannot get any response from compass.

Also I have try to uninstall the compass and re-install it, but still no luck.

Any idea on what can be wrong with that ?

**Comment by Anahkiasen** [comment]
I don't get it (like really, I didn't get most of the message), is your problem solved or not ?

**Comment by merianos** [comment]
Sorry for my English :)

The problem solved ... !!! It's ok.

Thanks for your interest .... !
