### ISSUE TITLE
#value deprecation & NoMethod

### ISSUE THREAD

**Issue by stephenway** [Compass/compass#145]
Running compass 0.10.1 & HAML 3.0.4
I am getting a dep warning for this http://bit.ly/aJoWeZ  which looks like this

<pre><code>DEPRECATION WARNING:
The Sass::Script::Color #value attribute is deprecated and will be
removed in version 3.2. Use the #rgb attribute instead.

NoMethodError on line 41 of /Users/user/.gem/ruby/1.8/gems/compass-0.10.1/lib/compass/sass_extensions/functions/gradient_support.rb: private method `split' called for [225, 225, 225]:Array
Run with --trace to see the full backtrace
$ 
</code></pre>

and the trace

<code><pre>NoMethodError on line 41 of /Users/user/.gem/ruby/1.8/gems/compass-0.10.1/lib/compass/sass_extensions/functions/gradient_support.rb: private method `split' called for [225, 225, 225]:Array
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/script/funcall.rb:69:in`send'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/script/funcall.rb:69:in `_perform'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/script/node.rb:61:in`perform'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/tree/variable_node.rb:30:in `_perform'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/tree/node.rb:209:in`perform'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/tree/mixin_node.rb:94:in `perform!'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/tree/mixin_node.rb:94:in`map'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/tree/mixin_node.rb:94:in `perform!'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/tree/node.rb:301:in`_perform'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/tree/node.rb:209:in `perform'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/tree/node.rb:322:in`perform_children'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/tree/node.rb:322:in `map'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/tree/node.rb:322:in`perform_children'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/tree/node.rb:313:in `perform!'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/tree/rule_node.rb:188:in`perform!'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/tree/node.rb:301:in `_perform'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/tree/node.rb:209:in`perform'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/tree/node.rb:322:in `perform_children'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/tree/node.rb:322:in`map'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/tree/node.rb:322:in `perform_children'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/tree/node.rb:313:in`perform!'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/tree/root_node.rb:59:in `perform!'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/tree/node.rb:301:in`_perform'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/tree/node.rb:209:in `perform'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/tree/root_node.rb:37:in`perform'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/tree/root_node.rb:29:in `render'
  /Users/user/.gem/ruby/1.8/gems/haml-3.0.4/lib/sass/engine.rb:159:in`render'
  /Users/user/.gem/ruby/1.8/gems/compass-0.10.1/lib/compass/compiler.rb:103:in `compile'
  /Users/user/.gem/ruby/1.8/gems/compass-0.10.1/lib/compass/logger.rb:43:in`red'
  /Users/user/.gem/ruby/1.8/gems/compass-0.10.1/lib/compass/compiler.rb:102:in `compile'
  /Users/user/.gem/ruby/1.8/gems/compass-0.10.1/lib/compass/compiler.rb:93:in`compile_if_required'
  /Users/user/.gem/ruby/1.8/gems/compass-0.10.1/lib/compass/compiler.rb:84:in `run'
  /Users/user/.gem/ruby/1.8/gems/compass-0.10.1/lib/compass/compiler.rb:82:in`each'
  /Users/user/.gem/ruby/1.8/gems/compass-0.10.1/lib/compass/compiler.rb:82:in `run'
  /Users/user/.gem/ruby/1.8/gems/compass-0.10.1/lib/compass/commands/update_project.rb:33:in`perform'
  /Users/user/.gem/ruby/1.8/gems/compass-0.10.1/lib/compass/commands/base.rb:18:in `execute'
  /Users/user/.gem/ruby/1.8/gems/compass-0.10.1/lib/compass/commands/project_base.rb:19:in`execute'
  /Users/user/.gem/ruby/1.8/gems/compass-0.10.1/lib/compass/exec/sub_command_ui.rb:38:in `perform!'
  /Users/user/.gem/ruby/1.8/gems/compass-0.10.1/lib/compass/exec/sub_command_ui.rb:15:in`run!'
  /Users/user/.gem/ruby/1.8/gems/compass-0.10.1/bin/compass:26
  /usr/bin/compass:19:in `load'
  /usr/bin/compass:19</code></pre>

Once I changed line 41 to rgb the dep warning went away, but the NoMethod is still there.

I am compiling a 960 framework project when I get this error. Thanks

**Comment by nex3** [comment]
What's the Sass that's causing this error? It sounds like you're passing in a color where it expects a string.

Chris, might you be interested in using `#assert_type` here?

**Comment by stephenway** [comment]
These are the four instances of +linear gradient

<pre><code>+linear-gradient(color-stops #FFFFFF, #E1E1E1)
+linear-gradient(color-stops #005F7D, #004759)
+linear-gradient(color-stops #444444, #888888)
+linear-gradient(color-stops #005F7D, #004759)</code></pre>

**Comment by stephenway** [comment]
And the long version

<pre><code>
//  960 Grid System ~ Core CSS. http://960.gs/
//  Licensed under GPL and MIT.
#XMENU1 a.active
  color: #000000 !important
  
@import "compass/utilities/general/reset"
@import "compass/css3"
@import "960/grid.sass"
@import "960/text.sass"

+global-reset


// GRID >> GLOBAL ----------------------------------------------
.dnngridcontainer_12 .dnngrid_1, .dnngrid_2, .dnngrid_3, .dnngrid_4, .dnngrid_5, .dnngrid_6, .dnngrid_7, .dnngrid_8, .dnngrid_9,  .dnngrid_10, .dnngrid_11, .dnngrid_12
  :display inline
  :float left
  :margin-left 10px
  :margin-right 10px


// CONTAINER
.dnngridcontainer_12
  :margin-left auto
  :margin-right auto
  :width 1020px


// GRID >> CHILDREN (ALPHA ~ FIRST, OMEGA ~ LAST)
.alpha
  :margin-left 0 
  
.omega
  :margin-right 0


// GRID >> 12 COLUMNS
.dnngridcontainer_12
  .dnngrid_1
    width: 65px
  .dnngrid_2
    width: 150px
  .dnngrid_3
    width: 235px
  .dnngrid_4
    width: 320px
  .dnngrid_5
    width: 405px
  .dnngrid_6
    width: 490px
  .dnngrid_7
    width: 575px
  .dnngrid_8
    width: 660px
  .dnngrid_9
    width: 745px
  .dnngrid_10
    width: 830px
  .dnngrid_11
    width: 915px
  .dnngrid_12
    width: 1000px
  // PREFIX AND SUFFIX EXTRA SPACE >> 12 COLUMNS
  .prefix_1
    padding: 0 85px
  .prefix_2
    padding: 0 170px
  .prefix_3
    padding: 0 255px
  .prefix_4
    padding: 0 340px
  .prefix_5
    padding: 0 425px
  .prefix_6
    padding: 0 510px
  .prefix_7
    padding: 0 595px
  .prefix_8
    padding: 0 680px
  .prefix_9
    padding: 0 765px
  .prefix_10
    padding: 0 850px
  .prefix_11
    padding: 0 935px
  .prefix_12
    padding: 0 1020px


// GRID >> CORE >> 1024PX

// CSS and HTML Generated by DNNGrid960.com Grid System Generator
// Tool Developed by http://www.SchwingSoft.com and http://www.HowardsHome.com
// Based on the Grid System by Natan Smith - http://960.gs/
// CSS and HTML can be freely used but keep this comment block intact 


// GRID >> GLOBAL
.dnngridcontainer_16 .dnngrid_1, .dnngrid_2, .dnngrid_3, .dnngrid_4, .dnngrid_5, .dnngrid_6, .dnngrid_7,  .dnngrid_8, .dnngrid_9, .dnngrid_10, .dnngrid_11, .dnngrid_12, .dnngrid_13, .dnngrid_14, .dnngrid_15, .dnngrid_16
  :display inline
  :float left
  :margin-left 10px
  :margin-right 10px


// CONTAINER
.dnngridcontainer_16
  :margin-left auto
  :margin-right auto
  :width 1024px


// GRID >> CHILDREN (ALPHA ~ FIRST, OMEGA ~ LAST)
.alpha
  :margin-left 0
.omega
  :margin-right 0


// GRID >> 16 COLUMNS
.dnngridcontainer_16
  .dnngrid_1
    width: 44px
  .dnngrid_2
    width: 108px
  .dnngrid_3
    width: 172px
  .dnngrid_4
    width: 236px
  .dnngrid_5
    width: 300px
  .dnngrid_6
    width: 364px
  .dnngrid_7
    width: 428px
  .dnngrid_8
    width: 492px
  .dnngrid_9
    width: 556px
  .dnngrid_10
    width: 620px
  .dnngrid_11
    width: 684px
  .dnngrid_12
    width: 748px
  .dnngrid_13
    width: 812px
  .dnngrid_14
    width: 876px
  .dnngrid_15
    width: 940px
  .dnngrid_16
    width: 1004px
// PREFIX AND SUFFIX EXTRA SPACE >> 16 COLUMNS
  .prefix_1
    padding: 0 64px
  .prefix_2
    padding: 0 128px
  .prefix_3
    padding: 0 192px
  .prefix_4
    padding: 0 256px
  .prefix_5
    padding: 0 320px
  .prefix_6
    padding: 0 384px
  .prefix_7
    padding: 0 448px
  .prefix_8
    padding: 0 512px
  .prefix_9
    padding: 0 576px
  .prefix_10
    padding: 0 640px
  .prefix_11
    padding: 0 704px
  .prefix_12
    padding: 0 768px
  .prefix_13
    padding: 0 832px
  .prefix_14
    padding: 0 896px
  .prefix_15
    padding: 0 960px
  .prefix_16
    padding: 0 1024px
    
.dnngrid_12
  :background url("images/header_bg.png") no-repeat top center scroll

+text

// Variables ----------------------------------------------

$fontset: "Helvetica Neue", "Helvetica", "Arial", "sans-serif"

$blue: #0981a0
$dblue: #004759
$orange: #d57803
$tangerine: $orange + #123
$beige: #f3f0e0

// Clear Floated Elements ----------------------------------------------

.clear
  :clear both
  :display block
  :overflow hidden
  :visibility hidden
  :width 0
  :height 0

// http://perishablepress.com/press/2008/02/05/lessons-learned-concerning-the-clearfix-css-hack

.clearfix:after
  :clear both
  :content ' '
  :display block
  :font-size 0
  :line-height 0
  :visibility hidden
  :width 0
  :height 0

.clearfix
  :display inline-block

* html .clearfix
  :height 1%

.clearfix
  :display block
  
.white
  :color #fff !important

// Elements ----------------------------------------------

//#XMENU1 a.level1, #XMENU1 span.level1
//  color: #fff !important
//  text-shadow: 0 -1px #000000

body
  -webkit-text-stroke: 1px transparent
  -moz-opacity: 0.99
  :font-family $fontset
  :background url("images/body_bg.png") repeat-x top

body, html, .gwhite
  :background-color #F3F0E0

#maincontent, #GetQuotes
  :background-color #fff

#maincontent
  :padding-bottom 40px

img 
  :border none
  :padding 0
  :margin 0

strong
  :font-weight bold

*:hover
  +transition-duration(150ms)
  
#Attention a, #GetQuotes a, #maincontent a, #footer a
  :color $blue
  :text-decoration none !important
  &:visited
    :color $blue !important

// Unique ----------------------------------------------

#dnn_ctr1500_ctl00_lblTitle
  :padding-left 30px

#XMENU1
  :z-index 9999999 !important

#XMENU1 li.level1.item6, #XMENU1 li.level1.item7
  :margin-top -35px !important
  :top 0 !important
  :left 650px !important

#XMENU2
  :margin 0 0 0 10px !important
  :width 300px !important
  div.box-1
    :width 300px !important
  ul
    :width 300px !important

#LeftMenu
  +border-radius(4px)
  +box-shadow(rgba(0, 0, 0, 0.5), 0, 1px, 4px)
  +linear-gradient(color-stops #FFFFFF, #E1E1E1)
  filter: progid:DXImageTransform.Microsoft.gradient( startColorstr= #FFFFFF, endColorstr= #E1E1E1 )
  -ms-filter: "progid:DXImageTransform.Microsoft.gradient( startColorstr= #FFFFFF, endColorstr= #E1E1E1 )"
  :padding 20px
  :margin-left 10px
  :width 240px
  :border 1px solid #fff
  :background-color #e2e2e2
  ul
    :display none
  li
    :margin-left 0px !important
    :list-style-type none !important
  a
    :padding 3px 3px 3px 40px
    :display block
    :text-shadow 0px 1px white
    :color #777
    &:hover
      +box-shadow(rgba(0, 0, 0, 0.5), 0, 1px, 1px)
      +border-radius(2px)
      +text-shadow(0px, 1px, #fff !important)
      :background-color #C3F1FF
      :border 1px solid #fff
      :color #000000 !important
      :cursor pointer
      :text-decoration none !important

#LeftMenuCurrentItem, #LeftMenuCurrentLink
  +border-radius(2px)
  +box-shadow(rgba(0, 0, 0, 0.2), 0, 1px, 1px)
  :text-decoration none !important
  :color #fff !important
  :background-color #fff !important
  :border 1px solid #C6C8C8 !important
  &:hover
    :color #000000 !important

#Header 
  :height 113px
  :background-color $blue
  :background-image url(images/header_bg.png) no-repeat top center scroll
  
#Menu 
  :float right
  :margin-top 68px

#Attention
  :background-color $beige
  :padding 20px 0 0 0
  :border-top #FBFAE7 solid 1px
  :border-bottom #AEAD9E solid 1px
  ul
    :font-size 14px !important

div
  slide
    :width 121px
    :height 155px
    :overflow hidden
    :background url(images/slide_bg.png) no-repeat
    :margin-left 15px
    div.inner
      :padding 5px
      :text-align center
    a
      :color #89a426
      :font-size 13px
      :font-weight bold
      :text-decoration none !important
      &:visited
        :color #89a426 !important
  .container
    :background-color $beige
    :padding 10px
    :margin-bottom 10px
    :border-bottom 1px solid #AEAD9E
    h1
      :color $blue
      :font-size 20px
      :font-weight normal
      :margin-bottom 10px
  .cntorange
    :background-color #fff
    :padding 0
    :margin-bottom 10px
    h2
      :color #d67a06
      :font-size 16px
      :font-weight normal
      :margin-bottom 10px
  .quoteblock
    :border 1px solid #e0dccb
    :padding 0 19px 0 19px
    :background #fff
    h3
      :color #84a126
      :font-weight bold
      :font-size 20px
      :margin-bottom 10px
  .balloon
    :background-color $beige
    :margin-bottom 2px
  .balloonheader
    :height 11px
    :overflow hidden
    :background url(images/balloon_trans_bg.png) no-repeat
  .ballooncontent
    :display block
    :padding 0 10px
  .balloonfooter
    :height 29px
    :overflow hidden
    :background url(images/balloon_trans_bg.png) no-repeat 0 -59px

a
  &:hover
    :color $blue !important
    :text-decoration none
  .quote
    :background-color $orange
    :display block
    :width 196px
    :height 33px
    :background url(images/big_button_bg.png) no-repeat
    :margin 7px 0 0 0
    :background-position 0 0
    :border-bottom #fff 7px solid
  .pointer
    :display block
    :font-weight bold
    :text-decoration none
    :color #0082a4
    :background url(images/sprite.png) no-repeat 0 -126px
    :padding-left 25px
    :margin-top 5px

  
.quotemenu
  :height 228px
  :background url(images/235_bg.png) no-repeat
  :width 235px
  :overflow hidden

.getquotes
  :height 215px
  :background-color $blue
  :background url(images/getquotes_bg.png) no-repeat
  :margin-bottom 10px
  :margin-top 20px
  :width 1020px
  :display block

.getquotestitle
  :height 45px
  :color #fff
  :font-size 16px
  :font-weight bold
  :padding-left 15px
  :margin-top 10px
  

// Teaser ----------------------------------------------

#dnn_HeaderVortexes
  :height 190px
  :padding-left 7px
  :margin-bottom -20px
  img
    :border none
    :margin-top 17px
  .Item
    :background transparent url(images/235_bg.png) no-repeat top center scroll
    :width 235px
    :height 249px
    :float left
    :clear right
    :position relative
    :text-align center
    :margin-right 30px
    ul, li
      :list-style none
    ul
      :margin 10px 5px 0 3px
      :font-size 16px
      :text-align left
      :line-height 50px
      :text-indent 50px
      :padding 0 0 0 10px
      li
        :width 210px
        :margin 0 !important
        :border-bottom #999 dotted 1px
        :padding 0
        :vertical-align center
        &.item1
          :background url("images/icon1.png") no-repeat left center scroll
        &.item2
          :background url("images/icon2.png") no-repeat left center scroll
        &.item3
          :background url("images/icon3.png") no-repeat left center scroll
        &.last
          :border-bottom none
          :background url("images/icon4.png") no-repeat left center scroll
        a
          :color #000000
          :text-decoration none
          &:hover
            :color $tangerine
            :cursor pointer

  .Item-alt
    :width 210px
    :height 224px
    :float left
    :clear right
    :position relative
    :text-align center
    :margin-right 30px
    :text-decoration none
    :background-color $orange
    :border-color $tangerine
    :border-style solid
    :border-width 1px
    :display block
    :cursor pointer
    +border-radius(10px)
    &:hover
      :background-color $orange + #102
    &.img2
      :background-color $tangerine
      :border-color $tangerine + #123
      &:hover
        :background-color $tangerine + #123
    a
      :text-decoration none

  .Link
    :text-align center
    :font-family $fontset
    :font-size 18px
    :font-weight bold
    :color $beige
    :width 198px
    :height 48px
    :background-repeat no-repeat
    :top 190px
    :left 6px
    :position absolute
    :z-index 1
    a
      +text-shadow(#666, 0, -1px, 0)
      :color #fff !important

#dnn_TopPane
  .Item
    +border-radius(5px)
    :float left
    :clear right
    :display block
    :text-align center
    :width 138px
    :height 115px
    :background #fff
    :margin 10px
    &:hover
      :color $blue - #225
    a
      :display block
      :height 77px
      &:hover
        :text-decoration none !important
      img
        +border-top-radius(5px)
        :position relative
        :display inline
        :top -9px

    img
      :margin 10px 0
    .Link
      +border-bottom-radius(5px)
      +text-shadow(#000000, 0, -1px, 0)
      +linear-gradient(color-stops #005F7D, #004759)
      filter: progid:DXImageTransform.Microsoft.gradient( startColorstr= #005F7D, endColorstr= #004759 )
      -ms-filter: "progid:DXImageTransform.Microsoft.gradient( startColorstr= #005F7D, endColorstr= #004759 )"
      :display block
      :color #fff
      :font-size 16px
      :text-align center
      :width 138px
      :height 30px
      :margin-top -65px
      :padding-top 3px
      :border-top #333 solid 1px
      :background #00526C
      a
        :color #fff !important
      &:hover
        :color $beige !important

#dnn_LeftPane
  :text-align left
  
#dnn_ContentPane
  +text-shadow(#fff, 0, -1px, 0)


// Misc ----------------------------------------------

input
  :border #b2ac8c 1px solid
  .btn
    :background-color $orange
    :background url(images/button_signup_bg.png) no-repeat
    :border 0
    :width 89px
    :height 33px
    :padding 0
    :margin 0
    :padding-bottom 5px
    :text-align center
    :display block
    :font-weight bold
    :color #fff
    :font-size 14px
    :text-indent -9000%
    :font-size 0.1em

.topmargin10
  :margin-top 10px
  
.cntclean
  :padding 10px

#LogoFloat
  :position absolute
  :color #fff
  :z-index 999999999
  :left 10px
  :top 12px

#PhoneFloat
  :position absolute
  :color #fff
  :z-index 999999999
  :left 675px

#dnn_ctr1507_HtmlModule_lblContent
  :font-size 18px
  :margin 10px 0 0 0
  :font-family $fontset
  
.staccato
  +border-radius(5px)
  :background-image none !important
  :background-color #fafafa !important
  :border #CBCBCB solid 1px
  :display inline
  :float left
  :margin 10px !important
  :padding 5px 8px
  :width 170px
  :font-size 10px
  a
    :font-size 13px

// Footer ----------------------------------------------

#footer
  :background-color $beige
  :border-color $dblue
  :border-top 1px solid
  :height 210px
  :clear left
  :display block
  .container
    :border-bottom none
.space
  :height 0.1em
  
.mysearch
  :background url(images/search-holder.png)
  :padding-left 10px
  :height 33px
  :position relative
  :width 290px
  :margin-top 20px
  input
    :border 0
    :background-color transparent
    :margin-top 5px
    :font-size 125%
    :width 250px
  a
    :position absolute
    :left 224px
    :top 0
    :text-indent -9999px
    :width 76px
    :height 33px
    :background url(images/search_button_bg.png) no-repeat
    :background-color $dblue
    &:hover
      :background-color $blue
    &:active
      :background-color $orange

#FooterLogo
  :margin-top 10px
  #LoginControls
    :display none
    :position absolute
    :z-index 10
    :color #000000 !important
    :height 72px
    :width 269px
    :padding 12px 0 0 0
    :background url("images/LoginBackground.png") no-repeat top center scroll
    a
      :font-size 14px
      :width 80px
      :height 15px
      :margin 0 0 0 3px
      :padding 2px 24px 5px 24px
      :display block
      :border-top 1px solid transparent
      :border-bottom 1px solid transparent
      &:hover
        +text-shadow(#888, 0, 1px, 0)
        +linear-gradient(color-stops #444444, #888888)
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr= #444444, endColorstr= #888888 )
        -ms-filter: "progid:DXImageTransform.Microsoft.gradient( startColorstr= #444444, endColorstr= #888888 )"
        :background-color #444
        :color #fff !important
        :border-top 1px solid #666
        :border-bottom 1px solid #666
  a
    :font-size 10px
    :color #555

#dnn_FooterLogo
  :margin-top 20px

// TweetDNN

.status
  :width 297px !important
  :font-size 8pt

.text
  :display block

div.ism-logo, div.ism-footer, .visibility
  :display none
div.ism-more, div.ism-about
  :display block !important

div.ism-more
  a
    +border-radius(5px)
    :background-color #fafafa
    :border #CBCBCB solid 1px
    :width 297px
    :display block
    :text-align center
    :font-weight bold
    :margin 5px 0
    :padding 12px 0
    :font-size 18px
    
div.ism-more a:hover, a:hover.ism-follow, #dnn_ctr1423_HtmlModule_lblContent p:hover
  :background-color #E7EAEA !important
  :color #115995
  :text-decoration none

#dnn_ctr1423_HtmlModule_lblContent p
  :padding 6px 8px

.status, #dnn_ctr1423_HtmlModule_lblContent p
  +border-radius(5px)
  :background-image none !important
  :background-color #fafafa !important
  :border #CBCBCB solid 1px
  :margin 10px 0 !important

.status .buffer, .status .buffer .text
  :font-family "Helvetica-Neue", Helvetica, Arial, sans-serif !important

.status .buffer
  :margin 5px !important
  .created_at
    :color #777
    :font-style normal !important
    :font-weight bold
    :font-size 10px
  span
    :padding 0 8px !important

a.ism-follow
  +border-right-radius(5px)
  :display block
  :text-align center
  :font-weight bold
  :padding 14px 10px 14px 45px !important
  :background-color #fafafa !important
  :border #CBCBCB solid 1px
  :font-size 18px

a.ism-avatar img
  :width 48px
  :height 48px
  :float left
  :position relative
  :top 6px
  :left 3px

.C03R_container, .C03M_container
  :float left !important
  :width 285px !important
  :display inline !important
  
img.ism-bird
  :display inline !important
  :position relative
  :margin -90px 0 0 -50px !important
  :z-index 999999999px !important
  :top -20px

table.ControlPanel
  :margin-bottom 0 !important

#ARLogo a
  :color #888 !important

// Fix Firefox Position of Bird
@-moz-document url-prefix()
  img.ism-bird
    :top -55px !important
  XMENU1 li
    :padding 0
    :margin-right -10px !important

#dnn_LeftMenuTop
  .wq-label, #wq-txt-email, #wq-txt-email input, #wq-txt-namefirst, #wq-txt-namefirst input, #wq-txt-namelast, #wq-txt-namelast input, #wq-txt-address1, #wq-txt-address1 input, #wq-txt-address2, #wq-txt-address2 input, #wq-txt-city, #wq-txt-city input, #wq-ddl-state, #wq-ddl-state select, #wq-txt-phone, #wq-txt-phone input
    :width 130px !important
    :position relative !important
    :float left !important
    :display inline !important
  #wq-lbl-zip
    :position absolute !important
    :top 75px !important
    :left 120px !important
    input
      :font-size 22px
      :height 35px

.removed
  :display none

//  Inner Page Styles

.inner
  #dnn_ContentPane
    .C01_ContentPane
      :height 530px
    .Item
      +border-radius(5px)
      :float left
      :clear right
      :display block
      :text-align center
      :width 138px
      :height 115px
      :background #fff
      :margin 5px 25px
      &:hover
        :color $blue - #225
      a
        :display block
        :height 77px
        &:hover
          :text-decoration none !important
      img
        +border-top-radius(5px)
        :margin 10px 0
        :position relative
        :display inline
        :top -9px
      .Link
        +border-bottom-radius(5px)
        +text-shadow(#000000, 0, -1px, 0)
        +linear-gradient(color-stops #005F7D, #004759)
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr= #005F7D, endColorstr= #004759 ) !important
        -ms-filter: "progid:DXImageTransform.Microsoft.gradient( startColorstr= #005F7D, endColorstr= #004759 )"
        :display block
        :color #fff
        :font-size 16px
        :text-align center
        :width 138px
        :height 30px
        :margin-top -65px
        :padding-top 3px
        :border-top #333 solid 1px
        :background #00526C
        a
          :color #fff !important
        &:hover
          :color $beige
  #footer
    :background $beige !important
    :clear none
    :display block
    
  .wq-form
    :margin-top 20px !important

// Container Styles

.containerClean
  :margin 0px
 
.C00_Box
  :background transparent
  :width 100%
  :text-align left
.C00_ContentPane
  :padding 0
  :clear both
  .actions
    :float left
    :margin 0
    :max-width 10px
    :min-width 0px
    :text-align center
  .icons
    :margin 0
    a
      :margin-top 10px
      &:hover
        :background-color transparent
         
.C01_container
  .title span
    +text-shadow(transparent, 0, 0, 0)
  .C01_Box
    :width 99%
    :background #0981A0 url("images/getquotes_bg.png") no-repeat top left scroll
    :margin 20px 0px 20px 10px
    :min-height 200px !important
    :padding 0 0 20px 0
    #padding-bottom: 30px !important
    :display block
    .C01_BoxTM
      :margin 0 15px
      :height 45px
    .icon
      :float left
      :padding-top 3px
    .actions
      :float left
      :margin 0
      :max-width 10px
      :min-width 0px
      :text-align center
    .title
      :float left
      :color #fff
      :font-family $fontset
      :font-size 16px
      :font-weight bold
      :padding-top 10px
      :line-height 120%
    .visibility
      :float right
      :width 8px
      :height 9px
      :margin-top 13px
      a:hover
        :background-color transparent
    .C01_BoxMM
      :margin 0 5px
      :padding 0 10px
      .C01_ContentPane
        :padding 10px 0 0 0
        :clear both
    .icons
      :margin 0
      a:hover
        :background-color transparent
      input
        :margin-top 10px
    .C01_BoxBM
      :margin 0 15px
      :height 15px

.C02_container
  :margin 0
  .C02_Box
    :width 100%
    .C02_BoxTL
      :background url("images/C01_BoxTL.png") no-repeat left top
      .C02_BoxTR
        :background url("images/C01_BoxTR.png") no-repeat right top
        .C02_BoxTM
          :background url("images/C01_BoxTM.png") repeat-x left top
          :margin 0 15px
          :height 45px
    .icon
      :float left
      :padding-top 3px
    .actions
      :float left
      :margin 0
      :max-width 10px
      :min-width 0px
      :text-align center
    .title
      :float left
      :font-family "Times New Roman", Times, serif
      :font-size 22px
      :font-weight 700
      :padding-top 13px
      :line-height 120%
      .visibility
        :float right
        :width 8px
        :height 9px
        :margin-top 13px
        a:hover
          :background-color transparent
    .C02_BoxML
      :background url("images/C01_BoxML.png") repeat-y left bottom
      .C02_BoxMR
        :background url("images/C01_BoxMR.png") repeat-y right bottom
        .C02_BoxMM
          :background #fff url("images/C02_BoxMM.gif") repeat-x bottom
          :margin 0 5px
          :padding 0 10px
          .C02_ContentPane
            :padding 10px 0 0 0
            :clear both
    .icons
      :margin 0
      a:hover
        :background-color transparent
      input
        :margin-top 10px
    .C02_BoxBL
      :display none

.C03L_container
  :margin 0
  .C03L_Box
    :width 100%
    .C03L_BoxTL
      :background url(C03L_BoxTL.png) no-repeat left top
      .C03L_BoxTR
        :background url(C03X_BoxTM.png) repeat-x left top
        :margin-left 15px
        .C03L_BoxTM
          :margin-right 15px
          :height 45px
    .icon
      :float left
      :padding-top 3px
    .actions
      :float left
      :margin 0
      :max-width 10px
      :min-width 0px
      :text-align center
    .title
      :float left
      :font-family "Times New Roman", Times, serif
      :font-size 22px
      :font-weight 700
      :padding-top 13px
      :line-height 120%
      .visibility
        :float right
        :width 8px
        :height 9px
        :margin-top 13px
        a:hover
          :background-color transparent
    .C03L_BoxML
      :background url(C03L_BoxML.png) no-repeat left top
      .C03L_BoxMR
        :background url(C03X_BoxMM.png) repeat-x left top
        :margin-left 15px
        .C03L_BoxMM
          :margin-right 15px
          :padding 0
          .C03L_ContentPane
            :padding 10px 0 0 0
            :clear both
    .icons
      :margin 0
      a:hover
        :background-color transparent
      input
        :margin-top 10px
    .C03L_BoxBL
      :display none

.C03M_container
  :margin 0 0 10px 0
  .C03M_Box
    :width 100%
    .C03M_BoxTL
      :background url(C03X_BoxTM.png) repeat-x left top
      .C03M_BoxTR
        :background url(C03X_BoxTL.png) no-repeat left 4px
        .C03M_BoxTM
          :margin 0 15px
          :height 45px
    .icon
      :float left
      :padding-top 3px
    .actions
      :float left
      :margin 0
      :max-width 10px
      :min-width 0
      :text-align center
    .title
      :float left
      :font-family "Times New Roman", Times, serif
      :font-size 22px
      :font-weight 700
      :padding-top 13px
      :line-height 120%
      .visibility
        :float right
        :width 8px
        :height 9px
        :margin-top 13px
        a:hover
          :background-color transparent
    .C03M_BoxML
      :background url(C03X_BoxMM.png) repeat-x left top
      .C03M_BoxMR
        :background url(C03X_BoxML.png) no-repeat left top
        .C03M_BoxMM
          :margin 0 15px
          :padding 0
          .C03M_ContentPane
            :padding 10px 0 0 0
            :clear both
    .icons
      :margin 0
      a:hover
        :background-color transparent
      input
        :margin-top 10px
    .C03M_BoxBL
      :display none

.C03R_container
  :margin 0 0 10px 0
  .C03R_Box
    :width 100%
    .C03R_BoxTL
      :background url(C03R_BoxTR.png) no-repeat right top
      .C03R_BoxTR
        :background url(C03X_BoxTM.png) repeat-x left top
        :margin-right 15px
        .C03R_BoxTM
          :background url(C03X_BoxTL.png) no-repeat left 4px
          :padding-left 15px
          :height 45px
    .icon
      :float left
      :padding-top 3px
    .actions
      :float left
      :margin 0
      :max-width 10px
      :min-width 0px
      :text-align center
    .title
      :float left
      :font-family "Times New Roman", Times, serif
      :font-size 22px
      :font-weight 700
      :padding-top 13px
      :line-height 120%
      .visibility
        :float right
        :width 8px
        :height 9px
        :margin-top 13px
        a:hover
          :background-color transparent
    .C03R_BoxML
      :background url(C03R_BoxMR.png) no-repeat right top
      .C03R_BoxMR
        :background url(C03X_BoxMM.png) repeat-x left top
        :margin 0 15px 0 0
        .C03R_BoxMM
          :background url(C03X_BoxML.png) no-repeat left top
          :padding 0 0 0 15px
          .C03R_ContentPane
            :padding 10px 0 0 0
            :clear both
    .icons
      :margin 0
      a:hover
        :background-color transparent
      input
        :margin-top 10px
    .C03R_BoxBL
      :display none
caption, th, td
  :vertical-align none !important
  
#dnn_ctr924_ContentPane, #dnn_ctr927_ContentPane
  +border-radius(10px)
  :border 1px solid #ccc
  :padding 10px 20px
  
.staffmember img
  :float left
  :display inline
  :width 196px
  :padding-right 10px
  
// IE6 Styles

.AttentionHolder
  _position: relative
  _height: 225px

.AttentionFloat
  _position: absolute
  _z-index: 999
  #padding-bottom: 60px
  .dnngridcontainer_12
    _width: 1040px
</code></pre>

**Comment by stephenway** [comment]
This might be the problem? +text-shadow(transparent, 0, 0, 0), scratch that.
Just changed my +box-gradient colors from rgba to #fff, didn't fix it

**Comment by stephenway** [comment]
Converting another file gave me a fresh mind and discovered my color-stops were missing parens. thanks!
