### ISSUE TITLE
Unrecognized file type: png

### ISSUE THREAD

**Issue by waynedpj** [Compass/compass#1456]
ahoy,

  though i have found a few references to this error, i have been unable to find a solution for my case.  i have a _very simple_ HTML file

```
<!doctype html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>scratch</title>
    <link href="css/scratch.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <div id="where">
      where?
    </div>
  </body>
</html>

```

and associated SCSS file

```
@import "compass";

#where {
    width: image-width(image-url('answers vs. questions/where2.png'));
    height: image-height(image-url("answers vs. questions/where2.png"));
    @include background(image-url("answers vs. questions/where2.png"));
    background-repeat: no-repeat;
    background-size: contain;    
}
```

and no matter what i try i get the following error on compile:

```
error sass/scratch.scss (Line 9: Unrecognized file type: png?1385516414'))
```

i have tried the various solutions referenced here
https://github.com/chriseppstein/compass/issues/505
http://stackoverflow.com/questions/18063768/compass-giving-the-error-unrecognized-file-type-png
https://gist.github.com/alanhogan/2878758

and so far no luck.  i have also tried disabling cache-buster but the end result is the same message minue the "?xxxxxxx" string:

```
error sass/scratch.scss (Line 9: Unrecognized file type: png'))
```

finally, though i am running Sass 3.2.9 (Media Mark) and Compass 0.12.2 (Alnilam), i received the same error when i tried the latest git version of Compass with Sass 3.3.0.rc.2

been digging around for a while with no luck, prob missing something simple.  thanks in advance for any help and for the great tools.

peace, w

**Comment by lolmaus** [comment]
Try `image-width('answers vs. questions/where2.png')`.

**Comment by waynedpj** [comment]
@lolmaus thanks for the reply and sorry for my original sleepy morning misread of your post.  as you suggested removing image-url() does the trick, though i am now wondering why?  i had thought that the image-url/image-path() functions where used to get URLs to resources according to the Compass directory setup in config.rb.  is that not the case for some reason here?
  thanks again for the reply/fix.

peace

**Comment by lolmaus** [comment]
I don't mean single quotes. I mean don't use `image-path` inside `image-width` and `image-height`.

**Comment by gisu** [comment]
Image path with spaces?

**Comment by waynedpj** [comment]
@gisu thanks but the image path with spaces seems not to be the problem as it is working now after doing what @lolmaus said: not using `image-url()` inside the `image-width()` and `image-height()`.  i see now that the `image-width()` and `image-height()` helper functions require a path to the image, while the `image-url()` function returns a `url()` wrapped path for CSS.  also, using `image-path()` or `image-url('path/image.png', true)` would work as well since they both return actual paths.

thanks again for the help and sorry for the miss.

peace, w
