### ISSUE TITLE
Installation of Link Icons

### ISSUE THREAD

**Issue by KevinMonk** [Compass/compass#146]
The documentation for installing the link icons here:
http://compass-style.org/docs/reference/blueprint/link_icons/#mixin-link-icon-sass

states that you can install the link_icons by using

compass install blueprint/buttons

this should be:

compass install blueprint/link_icons

PS. Great gem! My designers love it and so do I. It's particulalry useful when you have someone like the BBC give you their visual identity document:
http://www.bbc.co.uk/blogs/bbcinternet/2010/02/a_new_global_visual_language_f.html

labels:
- documentation

**Comment by KevinMonk** [comment]
How do I add a label to an issue?

**Comment by chriseppstein** [comment]
[Docs] Fix a bug in the docs for link_icons. Closed by 981bbd2b18d666f29844e2965c15a1c30df2169a.
