### ISSUE TITLE
Implement import-once plugin into compass core

### ISSUE THREAD

**Issue by xzyfer** [Compass/compass#1463]
This is a follow up to the suggestion made in https://github.com/nex3/sass/issues/1019.

Essentially plugins can be a tricky proposition for end users where as compass is second nature among many sass developers. Putting import-once into compass core would make it for feasible for opensource projects to rely on without risking endless "import-once not working" issue :(

**Comment by chriseppstein** [comment]
done: https://github.com/chriseppstein/compass/blob/master/import-once/README.md

**Comment by xzyfer** [comment]
Awesome! Thanks
