### ISSUE TITLE
Compass stats and compass compile, different compilation

### ISSUE THREAD

**Issue by wvddrss** [Compass/compass#1468]
When I run compass stats i got an error, 

`Sass::SyntaxError on line 94 of (sass): Invalid CSS after "      }": expected "}", was ""
  /Library/Ruby/Gems/1.8/gems/sass-3.2.12/lib/sass/../sass/scss/parser.rb:1148:in `expected'`

When i run compass compile, i don't get an error:

after searching for the problem, there was a } - missing. So the compile / watch function is checking less hard then when I run stats function. How is this possible, my setup is:

compass (0.12.2)
css_parser (1.2.6)
csscss (1.0.0)
sass (3.2.12)

**Comment by chriseppstein** [comment]
It's not checking less hard, it's just not a fatal error during compilation. The error should have been reported to your css file output and to the screen.
