### ISSUE TITLE
[Sourcemaps ~ 1.0.0.alpha.16] Sprite generation fails to correctly generate the map

### ISSUE THREAD

**Issue by RaphaelDDL** [Compass/compass#1479]
Hello there,

As [Chris asked](https://github.com/chriseppstein/compass/issues/1293#issuecomment-30285298), here is a bug that happens when using `compass/utilities/sprites` with `sourcemap = true`. Considering the following as `_sprites.scss`, being imported with `@import "sprites";` on `app.scss`:

```
@import "compass/utilities/sprites";

$dota-spacing: 15px;
@import "dota/*.png";
@include all-test-sprites;

.dota-sprite {
    width:128px;
    height:72px;
    display:inline-block;
    vertical-align:middle;
    *display:inline;
    zoom:1;
}
```

When generating map, this happens:

```
>>> Compass is watching for changes. Press Ctrl-C to Stop.
     info assets/css/sass/app.scss was modified
unchanged assets/img/dota-s7db68bee82.png
overwrite assets/css/app.css
WARNING: Couldn't determine public URL for "dota/*.png" while generating sourcemap.
  Without a public URL, there's nothing for the source map to link to.
  Custom importers should define the #public_url method.

   create assets/css/app.map
overwrite assets/css/default.css
   create assets/css/default.map
```

The map is generated but when debugging on DevTools, all classes point to their respective .scss file (in this case, app.scss or other import), except the ones from sprite, which point to the normal app.css

Here is the map:

```
{
"version": 3,
"mappings": ";;;;;;;;;;;;;;;;;;;;;;;;AAmFQ,SAAsB;EAlE5B,mBAAmB,EAAE,GACH;;;;AAiEZ,yBAAsB;EAlE5B,mBAAmB,EAAE,OACH;;;;AAiEZ,YAAsB;EAlE5B,mBAAmB,EAAE,QACH;;;;ACkBpB,gEAAa;EACZ,KAAK,EAAC,KAAK;EACX,MAAM,EAAC,IAAI;EACX,OAAO,EAAC,YAAY;EACpB,cAAc,EAAC,MAAM;EACrB,QAAQ,EAAC,MAAM;EACf,IAAI,EAAC,CAAC;;;;AC3BP;eACgB;EACf,OAAO,EAAE,GAAG;EACZ,OAAO,EAAE,KAAK;;;;AAGf,eAAgB;EACf,KAAK,EAAE,IAAI;;;;AAMZ,cAAe;EACd,QAAQ,EAAC,KAAK;EACd,GAAG,EAAC,CAAC;EACL,MAAM,EAAC,CAAC;EACR,IAAI,EAAC,CAAC;EACN,KAAK,EAAC,CAAC;EACP,UAAU,EC5BE,OAAO;;;AD8BnB,uBAAS;EACR,SAAS,EAAC,IAAI;EACd,KAAK,EC/BC,KAAI;ECkBT,mBAAuB,EAAC,4BAAmB;EAA3C,kBAAuB,EAAC,4BAAmB;EAA3C,gBAAuB,EAAC,4BAAmB;EAA3C,eAAuB,EAAC,4BAAmB;EAA3C,cAAuB,EAAC,4BAAmB;EAE5C,WAAY,EAAC,4BAAmB;EFahC,KAAK,EAAC,KAAK;EACX,MAAM,EAAC,IAAI;EACX,QAAQ,EAAC,QAAQ;EACjB,GAAG,EAAC,GAAG;EACP,IAAI,EAAC,GAAG;EACR,MAAM,EAAC,gBAAgB;EACvB,WAAW,EAAC,IAAI;EAChB,UAAU,EAAC,MAAM;EACjB,cAAc,EAAC,MAAM;;;;AAOvB,UAAU;EACT,UAAU,EAAC,IAAI",
"sources": ["../../../../../../../Dev/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-core-1.0.0.alpha.16/stylesheets/compass/utilities/sprites/_base.scss","sass/_sprites.scss","sass/app.scss","sass/_variables.scss","sass/_mixins.scss"],
"file": "app.css"
}
```

As you can see, one of the sources points to the utilities folder inside ruby/compass installation (_../../../../../../../Dev/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-core-1.0.0.alpha.16/stylesheets/compass/utilities/sprites/_base.scss_), which is what might be bugging (currently ruby is installed at `C:\Dev\Ruby200-x64`).

Best Regards,
Raphael DDL

**Comment by scottdavis** [comment]
What is the expected return here for my sanity

**Comment by RaphaelDDL** [comment]
@scottdavis IMO, the map is used to point to the real location of the declaration of the classes.

Therefore, when I inspect an element with a class that uses sprites, I was expecting that the map would point to the @import or @include at `_sprites.scss`, and not to the compass utility .scss that generated it, because while it IS the real scss that generated it, it's not part of the project's assets, it's like an 'environment' thing (because it's ruby installation dependent, a localhost/live server can't resolve that path).

For example:

`_sprites.scss`
![image](https://f.cloud.github.com/assets/1087109/1724840/9bb60766-6276-11e3-8fe0-05680d96fe49.png)

The resulting `app.css` is:
![image](https://f.cloud.github.com/assets/1087109/1724819/50237f36-6276-11e3-9197-6ab17f9e2d49.png)

Which in DevTools using the map, does not point to the line 34 or 35 where they are generated, but instead it points to (/utilities/sprites/_base.scss) which since it's path can't be resolved by server, it's pointed then to the normal `app.css`

![image](https://f.cloud.github.com/assets/1087109/1724815/37c2073c-6276-11e3-8b80-76f4ec117869.png)

Come to think of, it's both the map and the line comments issue.
Well, I hope that does make sense, because that's what the warning is actually complaining about I think.

**Comment by chriseppstein** [comment]
You need to set up your chrome workspace so that it can find sass files that are not served by your webserver.

See slides 20-24: http://sass-3-3-presentation.herokuapp.com/#slide-20

**Comment by RaphaelDDL** [comment]
@chriseppstein But why would someone want to map compass' folder to see _base.scss while debugging, if this is a compass' utility that we shouldnt edit?
Shouldn't the map file point to the line of the file in your current project which it's importing the sprites, without caring for under-the-hood compass utilities?
