### ISSUE TITLE
DEPRECATION WARNING: RAILS_ROOT is deprecated!

### ISSUE THREAD

**Issue by maxd** [Compass/compass#149]
Hello, All
I see the following message when I execute unit-tests in Rails 3 environment:

```
DEPRECATION WARNING: RAILS_ROOT is deprecated! Use Rails.root instead. (called from parse_string at /home/closer/.rvm/gems/ruby-1.8.7-p249@rails3/gems/compass-0.10.1/lib/compass/configuration/serialization.rb:44)
```

Steps for reproduce:
1. Create Rails 3 application
2. Create any controller using Rails generator (also will be created unit-tests for it)
3. Execute unit-tests use "rake test" command

P.S.
I have removed this warning when I have replaced project_path in config/comapss.rb to:

```
project_path = defined?(Rails) ? Rails.root : RAILS_ROOT
```

**Comment by chriseppstein** [comment]
fixed by 6ab85ec
