### ISSUE TITLE
Compiler throws errors on Shadow DOM's new ^ and ^^ combinators

### ISSUE THREAD

**Issue by ebidel** [Compass/compass#1490]
Shadow DOM's next Cat (^^) and Hat (^) selectors throw compiler errors. With it, one can write rules that penetrate the shadow boundary:

```
x-tabs ^^ h2 {
  ...
}

x-tabs ^ x-panel ^ h2 {
   ...
}
```

Reference:
https://github.com/html5rocks/www.html5rocks.com/blob/master/content/tutorials/webcomponents/shadowdom-201/en/index.md#the--and--combinators

**Comment by scottdavis** [comment]
This is more of a sass syntax issue I would open an issue on http://github.com/nex3/sass

**Comment by chriseppstein** [comment]
I've moved this over to Sass's issue tracker. Thanks for the heads up, @ebidel!

**Comment by ebidel** [comment]
Thanks fellas!
