### ISSUE TITLE
A Compass project is behaving oddly returning undefined mixin and sometimes undefined operation

### ISSUE THREAD

**Issue by rpkoller** [Compass/compass#1494]
That one confused me completely. I am running Compass 0.12.2 and Sass 3.2.13 alongside a few plugins like modular scale, breakpoint, toolkit and singularity. All imported properly. For preprocessing i use Codekit. 
Since a few days a Wordpress theme i build is throwing back compile errors. either that a mixin is missing (the adjust-font-size-to mixin) or it errors on an operation: 

```
Syntax error: Undefined operation: "2 times ms(0)".
        on line 131 of /Library/Ruby/Gems/1.8/gems/compass-0.12.2/frameworks/compass/stylesheets/compass/typography/_vertical_rhythm.scss, in `adjust-font-size-to'
        from line 70 of /Applications/MAMP/htdocs/schmidundkreative/dFGn2SxAy8Z7bnM/wp-content/themes/schmideinander/scss/layout/_typography.scss
        from line 121 of /Applications/MAMP/htdocs/schmidundkreative/dFGn2SxAy8Z7bnM/wp-content/themes/schmideinander/scss/layout/_elementary.scss
        from line 2 of /Applications/MAMP/htdocs/schmidundkreative/dFGn2SxAy8Z7bnM/wp-content/themes/schmideinander/scss/style.scss
```

the ms mixin is modular scale related. Somehow it appears Compass doesn't find imported Plugins in this project. Odd thing is that in an test case where i use modular scale and vertical rhythm all works out like a charm. The error happens in Codekit but also in the terminal on 'compass watch' . Is it possible that it might be an cache related issue? If you need any further informations let me know. Best regards Ralf

**Comment by chriseppstein** [comment]
This is what you'd get when the ms function is not defined. Check with the modular scale team for help.
