### ISSUE TITLE
pretty-bullets mixin

### ISSUE THREAD

**Issue by websanya** [Compass/compass#1496]
Shouldn't it use $base-line-height value as fourth and fifth argument instead of using static values? Would be much more convenient.

```
@mixin pretty-bullets(
    $bullet-icon,
    $width: image-width($bullet-icon),
    $height: image-height($bullet-icon),
    $line-height: 18px,
    $padding: 14px
) { ... }
```

**Comment by scottdavis** [comment]
using base line height would only apply if you were using this with vertical rhythm you can how ever wrap this in your own mixin if you want to achieve that.
