### ISSUE TITLE
@import partial with path relative to import path workign strange

### ISSUE THREAD

**Issue by istrasoft** [Compass/compass#1498]
Assume the files 

```
/* In Main app file C:\wwwroot\app\scss\app.scss */

@import 
  "lib\scss\mything",
  "mything";

/* Comes from a framework, like Bootrap, Foundation etc, app agnostic */
C:\wwwroot\lib\scss\_mything.scss  

/* Overrides / complements some behaviour of the same component, app specific */ 
C:\wwwroot\app\scss\_mything.scss

/* Config */
C:\wwwroot\app\config.rb
```

(the actual structure is more complex, but I'm simplifying)

First I was using plain SCSS to compile my stylesheets. I used the --load_path option during sass watch to point to "C:\wwwroot". It worked great, and despite the same name of the original module scss and the override, it was clear which was which, due to a small chunk of relative path for the lib\scss\mything import.

Then I switched to Compass. Works fine, except I cannot keep the same syntax. If I add_import_path in config.rb as "C:\wwwroot", it fails to find "lib\scss\mything" import. If I set the import path explicitly to "C:\wwwroot\lib\scss", I have to @import "mything", which obviously collides with the other import. 

Now, maybe I missed something in the config docs, or maybe the way I'm handling original module/override with the same name in different paths is a bad practice ?

Thanks for pointing me to the right thing to do here ..

**Comment by lolmaus** [comment]
Try `@import "../../lib/scss/mything"`.

**Comment by istrasoft** [comment]
Thanks of course this works but it's very ugly IMHO, plus if you have a bunch of those, it's even more yucky... if I have to do this, what's the point of import paths then I might ask ?

**Comment by scottdavis** [comment]
try `add_import_path '../'` add_import_path takes a path relative to the compass project directory

**Comment by istrasoft** [comment]
Well, if I do that and then  @import "lib\scss\mything"; it does not work for compass compile. 

Only thing that works is either ugly relaitve paths everywhere like @lolmaus suggested, or add_import_path "C:\wwwroot\lib\scss" and @import "mything". 

Actually, the other thing that works is using  sass_options = {:load_paths => ["C:\wwwroot"]}  and then @import "lib\scss\mything", but that does fall back on SASS options... Maybe there is something to consider for improving the way add_import_path works ?

**Comment by scottdavis** [comment]
You may want to move this conversation to the compass google group you will have a greater chance of finding someone that may be able to help you. This seems like a path configuration issue on windows.

**Comment by istrasoft** [comment]
Hmm isn't it a issue of Compass itself then, if something that should be working in some way does not ?...

But thanks for the suggestion.

**Comment by scottdavis** [comment]
ok, can you run `compass config --debug` and post the output this will show all the configurations and the load paths

**Comment by istrasoft** [comment]
ok well sorry for the disturbance. actually once I inspected all the resolved paths in the result of the debug output, I found out there was indeed an issue with my config and location of some files. Also, somehow the relative import path does not resolve to what I expected but absolute works fine. Thanks again, and sorry.
