### ISSUE TITLE
compass appends .sass, .scss or .css to @import when not needed - breaking Google Fonts import

### ISSUE THREAD

**Issue by dpfranklin** [Compass/compass#150]
importing google fonts into a compass based project calls for the following import:

@import url(http://fonts.googleapis.com/css?family=Cantarell)

but compass reacts with:

WARNING: Neither http://fonts.googleapis.com/css?family=Cantarell.sass nor .scss found. Using http://fonts.googleapis.com/css?family=Cantarell.css instead.
This behavior is deprecated and will be removed in a future version.
If you really need http://fonts.googleapis.com/css?family=Cantarell.css, import it explicitly.

which breaks the import.  need an option to accept url as stated to override appending of extension.

**Comment by chriseppstein** [comment]
This is a sass issue and it's being tracked here: http://github.com/nex3/haml/issues#issue/177
