### ISSUE TITLE
Documentation unclear

### ISSUE THREAD

**Issue by neoswf** [Compass/compass#1502]
On Page: http://compass-style.org/help/tutorials/spriting/

This needs to be clear and explained at start of the page:
@include all-[sprite_name]-sprites - generates all the selectors automatically.
@include [sprite_name]-sprite - used for selector control.

Documentation assumes user understands this. And he does not if he stumble upon this page without former knowledge of the page.

**Comment by scottdavis** [comment]
Feel like making a pull request?

**Comment by neoswf** [comment]
Will try to do that soon. Thanks for the opportunity :)

**Comment by neoswf** [comment]
https://github.com/chriseppstein/compass/pull/1539
