### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by jaxgeller** [Compass/compass#1503]
On Page: http://compass-style.org/

I was looking for:
the UMDF charity link at the bottom

But instead I found:
As I clicked on it the domain had expired, my guess is it should point to http://www.umdf.org/site/c.8qKOJ0MvF7LUG/b.7929671/k.BDF0/Home.htm

**Comment by mendozagioo** [comment]
I see the link working to: https://www.kintera.org/AutoGen/Simple/Donor.asp?ievent=420320&en=4dKxFFOfF3JGLPNiF2LDLMMtHhKFIINjG8KBIQPALrG
