### ISSUE TITLE
Watch can't compile a specific sass file

### ISSUE THREAD

**Issue by alexisg** [Compass/compass#1505]
Trying to watch a specific sass file fails. Compass compile seems to work as expected. Using the most basic compass project you can see the results using watch vs. compile. 

Compass 1.0.0.alpha.17

compass watch sass/screen.sass -c config.rb

> > > Compass is watching for changes. Press Ctrl-C to Stop.
> > > You must compile individual stylesheets from the project directory.

compass compile sass/screen.sass -c config.rb
overwrite stylesheets/screen.css

**Comment by scottdavis** [comment]
Watch isn't build todo this... the sass watcher might... /cc @chriseppstein

**Comment by ghost** [comment]
https://github.com/guard/guard

**Comment by alexisg** [comment]
@scottdavis I feel like this is probably a regression though no? We have been using compass like this for some time on gamespot and giantbomb.com since we have themes and multiple stylesheets. The sass watch works but it has some issues with out multiple repo import paths (which I won't get into here). The compass twitter account (not sure if its handled by Chris) said they noticed the same bug so hopefully this does get some love at some point. 

@xFactorApplications I'll take a look at guard, thanks.

**Comment by chriseppstein** [comment]
It can now.
