### ISSUE TITLE
Feature Request: Stylesheets-only Version of Compass

### ISSUE THREAD

**Issue by OlenDavis** [Compass/compass#1511]
I'd like to know when you and your community would find as much value as I would in cherry-picking all the SASS-only content of Compass out into its own project to avail most of the power of Compass to Node-SASS/Libsass derivatives of the SASS compiler that are written without any dependencies on Ruby - and therefore can't use Compass.

Ultimately, I find alternatives to Compass for SASS to be lacking, and the only viable option - Bourbon - seems to be so lacking, I can't even really consider it viable - especially for someone with a Bootstrap-scale CSS framework written on Compass.

Please let me know as soon as possible if I should wait for anything you've already got in the works along these lines.

**Comment by chriseppstein** [comment]
This is what compass-core intends to become.

**Comment by OlenDavis** [comment]
You're wonderful; thanks!!
