### ISSUE TITLE
compass-core adding gem directory when running compass watch 

### ISSUE THREAD

**Issue by impatient** [Compass/compass#1518]
When running compass watch, I get the following error.

Errno::EACCES on line ["1143"] of /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb: Permission denied - /Library/Ruby/Gems/2.0.0/gems/compass-core-1.0.0.alpha.16/stylesheets/.listen_test

This only happens on watches, not compiles.  I've tried it on 3 different versions of ruby.  
1) Default ruby from mountain lion (1.8.7)
2) Ruby from homebrew (2.0.0)
3) Ruby from Mavericks (2.0.0) (Only 3 gems, totally unrelated to compass were installed prior)

The only scenario that worked was option 2 because my gem directory is readwrite for all users.

**I believe what is happening is the gem root directory (plus stylesheets)  /Library/Ruby/Gems/2.0.0/gems/compass-core-1.0.0.alpha.16/stylesheets/ is added to the Watcher to determine when a compile needs to happen.**

I can't find where the Watcher is created, but I'm pretty sure that is what is happening.  Is this necessary, does compass-core's gem path need to be added to the watcher?

For all default Mac installations, they will be required to run as sudo in order to use compass, which seems like a bad idea.

This is related to three different issues and hopefully sheds some new light on it.  I pulled down the compass source and the listen source, trying to get an idea of what was going on.  Hope this helps.

Related: 

https://github.com/chriseppstein/compass/issues/1406
https://github.com/chriseppstein/compass/issues/1497
https://github.com/chriseppstein/compass/issues/1421

**Comment by impatient** [comment]
compass watch --poll does NOT trigger this behavior.

**Comment by scottdavis** [comment]
This is an issue with our/sass listen integration its a known issue

**Comment by scottdavis** [comment]
dup #1497
