### ISSUE TITLE
Applying !important directive to Compass mixins

### ISSUE THREAD

**Issue by ghost** [Compass/compass#153]
In environments using vendor stylesheets, it would be nice to use Compass mixins with !important directive to override preset styles. Currently, this feature is not available.

**Comment by chriseppstein** [comment]
I'll grant you that it doesn't do this, but often the need for !important is because your styles need some refactoring.

Even if we change this it wouldn't be in a stable release, so you should find a workaround on your end for the time being.

**Comment by chriseppstein** [comment]
Going to close this without change for the time being.

**Comment by ghost** [comment]
Thanks for the response, workarounds are easy enough for this.

**Comment by pabliqe** [comment]
You could be right @chriseppstein, but "!important" is a CSS standard, doesn't it?

**Comment by krisbulman** [comment]
I must admit, I've also had a need for this in some edge cases. Jonathan Snook (SMACSS) actually recommends using !important for state rules when necessary http://smacss.com/book/type-state#tips

I agree though, it wasn't hard to find workarounds (writing own mixins, or just not using a compass mixin).

**Comment by pabliqe** [comment]
If someone else is having this issue, the best workaround I have found is to use #{} around params.

> float( #{ none !important } );

**Comment by thomasbachem** [comment]
This is still a very important (duh) feature. "!important" has its uses, especially if you need to override styles that you have no control over.

**Comment by thomasbachem** [comment]
@chriseppstein Could you please reopen this issue? Or do you still think this isn't needed?
