### ISSUE TITLE
LoadError on line ["70"] of /home/will/.rvm/gems/ruby-2.1.0/gems/compass-0.12.2/lib/compass/commands/watch_project.rb: cannot load such file -- fssm

### ISSUE THREAD

**Issue by melbourne2991** [Compass/compass#1530]
LoadError on line ["70"] of /home/will/.rvm/gems/ruby-2.1.0/gems/compass-0.12.2/lib/compass/commands/watch_project.rb: cannot load such file -- fssm

I get this error after running "compass watch"

I initially had compass working fine, until out of the blue I started getting this error. 

I tried some of the proposed solutions for apparently similar issues with no success. Even after I completely reinstalled ubuntu on my machine I am still getting this error.

When I first got this error I was not using RVM, now I am using RVM and having the same problem.

Here is the trace:

  /home/will/.rvm/gems/ruby-2.1.0/gems/compass-0.12.2/lib/compass/commands/watch_project.rb:70:in `perform'
  /home/will/.rvm/gems/ruby-2.1.0/gems/compass-0.12.2/lib/compass/commands/base.rb:18:in`execute'
  /home/will/.rvm/gems/ruby-2.1.0/gems/compass-0.12.2/lib/compass/commands/project_base.rb:19:in `execute'
  /home/will/.rvm/gems/ruby-2.1.0/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:43:in`perform!'
  /home/will/.rvm/gems/ruby-2.1.0/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /home/will/.rvm/gems/ruby-2.1.0/gems/compass-0.12.2/bin/compass:30:in`block in <top (required)>'
  /home/will/.rvm/gems/ruby-2.1.0/gems/compass-0.12.2/bin/compass:44:in `call'
  /home/will/.rvm/gems/ruby-2.1.0/gems/compass-0.12.2/bin/compass:44:in`<top (required)>'
  /home/will/.rvm/gems/ruby-2.1.0/bin/compass:23:in `load'
  /home/will/.rvm/gems/ruby-2.1.0/bin/compass:23:in`<main>'
  /home/will/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
  /home/will/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in`<main>'

EDIT: I believe I tried some of the solutions here: https://github.com/chriseppstein/compass/issues/922, before reinstalling my OS (Ubuntu 12.04), again without success..

I am getting command not found with "rubygems-bundler-uninstaller"

**Comment by melbourne2991** [comment]
I found a solution that isn't exactly Ideal, I have to install ruby and rubygems without RVM.

as mentioned here: https://github.com/mpapis/rubygems-bundler/issues/58, not sure if this is a compass issue, or a rubygems bundler one?

**Comment by alastair-todd** [comment]
Isnt the recommended Ruby version 1.93?

Also this is being reported a lot in Stackoverflow (i had it myself).

The current 

```
gem install compass
```

apparently installs some bleeding edge version of SASS. this was my workaround

```
gem uninstall sass
gem install sass
```

**Comment by chriseppstein** [comment]
we use listen now.
