### ISSUE TITLE
Wrong syntax in baseline-grid-background()

### ISSUE THREAD

**Issue by jonespen** [Compass/compass#1531]
`baseline-grid-background()`, which uses the function `get-baseline-gradient()`, outputs `background-image: linear-gradient(bottom, #000000 5%, rgba(0, 0, 0, 0) 5%);` (among other vendor prefixes ofc). This is not according to the [linear-gradient specification](https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient#Syntax), and the background is ignored by Chrome. The correct output should be `background-image: linear-gradient(to bottom, #000000 5%, rgba(0, 0, 0, 0) 5%);` (note _to bottom_)

**Comment by mirisuzanne** [comment]
Thanks! Can you submit a pull request on the master branch?

**Comment by chriseppstein** [comment]
PR was merged.
