### ISSUE TITLE
Make Compass more modular and lightweight

### ISSUE THREAD

**Issue by emagnier** [Compass/compass#1534]
I love Compass and I use it on most of my projects. However I uses only a small part of this framework. I use a lot the Sprite feature, and occasionally the Image Dimensions & Inline Data helpers.

In contrast the mixins library seem (in my point of view) heavy and outdated (vs. [Autoprefixer](https://github.com/ai/autoprefixer) or [Bourbon](http://bourbon.io/)) and I never use the other features (I prefer to use other dependencies like [Inuit.css](https://github.com/csswizardry/inuit.css)). So I always have the feeling I use a big framework that adds a lot of features I do not need.

However I think Compass really helped to grow the community around Saas. So I have a lot of respect for this project. Sass is now very popular and is starting to be well integrated in IDEs. A lot of projects are developed around this language, including these nice Compass extensions: [SassyLists](http://sassylists.com/), [Singularity](https://github.com/Team-Sass/Singularity), [Toolkit](https://github.com/Team-Sass/toolkit)...

Today I would love to use Compass as a much more modular tool, providing a nice place to extensions. The sprite helpers would become a Compass extension. And I could embed only what I need in my projects. So Compass would be a sort of extension / package manager around Sass. It will continue to better federate and manage the extension ecosystem around Sass.

And with the advent of [LibSass](https://github.com/hcatlin/libsass) (an extremely fast Sass compiler), I think Compass has its full place to play here. In addition, it should be easier to port and maintain different sub-modules / specialized extensions, rather than a monolithic framework with (too) much features.

**Comment by emagnier** [comment]
Also sorry for my bad approximative English, I hope this was not too long :-)

**Comment by scottdavis** [comment]
We are currently in a grand decomposition if you check the master branch.

**Comment by mirisuzanne** [comment]
To translate for Scott — we're doing exactly what you asked for, and breaking Compass out into more modular pieces. And you should see the new, slick, caniuse-driven mixin library. :)

**Comment by emagnier** [comment]
Cool! That's a great news!
I can't wait to see it, thanks for all your good work :+1:

**Comment by InSuperposition** [comment]
Just for clarification; Does this mean that after the decomposition, Compass will be able to be compiled with libSass (SassC)? If not, are the plans to move in that direction? Is there another discussion on this topic so I can learn more?

Thanks for the excellent work so far.

**Comment by scottdavis** [comment]
Not really that one of the goals some day Libsass still Incomplete and does support all the new features of sass we use

**Comment by chriseppstein** [comment]
as scott noted, this is a direction we are headed. Thanks for the input.
