### ISSUE TITLE
Has _filter.scss been deprecated in v0.13?

### ISSUE THREAD

**Issue by spigotdesign** [Compass/compass#1536]
I've got a project where I'd like to use the animation mixins in v0.13, as well as filter mixins. _filter.scss is no longer included in 0.13, has it been depreciated?  

For the time being, I've copied it over from 0.12.2. Hopefully that doesn't cause any issues.

**Comment by chriseppstein** [comment]
@import "compass/css3/filter" should still work -- my tests pass with it.
