### ISSUE TITLE
lines-for-font-size only works with absolute units

### ISSUE THREAD

**Issue by jroitgrund** [Compass/compass#1541]
Because of the [line comparing the calculated line-height with the minimum padding](https://github.com/chriseppstein/compass/blob/stable/frameworks/compass/stylesheets/compass/typography/_vertical_rhythm.scss#L133), line-for-font-size breaks with "incompatible units: px and $font-unit" when $font-unit is anything else than px.

Using only the logic for calculating the number of lines without the part for ensuring it exceeds minimum padding:

```
ceil($font-size / $base-line-height)
```

no error is thrown.

**Comment by chriseppstein** [comment]
Set the minimum padding to the unit you are using so the math works.
