### ISSUE TITLE
Permission denied on -pre version

### ISSUE THREAD

**Issue by nexflo** [Compass/compass#1542]
doing compass watch XY compiles then fgives following error
Errno::EACCES on line ["1143"] of /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb: Permission denied - /Library/Ruby/Gems/2.0.0/gems/compass-core-1.0.0.alpha.16/stylesheets/.listen_test

sudo does the trick...but still...

**Comment by mprins** [comment]
duplicate of #1497
