### ISSUE TITLE
v0.12.2 is incompatible with Sass 3.3.0.rc.2

### ISSUE THREAD

**Issue by mislav** [Compass/compass#1544]
The sass version contraint in the gemspec should be changed to `~> 3.2.14`

sstephenson/rbenv#546

**Comment by Anahkiasen** [comment]
Doesn't really make sense, if you're using the prerelease of Sass you want the prerelease of Compass.

**Comment by ryanburnett** [comment]
I wasn't using the prerelease of Sass or Compass. Installed with:

```
gem install compass
gem install sass
```

**Comment by mislav** [comment]
@Anahkiasen I might be intending to use Sass 3.2.14 with current Compass, and Sass 3.3.0.pre for another project. But since Compass will try to load the latest available 3.x Sass on the system, it will load an incompatible version.

Version constraints in the gemspec are there so you can avoid loading incompatible version. This is a case of incompatible version, so a version constraint should be adjusted appropriately.

**Comment by scottdavis** [comment]
I'll try to get a 0.12 cut with the fix soon as I get my power back unless @chriseppstein beats me to it

**Comment by Anahkiasen** [comment]
@mislav Yeah my bad I misread the linked thread.

**Comment by developher-net** [comment]
The default install of compass now fails because SASS 3.3 is now stable. Compass needs the gemspec updated.

**Comment by scottdavis** [comment]
I just pushed 0.12.3 that locks sass to 3.2 http://rubygems.org/gems/compass/versions/0.12.3
