### ISSUE TITLE
1.0: transition for transform not rendering prefixed transform

### ISSUE THREAD

**Issue by thany** [Compass/compass#1545]
Consider this example:

```
@include transition(ease-in 1s transform);
```

This renders the following css:

```
-webkit-transition: ease-in 1s transform;
-moz-transition: ease-in 1s transform;
-o-transition: ease-in 1s transform;
transition: ease-in 1s transform;
```

That's not correct. Instead, it should be:

```
-webkit-transition: ease-in 1s -webkit-transform;
-moz-transition: ease-in 1s -moz-transform;
transition: ease-in 1s transform;
```

(I left the -o- out because it's not neccesary - Opera doesn't need prefixes)

Can this be fixed please?

Using Compass 0.12.2, Sass 3.2.14, Ruby 2.0.0p353, Windows 7 x64

**Comment by thany** [comment]
This problem persist in 1.0.0.alpha.17

**Comment by Anahkiasen** [comment]
[Related testcase](http://sassmeister.com/gist/8861229)

**Comment by thany** [comment]
It does work when using only longhand properties:

```
@include transition-easing(ease-in);
@include transition-duration(.1s);
@include transition-property(transform);
```

But this produces rather verbose css.
This compiles correctly too:

```
@include transition(transform);
```

But that leaves you with the browser's default transition-duration and transition-timing-function.

**Comment by chriseppstein** [comment]
0.14% of users would be affected if the `-o` prefix was dropped. The default threshold is 0.1%. If you change `$graceful-usage-threshold: 0.5%` then you'll see that the opera prefix is dropped (as well as several others in different places).

`$debug-browser-support: true;` is your friend.

**Comment by thany** [comment]
This problem still exists in alpha.21

Please reopen, since this produces problems for Chrome, not just Opera. I've been scratching my head on why my transitions wouldn't work on Chrome, because Chrome apparantly still needs the `-webkit-` prefix.

Current workaround:

```
@include transition(ease-in 1s);
@include transition-property(transform);
```

But this is more verbose scss and produces more verbose css.
