### ISSUE TITLE
NoMethodError on line ["37"] of /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/configuration/adapters.rb: undefined method `map' for "scss/vendor":String  Run with --trace to see the full backtrace

### ISSUE THREAD

**Issue by alycda** [Compass/compass#1547]
NoMethodError on line ["37"] of /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/configuration/adapters.rb: undefined method `map' for "scss/vendor":String

  /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/configuration/adapters.rb:67:in `sass_load_paths'

  /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/configuration/adapters.rb:52:in `to_sass_engine_options'

  /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/configuration/helpers.rb:88:in `sass_engine_options'

  /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/commands/update_project.rb:63:in `new_compiler_instance'

  /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/commands/update_project.rb:42:in `perform'

  /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/commands/base.rb:18:in `execute'

  /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/commands/project_base.rb:19:in `execute'

  /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:43:in `perform!'

  /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:15:in `run!'

  /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/bin/compass:30:in `block in <top (required)>'

  /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/bin/compass:44:in `call'

  /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/bin/compass:44:in `<top (required)>'

  /usr/bin/compass:23:in `load'

  /usr/bin/compass:23:in `<main>'

**Comment by chriseppstein** [comment]
I need to see your compass configuration. Depending on that, I may re-open it.
