### ISSUE TITLE
1.0.0.alpha.17: Compass still ouputting -o- prefixes all over the place

### ISSUE THREAD

**Issue by thany** [Compass/compass#1549]
The -o- prefix in not needed. Opera recognizes every CSS3 propery that it supports without prefix. Please exclude them by default.

What's more, the variable $experimental-support-for-opera no longer works:

```
WARNING: Compass has changed how browser support is configured. See the CHANGELOG for more details. The following config uration variables are no longer supported: $experimental-support-for-opera.
```

And I can't find the CHANGELOG anywhere, so I have no way of figuring what to do in place of this variable...

**Comment by Anahkiasen** [comment]
Prefixes data is now taken from Can I Use usage data, so they're here for a reason. Most likely the `o` prefixes are there for Opera mobile and such. You can see the details by enabling a variable : http://sassmeister.com/gist/8861447

See [this post](https://github.com/chriseppstein/compass/issues/1417#issuecomment-26752070) for an example of configuring the new system.

**Comment by thany** [comment]
Perhaps the default minimums and thresholds need some tweaking then. Opera's -o- requirement is for up to version 12.00 and was removed as of 12.10. Opera's users are generally a bit more tech-savvy and eager to update (well, up to 12.16 for me at least - as of Opera 15 one might as well install Chrome).

Opera Mobile is another story of course. Since that is a browser that comes with many low-end devices in Africa and Asia, those folks might be using outdated versions. But I suppose that's what `$browser-minimum-versions` is for.

So the default threshold of 1% may have to vary on browser type somehow.

**Comment by chriseppstein** [comment]
http://beta.compass-style.org/help/documentation/tuning-vendor-prefixes/

Contains all the details for how to tune your vendor prefix support. I'll make this more discoverable by mentioning this page from the warning we emit.

**Comment by chriseppstein** [comment]
In particular, if you turn on debug output you will see exactly why compass is including the opera prefix and it should be clear what you can do to turn it off.

I'm not going to add any per-browser threshold. A user is a user irrespective of what browser they've picked. You can set the threshold to 100% and rely solely on browser minimum versions if you prefer to decide what browsers you want to support.

**Comment by chriseppstein** [comment]
reopening to track better doc reference.
