### ISSUE TITLE
Horizontal linear gradient doesn't show up in IE10/11

### ISSUE THREAD

**Issue by feklee** [Compass/compass#1553]
On Page: http://compass-style.org/examples/compass/css3/gradient/

I was looking for:
Horizontal gradient in IE10/11 (Windows 7, browserstack.com)

But instead I found:
Horizontal linear gradient doesn't work. See attached screenshot.

![Horizontal gradient missing in IE11](https://f.cloud.github.com/assets/14994/2124420/2941989c-923e-11e3-955f-0543f8bc11ce.jpg)

**Comment by neilhem** [comment]
Compass version 0.12.2 linear-gradient function does not generate proper syntax of gradient for IE10+ (Which support only new syntax with "to"). You need to upgrade to pre release version of Compass.
