### ISSUE TITLE
Sprite - Smart Layout - Not Working

### ISSUE THREAD

**Issue by spacelab-sp** [Compass/compass#1555]
Hi, I'm trying to use the smart layout, but cannot make it work.

@import "compass/utilities/sprites";

$icons-layout:smart;
@import "icons/*.png";
@include all-icons-sprites;

If I change to vertical/horizontal/diagonal works,
I have 27 icons with 16x16.

Any idea?

**Comment by scottdavis** [comment]
compass version?

**Comment by spacelab-sp** [comment]
Version: 0.12.2.

I have found what happened, is because all icons are 16x16.
I added some big icons, and is working now, the grid is organized based on the size of the biggest icon. 
Some sprite generators don't have this problem.

Dont know if you guys can fix this, i'll leave open in case.

Thanks for this great tool.

**Comment by scottdavis** [comment]
So its working? im not sure what we need to fix then?

**Comment by spacelab-sp** [comment]
Working, but not as expected.

If I have 30 (or any other number) images with same size (16x16 as my case), the sprite will be generated in vertical, not rectangular as a smart layout should be in my opinion.

**Comment by spacelab-sp** [comment]
Here is my generated sprite, the layout on the scss is smart.

![icons-s23239710c3](https://f.cloud.github.com/assets/4255796/2128521/e39008b8-927b-11e3-8546-ca5a4d0318f8.png)

**Comment by scottdavis** [comment]
This is expected the smart packer optimizes vertically due to this is the most memory efficient in the browser.
