### ISSUE TITLE
Error during compile

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#1557]
Stack trace is here:

https://github.com/chriseppstein/compass/issues/1108#issuecomment-34581684

**Comment by ghost** [comment]
Just rebuilt mac osx machine today and after re-installing everything compass --pre and sass -pre have also started to get 'NoMethodError on line ["87"] of /Library/Ruby/Gems/2.0.0...'. Prior to rebuild was working like a charm. Perhaps something i forgot to do or perhaps some recent change?
Set-up is Grunt-contrib-compass as other commentators.

Interesting 'manually running' i.e $ sass --compass --sourcemap --watch sass/styles.scss:app/css/styles.css works. 

Hope this is helpful in some way and appreciate your help and dedication to an incredible project.

**Comment by jackw** [comment]
I don't know if this helps isolate the bug but I had a play with my setup. I was running Ruby 2.0 with compass-1.0.0.alpha.18 and getting this error. Switched to Ruby 1.8.7 and installed the following:
- compass (1.0.0.alpha.16)
- compass-core (1.0.0.alpha.16)
- sass (3.3.0.rc.2)

Source maps will now build without any issue on the command line running `compass compile`.

**Comment by sebastianhenneberg** [comment]
Same problem here. Stack trace is identical to @chriseppstein. I fixed the problem by installing the exact versions of compass, compass-core and sass @jackw stated. This even works with Ruby 2.0.

**Comment by JohnAlbin** [comment]
Thank god for Bundler. I'm running older versions of Sass/Compass on my projects with `bundle exec` and a gemfile.lock.

**Comment by chriseppstein** [comment]
Fixed by b4300d0c188609c402caa04a883fba04ec8cbf22
