### ISSUE TITLE
`compass` gem installs `listen` gem in production

### ISSUE THREAD

**Issue by 8bitDesigner** [Compass/compass#1558]
[This gemfile](https://github.com/chriseppstein/compass/blob/1.0.0.alpha.18/cli/compass.gemspec#L20) pulls in the `listen` dependency for all environments. This means that in our production web app, we're shipping a grip of native gems and filesystem watchers (`listen`, `rb-fsevents`, etc..) that aren't being used. Should this be `add_development_dependency` instead?

**Comment by chrisgriffin** [comment]
This resolves the issue for us:

http://stackoverflow.com/a/22003244/499566

**Comment by chriseppstein** [comment]
`add_development_dependency` means that it is a gem used to develop compass, not that it is a rails-style development concept. Also, this is also a sass issue as they depend on it too. I know it's cumbersome to have the gems you're not using getting downloaded and installed, but for now this is how it works. There is significant work to refactor sass and compass and extract those components to a separate gem that can be excluded from your production gem bundle. I'm not saying it shouldn't happen, just that it's very low priority at this time.

**Comment by chriseppstein** [comment]
we got rid of the listen dependency.
