### ISSUE TITLE
Defining the filename of a sprite file

### ISSUE THREAD

**Issue by jurgenhaas** [Compass/compass#1560]
Is it possible to define the resulting file name of a sprite? Currently it's the same name as the directory followed by a hash. That wouldn't hurt, unless you're working with a VCS like git or subversion and checkin your development results regularly to the vcs. That requires to add a new sprite and delete the old one from the vcs which is just some extra overhead.

If this behaviour would remain as a default but a new option would allow us to just overwrite an existing sprite when ever there is a change, then we would get the sprite history even in the vcs.

**Comment by scottdavis** [comment]
I never check in generated assets. I always compile then deploy. Less VCS leg work.

**Comment by jurgenhaas** [comment]
I do, because we use the vcs as the deployment mechanism. In other words, no file ever makes it on to the test or production server, if it wasn't in the vcs before.

**Comment by lolmaus** [comment]
It's considered to be a good practice not to store compilation results (CSS and sprites) in the VCS.

You should compile serverside with a deployment routine (Grunt, Capistrano...) or a Git hook ([example](http://stevegrunwell.com/blog/automatically-recompile-sass-upon-deployment-using-git-hooks/)).

**Comment by jurgenhaas** [comment]
Don't think that's a good practice. It requires Compass and all of it's dependencies on a production server which doesn't seem to be making sense. From my perspective, compilation is part of the development process and shouldn't get onto any other stage.

**Comment by lolmaus** [comment]
It's not a proper place to discuss this issue, my final statement: compilation is a part of a build routine. Building may not be necessary for development (for example, i develop frontends with [Middleman](http://middlemanapp.com/) which renders Sass on the fly and i don't need to compile it) but is crucial for deployment. So i consider building to be part of deployment.

Also, you can build before or after deployment, it's a matter of your team's preference. But you should not store assets in VCS. Your repo will soon become bloated and a nuisance to clone. Instead, update your deployment routine with an asset compilation step.

The same recommendations concern library assets, e. g. jQuery. You should not keep them in the repo. Instead, download them automatically with Bower and Grunt.

**Comment by chriseppstein** [comment]
compass removes the file and adds a new one. you vcs will track these changes with the same efficiency as if they were the same file name.
