### ISSUE TITLE
Changelog for 1.0.0.alpha.18?

### ISSUE THREAD

**Issue by thany** [Compass/compass#1567]
Just found out that there's an update to this version... But I have no way of knowing what has been changed. Would you please put the latest changelog somewhere? I mean in a place folks can find it?

**Comment by mprins** [comment]
you can see the changes like this: https://github.com/chriseppstein/compass/compare/1.0.0.alpha.17...1.0.0.alpha.18 (`https://github.com/chriseppstein/compass/compare/1.0.0.alpha.17...1.0.0.alpha.18`)

**Comment by thany** [comment]
Ah, nifty. But perhaps it's a good idea to make changelogs more easily findable... For example. by placing a CHANGELOG file in the project root, like many others do.

**Comment by Anahkiasen** [comment]
[There is one](https://github.com/chriseppstein/compass/blob/master/compass-style.org/content/CHANGELOG.markdown). You can find any file in a repo by typing `t` and then the name of your file.

**Comment by thany** [comment]
That's the one :)

Now maybe delete or merge these old ones, just for clarity. When you have the time of course.
[CHANGELOG-v0-11-beta](https://github.com/chriseppstein/compass/blob/master/compass-style.org/content/CHANGELOG-v0-11-beta.markdown)
[CHANGELOG-v0-10-0-beta](https://github.com/chriseppstein/compass/blob/master/compass-style.org/content/CHANGELOG-v0-10-0-beta.markdown)
