### ISSUE TITLE
#add_import_path in config file breaks -I CLI flag

### ISSUE THREAD

**Issue by bdkjones** [Compass/compass#1569]
If you have a config.rb file in which you write an `add_import_path` line such as this:

```
add_import_path "some/path/to/something"
```

Then you call Compass from the command line and pass the `-I` flag to add some additional include paths, every path added with an `-I` flag is ignored. 
### How I Know

I know this because Compass fails to compile my scss file and tells me it could not locate an imported file in a path which I'm including via an `-I` flag. The path that I have included is NOT listed in the "include paths" list that Compass spits out with this error.

When I delete the `add_import_path` line from the config.rb file, Compass correctly adds my `-I` paths to the include path list and finds my imported file while compiling.
### Version

I am working with the master branch of Compass; the 1.0 pre-release. I have not tested this with the stable branch.

**Comment by chriseppstein** [comment]
I'll look into it for the 1.0 release. Shouldn't be too hard to fix.

**Comment by bdkjones** [comment]
If I wanted to _attempt_ to look into this for you, which files in the repo would be relevant?

**Comment by chriseppstein** [comment]
fixed by fd3dad6a2437979e03fa4d80c25a30d653447a1b and ec6284c7368c24f7a3ad3bb6e83e931e06a19a76
