### ISSUE TITLE
Duplicated compiled CSSs

### ISSUE THREAD

**Issue by mhfs** [Compass/compass#157]
Hey there, I'm getting a weird behavior and could not figure it out by myself.

My scss/sass files are getting compiled to both public/stylesheets and public/stylesheets/compiled.

I'm using compass 0.10.2 with haml 3.0.9 and rails 3.0.0.beta3.

My config file is as follows:

```
# This configuration file works with both the Compass command line tool and within Rails.
# Require any additional compass plugins here.
project_type = :rails
project_path = Compass::AppIntegration::Rails.root
# Set this to the root of your project when deployed:
http_path = "/"
css_dir = "public/stylesheets/compiled"
sass_dir = "public/stylesheets/sass"
environment = Compass::AppIntegration::Rails.env
# To enable relative paths to assets via compass helper functions. Uncomment:
# relative_assets = true
```

Thanks in advance.

Cheers,
Marcelo

**Comment by chriseppstein** [comment]
pretty sure you must have a plugin or some sort of errant configuration going on. If you care to, please post a minimal rails app to github that reproduces this issue and I'll debug it.
