### ISSUE TITLE
Small grammer correction

### ISSUE THREAD

**Issue by jatemack** [Compass/compass#1570]
On the http://compass-style.org/help/ page I found:

Now you can edit the *.scss files in the sass directory with the text editor of your choice. the compass watch process will automatically compile your them into css..

Under the Manual Setup section, but it should probably read:
Now you can edit the *.scss files in the sass directory with the text editor of your choice. the compass watch process will automatically compile _them into your_ css..

**Comment by scottdavis** [comment]
mind making a pull request?

**Comment by parkr** [comment]
Closed by https://github.com/chriseppstein/compass/pull/1572
