### ISSUE TITLE
sourcemap parameter throws undefined method error

### ISSUE THREAD

**Issue by jeremy-green** [Compass/compass#1574]
I've tested on Compass 1.0.0.alpha.16 and 18.  When I specify `sourcemap = true` or pass sourcemap in via the compile method `compass compile --sourcemap`, I get the following error: `/Users/admin/.rvm/gems/ruby-1.9.2-p320/gems/compass-1.0.0.alpha.16/lib/compass/actions.rb: undefined method `index' for nil:NilClass`.  I'm using ruby 1.9.2 on a Mac at work and ruby 2.0.0 -- I think -- on Ubuntu at home.  I opened the offending file and realized that I don't know a thing about Ruby.

**Comment by jermbo002** [comment]
Having the same issue with the .18 alpha on windows.
