### ISSUE TITLE
border-corner-radius("top", "right",[value]);

### ISSUE THREAD

**Issue by dotnetCarpenter** [Compass/compass#1579]
`border-corner-radius("top", "right",[value]);` outputs `-moz-border-radius-topright: [value];`

It should probably be removed as Firefox stop supporting -moz-border-radius in Firefox 13

`compass --version Compass 0.12.2 (Alnilam)`

**Comment by mirisuzanne** [comment]
This is fixed in the master branch, where prefixes are based on caniuse data.
