### ISSUE TITLE
Compass is not deleting old sprites after assigning generated_images_dir (again?)

### ISSUE THREAD

**Issue by cookch10** [Compass/compass#1582]
I noticed that Compass was not removing old sprites in the generated_images_dir, which is a previously known issue (https://github.com/chriseppstein/compass/issues/931).  This was happening with compass-0.12.2, so I just updated to compass-0.12.3 but this issue still seems to persist.  Manual inspection of _sprite_methods.rb_ shows the culprit:

```
def cleanup_old_sprites
  Dir[File.join(Compass.configuration.images_path, "#{path}-s*.png")].each do |file|
    log :remove, file
    FileUtils.rm file
    Compass.configuration.run_sprite_removed(file)
  end
end
```

**Comment by chriseppstein** [comment]
This is fixed on master already: https://github.com/chriseppstein/compass/blob/master/cli/lib/compass/sass_extensions/sprites/sprite_methods.rb#L66
