### ISSUE TITLE
Setting [$lines] in adjust-font-size-to breaks following rhythm

### ISSUE THREAD

**Issue by modermo** [Compass/compass#1584]
Observe the span behaviour in this Gist:

http://sassmeister.com/gist/9374486

You'll notice that it throws the proceeding elements to shift off the baseline by 1/3.  whilst applying a margin-trailer of 4/3 to the span element fixes resets the following elements' adherence to the baseline, the bottom border of the span element is still still off.

Do you know of a fix to this?

**Comment by mirisuzanne** [comment]
If you set `$lines` to `2/3`, then after 4 lines you will be 1/3 off your baseline. That's not a bug, that's how the rhythm module works. You are in control of your rhythm. If you want to stay on rhythm, any fractions have to add up to an integer.

In any case, there is nothing precise about vertical rhythms on the web. They are useful for giving a sense of consistent spacing, but trying to achieve 100% pixel-precision across browsers is not realistic. Compass can't do anything about that. We can make the math simpler, and provide shortcuts, but the rest is a matter of browser rendering and sub-pixel rounding.

**Comment by modermo** [comment]
Ok, nice. Makes sense. I thought there may have been a rule I wasn't considering.

Thanks for the response. The typography set of mixins are really great. :)
