### ISSUE TITLE
How to enable this plugin without compass?

### ISSUE THREAD

**Issue by UltCombo** [Compass/compass#1586]
Sorry for the dumb question, but I've read through the [usage](https://github.com/chriseppstein/compass/tree/master/import-once#usage) section and I didn't understand how to enable this plugin on a non-compass non-ruby project environment. As far as I can see, the only proper place for that `require` is a `config.rb` file which only makes sense with the `--compass` flag.

Am I missing something? What would be the proper way to activate this plugin?

Thanks.

**Comment by UltCombo** [comment]
Oh, `-r 'compass/import-once/activate'` seems to work fine. I've took a little while to figure that out, perhaps add that alternative to the docs?

**Comment by pprince** [comment]
I was reading that part of the documentation the other day, and I also
found it unclear.

Thanks,
-Paul P.

**Comment by chriseppstein** [comment]
fixed by 55be8b56ccbd0860474936140192ed46ddd1d24a
