### ISSUE TITLE
Sass 3.3.0 compatibility

### ISSUE THREAD

**Issue by lencioni** [Compass/compass#1587]
Sass 3.3.0 [was released yesterday](http://sass-lang.com/documentation/file.SASS_CHANGELOG.html#330_7_march_2014). I know that [you are working on it](https://twitter.com/compass/status/442129752850042880), but I wanted an issue where folks can easily track the progress.

Thanks for all the hard work!

**Comment by Anahkiasen** [comment]
Doesn't compass 1.0 already work with Sass 3.3 ?

**Comment by lencioni** [comment]
Probably, but it hasn't seen a full release yet.

**Comment by chriseppstein** [comment]
Working on it. They should track the 1.0 milestone.
