### ISSUE TITLE
Main help documentation page needs rewriting (obsolete)

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#1589]
the main help page http://beta.compass-style.org/help/ is completely out of date.

**Comment by xiwcx** [comment]
Hi, is there any way I can help with this? I'd be happy to flesh out something more detailed if given a general outline of what needs to be omitted and added.

**Comment by FrancescoK** [comment]
I'd be very glad to help as well.

**Comment by scottdavis** [comment]
I have cleaned this up and removed the old information for 1.0 but it still needs some love

**Comment by chriseppstein** [comment]
did a bunch of stuff
