### ISSUE TITLE
inset box shadow

### ISSUE THREAD

**Issue by chrisdrackett** [Compass/compass#159]
Safari 5 and mobile webkit in iOS 4 supports the inset keyword on box shadow:

http://cssdesk.com/d8FaK

It would be great to have this support in compass.

**Comment by chrisdrackett** [comment]
also supported in firefox 3.5:

https://developer.mozilla.org/en/css/-moz-box-shadow

**Comment by mirisuzanne** [comment]
Also in Opera and Chrome. Safari was the hold-out (ignoring the obvious IE). 'Spread' is also now supported in all of them. I adjusted my earlier proposal to account for it all:

http://gist.github.com/401744

I have that working the same in all-but-IE, and will be glad to submit it as a patch.

**Comment by chriseppstein** [comment]
fixed by 0bcbd2b2fd8c6adc6802571d9738282f2ac7e577
