### ISSUE TITLE
filter: brightness(1.1) is broken

### ISSUE THREAD

**Issue by hagenburger** [Compass/compass#1599]
Compass’ own [brightness() function](https://github.com/chriseppstein/compass/blob/master/core/stylesheets/compass/utilities/color/_brightness.scss) breaks the [official CSS3 filter brightness](http://www.w3.org/TR/2013/WD-filter-effects-1-20131126/#funcdef-brightness):
- Compass returns a percentage of a color: `brightness($color)` = 0% to 100%
- CSS3 expects a value between 0 and 2 or 0% and 200%: `brightness(1.1)` = make it 10% brighter 

I would prefer to rename Compass’ `brightness($color)` to `brightness-of($color)` and raise a warning if `brightness($value)` is called with a color value. What do you think?

---

If you have the same issue, here’s a work around:

``` scss
.whatever {
  @include filter(unquote("brightness(0.7)"));
}
```

**Comment by chriseppstein** [comment]
We should just return that string as the result of the function if the value is a number instead of a color. This is what we do elsewhere in sass. Could you make a patch?

**Comment by hagenburger** [comment]
Sure.

**Comment by hagenburger** [comment]
@chriseppstein do you think this might get merged? My projects are full of work-arounds ;)

**Comment by chriseppstein** [comment]
@hagenburger 

don't we want `brightness(1.1)` to return `brightness(1.1)` instead of `1.1`?

**Comment by chriseppstein** [comment]
Assuming you said yes. :)

Merged and pushed to master.

**Comment by hagenburger** [comment]
Ehm, “yes” (I was busy yesterday). As far as I see you are right and it needs a fix. Did you change your mind?

**Comment by chriseppstein** [comment]
@hagenburger I added a follow-on commit: 690477a1348bb92c978e7ea226087510ab495e91

**Comment by hagenburger** [comment]
Thanks :)
