### ISSUE TITLE
Replace-text doesn't work on Safari 4

### ISSUE THREAD

**Issue by marnen** [Compass/compass#16]
Replace-text doesn't work on Safari 4. Discussion with Chris (and pull request for patch) is at http://github.com/inbox/147846 ; filing here for tracking purposes.

**Comment by marnen** [comment]
I suppose I should mention that the commit (in my fork) that fixes this is http://github.com/marnen/compass/commit/36f83511383fdd02be58b0a596a53080b0cb3861 .

**Comment by tdreyno** [comment]
I am having no issues with Safari 4. Perhaps you're mistaking !x and !y for the !width and !height (as in your patch), when they are actually for positioning the background image.

Works here: http://www.quicksnapper.com/files/9241/5712114684A3983E08A53A.png

Additionally, it seems quite easy to add width/height to the selector in the normal Sass fashion (I always do this) than to add more variables to the mixin.

**Comment by marnen** [comment]
You're right that I was a bit confused about the function of the !x and !y parameters, but even when I omitted them entirely, replace-text didn't work. I'll test again and report if anything changes.

**Comment by marnen** [comment]
Setting height and width and using 0 for !x and !y seems to have done the trick. I guess I'll just wrap that all in my own convenience function. Thanks for your advice here.

**Comment by chriseppstein** [comment]
I added more [comments to the mixin](http://github.com/chriseppstein/compass/commit/4533a00085c300aa57ac0c7b7370d5857e17930d) in the code.
