### ISSUE TITLE
multiple box shadows

### ISSUE THREAD

**Issue by chrisdrackett** [Compass/compass#160]
Now that safari support inset box shadows I really would love to be able to add multiple box shadows to an object:

here is an example:
http://cssdesk.com/JaaVF

**Comment by erikdahlstrand** [comment]
I second this feature request. Multiple shadows would be great.
    -moz-box-shadow:  none | <shadow> [,<shadow>]*

**Comment by hexorx** [comment]
I made this ugly [mixin](http://gist.github.com/585198) in order to get it working for me.

**Comment by elado** [comment]
Thank you, hexorx!

**Comment by mathiasschopmans** [comment]
multiple text-shadows would be awesome, too. ;)

**Comment by chriseppstein** [comment]
This feature is waiting for list support in Sass 3.1

**Comment by chriseppstein** [comment]
I've started a branch where we'll be re-writing some of the css3 modules to keep up with CSS3 developments in the last year or so and Sass enhancements too.

This feature is addressed [here](https://github.com/chriseppstein/compass/commit/806c957e867a1ae3e114b9dcacbde511e2bff8d9) on the [css3-v2 branch](https://github.com/chriseppstein/compass/commits/css3-v2)

**Comment by erikdahlstrand** [comment]
Nice! Thanks Chris.

**Comment by chriseppstein** [comment]
closing
