### ISSUE TITLE
Move away from JSON gem?

### ISSUE THREAD

**Issue by Snugug** [Compass/compass#1603]
I'm not entirely sure how feasible this is, but on OSX the JSON gem needs to build a native extension, meaning that they need XCode Command Line Tools to build. For many, that's fine. However, as of [XCode 5.1](http://stackoverflow.com/questions/22352838/ruby-gem-install-json-fails-on-mavericks-and-xcode-5-1-unknown-argument-mul), projects using invalid compiler options (like JSON appears to be doing) simply error out. The only options remaining for those currently wishing to install JSON (and therefore Compass) on current OSX setups are either to temporarily use `ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future gem install json` (okay if you're installing to global namespace, not so if installing to different Bundler path), start using some form of ruby version management to upgrade to [Ruby 2.0.0p451](https://www.ruby-forum.com/topic/4454830#1139577), or sit it out and wait for Apple to upgrade system ruby.

The reason I bring this up is this is not the first time that the fact that the JSON gem needs to build native extensions has bitten me when trying to get new developers set up with Compass, it's just the first time when I've had a fully functioning environment where it has and my only recourse was to dip into ruby management to resolve. From a [quick search of the code(https://github.com/chriseppstein/compass/search?q=json&ref=cmdform), and admittedly I'm no Ruby expert, it appears as if the JSON gem is used only for [`search-data.js.erb`](https://github.com/chriseppstein/compass/blob/9ee6b422262668e8a7e154d2ac34f350ee331dc0/doc-src/content/search-data.js.erb#L34). Is it possible to architect the docs in such a way that you don't need to install their dependencies just to run Compass?

**Comment by chriseppstein** [comment]
JSON is needed to read the caniuse data.

We should use the multijson library. It comes with a pure ruby implementation that is slow but will pick up the faster implementations if they are available.

**Comment by mikesherov** [comment]
@chriseppstein looks like you already introduced the multi_json library for the caniuse.com data in 71dd03c36ad9d32273ef2aa2df95b7cc684ce6b8 .

However, now `json` is being used in the compiler to generate sourcemaps in addition to being used by the various docs that @Snugug mentioned.

**Comment by chriseppstein** [comment]
@mikesherov yep! @Snugug Please file a bug against sass for the rest of this.

**Comment by mikesherov** [comment]
@chriseppstein I'm not sure why this issue was closed though. It seems the `json` dependency needs to be removed from the cli gemfile and gemspec, and the compass-style.org json dependency  needs to still be replaced with multi-json.

**Comment by mikesherov** [comment]
BTW, the easy way to fix the JSON error for the time being is: http://stackoverflow.com/questions/22352838/ruby-gem-install-json-fails-on-mavericks-and-xcode-5-1-unknown-argument-mul

**Comment by alexweber** [comment]
Just in case anyone else stumbles upon this, the one-line answer from the Stack Overlow question works like a charm! http://stackoverflow.com/a/22583048/197007
