### ISSUE TITLE
remove obsolete documentation

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#1606]
http://compass-style.org/help/tutorials/exclude_vendor_prefixes/

Also worth searching around in the docs for other things mentioning the old prefix configuration variables.

**Comment by sturobson** [comment]
Hi Chris,

Looking into this, what would be the way forward? Having a quick look leads me to believe that some parts of the documentation need a re-write as apposed to a remove?

Your example above would be better to be re-written explaining it's using Autoprefixer to help?

Thoughts on this. I've got the repo forked and I'm raring to go when I've got moments here and there to help.

**Comment by chriseppstein** [comment]
This documentation was removed. I don't see any references to the old experimental variables now.

**Comment by mdrmike** [comment]
I find that sometimes it would be nice to have historical documentation on the website

The current method of having either a stable or beta documentation reminds me of how Apple would solve the KISS problem:
http://beta.compass-style.org/
http://beta.compass-style.org/ 

It is indeed nice and simple, but as a developer, I sometimes have more complex needs.  I need old reference documentation. As a result the current compass site seems to be lacking something like:

__ http://<version>.compass-style.org  __ 

Where version 0.12.7 would be something like: http://0-12.compass-style.org

## Use Case
- An existing (mature) project deployed based on older stable versions.
- Frameworks / plugins using **bundler**  which lock a project to a specific compass / sass version.  
- Reference for future access ...
