### ISSUE TITLE
Not working with latest Jekyll

### ISSUE THREAD

**Issue by martinbavio** [Compass/compass#1607]
```
Bundler could not find compatible versions for gem "listen":
  In Gemfile:
    compass (>= 1.0.0.alpha.19) ruby depends on
      listen (~> 1.1.0) ruby

    jekyll (~> 1.4.3) ruby depends on
      listen (1.3.1)
```

I read something about removing listen dependency, is that gonna happen soon?

**Comment by chriseppstein** [comment]
This is why we introduced the compass-core gem. But yes, we also are going to use Sass's version of listen which doesn't have an explicit gem dependency on listen.

**Comment by martinbavio** [comment]
@chriseppstein So I should use compass-core gem only for this use case?

**Comment by jasonhodges** [comment]
Glad to see this is in the works! Would really love to try the latest versions of Jekyll, Susy, Compass and Sass together.

**Comment by martinbavio** [comment]
I could make all those to work together (alongside new Octopress CLIs). The
only thing I had to manually add is to comment out Compass dependency from
listen.

---

MB

**Comment by huijing** [comment]
@mbavio could you please advise on how to comment out the compass dependency from listen? Right now the only way I can get everything (Jekyll, Compass and SASS) to play nicely together is to use old versions of sass and compass.

**Comment by pprince** [comment]
As I understand it, there is a fix planned for this.  @chriseppstein is or
was waiting on SASS to bundle listen.

In the mean time I am maintaining a minimal fork for exactly this reason,
at https://github.com/pprince/compass

It has been working for me.

Thanks,
-Paul P.

**Comment by pprince** [comment]
I should add:  I plan to keep this up to date (within a couple of days,
anyway) of released versions, until this bug is fixed; after that my fork
will disappear.

Thanks,
-Paul P.

**Comment by sdhull** [comment]
@chriseppstein can you give me a hint on how to use `compass-core` in Jekyll?  Currently I'm using a jekyll plugin based on [this gist](https://gist.github.com/Grandrath/8282339), which calls

```
Compass::Exec::SubCommandUI.new(%w(compile)).run!
```

however compass/exec isn't included in compass-core.

**Comment by sdhull** [comment]
Does _anyone_ here know how to use compass-core in Jekyll?  I was looking at [the projects test](https://github.com/chriseppstein/compass/blob/master/core/test/integrations/projects_test.rb#L97) and it's a bit... unwieldy. Why bother with `config.rb` if I just manually feed all the config options to the sass parser?

**Comment by macie** [comment]
@sdhull 
I had problems with Jekyll with Compass and [Susy](http://susy.oddbird.net/). [Bundler](http://bundler.io/) solved them (see [my gists with configuration & instructions](https://gist.github.com/macie/39cd87034c73ca7a969f)).

**Comment by sdhull** [comment]
@macie thanks for the reply! However I couldn't use `jekyll` 2.0 with compass 1.0 alpha, as you get the following bundler error:

```
Bundler could not find compatible versions for gem "listen":
  In Gemfile:
    jekyll (~> 2.0.0) ruby depends on
      listen (~> 2.5) ruby

    compass (~> 1.0.0.alpha) ruby depends on
      listen (1.1.0)
```

Could you check your Gemfile.lock to see what version of things actually ended up being installed?

I'm trying to get Jekyll 2.0 + Compass + Sass 3.3

**Comment by macie** [comment]
@sdhull 
This is part of my `Gemfile.lock`:

```
compass (1.0.0.alpha.19)
jekyll (1.2.1)
sass (3.3.8)
susy (2.1.2)
```

I used default gem for jekyll - shouldn't I have version 2? Interesting...

**Comment by sdhull** [comment]
The tests I link to from above have this `compile_project` method (included below).

Apparently the way to do it is `Sass::Plugin::Compiler.new(options).update_stylesheets`. And I guess that just having `compass-core` loaded maybe puts the necessary compass files (eg for `@import "compass/css3/box-shadow"`) on the sass load path.

The method from the tests:

``` ruby
  def compile_project(project_name, options = {})
    @last_compile = Time.now
    @diff_start = Time.now
    @current_project = project_name
    options = {
      :always_update => true,
      :load_paths => []
    }.merge(options)
    options.update(
      :css_location => tempfile_path(project_name),
      :template_location => template_path(project_name)
    )
    options[:load_paths] = (load_paths + options[:load_paths] + sass_path_env).uniq
    compiler = Sass::Plugin::Compiler.new(options)
    yield compiler
    compiler.update_stylesheets
  rescue
    save_output(project_name)
    raise
  ensure
    @current_project = nil
  end
```

However, `jekyll-sass-converter` uses a different method to convert sass: https://github.com/jekyll/jekyll-sass-converter/blob/master/lib/jekyll/converters/scss.rb#L59

``` ruby
  def convert(content)
    ::Sass.compile(content, sass_configs(content))
  end
```

This doesn't seem to work for me, or at any rate, it can't find the foundation sources I've included via my copy of the foundation gem (with updated version of foundation: https://rubygems.org/gems/zurb-foundation-5).

**Comment by chriseppstein** [comment]
We don't depend on listen explicitly anymore.
