### ISSUE TITLE
Feature Request: Change handling for sprites

### ISSUE THREAD

**Issue by Huaba** [Compass/compass#1608]
Hi,
if you work with git or any other VCS it is hard to add the generated spritemaps manually. Also your repository contains the old spritemaps. If you deploy your projects with VCS it's a source of error...

Perhaps the handling of this files could rethinked. In my opinion it would be usefull if the hash wouldn't added to the spritemap. To avoid browser caching issues, it would be useful to ad the hash (or timestamp) to the generated css file.

For example: directory for sprites called "icons", the generated spritemap called "icons.png" and the image-url in the css could be "icons.png?1395069810"

At the moment we realize this with the additional configuration in config.rb:

```
# Rename the generated sprite images
# delete the hash at the end of the filename
on_sprite_saved do |filename|
 if File.exists?(filename)
    FileUtils.mv filename, filename.gsub(%r{-s[a-z0-9]{10}\.png$}, '.png')
  end
end

# Replace in stylesheets generated references to sprites
# by their counterparts without the hash uniqueness and add an timestamp
# to avoid the browsercaching issue for the sprites in bigger projects.
on_stylesheet_saved do |filename|
  if File.exists?(filename)
    time = Time.now.to_i
    css = File.read filename
    File.open(filename, 'w+') do |f|
      f << css.gsub(%r{-s[a-z0-9]{10}\.png}, '.png?' + time.to_s)
    end
  end
end
```

The disadvantage of this solution is the bad performance! It takes a long time to "rebuild" the files and the generated css files...

I don't know how complex it is, it's only a suggestion from me :)

Thanks for your time and the great tool you create, we all love it!

Greets
Huaba

**Comment by scottdavis** [comment]
As a best practice you shouldn't check in compiled files.

**Comment by Huaba** [comment]
Sure, but this was the only known way to solve the problems with vcs deployment for us. Any better suggestion?

**Comment by scottdavis** [comment]
Not really. Your situation is kind of an edge case for most of our users.
