### ISSUE TITLE
Consistent Variable names

### ISSUE THREAD

**Issue by direction** [Compass/compass#161]
Hi,

I know this would be a really big breaking change but is it possible to have consistency for the naming of the variable names; I just noticed a discrepancy between the use of the underscore and the dash in the names of variables for e.g.: 

$blueprint_grid_columns is underscored but $blueprint-font-size is dashed. All the mixin names however are dashed. Is there a standard that you are following?

Thanks,
Disha

**Comment by chriseppstein** [comment]
I have a patch for this on master but underscores and dashes are interchangeable. You can use whichever you prefer and they'll refer to the same variable.

**Comment by chriseppstein** [comment]
All dashes all the time on master now.
