### ISSUE TITLE
only the first file updated when using import-once and compiling multiple files

### ISSUE THREAD

**Issue by anchann** [Compass/compass#1612]
Hello!

I have three files in a directory, one.scss, two.scss, and _common.scss. Each of the first two files imports _common.scss, and accesses a variable defined there.

When import-once is disabled, updating the variable value expectedly results in changes to both one.css and two.css. When import-once is enabled, updating the variable in _common.scss results in "overwrite" for one.css, and "unchanged" for two.css.

It seems that if "once" in "import-once" means "once per compilation unit", in the current implementation the full sass run is treated as a compilation unit, whereas it may make more sense to treat each .css-file-producing .scss file (i.e. presumably every .scss file that doesn't start with an underscore) as a compilation unit.

I noticed that the test harness for import-once goes through scss files one by one, compiling each and comparing them to expected output. Perhaps a test that compiles multiple scss files in a single run, similarly to how cli sass does, will expose this problem?

Thank you for your time!

-a

**Comment by chriseppstein** [comment]
Please retest this against 1.0, I think I fixed it.
