### ISSUE TITLE
Permission denied since update compass 0.12.4

### ISSUE THREAD

**Issue by isyara** [Compass/compass#1615]
Hi,

On compass 0.12.3   Works perfect but since update  compass to version 0.12.4 impossible to compile :

Errno::EACCES on line ["891"] of c: Permission denied  ...pathcompiledstyle.css

I have change permission to 777  but fail again . (if i'm rollback to 0.12.3  it's Works)

PS : i'm under windows 7 x64

**Comment by nicholashead** [comment]
I too am having the same issue. Windows 8.1, x64.

**Comment by nicholashead** [comment]
It looks like it's trying to write a weird filename-- I don't think it has to do with permissions.

**Comment by Adam14Four** [comment]
I'm experiencing the same thing, also on Windows 8.1 x64.

**Comment by chriseppstein** [comment]
Actually, this was a bug in a utility function in Sass that I just started using to write out our css files (to fix concurrency issues). I have fixed the underlying issue in Sass and will release both libraries asap.

https://github.com/nex3/sass/commit/5007bdf2b1cf9d43e5ed69690efb339660a3564c

**Comment by mattpolicastro** [comment]
Hi guys—I'm relatively new to Sass/Compass and ran into this bug after updating yesterday. Has the fix been released yet, and would anyone care to walk me through it?

**Comment by lolmaus** [comment]
Wait for version 0.12.5 or install from git.

**Comment by chriseppstein** [comment]
No new compass release is needed. I've just released sass 3.2.18. Please update sass to fix this issue.

**Comment by chriseppstein** [comment]
```
$ gem install sass --version "~> 3.2.18"
```

**Comment by iholler** [comment]
I'm a total noob to Ruby, Sass, and Compass. So, my problems may be due to my ignorance.
However, I'm having the same issues regarding Compass/Sass even after installing the new version of sass ver 3.2.18.

Actually I uninstalled both Sass and Compass entirely and started fresh. As you can see in the code block below I installed fresh, and immediately tried to create a new project named "bestof" in my local project folder "C:\wamp\www\best_www" and I still receive the same error.

```
        C:\wamp\www\best_www>gem install compass
        Fetching: sass-3.2.18.gem (100%)
        Successfully installed sass-3.2.18
        Fetching: compass-0.12.4.gem (100%)
        Successfully installed compass-0.12.4
        Installing ri documentation for compass-0.12.4
        Installing ri documentation for sass-3.2.18
        2 gems installed

        C:\wamp\www\best_www>compass create bestof --trace
           create bestof/config.rb
        Errno::EACCES on line ["897"] of C: Permission denied - (C:/wamp/www/best_www/bestof/config.rb201403
        22-110584-wsqlb4, C:/wamp/www/best_www/bestof/config.rb)
          C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.18/lib/sass/util.rb:897:in `atomic_create_and_write_f
        ile'
          C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.12.4/lib/compass/actions.rb:58:in `write_file'
          C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.12.4/lib/compass/app_integration/stand_alone/install
        er.rb:20:in `write_configuration_files'
          C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.12.4/lib/compass/app_integration/stand_alone/install
        er.rb:35:in `prepare'
          C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.12.4/lib/compass/installers/base.rb:32:in `run'
          C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.12.4/lib/compass/commands/stamp_pattern.rb:75:in `pe
        rform'
          C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.12.4/lib/compass/commands/base.rb:18:in `execute'
          C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.12.4/lib/compass/commands/project_base.rb:19:in `exe
        cute'
          C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.12.4/lib/compass/exec/sub_command_ui.rb:43:in `perfo
        rm!'
          C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.12.4/lib/compass/exec/sub_command_ui.rb:15:in `run!'

          C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.12.4/bin/compass:30:in `block in <top (required)>'
          C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.12.4/bin/compass:44:in `call'
          C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.12.4/bin/compass:44:in `<top (required)>'
          C:/Ruby193/bin/compass:23:in `load'
          C:/Ruby193/bin/compass:23:in `<main>'

        C:\wamp\www\best_www>
```

@chriseppstein

**Comment by mattcollier** [comment]
Hello, having the same issue here.  This problem coincided with day 1 of my sass/compass experience.  There has been much gnashing of teeth!

Anyhow, I'm a bit confused.  Isn't the current version of sass 3.3.4?  Why are we talking about 3.2.18?

**Comment by nicholashead** [comment]
I don't know if this is a problem with sass or compass-- but I was able to install previous version of compass and everything works fine again. So, there's that.

**Comment by iholler** [comment]
@mattcollier - I uninstalled compass and sass again and reinstalled **Compass ver. 0.12.3** which automatically installed **Sass ver. 3.2.18** everything now works. Guess there's still some bugs to iron out with the newest version of either Compass or Sass (which I don't have the knowledge of which is the culprit).

**Comment by pabliqe** [comment]
+1 for downgrade

Thanks guys, Ive been looking a workaround since yesteday

**Comment by nicholashead** [comment]
I think this needs to be reopened?

**Comment by Josh68** [comment]
I'm still having issues, as 0.12.3 (or the sass downgrade) is causing other errors in my site build. Is there another solution that doesn't require any downgrades? Thanks

**Comment by wheatpenny** [comment]
Upgrading SASS from 3.2.17 to 3.2.18 fixed the issue for me. Thank you!
