### ISSUE TITLE
403 error on compiled CSS since 0.12.4 update

### ISSUE THREAD

**Issue by weshardee** [Compass/compass#1616]
Since the update, my css files have been compiling without permission for the web user, resulting in 403 errors on my localhost. I can of course change those permissions by hand, but it's annoying to do so. 0.12.3 works fine, so I'm rolling back to that for the moment.  I'm on OSX version 10.9.2 using ruby v2.1.1p76.

**Comment by tjoneseng** [comment]
Ditto.

**Comment by MisterEdel** [comment]
I have the same issue and had to downgrade to 0.12.3

**Comment by jdhartley** [comment]
I think this issue is the same as #1615 

@chriseppstein says it is fixed (https://github.com/chriseppstein/compass/issues/1615#issuecomment-38332287)

**Comment by chriseppstein** [comment]
Closing as duplicate.
