### ISSUE TITLE
Cannot access css files generated by Compass (403 Forbidden)

### ISSUE THREAD

**Issue by rizkysyazuli** [Compass/compass#1619]
Not sure what happened. Suddenly my css files cannot be accessed and sends a 403 forbidden response (the file permission is 600).

I'm on a Mac 10.9 running ruby 2.1.0 (using RVM). Working with Compass 0.12.4 via grunt-contrib-compass (the gem version also gives a 403).

FYI, the project is based on Foundation 5. Originally using grunt-sass, but i replace it with grunt-contrib-compass, and that's when it happens.

Any ideas?

**Comment by lolmaus** [comment]
https://github.com/chriseppstein/compass/issues/1615#issuecomment-38332287

**Comment by chriseppstein** [comment]
Dupe and fixed by sass 3.2.18.

**Comment by rizkysyazuli** [comment]
updated to sass 3.3.4 and still not working. but since i'm using grunt-contrib-compass, is this related directly to compass or sass?
