### ISSUE TITLE
support for css keyframes

### ISSUE THREAD

**Issue by chrisdrackett** [Compass/compass#162]
would be nice :)

**Comment by chriseppstein** [comment]
patches accepted.

**Comment by chrisdrackett** [comment]
I would if I understood even a little about how to write such a thing.

**Comment by chriseppstein** [comment]
Don't underestimate yourself. Tho I should put together a contribution guide so that folks know how to work on compass itself. even if you just have a gist of the sass code -- that's a fine start. then we just need tests and docs and peer-review.

**Comment by mirisuzanne** [comment]
Looking into this, but I'm not sure what it would look like. Off-hand I see ways that we could mimic the syntax, but not a clear way to improve on it or provide shortcuts. What sort of support were you hoping for?

Without needing to know or care how we would do it on the back end, what would you like to see supported about it? What syntax would you like to put in, and what results would you like to get back?

**Comment by chriseppstein** [comment]
as it stands, it seems that only webkit supports this, and without a clear higher level abstraction, I don't see anything to be done at this time. Let's revisit this issue when other browsers have support or if someone proposes a simplification for the common use cases.

**Comment by alanhogan** [comment]
Firefox 5+ supports this style of animation.

https://developer.mozilla.org/en/CSS/CSS_animations
