### ISSUE TITLE
updated compass and sass gem. Now I get compile errors

### ISSUE THREAD

**Issue by legiondesigns** [Compass/compass#1620]
I updated my compass and sass...that was all. Now when compass tries to compile the sass and overwrite the styles.css I get: 
Errno::EACCES on line ["897"] of C: Permission denied - (c:/xampp/.....)

Running windows 8
Ruby version 2.0.0p247
Compass version 0.12.4 (Alnilam)
Sass version 3.2.18 (Media Mark)

**\* LOCAL GEMS ***

bigdecimal (1.2.0)
bootstrap (0.0.1)
bower (0.0.2)
chunky_png (1.2.9, 1.2.8)
compass (0.12.4)
foundation (1.0.4, 1.0.2)
fssm (0.2.10)
git (1.2.6, 1.2.5)
io-console (0.4.2)
json (1.7.7)
minitest (5.0.8, 4.3.2)
psych (2.0.0)
rake (10.1.0, 0.9.6)
rdoc (4.0.1, 4.0.0)
sass (3.2.18)
test-unit (2.5.5, 2.0.0.0)
thor (0.18.1)
zurb-foundation (4.3.2, 4.3.1)

Compass watch with trace:

Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.18/lib/sass/util.rb:897:in `atomic_create_and_write_file'
Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.4/lib/compass/actions.rb:58:in`write_file'
Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.4/lib/compass/compiler.rb:143:in `compile'
Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.4/lib/compass/compiler.rb:118:in`compile_if_required'
Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.4/lib/compass/compiler.rb:103:in `block (2 levels) in run'
Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.4/lib/compass/compiler.rb:101:in`each'
Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.4/lib/compass/compiler.rb:101:in `block in run'
Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.4/lib/compass/compiler.rb:126:in`timed'
Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass 0.12.4/lib/compass/compiler.rb:100:in `run'
Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.4/lib/compass/commands/watch_project.rb:147:in`recompile'
Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.4/lib/compass/commands/watch_project.rb:68:in `perform'
/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.4/lib/compass/commands/base.rb:18:in`execute'
Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.4/lib/compass/commands/project_base.rb:19:in `execute'
Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.4/lib/compass/exec/sub_command_ui.rb:43:in`perform!'
Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.4/lib/compass/exec/sub_command_ui.rb:15:in `run!'
Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.4/bin/compass:30:in`block in <top (required)>'
Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.4/bin/compass:44:in `call'
Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.4/bin/compass:44:in`<top (required)>'
Ruby200-x64/bin/compass:23:in `load'
Ruby200-x64/bin/compass:23:in`<main>'

I have tried removing compass and sass and re-installing them. That didn't work either. I have a drupal project due tomorrow and I have to provide that sass and matching css file. 

All this happens just from one simple 5 second update. Why? Did I do something wrong?

Please help,
Agon024

**Comment by lolmaus** [comment]
Duplicate for https://github.com/chriseppstein/compass/issues/1618

**Comment by legiondesigns** [comment]
My bad. I looked around in here but must have missed that. Thanks for pointing me to that issue posting. I did what most of them did and reverted back to 0.12.3 and it is working again.
