### ISSUE TITLE
Location of temporary sprite files

### ISSUE THREAD

**Issue by mingan** [Compass/compass#1625]
Change introduced in db3c621 made Compass stop working in a shared folder between Win host and Ubuntu guest. When sprites are compiled the renaming from generated tempfile to proper name fails.

I had similar issue with running SASS in this setup, but there's the cache_location option which solves it. Is there some way to instruct Compass to save temporary files to a different folder?

**Comment by chriseppstein** [comment]
No way to do that. we need to make this work on windows instead of break.

**Comment by chriseppstein** [comment]
It's a rename in the same directory. I don't see why this should be breaking. Can you retest with 1.0?

**Comment by mingan** [comment]
I tested it with 1.0.1 and it worked ok, but when I went back to 0.12.4 the problem didn't manifest either.
