### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by plynchnlm** [Compass/compass#1626]
On Page: http://compass-style.org/help/tutorials/spriting/customization-options/

I was looking for:
the page

But instead I found:
Site Temporarily Unavailable

We apologize for the inconvenience. Please contact the webmaster/ tech support immediately to have them rectify this.
error id: "bad_httpd_conf"

**Comment by chriseppstein** [comment]
https://twitter.com/compass/status/449281085097009152
