### ISSUE TITLE
http://compass-style.org down: "Site Temporarily Unavailable"

### ISSUE THREAD

**Issue by awholegunch** [Compass/compass#1627]
Site Temporarily Unavailable

We apologize for the inconvenience. Please contact the webmaster/ tech support immediately to have them rectify this.
error id: "bad_httpd_conf"

**Comment by lolmaus** [comment]
![Y U NO search](http://i.memeful.com/memes/RXEDVLd/YUNO.jpg)
https://github.com/chriseppstein/compass/issues/1626
https://twitter.com/compass/status/449281085097009152
