### ISSUE TITLE
Use `$legacy-support-for-ie6` in float mixin

### ISSUE THREAD

**Issue by ctumolosus** [Compass/compass#1629]
You're using `display: inline` on the float mixin to fix an IE5/6 issue. Most of your mixins that take care of IE quirks wrap the logic using these `$legacy-support-for-iex` variables, which is a very nice feature if you are trying to suppress the amount of CSS that you use when certain browsers are no longer supported by your business.

**Comment by Anahkiasen** [comment]
This is fixed on master no ?

**Comment by ctumolosus** [comment]
It doesn't seem to be unless I'm looking in the wrong place [utilities/general/float](https://github.com/chriseppstein/compass/blob/stable/frameworks/compass/stylesheets/compass/utilities/general/_float.scss)

**Comment by Anahkiasen** [comment]
No that's stable, I mean in the [master](https://github.com/chriseppstein/compass/tree/master) branch

**Comment by ctumolosus** [comment]
Your are correct. Closing.
