### ISSUE TITLE
import it explicitly +  Unable to load CarbonCore. FSEvents will be unavailable.

### ISSUE THREAD

**Issue by lessallan** [Compass/compass#163]
This might be two issues or maybe none, I'm a newbie at sass and compass  ----

WARNING: Neither fancy-buttons.sass nor .scss found. Using fancy-buttons.css instead.
This behavior is deprecated and will be removed in a future version.
If you really need fancy-buttons.css, import it explicitly.

Warning: Unable to load CarbonCore. FSEvents will be unavailable.

> > > Compass is polling for changes. Press Ctrl-C to Stop.

Rails 2.3.5
ruby 1.8.6 (2007-09-24 patchlevel 111) [i686-darwin9.5.0]
Ruby Cocoa is installed

**Comment by chriseppstein** [comment]
For the carbon core thing: http://groups.google.com/group/compass-users/msg/97e29e5ab398a205

**Comment by chriseppstein** [comment]
for the fancy buttons thing, you probably need to add:

```
require 'fancy-buttons'
```

to your configuration file.

**Comment by chriseppstein** [comment]
closing -- not much I can do about this on my end.
