### ISSUE TITLE
placeholder mixin extension for firefox

### ISSUE THREAD

**Issue by lhtdesignde** [Compass/compass#1635]
Is it possible to add "opacity: 1" as a reset for the Mozilla declaration? Firefox gives default opacity value of 0.54 to the placeholder which makes it look different from the placeholder styling in other browsers. So at the moment I can either give all an opacity of 1 or live with the difference which is in the some cases a no-go.

On Page: http://beta.compass-style.org/reference/compass/css3/user_interface/

**Comment by cimmanon** [comment]
This seems like something that would be out of scope for that particular mixin, since it is not part of the reset module.

**Comment by chriseppstein** [comment]
`opacity: 1` seems like a shitty default to force here. I like mozilla's value. In theory, we could add something to our reset... but it's really hard to do in a backwards compatible way.
