### ISSUE TITLE
1.0.0.alpha.19 cannot import images folder

### ISSUE THREAD

**Issue by eradrix** [Compass/compass#1636]
Hi,

It seems that compass fail to import an images folder, as soon as there is a versioned image name (foo.1.1.0.png) inside. Curiously the log reports an "Invalid CSS" error, which is not very helpful.

**Comment by ghost** [comment]
I came across the same issue.

UPDATE:

It seems like non alfanumeric characters are the issue.

**Comment by chriseppstein** [comment]
we use the filename to be a css class, so you must name each file according to a legal css class name.
