### ISSUE TITLE
Lists don't work in local Compass projects?

### ISSUE THREAD

**Issue by corysimmons** [Compass/compass#1638]
- `compass create --sass-dir "scss" --css-dir "css" --javascripts-dir "js" --images-dir "images"`
- `echo '$map: (key1: value1, key2: value2, key3: value3);' >> scss/screen.scss`
- `compass watch`

```
error scss/screen.scss (Line 7: Invalid CSS after "$map: (key1": expected ")", was ": value1, key2:...")
```

Any ideas? Doesn't seem to throw this error on http://sassmeister.com/gist/10219326

https://github.com/mojotech/jeet/issues/187

**Comment by lolmaus** [comment]
Use Bundler.

**Comment by corysimmons** [comment]
@lolmaus There's no Gemfile? Should I create one with just Compass in it and install Compass on a per-project basis?

**edit** Even doing that doesn't seem to fix the problem.

**Comment by lolmaus** [comment]
What versions of Sass and Compass appear in the Gemfile.lock? Are you running Compass with "bundle exec"?

**Comment by corysimmons** [comment]
```
GEM
  specs:
    chunky_png (1.3.0)
    compass (0.12.4)
      chunky_png (~> 1.2)
      fssm (>= 0.2.7)
      sass (~> 3.2.17)
    fssm (0.2.10)
    sass (3.2.19)

PLATFORMS
  ruby

DEPENDENCIES
  compass
```

I've tried running it with `compass watch` and `bundle exec compass watch`. Same error.

**Comment by lolmaus** [comment]
There's your problem.

You're using Compass 0.12 which pulls Sass 3.2 which doesn't support maps.

Update your Gemfile to require Compass 1:

``` rb
source 'https://rubygems.org'
gem 'compass', '~> 1.0.0.alpha.19'
```

Then run:

```
bundle
bundle exec compass watch
```

**Comment by corysimmons** [comment]
Works, thanks. Out of curiosity, when I `gem uninstall compass sass` and remove all of them, then `gem install compass` (which installs the latest alpha and Sass 3.2) it continues to throw the same errors globally. Any ideas?

**Comment by lolmaus** [comment]
@corysimmons, you did two mistakes:
1. `gem install compass` won't install an alpha. To install an alpha globally, you have to use `gem install compass --pre`.
2. An alpha version of Compass won't pull Sass 3.2. It has Sass locked at `< 3.5, >= 3.3.0`. See [RubyGems](http://rubygems.org/gems/compass/versions/1.0.0.alpha.19).

**Comment by corysimmons** [comment]
@lolmaus I did specifically install Compass @ 1.0.0.alpha.19 and it was the only version of Compass on my machine. If it's targeting Sass @ < 3.5, >= 3.3.0, then that range falls above 3.2, which is where maps were introduced, so shouldn't it still work?

**Comment by lolmaus** [comment]
@corysimmons I can only repeat what i said in my first comment.

**Comment by corysimmons** [comment]
Sorry, just trying to understand why global Compass that relies on Sass 3.3 - 3.5 (which supports maps) wasn't supporting maps. Bundler seems to work so I guess I'm crazy. :[

Thanks for the help.

**Comment by lolmaus** [comment]
If you used `gem install compass` then you installed Compass stable (most probably 0.12.5) which relies on Sass 3.2.
