### ISSUE TITLE
Tutorial for compass with semantic blueprint

### ISSUE THREAD

**Issue by codingisacopingstrategy** [Compass/compass#164]
This seems to be a killer combination!

However I have some trouble getting started, having to grok three conceptual frameworks at the same time (blueprint, compass, sass). The current page in the docs just tells me how to create my scaffolding.

I think a short tutorial that shows how to make a simple design using these three techniques could serve to make the framework more accessible (to me). Or maybe such a tutorial already exists elsewhere, and you can point me to it.

Thanks,

**Comment by tatyree** [comment]
I'll second that.  I'm as lost as I was when I transitioned from Test::Unit to Rspec (and that's pretty lost).

**Comment by chriseppstein** [comment]
Hey guys, it's a little old, so I took it off the website with the intention to replace it with many shorter videos. But here's a tutorial: http://vimeo.com/4335944 I know the docs can be better... will try to address this soon.

**Comment by davepeck** [comment]
+1 for this tutorial. I feel a bit dead in the water here, too, though hopeful I can muddle my way through.

**Comment by itkin** [comment]
+1

**Comment by jasherai** [comment]
+1 please!!

**Comment by lgs** [comment]
... split http://vimeo.com/4335944 into a series of many shorter, updated videos, should be great !

bye luca

**Comment by amaia** [comment]
A tutorial on compass with semantic blueprint would be great, I'm also a bit lost on that. 

Just watched the video on vimeo and it's just what I needed to understand better how things work, thanks for that video. 
I think it should be linked from the website, even if it's a bit outdated, maybe with a note like "this video is a bit outdated but still useful" or something like that.

**Comment by adambom** [comment]
I've set up a repo called Boilergrid (https://github.com/adambom/Boilergrid-for-Compass/), which is a nice semantic implementation of blueprint using compass. I've integrated Paul Irish's HTML5 boilerplate for cross-browser, optimized markup.

Using this as a template should help you get up and running with compass and blueprint.

Add all of your styles in scss or css in /css/src/partials/_main.scss

Set the width of blueprint elements like column width, grid width, and gutter width in /css/src/partials/_base.scss

when you want to specify column width for element #myelement, add the following scss to /css/src/partials/_main.scss:

```
#myelement {
    @include column(number-columns) // where number-columns is the integer number of columns to span. Equivalent to class="span-numbercolumns".
}
```

To prepend or append columns to an element use the @include append(number-columns), or @include prepend(number-columns) mixins. That is equivalent to class="prepend-numbercolumns".

To indicate the last column in a row, use the @include last mixin. This is equivalent to class="last". e.g.
    #myelement {
        @include last;
    }

Follow the tutorial outlined in README
https://github.com/adambom/Boilergrid-for-Compass/

Direct link to README
https://github.com/adambom/Boilergrid-for-Compass/blob/master/README
