### ISSUE TITLE
"NoMethodError" With Fresh Install of Compass

### ISSUE THREAD

**Issue by kellylawrence** [Compass/compass#1641]
Hello. Me and my co-workers have been using Compass for some time now, but have recently ran into a strange issue. As of yesterday, we started getting errors about our **config.rb** files not existing or being readable in our project folders, when none of them had been changed, and no changes had been made to our installs of Compass (To our knowledge).

We tried recreating the **config.rb** files in our project folders on our internal networked server, but ran into the same issues. Upon creating **config.rb** files in temp folders on our desktop though, where we were able to run _"compass watch"_ successfully. 

Thinking there might have been an issue with some conflict between Compass and Sass, we've uninstalled the Compass and Sass gem's, and tried installing the latest versions. (Running _gem install compass_) We had some issues at first with not being able to download any gems from Amazon servers, but found a fix to that.

We've been able to successfully install the latest versions of Compass now, without any errors appearing during install. However now, when we try to run _compass watch_ in our project folders, instead of getting errors about our **config.rb** files, we now get the following:

```
library USERNAME$ compass watch --trace
NoMethodError on line ["184"] of /Users/USERNAME/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.19/lib/sass/plugin/staleness_checker.rb: undefined method `to_tree' for nil:NilClass
  /Users/USERNAME/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.19/lib/sass/plugin/staleness_checker.rb:174:in `compute_dependencies'
  /Users/USERNAME/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.19/lib/sass/plugin/staleness_checker.rb:149:in `dependencies'
  /Users/USERNAME/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.19/lib/sass/plugin/staleness_checker.rb:125:in `dependencies_stale?'
  /Users/USERNAME/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.19/lib/sass/plugin/staleness_checker.rb:166:in `block in dependency_updated?'
  /Users/USERNAME/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.19/lib/sass/plugin/staleness_checker.rb:81:in `call'
  /Users/USERNAME/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.19/lib/sass/plugin/staleness_checker.rb:81:in `stylesheet_modified_since?'
  /Users/USERNAME/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.19/lib/sass/plugin/staleness_checker.rb:69:in `stylesheet_needs_update?'
  /Users/USERNAME/.rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.5/lib/compass/compiler.rb:67:in `needs_update?'
  /Users/USERNAME/.rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.5/lib/compass/compiler.rb:61:in `block in out_of_date?'
  /Users/USERNAME/.rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.5/lib/compass/compiler.rb:60:in `each'
  /Users/USERNAME/.rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.5/lib/compass/compiler.rb:60:in `out_of_date?'
  /Users/USERNAME/.rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.5/lib/compass/commands/watch_project.rb:143:in `recompile'
  /Users/USERNAME/.rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.5/lib/compass/commands/watch_project.rb:68:in `perform'
  /Users/USERNAME/.rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.5/lib/compass/commands/base.rb:18:in `execute'
  /Users/USERNAME/.rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.5/lib/compass/commands/project_base.rb:19:in `execute'
  /Users/USERNAME/.rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.5/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /Users/USERNAME/.rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.5/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Users/USERNAME/.rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.5/bin/compass:30:in `block in <top (required)>'
  /Users/USERNAME/.rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.5/bin/compass:44:in `call'
  /Users/USERNAME/.rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.5/bin/compass:44:in `<top (required)>'
  /Users/USERNAME/.rvm/rubies/ruby-2.0.0-p247/bin/compass:23:in `load'
  /Users/USERNAME/.rvm/rubies/ruby-2.0.0-p247/bin/compass:23:in `<main>'
```

The following is our standard **config.rb** file:

```
# Require any additional compass plugins here.

# Set this to the root of your project when deployed:
http_path = "/"
css_dir = "css"
sass_dir = "sass"
images_dir = "images"
javascripts_dir = "js"

# You can select your preferred output style here (can be overridden via the command line):
# output_style = :expanded
output_style = :nested
# output_style = :compact
# output_style = :compressed

# To enable relative paths to assets via compass helper functions. Uncomment:
# relative_assets = true

# To disable debugging comments that display the original location of your selectors. Uncomment:
line_comments = false

# If you prefer the indented syntax, you might want to regenerate this
# project again passing --syntax sass, or you can uncomment this:
# preferred_syntax = :sass
# and then run:
# sass-convert -R --from scss --to sass sass scss && rm -rf sass && mv scss sass
```

According to _gem list_, these are the versions of Compass and Sass that I have installed.

```
compass (0.12.5)
sass (3.2.19)
```

The following is the version of Ruby running on my machine:

```
ruby 2.0.0p247
```

Unfortunately, I'm not very knowledgeable about Ruby, gems, etc., so I've tried my best to figure out what might be going on based on what I've been able to find on Google, but so far haven't had much luck.

If there's any additional info that I should provide, please let me know, and I can do my best to provide it.

**Comment by kellylawrence** [comment]
Just a follow up to this. I've installed a fresh version of Ruby _(2.1.1p76)_ through RVM, then installed Compass through there, and everything seems to be working fine now. I'm not sure what the issue was before with our old combination that just stopped working yesterday, but the latest stable versions of everything seemed to have solved my issue at least. Consider this issue closed I guess!

**Comment by mauricevancooten** [comment]
I updated the SASS Ruby Gem and it worked for me.
