### ISSUE TITLE
compass hangs eternally on project creation

### ISSUE THREAD

**Issue by sunilw** [Compass/compass#1647]
Compass 1.0.0.alpha.19

This command does not return at all.

```
compass create  --bare --sass-dir "sass" --css-dir "css"
```

So does this one

```
compass create .
```

**Comment by mcmillion** [comment]
+1

**Comment by simonwalsh** [comment]
+1

**Comment by swecker** [comment]
I had this issue as well, and found that it was some conflict with compass-rails (at least in my case).  Removing the compass-rails gem solved it for me (so if you actually need the compass-rails gem then I guess this solution means nothing).

**Comment by chriseppstein** [comment]
filed a bug against compas-rails. https://github.com/Compass/compass-rails/issues/176

**Comment by procommerz** [comment]
If you're setting up a bare project it's a good idea to use bundler, e.g.:

$ bundle init
... // edit Gemfile to include sass and compass gems
$ bundle install
$ bundle exec compass create ...

That way you're using an isolated namespace of gems and no conflicts will occur.
