### ISSUE TITLE
Support for http_sass_path

### ISSUE THREAD

**Issue by jvliwanag** [Compass/compass#1648]
When enabling sourcemaps, the public url for the sass directory is automatically predicted based on the sass and css directories.

It would be great however if a public http_sass_path can be configured manually. 

Encountered this limitation while using compass with yeoman.

Mentioned in: #1108

**Comment by chriseppstein** [comment]
There's no such thing as `http_sass_path` because sass files are not served via http. There is only `http_stylesheets_path`
