### ISSUE TITLE
0.12.2 font-face() mixin docs not correct

### ISSUE THREAD

**Issue by jawinn** [Compass/compass#1656]
On Page: http://compass-style.org/reference/compass/css3/font_face/

The page lists the Version as 0.12.2 in the upper left, but the code displayed for the font-face() mixin doesn't match up. See `format('eot')` vs newer `format('embedded-opentype')`. I was using the reference, and when I checked my compiled CSS I was surprised to see the older "eot" being used (compiling with compass.app). ~~I'm not sure if these docs are just for the latest edge version and the page listing 0.12.2 is wrong and confusing?, or what. Perhaps that needs to be made clear, if so.~~ I downloaded the 0.12.2 release zip just to check, and it does have the older `format('eot')`.

**Comment by chriseppstein** [comment]
1.0 has support for embedded-opentype.
