### ISSUE TITLE
Generating sprites on Windows raises Errno::EINVAL (again)

### ISSUE THREAD

**Issue by bodrovis** [Compass/compass#1657]
Hello.

Firstly I faced this problem a couple of months ago when trying to upgrade one of my apps from Rails 3 to 4. I used compass there to hook up some CSS3 helpers and generate sprites. I followed the migrations guidlines, but kept getting this error:

```
Errno::EINVAL at /

Invalid argument - /nested_comments/tmp/cache/assets/development/sass/2c1508b5ee6d70f069ec044e642bbb29c0b97efe/*.pngc (in p:/rails/my/sitepoint/nested_comments/app/assets/stylesheets/application.css.scss)
```

when trying to visit the main page of the app. At that time I actually did not have a lot of time to work on this so I just gave up after some Googling (yes I saw https://github.com/chriseppstein/compass/issues/695 https://github.com/nex3/sass/issues/259 https://github.com/nex3/sass/issues/522)

Today I returned to the same app again and began migration from the very start. Guess what - I stumbled upon the very same error. I spent loads of time trying to fix it but absolutely no luck. I've tried clearing the `tmp` dir, expiring assets, changing the versions of the gems (`compass`, `compass-rails` and `sass-rails`) but really nothing helps.

I thought that this has something to do with my app and opened another very simple app that was created initially using Rails 4, no migration took place and compass was not used as well. You can clone it here: https://github.com/bodrovis/SitePointNestedComments/tree/compass_issue

I did the following:
- Added `gem 'compass-rails'` to the Gemfile
- Created an `auth` directory with a `facebook.png` image there
- Added this to the `application.css.scss`

```
@import 'auth/*.png';

.test {
  width: 32px;
  height: 32px;
  @include auth-sprite(lol);
}
```
- Added this to the `comments/index.html.erb` (the root of the app):

```
<div class="test"></div>
```
- Run `rails s`

Absolutely the same error showed up.

I really have no more ideas what can be done here. Any help will be very much appreciated.

**Comment by bencooling** [comment]
I'm having the same issue.

**Comment by dreamersp** [comment]
Same here, running on windows by the way.
Any workaround until it get fixed?

**Comment by bodrovis** [comment]
@dreamersp I have not found any...

**Comment by dreamersp** [comment]
@bodrovis Just for the record, for which version of Ruby and which of Rails are you experiencing the problem in?

**Comment by bodrovis** [comment]
@dreamersp Ruby 2 and Rails 4.0.4 - https://github.com/bodrovis/SitePointNestedComments/blob/compass_issue/Gemfile#L2

**Comment by dreamersp** [comment]
@bodrovis Thanks. So it seems not related with Ruby or Rails version. It happens the same with Ruby 1.9.3 and Rails 4.1

**Comment by dreamersp** [comment]
@bodrovis I've found a workaround, using the low level `sprite-map()` mixin instead of the `@include`.
This sample shall work:

``` scss
$icons: sprite-map("icons/*.png");

.icon-facebook{
  width: image-width(sprite-file($icons, facebook));
  height: image-height(sprite-file($icons, facebook));
  background: sprite($icons, facebook);
}
```

**Comment by dreamersp** [comment]
This is definitely a problem in compass-rails in Windows, as I can't reproduce the problem using compass in command line.

**Comment by bodrovis** [comment]
@dreamersp Okay, cool - will give it a try. I hope compass-rails's authors will take a look at that. Thank you a lot!

**Comment by chriseppstein** [comment]
moved this issue to compass-rails.
