### ISSUE TITLE
Compass Android 2.3 Support

### ISSUE THREAD

**Issue by jribeiro** [Compass/compass#1658]
Hi,

I'm using Compass 1.0.19 beta with the following browser support definition:

```
$support-for-original-webkit-gradients : true !default;
$browser-minimum-versions:  (ie:'8', chrome: null, firefox: null, opera: null, safari: null);
```

Problem is I have a linear gradient definition which is not generating the appropriate syntax for Android 2.3:

```
@include background-image(linear-gradient(white, black));
```

I needed Compass to generate something like

```
background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,white), color-stop(100%,black));
```

Any idea?

**Comment by aronwoost** [comment]
Yes, [is it removed](https://github.com/Compass/compass/issues/1257).

**Comment by chriseppstein** [comment]
we added it back for the 1.0 release.
