### ISSUE TITLE
image_url doesn't handle root-relative paths

### ISSUE THREAD

**Issue by torbit** [Compass/compass#166]
image_url helper fails silently if it is passed a root relative path like "/images/filename.png" instead of a filename by itself.  

the output from

image_url("/images/filename.png");

should be the same as the output from

image_url("filename.png");

right now, that is not the case.  although a root-relative path will still be output, it won't have support for cache busting, absolute URLs, etc.

**Comment by danielsreichenbach** [comment]
I have tried with compass 0.10.2, and susy 0.7.0. Works for me, but it fails when using [staticmatic](http://github.com/staticmatic/staticmatic). standalone mode works fine with relative_assets true.

**Comment by ghost** [comment]
I ran into a similar problem with susy-compass-staticmatic. I couldn't get the +show-grid("grid.png") give a valid path in preview or build. I had to paste and rewrite that mixin manually

**Comment by chriseppstein** [comment]
fixed by 06ab3d4b410da9d97ce4b7b3e7850cc7d09c32db
