### ISSUE TITLE
Newer alphas using very old listen gem

### ISSUE THREAD

**Issue by kjbkjb** [Compass/compass#1663]
Noticed that listen gem was added as a dependency, but it is on a version that is well over a year old (1.1). Listen is up to 2.7.3. It is conflicting with my use of guard-rspec. much sad.

**Comment by felixbuenemann** [comment]
I'm running into the same issue. Does it really need such an ancient version?

**Comment by gpakosz** [comment]
Looking at the master branch, no `Gemfile` binds specifically to `listen 1.1.0`.

Yet there's a `Gemfile.lock` in the `compass-style.org` directory that depends on `listen ~> 1.1.0`. Rebuilding the `core` and `cli` gems from source works for me. So it seems @chriseppstein and/or @scottdavis just uploaded a Gem with a very old dependency without noticing.

**Comment by felixbuenemann** [comment]
@gpakosz The Gemfile is irrelevant, look at the compass.gemspec:

``` ruby
gemspec.add_dependency 'listen', '~> 1.1.0'
```

**Comment by chriseppstein** [comment]
https://github.com/chriseppstein/compass/blob/master/cli/compass.gemspec

Will be fixed when we release the next version.

**Comment by felixbuenemann** [comment]
Thanks, Chris!

**Comment by kjbkjb** [comment]
Thanks!
