### ISSUE TITLE
Compass compile throws Errno::ENOENT on line ["346"] of D: No such file or directory

### ISSUE THREAD

**Issue by pramodsankarl** [Compass/compass#1664]
I am trying to write a batch script to compile scss files using compass. While doing so it succesfully gets to the path detects the unchanged files but while overwriting/creating the css file it throws **ENOENT** error on a temp file which is not present in the location. ANy idea what could the issue be? appreciate your help.

Using compass version 0.12.5

**_Errno::ENOENT on line ["346"] of D: No such file or directory - D:/Applications/aaa/bbb/Application/content/css/application.css20140502-14
24-rvlxnr.lock_**

**Comment by chriseppstein** [comment]
please upgrade to 1.0 and open a new issue with a full stack trace if this continues to happen.

**Comment by rans0000** [comment]
This is not an elegant solution but...
i had a similar issues. My ruby was installed in c: and project folder in e:
copied the project from e: to c: and compiled. the issue was gone!!
