### ISSUE TITLE
sprite_file function pathing bug

### ISSUE THREAD

**Issue by brewster1134** [Compass/compass#1665]
I was having trouble using the sprite-file function with alpha19 and found a couple possible bugs...

Firstly, the function attempts to return a relative path from the generated images folder. It attempt to do this without ensuring that the two paths are both absolute.  If the `generated_images_path` is a relative path, or more likely, the `project_path` is set to the current directory (`.`), Pathname's prefix exception is thrown...

Secondly, why is the sprite file path bound to the generated images path anyways?  This would seemingly create relationship restrictions between the your project source, images sources, and generated images location.

**Comment by chriseppstein** [comment]
Use `generated_images_dir` if it's a relative directory.

**Comment by chriseppstein** [comment]
project_path gets expanded internally to an absolute path.

**Comment by chriseppstein** [comment]
I don't understand the question here:

> Secondly, why is the sprite file path bound to the generated images path anyways? This would seemingly create relationship restrictions between the your project source, images sources, and generated images location.

can you give a better example of the issue?

**Comment by brewster1134** [comment]
so first thing is `generated_images_path` gets used explicitly from `sprite_file`so it doesn't seem that `generated_images_dir` has any effect.

---

regarding my question about pathing... i discovered it seems to only become an issue when compass is run in the context of guard.  i have a test application setup [here](https://github.com/brewster1134/test/tree/compass_1665) on the `compass_1665` branch

in the Gemfile i have compass pointing to your current master.
there is also a commented out line pointing to my forked master.

the diff between the branches is [here](https://github.com/brewster1134/compass/compare/chriseppstein:master...master)

if you run guard with the gem pointing to `chriseppstein/compass`  you get a `TypeError: no implicit conversion of nil into String` coming from `Compass::Core::SassExtensions::Functions::ImageSize` trying to initialize a new `ImageProperties` with a `nil` file

if you switch the gem to point to `brewster1134/compass`, it works fine.  i hope this provides more info than my poorly worded question can provide :smile:

**Comment by scottdavis** [comment]
@brewster1134 can you open a PR so i can review it more sainly?

**Comment by brewster1134** [comment]
can you not see the diff from the compare view?

here is the PR as welll https://github.com/chriseppstein/compass/pull/1696

**Comment by scottdavis** [comment]
Oh i could see the diff just fine the PR just helps me remember that i need to look into it and gives you credit if it is indeed the fix :)
