### ISSUE TITLE
Closing comment blocks

### ISSUE THREAD

**Issue by pabliqe** [Compass/compass#1666]
What is this error about? I can't get it. Thanks in advance

```
/*
#wrapper2
    overflow-x: hidden
    overflow-y: auto
    -webkit-overflow-scrolling: touch
    +b_remove_scrollbars
*/ <== Line 78
```

```
(Line 78: Invalid CSS after "*/": expected identifier, was "")
```

**Comment by lolmaus** [comment]
Sass indented syntax does not have a closing tag for comment blocks. It uses indentation instead:

``` sass

html
  foo: bar

/*
  #wrapper2
    overflow-x: hidden
    overflow-y: auto
    -webkit-overflow-scrolling: touch
    +b_remove_scrollbars

body
  bar: baz
```

Demo: http://sassmeister.com/gist/11540683

It is strongly recommended to use block comments only for legal information which should survive minification. For anything else, use line comments instead. Leverage your notepad/IDE hotkey to comment out blocks of code with line comments.

**Comment by pabliqe** [comment]
I see, thank you so much for the info. I have heard about the "not-closing" comment syntax but I got confused due to the IDE syntax highlighter.

**Comment by lolmaus** [comment]
I forgot to provide a link to the reference for the indented syntax: http://sass-lang.com/documentation/file.INDENTED_SYNTAX.html#comments
