### ISSUE TITLE
URL for depreciated vendor prefixes is broken

### ISSUE THREAD

**Issue by rootwork** [Compass/compass#1669]
In the commit https://github.com/chriseppstein/compass/commit/e5742f64e2b5a1fb18def2002a3a8d8b04cc1ded the warning message was updated to include a link to the documentation. However, that URL is wrong, and it took me a bit of searching around to find the correct one.

The address that is listed is:
http://compass-style.org/help/documentation/tuning-vendor-prefixes/

but it should be:
http://beta.compass-style.org/help/documentation/tuning-vendor-prefixes/

**Comment by chriseppstein** [comment]
we've released so it's right now.

**Comment by rootwork** [comment]
And congratulations!
