### ISSUE TITLE
Undefined mixin 'clearfix'

### ISSUE THREAD

**Issue by mferreira** [Compass/compass#167]
Syntax error: Undefined mixin 'clearfix'.
        on line 26 of /Library/Ruby/Gems/1.8/gems/compass-0.10.2/frameworks/compass/stylesheets/compass/utilities/lists/_horizontal-list.scss, in `clearfix'
        from line 26 of /Library/Ruby/Gems/1.8/gems/compass-0.10.2/frameworks/compass/stylesheets/compass/utilities/lists/_horizontal-list.scss, in`horizontal-list-container'

This happens when adding any of the Compass Horizontal List mixins.

**Comment by chriseppstein** [comment]
fixed by e79232a7ab2de53e56fb1ab6372e4a0093c4f4d0
