### ISSUE TITLE
[1.0.0.alpha.19] browser-out-of-scope() not working

### ISSUE THREAD

**Issue by thany** [Compass/compass#1675]
browser-out-of-scope always returns false, no matter what. Look:

```
$supported-browsers: ("chrome", "firefox", "ie", "safari", "opera");

$browser-minimum-versions: (
    "opera": "15",
    "chrome": "30",
    "firefox": "24",
    "ie": "9",
    "safari": "5"
);

@debug browser-out-of-scope('ie', '8');
```

Guess what this prints out... false.
I'd expect this to print out true, because clearly, IE8 is supposed to be out of scope here.

**Comment by chriseppstein** [comment]
out of scope means that compass is in a specific context for a particular browser and that some other browser could not possibly apply to that context. E.g. in `@-webkit-keyframes { }` then mozilla is out of scope.
