### ISSUE TITLE
uninitialized constant Compass::Exec::Helpers (NameError)

### ISSUE THREAD

**Issue by mrinterweb** [Compass/compass#168]
I am getting the following error running compass 10.2 on ruby 1.9.1p378
    ➜  hub git:(master) compass --help
    /Users/sean/.rvm/gems/ruby-1.9.1-p378/gems/compass-0.10.2/bin/compass:25:in `<top (required)>': uninitialized constant Compass::Exec::Helpers (NameError)
    from /Users/sean/.rvm/gems/ruby-1.9.1-p378/bin/compass:19:in`load'
    from /Users/sean/.rvm/gems/ruby-1.9.1-p378/bin/compass:19:in `<main>'

I have tried removing my the compass gem I had installed for my non-rvm ruby install.  I uninstalled and installed compass 10.2 many times and I keep getting the same error.  Searching the Googles, I have seen other people have encountered this bug as well.  I have tried all recommendation that applied, but nothing has yet worked for me.

Extra debugging stuff:
    ➜  hub git:(master) ruby -v
    ruby 1.9.1p378 (2010-01-10 revision 26273) [i386-darwin10.3.0]
    ➜  hub git:(master) gem list -d compass

```
*** LOCAL GEMS ***

compass (0.10.2)
    Authors: Chris Eppstein, Eric A. Meyer, Brandon Mathis
    Homepage: http://compass-style.org
    Installed at: /Users/sean/.rvm/gems/ruby-1.9.1-p378

    A Real Stylesheet Framework
➜  hub git:(master) which compass
/Users/sean/.rvm/gems/ruby-1.9.1-p378/bin/compass
```

**Comment by chriseppstein** [comment]
that's very strange. it works just fine for me on OSX using RVM and ruby 1.9.1p378. Are you sure you don't have "chriseppstein-compass" or any other gem that defines compass.rb earlier on the load path installed?

**Comment by mrinterweb** [comment]
I just took a look at my path and my rvm 1.9.1 bin is the first in the path:
    ➜  hub git:(master) echo $PATH
    /Users/sean/.rvm/gems/ruby-1.9.1-p378/bin:/Users/sean/.rvm/gems/ruby-1.9.1-p378@global/bin:/Users/sean/.rvm/rubies/ruby-1.9.1-p378/bin:/Users/sean/.rvm/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/sean/bin/:/Users/sean/scripts/:/opt/local/libexec/git-core:/usr/local/mysql/bin:/usr/X11/bin

Do you know of a more specific way to debug which compass.rb it might be trying to use?

**Comment by mrinterweb** [comment]
Chris, I think you're right.  I'm digging through the code right now and I notice that the 0.10.2/lib/compass.rb file is not being loaded.  It must be trying to load another file.  I'm going to try to keep digging through the code to see why it is not loading the correct version of compass.rb.  I was able to force it to load the correct compass.rb by:
    require File.join(File.dirname(**FILE**), '..', 'lib', 'compass')
There are other spots in the code where require is pulling in libs so my approach is not a sustainable solution.  It must be something that is messed up with my ruby gems configuration or something.  I don't really know where to start with that.

**Comment by mrinterweb** [comment]
Chris, I got it.  I think I must have been looking at another ruby gems installed when I did not see 'chriseppstein-compass' installed.  You had mentioned that before, and I thought that gem was not installed.  I was wrong.  I uninstalled 'chriseppstein-compass' and reinstalled 'compass' and everything works great.  Thanks for your help with this.

**Comment by mrinterweb** [comment]
Just a thought for future debugging, people should check their gems installed with the following:
    gem list | grep compass

**Comment by chriseppstein** [comment]
glad you got it figured out.
