### ISSUE TITLE
Compiler Issue with Compound Selectors

### ISSUE THREAD

**Issue by azavisha** [Compass/compass#1680]
Sass Reference (http://sass-lang.com/documentation/file.SASS_REFERENCE.html#parent-selector) has the following example, which compiles without errors with sass compiler, but throws an error when compiled with compass (the error message is Invalid CSS after "&": expected "{", was "-sidebar {" "-sidebar" may only be used at the beginning of a compound selector).

& must appear at the beginning of a compound selector, but it can be followed by a suffix that will be added to the parent selector. For example:
# main {

  color: black;
  &-sidebar { border: 1px solid; }
}

is compiled to:
# main {

  color: black; }
  #main-sidebar {
    border: 1px solid; }

**Comment by cimmanon** [comment]
Check your version of Compass.  The feature you're referencing is new for Sass 3.3, but Compass 0.12 is incompatible with it (it requires Sass 3.2).  You'll need to upgrade to Compass 1.0 via `gem install compass --pre`.
