### ISSUE TITLE
mistake in naming

### ISSUE THREAD

**Issue by auipga** [Compass/compass#1681]
On Page: http://compass-style.org/help/tutorials/spriting/

In block "Basic Usage"
**Note: The use of icon is only for this example, "icon" represents the folder name that contains your sprites.

It must be "my-icons" instead of just "icon".

**Comment by auipga** [comment]
same at block "Selector Control", "Magic Imports"

**Comment by auipga** [comment]
block "Nested Folders"
icon -> orange

**Comment by chriseppstein** [comment]
fixed.
