### ISSUE TITLE
Include all images from sub folders into single sprite map with compass

### ISSUE THREAD

**Issue by theghostbel** [Compass/compass#1686]
We're using compass+scss and have next folder structure inside folder "/images/:
- signup
  - logo.png
  - button.png
- login
  - bullet.png
  - trash.png

Also, we have, for example two per-module scss files (partials): signup.scss and login.scss. 

```
base.scss:
    @import "signup";
    @import "login";

_signup.scss:
    @import "signup/*.png";
    a { @include signup-sprite(logo) }

_login.scss:
    @import "login/*.png";
    div { @include login-sprite(bullet) }
```

As a result, compass creates two sprite images. It's more or less ok. But in real life we have 20 modules and each creates it's own sprite. My goal is to shrink number of http request and have only one sprite map. 

Is it possible to do it in next way:

```
base.scss:
    @import "*/**/*.png"; //whatever command which will stick all images from subfolders into single map object
    @import "signup";
    @import "login";

_signup.scss:
    a { @include signup-sprite(logo) }

_login.scss:
    div { @include login-sprite(bullet) }
```

**Comment by lolmaus** [comment]
https://github.com/chriseppstein/compass/issues/800

**Comment by lolmaus** [comment]
https://github.com/chriseppstein/compass/issues/1286

**Comment by scottdavis** [comment]
Your "next way" is the correct way. The importer supports globing for this reason.
