### ISSUE TITLE
Comass Documentation Reference Page should include index links

### ISSUE THREAD

**Issue by deisner** [Compass/compass#1689]
On Page: http://compass-style.org/reference/compass/

I was looking for:
An index of all variables, mixins, and functions.

But instead I found:
Lots of great information, but not that. The search results page includes links to an index of all variables, mixins, and functions. I think the reference section page should have these links, too. 

As it stands, I find myself searching for 'fdsajklsd' to get to the index links, or typing the URL manually.

**Comment by chriseppstein** [comment]
The search page has links to all of these: http://compass-style.org/search/

**Comment by chriseppstein** [comment]
Fixed by 7767fac5689cdcd6402212967c3ea4e6f800315d
