### ISSUE TITLE
Growl support for "compass watch"

### ISSUE THREAD

**Issue by kientran** [Compass/compass#169]
I would love to see growl support built into "compass watch" using growlnotify. I regularly just leave a small terminal window to the side to at a glance view when it rebuilds my files, but having it as a growl notification would cut down on some of the needed window space.

It'd be especially useful when a build fails.

**Comment by chriseppstein** [comment]
I'd love to see a compass plugin that provides this. I can add some explicit callbacks if it is needed and a user could do some basic setup in their config file...

**Comment by kientran** [comment]
From looking around the code a bit, I think what would help the most is some type of call back from the Logger class where it has the option of sending the Compass::Logger.record -> msg back to a plugin (defined in the configuration) so that I can take that message and send it back to the ruby-growl gem.

With this callback or API function, other's could also write similar notifications type plugins for other platforms or outputs.

**Comment by codyrobbins** [comment]
Is anyone working on this? I’ll try my hand at it if not.

**Comment by chriseppstein** [comment]
@codyrobbins Please proceed :)

**Comment by tdwesten** [comment]
this would by great!

**Comment by sveisvei** [comment]
+1

**Comment by alanhogan** [comment]
The simplest thing to do is work with `growlnotify`, the command-line tool for Growl that ships with Growl but is not included by default.

```
growlnotify -n net.eppsteins.chris.compass -t "Compass: Built" -m "CSS successfully generated"
```

The proper thing is to actually use Growl, but hey.

(I’m not working on this, but would love to see it.)

**Comment by chriseppstein** [comment]
Soon compass will have callbacks that can be used to integrate with growl.

**Comment by scottdavis** [comment]
And a growl plugin! it will be done once i find out a ruby growl library that isn't horrible

**Comment by jeff-foster** [comment]
I may try my hand in it using growlnotify. I haven't even looked into any code yet. Are callbacks even necessary for it to work?

**Comment by scottdavis** [comment]
growlnotify isn't a good option because you have to install it from another package with the new version of growl. they also discourage coding against it

**Comment by alanhogan** [comment]
Callbacks are not necessary but as noted, growlnotify isn't a good option for something you want to distribute. It'd be a good hack for personal use though.

**Comment by scottdavis** [comment]
I wrote a growl library that uses the applescript bindings for ruby to send growl messages so thats what i plan to implement this with

https://github.com/jetviper21/growl_notify

**Comment by chriseppstein** [comment]
can we close this now?

**Comment by scottdavis** [comment]
yes

**Comment by scottdavis** [comment]
https://github.com/jetviper21/compass-growl
