### ISSUE TITLE
0.13.alpha.2 watch broken on Windows8 root drive other then C

### ISSUE THREAD

**Issue by simongcc** [Compass/compass#1693]
I have working for different drives including network drives, but yesterday, my colleague pass me a project folder which put in the root of a drive eg. root/nodejs
and when I mount nodejs in network space, it becomes, say, y:/
# then I watch as usual and find the following error:

ArgumentError on line ["465"] of C: different prefix: "y:/" and "y:."
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.2/lib/compass/watcher/project_watcher.rb:55:in `block in create_sass
_watchers'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.2/lib/compass/watcher/project_watcher.rb:51:in`map'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.2/lib/compass/watcher/project_watcher.rb:51:in `create_sass_watchers
'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.2/lib/compass/watcher/project_watcher.rb:25:in`initialize'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.2/lib/compass/commands/watch_project.rb:64:in `new'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.2/lib/compass/commands/watch_project.rb:64:in`perform'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.2/lib/compass/commands/base.rb:18:in `execute'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.2/lib/compass/commands/project_base.rb:19:in`execute'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.2/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.2/lib/compass/exec/sub_command_ui.rb:15:in`run!'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.2/bin/compass:30:in `block in <top (required)>'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.2/bin/compass:44:in`call'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.2/bin/compass:44:in `<top (required)>'
  C:/Ruby193/bin/compass:23:in`load'
  C:/Ruby193/bin/compass:23:in `<main>'
# My config for reference:

http_path = "/"
css_dir = "css"
sass_dir = "_source"
images_dir = "images"
javascripts_dir = "js"

Remark: # project_path = "y:/" # tried, not work

**Comment by chriseppstein** [comment]
we use the sass watcher now. I think it should work. Please retest with 1.0.
