### ISSUE TITLE
Compass not looping on reverse @for

### ISSUE THREAD

**Issue by arthurgouveia** [Compass/compass#1695]
Compass v0.12.6
Sass 3.3.8

When compiling the .scss file with pure Sass, the for outputs just fine.
If I compile that with Compass, the reverse loop does not work. Switching the <start> and <end> params to the standard increasing way, works.

``` scss
/* Doesn't work */ 
@for $i from 12 through 1 {
    .grid-#{$i} {
        /* ... */
    }
}

/* Works */ 
@for $i from 1 through 12 {
    .grid-#{$i} {
        /* ... */
    }
}

```

As per Sass documentation: "When < start > is greater than < end > the counter will decrement instead of increment"

**Comment by manoelneto** [comment]
I`m having the same issue.

**Comment by cimmanon** [comment]
Compass 0.12 is not compatible with Sass 3.3.  It still depends on Sass 3.2, which is not able to decrement with loops.  If you wish to take advantage of Sass 3.3 features while using Compass, you will need to upgrade to 1.0 via `gem install compass --pre`.

**Comment by arthurgouveia** [comment]
Sorry about that and thanks for the explanation. Much appreciated.
