### ISSUE TITLE
Incorrect output for column-break-* mixins

### ISSUE THREAD

**Issue by KittyGiraudel** [Compass/compass#1697]
I didn't find anything related to this issue so let me open it.

Mixins `column-break-before` and `column-break-after` output something weird: unprefixed rule, then WebKit prefixed rule, then unprefixed rule again.

http://sassmeister.com/gist/e61226fcfb332e709b2f

Did I miss something perhaps?

**Comment by cimmanon** [comment]
Duplicate of https://github.com/chriseppstein/compass/issues/1561

**Comment by KittyGiraudel** [comment]
My bad. Didn't find it with a search. :(
