### ISSUE TITLE
$legacy-support-for-mozilla: true isn't !default

### ISSUE THREAD

**Issue by shaneafsar** [Compass/compass#1699]
I noticed that setting **$legacy-support-for-mozilla** to false on our project was not preventing legacy mozilla code from rendering (see **inline-block** mixin). Looking at the source, I then noticed that the !default flag isn't set, which means that setting the variable before compass is included in your SASS file doesn't work like it does with the **$legacy-support-for-ie** flags.

**Comment by chriseppstein** [comment]
This variable isn't used in `1.0`.
