### ISSUE TITLE
Support for 3D transform

### ISSUE THREAD

**Issue by chrisdrackett** [Compass/compass#170]
see title ;)

**Comment by chriseppstein** [comment]
Maybe you'd like to suggest a syntax?

**Comment by chrisdrackett** [comment]
I'm still learning the stuff myself, so anything I suggest now wouldn't be very well informed. After I get the css working the way I want, I can take a stab.

**Comment by chrisdrackett** [comment]
- translate3d(x, y, z)
- translateZ(z)
- scale3d(sx, sy, sz)
- scaleZ(sz)
- rotate3d(x, y, z, angle),
- perspective(p)

-webkit-transform-origin now accepts three values, allowing you to specify a z offset for the transform origin.

**Comment by mirisuzanne** [comment]
I'm working on this, but have run into a semantic question. How do you phrase the difference between:

perspective: p;

and

transform: perspective(p);

both of which exist. They work the same, but the former is set on a containing element, and the later on the transformed element itself (if I understand right). Perhaps we use something like "content-perspective" and "perspective"?

**Comment by mirisuzanne** [comment]
Never mind. The way mixins work renders the later useless as a distinct mixin. There is no conflict. Sorry.

**Comment by mirisuzanne** [comment]
https://github.com/chriseppstein/compass/commit/4bb8bb6af9054fec08146f921a5844379731f157
