### ISSUE TITLE
alpha19: `image-url` returns the wrong url

### ISSUE THREAD

**Issue by thany** [Compass/compass#1704]
My project structure is as follows, simplified:

```
projectname
\-- dir
    \-- dir
        \-- includes
            |-- css
            |-- image
            |-- sass
            |   \-- default.scss
            \-- config.rb
```

And my config is as follows:

```
css_dir = "css"
sass_dir = "sass"
images_dir = "image"
```

I'm running compass from the directory `includes` where `config.rb` is as well. All is fine. Works great. The function `inline-image` works fine, too. But `image-url` does not.

When I use this code:

```
@debug image-url('blahblah.png');
```

It spews out:

```
... DEBUG: url('/image/blahblah.png')
```

Which is not correct, because the actual website starts at `projectname`. It must return either `../image/blahblah.png` or `/projectname/dir/dir/includes/image/blahblah.png`. The first one is preferable, because that's what compass is probably aware of - where the resulting css will be, and where my images are. The _actual_ project root is presumably not known to compass.

Can this please be fixed in the next update?
And is there a workaround for this problem that anyone knows of, without changing too much in my project structure?

Specs:
Compass 1.0.0.alpha.19 (no extra plugins)
Sass 3.3.8
Ruby 2.0.0p353
Windows 7 x64

**Comment by chriseppstein** [comment]
You need to set `http_path = "<project_name>/"`
