### ISSUE TITLE
[alpha.19] `watch` doesn't pickup changes in directory "vendor"

### ISSUE THREAD

**Issue by thany** [Compass/compass#1707]
When I make a change in an scss file in a directory called `vendor`, for some reason `compass watch` doesn't see any changes and doesn't update my css files.

My project structure is as follows: (simplified)

```
project root
\-- includes
    |-- css
    |-- image
    |-- js
    \-- sass
        |-- inc
        |   \-- (several files here)
        |-- vendor
        |   \-- (several files here)
        \-- default.scss
```

I'm running `compass watch` from the project root, with the config.rb like this:

```
css_dir = "includes/css"
sass_dir = "includes/sass"
images_dir = "includes/image"
javascripts_dir = "includes/js" 
```

Everything runs fine. Except any change in any file in `includes/sass/vendor` doesn't get picked up by the compass watcher. I have to exit it, and re-start the watcher everytime I make a change. Any change in any file in any _other_ directory gets picked up just fine.

The command I'm using to start the watcher is litterally this:

```
compass watch
```

I'm running this:
- Compass 1.0.0.alpha.19
- Sass 3.3.8
- Ruby 2.0.0p353
- Windows 7 x64

**Comment by mozzi** [comment]
I have same bug. 
Changes in /sass/vendor/subfolder1 are not detected by watcher.
Changes in /sass/lib/subfolder2 are detected correctly.
If i rename vendor to any other name changes are tracked correctly.

```
\-- sass
    \-- vendor
        |-- subfolder1
        \-- (files here)
    \-- lib
        |-- subfolder2
        \-- (files here)
    \-- style.scss
```

compass (1.0.0.alpha.20)
sass (3.3.9)
wdm (0.1.0)

ruby 2.0.0p353, Windows 8 x64

**Comment by Arcovion** [comment]
This is due to the outdated `listen` dependency ([original code](https://github.com/guard/listen/blob/v1.3/lib/listen/directory_record.rb#L15), [fixed code](https://github.com/guard/listen/blob/master/lib/listen/silencer.rb#L11-L14))
See #1634

**Comment by thany** [comment]
Okay so the culprit appears to be the DEFAULT_IGNORED_DIRECTORIES constant... Is there a workaround that can be used to override it, until the fix is deployed?

**Comment by Arcovion** [comment]
``` ruby
gem 'listen', '~> 1'
require 'listen'
Listen::DirectoryRecord::DEFAULT_IGNORED_DIRECTORIES.pop
```

Adding this to the end of your `config.rb` should work for now.

**Comment by thany** [comment]
Brilliant, that works. Thanks.
I'll remember to re-test this when the next version comes out.

**Comment by Arcovion** [comment]
Huh, a new compass gem was released just a few days ago (`1.0.0.alpha.20`) where it looks like the `listen` dependency has been removed... can you check whether
`listen ~> 2.7` & `compass ~> 1.0.0.alpha.20` are now compatible?

**Comment by thany** [comment]
Ooh, even better. I'll check it out tomorrow :)

**Comment by thany** [comment]
And it works. Nice work, thanks :)

**Comment by Arcovion** [comment]
I can't take the credit, it was fixed months ago - just wasn't released till now. Will notify the other tickets.

**Comment by aubricus** [comment]
Just for future reference; this wasn't totally obvious to me.

**Listen** has to be installed manually (at least for a non-ruby, standalone project), `gem install listen`. This solved this issue for me.
