### ISSUE TITLE
Alpha 20

### ISSUE THREAD

**Issue by littlbr** [Compass/compass#1709]
On Mac OS X 10.9.3 
After updating my configuration to Compass 1.0.0.alpha.20 Compass is no longer polling for changes. Compilation works when starting a compass watch action, then nothing updates...
Only solution found so far is a downgrade to alpha.19.

I can provide more system info on request.
Thank you

**Comment by tannerjfco** [comment]
I experience this issue as well, but with alpha.19. When I start compass watch, it will detect any changes pending and compile, but after that polling seems to silently fail, as it does not pick up any further changes unless i stop and start compass watch again.

Looks like this is likely related to #1707 and #1634

**Comment by littlbr** [comment]
Coming back to the issue with more details
I'm using a Mac with Mac OS X 10.9.4
Ruby installation is set via rbenv
The Ruby version is 2.0.0-p247
Gems list:
bigdecimal (1.2.5, 1.2.0)
celluloid (0.15.2)
celluloid-io (0.15.0)
chunky_png (1.3.1)
compass (1.0.0.alpha.20)
compass-core (1.0.0.alpha.20)
compass-import-once (1.0.4)
ffi (1.9.3)
fssm (0.2.10)
hitimes (1.2.1)
io-console (0.4.2)
json (1.8.1, 1.7.7)
listen (2.7.9)
minitest (5.3.5, 4.3.2)
multi_json (1.10.1)
nio4r (1.0.0)
psych (2.0.5, 2.0.0)
rainbow (2.0.0)
rake (10.3.2, 0.9.6)
rb-fsevent (0.9.4)
rb-inotify (0.9.5)
rb-kqueue (0.2.3)
rdoc (4.1.1, 4.0.0)
rubygems-update (2.3.0)
sass (3.3.9)
scss-lint (0.25.1)
susy (2.1.2)
test-unit (2.5.5, 2.0.0.0)
timers (3.0.1, 1.1.0)

Note that after installing alpha.20 and launching "gem cleanup" listen 1.1.6 is removed. Reintalling listen version 1.1.6 does not fix the issue.

Removing compass and installing version alpha.19 and listen 1.1.6 fixes the issue.

Let me know if I can provide more info.

**Comment by littlbr** [comment]
Update : upgrading ruby to 2.1.2 and reinstalling compass alpha 20 corrected the problem for me.

**Comment by chriseppstein** [comment]
I'm seeing this too. Making it a blocker.

**Comment by chriseppstein** [comment]
I narrowed it down to a bug in Listen: https://github.com/guard/listen/issues/243

**Comment by chriseppstein** [comment]
I'll look into a workaround tomorrow.

**Comment by chriseppstein** [comment]
Fixed by b999b49eae178da056cfcd94a8d726775a2088b7
