### ISSUE TITLE
Suggestion: Css3 mixins should output css3 css also

### ISSUE THREAD

**Issue by scottdavis** [Compass/compass#171]
example for linear gradients:
useing :

<pre>
@include linear-gradient(color-stops(#550000, #333333), top);
</pre>

should create:

<pre>
#wrapper {
  background-image: linear-gradient(top, #550000 0%, #333333 100%);
  background-image: -webkit-gradient(linear, 0% 0%, 0% 100%, color-stop(0%, #550000), color-stop(100%, #333333));
  background-image: -moz-linear-gradient(top, #550000 0%, #333333 100%);
}
</pre>

limiting it to just the webkit and mozilla ones makes it a real pain to use compass with PIE.htc or ie-css.htc to bring css3 to IE if the mixin's took this in to account it would just work. I'm not saying this to support a IE library for css3 just that it would make compass css3 framework a bit more complete for the future and stop the duck punching.

**Comment by mirisuzanne** [comment]
I agree that the current CSS3 spec format should always be included when available. I'll be looking through all the CSS3 mixins this week to update them.

**Comment by imathis** [comment]
Given the serious difference between the webkit and gecko gradient APIs and the state that they are currently the only browsers which use vendor prefixes to support linear-gradients, it was a fitting solution. Watching and supporting browsers is far easier than third party browser hacks, and up until recently, they didn't have enough stability to warrant inclusion.

That said, I've been impressed with the potential of CSS3PIE and I'm working on a fork that adds support for it in Compass. Right now you'll have to use your duck punching though. The author says it's not ready for primetime and shouldn't be included in release at this point. I want to give it a go for a bit and watch his release cycle to see how well it integrates.

**Comment by chriseppstein** [comment]
Almost all the css3 mixins do output the css standard value. Gradient might be the only exception to the rule. For instance: http://compass-style.org/docs/examples/compass/css3/box/#css

I'd be fine with the gradient mixin emitting whatever is the current spec, once it achieves some semblance of stability. I'm not sure where the process is at for this particular part of the spec.

**Comment by chriseppstein** [comment]
fixed by f0d80d789fe6979698ca9dd617493e0fff9fed01
