### ISSUE TITLE
Rubygems SASS dependecy version

### ISSUE THREAD

**Issue by thiagofesta** [Compass/compass#1710]
I think we should update the SASS version to 3.3.0. Am I correct? https://github.com/Compass/compass/blob/stable/Gemfile#L11

**Comment by Arcovion** [comment]
Use the [alpha versions](http://rubygems.org/gems/compass/versions) for Sass 3.3+

I think the default branch of this repo should be set to `master`; lots of people keep looking at the `stable` branch which is essentially obsolete.

**Comment by thiagofesta** [comment]
Sounds good. Thanks!
