### ISSUE TITLE
Compass not writing charset

### ISSUE THREAD

**Issue by winghouchan** [Compass/compass#1712]
Compass does not write the charset in the output stylesheet.

For example, if I have this written in SCSS:

``` scss
@charset "UTF-8";
```

The output CSS would be:

``` css

```

Nothing! There is no output. :confused:

**Comment by winghouchan** [comment]
I found a **temporary** workaround here: http://stackoverflow.com/questions/22573254/compass-dont-compile-charset-rule

**Comment by Arcovion** [comment]
This is an intentional optimization, Sass only adds the encoding if there are non-ASCII characters like the StackOverflow answer says. The other answer also links to the docs where other encoding stuff is explained; maybe further explanation is needed there.
