### ISSUE TITLE
gem install compass broken

### ISSUE THREAD

**Issue by lvarela-r7** [Compass/compass#1716]
AUS-MAC-1116:test1rp lvarela$ gem install compass
ERROR:  Could not find a valid gem 'compass' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://s3.amazonaws.com/production.s3.rubygems.org/latest_specs.4.8.gz)
AUS-MAC-1116:test1rp lvarela$

**Comment by lvarela-r7** [comment]
I bypassed the certificate... but I think this should be addressed.

**Comment by scottdavis** [comment]
This is un realted to compass and is a problem with rubygems
