### ISSUE TITLE
Rails 3 extensions (frameworks) are not automatically added

### ISSUE THREAD

**Issue by notthatwoz** [Compass/compass#172]
Placing a framework extension in the vendor/plugins/compass_extensions directory will not automatically load the framework in Rails 3 (note: I have not tested this in Rails 2).

As an example, consider the YUI framework. After adding it to the compass_extensions directory running the command "compass frameworks", displays the following output: 
- blueprint 
  - blueprint/basic      - A basic blueprint install that mimics the 
    actual blueprint css. 
  - blueprint/buttons    - Button Plugin 
  - blueprint/link_icons - Icons for common types of links 
  - blueprint/project    - The blueprint framework. 
  - blueprint/semantic   - The blueprint framework for use with 
    semantic markup. 
- compass 
  - compass/ellipsis     - Plugin for cross-browser ellipsis 
    truncated text. 
  - compass/extension    - Generate a compass extension. 
  - compass/project      - The default project layout. 
- yui 
  - yui/project 

However, it is nowhere to be found in Compass::Frameworks::ALL, and as such any calls to @include "yui" result in a load error. 

Adding "Compass.discover_extensions!" just before "Compass.configure_sass_plugin!" in the compass initializer seems to fix this issue.

Reference: http://groups.google.com/group/compass-users/browse_thread/thread/8aaef33e0a7201d3

**Comment by chriseppstein** [comment]
fixed by 5864f2aeabe1dcba61dad256c56c1521f98eed6f
