### ISSUE TITLE
Spriting Tutorial

### ISSUE THREAD

**Issue by jasonkendall** [Compass/compass#1721]
On Page: http://compass-style.org/help/tutorials/spriting/

I think under the Basic Setting part (and the other sections for that matter), the text needs to either read .my-icons or .icon. Right now it's referencing both. Sorry in advance if I'm getting this wrong!

Currently: **Note: The use of icon is only for this example, "icon" represents the folder name that contains your sprites.

@import "compass/utilities/sprites";
@import "my-icons/*.png";
@include all-my-icons-sprites;

**Comment by philgruneich** [comment]
True, also replacing it for my-icons in the copy would also make the reference to the code clearer.

**Comment by chriseppstein** [comment]
This is fixed in 1.0 http://beta.compass-style.org/help/tutorials/spriting/
