### ISSUE TITLE
Compass watch task doesn't stay active in version 1.0.0.alpha.20

### ISSUE THREAD

**Issue by starryeyez024** [Compass/compass#1723]
I upgraded to Compass version 1.0.0.alpha.20 and when I ran the command "bundle exec compass watch" it would only compile the sass upon the first save of the sass file. All subsequent saves had no effect, and terminal was idle. I'd have to keep stopping the process and re-running the command. When I switched back to 1.0.0.alpha.19 and Listen 1.1.0, it worked again. here is my full (working) gem file.

```
source 'https://rubygems.org'

group :development do

  # Sass, Compass and extensions.
  gem 'singularitygs', '~>1.2.0' # Alternative to the Susy grid framework.
  gem 'singularity-extras', '~> 1.0.0.alpha.3'
  gem 'breakpoint'              # Manages CSS media queries.

  gem 'sass'                    # Sass.
  gem 'sass-globbing'           # Import Sass files based on globbing pattern.
  gem 'compass', '1.0.0.alpha.19'                # Framework built on Sass.
  gem 'compass-validator'       # So you can `compass validate`.
  gem 'compass-normalize'       # Compass version of normalize.css.

  gem 'toolkit'                 # Compass utility from the fabulous Snugug.
  gem 'oily_png'                # Faster Compass sprite generation.
  gem 'css_parser'              # Helps `compass stats` output statistics.

  # Guard
  gem 'guard'                   # Guard event handler.
  gem 'guard-bundler'           # Auto install/update bundle when needed.
  gem 'guard-compass'           # Compile on sass/scss change.
  gem 'guard-shell'             # Run shell commands.
  gem 'guard-livereload'        # Browser reload.

  gem 'listen', '~> 1.1.0'     # Listens to file mods & notifies you of changes.
  gem 'yajl-ruby'                  # Faster JSON with LiveReload in the browser.


  # Dependency to prevent polling. Setup for multiple OS environments.
  # Optionally remove the lines not specific to your OS.
  # https://github.com/guard/guard#efficient-filesystem-handling
  gem 'rb-inotify', '~> 0.9', :require => false      # Linux
  gem 'rb-fsevent', :require => false                # Mac OSX
  gem 'rb-fchange', :require => false                # Windows

end
```

**Comment by starryeyez024** [comment]
Turns out it was actually Sass. It had updated to 3.3.10, and when I set it back to 3.3.8 the problem went away.

**Comment by chriseppstein** [comment]
@nex3 ping. I found this bug in listen: https://github.com/guard/listen/issues/243 sounds like it might affect sass too?

**Comment by nex3** [comment]
I can't reproduce this with Sass. Maybe it's OS-dependent? What OSes are people seeing this on?

**Comment by Razunter** [comment]
Windows 8.1 x64, Rubyinstaller (Ruby 1.9.3-p545)

compass (1.0.0.alpha.20)
compass-960-plugin (0.10.4)
compass-core (1.0.0.alpha.20)
compass-import-once (1.0.4)
compass-normalize (1.5)
compass-rgbapng (0.2.1)
compass-sourcemaps (0.12.4.sourcemaps.a4836f1)
compass-validator (3.0.1)
..
listen (2.7.9)
..
sass (3.3.10)
sass-globbing (1.1.1)

**Comment by nex3** [comment]
@Razunter can you try running with Sass from [this branch](/sass/sass/tree/maybe-fix-issue) and see if that fixes the issue?

**Comment by Razunter** [comment]
Same.

```
w:\web\metallss.ru\metalss>compass watch
>>> Compass is watching for changes. Press Ctrl-C to Stop.

w:\web\metallss.ru\metalss>
```

**Comment by nex3** [comment]
I don't follow. What are the directories you're trying to watch? What changes are you making to the files? Is it not picking up on any of the changes at all? @starryeyez024's report sounded like the first change was getting picked up.

**Comment by Razunter** [comment]
@nex3 there weren't any changes. "Watch" works like "compile" right now, only doesn't output 'unchanged'

```
w:\web\metallss.ru\metalss>compass compile
unchanged sass/styles.scss

w:\web\metallss.ru\metalss>compass watch
>>> Compass is watching for changes. Press Ctrl-C to Stop.

w:\web\metallss.ru\metalss>
```

There is [config.rb](http://pastebin.com/6SJ7WHY2) in this directory & "sass" folder.

Output with changes:

```
w:\web\metallss.ru\metalss>compass watch
>>> Compass is watching for changes. Press Ctrl-C to Stop.
overwrite css/styles.css
identical css/styles.css.map
```

Execution stopped there.

P.S. "compass compile" ignores sass_options = {:cache_location => "/tmp/sass"}

**Comment by nex3** [comment]
What happens if you just run "sass --watch" on a few directories containing simple dummy files?

**Comment by Razunter** [comment]
Works OK even on unpached version:

```
d:\temp\1>sass --watch scss
>>> Sass is watching for changes. Press Ctrl-C to stop.
      write scss/styles.css
>>> Change detected to: scss/styles.scss
      write scss/styles.css
```

**Comment by nex3** [comment]
What happens if you watch multiple directories at once?

**Comment by Razunter** [comment]
Still OK with both versions:

```
d:\temp\1>sass --watch scss scss2 scss3
>>> Sass is watching for changes. Press Ctrl-C to stop.
      write scss3/styles.css
["d:/temp/1/scss", {:relative_paths=>false, :force_polling=>true}]
["d:/temp/1/scss2", {:relative_paths=>false, :force_polling=>true}]
["d:/temp/1/scss3", {:relative_paths=>false, :force_polling=>true}]
>>> Change detected to: scss3/styles.scss
      write scss3/styles.css
>>> Change detected to: scss3/styles.scss
      write scss3/styles.css
>>> Change detected to: scss3/styles.scss
>>> Change detected to: scss3/styles.scss
      write scss3/styles.css
Завершить выполнение пакетного файла [Y(да)/N(нет)]? y

d:\temp\1>sass --watch scss scss2 scss3
>>> Sass is watching for changes. Press Ctrl-C to stop.
>>> Change detected to: scss3/styles.scss
      write scss3/styles.css
>>> Change detected to: scss2/styles.scss
      write scss2/styles.css
```

**Comment by nex3** [comment]
Looks like this may not affect Sass, then.

**Comment by starryeyez024** [comment]
I was watching two directories at once. At first both directories would only compile once and then hang, and when I switched the version of compass only one directory would hang. When I rolled back to compass 3.3.8 both directories compiled normally.

**Comment by nex3** [comment]
@starryeyez024 can you reproduce this using only `sass`, without Compass involved?
