### ISSUE TITLE
-webkit-linear-gradient doesn't work...

### ISSUE THREAD

**Issue by totty90** [Compass/compass#1725]
```
                    background: -webkit-linear-gradient(
                        left,
                        #0193CD 30%,
                        #66D4E5 80%,
                        #0193CD 100%
                    ) repeat;
```

This will not output the css at all. Using grunt compass for scss

Also -webkit-gradient doesn't work.

**Comment by chriseppstein** [comment]
I cannot reproduce this. Please provide a complete sass file that exhibits this issue and tell me how you are compiling it and with what versions of software.

**Comment by chriseppstein** [comment]
Closing due to lack of reply.

**Comment by vietnogi** [comment]
Probably due to autoprefixer, may have to change `last 1 version` to 2 or 3
