### ISSUE TITLE
`compass` is not following symbolic links

### ISSUE THREAD

**Issue by sroze** [Compass/compass#1729]
I'm bootstrapping a project on which SASS stylesheets are in different sub-folders and one aggregate them using symbolic links. The problem is that when I want to compile the directory, linked directories aren't found.

My directory structure is so simple:

``` sh
samuel ~ $ ls -al app/public/
total 8
drwxr-xr-x   4 samuel  staff  136 Jul 23 10:55 .
drwxr-xr-x  10 samuel  staff  340 Jul 22 18:39 ..
drwxr-xr-x   3 samuel  staff  102 Jul 22 18:34 main
lrwxr-xr-x   1 samuel  staff   25 Jul 23 10:55 travel -> ../modules/travel/public/
```

This is the result of `compass compile` call on the master directory (`app/public`):

``` sh
samuel ~ $ compass compile --sass-dir app/public  --css-dir .tmp/public -I ./bower_components/
unchanged app/public/main/stylesheets/main.scss
```

As you can see, the subdirectory `travel` is not discovered by compass. By the way, I can compile by setting the `sass-dir` of this sub-directory.

``` sh
samuel ~ $ compass compile --sass-dir app/public/travel/  --css-dir .tmp/public -I ./bower_components/
unchanged app/public/travel/stylesheets/layout.scss
```

I'm running on Mac OS X:

``` sh
samuel ~ $ uname -v
Darwin Kernel Version 13.3.0: Tue Jun  3 21:27:35 PDT 2014; root:xnu-2422.110.17~1/RELEASE_X86_64
```

**Note that the symbolic link points to a directory, not a file**: this is working with files.

If you've any solution, thanks a lot in advance !

**Comment by Arcovion** [comment]
See https://github.com/guard/listen/issues/25

**Comment by chriseppstein** [comment]
Compass now uses the Sass compiler and watcher, can you please confirm this is working as expected in `1.0.0.rc.0`?
