### ISSUE TITLE
Suggestion: Define custom multilevel folder-structure 

### ISSUE THREAD

**Issue by MarioRicalde** [Compass/compass#173]
It would be great if we could define within a extension a custom multilevel folder structure; even without putting files into it.

For example:
    images/
     - general
     - body
    javascript/
     - libraries/

This would allow developers to include development patterns with frameworks.

**Comment by chriseppstein** [comment]
[Extensions] Make it possible for extensions to create empty directories. Closed by 755b9a3a11baffa773284afcb071e7bfab128c28.
