### ISSUE TITLE
Compile option to specify output file name.

### ISSUE THREAD

**Issue by quaertym** [Compass/compass#1730]
I haven't found a way to specify output file name for compass compile. The suggested solutions on the web are using `partials` and `import` however those are workarounds rather than a solution. I think adding this option would be great for plugins like `grunt-compass` and `broccoli compass` as it removes other additional tasks to rename compiled scss output.

**Comment by chriseppstein** [comment]
compass compiles projects, not files. Use the Sass compiler with the `--compass` option for a file-oriented compiler.
