### ISSUE TITLE
Add keyword support to vertical rhythm

### ISSUE THREAD

**Issue by Undistraction** [Compass/compass#1731]
Would be really nice to be able to pass in keywords aliased to numbers of lines:

```
rhythm(single)
rhythm(double)
rhythm(triple)
rhythm(half)
```

Obviously it's easy to create variables: `$double: 2`, but would be nice to be able to use keywords directly. Could be just a matter of a lookup with `map-has-key` to a map of keywords.

**Comment by mirisuzanne** [comment]
At that point you're getting into a style-guide approach, which is a great idea — but I think it should be a separate layer of abstraction. At OddBird, we use our own `size()` function that does exactly that - and calls rhythm in the background. That sounds like a great Compass plugin, but I'm not sure it makes sense in the core.

**Comment by lolmaus** [comment]
`rhythm($single)` anyone?

**Comment by Undistraction** [comment]
@ericam Fair enough. What would be really nice is being able to override the `rhythm` function, add a layer of keyword handling, then hand-off to the original implementation, but of course Sass doesn't support overriding functions (yet).

@lolmaus I already mentioned in my issue that passing variables is a possibility
