### ISSUE TITLE
No recompilation when imported partials are modified

### ISSUE THREAD

**Issue by peta** [Compass/compass#1733]
Probable bug is related to the `compass watch` command. Lets assume the following files in a directory:

```
_settings.scss
_layout.scss
main.scss
```

whereas `main.scss` imports the partials. When a partial changes, the compass command e.g. logs `info file/to/main.scss was modified` but the referencing main.scss won't be recompiled. If I modify (like entering a space somewhere) the main.scss the recompilation happens. 

This bug doesn't occur, when I directly use  the `sass --compass --watch myWatchTarget` command – then everything works as expected. Non-partial scss files are recompiled once referenced partials are modified. 

Gem versions used on OSX 10.8.5 with `ruby 2.0.0p353 (2013-11-22 revision 43784) [universal.x86_64-darwin12.5.0]`:

```
compass-1.0.0.alpha.21
compass-core-1.0.0.alpha.21
compass-import-once-1.0.4
sass-3.4.0.rc.1
```

**Comment by chriseppstein** [comment]
This is fixed in `1.0.0.rc.0`
