### ISSUE TITLE
NoMethodError in sass_compiler.rb

### ISSUE THREAD

**Issue by alexcabrera** [Compass/compass#1736]
Received a `NoMethodError` when running Compass through a Gruntfile using the following configuration:

```
compass:
    development:
        options:
            sassDir         : SOURCE_DIR
            cssDir          : BUILD_DIR
            imagesDir       : SOURCE_DIR
            extensionsDir   : 'node_modules' # For npm-installed extensions
            outputStyle     : 'expanded'
            trace           : true
```

This was working under 1.0.0.alpha.21.

Full Backtrace:

```
Running "compass:development" (compass) task
NoMethodError on line ["31"] of /usr/lib/ruby/gems/1.9.1/gems/compass-1.0.0.rc.0/lib/compass/sass_compiler.rb: undefined method `on_compilation_starting' for #<Sass::Plugin::Compiler:0x000000021cdca0>
  /usr/lib/ruby/gems/1.9.1/gems/compass-1.0.0.rc.0/lib/compass/sass_compiler.rb:30:in `each'
  /usr/lib/ruby/gems/1.9.1/gems/compass-1.0.0.rc.0/lib/compass/sass_compiler.rb:30:in `initialize'
  /usr/lib/ruby/gems/1.9.1/gems/compass-1.0.0.rc.0/lib/compass/commands/update_project.rb:93:in `new'
  /usr/lib/ruby/gems/1.9.1/gems/compass-1.0.0.rc.0/lib/compass/commands/update_project.rb:93:in `new_compiler_instance'
  /usr/lib/ruby/gems/1.9.1/gems/compass-1.0.0.rc.0/lib/compass/commands/update_project.rb:46:in `perform'
  /usr/lib/ruby/gems/1.9.1/gems/compass-1.0.0.rc.0/lib/compass/commands/base.rb:18:in `execute'
  /usr/lib/ruby/gems/1.9.1/gems/compass-1.0.0.rc.0/lib/compass/commands/project_base.rb:19:in `execute'
  /usr/lib/ruby/gems/1.9.1/gems/compass-1.0.0.rc.0/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /usr/lib/ruby/gems/1.9.1/gems/compass-1.0.0.rc.0/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /usr/lib/ruby/gems/1.9.1/gems/compass-1.0.0.rc.0/bin/compass:30:in `block in <top (required)>'
  /usr/lib/ruby/gems/1.9.1/gems/compass-1.0.0.rc.0/bin/compass:44:in `call'
  /usr/lib/ruby/gems/1.9.1/gems/compass-1.0.0.rc.0/bin/compass:44:in `<top (required)>'
  /usr/bin/compass:23:in `load'
  /usr/bin/compass:23:in `<main>'
```

**Comment by chriseppstein** [comment]
Huh, this is because you need the latest Sass release. Gem version dependencies should have enforced this. You need Sass `3.3.13` or greater. Please confirm your sass version.

**Comment by cimmanon** [comment]
This just popped up on SO, same error:  http://stackoverflow.com/questions/25085638/cant-get-compass-to-watch-my-susy-project

The question author lists these gems:

compass (1.0.0.rc.0, 0.12.7)
compass-core (1.0.0.rc.0)
compass-import-once (1.0.4) 
sass (3.4.0.rc.2, 3.2.19)
susy (2.1.3)

**Comment by rkpasia** [comment]
I have the same issue, using grunt-contrib-compass I can't compile because I have NoMethodError on the line 31 in `sass_compiler.rb`.
- **jekyll-sass-converter (1.2.0, 1.0.0)**
- **sass (3.4.0.rc.2, 3.3.13)**
- **compass (1.0.0.rc.0)**
- **compass-core (1.0.0.rc.0)**
- **compass-import-once (1.0.4)**

**Comment by scottdavis** [comment]
gem doesn't or didn't used to fix dependency hell problems using bundler should make this a non-issue. Im betting he has multiple versions of sass installed what do you get if you run `gem list sass`. Its going to try to use which ever sass is on the load path first i think to avoid this we should detect the required sass version and notify the user of this problem.

**Comment by chriseppstein** [comment]
The issue here is that you need sass 3.4.0.rc.3. The APIs added in 3.3.13 are not present in 3.4.0.rc.2.
