### ISSUE TITLE
@extend not supported into @media only screen... 

### ISSUE THREAD

**Issue by dexterns88** [Compass/compass#1738]
@extend not supported into @media only screen... 

@media only screen
and (min-device-width : 320px)
and (max-device-width : 480px) {
    @extend  .something;
}

getting error message  (Line 24 of sass/_bundle.scss: Extend directives may only be used within rules.)

This option will be very useful.

**Comment by chriseppstein** [comment]
This is a sass language issue. Duplicate of https://github.com/sass/sass/issues/1050.
