### ISSUE TITLE
Compass v1 Core is unusable without Config code from CLI

### ISSUE THREAD

**Issue by tdreyno** [Compass/compass#1739]
Hey @chriseppstein, we chatted about this a while back. Checked in to see how the RC was looking and it seems to still be an issue.

Basically, Middleman would like to depend on `compass-core` and not have the CLI portions of Compass conflict with ours. Right now, you have `core` depending on various file watcher gems and CLI contains Sass Configuration which is needed outside the CLI.

The simplest approach, and the one we've used in Middleman, is to keep all Ruby code in the core gem while moving only the gem requirements to the separate gem.

Thanks for listening. We've had to pull Compass out of our core due to these issues (https://github.com/middleman/middleman-compass), which is a bummer.

**Comment by chriseppstein** [comment]
I'm surprised to hear this. Can you please list the specific issues which you ran into? Which gems? Which config? I want to support this use case in 1.0.

**Comment by tdreyno** [comment]
Seems like `Compass.configuration.to_sass_engine_options` isn't available. Did this just get renamed? Looks like some of it is defined in CLI.

Additionally, looks like the Sprite code is in CLI instead of Core.

**Comment by scottdavis** [comment]
spriting is set to be its own gem in 1.1. so for the 1.0 release it will sadly still be in cli

**Comment by scottdavis** [comment]
Also a stack trace would help

**Comment by chriseppstein** [comment]
As scott said, spriting is it's own gem soon. It has a lot of dependencies, so I didn't want to make it part of core. The work is mostly done so the 1.1 release should follow relatively quickly after 1.0.

I will move `to_sass_engine_options` and `to_sass_plugin_options` to core.

**Comment by tdreyno** [comment]
Gracias. I'll point my test branch at master and let you know. Is there any way to communicate to users that Spriting is disabled?

**Comment by chriseppstein** [comment]
@tdreyno Spriting is not disabled. Moving to compass-core is optional. Users who have installed "compass" and depend on the "compass" gem continue to have sprites.

**Comment by lolmaus** [comment]
@tdreyno How about we depend on `compass` until `compass-core` and `compass-sprites` hit 1.1?

**Comment by chriseppstein** [comment]
@tdreyno I suggest, if you're eager to use compass-core by default, you can message this change about sprites however makes sense to middleman, and allow people to install the old plugin instead if they need that.

**Comment by chriseppstein** [comment]
@tdreyno Let me know if you bump into anything else.
