### ISSUE TITLE
Compile error when using SASS maps

### ISSUE THREAD

**Issue by sergonie** [Compass/compass#1744]
__base.scss_:

```
...
//headers (h1, h2, ...)
$h-color: #444;
$h-font-size: (
        h1: 32pt,
        h2: 24pt,
        h3: 18pt,
        h4: 16pt,
        h5: 14pt,
        h6: 12pt
);
@each $header, $size in $h-font-size {
  #{$header} {
    color: $h-color;
    font-size: $size;
  }
}
...
```

and _cudui.scss_:

```
@import "base";
```

At command execution `compass compile` there is a mistake:

```
error assets/sass/cudui.scss (Line 24 of assets/sass/_base.scss: Invalid CSS after "        h1": expected ")", was ": 32pt,")
```

I use **Compass 0.12.7** and **Sass 3.3.14**

Thanks for attention!

**Comment by lolmaus** [comment]
Compass 0.x is incompatible with Sass 3.3 and most likely pulls Sass 3.2 which is in turn incompatible with maps and raises the above error.

Use Bundler to impose proper dependency versions. Use Compass 1.x and Sass 3.3 or 3.4 for maps support.

**Comment by chriseppstein** [comment]
What @lolmaus said, the issue is that you need the 1.0 preview release of compass to use sass 3.3.

```
$ gem install compass --pre
$ compass version
Compass 1.0.0.rc.1 (Polaris)
Copyright (c) 2008-2014 Chris Eppstein
Released under the MIT License.
Compass is charityware.
Please make a tax deductable donation for a worthy cause: http://umdf.org/compass
```
