### ISSUE TITLE
Omit compass files from generated sourcemap

### ISSUE THREAD

**Issue by zerocrates** [Compass/compass#1745]
Using the sourcemap support with compass works great, but it does generate a large number of relative references to compass's own files inside my .gem directory. Is there a way to omit these?

To my understanding, those paths in the `sources` key are only useful if the sources are actually being served at the paths given. I suppose this might work for pages being worked on at `file:///` URLs, but are these really likely to work for anyone?

**Comment by chriseppstein** [comment]
run `compass unpack compass` to unpack compass's sass stylesheets into a local directory.

**Comment by zerocrates** [comment]
I guess the question I'm really asking is: is there a way to make those compass sources not show up in the sourcemap if I _haven't_ locally unpacked them?
