### ISSUE TITLE
Opacity mixin to support !important argument

### ISSUE THREAD

**Issue by Melonbwead** [Compass/compass#1748]
(Feature Request)

Currently the opacity mixin takes a $opacity param only.
http://compass-style.org/reference/compass/css3/opacity/

Any thoughts on allowing us to do something like this:

```
@include opacity(1 !important);
```

**Comment by chriseppstein** [comment]
I am not going to be able to handle adding `!important` support to every mixin in compass. This requires Sass language support. In https://github.com/sass/sass/issues/1040 I outlined how I think this should work, but @nex3 is not on board.
