### ISSUE TITLE
strange dropped /* comments */

### ISSUE THREAD

**Issue by hansbkk** [Compass/compass#175]
To get the below comment 
  <code>
  /\* For all. */
  </code>

to output, I have to do this:

  <code>
  button {
    @if $ie6-7 {
        margin: 1.75em 0 0;
        /\* For all. _/
     } @else {
        /_ For all but IE 6 & 7. _/
        margin: 0.8em 0 0;
        /_ For all. */
     }
    padding: 0 0.5em;
  }
  </code>

rather than this:

  <code>
  button {
    @if $ie6-7 {
        /\* For IE 6 & 7 only. _/
        margin: 1.75em 0 0;
     } @else {
        /_ For all but IE 6 & 7. _/
        margin: 0.8em 0 0;
     }
    /_ For all. */
    padding: 0 0.5em;
  }
</code>

**Comment by chriseppstein** [comment]
This is a Sass bug, I have copied the issue to here:

http://github.com/nex3/haml/issues/issue/218
