### ISSUE TITLE
Compass Stats broken in 1.0.0.rc.1

### ISSUE THREAD

**Issue by micahgodbolt** [Compass/compass#1750]
On 100% fresh "compass create" project (as well as on large established project) i get this error when running `compass stats` in RC1

/2.1.1/lib/ruby/gems/2.1.0/gems/compass-1.0.0.rc.1/lib/compass/commands/project_stats.rb: undefined method `sass_files' for #Compass::SassCompiler:0x007fece97cc788

**Comment by chriseppstein** [comment]
Fixed by fd2194da2a42d6c078b8928d36aa82a2fb5b185a
