### ISSUE TITLE
Duplicate Compass compiles when using watch

### ISSUE THREAD

**Issue by kemch** [Compass/compass#1752]
I'm getting multiple compiles when doing `compass watch .`. When I first initiate it this way, files will compile once as normal, but when making a change, I'll see this in the terminal.

`info base/_base.scss was modified`
`info base/_base.scss was modified`
`overwrite ../css/main.css was modified`
`identical ../css/main.css`

I get anywhere from 2 to 3 duplicates depending on the project.

I'm not quite sure what caused this... restarting does not help. Any idea how to idenitfy what is going on?

**Comment by chriseppstein** [comment]
Please upgrade to `1.0.0.rc.1` and let us know if you still see this issue.

**Comment by chriseppstein** [comment]
(I could not reproduce it)

**Comment by kemch** [comment]
I still see the same issue with `1.0.0.rc.1`.

**Comment by chriseppstein** [comment]
kemch I need to see your compass configuration.

**Comment by kemch** [comment]
I think I isolated the behavior to when I use `additional_import_paths`.

```
sassPath = "/users/kurt.emch/Sites/sandbox/"

additional_import_paths = [sassPath]

http_path = "/"
css_dir = "../css"
sass_dir = "."
images_dir = "../images"
sprite_load_path = "../images/icons"

http_images_path = images_dir

sourcemap     = true
output_style  = :expanded
line_comments = true
```

**Comment by chriseppstein** [comment]
Why are you adding the sass path again? That shouldn't be necessary.

**Comment by kemch** [comment]
So I can use 'absolute' import paths for lack of a better term. In any case, it shouldn't be watching a file more than once?

**Comment by kemch** [comment]
Not sure why, but after updating to ruby 2.1.1p76, using Sass 3.3.7, and Compass 1.0.0.alpha.19, the problem seems to have gone away.
