### ISSUE TITLE
Sourcemaps are always output even when not requested

### ISSUE THREAD

**Issue by JohnAlbin** [Compass/compass#1753]
When using compass on the command line, it _always_ outputs sourcemap files. It should only output sourcemap files when the `--sourcemap` option is given to it or its specified in config.rb.

Here's my simple test case. There is no config.rb file in the directory. sass/test.scss is a CSS file with 1 ruleset and with no Sass syntax used.

```
$ sass --version
Sass 3.3.14 (Maptastic Maple)

$ compass --version
Compass 1.0.0.rc.1 (Polaris)

$ sass --update sass/test.scss:stylesheets/test.css
  directory stylesheets
      write stylesheets/test.css

$ rm -rf stylesheets/ .sass-cache/

$ sass --sourcemap --update sass/test.scss:stylesheets/test.css
  directory stylesheets
      write stylesheets/test.css
      write stylesheets/test.css.map

$ rm -rf stylesheets/ .sass-cache/

$ compass compile sass/test.scss 
directory stylesheets
    write stylesheets/test.css
    write stylesheets/test.css.map
```

You can see that the `sass` command works as expected on the command line. The Compass one generates a map file when it isn't told to.

**Comment by chriseppstein** [comment]
I don't see this @JohnAlbin. I removed my config file and it only writes the sourcemap.

```
➜  browser_support git:(master) ✗ bundle exec compass clean
   delete stylesheets/ie.css
   delete stylesheets/print.css
   delete stylesheets/screen.css
➜  browser_support git:(master) ✗ bundle exec compass compile
    write stylesheets/ie.css
    write stylesheets/print.css
    write stylesheets/screen.css
➜  browser_support git:(master) ✗ bundle exec compass clean
   delete stylesheets/ie.css
   delete stylesheets/print.css
   delete stylesheets/screen.css
➜  browser_support git:(master) ✗ bundle exec compass compile --sourcemap
    write stylesheets/ie.css
    write stylesheets/ie.css.map
    write stylesheets/print.css
    write stylesheets/print.css.map
    write stylesheets/screen.css
    write stylesheets/screen.css.map
```

Are you sure compass isn't picking up sass 3.4.0.rc.x? In that release, sourcemaps default to being enabled.

**Comment by chriseppstein** [comment]
I saw someone else report this too. I need to be able to reproduce it. >_<

**Comment by JohnAlbin** [comment]
> Are you sure compass isn't picking up sass 3.4.0.rc.x?

I haven't installed a pre-release of Sass since the 3.2 betas (placeholder selectors were too tempting!). So I definitely had Sass 3.3.14 installed at the time.

I now have Compass 1.0.1 and Sass 3.4.4 and I no longer experience the problem.

**Comment by scottdavis** [comment]
@chriseppstein i can reproduce it

**Comment by scottdavis** [comment]
```
$ bundle exec compass compile /Users/sdavis/Work/js-app /Users/sdavis/Work/js-app/app/styles/application.scss --environment production -c ./config/compass.rb  --css-dir dist/styles --sass-dir app/styles --no-sourcemap

directory dist/styles
    write dist/styles/application.css
    write dist/styles/application.css.map
```
