### ISSUE TITLE
compass-import-once: Import order does not follow the dependency path

### ISSUE THREAD

**Issue by ChristianPeters** [Compass/compass#1755]
_Using compass-import-once 1.0.4 with sass 3.2.19 and sass-rails 4.0.3_

I am trying to manage the dependencies of my Sass partials by defining them at the top of each partial using `@import`.

The output CSS does not have the intended order though. I am facing the following problem:

Manifest application.css.sass:

``` sass
@import globals/form
@import components/classic-form
```

globals/_form.css.sass:

``` sass
@import components/balloon

%field-hint
  @extend .balloon
  position: absolute
  left: 5%
```

components/_balloon.css.sass:

``` sass
@mixin balloon
  position: relative  
  …

.balloon
  +balloon
```

components/_classic-form.css.sass:

``` sass
@import globals/form

.classic-form--field-hint
  @extend %field-hint
  left: 30% + 5%
```

The order in the generated CSS file is not the same as above though:
1. globals/_form.css.sass
2. components/_classic-form.css.sass
3. components/_balloon.css.sass

The result is that my `.classic-form--field-hint` is `position: relative` instead of `absolute`:
![easy entry 2014-08-11 15-50-43 2014-08-11 15-51-04](https://cloud.githubusercontent.com/assets/56810/3876694/883b723c-215e-11e4-8d04-157c07c99ec8.jpg)
The reason is that `.balloon` is `relative` and imported after the placeholder `%field-hint` which is `absolute`.

It seems to me that all files of the manifest are imported first, then the imports of the first imported file and so on. My requirement, however, is that the dependency tree is traversed in a depth-first manner.

I would like to leverage Sass and the tools in its ecosystem to establish a set of components which can be used as building blocks and composed to bigger components like a speech `balloon` used as a `field-hint`, used in a `classic-form--field-hint` component. Importing everything once in the manifest file  impedes the idea of having isolated and reusable components.

Is this a limitation of compass-import-once (or even sass / sass-rails?)? Or is my dependency management flawed and there is a better way of doing this?

**Comment by chriseppstein** [comment]
As I understand it you've got this structure:

```
application
  globals/form (Imported)
    components/balloon (imported)
  components/classic-form (imported)
    globals/form (Skipped. Already Imported)
      components/balloon (Skipped. Already imported)
```

You used to import it twice, bloating your output but giving you the cascade you wanted. Now you are only importing it once, but it giving you a different cascade. You will need to reorganize your importing to take import-once into account.
