### ISSUE TITLE
Require compiled without import

### ISSUE THREAD

**Issue by lagden** [Compass/compass#1757]
I have 2 `Compass` running...
1. Home - `Compass 1.0.0.rc.1 (Polaris) + Sass 3.4.0.rc.3 (Selective Steve)`
2. Work - `alpha version`

---

The `alpha` is ok...
The `Compass 1.0.0.rc.1` is with a strange behavior when compiled...

For example:

`$ compass create example`

Put `require 'bootstrap-sass'` on `config.rb` and run:

```
$ compass compile
 modified config.rb
    clean stylesheets
   delete stylesheets/ie.css
   delete stylesheets/print.css
   delete stylesheets/screen.css
    write stylesheets/ie.css
    write stylesheets/print.css
    write stylesheets/screen.css
directory stylesheets/bootstrap
    write stylesheets/bootstrap/bootstrap.css
directory stylesheets/bootstrap/bootstrap
    write stylesheets/bootstrap/bootstrap/bootstrap.css
```

Note that was generated `bootstrap.css` without any `sass file` in my example
In `alpha` that does not happen

**Comment by chriseppstein** [comment]
This is a feature in compass 1.0. Any extension with non-partials will generate into your project as a subfolder. Ask them to convert those files to partials.

**Comment by lagden** [comment]
tks!!
:beers:
