### ISSUE TITLE
Compass watch doesn't pickup new files

### ISSUE THREAD

**Issue by timmfin** [Compass/compass#176]
I've been using Compass quite extensively, and I love it. One thing that has been bugging me though is that the "compass watch" command does not pickup new files. I need to kill it and run it again to get a newly created file to compile (and then it works fine until I create another new file).

**Comment by chriseppstein** [comment]
I cannot reproduce this. Please provide more details. What OS? What exact steps did you perform?

**Comment by timmfin** [comment]
I apologize, I actually have this problem with coffeescript and not compass (I have one script that starts the "watch" processes at the same time so I only use up one terminal window). Must have had a brainfart and switched the two around when I went to post the issue. My bad.

**Comment by chriseppstein** [comment]
coffeescript should use fssm too ;)
