### ISSUE TITLE
compass app just not loading

### ISSUE THREAD

**Issue by jemcook** [Compass/compass#1764]
Hi I've just downloaded the compass app for windows. I can't get it to run. I've used it on previous systems and it's been brilliantly easy to set up, but on this new system I'm double clicking the icon and nothing is happening. I've tried downloading the package again and updating java but still no response. I'm using windows 8.1 - anyone any ideas about what may be going wrong?

with many thanks

Jem

**Comment by chriseppstein** [comment]
please file a bug about Compass.app here: https://github.com/KKBOX/CompassApp/issues
