### ISSUE TITLE
Configuration Reference Documentation Missing

### ISSUE THREAD

**Issue by Snugug** [Compass/compass#1768]
With the launch of the new site, it appears as if the [Configuration Reference](http://compass-style.org/help/tutorials/configuration-reference/) page has disappeared.

**Comment by chriseppstein** [comment]
It's here now: http://compass-style.org/help/documentation/configuration-reference/

**Comment by Snugug** [comment]
Awesome, thanks. I'd recommend a redirect from the old page because it's got a lot of SEO juice.
