### ISSUE TITLE
Compass 1.0.1 errors

### ISSUE THREAD

**Issue by ryanburnett** [Compass/compass#1777]
I just updated Compass to 1.0.1 and Sass to 3.4. Before the update everything was working perfectly. Now when I `compass watch` I get this error:

```
error sass/titan_sun_moon_fishing.sass

(Line 88 of /Library/Ruby/Gems/2.0.0/gems/toolkit-1.3.8/stylesheets/toolkit/_selectors.scss: 

Invalid CSS after "  a:not(": expected ")", was "[href^='http://...")

Errno::ENOENT on line ["50"] of /Library/Ruby/Gems/2.0.0/gems/listen-2.7.9/lib/listen/listener.rb:

No such file or directory - /Library/Ruby/Gems/2.0.0/gems/sassy-strings-1.0.0/stylesheets

Run with --trace to see the full backtrace
```

Any idea how to avoid this error? 

P.S. I'm on OS X 10.9.4 with:

```
compass -v
Compass 1.0.1 (Polaris)
sass -v
Sass 3.4.0 (Selective Steve)
```

**Comment by chriseppstein** [comment]
This is a sass issue, I filed the bug there.

**Comment by ryanburnett** [comment]
Great - thank you Chris!

**Comment by minneapolisdan** [comment]
I have the same issue, and not having luck finding the solution at https://github.com/sass/sass/issues. I realize this isn't the place to ask for help, but can anyone point the way? I'll keep looking. I did find this, https://github.com/sass/sass/issues/1385, but don't understand how they're related.

**Comment by minneapolisdan** [comment]
Never mind, I'll file my issue in the right place with more details.
