### ISSUE TITLE
@font-face - missing ";" in production-mode with compression 

### ISSUE THREAD

**Issue by vedam** [Compass/compass#178]
the following mixin...
    @mixin font-face($fontname) {
        @font-face {
          font-family: "#{$fontname}";
            font-style: normal;
          src: url($fontname + '.eot');
          src: local('☺'), url('/lib/fnt/' + $fontname + '.otf') format('opentype');
        }
    }

...produces in dev-mode without compression = CORRECT
    @font-face {
      font-family: "MyFontName";
      font-style: normal;
      src: url("MyFontName.eot");
      src: local("☺"), url("/lib/fnt/MyFontName.otf") format("opentype");
    }

...but in production-mode with compression = INCORRECT - missing ";"
    @font-face{font-family:"Gmond";font-style:normal;src:url("Gmond.eot");src:local("☺"), url("/lib/fnt/Gmond.otf") format("opentype")/\* missing ";" here */}

**Comment by nex3** [comment]
This is a Sass issue. In addition, the produced CSS is valid: you're allowed to omit semicolons at the end of a bracketed block.
