### ISSUE TITLE
--no-sourcemap flag doesn't work

### ISSUE THREAD

**Issue by nesk** [Compass/compass#1786]
Here's a simple example:

```
❯ compass help compile
[…]
Options:
        --[no-]sourcemap             Generate a sourcemap during compilation.
[…]
```

```
❯ compass compile --no-sourcemap sass/test.scss
directory stylesheets
    write stylesheets/test.css
    write stylesheets/test.css.map
```

However, I think you should stick to the original `--sourcemap` flag used by Sass which allows more configuration options from the command line.

This issue leads me to a question: Currently, how can I disable sourcemaps?

**Comment by scottdavis** [comment]
Yep im seeing the same thing

**Comment by scottdavis** [comment]
same as #1753
