### ISSUE TITLE
why your software is such piece of fucking shit i don't even

### ISSUE THREAD

**Issue by paulmillr** [Compass/compass#1789]
...

sorry i get into all sorts of stupid issues with your shit but I am still obligated to use compass since clients used in in the past

fucking issues with: sass / compass ver dependency hell; SUSY / breakpoint module issues; horrible traces which don't allow me to solve ANYTHING with `puts` 

whatever

![](http://unvailed.com/wp-content/uploads/2014/02/00000065-001.png)

@chriseppstein I don't want any support. Just wanted to relieve myself here.

**Comment by chriseppstein** [comment]
If you want support, put your emotions away and act like a grown up.
