### ISSUE TITLE
Better clearfix

### ISSUE THREAD

**Issue by ramaboo** [Compass/compass#179]
According to http://compass-style.org/docs/reference/compass/utilities/general/clearfix/

pie-clearfix says this:
"This method of clearing might cause a gap at the bottom of the page in some browsers when used on the last element of the page."

There is a simple fix for this. Rather than use your clearfix method:
=pie-clearfix
  &:after
    content: " "
    display: block
    height: 0
    clear: both
    overflow: hidden
    visibility: hidden
  +has-layout

Try this:
=pie-clearfix
  &:after
    content: "\0020"
    display: block
    height: 0
    clear: both
    overflow: hidden
    visibility: hidden
  +has-layout

and it will solve the problem (notice the special character \0020 use for content rather than a space).

Blueprint has now adopted this fix!

**Comment by chriseppstein** [comment]
Thanks, I will make this change.

**Comment by chriseppstein** [comment]
[Compass Core] New content char is the best practice for the pie-clearfix now. Avoids the gap at the bottom in some browsers.

Closed by dafbf93999c3f3e2be5f807df1bc5bcea73cb3a4
