### ISSUE TITLE
Flexbox Error: Mixin flexbox takes 0 arguments but 1 was passed.

### ISSUE THREAD

**Issue by Bobz-zg** [Compass/compass#1813]
I'm trying to test this flexbox layout model in compass.
I run into problem, when I copy entire example to my localhost: http://compass-style.org/examples/compass/css3/flexbox/

I get following error:

```
error: assets/sass/main.scss (Line 94 of /Users/xyz/.rvm/gems/ruby-2.0.0-p481@global/gems/compass-core-1.0.1/stylesheets/compass/css3/_flexbox.scss: Mixin flexbox takes 0 arguments but 1 was passed.)
```

To compile my scss files I use grunt-contrib-compass

ruby: 2.0.0p481 (2014-05-08 revision 45883) [x86_64-darwin13.1.0]
compass: Compass 1.0.1 (Polaris)
Sass 3.4.3 (Selective Steve)
grunt-contrib-compass: "~0.9.1"

Same error I get when I run 'Compass watch'.
Any ideas why is this happening?

**Comment by eddie-ruva** [comment]
@Bobz-zg Hi! I tried to reproduce your problem but for me everything is working correctly with the same versions that you are mentioning: 

``` bash
$ compass --version
Compass 1.0.1 (Polaris)

$ ruby --version
ruby 2.0.0p451
```

Do you remember doing anything besides copying and pasting the example?

**Comment by Bobz-zg** [comment]
Hi Eddie,

Thanks for reply
It was my mistake, I just realised that I have imported my custom flexbox mixins, so there was a conflict _captain obvious_.
Works, thanks

Cheers
