### ISSUE TITLE
1.0.1 upgrade problem: zen-grid-item 

### ISSUE THREAD

**Issue by adriancotter** [Compass/compass#1818]
Hope this is a good place to post this question. If not, if you have suggestions as to where I could get help, that would be greatly appreciated.

I use a PC. I was on compass 0.12 (I may have the exact number wrong)
When I upgraded my layouts were suddenly blown out, the width of the page being written as 200% instead of 66%.

This code

```
  .sidebar-first {
    #content {
      @include zen-grid-item(2, 1);
    }
```

was producing

```
media all and (min-width: 60em) {
  /* line 38, ../../sass/layouts/extended-responsive-sidebars.scss */
  .sidebar-first #content {
    float: left;
    width: 66.66667%;
    margin-left: 0%;
    margin-right: -66.66667%;
```

Now, with Compass 1.0.1 it is producing this

```
@media all and (min-width: 60em) {
  /* line 39, ../../sass/layouts/extended-responsive-sidebars.scss */
  .sidebar-first #content {
    float: left;
    width: 200%;
    margin-left: 0%;
    margin-right: -200%;
```

I went through all the changelogs but didn't see anything that would directly affect this. Any pointers as to where I should be looking?

Thanks,
Adrian

**Comment by adriancotter** [comment]
the problem seems to be around zen-grid-width: 100%
This seems to be setting the column width, not the full grid.
I don't see any documentation that says it should be doing this.

**Comment by lolmaus** [comment]
Here's the correct place to ask that: https://github.com/JohnAlbin/zen-grids/issues/

**Comment by lolmaus** [comment]
There seems to be a ticket for that already: https://github.com/JohnAlbin/zen-grids/issues/68

**Comment by adriancotter** [comment]
thanks @lolmaus

**Comment by shayank66** [comment]
you must overwrite zen-column-count with !global.
https://www.drupal.org/node/2346291#comment-9475791
