### ISSUE TITLE
compass imports never ends and eat 100% CPU

### ISSUE THREAD

**Issue by zedalaye** [Compass/compass#1819]
I have these versions of compass related gems installed:

``` bash
$ gem list | grep compass
compass (1.0.1, 0.12.7, 0.12.2)
compass-core (1.0.1)
compass-import-once (1.0.5)
compass-rails (2.0.0, 1.1.3)
```

When I run `$ compass imports` the process never ends and eat a full CPU core.

The problem surfaced in RubyMine. The command it lauches is:

`/home/pierre/.rvm/rubies/ruby-2.1.2/bin/ruby /home/pierre/.rvm/gems/ruby-2.1.2/gems/compass-0.12.7/bin/compass imports`

Same result.

**Comment by chriseppstein** [comment]
This happens when you don't have a rails configuration. 

https://github.com/Compass/compass-rails/blob/master/lib/compass-rails.rb#L18

Perhaps that project would consider this a bug. Please file a bug against them to discuss: https://github.com/Compass/compass-rails/issues
