### ISSUE TITLE
undefined method `usage' for Compass::Commands::Imports:Class

### ISSUE THREAD

**Issue by homburg** [Compass/compass#182]
NoMethodError on line ["71"] of /var/lib/gems/1.9.1/gems/compass-0.10.2/lib/compass/commands/help.rb: undefined method `usage' for Compass::Commands::Imports:Class

**Comment by chriseppstein** [comment]
what did you do to reach this error?

**Comment by homburg** [comment]
Sorry, bad issue reporting :-)

`$ compass help imports`

on Ubuntu Lucid 10.04 amd64

**Comment by homburg** [comment]
There is no error on the rest of the help subjects: create, init, frameworks, etc.

**Comment by chriseppstein** [comment]
Add help text for the imports subcommand.
Closed by 37db7f3b8c7e2faeb72463b97059bbca5720c6a7
