### ISSUE TITLE
update documentation

### ISSUE THREAD

**Issue by Bryce-Stark** [Compass/compass#1820]
You guys still have flexbox labeled in the css3 on your site, but when trying to import or view files........ 404. 

thanks.

**Comment by chriseppstein** [comment]
The flexbox links on [this page](http://compass-style.org/reference/compass/css3/) all go to the [flexbox page](http://compass-style.org/reference/compass/css3/flexbox/) Which loads for me.

Maybe I don't understand what link you're referring to. Please let me know more details, thanks.
