### ISSUE TITLE
using $use-percentages for sprite()

### ISSUE THREAD

**Issue by Yog** [Compass/compass#1829]
from documentation http://compass-style.org/reference/compass/helpers/sprites/#sprite
I'd like to use:
`sprite($map, $sprite, $offset-x, $offset-y, $use-percentages)`
so that compass will parse background-position as percentage values and not as px
my code:

``` scss
$sprite-technologyy: sprite-map("_technology/*.png");
background: sprite($sprite-technology, 'technology-image', true);
```

Doesn't seam to work.
But it should in v1.0.0, which I use ? 
I'm probably missing something, does anyone knows what?

**Comment by chriseppstein** [comment]
`$use-percentages` is the 5th argument. You are passing it as the 3rd. To pass the 5th argument without passing the 3rd and 4th arguments, use keyword-style argument passing:

`sprite($sprite-technology, 'technology-image', $use-percentages: true);`

**Comment by Yog** [comment]
thank you, unfortunately

``` scss
background: sprite($sprite-technology, 'technology-image', $use-percentages: true);
```

or

``` scss
background: sprite($sprite-technology, 'technology-image', 0px, 0px, true);
```

wouldn't work and I'm getting: 
`error app/styles/main.scss (Line 413 of app/styles/_styles.scss: Function sprite requires an argument named $offset_x)`
and for the latter:
`error app/styles/main.scss (Line 413 of app/styles/_styles.scss: wrong number of arguments (5 for 4) for 'sprite')`
I must be missing something else besides compass then, but i don't know it could be.
