### ISSUE TITLE
Installation on Ubuntu fails: A certain dependency (ffi_c) of Compass fails to be built on Ubuntu 14+  

### ISSUE THREAD

**Issue by lozandier** [Compass/compass#1830]
For some reason Compass fails to install itself and its dependency on Ubuntu w/ Ruby 2.1.2 installed: 
![screenshot from 2014-09-18 04 03 09](https://cloud.githubusercontent.com/assets/1223224/4316702/76b69f4a-3f0a-11e4-8a37-1b3100374d57.png)

**Comment by chriseppstein** [comment]
Looks like this issue with how you installed ruby: http://blogs.law.harvard.edu/hoanga/2006/10/27/fixing-mkmf-load-error-ruby-in-ubuntu/
