### ISSUE TITLE
"Did not recognize your adapter specification" - Dependency problem with compass/support?

### ISSUE THREAD

**Issue by cibulka** [Compass/compass#1831]
Hello everyone!

If I use `@import "compass/support";` in my master .scss file, I get this error: 

> assets/styles/dev/style.scss (Line 7 of /Users/Cibulka/.rvm/gems/ruby-2.1.2/gems/compass-core-1.0.1/stylesheets/compass/_support.scss: Did not recognize your adapter specification (cannot load such file -- multi_json/adapters/json_gem). for `browsers')

Multi_json gem exists and is updated to its current version. Due to a myriad of problems with Ruby version conflicts (which I don't know much about), I am using RVM to manage them.

```
$ ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
$ gem -v
2.2.2
$ gem list
(...)
compass (1.0.1)
compass-core (1.0.1)
(...)
multi_json (1.10.1)
(...)
rvm (1.11.3.9)
sass (3.4.4)
```

Any suggestions what might be wrong? Thank you!

**Comment by cibulka** [comment]
Okay, it seems, that the problem was solved with **yet another** RVM reinstall. I probably made some user error involved with installation of RVM, although the problem seemed to be appearing only with Compass installation (every other gem I've tried worked more or less fine)... 

As Compass seems to be quite designer-oriented, could you maybe consider some sort of tutorial with recommended RVM setup with some basic troubleshooting steps? Anyway, closing this for now - hopefully the mysterious problem will stay fixed!

**Comment by alanhogan** [comment]
I also bumped into this. So did my co-worker.

**Comment by alanhogan** [comment]
@cibulka which Ruby are you using?

**Comment by alanhogan** [comment]
I experienced this with 
`=* ruby-2.1.3 [ x86_64 ]`

**Comment by alanhogan** [comment]
```
>>> ruby -v
ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]
```

**Comment by alanhogan** [comment]
Co-worker with this problem is on `2.0.0p481`

**Comment by cibulka** [comment]
My `ruby -v` command outputs this:

```
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin11.0]
```

I had A LOT of problems with Compass installation. It seems, that they were caused by conflicting versions of Ruby (or at least most of them?). [That apparently happens quite often](https://www.google.cz/search?q=ruby+version+conflict), as it is common to have multiple Rubies installed on your system. 

In short - install Ruby version manager ([RVM](http://rvm.io/)) or similar library. I needed to reinstall it few times though, as the process was a little cryptic to me (my knowledge of Ruby is pretty much none). Finally I needed to delete weird alias from my `~/.rvm` folder - I think it was something like ruby2.1.2@global? - and for some reason, everything started working.

**Comment by alanhogan** [comment]
I just fixed my issue.
1. `rm -rf ~/.rvm/`
2. `\curl -sSL https://get.rvm.io | bash -s stable --ruby`
3. `gem install bundler`
4. `bundle install`

Note that 3 & 4 are not necessary; I have a gemfile for this project; you can just run `gem install compass` instead, depending on your situation

**Comment by palladius** [comment]
I'm having the same problem with ruby-2-3-3 :/

/home/riccardo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require': Did not recognize your adapter specification (incompatible library version - /home/riccardo
/.rvm/gems/ruby-2.3.3/gems/json-2.0.3/lib/json/ext/parser.so). (MultiJson::AdapterError)
        from /home/riccardo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /home/riccardo/.rvm/gems/ruby-2.3.3/gems/json-2.0.3/lib/json/ext.rb:7:in `<module:Ext>'
        from /home/riccardo/.rvm/gems/ruby-2.3.3/gems/json-2.0.3/lib/json/ext.rb:6:in `<module:JSON>'
        from /home/riccardo/.rvm/gems/ruby-2.3.3/gems/json-2.0.3/lib/json/ext.rb:3:in `<top (required)>'
        from /home/riccardo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /home/riccardo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /home/riccardo/.rvm/gems/ruby-2.3.3/gems/multi_json-1.12.1/lib/multi_json/adapters/json_gem.rb:1:in `<top (required)>'
        from /home/riccardo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /home/riccardo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /home/riccardo/.rvm/gems/ruby-2.3.3/gems/multi_json-1.12.1/lib/multi_json.rb:157:in `load_adapter_from_string_name'
        from /home/riccardo/.rvm/gems/ruby-2.3.3/gems/multi_json-1.12.1/lib/multi_json.rb:101:in `load_adapter'
        from /home/riccardo/.rvm/gems/ruby-2.3.3/gems/multi_json-1.12.1/lib/multi_json.rb:103:in `load_adapter'
        from /home/riccardo/.rvm/gems/ruby-2.3.3/gems/multi_json-1.12.1/lib/multi_json.rb:91:in `use'
        from /home/riccardo/.rvm/gems/ruby-2.3.3/gems/multi_json-1.12.1/lib/multi_json.rb:73:in `adapter'
        from /home/riccardo/.rvm/gems/ruby-2.3.3/gems/multi_json-1.12.1/lib/multi_json.rb:133:in `current_adapter'
        from /home/riccardo/.rvm/gems/ruby-2.3.3/gems/multi_json-1.12.1/lib/multi_json.rb:120:in `load'
        from /home/riccardo/.rvm/gems/ruby-2.3.3/gems/signet-0.7.3/lib/signet/oauth_2.rb:82:in `parse_credentials'
        from /home/riccardo/.rvm/gems/ruby-2.3.3/gems/signet-0.7.3/lib/signet/oauth_2/client.rb:975:in `fetch_access_token'
        from /home/riccardo/.rvm/gems/ruby-2.3.3/gems/signet-0.7.3/lib/signet/oauth_2/client.rb:998:in `fetch_access_token!'
        from /home/riccardo/.rvm/gems/ruby-2.3.3/gems/googleauth-0.5.1/lib/googleauth/signet.rb:69:in `fetch_access_token!'
        from /home/riccardo/.rvm/gems/ruby-2.3.3/gems/google-cloud-core-0.21.0/lib/google/cloud/credentials.rb:59:in `initialize'
        from /home/riccardo/.rvm/gems/ruby-2.3.3/gems/google-cloud-datastore-0.21.0/lib/google/cloud/datastore.rb:570:in `new'
        from /home/riccardo/.rvm/gems/ruby-2.3.3/gems/google-cloud-datastore-0.21.0/lib/google/cloud/datastore.rb:570:in `credentials_with_scope'
        from /home/riccardo/.rvm/gems/ruby-2.3.3/gems/google-cloud-datastore-0.21.0/lib/google/cloud/datastore.rb:557:in `new'
        from datastore-riccardo-test.rb:8:in `<main>'

**Comment by nerwinhernando** [comment]
I know this is an old post. I am using Ruby 2.4.1 in my Rails project. And this also happened to me.  What I did is just to use an older ruby version.. 2.3.0 and below will work.
