### ISSUE TITLE
Compass Fails to Compile Says No such file or directory Version 1.0.1

### ISSUE THREAD

**Issue by rmevans1** [Compass/compass#1832]
When I try to include any of the compass libraries I get the following error or a very similar error when I try to compile the code:

c:/Ruby193/lib/ruby/1.9.1/tempfile.rb:346:in `rmdir': No such file or directory - c:/Users/Robert/Documents/Aptana Studio 3 Workspace/compass/.sass-c
ache/75fcaf1b4852ceb732871195e41567cc2a7d8997/c%058/Ruby193/lib/ruby/gems/1.9.1/gems/compass-core-1.0.1/stylesheets/compass/utilities/general/_clearfix.scssc20140919-9136-1k9x9p
m.lock

**Comment by chriseppstein** [comment]
I don't understand what you're doing to get this error. Please provide steps to reproduce.

**Comment by rmevans1** [comment]
Nevermind it turns out compass doesn't like spaces in the path.

**Comment by mazarini** [comment]
I have the same problème when I add both lines
@import "compass/utilities";
@import "compass/typography";
or just one of this
@import "compass/css3"; works fine alone

Message : 
Errno::ENOENT: No such file or directory - C:/srv/www.magento.dev/web/skin/frontend/theme/default/.sass-cache/75fcaf1b4852ceb732871195e41567cc2a7d8997/C%058/Ruby193/lib/ruby/gems/1.9.1/gems/compass-core-1.0.1/stylesheets/compass/typography/lists/_horizontal-list.scssc20141001-6620-a0d9zq.lock

Backtrace:
C:/Ruby193/lib/ruby/1.9.1/tempfile.rb:346:in `rmdir'
C:/Ruby193/lib/ruby/1.9.1/tempfile.rb:346:in`rmdir'
C:/Ruby193/lib/ruby/1.9.1/tempfile.rb:338:in `ensure in locking'
C:/Ruby193/lib/ruby/1.9.1/tempfile.rb:338:in`locking'
C:/Ruby193/lib/ruby/1.9.1/tempfile.rb:144:in `block in initialize'
C:/Ruby193/lib/ruby/1.9.1/tmpdir.rb:133:in`create'
C:/Ruby193/lib/ruby/1.9.1/tempfile.rb:134:in `initialize'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/util.rb:1251:in`new'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/util.rb:1251:in `atomic_create_and_write_file'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/cache_stores/filesystem.rb:39:in`_store'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/cache_stores/base.rb:51:in `store'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/cache_stores/chain.rb:19:in`block in store'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/cache_stores/chain.rb:19:in `each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/cache_stores/chain.rb:19:in`store'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/engine.rb:404:in `_to_tree'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/engine.rb:299:in`to_tree'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:313:in `block in visit_import'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/stack.rb:88:in`block in with_import'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/stack.rb:115:in `with_frame'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/stack.rb:88:in`with_import'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:312:in `visit_import'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/base.rb:36:in`visit'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/stack.rb:79:in`block in with_base'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/stack.rb:115:in `with_frame'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/stack.rb:79:in`with_base'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:158:in `visit'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:315:in`block (2 levels) in visit_import'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:315:in `map'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:315:in`block in visit_import'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/stack.rb:88:in `block in with_import'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/stack.rb:115:in`with_frame'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/stack.rb:88:in `with_import'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:312:in`visit_import'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/base.rb:36:in `visit'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:158:in`block in visit'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/stack.rb:79:in `block in with_base'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/stack.rb:115:in`with_frame'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/stack.rb:79:in `with_base'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:158:in`visit'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:315:in `block (2 levels) in visit_import'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:315:in`map'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:315:in `block in visit_import'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/stack.rb:88:in`block in with_import'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/stack.rb:115:in `with_frame'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/stack.rb:88:in`with_import'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:312:in `visit_import'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/base.rb:36:in`visit'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/stack.rb:79:in`block in with_base'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/stack.rb:115:in `with_frame'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/stack.rb:79:in`with_base'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:158:in `visit'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:315:in`block (2 levels) in visit_import'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:315:in `map'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:315:in`block in visit_import'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/stack.rb:88:in `block in with_import'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/stack.rb:115:in`with_frame'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/stack.rb:88:in `with_import'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:312:in`visit_import'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/base.rb:36:in `visit'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:158:in`block in visit'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/stack.rb:79:in `block in with_base'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/stack.rb:115:in`with_frame'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/stack.rb:79:in `with_base'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:158:in`visit'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/base.rb:52:in`map'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/base.rb:52:in `visit_children'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:167:in`block in visit_children'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:166:in`visit_children'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/base.rb:36:in `block in visit'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:186:in`visit_root'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/base.rb:36:in `visit'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:157:in`visit'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/visitors/perform.rb:8:in `visit'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/root_node.rb:36:in`css_tree'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/tree/root_node.rb:20:in `render'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/engine.rb:268:in`render'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-import-once-1.0.5/lib/compass/import-once/engine.rb:17:in `block in render'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-import-once-1.0.5/lib/compass/import-once/engine.rb:29:in`with_import_scope'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-import-once-1.0.5/lib/compass/import-once/engine.rb:16:in `render'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/plugin/compiler.rb:491:in`update_stylesheet'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/plugin/compiler.rb:215:in `block in update_stylesheets'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/plugin/compiler.rb:209:in`each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.5/lib/sass/plugin/compiler.rb:209:in `update_stylesheets'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/lib/compass/sass_compiler.rb:40:in`compile!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/lib/compass/commands/update_project.rb:49:in `perform'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/lib/compass/commands/base.rb:18:in`execute'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/lib/compass/commands/project_base.rb:19:in `execute'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/lib/compass/exec/sub_command_ui.rb:43:in`perform!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/lib/compass/exec/sub_command_ui.rb:15:in `run!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/bin/compass:30:in`block in <top (required)>'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/bin/compass:44:in `call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/bin/compass:44:in`<top (required)>'
C:/Ruby193/bin/compass:23:in `load'
C:/Ruby193/bin/compass:23:in`<main>'
*/
body:before {
  white-space: pre;
  font-family: monospace;
  content: "Errno::ENOENT: No such file or directory - C:/srv/www.magento.dev/web/skin/frontend/theme/default/.sass-cache/75fcaf1b4852ceb732871195e41567cc2a7d8997/C%058/Ruby193/lib/ruby/gems/1.9.1/gems/compass-core-1.0.1/stylesheets/compass/typography/lists/_horizontal-list.scssc20141001-6620-a0d9zq.lock"; }

**Comment by bastiW** [comment]
I had to add the full project path to the watch command. Then it worked on windows. So e. g. 

> compass watch "C:\Users\MyUSER\Documents\compass\my-awesome-compass-project"

**Comment by RobWiddick** [comment]
I was having the same issue with Ruby v1.9.3.

My solution was to uninstall all ruby versions and install 2.1.6 and then install compass.

From there, I was able to compile properly.
