### ISSUE TITLE
Gradients not being output

### ISSUE THREAD

**Issue by rctneil** [Compass/compass#1834]
I am trying to use a gradient just as normal like so:

```
.highlight-box__list
  padding: 20px
  +background-image(linear-gradient(#eeeeee, #ffffff))
```

Nothing is getting output into the compiled CSS. I have tried using Compass 1.0.1 and Compass 1.1.0.alpha.3 and same results on both.

Any ideas?

**Comment by scottdavis** [comment]
Are you importing any other libraries before this?

**Comment by rctneil** [comment]
Thanks for the hint. Compass was the first to be loaded but I was importing another one after that must have messed it up. Removed it and all is working normally. Thanks!
