### ISSUE TITLE
Sprite output has changed

### ISSUE THREAD

**Issue by antgonzales** [Compass/compass#1835]
For some reason, my sprites are no longer output as 
`background: url(...)`

but are now output as
`background-image: url(...)`

I looked through the documentation but couldn't find a way to pass options that would make this change in behavior.

**Comment by scottdavis** [comment]
This was a change that happened during the 0.13 era mostly because sprites are `background-images`. And assigning it to `background` was causing issues with other properties you would want to set on `background`

**Comment by antgonzales** [comment]
Is there any way to change the configuration to get the original behavior?

**Comment by scottdavis** [comment]
not currently

**Comment by scottdavis** [comment]
if this is an issue we can keep this open and maybe work it in as a configuration option in future releases

**Comment by antgonzales** [comment]
Ah, okay cool. That would be fantastic only because it has altered some sprite styles on a pretty large site our team works on and would make it difficult to change to the new behavior. It would be great to have an option to choose the `background:` or `background-image:`
