### ISSUE TITLE
Fluid grid system

### ISSUE THREAD

**Issue by bartkozal** [Compass/compass#184]
A grid system like http://fluid.newgoldleaf.com/ might be a cool feature.

**Comment by chriseppstein** [comment]
Anyone can port this and distribute it as a compass extension.

Here's the documentation on how to do this:
http://compass-style.org/docs/tutorials/extensions/

Also, you may find this blog post and screencast useful to get started:
http://chriseppstein.github.com/blog/2010/08/01/building-a-personal-framework/

**Comment by mirisuzanne** [comment]
In fact there are several fluid grid systems ported already. Both Susy and the Blueprint port support fluid grids.

**Comment by bartkozal** [comment]
Ok, thank you for the information and sorry for my stupid issue! Cheers :)

**Comment by chriseppstein** [comment]
Not stupid at all. If you want, you can start a thread on the mailing list to discuss this framework and maybe see if people like the idea of porting it to sass. I'm always willing to help people get new frameworks set up.
