### ISSUE TITLE
incompatibility with margin: 0 auto of the @include container;

### ISSUE THREAD

**Issue by standuprey** [Compass/compass#185]
If I put @include container in my wrapper, I need to scroll down to see the footer.
This is due to margin: 0 auto in the container mixin
It needs to be margin: 0 auto -$footer_height

**Comment by chriseppstein** [comment]
sounds like you're using the sticky footer mixin too. Try changing the order so that the sticky footer comes after container.

**Comment by standuprey** [comment]
That does not change to put the sticky footer after, but I just added the line:
margin-bottom: -$footer-height;
after the @include container in my wrapper definition and it works

Note that I tried first to add
margin: 0 auto -$footer-height;
But that does not work, the source code shows ($footer-height = 90px)
margin: 0 auto-90px;
Where is the space gone?

**Comment by chriseppstein** [comment]
that's a quirk with sass because of how expressions can be nested in value lists. You just need to add some parens to disambiguate between subtraction and negation.
