### ISSUE TITLE
Where did the Blueprint documentation go?

### ISSUE THREAD

**Issue by Peeja** [Compass/compass#1857]
The Blueprint documentation appears to be missing. The closest I could find was https://github.com/Compass/compass/wiki/blueprint-documentation, which links to http://compass-style.org/reference/blueprint/, which is 404.

**Comment by mirisuzanne** [comment]
Blueprint was removed from Compass in 1.0, and is now living [on it's own](http://compass-blueprint.org/)

**Comment by Peeja** [comment]
Ah, I see. I thought that was an old site; the copyright says 2012, and I the Blueprint docs were only just recently removed from compass-style.org.

**Comment by mirisuzanne** [comment]
1.0 was a long time coming, and that was one of the early changes. :p
