### ISSUE TITLE
Compass Compile Converting “\f…” to “^O…”

### ISSUE THREAD

**Issue by luiscvega** [Compass/compass#1870]
When I run `compass compile public/`, compass converts the following styles:

```
    .foundicon-rss:before {
      content: "\f002";
    }

    .foundicon-facebook:before {
      content: "\f003";
    }

    .foundicon-twitter:before {
      content: "\f004";
    }
```

... to this...

```
    .foundicon-rss:before {
      content: "^O002";
    }

    .foundicon-facebook:before {
      content: "^O003";
    }

    .foundicon-twitter:before {
      content: "^O004";
    }
```

I'm viewing these fields via vim. It's messing up the styling of my site's icons. Is it a Foundation issue? Compass? Sass? This didn't use to happen in the previous versions. Was there a change that I'm not aware of?

**Comment by chriseppstein** [comment]
Sass changed how escapes are managed in sass 3.4. Try updating to the latest 3.4.x and if it's still breaking file a bug against the Sass repo.

**Comment by luiscvega** [comment]
@chriseppstein Thanks for this.
