### ISSUE TITLE
no implicit conversion of Array into String

### ISSUE THREAD

**Issue by csfeijo** [Compass/compass#1879]
Trying to use Compass inside a Rails application for CSS Sprites, but after insert the path of my icons inside the SCSS file the error below is displayed:

```
"in implicit conversion of Array into String"
```

This is the code:

file: custom.css.scss

```
@import "../icons/*.png"; // only this line causes the problem :( @include all-icons-sprites;
```

Inside the icons directory we have 4 files: 
![compass_issue](https://cloud.githubusercontent.com/assets/25899/5128493/a360efca-70c2-11e4-8830-9ff43d2c8692.png)
add.png, delete.png, settings.png and new.png.

**Comment by chriseppstein** [comment]
The import statement needs to be relative to your images directory, it's not relative to your sass file.
