### ISSUE TITLE
sass_compiler.rb should handle the case where the sass_filename method returns nil

### ISSUE THREAD

**Issue by mikesnare** [Compass/compass#1883]
In sass_compiler.rb's `when_compilation_error` method, the code checks to see if the error object responds to [sass_filename](https://github.com/sass/sass/blob/84e55254674508a4006517fff636f750da39ed64/lib/sass/error.rb#L65).  When this error is an instance of an SyntaxError this will always evaluate to true, but the docs for sass_filename make it clear that this method can return nil.

I'm not 100% sure why it's returning nil in my particular case, but it is.  Regardless of why it's nil, this should probably be handled by compass correctly.  As it is now, this nil value is passed to relativize [here](https://github.com/Compass/compass/blob/350bcaa544f594bca972aaa29a9bdfddceee5d4f/cli/lib/compass/sass_compiler.rb#L116) which pukes on the nil value, preventing any meaningful error about the actual compilation error from being displayed.

I eventually traced the error to be a compilation error due to a non-ascii character in a template that got included by a changed template (this happens during compass watch).  FWIW, in this particular case the sass_file variable passed to when_compilation_error is perfectly fine.

**Comment by chriseppstein** [comment]
Your patch didn't quite give the desired output so I just fixed it. Thanks!

**Comment by mikesnare** [comment]
Works for me, thanks.  I'll close #1884.
