### ISSUE TITLE
Compass sprite returns error

### ISSUE THREAD

**Issue by lwensveen** [Compass/compass#1896]
This is the config in my gruntfile.

```
    compass: {                  // Task
    dist: {                   // Target
        options: {              // Target options
            imagesDir: "./public/images/",
            generatedImagesDir: "./public/images/sprites/",
            generatedImagesPath: "./public/images/sprites/",
            httpGeneratedImagesPath: "../images/sprites"
        }
    }
},
```

When I run compass it returns the following error:

NoMethodError on line ["41"] of /Library/Ruby/Gems/2.0.0/gems/compass-1.0.1/lib/compass/commands/sprite.rb: undefined method `gsub' for nil:NilClass

**Comment by scottdavis** [comment]
grunt config doesn't help me debug this can you either supply an example project or a full stack track
