### ISSUE TITLE
rake assets:precompile bug with rails and compass and "*"

### ISSUE THREAD

**Issue by MatrixFr** [Compass/compass#1909]
I use rails 4.2.0 and compass-rails (2.0.2)

I have a css.scss file with 

```
@import "compass/utilities/sprites";
@import "icons/*.png";
@include all-icons-sprites(true);
```

I have many image .png in app/assets/images/icons/XXX.png

I want deploy my app in production, it's work but with no assets, so I start 

```
rake assets:precompile
```

in production environement.

I try to remove assets files in cache, nothing change.

The error: 

```
rake aborted!
Sprockets::FileNotFound: couldn't find file 'icons/*.png'
```

details error: http://pastebin.com/6ggS3pP2

I think there is a problem with wildcard and path.

I try in dev ENV, nothing change...

I don't know what do more, what's the solution, plz?

**Comment by rosenfeld** [comment]
Try using the master branch. This fixed it for me:

``` ruby
gem 'compass-rails', github: 'Compass/compass-rails'
```

**Comment by MatrixFr** [comment]
@rosenfeld  ok, works for me, but now it's the opposite problem, only image from sprite are shown.
The other, I have the good css but they are name statically "foo.png" and not "foo5a6c74fba31e0998218171e3ca.png", so all others images are hidden, how can I solve that?

**Comment by rosenfeld** [comment]
Sorry, but I didn't experience this problem so I have no idea on what might be happening...

**Comment by karlwist0** [comment]
Did you ever find the solution? I'm having trouble with wildcards too.
