### ISSUE TITLE
horizontal-list and no-bullets don't work in IE

### ISSUE THREAD

**Issue by saschwarz** [Compass/compass#191]
Load http://compass-style.org/docs/ in IE 8 and notice the element <nav id="compass-nav"> is rendered as a normal ul list.

**Comment by saschwarz** [comment]
Looks like this is only a problem when the ul li is within a <nav> element. Changing the nav to a div i.e. <div id="nav"> works as expected.

**Comment by chriseppstein** [comment]
closing
