### ISSUE TITLE
error on load of VERSION_NAME

### ISSUE THREAD

**Issue by beingmattlevy** [Compass/compass#1917]
Just updated my bundle with Rails 4.2. 
Got the following error:

/Users/matt/.rvm/gems/ruby-2.1.5@betterdoctor-web/gems/compass-1.0.2/lib/compass/version.rb:37:in `read': No such file or directory @ rb_sysopen - /Users/matt/.rvm/gems/ruby-2.1.5@betterdoctor-web/gems/compass-1.0.2/lib/compass/../../VERSION_NAME (Errno::ENOENT)

/lib/compass/version.rb:37
    VERSION_NAME = File.read(scope("VERSION_NAME")).strip

**Comment by abnovak** [comment]
:+1: I'm seeing this issue as well.

**Comment by pi-ron** [comment]
Changing my bundle to use compass '1.0.1' (instead of 1.0.2), fixed the issue for me.

**Comment by ryanmmmmm** [comment]
meet too im seeing issue

**Comment by scottdavis** [comment]
hmmm

**Comment by scottdavis** [comment]
ruby version?

**Comment by pi-ron** [comment]
My version is 2.0.0

**Comment by tamird** [comment]
2.2 here

**Comment by scottdavis** [comment]
oh i found it the VERSION_NAME wasn't included in the gemspec
let me yank 1.0.2 and cut 1.0.3

**Comment by scottdavis** [comment]
he about 30 minutes until i get to it

**Comment by PeterKneale** [comment]
woah, got this error 1 minute ago, and its reported here and a fix underway already! top stuff :)

**Comment by scottdavis** [comment]
ok 1.0.3 is out give it a spin

**Comment by hslater** [comment]
1.0.3 is failing for me because it's trying to find version 1.0.3 of compass-core, which doesn't exist.

**Comment by beingmattlevy** [comment]
Wow! top speed! Color me impressed.

**Comment by scottdavis** [comment]
sorry lets try this again its my first time releasing under the new de
coupling compass-core 1.0.3 pushed

**Comment by beingmattlevy** [comment]
confirmed 1.0.3 works. Thanks.
