### ISSUE TITLE
Missing _horizontal-list.scssc in compass-core on windows

### ISSUE THREAD

**Issue by dotnetCarpenter** [Compass/compass#1925]
`compass -v`: Compass 1.0.3 (Polaris)
`sass -v`: Sass 3.4.10 (Selective Steve)

Ok, this might be a hard one to track down.. On windows, using [gulp](https://github.com/gulpjs/gulp) task helper [gulp-compass](https://github.com/appleboy/gulp-compass), compiling throws:

```
Errno::ENOENT on line ["146"] of c: No such file or directory @ rb_sysopen - c:/Users/dotnet/Projects/weaddmotion/armadillo/indecks-component-filter/.sass-cache/75fcaf1b4852ceb732871195e41567cc2a7d8997/c%058/Ruby21-x64/lib/ruby/gems/2.1.0/gems/compass-core-1.0.3/stylesheets/compass/typography/lists/_horizontal-list.scssc20150126-8728-1swc7ha
```

Looking into the folder written above (... compass-core-1.0.3/stylesheets/compass/typography/lists/), is only __bullets.scssc_.
The command that gulp-compass uses is:

```
c:\Ruby21-x64\bin\compass.BAT compile c:/Users/dotnet/Projects/weaddmotion/armadillo/indecks-component-filter c:/Users/dotnet/Projects/weaddmotion/armadillo/indecks-component-filter/sass/filter.scss --no-line-comments --relative-assets --debug-info --sourcemap --fonts-dir fonts --output-style expanded --images-dir images --javascripts-dir js --css-dir css --sass-dir sass --require compass/import-once/activate
```

It doesn't make any difference if I use [MinGW](http://www.mingw.org/) (comes with [Msysgit](https://msysgit.github.io/)) or Windows _cmd_. If I just write `compass compile`, however, the sass files are compiled without errors.

Any pointers to where I should look for an answer?

**Comment by RobWiddick** [comment]
I was having the same issue with Ruby v1.9.3.

My solution was to uninstall all ruby versions and install 2.1.6 and then install compass.

From there, I was able to compile properly.

**Comment by dotnetCarpenter** [comment]
I actually found out that the issue was [too long paths](https://support.microsoft.com/en-us/kb/2891362) on windows. I then changed from using a configuration in gulp to use a `config.rb`, where I set the `.sass_cache` to be in the root (C:) on my drive.

I don't remember if using a `config.rb` was significant in the solution.

**Comment by MatthieuScarset** [comment]
Thank you for having solved this issue ;) 
I confirm that on Windows, setting <code>cache_path = '/c/.sass-cache'</code> in config.rb solve the issue.

**Comment by ccurtin** [comment]
:+1:  This was driving me insane. Thanks!
