### ISSUE TITLE
Download link at http://compass-style.org is broken

### ISSUE THREAD

**Issue by dnadlinger** [Compass/compass#195]
Currently, the »Download« link at http://compass-style.org points to http://github.com/chriseppstein/compass/wiki/getting-started, which displays a »Page has moved« message (which points you to the main documentation page instead of a download/install page).

**Comment by chriseppstein** [comment]
And the main docs page tells you how to install...

I've made a change to the homepage to take a less indirect path -- will deploy it soon.
