### ISSUE TITLE
Properties are only allowed within rules, directives, mixin includes, or other properties.

### ISSUE THREAD

**Issue by DamienRobert** [Compass/compass#1987]
WIth compass-1.0.3 + sass-3.4.15, the column mixin 
@import "compass/css3/columns";
@include columns(20em 2);
taken from
http://compass-style.org/reference/compass/css3/columns/
yields the following error:
error sass/screen.scss (Line 349 of /home/dams/opt/pkgmgr/gems/gems/compass-core-1.0.3/stylesheets/compass/_support.scss: Properties are only allowed within rules, directives, mixin includes, or other properties.)

**Comment by cimmanon** [comment]
Just like every other CSS3 mixin, the columns mixin outputs CSS properties.  You have to use it inside of a selector.

``` scss
.foo {
    @include columns(20em 2);
}
```

Note that there is an [example page for the columns module](http://compass-style.org/examples/compass/css3/columns/) showing this.

**Comment by DamienRobert** [comment]
Indeed, thanks and sorry for the noise!
