### ISSUE TITLE
Silent failure of compass command

### ISSUE THREAD

**Issue by shanesveller** [Compass/compass#2]
I am running on Leopard 10.5.6, with Ruby 1.8.6pl114, Rubygems 1.3.1.
My installed gems are [listed here](http://gist.github.com/111057).

Compass is gem version 0.6.6.

While attempting to follow [this tutorial](http://github.com/chriseppstein/compass-rails-sample-application/tree/master), when running the command `compass --rails -f blueprint .`, if the the target path ('.' in this case) is left off, it will fail silently.

**Comment by chriseppstein** [comment]
Yes, I've seen this bite people a couple of times now. I'll make a fix.

**Comment by chriseppstein** [comment]
Print a message when updating a project that has no files. They probably meant to install but forgot the directory argument. Closed by 15ebbfef304370d840d37a40c82636d0de73ea63.
