### ISSUE TITLE
Mixin Stretch sets value 0 on unspecified values

### ISSUE THREAD

**Issue by dcondrey** [Compass/compass#2002]
div { @include stretch($offset-top:5px); }

Output:

div { position: absolute;top: 5px;bottom: 0;left: 0;right: 0; }

Expected:

div { position: absolute;top: 5px; }

Setting the 0 values causes unexpected errors in layout because these values were intentionally to be undefined or inherited.

**Comment by cimmanon** [comment]
It sounds like what you want is _not_ the stretch mixin at all.  Looking at the [source of the mixin](http://compass-style.org/reference/compass/layout/stretching/#mixin-stretch), it should be obvious what you're getting.  If you don't want that, either don't use the mixin (absolutely positioning an element 5px from the top is _not_ what I would call "stretching") or set the other values to null:

``` scss
div { @include stretch(5px, null, null, null); }
```

Output:

``` css
div {
  position: absolute;
  top: 5px;
}
```
