### ISSUE TITLE
Background-position for sprite icons is calculated wrong

### ISSUE THREAD

**Issue by RandieM** [Compass/compass#2004]
Hello everyone,

Since I upgraded compass and compass-rails, the background-position related to sprite icons is calculated wrong in the CSS. The result is that the wrong icon is displayed on my website every time I call for a sprite icon in my CSS.

Here are the changes to my Gemfile that caused/triggered this issue:

```
-gem 'sass-rails', '~> 4.0.5'
+gem 'sass-rails', '~> 5.0.1'

-gem 'compass-rails', '~> 2.0.0'
+gem 'compass-rails', '~> 2.0.4'

-gem 'susy', '~> 1.0.9'
+gem 'susy', '~> 2.2.5'

-gem 'sass', '~> 3.2.19'
+gem 'sass', '~> 3.4.16'

-gem 'compass', '~> 0.12.7'
+gem 'compass', '~> 1.0.3'
```

My ruby version is 2.1.2, but I have also tried upgrading to 2.2.1 and 2.2.2 and the problem is still there.
I am using Rails 4.2
I am happy to provide you with any other information that you may need.

Many thanks

**Comment by RandieM** [comment]
Anyone?

**Comment by ryangraham** [comment]
I might have the same issue. But I think it was triggered when I went from ruby 1.9.3 to ruby 2.2.2.

I made similar gem upgrades hoping that would fix it. It did not.

**Comment by RandieM** [comment]
In case this could be helpful to somebody, I upgraded my application's gems to the following and the sprite problem "magically" resolved itself; hope it stays this way...

 `- gem 'sass-rails', '~> 5.0.1'`
`+ gem 'sass-rails', '~> 5.0.4'`

`- gem 'compass-rails', '~> 2.0.4'`
`+ gem 'compass-rails', '~> 2.0.5'`

`- gem 'susy', '~> 2.2.5'`
`+ gem 'susy', '~> 2.2.7'`

`- gem 'sass', '~> 3.4.16'`
`+ gem 'sass', '~> 3.4.20'`

`- gem 'compass', '~> 1.0.3'`
`+ gem 'compass', '= 1.0.3'`

**Comment by braindeaf** [comment]
Did anyone ever find a helpful fix for this, we're seeing this in production now. touching the sass files and forcing them to rebuild on every deploy seems to help but it is a tiresome workaround.

**Comment by brentdodell** [comment]
Any updates? Our production app just started experiencing this today.

**Comment by BenGlassAtlas** [comment]
@brentdodell Compass is no longer supported anymore so I doubt there will be an update

**Comment by brentdodell** [comment]
Thanks @BenSpace48, I was mainly hoping that someone in the community that still uses might have come up with a fix.

**Comment by RandieM** [comment]
Compass is no longer supported, therefore there is no point in keeping this issue open.
