### ISSUE TITLE
Importing of folders causes failed compile

### ISSUE THREAD

**Issue by danflynndesign** [Compass/compass#2008]
The following line fails to compile

@import "components/base/*";

It results in the following error

modified assets/sass/style.scss
    error assets/sass/style.scss (Line 27: File to import not found or unreadable: components/base/*.
Load paths:
  Compass::SpriteImporter
...
/Library/Ruby/Gems/2.0.0/gems/compass-core-1.0.3/stylesheets)

However, compiling the exact same code using Codekit worked so it has something to do with using "compass watch" from terminal that breaks it.

**Comment by cimmanon** [comment]
Are you using a globbing extension?  Neither Sass nor Compass includes the ability to do this by default.

**Comment by danflynndesign** [comment]
Thanks for your help @cimmanon! I realize now that I did not have that installed. I found the details here.
http://fuseinteractive.ca/blog/automatic-sass-imports-sass-globbing

Codekit worked fine to compile it and I didn't realize it was using a separate sass setup.
