### ISSUE TITLE
Adding trig functions for angle calculations

### ISSUE THREAD

**Issue by heygrady** [Compass/compass#201]
http://github.com/nex3/sass/issues/issue/4/

In order to target IE-specific fixes with handy mixins, it is necessary to do some simple math that is not supported currently in SASS.

Potential uses:
- IE specific fixes like calculating the shadow angle from the css compliant offsets.
- Working with CSS transforms

**Comment by thedarkone** [comment]
I use trig functions for pure CSS ribbons (allows me to change the angle without having to manually recalculate border dimensions).

Here's my implementation: http://gist.github.com/609458.

**Comment by chriseppstein** [comment]
Added trigonometry functions for fun and profit.
Closed by 463301e9834f97951f28179ef26afd9817bb48d7.

**Comment by heygrady** [comment]
hawt. I will do something incredibly useless with this new functionality.
