### ISSUE TITLE
(problem resolved) File to import not found or unreadable @import

### ISSUE THREAD

**Issue by stabla** [Compass/compass#2046]
hi,

after 3hours of constant research, i progressively desesperate, my problem is the next one : 
I'm Windows 10 user (and deeply sad of that), i installed today Brackets, with sass & compass,

I create my project with the lovely compass create command, then i create my files,  (index.html, style.scss) in my scss folder, and started compass watch, at this point everything going ok, but when I tried to add @import "compass"; or @import "compass/css3"; I had an error which appear in my IDE : 

 "file to import not found or unreadable: compass Current dir: C:/Users/myusername/AppData/Roaming/Brackets/brackets-sass/8ea1f18fb9c14b5a0a8543cb1d8c944f/Lab/test/sass/   @import "compass";"

I downgraded the version, upgraded, installed sass -rails && compass -rails, but no way, i'm fully blocked, I tried to reboot many times, i uninstalled, installed again & again, but nothing happen,

I haven't found any solution in internet, thanks to your comprehension,

**Comment by JamesVanWaza** [comment]
Hi @idkn, Please post the modules you are using as well as your `gruntfile.js`

**Comment by stabla** [comment]
modules I are using : W3CValidation, Swatch, Prtojects, Jslint Configurator, Jslint, Jhint, Javascript & CSS CDN Suggestions, Interactive Linter, HtmlHint, Extract for Brackets, Epic Linter, Emmet, CSSLint, ColorHints, BracketstoIX, Brackets SASS, Beautify, Autosave files on window blur, 

and I haven't grunt installed, did I need it ?

**Comment by JamesVanWaza** [comment]
Yes,  I use both grunt and compass, and it works, so you can try installing grunt. once that is done run `grunt watch` and see if the error shows up.

**Comment by stabla** [comment]
up,
I desactivated some plugins, and it seem to work, Brackets SASS (https://github.com/jasonanjose) seem to be in cause of my problem, 

@jgacuca567 but if you have others suggestions i take it

**Comment by JamesVanWaza** [comment]
Ok, If its working, then you should be good to go.

**Comment by stabla** [comment]
thanks for your help @jgacuca567

**Comment by iamsaifkhan** [comment]
i can't "IMPORT" @import compass/css3 in my website [Love Status](https://www.swaggiestatus.com/2018/04/love-status.html) css, i am trying to implement a "heart" Like button but @import compass/css3 isn't working. is their any link to import this function? 
https://www.swaggiestatus.com/2018/04/love-status.html this is the website in which i'm trying to import.
