### ISSUE TITLE
Why compass have 3 versions on Flebox?

### ISSUE THREAD

**Issue by davesnx** [Compass/compass#2058]
Hello guys,

I really appreciate the work that you'r doing, but I found a small issue related on Flexbox stuff, I tryed to read on the documentation.

That the mixin of [flexbox](https://github.com/Compass/compass/blob/d5df161d0df7edc686e576b22412f437dd0590cc/core/stylesheets/compass/css3/_flexbox.scss), why don't apply the 3 versions directly?

**Comment by cimmanon** [comment]
Duplicate of https://github.com/Compass/compass/issues/1427
