### ISSUE TITLE
Docs on how to create an inset box shadow are not clear.

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#206]
People keep asking me about it. Must be a docs bug. They expect the value to be true. Maybe we should support both values.

**Comment by joegaudet** [comment]
I would be one of those people, it's more so that the function description says default value is false, which implies that the positive value would be true.

**Comment by mirisuzanne** [comment]
We can easily support both by just accepting any non-null value. I can push a fix soon.

**Comment by chriseppstein** [comment]
Support true in addition to the inset keyword for the box-shadow mixin. Closed by 3a6481d2d505d83ca5dafdbb71cfab334e5216ca
