### ISSUE TITLE
Rails 5 No application integration exists for rails

### ISSUE THREAD

**Issue by edwardbako** [Compass/compass#2062]
I'm creating a new project and installing compas according to http://compass-style.org/install/
I've added `gem 'compass-rails'` to my `Gemfile`.

But when I run command `bundle exec compass init rails` 
`=> No application integration exists for rails`

How to come over this issue?

**Comment by alex-handley** [comment]
@edwardbako Are you still having this issue? Is it a new Rails app?

**Comment by bitsapien** [comment]
I'm using Rails 4.2.5.2, with Compass 1.0.3.I get the same error.

**Comment by alex-handley** [comment]
Hi Rahul, could you put an example app up please

**Comment by bitsapien** [comment]
After reading the [README.md](https://github.com/Compass/compass-rails/blob/master/README.md) for `compass-rails`, I realised I do not need to run that. Instead a `bundle exec compass create <project-name>` works. I think you should change this on http://compass-style.org/install/

**Comment by alex-handley** [comment]
Looks like this site is no longer running :( might be worth closing this issue as the project seems to be dead for now :speak_no_evil:

**Comment by m0ppun** [comment]
Remove `project_type = :rails` from your config file if you've written it.
