### ISSUE TITLE
compass-style.org is down?

### ISSUE THREAD

**Issue by scottyeck** [Compass/compass#2073]
Not sure how best to communicate this, so feel free to close if this isn't the appropriate place to do so.

Also this could just be a false alarm. Don't want to start a panic here.

**Comment by bferdinand** [comment]
Doesn't seem to be a false alarm. I am unable to get to the site as well.

**Comment by zachfeldman** [comment]
Me too

**Comment by jen4web** [comment]
Site has been down since yesterday at least. DNS issue.

**Comment by scottyeck** [comment]
Aaaand looks like it's back up! :tada: :tada: :tada:

**Comment by chriseppstein** [comment]
It turns out you have to pay your hosting service. >_<

**Comment by zachfeldman** [comment]
@chriseppstein unless you go with the ol' "Raspberry Pi in a basement and dyn-dns" model!! Hehe
