### ISSUE TITLE
Add Opera and IE9 support for gradients via SVG

### ISSUE THREAD

**Issue by alanhogan** [Compass/compass#208]
Given
- IE9 (as of the last beta I checked) supports _neither_ CSS3 gradients _nor_ `-ms-filter` gradients;
- Opera still lacks CSS3 gradients;
- Both Opera and IE9 allow SVGs to be used as backgrounds (and also support `data:` URIs); and
- Compass already includes a feature to “inline” and base64-encode images,

I think it would make sense for Compass to generate SVG gradients, base64 compress them, and set them as the background, for these browsers.

The SVG can be pretty simple. Here is a vertical gradient with one semi-opaque stop.

```
<?xml version="1.0" ?> 
<svg xmlns="http://www.w3.org/2000/svg"> 
 <defs>
  <linearGradient y2="1" x2="0.5" y1="0" x1="0.5" id="svg_gradient_2">
   <stop stop-color="#000000" offset="0"/>
   <stop stop-opacity="0.5" stop-color="#ffffff" offset="1"/>
  </linearGradient>
 </defs>
 <g>
      <rect id="svg_1" x="0" y="0" width="100%" height="100%" fill="url(#svg_gradient_2)"/>
 </g>
</svg>
```

**Comment by alanhogan** [comment]
Oh, and the SVG can be further compressed:

```
<svg xmlns="http://www.w3.org/2000/svg"> 
  <linearGradient y2="1" x2="0.5" y1="0" x1="0.5" id="svg_gradient_2">
   <stop stop-color="#000000" offset="0"/>
   <stop stop-opacity="0.5" stop-color="#ffffff" offset="1"/>
  </linearGradient>
  <rect id="svg_1" x="0" y="0" width="100%" height="100%" fill="url(#svg_gradient_2)"/>
</svg>
```

**Comment by alanhogan** [comment]
Added benefit: Gradients that actually rely on published non-draft web standards!

**Comment by alanhogan** [comment]
Related: This tool generates SVG and PNG fallbacks along with the traditional options. 

http://www.display-inline.fr/projects/css-gradient/#startType=rgba&extOpera=1&extIE=1

**Comment by chriseppstein** [comment]
I think this makes sense as an opt-in feature. Anyone want to try their hand at a patch?

**Comment by chriseppstein** [comment]
related: #183

**Comment by dira** [comment]
I wrote opt-in support for linear gradients, but I got stuck when adding a new stylesheet for testing it, as it makes integration tests fail.

I am quite puzzled by this and could not figure out why it happens, so I posted details on the mailing list, hoping that somebody can help me fix that. :D

**Comment by dira** [comment]
Sent a pull request for SVG support.

**Comment by alanhogan** [comment]
Dira, you give me great hope! Cool `8-)`

**Comment by dira** [comment]
:)

You can see the result here: http://dira.ro/code/CSS3-gradients/. Works in Webkit, Firefox, Opera, IE9beta

**Comment by alanhogan** [comment]
Pretty comprehensive demo page, Irina… I like it and can’t wait for your patch to make it into the gem.

**Comment by chriseppstein** [comment]
it's on the css3-v2 branch now and will land on master shortly.

**Comment by jitendravyas** [comment]
How to get gradient for IE 7 and 8?

**Comment by chriseppstein** [comment]
Use the filter-gradient mixin.

**Comment by jitendravyas** [comment]
OK and for IE9 this new plugin http://compass-style.org/reference/compass/css3/images/ is generating SVG but to use filter-gradient with svg we will have to set filter:none for IE9.

is there a quick way to do that?

**Comment by chriseppstein** [comment]
Existing CSS techniques apply, or you can make your own version of filter-gradient.

**Comment by jitendravyas** [comment]
background: url(data:image/svg+xml;base64,PD9morecode /\* IE9 _/;
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#1e5799', endColorstr='#7db9e8',GradientType=0 ); /_ IE6-8 */

/\* IE9 SVG, needs conditional override of 'filter' to 'none' */

Is there a way to replace filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#1e5799', endColorstr='#7db9e8',GradientType=0 ) to  filter: none; for IE9 only
