### ISSUE TITLE
@charset breaks Safari if it isn't the first line of the file

### ISSUE THREAD

**Issue by joshjhall** [Compass/compass#211]
I ran into this while testing the upgrade path to 0.10.6.  The standard reset now includes an @charset "UTF-8"; at the end of the reset.  Apparently, the @charset must be the first line of the file to be standards compliant.  More importantly, this will break other styles in Safari if it is not the first line.

From what I can tell, any styles applied to the body element (including classes, but not ids) will fail.  For instance, I reset everything to a standard font in the body tag.  These are ignored.

I suggest including an option in the settings for the @charset rather than including it in the reset.  That way the compiled CSS is ensured to have the @charset in the right place and only show up once (I can't imagine using reset more than once, but I suppose one could do that).

I'd provide a patch, but I'm honestly not sure how to go about accomplishing this.  In the meantime, I'll stick to 0.10.5.

**Comment by chriseppstein** [comment]
This is a combination of bugs in Sass and Webkit. [Read more](http://groups.google.com/group/compass-users/browse_thread/thread/eea0d22274b6e880)

I think you should be able to work around it for now. I'll see what can be done in Sass.

**Comment by joshjhall** [comment]
After a bit of experimenting, I found it's actually just ignoring the very next style.  So, a work-around for the moment (and this is a total hack) is to create an empty style tag right after the @charset declaration.  Something like this will correct the issue in Safari (and hopefully not cause problems elsewhere, I haven't tested IE yet).

@charset "UTF-8";
a{}
style { ...

**Comment by chriseppstein** [comment]
Nathan is going to try to get a fix for this into Sass this weekend.

**Comment by chriseppstein** [comment]
Fixed in Haml 3.0.23. The charset will be on the first line now irrespective of where it is imported. See the [changelog](http://sass-lang.com/docs/yardoc/file.SASS_CHANGELOG.html) for more details.

**Comment by jf** [comment]
Chris, I assume you mean in _Sass_ 3.0.23...

Edit: ok, nvm. I guess the _haml_ gem provides sass, argh...

**Comment by chriseppstein** [comment]
Sass is in a gem named "haml"
