### ISSUE TITLE
Link to http://compass.handlino.com/ leads to name not resolved DNS error

### ISSUE THREAD

**Issue by macbikegeek** [Compass/compass#2121]
On Page: http://compass-style.org/

I was looking for:
http://compass.handlino.com/

But instead I found:
This site can’t be reached

compass.handlino.com’s server DNS address could not be found.
Go to http://handlino.com/
Search Google for compass handlino
ERR_NAME_NOT_RESOLVED

http://handlino.com/ also could not be reached

**Comment by amrelkerm** [comment]
hello can we connected together I don't know your page on facebook but this link my page on facebook  https://www.facebook.com/profile.php?id=100020376695941 please I wait your  message 
thank you
