### ISSUE TITLE
Documentation: compass grid-img: What's "W+GxH"?

### ISSUE THREAD

**Issue by tmaier** [Compass/compass#213]
For some obvious, for beginners not

compass grid-img is not documented at http://compass-style.org/docs/tutorials/command-line/

compass grid-img W+GxH

Where:
W = Column Width
G = Gutter Width
H = Row Height

The best would be, if you could link this values in the documentation to the variables
referenced at http://compass-style.org/docs/reference/blueprint/grid/#mixin-column-base-sass

**Comment by chriseppstein** [comment]
Better docs on the grid image command.
Closed by 99a95e25e028f5ba28f567944266e7b139976c93.
