### ISSUE TITLE
Hand over project to Community

### ISSUE THREAD

**Issue by donatj** [Compass/compass#2153]
Compass may have ceased development, but it is still in use by thousands and thousands of developers. Rather than staying shut down, why not give the project over to its community?

**Comment by scottdavis** [comment]
I don't think anyone on the past team would have an issue with that if someone wants to step up as a maintainer. However, Compass is based on ruby sass which is also not the preferred sass interpreter these days. So I welcome anyone that wants to set up as a maintainer.

**Comment by donatj** [comment]
I've long since stopped using Compass. Closing.
