### ISSUE TITLE
Invalid US-ASCII character 😡

### ISSUE THREAD

**Issue by bade3** [Compass/compass#2163]
"error scss/base.scss (Line 622 of scss/_base/_fnkeelat.scss: Invalid US-ASCII character "\xD9")"

"
&:after {
👉 content: "وضع الفن"
}
"

wt1 🤬

**Comment by lora-palmer** [comment]
can u learn me HTML ?

**Comment by lora-palmer** [comment]
?

**Comment by lora-palmer** [comment]
!
