### ISSUE TITLE
[CSS3/version-2] box-shadow irgnores default values

### ISSUE THREAD

**Issue by mathiasschopmans** [Compass/compass#222]
`+box-shadow(#f00)` produces:

```
-moz-box-shadow: red;
-webkit-box-shadow: red;
-o-box-shadow: red;
box-shadow: red;
```

**Comment by chriseppstein** [comment]
that's how sass works colors go in, colors come out. Result is the same.

Thanks for the report.

**Comment by mathiasschopmans** [comment]
hmn. maybe i get it wrong. is there no support for default values in the new +box-shadow? :'(

test suite:

-sass

```
$default-box-shadow-color: x666
$default-box-shadow-h-offset: 1px
$default-box-shadow-v-offset: 1px
$default-box-shadow-blur: 10px
$default-box-shadow-spread : false
$default-box-shadow-inset : false

.box-shadow-default
  //everything ok
  +box-shadow()


.box-shadow-one-param
  //oh oh. where are the default values?
  +box-shadow(x333)


.single-box-shadow-one-param
  //sweet
  +single-box-shadow(x333)


.multiple-box-shadow-one-param
  //sour
  +box-shadow(x333,x333)


.box-shadow-all-params
  //single-box-shadow param order.
  //$color, $hoff, $voff, $blur, $spread, $inset
  +box-shadow(x333 3px 3px 3px 3px false)


.box-shadow-switched-order
  +box-shadow(1px 1px 10px x666)
```

-compiled css

```
@charset "UTF-8";
/*
 * 11/2010 mathias schopmans
 * styles compiled by sass / compass
 *
 */
.box-shadow-default {
  -moz-box-shadow: 1px 1px 10px x666666;
  -webkit-box-shadow: 1px 1px 10px x666666;
  -o-box-shadow: 1px 1px 10px x666666;
  box-shadow: 1px 1px 10px x666666;
}

.box-shadow-one-param {
  -moz-box-shadow: x333333;
  -webkit-box-shadow: x333333;
  -o-box-shadow: x333333;
  box-shadow: x333333;
}

.single-box-shadow-one-param {
  -moz-box-shadow: 1px 1px 10px x333333;
  -webkit-box-shadow: 1px 1px 10px x333333;
  -o-box-shadow: 1px 1px 10px x333333;
  box-shadow: 1px 1px 10px x333333;
}

.multiple-box-shadow-one-param {
  -moz-box-shadow: x333333, x333333;
  -webkit-box-shadow: x333333, x333333;
  -o-box-shadow: x333333, x333333;
  box-shadow: x333333, x333333;
}

.box-shadow-all-params {
  -moz-box-shadow: x333333 3px 3px 3px 3px false;
  -webkit-box-shadow: x333333 3px 3px 3px 3px false;
  -o-box-shadow: x333333 3px 3px 3px 3px false;
  box-shadow: x333333 3px 3px 3px 3px false;
}

.box-shadow-switched-order {
  -moz-box-shadow: 1px 1px 10px x666666;
  -webkit-box-shadow: 1px 1px 10px x666666;
  -o-box-shadow: 1px 1px 10px x666666;
  box-shadow: 1px 1px 10px x666666;
}
```

replace `x` with `#`

**Comment by mirisuzanne** [comment]
This is a bug worth noting, as it is a major change from the former bo-shadow mixin. Is it a change we want?

previously `+box-shadow(#f00)` would have returned:

```
-moz-box-shadow: red $default-h-off $default-v-off $default-blur $default-spread;
etc...
```

In other words: you were able to override one default without overriding all of them. That's a handy feature. I use it quite a bit to change the color of shadows while keeping the light source consistent.

**Comment by mathiasschopmans** [comment]
sadly only `single-box-shadow` do it the old way.

maybe it would be an option to "route" `box-shadow` to `single-box-shadow` instead of `multiple-box-shadow` for better migration.

**Comment by chriseppstein** [comment]
Sorry I misread the report. I did willfully discard the defaults. I want the most low-level compass mixins to do as little as they must to ensure cross-browser compatibility. I am not sure how much it makes sense to apply the defaults to every shadow that is passed, or just to the first one, etc. The `single-box-shadow` mixin still has the default value behavior you're expecting.

Thoughts?

**Comment by chriseppstein** [comment]
@mathiasschopmans There's a reason this module is versioned. it is not backwards compatible with the old version -- the release notes and upgrade page should make it clear what changes are needed. I'm happy to update those docs, but IMO the new behavior is the most correct behavior for a "fundamental building block". We can add other mixins that do more.

**Comment by mirisuzanne** [comment]
It makes sense to me that defaults can/should be set on a project level. It would be quite simple to make a wrapper mixin to handle that as needed.

Should we make sure we are consistent with that across the other css3 mixins?

**Comment by mathiasschopmans** [comment]
okay. so i can reroute `box-shadow` to the "old" version in all my projects and use `multiple-box-shadow` only if needed?!

```
=box-shadow($c:$default-box-shadow-color, $h:$default-box-shadow-h-offset, $v:$default-box-shadow-v-offset, $b:$default-box-shadow-blur, $s:$default-box-shadow-spread, $i:$default-box-shadow-inset)
  +single-box-shadow($c, $h, $v, $b, $s, $i)
```

**Comment by chriseppstein** [comment]
@ericam, yes I'd like this philosophy to be consistent across the css3 API:
1. Lowest level mixins don't transform the argument more than they must.
2. Lowest level mixins take space delimited args and comma delimited args that match their css3 standard counterpart properties.
3. Value add mixins can be built on top of these and might be in the compass core or other projects might deliver patterns built on top of these.

As always, I see compass as the minimum amount of stuff to enable the CSS extension ecosystem, not as a single comprehensive solution to styling.

**Comment by chriseppstein** [comment]
@mathias

http://beta.compass-style.org/docs/tutorials/upgrading/css3-v2/

That upgrade guide suggests that you just change your usage of `box-shadow` to be includes of `single-box-shadow`. If you overwrite it, you'll open yourself up to import order issues that will be more hassle than it's worth.

**Comment by mathiasschopmans** [comment]
thank god - there is CMD + F  ;)

thank you chris!

**Comment by chriseppstein** [comment]
Of note, users who do not change their @imports get a deprecation warning with a link to this guide. Mathias, did you see that link and ignore it?

**Comment by mathiasschopmans** [comment]
I've never seen a deprecation warning in the shell.

**Comment by chriseppstein** [comment]
@mathias Then how did you know to change your imports?

**Comment by mathiasschopmans** [comment]
https://github.com/chriseppstein/compass/tree/css3-v2/frameworks/compass/stylesheets/compass/css3

```
    //_mixins.sass
    @import "compass"
    @import "compass/css3/version-2"
```
