### ISSUE TITLE
compass master + haml-edge

### ISSUE THREAD

**Issue by slbug** [Compass/compass#225]
Please make it possible to use compass master and haml 3.1.alpha. atm it gives error while doing bundle install.

<pre>
Bundler could not find compatible versions for gem "haml":
  In Gemfile:
    compass depends on
      haml (~> 3.0.23)

    haml (3.1.0.alpha.0)
</pre>

**Comment by agibralter** [comment]
Also, isn't Sass a separate gem now? Could Compass just depend on the Sass gem?

**Comment by chriseppstein** [comment]
Compass master now requires sass 3.1.
