### ISSUE TITLE
Error when installing CSS3 Pie with 0.11.alpha

### ISSUE THREAD

**Issue by lmartins** [Compass/compass#226]
When i try to install this new module i get the following error:

Errno::ENOENT on line 144 of /Library/Ruby/Gems/1.8/gems/compass-0.11.alpha.0/lib/compass/installers/manifest.rb: No such file or directory - /Library/Ruby/Gems/1.8/gems/compass-0.11.alpha.0/frameworks/compass/templates/pie/manifest.rb
  /Library/Ruby/Gems/1.8/gems/compass-0.11.alpha.0/lib/compass/installers/manifest.rb:144:in `open'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.alpha.0/lib/compass/installers/manifest.rb:144:in`parse'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.alpha.0/lib/compass/installers/manifest.rb:135:in `with_manifest'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.alpha.0/lib/compass/installers/manifest.rb:143:in`parse'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.alpha.0/lib/compass/installers/manifest.rb:20:in `initialize'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.alpha.0/lib/compass/installers/manifest_installer.rb:10:in`new'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.alpha.0/lib/compass/installers/manifest_installer.rb:10:in `initialize'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.alpha.0/lib/compass/app_integration/stand_alone.rb:12:in`new'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.alpha.0/lib/compass/app_integration/stand_alone.rb:12:in `installer'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.alpha.0/lib/compass/commands/installer_command.rb:23:in`installer'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.alpha.0/lib/compass/commands/installer_command.rb:12:in `configure!'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.alpha.0/lib/compass/commands/project_base.rb:15:in`initialize'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.alpha.0/lib/compass/commands/stamp_pattern.rb:69:in `initialize'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.alpha.0/lib/compass/exec/sub_command_ui.rb:38:in`new'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.alpha.0/lib/compass/exec/sub_command_ui.rb:38:in `perform!'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.alpha.0/lib/compass/exec/sub_command_ui.rb:15:in`run!'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.alpha.0/bin/compass:26
  /usr/bin/compass:19:in `load'
  /usr/bin/compass:19

**Comment by chriseppstein** [comment]
Sorry. The beta docs are actually ahead of the current alpha release. You need to install from master or wait to use this feature.

**Comment by chriseppstein** [comment]
https://rubygems.org/gems/compass/versions/0.11.alpha.1
