### ISSUE TITLE
problems on beta.compass-style.org

### ISSUE THREAD

**Issue by slbug** [Compass/compass#228]
JS alert almost on all pages:

<pre>
SyntaxHighlighter

Can't find brush for: sass
</pre>

**Comment by imathis** [comment]
Thanks for the report, it should be fixed now.

**Comment by slbug** [comment]
still have same issue. for example here - http://beta.compass-style.org/reference/compass/css3/gradient/

**Comment by imathis** [comment]
Give it a hard refresh, it is fixed you may just have cached assets.
