### ISSUE TITLE
Blueprint 1.0 port buggy in Safari

### ISSUE THREAD

**Issue by tomstuart** [Compass/compass#230]
Something about the Compass 0.11.alpha.1 port of Blueprint 1.0 is causing odd behaviour in Safari, while the real Blueprint 1.0 is fine. I haven't tried any earlier versions of Compass so I don't know whether this issue predates 0.11.

For example:

```
<!doctype html>

<html>
  <head>
    <link href="stylesheets/screen.css" media="screen, projection" rel="stylesheet" type="text/css">
    <link href="stylesheets/print.css" media="print" rel="stylesheet" type="text/css">
    <!--[if IE]>
      <link href="stylesheets/ie.css" media="screen, projection" rel="stylesheet" type="text/css">
    <![endif]-->
    <style type="text/css">
      a {
        color: green;
      }
    </style>
  </head>

  <body>
    <p><a href="an-unvisited-page">Unvisited link</a>. <a href="http://compass-style.org/">Visited link</a>.</p>
  </body>
</html>
```

With real Blueprint 1.0, both "Unvisited link" and "Visited link" appear in green as intended. With the Compass 0.11.alpha.1 port (blueprint/basic), "Visited link" is still #004c99 (i.e. $link-visited-color) in Safari 5.0.3, although it's green in Chrome.

Perhaps this is ultimately Safari's fault rather than Compass's, but either way the real Blueprint 1.0 is successfully working around the problem, so is it possible for the Compass Blueprint port to have the same behaviour?

**Comment by chriseppstein** [comment]
Thanks for the report and for testing the alpha release.

I cannot tell from this report what is broken. What value in your css were you expecting and what value did you get? What Sass code did you write, etc. What steps did you take to get to this issue. Thanks in advance for the additional information.

**Comment by tomstuart** [comment]
Sorry, I'll try to be clearer.

The above page is a minimal, static HTML test case that doesn't involve writing any Sass. What's broken is the rendering behaviour in Safari, not any values in the generated files.

What I'm saying is: the screen.css, print.css and ie.css files which are generated out of the box by Compass 0.11.alpha.1's blueprint/basic pattern (i.e. what you get from `compass create myproject --using blueprint/basic`) produce a different rendering behaviour in Safari than the screen.css, print.css and ie.css which come with Blueprint 1.0. I assume the intention of Compass's Blueprint port is to reproduce the behaviour of Blueprint, which is why I'm reporting this difference in rendering behaviour as an issue.

If you generate a project with blueprint/basic, drop the above HTML file into it and open it in Safari 5.0.3, you'll see "Unvisited link" in green and "Visited link" in the Blueprint default visited link colour (assuming your browser has visited compass-style.org!), which is unexpected behaviour. If you replace the Compass-generated screen.css, print.css and ie.css files with the real Blueprint screen.css, print.css and ie.css files, "Visited link" renders in green as expected.

Since Chrome doesn't exhibit the difference in behaviour, it may well be due to some quirk in Safari's CSS or rendering implemention, so it's not necessarily an actual bug in Compass, but it'd be really great if Compass could match Blueprint as much as possible.

**Comment by tomstuart** [comment]
Having briefly investigated this, it looks like the difference is due to the Compass Blueprint port setting an explicit colour for `a:visited` (and `:active`), which Blueprint doesn't do.

On Safari this makes it hard to set a different colour for links, since a rule like `#foo a { color: green; }` will make `#foo`'s links green unless they're visited, in which case they continue to show up in the (now inconsistent) `a:visited` colour provided by the Blueprint port. Chrome doesn't exhibit this behaviour so I don't know which browser is "in the wrong".

Is this just something Compass users have to live with? It took me by surprise as someone who's trying to migrate a Blueprint site to Compass -- I'd assumed the port would be a fully compatible replacement.

**Comment by chriseppstein** [comment]
This is an area where Compass differs from Blueprint. It's an incredibly bad idea to not specify colors for each link state. Compass provides a simple mixin that let's you specify all the link-colors. I suggest you use that to set [link colors](http://beta.compass-style.org/reference/compass/utilities/links/link_colors/#mixin-link-colors). If you want to control the default color for links, the easiest way to do this is to customize the [link color variables](http://beta.compass-style.org/reference/blueprint/colors/).
