### ISSUE TITLE
Compass stops auto-compiling in rails

### ISSUE THREAD

**Issue by tmancino** [Compass/compass#233]
<cross posted to mailing list>
I had to clone my repo after blowing away the app directory, now compass will not autocompile, but the compass command works as expected. Is this expected behavior? I tried compass init rails, but and --force but nothing seems to work. Thanks....

**Comment by chriseppstein** [comment]
google groups thread indicates this issue is resolved: http://groups.google.com/group/compass-users/browse_thread/thread/351706df2685d2d

I don't know of any thing I can do on my end -- closing.
