### ISSUE TITLE
FSSM ain't happy with something

### ISSUE THREAD

**Issue by imathis** [Compass/compass#236]
On the compass docs when I reun ./bin/compass watch from /doc-src
I get this:

> > > Compass is watching for changes. Press Ctrl-C to Stop.
> > > FSSM::FileNotFoundError on line 84 of /Users/bmathis/.rvm/gems/ruby-1.8.7-p302@compass/gems/sass-3.1.0.alpha.50/vendor/fssm/lib/fssm/path.rb: No such file or directory - 
> > > Run with --trace to see the full backtrace

Same setup works fine with older versions.

**Comment by chriseppstein** [comment]
I'll upgrade compass to fssm 0.2, but sass shouldn't force it's version unless the Sass CLI is being used.

**Comment by chriseppstein** [comment]
this is fixed now.
