### ISSUE TITLE
ChunkyPNG throws an error when using the $<map>-position variable

### ISSUE THREAD

**Issue by doctyper** [Compass/compass#238]
Using Compass (0.11.alpha.4, 0.10.6)

I _believe_ I have this narrowed down, but I could be wrong. This is the error I get:

`ChunkyPNG::OutOfBounds on line 233 of /Library/Ruby/Gems/1.8/gems/chunky_png-0.10.4/lib/chunky_png/canvas/operations.rb: Background image width is too small!`

The error occurs when I have a sprite map of two or more equal-dimension sprites. For my test case they were 38x38. Even adding a position of 1px threw the error. I think it appears when the area of the image + position exceeds the bounds of the original sprite map. But don't quote me on that.

Test case here: https://gist.github.com/737049

Incidentally, I still receive this error regardless of whether or not oily_png is installed. I'm not sure if Compass is detecting its presence.

**Comment by chriseppstein** [comment]
fixed by 638fd8f54326e8ddb5e1a917b6a22f48c8b664a4

**Comment by chriseppstein** [comment]
thanks for the great bug report.
