### ISSUE TITLE
LoadError on line ["29"] of <internal: no such file to load -- lemonade

### ISSUE THREAD

**Issue by flippingbits** [Compass/compass#239]
It seems that you make usage of lemonade but didn't add it as a dependency to compass.

I'm getting the following error:
    LoadError on line ["29"] of <internal: no such file to load -- lemonade
when using compass 0.10.6 with Ruby 1.9.2 and running
    compass watch

It'd be cool, if you could add lemonade as a dependency to compass.

Regards

**Comment by chriseppstein** [comment]
Compass does not require lemonade. Never has and never will. However in the v0.11 release, the lemonade functionality has merged into compass. If something is requiring 'lemonade', I suggest you grep your project and plugins.
