### ISSUE TITLE
0.10.6 rails installer not putting public directories in right place?

### ISSUE THREAD

**Issue by scottdavis** [Compass/compass#240]
<pre>
138:recipe_box sdavis$ bundle exec compass init rails
directory src/
<b>directory stylesheets/</b>
   exists config/initializers
identical config/initializers/compass.rb
  convert screen.sass
   create src/screen.scss
  convert print.sass
   create src/print.scss
  convert ie.sass
   create src/ie.scss

Congratulations! Your rails project has been configured to use Compass.
Just one more thing left to do: Register the compass gem.

</pre>

Isn't the stylesheet directory suppose to be in public?

I verified that its working perfectly in 0.10.0
If im wrong yell at me in all caps

**Comment by chriseppstein** [comment]
It works for me: [Gist](https://gist.github.com/b109cdc04897b1a72d9e).

Are you sure you don't have a compass config file already?

**Comment by scottdavis** [comment]
i think the difference is i did a `bundle exec compass init rails` it was in a clean rails app so that seems to be the only difference

**Comment by chriseppstein** [comment]
when I tried it that way it works too. Not sure what I can do here...

**Comment by scottdavis** [comment]
yea its working now i think im just a retard
