### ISSUE TITLE
Sprite command causes undefined method `declare' for Sass::Script::Functions:Module

### ISSUE THREAD

**Issue by billsaysthis** [Compass/compass#243]
On OSX 10.6.5, ruby 1.9.2-p0, rails 3.0.3:

tester1: compass sprite "public/images/*.png"
/Users/billlazar/.rvm/gems/ruby-1.9.2-head/gems/compass-0.11.alpha.4/lib/compass/sass_extensions/functions/urls.rb:21:in `<module:Urls>': undefined method`declare' for Sass::Script::Functions:Module (NoMethodError)
    from /Users/billlazar/.rvm/gems/ruby-1.9.2-head/gems/compass-0.11.alpha.4/lib/compass/sass_extensions/functions/urls.rb:1:in `<top (required)>'
    from /Users/billlazar/.rvm/gems/ruby-1.9.2-head/gems/compass-0.11.alpha.4/lib/compass/sass_extensions/functions.rb:9:in`require'
    from /Users/billlazar/.rvm/gems/ruby-1.9.2-head/gems/compass-0.11.alpha.4/lib/compass/sass_extensions/functions.rb:9:in `block in <top (required)>'
    from /Users/billlazar/.rvm/gems/ruby-1.9.2-head/gems/compass-0.11.alpha.4/lib/compass/sass_extensions/functions.rb:5:in`each'
    from /Users/billlazar/.rvm/gems/ruby-1.9.2-head/gems/compass-0.11.alpha.4/lib/compass/sass_extensions/functions.rb:5:in `<top (required)>'
    from /Users/billlazar/.rvm/gems/ruby-1.9.2-head/gems/compass-0.11.alpha.4/lib/compass/sass_extensions.rb:4:in`require'
    from /Users/billlazar/.rvm/gems/ruby-1.9.2-head/gems/compass-0.11.alpha.4/lib/compass/sass_extensions.rb:4:in `<top (required)>'
    from /Users/billlazar/.rvm/gems/ruby-1.9.2-head/gems/compass-0.11.alpha.4/lib/compass.rb:5:in`require'
    from /Users/billlazar/.rvm/gems/ruby-1.9.2-head/gems/compass-0.11.alpha.4/lib/compass.rb:5:in `block in <top (required)>'
    from /Users/billlazar/.rvm/gems/ruby-1.9.2-head/gems/compass-0.11.alpha.4/lib/compass.rb:4:in`each'
    from /Users/billlazar/.rvm/gems/ruby-1.9.2-head/gems/compass-0.11.alpha.4/lib/compass.rb:4:in `<top (required)>'
    from /Users/billlazar/.rvm/gems/ruby-1.9.2-head/gems/compass-0.11.alpha.4/bin/compass:20:in`require'
    from /Users/billlazar/.rvm/gems/ruby-1.9.2-head/gems/compass-0.11.alpha.4/bin/compass:20:in `block in <top (required)>'
    from /Users/billlazar/.rvm/gems/ruby-1.9.2-head/gems/compass-0.11.alpha.4/bin/compass:8:in`fallback_load_path'
    from /Users/billlazar/.rvm/gems/ruby-1.9.2-head/gems/compass-0.11.alpha.4/bin/compass:19:in `<top (required)>'
    from /Users/billlazar/.rvm/gems/ruby-1.9.2-head/bin/compass:19:in`load'
    from /Users/billlazar/.rvm/gems/ruby-1.9.2-head/bin/compass:19:in `<main>'

**Comment by billsaysthis** [comment]
tester1: gem list compass 

**\* LOCAL GEMS ***

compass (0.11.alpha.4)

**Comment by chriseppstein** [comment]
Upgrading sass should clear up the issue.

**Comment by billsaysthis** [comment]
I already have latest SASS as best I know:

tester1: gem list sass                       

**\* LOCAL GEMS ***

sass (3.1.0.alpha.206)
tester1: gem install sass --pre
Successfully installed sass-3.1.0.alpha.206
1 gem installed
tester1: gem list sass         

**\* LOCAL GEMS ***

sass (3.1.0.alpha.206)

**Comment by chriseppstein** [comment]
did you get things working yet?

**Comment by billsaysthis** [comment]
Yes, you were right about HAML version needed. Still, can't get image_height, per my mail to the group list. Seems like passing a string name/path is erroring on RealPath method call.

**Comment by chriseppstein** [comment]
I'll send you a reply to that on the mailing list.

**Comment by timothyklim** [comment]
Hi! My Gemfile has same gems

<pre><code>gem 'sass', '>= 3.1.0.alpha.50'
gem 'haml-edge'
gem 'haml-rails'
gem 'compass', git: "git://github.com/chriseppstein/compass.git"
...
% gem list|ack sass
sass (3.1.0.alpha.214)
</code></pre>

and I'm got same error:

<pre><code>/Users/timothyklim/.rvm/gems/ruby-1.9.2-p136/bundler/gems/compass-8519a66a024e/lib/compass/sass_extensions/functions/urls.rb:21:in `<module:Urls>': undefined method `declare' for Sass::Script::Functions:Module (NoMethodError)</code></pre>

I use ruby-1.9.2-p136, rails-3.0.3 on OS X 10.6.6.

**Comment by jhilden** [comment]
I had the same error and this fixed it for me:

```
gem 'haml', '>= 3.1.alpha.214'
```

**Comment by chriseppstein** [comment]
You should change haml-edge to:

```
gem "haml", ">= 3.1.alpha.50"
```

And then run:

```
bundle update haml
```

**Comment by timothyklim** [comment]
@jhilden, @chriseppstein It works! Thanks.
