### ISSUE TITLE
v0.11 issue when using $<map>-position 

### ISSUE THREAD

**Issue by danjessen** [Compass/compass#247]
this is using the "new" Spriting with Compass and calling 
+<map>-sprite(name-of-image)
i set the position for the map to 100%
expected output should be:
background-position: 100% -xxpx;
but i get
background-position: 0 -xxpx;

**Comment by danjessen** [comment]
meh comments don't allow the map tag, but i hope you get the point :)

**Comment by hagenburger** [comment]
There are two different 100% positions for sprites:
1. the position in the sprite map
2. the CSS background position

Pleas have a look at [the spriting documentation](http://beta.compass-style.org/help/tutorials/spriting/) or this [visual guide to spriting](http://www.hagenburger.net/TMP/compass-sprites-position.png).

I hope, this answers the question.
