### ISSUE TITLE
Sprite hover selectors

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#248]
generate a :hover selector if filename ends in _hover.

**Comment by imathis** [comment]
I like this. Also, I wonder if _active -> :active while you're at it.

**Comment by chriseppstein** [comment]
any other states? :target ?

**Comment by imathis** [comment]
Seems like :target is sensible. I don't have a full list of interactive pseudo selectors, but I think those are probably it.

**Comment by scottdavis** [comment]
added search methods to the sprite base class for checking if these exist
http://rdoc.info/github/chriseppstein/compass/dda7c9/Compass/SassExtensions/Sprites/Image

**Comment by scottdavis** [comment]
9962a37b2ed6150ccb56e56521cceddd96a55f61
