### ISSUE TITLE
disable sprite folder prefix in selectors

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#249]
Add an option to be able to take off the sprite folder prefix in sprite selectors.

**Comment by scottdavis** [comment]
can you give an example im not 100% sure what you mean

**Comment by scottdavis** [comment]
get me a use/test case and ill get this into 0.13

**Comment by scottdavis** [comment]
i think this is possible by setting `$<%= name %>-sprite-base-class`

**Comment by chriseppstein** [comment]
I don't know what I meant either.

**Comment by rds** [comment]
This was actually a good idea – currently `@include all-icons-sprites` prefixes all the classes with `icons-`, it would be nice to have the option to remove the prefix completely so you can do `class="add icon"` instead of `class="icons-add icon"`.

**Comment by friedhelm-langhof** [comment]
+1

**Comment by rds** [comment]
I've modified the sprite importer template to utilise `$sprite-name-prefix` with an example. https://gist.github.com/rds/3766814

**Comment by scottdavis** [comment]
feel like turning it into a pull request?

**Comment by hagenburger** [comment]
+1

**Comment by materliu** [comment]
+1

**Comment by amelnikova-cn** [comment]
+1
