### ISSUE TITLE
css3 grid background

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#250]
Use Divya's fancy grid maker.

**Comment by nimbupani** [comment]
WOOT. Result: http://dl.dropbox.com/u/952/compass-grid/index.html

Mixin: https://gist.github.com/763090

**Comment by mirisuzanne** [comment]
've been working on a fluid version of this for Susy, but have run into a Sass list parsing problem:

https://gist.github.com/783336

Mine doesn't currently take arguments, but that's an easy change once the concept is working.

**Comment by chriseppstein** [comment]
Ok. This changeset fixes the compass issue that was preventing the generation of the gradient you've got there: 727c025881a380879f3b327d30dbd689e8909d61

But I couldn't make it work in a browser, chrome was complaining about the gradient that was generated and not saying why.

**Comment by chriseppstein** [comment]
Here's an updated gist: https://gist.github.com/899769

**Comment by mirisuzanne** [comment]
There are some choices to make before I finish this up.

The problem you were having with chrome stems from sending non-percentage-based color-stops to the old webkit syntax. 

One solution to that is the same solution that I need for this to work with susy: convert everything to percentages. That makes it all a bit less pixel-perfect for people using fixed or elastic grids, but it works everywhere on any type of grid. I have that built and ready to go.

The other solution involves the fact that we need to update our gradient mixin. Newer versions of webkit will accept the mozilla gradient syntax, along with non-percentage units. If the -webkit- output from compass included the new syntax, it would work to leave the units as declared.

In that second case we could possibly separate things out and support BOTH newer browsers with any units AND older browsers with percentage-based units.

Here's what I have working with our current gradient module: https://gist.github.com/902815

**Comment by mirisuzanne** [comment]
(also, not clear why this isn't working in opera yet. more testing needed.)

**Comment by mirisuzanne** [comment]
(oh, only opera beta supports gradients. also fixed a silly width declaration in my sample.)

**Comment by nimbupani** [comment]
The generated CSS does work in Opera tho! :/ 

http://jsfiddle.net/nimbu/PX6aM/ (or am I missing smthing?)

**Comment by mirisuzanne** [comment]
I was the one missing something, as noted above. It works great if your on the Opera Beta.

**Comment by chriseppstein** [comment]
Where are we with this? Once I patch compass to support the new webkit gradients are we done? If so, let's turn this into a pull request and do a final code review.

**Comment by mirisuzanne** [comment]
my computer died, and it will take me a bit to get up and running on a new one. that's where I am. I can come back to this in a day or two, I hope. 

Do we have a preference between always using percentages in the output (as it's written now) vs using whatever units we are passed (I need to make some adjustments)? I assume the latter, in which case it's not quite ready to go, but I'll send a pull request as soon as it is.

**Comment by mirisuzanne** [comment]
Pushed: e66c822503d32d9b4e87a1fb0ccfec35dedda983

This may need some internal adjustments once $experimental-support-for-legacy-webkit is in place, but it shouldn't change the use at all.

@nimbupani, I went with multiple-backgrounds over generated-content because I didn't see any browsers supporting gradients without also supporting multiple-backgrounds.

@chriseppstein, also note the line comment @ #L5R59. I think my workaround is reasonably solid, if you don't want to address another edge-case for this.

**Comment by chriseppstein** [comment]
72434be1375ecce208eee90796f3b99a4ad40485 adds support for webkit's standardized css3 gradients.

**Comment by chriseppstein** [comment]
Did a little cleanup: 8a8d625a7de5060a0664e1c2660573469544c6c4 and 0a33bc14b2d6b6f2a30e671e2b6fbbb4d54bac20

**Comment by chriseppstein** [comment]
Will inform users who generate grid background about this feature: 26fe7f1074927103e77eadd3819e465b8fa83335

**Comment by chriseppstein** [comment]
Default the blueprint grid background to the this implementation: 196abb2a2817f4fb375bb45ea618cda0b6d2aef0

**Comment by chriseppstein** [comment]
I think that does it. Great work everyone!

**Comment by mirisuzanne** [comment]
Fantastic! Well played, kids [sic]. Howz about a version bump to spread all that love?

@nimbupani thanks for being brilliant. what next? :)

**Comment by chriseppstein** [comment]
v0.11.beta.7 is out: https://twitter.com/#!/chriseppstein/status/59172334820528128

**Comment by mirisuzanne** [comment]
```
error sass/screen.sass (Line 69: Color stops must be specified in increasing order. 91.8918918918919 came after 91.8918918918919.)
```

**Comment by chriseppstein** [comment]
@ericam please provide steps to reproduce in a new bug.

**Comment by nimbupani** [comment]
WOOT I shall test!
