### ISSUE TITLE
sass 3.1.0.alpha.217 breaks support for browser prefixes

### ISSUE THREAD

**Issue by mirisuzanne** [Compass/compass#252]
+background-image(linear-gradient(...)) outputs only the official syntax, and +background-size(...) outputs nothing at all. Those were the two I tested. Downgrading sass to v. 3.1.0.alpha.216 fixes the problem.

If this is actually a sass problem let me know and I'll post it over there.

**Comment by chriseppstein** [comment]
Yes. it's a sass bug. I traced it to this commit: https://github.com/nex3/sass/commit/947e8cfc6bc31a7f39933a5d4035f6da75dcb5d1

It causes the `@if` directive to not output it's contents under some conditions that I have yet to isolate.

**Comment by chriseppstein** [comment]
Fixed in Sass now.
