### ISSUE TITLE
Sprites spacing not considered in generated sprite-position

### ISSUE THREAD

**Issue by lmartins** [Compass/compass#253]
The following code produces an image with the request spacing between sprites, the problem is that the +sprite-background-position generates coordinates like if there was no space between the sprites:

$icons: sprite-map("sprites/icons/_.png")
$icons-spacing: 10px
@import sprites/icons/_.png

label.restaurantes
    @extend .icons-sprite
    +sprite-background-position($icons, searchicon-restaurantes, 100%)

This was tested on the latest Compass version 0.11.beta.1

**Comment by scottdavis** [comment]
i just reviewed the code and i think this is fixed in my sprite patch can you give me the css its returning to you and the expected css so i can make sure my spec it correct

**Comment by scottdavis** [comment]
just verified that this is fixed in my patch

**Comment by scottdavis** [comment]
<pre>
      $squares-spacing: 10px;
      @import "squares/*.png";
</pre>


your syntax was a bit off you don't need to define $icons by doing 

@import sprites/icons/.png

you can access your sprite map via ${name}-sprites

what you where trying to do was causing 2 sprite maps to be created one with the correct results and one without.
