### ISSUE TITLE
Border-radius not being processed

### ISSUE THREAD

**Issue by lmartins** [Compass/compass#254]
After upgrading to Compass 0.11.beta.1, the mixin +border-radius() does nothing. The generated code doesn't include any declarations for any browser.

Not sure if related, but i had also some mixins for position +absolute-top-left() that would accept up to 4 variables. Since the upgrade, that mixins do work but wont process any of the variables.

**Comment by roytomeij** [comment]
+1 on this one.

**Comment by mirisuzanne** [comment]
The first part of this sounds to me like a known bug in sass 3.1.0.alpha.217. Any chance you upgraded to that at the same time? If so, try jumping back to 214.

**Comment by roytomeij** [comment]
No, it happened right after I upgraded from Compass 0.11.alpha.4 to beta.1, without changing the Sass version.

**Comment by jonasvp** [comment]
We seem to have a similar issue: running on Ubuntu or OS X, 0.11.beta.1 works fine. On Debian, even with a self-compiled version 1.4.1 of rubygems, it doesn't include border-radius or box-shadow and only the CSS3 version of linear-gradient (background-image: linear-gradient()) No fallbacks for -webkit or -moz.

We also use CSS3PIE and the necessary support declarations (behavior, etc.) don't appear at all. We've been looking for a couple of hours already but haven't been able to find any difference in the installations between Debian and Ubuntu/OS X.

This all worked fine in 0.11.alpha. I'd be really grateful for any pointers.

**Comment by jonasvp** [comment]
Wow... your tip to downgrade sass to 3.1.0.alpha.214 helped wonders. We're up and running again! Thanks a lot, hope you'll be able to find the regression introduced in those 3/1000s of a version. I'll be glad to help if I can.

**Comment by chriseppstein** [comment]
the sass issue is fixed now. Closing.
