### ISSUE TITLE
Compass doesn't find plugins on Ruby 1.9.2

### ISSUE THREAD

**Issue by lucasefe** [Compass/compass#256]
Hi, I have a new Rails 3 project setup with compass 0.10.6 and compass-960-plugin.

When using it with ruby ree/1.8.7, I see the following output:

<pre>
Available Frameworks & Patterns:

  * blueprint
    - blueprint/basic      - A basic blueprint install that mimics the actual blueprint css.
    - blueprint/buttons    - Button Plugin
    - blueprint/link_icons - Icons for common types of links
    - blueprint/project    - The blueprint framework.
    - blueprint/semantic   - The blueprint framework for use with semantic markup.
  * compass
    - compass/ellipsis     - Plugin for cross-browser ellipsis truncated text.
    - compass/extension    - Generate a compass extension.
    - compass/project      - The default project layout.
  * 960
    - 960/project          - The 960 Grid System.
</pre>

But when I execute it with 1.9.2 I see the following:

<pre>
Available Frameworks & Patterns:

  * blueprint
    - blueprint/basic      - A basic blueprint install that mimics the actual blueprint css.
    - blueprint/buttons    - Button Plugin
    - blueprint/link_icons - Icons for common types of links
    - blueprint/project    - The blueprint framework.
    - blueprint/semantic   - The blueprint framework for use with semantic markup.
  * compass
    - compass/ellipsis     - Plugin for cross-browser ellipsis truncated text.
    - compass/extension    - Generate a compass extension.
    - compass/project      - The default project layout.

</pre>

As you can see, in the last snippet, 960 framework is omitted. I think this is related to how 1.9.2 handles the current path (.). Is there something I am missing to make compass work under 1.9.2? Any hint? 

Thanks in advance.

Lucas

**Comment by scottdavis** [comment]
I can't seem to recreate this issue if i run

<pre>
ruby 1.9.2p180 (2011-02-18 revision 30909) [x86_64-darwin10.6.0]
$ bundle exec compass frameworks -r ninesixty
</pre>


I get

<pre>

Available Frameworks & Patterns:

  * blueprint
    - blueprint/basic      - A basic blueprint install that mimics the actual blueprint css.
    - blueprint/buttons    - Button Plugin
    - blueprint/link_icons - Icons for common types of links
    - blueprint/project    - The blueprint framework.
    - blueprint/semantic   - The blueprint framework for use with semantic markup.
  * compass
    - compass/ellipsis     - Plugin for cross-browser ellipsis truncated text.
    - compass/extension    - Generate a compass extension.
    - compass/pie          - Integration with http://css3pie.com/
    - compass/project      - The default project layout.
  * 960
    - 960/project          - The 960 Grid System.
</pre>


I think this was patched in 0.11 beta and no one noticed it

**Comment by scottdavis** [comment]
can't replicate
