### ISSUE TITLE
Still requiring haml-edge

### ISSUE THREAD

**Issue by csmosx** [Compass/compass#26]
Check out lib/compass/dependencies.rb
It's still requiring haml-edge.. I noticed when unpacking it in a rails app.

unless defined?(Sass)
  require 'rubygems'
  begin
    gem 'haml-edge','>= 2.1'
  rescue Exception
    $stderr.puts "WARNING: haml-edge gem not found. Trying to find haml on the load path."
  end
  require 'sass'
end

**Comment by chriseppstein** [comment]
Compass will continue to default to haml-edge if it is installed, but I will change the behavior to printing out a message only when it is used, not when it is missing.

**Comment by chriseppstein** [comment]
Load haml-edge if it's all new and shiny. Closed by 59a6067b3a67a79bfd9a5ce325fc1be4bb6c9e78.
