### ISSUE TITLE
invalid option: --using

### ISSUE THREAD

**Issue by virtualmice** [Compass/compass#265]
Whenever I try to create a stand-alone Compass project or to Compass-enable a Rails project I keep getting this error:

$ compass create my_project --using blueprint/semantic

/usr/lib/ruby/1.8/optparse.rb:1450:in `complete': invalid option: --using (OptionParser::InvalidOption)

Same in rails with 
$ compass init rails . -f blueprint/semantic 

Have I missed something  ?

Also, I've just noted a discrepancy in version number :

$ gem list compass => compass (0.10.6)
but,
$ compass -v
Compass 0.8.17 [2465bab]

Could there be something wrong with my install ?

**Comment by chriseppstein** [comment]
Almost certainly.

**Comment by rathgar** [comment]
I just had exactly the same issue.

Discovered that I had a version of compass installed outside of rvm. The solution that worked for me was to go to home dir and uninstall all versions of compass. Restart your terminal sessions then go back to the project directory and bundle install again. IT should be fine.
