### ISSUE TITLE
Sprite generation: PNGs files starting with numbers don't compile.

### ISSUE THREAD

**Issue by ericdfields** [Compass/compass#268]
Renamed a file from '5-3-2_doodad.png' to 'doodad.png' and it worked.

```
error savertime/scss/style.scss (Line 34: Invalid CSS after "...content/*.png",": expected function argument, was "$5-3-2_doodad-p...")
identical savertime/css/style.css 
>>> Change detected to: /Users/…/style.scss
overwrite savertime/css/style.css
```

**Comment by chriseppstein** [comment]
Yes, this is because the filename becomes a css class and css classes can't start with numbers. I'll make a note in the docs.

**Comment by chriseppstein** [comment]
Also, maybe we could come up with a better error message :)

**Comment by jeremyw** [comment]
I'd like to start using Compass sprites, but have a ton of icon images that are just sequential numbers (don't ask).

Would it make sense to prefix the class name to ensure that it starts with a valid character? e.g. "_s-5-3-2-doodad-png", or "sprite-5-3-2-doodad-png" if you're not into the whole brevity thing.

I'd be interested in making this change myself if that's an acceptable implementation.

**Comment by chriseppstein** [comment]
There's a [prefix option](https://github.com/chriseppstein/compass/blob/master/frameworks/compass/stylesheets/compass/utilities/sprites/_base.scss#L33) to the `sprites` mixin. It means that you can't use the autogenerated "magic" sprite import. Instead you should generate a sprite stylesheet and hand edit it.

**Comment by jeremyw** [comment]
What I meant was a default prefix for the magic sprites.

**Comment by chriseppstein** [comment]
I guess there could be some variable that you could set for that.

**Comment by scottdavis** [comment]
Since this is more of a sass limitation. we are adding a verification and gracefully going to raise an error telling you to rename your file. Numbers will not be allowed at the start of a file name.
