### ISSUE TITLE
new x-browser font-face technique

### ISSUE THREAD

**Issue by mirisuzanne** [Compass/compass#270]
http://www.fontspring.com/blog/the-new-bulletproof-font-face-syntax

Removes the need for special handling of EOT files in compass. They should simply be listed first, and with the trailing hash by the designer.

A backwards-compatible change could mean the arguments remain the same, but if $eot is specified, it simply gets the hash added and is prepended to the other $font-files. From there, $eot can be deprecated slowly.

**Comment by paulirish** [comment]
i pinged chris on this guy this morning. I'm a +1 behind it.

The downside is you will ALWAYS serve webfonts to Android 2.2+ ... but.. I guess that's what people want?

**Comment by hoopyfrood** [comment]
+1

**Comment by chriseppstein** [comment]
This is in compass v0.11.beta.3
