### ISSUE TITLE
command line interface truncates file name

### ISSUE THREAD

**Issue by derek73** [Compass/compass#271]
I am working on a project that has a layout non-rails project layout. I would like to hook up compass to our existing css compile process in the same way that we use sass. However it appears that the command line interface is broken.

```
Sprout:project derek$ compass compile . domain/static/site/css/styles.scss --css-dir domain/static/site/css/
   exists ./domain/static/site/css
  compile domain/static/site/css/styles.scss
   create ./domain/static/site/css/les.css
```

Seems regardless how I attempt to pass in a specific scss or sass file, the resulting css file's name gets truncated (css/styles.scss > css/les.css).

**Comment by scottdavis** [comment]
closed by da2af62f47c81b95f995e17cf745b21a36bf5317 - fixed bug that was causing file name to truncate
