### ISSUE TITLE
compass generator for rails 3.x

### ISSUE THREAD

**Issue by apraditya** [Compass/compass#272]
Just notice that running

```
compass init rails ./ --using blueprint
```

put compass.rb inside config/ and it caused this error http://pastie.org/1541736. The file should be in config/initializers/

**Comment by chriseppstein** [comment]
There should be a compass.rb in config as well as config/initializers

**Comment by scottdavis** [comment]
theres no need for ./

just `compass init rails --using blueprint` from within the directory

guess the documentation on this needs to be updated

**Comment by chriseppstein** [comment]
There's new installer documentation in the latest docs:
http://beta.compass-style.org/download/

**Comment by scottdavis** [comment]
was more of a axe the compass rails init . and use the rails generate compass:init using thor .. was merely a suggestion but its pretty much a consistency thing its just intuitive  for me to look at the generators after installing a gem to see if there is anything i need todo

**Comment by scottdavis** [comment]
oh wait this is a way old ticket
i should read the tickets first lol .. its too early
