### ISSUE TITLE
compass/reset could include HTML5 shim

### ISSUE THREAD

**Issue by alanhogan** [Compass/compass#276]
Styles applied to e.g. <header> won’t take properly in e.g. Firefox 3.6 without 

```
article, aside, details, figcaption, figure,
footer, header, hgroup, menu, nav, section {
  display: block;
}
```

More than this is actually recommended for an HTML5-ready reset; see http://html5doctor.com/html-5-reset-stylesheet/

**Comment by chriseppstein** [comment]
I don't include it by default yet, but the mixin exists:
http://beta.compass-style.org/reference/compass/reset/utilities/#mixin-reset-html5

**Comment by alanhogan** [comment]
Works for me. Your call to close the issue, include it by default, or maybe make a bigger stink about the option in the docs (my vote: the include by default, but I don’t care much)

**Comment by chriseppstein** [comment]
The new compass reset (from eric meyer's reset 2.0) has html5 elements in it. This is in the latest betas.
