### ISSUE TITLE
Variables not scoping or working as expected

### ISSUE THREAD

**Issue by alanhogan** [Compass/compass#277]
Steps to reproduce:

style.scss:

```
@import "compass";
@import "compass/reset";
@import "compass/utilities";
@import "compass/css3";
$experimental-support-for-webkit: true;
@import "display"
```

display.scss:

```
.bar {
    $experimental-support-for-webkit: false;
    @include background-image(radial-gradient(50% 400px, circle farthest-side, red, black));
}
.foo {
    @include border-radius(15px);
}
```

Expected: 
: The radial gradient does not include `-webkit-` support, but the `border-radius` does

Actual
: Radial gradient as expected, but now `border-radius` did not generate `-webkit-` code!

**Comment by alanhogan** [comment]
(Edited: style.css variable, I made a typo confusing `true` and `false` in this bug report)

**Comment by imathis** [comment]
This is a misunderstanding of variable scoping. The $experimental-support-for-webkit variable is global, it must be set before you <code>@import "compass";</code>.

If you want to just use a specific vendor you can also do this:
<pre><code>background-image: -moz(radial-gradient(50% 400px, circle farthest-side, red, black));</pre></code>

Also just so you know, when you import compass, you also import utilities, and css3 automatically.

**Comment by alanhogan** [comment]
Hmm, then why in [this demo page](http://beta.compass-style.org/examples/compass/css3/gradient/) does ` $experimental-support-for-svg: true;` get set for just one CSS block?

**Comment by alanhogan** [comment]
Also, just realized I am dumb for filing this as a compass bug, not a sass bug.

Still, I’m not sure what’s going on. Is that declared to be global somewhere?

**Comment by chriseppstein** [comment]
A variable is only scoped to a block if it didn't exist already.

**Comment by alanhogan** [comment]
Thanks.

So to achieve the above, would this work:

```
.bar {
    $experimental-…: false;
    // compass css3…
    $experimental-…: true;
}
```
