### ISSUE TITLE
wrong command line help for the pie extension

### ISSUE THREAD

**Issue by scottdavis** [Compass/compass#279]
- compass
  - compass/ellipsis     - Plugin for cross-browser ellipsis truncated text.
  - compass/extension    - Generate a compass extension.
  - compass/pie          - Plugin for cross-browser ellipsis truncated text.
  - compass/project      - The default project layout.

**Comment by chriseppstein** [comment]
Fix copy/paste error. Closed by 3ee95174ebe2f987024cc1406eef592413837532.
