### ISSUE TITLE
[blueprint] ie.sass template should include a little help about layout

### ISSUE THREAD

**Issue by gravis** [Compass/compass#28]
Hi,

I've discovered today that compass will center all text under IE with blueprint framework. Sounds like without this option, the container gets stuck to the left, and is not centered.

I think the ie.sass template file should include some comments to help new comers figure out why their css behave like this, and what to do next.

Something maybe like :

```
// Compass will center text to fix IE6 container centering.
// That means all your texts will be centered under all version of IE by default.
// Please don't forget to restore the correct behavior to your main container (but not the body tag!)
//
// Example :
//
// .container, .footer
//   :text-align left
// 
//
```

**Comment by chriseppstein** [comment]
There's a similar comment in the compass implementation file, but perhaps one here would be more useful.

**Comment by gravis** [comment]
Indeed :)
Anyway, I don't which file you're mentioning, I don't see anything like that in frameworks/blueprint/_ie.sass ?

**Comment by chriseppstein** [comment]
It's here:
http://github.com/chriseppstein/compass/blob/f8987b816531e2e9bc64c7a24e0c82d9ef34bfff/frameworks/blueprint/stylesheets/blueprint/modules/_grid.sass#L71

But your way is better.

**Comment by chriseppstein** [comment]
merged. thanks.
