### ISSUE TITLE
sprites dont update if a sprite file changed but the sass file stays the same

### ISSUE THREAD

**Issue by scottdavis** [Compass/compass#285]
This is mostly so i don't forget but if you remove a generated sprite but don't change the mtime on a sass file then the sprite doesn't get regenerated. There should be some sort of check to update the sprites maybe store some info in a temp file?. Implementation is the part im stuck on.

line 126: compiler.rb
options[:force] || Sass::Plugin.send(:stylesheet_needs_update?, css_filename, sass_filename)

**Comment by scottdavis** [comment]
this is with the rails configuration

**Comment by chriseppstein** [comment]
Can you test again with yesterday's release? I think it might be fixed.

**Comment by scottdavis** [comment]
this was fixed by a sass patch
