### ISSUE TITLE
Compass watch is broken on OS X Lion

### ISSUE THREAD

**Issue by dlo** [Compass/compass#288]
Here is the traceback. Not really sure if this is library related to compass or what, but it certainly breaks the FSEvents hook.

```
$ compass watch
identical media/css/main.css
>>> Compass is watching for changes. Press Ctrl-C to Stop.
/Library/Ruby/Gems/1.8/gems/haml-3.0.24/vendor/fssm/lib/fssm/backends/fsevents.rb:27: [BUG] Segmentation fault
ruby 1.8.7 (2010-01-10 patchlevel 249) [universal-darwin11.0]

Abort trap: 6
```

**Comment by chriseppstein** [comment]
That code is in [Sass](https://github.com/nex3/sass) which is vendored from [FSSM](https://github.com/ttilley/fssm). I don't have access to Lion, so it'd be awesome if you could diagnose the issue and provide a patch if possible.

**Comment by dlo** [comment]
@chris As soon as I get a chance I'll put some work into it. Super busy ATM but I'd love to help, just wanted you to be aware of the issue.

**Comment by ttilley** [comment]
this makes me a saaaaad panda

**Comment by skue** [comment]
Why is this closed?

I get the same error in Snow Leopard 10.6.6 running ruby 1.8.7 (2009-06-12 patchlevel 174). I've never been able to get compass watch to work...

**Comment by chriseppstein** [comment]
I think it got closed on accident.

If you've never had the watcher work, it's certainly system specific, you can file a bug if you want, but I doubt it'll get worked on anytime soon -- as always with open source projects, patches are accepted.

**Comment by skue** [comment]
Ah. Will try to hunt it down then and send you a patch/pull response if needed. Thanks.

**Comment by ttilley** [comment]
This would, in fact, be an FSSM bug and not a compass bug regardless. I have access to lion, but enough of my dev/play environments outright break that I played with it quite briefly before reverting to a backup. Besides, that change in scroll behavior makes me want to stab someone in the face.

If this continues to occur, and you file a bug for it in the FSSM issues system rather than here, I will do my best to find time sooner rather than later to look into it.

**Comment by ttilley** [comment]
This bug is, unfortunately, verified on lion. RubyCocoa is incredibly grumpy.

```
suzaku:test_project ttilley$ compass watch
>>> Change detected to: /Users/ttilley/tmp/test_project/src/screen.scss
identical stylesheets/screen.css
>>> Compass is watching for changes. Press Ctrl-C to Stop.
/Library/Ruby/Gems/1.8/gems/haml-3.0.25/vendor/fssm/lib/fssm/backends/fsevents.rb:27: [BUG] Segmentation fault
ruby 1.8.7 (2010-01-10 patchlevel 249) [universal-darwin11.0]

Abort trap: 6
suzaku:test_project ttilley$ uname -a
Darwin suzaku.local 11.0.0 Darwin Kernel Version 11.0.0: Sat Feb 19 19:29:29 PST 2011; root:xnu-1699.21.15~1/RELEASE_X86_64 x86_64
```

Awesome, right? Luckily, rb-fsevent still works fine on lion... So it's just a matter of not using the rubycocoa backend where we know it won't work. Use rb-fsevent if available, or fall back to polling.

**Comment by chriseppstein** [comment]
Sounds like a fine plan. Please let me know when FSSM is released and I will update compass accordingly. Thanks for looking into this!

**Comment by ttilley** [comment]
On lion, without rb-fsevent installed:

```
[02:08][test_project]$ compass watch
FSSM -> An optimized backend is available for this platform!
FSSM ->     gem install rb-fsevent
>>> Compass is polling for changes. Press Ctrl-C to Stop.
>>> Change detected to: /Users/ttilley/tmp/test_project/src/screen.scss
identical stylesheets/screen.css
```

I've also done some quick work to get rb-fsevent multipath support into FSSM now rather than wait for the cleaner, simpler, and not even close to complete metadata support. ;)

Chris, if you have a list of things you're particularly grumpy about, let me know. In particular, I'm sure being unable to tell FSSM to just shutup and use polling is probably a PITA. Anything else?

**Comment by chriseppstein** [comment]
@ttilley, the biggest pain point is that fssm reverts to polling whenever compass is used with rvm. I think rb-fsevent will fix that, right?

**Comment by ttilley** [comment]
yeah. technically, when using rvm, and a 1.8.x ruby, you could manually install rubycocoa... which apple so generously does for you with the system ruby. that still wouldn't do you much good if you're using 1.9.x though. rb-fsevent will solve both problems.

originally, rb-fsevent could only accept and report on a single path, but i pretty much rewrote the C code for fsevent_watch to be more flexible without breaking backward compatibility. the requirement of not breaking backward compatibility until i absolutely have to means that the handler isn't as clean as i would like, but that too will change at some point soonish.

anyways, in short, rb-fsevent 0.4.x+ for the win.

**Comment by chriseppstein** [comment]
Closing, rb-fsevent works great now.
