### ISSUE TITLE
Sprite: new features

### ISSUE THREAD

**Issue by aurelien-baudet** [Compass/compass#290]
<ol>
    <li><b>optimize the final sprite image to have less blanks as possible (if using different sizes)</b>
        <pre>
Example:
    wanted result: <a href="http://img819.imageshack.us/i/spritemanuel.png/">http://img819.imageshack.us/i/spritemanuel.png/</a>
    actual result: <a href="http://img825.imageshack.us/i/sprite4fcf1a7b31.png/">http://img825.imageshack.us/i/sprite4fcf1a7b31.png/</a>
        </pre>
                   
        <ul>
            <li>May be automatic if no repeat-x (=> can be in row) or repeat-y (=> can be in column) detected for the image</li>
            <li>
                Currently, we can provide a position for the sprite in the image using offset-x but the offset-y doesn't seem to work
                <ul>
                    <li>possibility to provide a configuration to position manually using variables the image in the sprite. <br />
                    The aim is to keep the inclusion of the sprite really simple and to don't care of where is the image in the sprite, and use another file that contains all the variables used to position sprites manually (separation between code and optimization)</li>
                </ul>
            </li>
            <li>Possibility to provide, using variable, a "layout" manually (row or column) for the sprite. <br />
            Same as above, use variable in order to separate code from optimization. <br />
            Possibility to define a general layout for the whole sprite and then define a particular case for one image for example
            </li>   
        </ul>
    </li>
    <li><b>possibility to make one image for all css files</b>
        <ul>
            <li>images can be placed in different folders and subfolders</li>
            <li>define a sprite using all the images using for example this syntax (from ant)
                <pre>import "images/**/*.png"</pre>
                => load all images recursively starting in images folder
            </li>
        </ul>
    </li>
    <li><b>possibility to make a meta sprite from separated sprites:</b>
        <pre>
 Example:
        - You have defined the window-sprite in Window.scss
        - You have defined the status-sprite in Status.scss
        - Now you want to have for production, only one image for these sprites
              => you can write something like this:
                     all-sprite(window, status)
        </pre>
    </li>
    <li><b>just use image_url in code</b>
        <ul>
            <li>do not use sprite in code but just image_url for example and then use an external file to configure what you want to do with images: use sprite or base64 or somehting else</li>
            <li>The aim is to code simplier again without caring about sprites and base64 while developing and then provide a configuration file that declares that some images should be included in sprites, other in base64 and so on (we separate the code from the optimization)</li>
        </ul>
    </li>
</ol>

These features are not really simple to implement but with these features and the simplicity you have introduce to use sprites in compass, the sprites feature will be very powerful.
For the moment, we can do advance sprite using this: http://csssprites.org/, but it's more complicated than you're way to do.

**Comment by hagenburger** [comment]
**@1. optimize the final sprite image to have less blanks as possible (if using different sizes):**

This would break the original use case Compass Sprites ([Lemonade](http://www.hagenburger.net/BLOG/Lemonade-CSS-Sprites-for-Sass-Compass.html)) was made for. Your example would be useful if you use sprites as an image replacement (having an HTML element with exactly the size of the image). Compass Sprites is even more powerful to use positioned background images just like in CSS (this way you can save HTML tags and have a more semantic markup).

All positions influence the outputted values in the CSS file. Have a look at [this visual example](http://www.hagenburger.net/TMP/compass-sprites-position.png).

Anyway I think this is an additional use case which could be implemented in the next version. By the way, this would not effect the file size a lot (PNG is quite good in handling empty space). But it would effect the memory usage in the browser.

**Comment by hagenburger** [comment]
**@2. possibility to make one image for all css files**

Sure.

**Comment by hagenburger** [comment]
**@3. possibility to make a meta sprite from separated sprites:**

I think this would make it too complicated. Also for my experiences it’s OK to have more than one sprite map (outputted sprite PNG).

**Comment by hagenburger** [comment]
**@4. possibility to make a meta sprite from separated sprites:**

Hmm … it think it’s good to have readable code. Very often “normal” designers work in the same project. So it’s important to understand each line as much as possible. If there’s some magic somewhere else, it could be more complicated. Again: This could be useful for projects with just image replacements. If you use background-positions/-repeats it would get very difficult.

**Comment by aurelien-baudet** [comment]
Thanks for the responses.

> PNG is quite good in handling empty space
> Not so much. With the images I put in example:
- the automatically generated sprite by compass is <b>2.77 Kb</b>
- the automatically generated sprite by compass after optimization using gimp is <b>2.49 Kb</b>
- the manual sprite image using gimp is <b>1.71 Kb</b>

This is 0.78 Kb less (using gimp for both) so it saves 31% for this simple image. In our website, we have more than 50 images from different sizes. So we could have a final image approximatively 500Kb instead of 800Kb currently generated

**Comment by moeffju** [comment]
A lot of the savings probably stem from different PNG libraries. Just taking the generated sprite image and running it through optipng or pngcrush reduces size by several kilobytes.
