### ISSUE TITLE
CSS3: animations

### ISSUE THREAD

**Issue by aurelien-baudet** [Compass/compass#291]
Actually, the CSS3 animation feature (http://www.w3.org/TR/css3-animations/) is not supported by compass.
Is it possible to add the following mixins:

<pre>
animation($name, $duration, $timing_function, $delay, $iteration_count, $direction)
animation-name($name)
animation-duration($duration)
animation-timing-function($function)
animation-iteration-count($count)
animation-direction($direction)
keyframes($name, $frames)
</pre>

Thanks

**Comment by mirisuzanne** [comment]
I've started working on a basic syntax here: https://gist.github.com/939663

I'm recreating the first example in the w3c proposal. It looks to me like `keyframes` are best suited to the proposed new `@children` syntax (which has not yet been implemented). The rest are simple prefixed properties.

**Comment by MoOx** [comment]
So we can almost do that, thanks to this PR https://github.com/nex3/sass/pull/167.
Is somebody working on this ?

**Comment by mirisuzanne** [comment]
I'm waiting for the signal from Chris that this syntax is set on the sass end. Then, unless someone beats me to it (you are more than welcome), I'll start putting together the compass module.

**Comment by silvenon** [comment]
Just do it :)

**Comment by paulirish** [comment]
@ericam now that 9b924243ff7fb543ea8fdce572cf3fc94ef147ba is in.. fixed?

**Comment by mirisuzanne** [comment]
Yes @paulirish, thanks.
