### ISSUE TITLE
Sprite: impossible to load gif images

### ISSUE THREAD

**Issue by aurelien-baudet** [Compass/compass#292]
When using the sprite feature, it fails when loading gif images
      @import "smileys/*.gif";

Fails with:
     Line 4: File to import not found or unreadable: smileys/*.gif

**Comment by hagenburger** [comment]
Compass Sprites uses [chunky_png](https://github.com/wvanbergen/chunky_png) which supports PNG files only. This way you don’t need to use RMagick which is known to have struggles while installing. Please convert your GIF files to PNG (you won’t have any difference in the resulting sprite map).

**Comment by chriseppstein** [comment]
There's a plugin to compass coming that uses rmagick instead of chunkypng. For people who install this plugin, I think this can be made to work so I reopened it.

**Comment by scottdavis** [comment]
Noted ill add this to my feature list for the plugin

**Comment by MarioRicalde** [comment]
I found this issue when I was working with it the other day; somehow I didn't find a comment pointing out that the sprites were only for png's. Maybe we should add this as an important note on the documentation?

**Comment by chriseppstein** [comment]
Sure. but user's don't read docs so we should probably have a better error message in compass.

**Comment by davetheninja** [comment]
@hagenburger - You say "you won’t have any difference in the resulting sprite map" but for people unfortunate enough to still have a requirement to support IE6 (like me) PNG wont cut the mustard.  

PNG transparency is not supported in IE6 :-(

**Comment by hagenburger** [comment]
@davetheninja this issue is about loading GIFs. The result would not differ if you load a GIF or 8 bit PNG.

_For saving images:_ You can set the PNG output file to 256 colors (IE6 does support 1 bit PNG transparency just like for GIFs). This configuration should work (sorry, I can’t test it at the moment):

```
Compass.configuration.chunky_png_options[:color_mode] = ChunkyPNG::COLOR_INDEXED
```

**Comment by davetheninja** [comment]
Most most most excellent sir!

On 29 Nov, 2011, at 6:59 PM, Nico Hagenburger
reply@reply.github.com
wrote:

**Comment by tuomassalo** [comment]
The error message and [documentation](http://compass-style.org/help/tutorials/spriting/) still seem to lack the note about not supporting gif files.

**Comment by tilsammans** [comment]
@chriseppstein is the documentation something others can update quickly? I just spent an hour trying to sprite a .gif and it seems like a quick thing to add to the documentation.
