### ISSUE TITLE
Compass::AppIntegration::Rails.env returns wrong value

### ISSUE THREAD

**Issue by mobilutz** [Compass/compass#297]
In one of my applications I use a custom environment value.

Using "Compass::AppIntegration::Rails.env" does not return the same value as "Rails.env" which corrupts the processing of the scss.

**Comment by chriseppstein** [comment]
Compass only has two environments development and production. I can revisit this design decision soon, but in the time being you should probably refer to Rails.env directly. If this work around doesn't work, please let me know why.

**Comment by chriseppstein** [comment]
closing for now
