### ISSUE TITLE
Installed chunky_png 1.0.1 – "compass --pre" says it requires chunky_png ~> 0.12.0

### ISSUE THREAD

**Issue by digitarald** [Compass/compass#298]
Installing compass --pre requires chunky_png ~> 0.12.0

Installing chunky_png installs 1.0.1.

Installing compass --pre still fails with requiring chunky_png ~> 0.12.0

**Comment by scottdavis** [comment]
im working on a patch for 1.0.1 until then 0.12.0 is the stable currently used in the compass beta

**Comment by scottdavis** [comment]
fixed pending my pull request

**Comment by scottdavis** [comment]
fixed pending my pull request

**Comment by scottdavis** [comment]
^
