### ISSUE TITLE
WARNING: Neither typography.sass nor .scss found. Using typography.css instead

### ISSUE THREAD

**Issue by ganar** [Compass/compass#299]
The following message appears upon rendering fancy-type, I downloaded the file from git-hub

```
WARNING: Neither typography.sass nor .scss found. Using typography.css instead.
This behavior is deprecated and will be removed in a future version.
If you really need typography.css, import it explicitly.
```

**Comment by chriseppstein** [comment]
Doesn't sound like you have compass installed correctly. You can't just drop a file into your project. Please contact the mailing list for support after following the compass installation instructions.

**Comment by ganar** [comment]
Solved: I was importing the mixing in the wrong way. Thanks for your help with this issue Chris
