### ISSUE TITLE
rails-blueprint integration sass errors after install

### ISSUE THREAD

**Issue by rodebrahimi** [Compass/compass#3]
in appropriate general gem directory...
- _float.sass
  -- line #2 "Float" needed to be commented out
- _clearfix.sass
  -- comments to be malformed originally, needed edits to resolve and run properly

**Comment by chriseppstein** [comment]
This is a Sass bug that has been fixed. You need to upgrade to haml-edge:

```
sudo gem uninstall haml
sudo gem install haml-edge
```

**Comment by rodebrahimi** [comment]
I have both running actually... will this mess with my environment if I don't use haml-edge for other projects but use haml? I guess I'm not clear on the diff btwn these releases...

**Comment by chriseppstein** [comment]
You can just download and install the latest from haml's master branch, that is what haml-edge is. Compass will try to pick up haml-edge if it's installed, but YMMV.
