### ISSUE TITLE
Some future requests for better (IMO) project / folder managment

### ISSUE THREAD

**Issue by joneff** [Compass/compass#30]
What about templates that could be used when creating new projects? Something like

> $compass "project / folder name" --from "template name"
> $compass "project /folder name" --to "template name"

to create from templates and create templates. I suppose templates could be directories in the gems folder.

Also, the ability to rebuild all projects within a specific folder

> $compass "folder name" --rebuild

where folder name has the folders where I keep my projects in the form of other folders. There could be switches like "--rebuild all" (which could be the default). Or "--rebuild modified" to rebuild only those who are modified after the latest rebuild for this folder. Or "--rebuild registered", where it rebuilds only the registered projects.

Speaking of which -- registered projects. Say I not always am in my project dir. Invoking compass is easy, since the path is added to the system path. But not projects unless you add the project dir in the path. So if i do something like

> $compass "folder name" --register "short name"

it might be added to a list of projects. Of course it have to be taken in mind if there is a project dir in the current dir, that matches a name from the registered projects.

I could go on like this forever ;) So I stop for now.

-- Ivan

**Comment by chriseppstein** [comment]
It's pretty easy to make a new project using an existing setup:

```
mkdir new_project
cp old_project/config.rb new_project/config.rb
cd new_project
compass -f blueprint --install
```

Perhaps an example should be added to command line wiki page.

Regarding the project registry and related commands, I feel this might be too much complexity. A simple bash script could accomplish the same. Maybe I don't understand the use case...

**Comment by chriseppstein** [comment]
http://github.com/ttilley is currently working on some multi-project thing called sassinator. Maybe it will meet your needs when he releases it into the wild.
