### ISSUE TITLE
Incorrect absolute path handling

### ISSUE THREAD

**Issue by miracle2k** [Compass/compass#304]
I kind of feel like this may be related to a bug I reported before, #129 (which is closed as fixed), but frankly, reading that bug report I don't quite understand what the problem was back then.

Still, using Compass 0.11.beta.3, I have this problem:

```
 $ compass compile $(pwd)/ie.sass --css-dir /tmp/foo
 directory foo/
 create .css
 $ ls -lah /tmp/foo
 -rw-r--r--  1 michael michael 3.8K 2011-03-24 23:40 .css
```

As you can see, it creates /tmp/foo/.css rather than /tmp/foo/ie.css, as you would expect.

This seems due do some simplified path handling where it simply cuts the length of --sass-dir from each input file to determine the output, rather than properly determining the relative path between the two, or even just going with the file basename (ie.sass) in cases where --sass-dir is not defined.

Note that I can work around the issue by using:

```
 $ compass compile $(pwd)/ie.sass -sass-dir $(pwd) --css-dir /tmp/foo
```

**Comment by scottdavis** [comment]
<pre>

$ compass help compile

Usage: compass compile [path/to/project] [path/to/project/src/file.sass ...] [options]
</pre>


try 

<pre>
compass compile /tmp/foo $(pwd)
</pre>

**Comment by miracle2k** [comment]
FWIW, this:

```
 $ compass compile /tmp/foo $(pwd)
 Errno::EISDIR on line 116 of /var/lib/gems/1.8/gems/compass-0.10.6/lib/compass/compiler.rb: Is a directory - /home/michael/the/full/path/to/pwd
```

If I use your syntax but pass a source file:

```
$ pwd
/home/michael/Development/projects/foo
$ compass compile /tmp/foo $(pwd)
directory src/
 compile ie.sass
   create ie.css
$ ls /tmp/foo/stylesheets/evelopment/projects/foo
ie.css
```

So this recreates the full path within /tmp/foo (not really what I want), and what's more, it still cuts off the path incorrectly (see the folder called "evelopment" - that should be "Development".

Note that I don't actually want to use compass's project management features. That's why I'm pointing it to a temp directory. I want to call the compass executable from a script and create a specific output file that I can post-process further.

**Comment by scottdavis** [comment]
<pre>
stylesheets (master)]$ compass compile screen.scss --css-dir /tmp
   create n.css 
</pre>


I'm seeing this happening also definitely seems to be unintended. thanks for reporting ill get this on my list

**Comment by scottdavis** [comment]
<pre>
compass compile /tmp --sass-dir=`pwd`
</pre>


this worked for me

**Comment by chriseppstein** [comment]
I made a fix for this, you'll get an error unless you run this variant of the command from the project directory.

**Comment by chriseppstein** [comment]
commit: 389291958516adf695e274b81dab16a3c12cb2cc
