### ISSUE TITLE
Re-scoping in blueprint-typography results in partial resetting

### ISSUE THREAD

**Issue by jdrowell** [Compass/compass#31]
The _typography.sass module of blueprint generates markup like

```
body.bp body { line-height: 1.5; font-family: Helvetica Neue, Arial, Helvetica, sans-serif; color: #333333; font-size: 75%; }
```

when a regular mixin call like +blueprint-typography is called (using the generated screen.sass). Clearly the extra "body" child class prevents the rule from ever being put into effect (body inside a body), thus not resetting the fonts for the whole body. This was observed with compass 0.8.7 and haml 2.2.1. These are several ways to prevent this from happening (like calling -body and -defaults explicitly) but the real bug seems to be in the

```
=blueprint-typography(!body_selector = "body")
```

block itself. The default placement for the +blueprint-typography mixin call is already scoped inside the body, so re-scoping it causes the problem. I just started using compass so will not attempt to mess with the code before I'm more familiarized. BTW thanks for compass, having fun with it so far.

**Comment by chriseppstein** [comment]
This is fixed in edge already and will go out with the next release.

http://github.com/chriseppstein/compass/commit/7b28e9af4ab70b995239158a8c6a809c76184fa0
