### ISSUE TITLE
Background linear gradient Opera

### ISSUE THREAD

**Issue by WaYdotNET** [Compass/compass#318]
// work with FF & Chrome
   // NOT works with Opera/9.80 (X11; Linux x86_64; U; it) Presto/2.8.119 Version/11.10

   @include linear-gradient(color-stops($header, darken($header, 10%)));

   // Hack to works with Opera:

   background-image:-o-linear-gradient(color-stops($header, lighten($header, 20%)));

   // test with compass  compass-0.10.6 & compass-0.11.beta.5

**Comment by chriseppstein** [comment]
Sounds like we need to revisit our opera support matrix.

**Comment by chriseppstein** [comment]
Fixed by da57adc49d4c75b56235390cad4c5721b8961a24

**Comment by WaYdotNET** [comment]
good job chris!
