### ISSUE TITLE
`compass --rails -f blueprint .` tells you to include " stylesheet_link_tag 'compiled/partials/_base.css' " in %head

### ISSUE THREAD

**Issue by agibralter** [Compass/compass#32]
The README @ http://github.com/chriseppstein/compass-rails-sample-application/tree/master is correct, however.

**Comment by chriseppstein** [comment]
I think you need to upgrade. I fixed the bug a while ago and cannot reproduce it using Compass 0.8.7 [9aa9867]

**Comment by agibralter** [comment]
<pre>
$ compass --version
Compass 0.8.8 [6ae3f9a]
$ mkdir test
$ cd test
$ rails test
$ cd test
$ compass --rails -f blueprint .
...
Congratulations! Your rails project has been configured to use Compass.
Sass will automatically compile your stylesheets during the next
page request and keep them up to date when they change.
Make sure you restart your server!

Next add these lines to the head of your layouts:

%head
  = stylesheet_link_tag 'compiled/screen.css', :media => 'screen, projection'
  = stylesheet_link_tag 'compiled/partials/_base.css'
  = stylesheet_link_tag 'compiled/print.css', :media => 'print'
  /[if lt IE 8]
    = stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection'

(You are using haml, aren't you?)
</pre>
