### ISSUE TITLE
Can't create sprite file from cmd line with -f option

### ISSUE THREAD

**Issue by jleider** [Compass/compass#320]
$ compass sprite -f "app/webroot/img/sprite_imgs/general/*.png" --trace

NoMethodError on line 42 of /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.4/lib/compass/commands/sprite.rb: private method `gsub' called for nil:NilClass

  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.4/lib/compass/commands/base.rb:18:in `execute'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.4/lib/compass/commands/project_base.rb:19:in`execute'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.4/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.4/lib/compass/exec/sub_command_ui.rb:15:in`run!'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.4/bin/compass:25
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.4/bin/compass:39:in `call'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.4/bin/compass:39
  /usr/bin/compass:19:in`load'
  /usr/bin/compass:19

**Comment by jleider** [comment]
This error exists in 0.11.beta.5 as well.

**Comment by chriseppstein** [comment]
Try this instead:

```
compass sprite -f "sass/_mysprite.scss"
```

"app/webroot/img/sprite_imgs/general/*.png" --trace

Chris

**Comment by scottdavis** [comment]
I'll get this fixed. I Didn't notice it because someone didnt write a test for it =p /nudge @chriseppstein

Scott Davis

**Comment by scottdavis** [comment]
or maybe not

**Comment by chriseppstein** [comment]
I think it just needs a better error when they don't provide a path to the sprites.

**Comment by chriseppstein** [comment]
Who needs tests. we have users!

**Comment by scottdavis** [comment]
yea this is definitely broken im working on a patch and test now

**Comment by scottdavis** [comment]
closed by 96f1e4dc969e565206cc57c6f5c51120732299f4 and refactored the rspec tests

**Comment by jleider** [comment]
Wow, awesome response. Thanks!
