### ISSUE TITLE
How to use compass in java/scala?

### ISSUE THREAD

**Issue by freewind** [Compass/compass#322]
I want to use compass in scala through jruby, but I don't know how to invoke it.

There is a project let me use sass in scala, the code is very simple. I think I can use compass the same way, could you help me?

The project I mentioned is [scalate-jruby](https://github.com/scalate/scalate/tree/master/scalate-jruby/src/main/scala/org/fusesource/scalate/jruby), only 2 files needed.

**Comment by ttilley** [comment]
I have code lying around for bootstrapping rake and so forth from ant using both maven and ivy... perhaps this would make a good wiki item for jruby, with a mention in the compass wiki that points to it?

Anyways, here's an ant snippet to install ivy if necessary, load ivy, use ivy to resolve jruby and dependencies, install those, load org.jruby.ant.RakeImport, and fire off the "default" task (whether it be defined via ant or rake):

```
<project name="jruby-kickstart"
         default="default"
         xmlns:ivy="antlib:org.apache.ivy.ant">

    <property name="jruby.version" value="1.6.0" />
    <property name="ivy.install.version" value="2.0.0" />
    <property name="ivy.jar.dir" value="${basedir}/ivy" />
    <property name="ivy.jar.file" value="${ivy.jar.dir}/ivy.jar" />
    <property name="ivy.checksums" value="" />

    <mkdir dir="${ivy.jar.dir}" />

    <get src="http://repo1.maven.org/maven2/org/apache/ivy/ivy/${ivy.install.version}/ivy-${ivy.install.version}.jar"
         dest="${ivy.jar.file}"
         usetimestamp="true" />

    <path id="ivy.lib.path">
        <fileset dir="${ivy.jar.dir}" includes="*.jar" />
    </path>

    <taskdef resource="org/apache/ivy/ant/antlib.xml"
             uri="antlib:org.apache.ivy.ant"
             classpathref="ivy.lib.path" />

    <ivy:cachepath organisation="org.jruby"
                   module="jruby-complete"
                   revision="${jruby.version}"
                   pathid="jruby.path.id"
                   inline="true" />

    <taskdef name="rakeimport"
             classname="org.jruby.ant.RakeImport"
             classpathref="jruby.path.id"/>

    <rakeimport/>
</project>
```

And then your rakefile can do whatever one would normally do in a rakefile without having to depend on the system having ruby or jruby installed. Pretty convenient (at times)...

You could probably ignore the rake-related bits entirely and just fire off jruby commands as if you were running it from the commandline. Assuming you're installing and loading jruby like above, I think this might do what you want (untested):

```
<target name="compass.install" description="install compass">
    <java classname="org.jruby.Main" fork="true" failonerror="true">
        <classpath refid="jruby.path.id" />
        <arg value="-S" />
        <arg value="gem" />
        <arg value="install" />
        <arg value="compass" />
    </java>
</target>

<target name="compass.watch" description="watch for changes">
    <java classname="org.jruby.Main" fork="true" failonerror="true">
        <classpath refid="jruby.path.id" />
        <arg value="-S" />
        <arg value="compass" />
        <arg value="watch" />
    </java>
</target>
```

You MAY need to set gem-related environment variables in those tasks to get it to work as expected with jruby-complete, as i think the default gem home is inside of a jar file, which would be somewhat difficult to install to. ;)

...I also think there's a pre-existing task in jruby's ant integration for installing gems that wouldn't require the hackish "lets pretend this is a commandline" call to org.jruby.Main, and potentially also avoid the gem environment issue. I didn't need it for my use-case, and just used ruby in the rakefile to install a gem programmatically if it didn't exist (cant depend on bundler being installed either), so I honestly don't recall the behavior here.

**Comment by ttilley** [comment]
Ah... after reading further into scalate, I see that this is a much more deeply integrated system, more akin to running compass within rails. Interesting.

**Comment by freewind** [comment]
Thanks, ttilley. I'm sorry I didn't express clearly, actually I want to invoke compass programmatically. I have set up the jruby jars and environment, but I don't know to invoke compass.

The code I'm using now is:

```
require 'compass'
options = { :cache_location => "cache" }
compiler = Compass::Compiler.new("/test", "sass", "css", options)
compiler.compile("aaa.sass", "aaa.css")
```

Unfortunately, it reports an error about logger. Which logger compass uses?

**Comment by ttilley** [comment]
So.... At this point in the source tree:

https://github.com/scalate/scalate/tree/master/scalate-jruby/src/main/resources

You would need to add compass and its' dependencies. The latest git version of compass depends on sass, not haml, as it has been split out into its own package. You will probably want to edit the existing scalate sass code to load this instead of what it's currently doing. IF you use the latest sass code, and make sure to have everything necessary on the load path, then you can use the sass scalate code almost as-is and just add an option that generates:

```
options[:compass] = true
```

...if you want compass integration. At the very least it'll load compass, so that you get the additional extensions to sass, and include any load paths it should based on the compass configuration (which lives separately in your project).

**Comment by ttilley** [comment]
I lied. The compass option is handled in exec, not engine, so it would require larger changes to the ruby that scalate pushes to jruby. The compass option effectively does this:

```
  def load_compass
    begin
      require 'compass'
    rescue LoadError
      require 'rubygems'
      begin
        require 'compass'
      rescue LoadError
        puts "ERROR: Cannot load compass."
        exit 1
      end
    end
    Compass.add_project_configuration
    Compass.configuration.project_path ||= Dir.pwd
    @options[:for_engine][:load_paths] += Compass.configuration.sass_load_paths
  end
```

This loads the compass configuration file, with sane defaults for anything not specified (or even if there isn't a config I believe), sets the project path to the current directory (which may be wrong in your case), and then takes the load paths compass has set up and adds those to the options it would pass on to the call to engine.

**Comment by freewind** [comment]
@ttilley,thank you. Let me have a try
