### ISSUE TITLE
Custom defined watch only runs once

### ISSUE THREAD

**Issue by Kevnz** [Compass/compass#323]
I have a watch setup in the config.rb of my project and on the first save it works great. But after the first time it doesn't run until a scss file is changed. https://gist.github.com/895290

**Comment by chriseppstein** [comment]
Do you have rb-fsevents installed?

**Comment by chriseppstein** [comment]
ping?

**Comment by chriseppstein** [comment]
I think this was due to a bug in FSSM when using the rb-fsevent backend. That bug is fixed on master now. Please let me know if your issue is different.

**Comment by Kevnz** [comment]
Sorry, I've actually been sick and haven't had a chance to check this.
