### ISSUE TITLE
Problem with compass stats in a rails app

### ISSUE THREAD

**Issue by scottdavis** [Compass/compass#324]
$ bundle exec compass compile stats
Errno::ENOENT on line 143 of /Users/sdavis/Work/compass/lib/compass/compiler.rb: No such file or directory - /Users/sdavis/Work/breakthroughs/hubble-breakthroughs/stats
Run with --trace to see the full backtrace

seems to be a load path problem

**Comment by scottdavis** [comment]
Note:
file or directory - /Users/sdavis/Work/breakthroughs/hubble-breakthroughs/stats

does not and should not exist

**Comment by chriseppstein** [comment]
When you pass an argument to compile, it assumes that is the folder/file that you want to limit the compilation to. Did you want stats for your project? Then just do:

```
bundle exec compass stats
```

That said a better error message could have been given here.

**Comment by scottdavis** [comment]
I was hoping if i ran it from the rails root it would find the config and give me the stats for the project. so i should run it from the stylesheets directory?

**Comment by scottdavis** [comment]
hahaha nvm im closing this im stupid i had `compass compile stats` herp derp
