### ISSUE TITLE
Undefined variable: "$sprite-selectors"

### ISSUE THREAD

**Issue by hoverlover** [Compass/compass#325]
I am in the process of trying out Compass' sprites functionality in the 0.11.beta.5 version and ran into a problem:

```
Syntax error: Undefined variable: "$sprite-selectors".
    on line 31 of /Users/cboyd/.rvm/gems/ruby-1.9.2-p180@my-proj/gems/compass-0.11.beta.5/frameworks/compass/stylesheets/compass/utilities/sprites/_base.scss, in `sprite_selectors'
    from line 54 of /Users/cboyd/.rvm/gems/ruby-1.9.2-p180@my-proj/gems/compass-0.11.beta.5/frameworks/compass/stylesheets/compass/utilities/sprites/_base.scss, in `sprites'
    from line 283 of social, in `social-sprites'
    from line 287 of social, in `all-social-sprites'
    from line 27 of /Users/cboyd/workspace/my-proj/app/stylesheets/partials/_base.scss
    from line 2 of /Users/cboyd/workspace/my-proj/app/stylesheets/screen.scss
```

This is where the error originated, which as you can tell from the stack trace above was in my `app/stylesheets/partials/_base.scss` file that is imported from my `app/stylesheets/screen.scss` file:

```
@import "social/*.png";
@include all-social-sprites;
```

I fixed it by importing `compass/utilities/sprites` but the sprites tutorial made no mention of this.  Here is the code now, that works:

```
@import "social/*.png";
@import "compass/utilities/sprites";
@include all-social-sprites;
```

Just wanted to point this out so someone could update the tutorial for others that might also run into this problem.

**Comment by scottdavis** [comment]
This is actualy confusing me since i created a new sprite project today and i didn't need to add that import are you using compass standalone or with rails?

**Comment by hoverlover** [comment]
I'm using it with rails 3.0.5.

On Apr 1, 2011, at 8:48 PM, jetviper21
reply@reply.github.com
wrote:

**Comment by scottdavis** [comment]
can i see your compass.rb thats in configs and your screen.scss

**Comment by scottdavis** [comment]
nvm seems you need to import the file when in stand alone mode. i fixed the docs

**Comment by hoverlover** [comment]
I'm not using stand-alone mode.  I'm using compass within a rails
project. I just checked the docs and they don't appear to be updated.
The tutorial I was referring to was here:

http://beta.compass-style.org/help/tutorials/spriting/

The tutorial doesn't appear to be specific to rails, so you might add
a rails-only note mentioning the need for the import if it's only
necessary for rails projects.

On Apr 2, 2011, at 7:31 AM, jetviper21
reply@reply.github.com
wrote:

**Comment by scottdavis** [comment]
They are updated in git I haven't pushed the update since I'm still working on documentation 

Scott Davis

**Comment by hoverlover** [comment]
Ah, ok.  Thanks.

On Apr 2, 2011, at 9:32 AM, jetviper21
reply@reply.github.com
wrote:

> They are updated in git I haven't pushed the update since I'm still working on documentation
> 
> Scott Davis
>

**Comment by scottdavis** [comment]
Chris patched this error yesterday I put the configuration variable in the
wrong spot. So feel free to flog me the documentation was correct.

**Comment by hoverlover** [comment]
Ha!  No problem.

On Apr 3, 2011, at 6:37 PM, jetviper21
reply@reply.github.com
wrote:

> Chris patched this error yesterday I put the configuration variable in the
> wrong spot. So feel free to flog me the documentation was correct.
> 
> On Sat, Apr 2, 2011 at 11:09 AM, hoverlover <
