### ISSUE TITLE
Add a page to the docs for the Compass Team

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#329]
@imathis would you design a page for the docs that highlights who are the members of the compass team? A short bio and some links to them on the 'net, etc? Would like to get more credit where it's due.

**Comment by scottdavis** [comment]
/nudge @imathis you have time todo this or should i throw something together just trying to triage old tickets

**Comment by chriseppstein** [comment]
I am chris, destroyer of old issues.
