### ISSUE TITLE
compass on windows issue

### ISSUE THREAD

**Issue by Gromina** [Compass/compass#33]
compass doesn't work on windows out from the box

it shows up the error box "CORE_RL_magick_.dll not found"

**Comment by chriseppstein** [comment]
I've had several reports that compass does work on windows. Please indicate the steps to reproduce this issue. What command are you running? What version of windows? Steps you followed to install compass?

Thanks

**Comment by Gromina** [comment]
Hi, thanks for your feedback.

I finally spent some more time on this issue and find out a solution:

```
* Got to install ImageMagick manually (important: mark "add ImageMagick to system path" during install)
* You have to install RMagik gem manually on windows instructions a there http://rmagick.rubyforge.org/
```

best regards, Alex

**Comment by chriseppstein** [comment]
closing. Hopefully google will help people find this issue if it affects them. Feel free to edit the wiki as you feel is appropriate.
