### ISSUE TITLE
issue installing on rvm gemset

### ISSUE THREAD

**Issue by chabgood** [Compass/compass#330]
ERROR:  While executing gem ... (TypeError)
    can't dup NilClass

**Comment by chriseppstein** [comment]
Please provide better steps to reproduce and a full stack trace.

**Comment by chabgood** [comment]
How do I get a stack trace that is the only message I get when I do:
gem install -f chriseppstein-compass-0.8.17.gem

ERROR:  While executing gem ... (TypeError)
    can't dup NilClass

**Comment by chriseppstein** [comment]
That gem name and version are very old. Are you a new user of compass? Please use the gem named "compass" and let me know if it works.

**Comment by chabgood** [comment]
No it is being used and is working in production.  We are trying to set it
up on a staging server and it is giving this error all of a sudden with
rvm.  I am using rvm with this gem locally and it works fine.

**Comment by chriseppstein** [comment]
I can't help you with this. It's an ancient gem version and the error is not coming from my software. There's been a bunch of gem bugs lately I suggest you consider upgrading or downgrading rubygems in that environment. I also suggest you upgrade compass to at least v0.10.

**Comment by chriseppstein** [comment]
Closing.

**Comment by ekenberg** [comment]
Just update your RubyGems:

```
gem update --system
```

after that, it should work.
