### ISSUE TITLE
Blueprint partials aren't installed (Rails 3/Bundler/rvm/ruby 1.9.2 p136)

### ISSUE THREAD

**Issue by ragaskar** [Compass/compass#332]
Tried various combos of 

compass init, compass create, compass install on my rails project, finally tried with a 'fresh', standalone project, still no love: 

example output with fresh project: 

~/workspace$ compass create test2 --using blueprint
directory test2/
directory test2/images/
directory test2/src/
directory test2/src/partials/
directory test2/stylesheets/
   create test2/config.rb
  convert screen.sass
   create test2/src/screen.scss
  convert _base.sass
   create test2/src/partials/_base.scss
  convert print.sass
   create test2/src/print.scss
  convert ie.sass
   create test2/src/ie.scss
   create test2/images/grid.png
   exists test2/stylesheets
  compile test2/src/ie.scss
   create test2/stylesheets/ie.css
  compile test2/src/print.scss
   create test2/stylesheets/print.css
  compile test2/src/screen.scss
   create test2/stylesheets/screen.css

Using latest (0.10.6) compass: 

~/workspace$ gem list compass

**\* LOCAL GEMS ***

compass (0.10.6)

rvm version 1.5.2, using a gemset. rubygems version was 1.3.7, upgraded to 1.7.2 and uninstalled, reinstalled, same problem. 

Absolutely bewildered especially since 10.6 has been out since November and I seem to be the only one with this problem (natch). Any ideas? I'm guessing it _should_ copy the stuff out of the frameworks/_blueprint_deprecated_imports/stylesheets/ but it doesn't seem to. Am I missing something completely obvious? 

Thanks for your time!

**Comment by chriseppstein** [comment]
Compass does not put its stylesheets in your project, they stay with compass and you import them from where they are using the @import directive.

If you really want them in your project look at the `compass unpack` command.

**Comment by ragaskar** [comment]
I'm pretty confident this was a load path problem that got cached in the tmp/sass-cache or public/stylesheets, since checking out the project on a new machine got it working normally. I ran into problems again when I switched to susy. Killing tmp/sass-cache and public/stylesheets fixed all my problems.
