### ISSUE TITLE
add support for new column properties

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#334]
compass doesn't support `column-fill` or `column-span`. We should do a scan of the latest spec and update the compass columns module to match.

**Comment by mirisuzanne** [comment]
useful: http://kmsm.ca/2010/an-almost-complete-guide-to-css3-multi-column-layouts/
and of course: http://www.w3.org/TR/css3-multicol/

I have my eye on this if it's still sitting around when I have the chance. probably in a week or so.

**Comment by chriseppstein** [comment]
I'm hoping we can do the v0.11 release before the end of the month.

**Comment by mirisuzanne** [comment]
I like the sound of that. Let's do.

**Comment by chriseppstein** [comment]
This was actually done a long time ago. Closing. Note: I did check and it seems like it's prudent to add -ms support so I did.
