### ISSUE TITLE
Add inline sprite rendering

### ISSUE THREAD

**Issue by scottdavis** [Compass/compass#336]
http://groups.google.com/group/compass-users/browse_thread/thread/c62aeca396c67600

**Comment by ghost** [comment]
I´ve once written a parse and replace tool using js/rhino, based on an article of stoyan stefanov which adresses issues the current image-inline also could benefit from (IE6/7 MHTML).
http://www.phpied.com/the-proper-mhtml-syntax/

Unfortunatly i´am not a Ruby dev but if anyone comes up with an pull request i can help out with manual testing and also have a few pages up with already inlined images which i can easily switch over to a new compass version to test the output against the old one.

Regards.

**Comment by scottdavis** [comment]
not going to happen in this release will reopen the issue at another time if a need arises

**Comment by haarts** [comment]
Too bad. I believe this would solve the issue with Compass and read only filesystems like Heroku.

**Comment by scottdavis** [comment]
the real problem is mhtml syntax

**Comment by chriseppstein** [comment]
@haarts heroku's model is broken. They are adding a deploy step where stylesheet compilation can occur before the slug is locked down. This is necessary for rails 3.1 support.

**Comment by haarts** [comment]
@chriseppstein not sure I follow. So they are the once who are going to fix this? That is good news! FYI I'm now looking into the inline-image option of compass, this would make the sprite generation obsolete (I think).

**Comment by chriseppstein** [comment]
@haarts Serving images via base64 encoding is not usually more efficient than serving an image. Unless the image is very small. Usually spritemaps are big enough to warrant being a proper image served by the webserver.

I heard that heroku is going to add a predeploy step for the `rake assets:precompile` step in rails 3.1.
