### ISSUE TITLE
Compass does not provide a way to pass configuration to Sass

### ISSUE THREAD

**Issue by jjl** [Compass/compass#338]
...or if it does, I can't seem to find where it permits it in the documentation.

My main request is to be able to select an output style, so that i can use compass to do the building for deployment by using the compressed output while using the expanded style during dev.

Relevant sass doc: http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#output_style

**Comment by chriseppstein** [comment]
you can specify the output style on the command line (compass compile -h), using the `output_style` config option, or by passing it to the sass options directly like this in your config:

```
sass_options = {:style => :compressed}
```
