### ISSUE TITLE
filter-gradient requires utilities/general/hacks

### ISSUE THREAD

**Issue by joliss** [Compass/compass#339]
Using filter-gradient throws the following error message:

```
Syntax error: Undefined mixin 'has-layout'.
        on line 77 of /var/lib/gems/1.9.1/gems/compass-0.11.beta.6/frameworks/compass/stylesheets/compass/css3/_images.scss, in `has-layout'
        from line 77 of /var/lib/gems/1.9.1/gems/compass-0.11.beta.6/frameworks/compass/stylesheets/compass/css3/_images.scss, in `filter-gradient'
```

It goes away if I put `@import "compass/utilities/general/hacks";` at the top.  Shouldn't filter-gradient import that module automatically?

(I'd send you a pull request, but I'm not sure where to best put the @import.)

**Comment by joliss** [comment]
Also: I've only used it very briefly, but so far, Compass seems most awesome!  Thanks for all the hard work!

**Comment by chriseppstein** [comment]
Yes. Thanks for the bug, we will add the import.
