### ISSUE TITLE
compass fails with ruby 1.9.1

### ISSUE THREAD

**Issue by priit** [Compass/compass#34]
Thanks for creating compass!

I have issue on ruby 1.9.1 and passing test:
http://pastie.org/559276

Moreover I got the same issue as on the list: http://groups.google.com/group/compass-users/browse_thread/thread/e2d57f9d408343ea 

Should I fork and fix the bugs or leave it to you?
Cheers, keep up good work!

**Comment by adamsalter** [comment]
I'm also getting these issues... Ruby 1.9.1p0
How long do we expect until this gets fixed?

**Comment by priit** [comment]
Hi, I fixed my problem and pushed up to my own master fork http://github.com/priit/compass/tree/master (I made fork only for fixing this bug). By the way, the fix are already pulled to chriseppstein edge branch, so you can use edge or my temporary master branch. Cheers!

**Comment by chriseppstein** [comment]
I release the fix for this in v0.8.12. Please let me know if you're having any more issues with ruby 1.9.1

**Comment by adamsalter** [comment]
seems to be working fine. sass files generate no problems.

**Comment by chriseppstein** [comment]
:-D Great!

**Comment by adamsalter** [comment]
One less ruby 1.9.1 bug to deal with ;)

... Actually it all works pretty well: db drivers - 'kwatch/mysql-ruby' and 'qooba/sqlite3-ruby' being major needed updates.
... and tempfile problem with passenger:
http://www.taylorluk.com/articles/2009/08/12/ruby-19-and-passenger

Anyway cheers, ;)
