### ISSUE TITLE
watch leaks memory

### ISSUE THREAD

**Issue by passy** [Compass/compass#340]
Today I noticed that compass 0.11.beta.5 is leaking a noticeable amount of memory after each change. I tracked the memory usage over a few hours while working with it and it grew from an initial 86 MB to over 600 MB in 2 and a half hours (even though it seems to solely depend on the amounts of changes). Restarting compass watch does obviously help, though.

Here's a graph of the memory usage over time:

![](https://spreadsheets.google.com/a/weluse.de/oimg?key=0AqUNb6kPhsZIdHUyanh6aEhZOUdGQU9uTVFuNk9XZVE&oid=2&zx=17xratqyvb3g)

<pre>$ ruby --version
ruby 1.8.7 (2010-06-23 patchlevel 299) [x86_64-linux]
</pre>

**Comment by scottdavis** [comment]
this is probably more suited as an fssm bug

**Comment by thedarkone** [comment]
@chriseppstein: this is most likely SASS's `Plugin::StalenessChecker` leak that that has been introduced by the `plugin_v2` branch/refactor. I've talked about this with Nathan back in september and from a cursory look it still hasn't been fixed as of yet. Basically `Sass::Importers` classes need to have consistent hashing as required by ruby's `Hash`, so that:

```
importer_a, importer_b = Sass::Importers::Filesystem.new("abc/x.scss"), Sass::Importers::Filesystem.new("abc/x.scss")
importer_a.hash == importer_b.hash # => true
importer_a.eql?(importer_b) # => true
```

I think doing something like this would fix the leak:

```
class Sass::Importers::Filesystem
  delegate :hash, :eql?, :to => '@root'
end
```

**Comment by chriseppstein** [comment]
@thedarkone - thanks for the pointer. I will test to see if that clears up the issue.

**Comment by chriseppstein** [comment]
@thedarkone I tried what you said, but that doesn't seem to be the major offender.

I spent a few hours on this tonight. I'm pretty sure this is due to the introduction of the in memory cache. I need to look into it more tomorrow.

**Comment by chriseppstein** [comment]
@thedarkone Actually that turned out to be about 50% of the issue. Thanks for the pointer.

The relevant fixes are [here](https://github.com/chriseppstein/compass/compare/fec367d60c...9cafbc642c).

Memory use during watch is very stable now.

**Comment by passy** [comment]
I can confirm that the leak has been greatly reduced, however it seems like some changes are no longer detected after your patch. I.e. files are marked as "identical" until the watch service is restarted. I guess this is related to the new hashing algorithm, isn't it?

**Comment by chriseppstein** [comment]
I see that too :(

**Comment by chriseppstein** [comment]
fixed and working now.
