### ISSUE TITLE
problems with rounding color-stops

### ISSUE THREAD

**Issue by mirisuzanne** [Compass/compass#341]
With Compass 0.11.beta.7 and Sass 3.1.0.alpha.253.

SCSS:

@import "compass";
@import "compass/layout/grid-background";

@include column-grid-background(12, 2em, 1em, 1em, rgba(100, 100, 225, 0.25), rgba(0,0,0,0), true);

RESULT:

error sass/screen.scss (Line 69: Color stops must be specified in increasing order. 91.8918918918919 came after 91.8918918918919.)

/*
Syntax error: Color stops must be specified in increasing order. 91.8918918918919 came after 91.8918918918919.
        on line 69 of /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/frameworks/compass/stylesheets/compass/css3/_images.scss, in `background-image'
        from line 138 of /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/frameworks/compass/stylesheets/compass/layout/_grid-background.scss, in`column-grid-background'
        from line 4 of /Users/eric/Sites/_misc/test/sass/screen.scss

Backtrace:
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/frameworks/compass/stylesheets/compass/css3/_images.scss:69:in `background-image'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/frameworks/compass/stylesheets/compass/layout/_grid-background.scss:138:in`column-grid-background'
/Users/eric/Sites/_misc/test/sass/screen.scss:4
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/sass_extensions/functions/gradient_support.rb:293:in `color_stops_in_percentages'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/sass_extensions/functions/gradient_support.rb:287:in`map'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/sass_extensions/functions/gradient_support.rb:287:in `color_stops_in_percentages'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/sass_extensions/functions/gradient_support.rb:276:in`grad_color_stops'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/sass_extensions/functions/gradient_support.rb:151:in `to_owg'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/sass_extensions/functions/cross_browser_support.rb:59:in`send'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/sass_extensions/functions/cross_browser_support.rb:59:in `prefix'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/sass_extensions/functions/cross_browser_support.rb:55:in`prefix'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/sass_extensions/functions/cross_browser_support.rb:54:in `map'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/sass_extensions/functions/cross_browser_support.rb:54:in`prefix'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/sass_extensions/functions/cross_browser_support.rb:41:in `_owg'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/script/funcall.rb:80:in`send'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/script/funcall.rb:80:in `_perform'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/script/node.rb:40:in`perform'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:215:in `visit_prop'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:37:in`send'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:18:in`visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:53:in `visit_children'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:53:in`map'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:53:in `visit_children'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:27:in`visit_children'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:39:in `with_environment'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:26:in`visit_children'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:127:in`visit_if'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:37:in `send'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:37:in`visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:18:in `visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:200:in`visit_mixin'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:200:in `map'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:200:in`visit_mixin'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:39:in `with_environment'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:200:in`visit_mixin'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:37:in `send'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:37:in`visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:18:in `visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:200:in`visit_mixin'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:200:in `map'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:200:in`visit_mixin'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:39:in `with_environment'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:200:in`visit_mixin'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:37:in `send'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:37:in`visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:18:in `visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:53:in`visit_children'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:53:in `map'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:53:in`visit_children'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:27:in `visit_children'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:39:in`with_environment'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:26:in `visit_children'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:37:in`visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:47:in `visit_root'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:37:in`send'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:18:in`visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:7:in `send'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:7:in`visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/root_node.rb:20:in `render'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/engine.rb:291:in`_render'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/engine.rb:238:in `render'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/compiler.rb:131:in`compile'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/compiler.rb:117:in `timed'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/compiler.rb:130:in`compile'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/logger.rb:45:in `red'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/compiler.rb:129:in`compile'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/compiler.rb:109:in `compile_if_required'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/compiler.rb:96:in`run'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/compiler.rb:94:in `each'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/compiler.rb:94:in`run'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/compiler.rb:117:in `timed'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/compiler.rb:93:in`run'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/commands/update_project.rb:36:in `perform'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/commands/base.rb:18:in`execute'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/commands/project_base.rb:19:in `execute'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/exec/sub_command_ui.rb:43:in`perform!'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/lib/compass/exec/sub_command_ui.rb:15:in `run!'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/bin/compass:25
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/bin/compass:39:in`call'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7/bin/compass:39
/usr/bin/compass:19:in `load'
/usr/bin/compass:19
*/

**Comment by scottdavis** [comment]
@ericam did you make a failing test for this?

**Comment by mirisuzanne** [comment]
Nope. But I can.

**Comment by scottdavis** [comment]
check one in and ill work on it .. im bored and its raining

**Comment by mirisuzanne** [comment]
Ok, so I can commit the sass, but since it throws an error I don't have the correct output code for the other end of the test. I suppose I could run all the math by hand, but it'd take a while and I couldn't do it right now. Is that still helpful to you?

**Comment by mirisuzanne** [comment]
All I'd be doing is adding:

```
.forced-fluid {
  @include column-grid-background(12, 2em, 1em, 1em, $grid-background-column-color, $grid-background-gutter-color, true);
}
```

to the grid_background.scss test.

**Comment by scottdavis** [comment]
ok ill do it =p

**Comment by scottdavis** [comment]
this seems to be a problem with ruby's shitty handling of decimals

**Comment by scottdavis** [comment]
https://gist.github.com/aa435a04493e8e84d6bd

useing the BigDecimal class to to the compair seems to kill the error but i can't verify what the output should be

heres the test output of the failing tests

https://gist.github.com/ef4b740c0a99b6f59902
and:
https://gist.github.com/a1c1c176384493d3b68d

**Comment by mirisuzanne** [comment]
That output looks right to me. If you check it in, I'll run some live tests and make sure it's all working the way it should.

**Comment by scottdavis** [comment]
done
https://github.com/chriseppstein/compass/commit/d845c4d48614fb57302054914d722850e4290bf8

**Comment by mirisuzanne** [comment]
perfect. well solved!

I fixed all the related tests and pushed back.

closed by: 3c86dfa0b3dcb4bae422fd80a26c595fd565a992

**Comment by mirisuzanne** [comment]
I was wrong. Somehow I just hit the exact same error again by changing the column-width argument from 2em to 4em. Not sure why that would make a difference. Guess I should have done more testing.

**Comment by mirisuzanne** [comment]
actually a slightly different problem:

```
Color stops must be specified in increasing order. 50.8196721311475 came after 50.8196721311476
```

note the very last digit.

**Comment by scottdavis** [comment]
Stack trace?

Scott Davis

**Comment by mirisuzanne** [comment]
/Users/eric/Sites/_misc/test/sass/screen.scss:4
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/sass_extensions/functions/gradient_support.rb:294:in `color_stops_in_percentages'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/sass_extensions/functions/gradient_support.rb:288:in`map'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/sass_extensions/functions/gradient_support.rb:288:in `color_stops_in_percentages'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/sass_extensions/functions/gradient_support.rb:277:in`grad_color_stops'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/sass_extensions/functions/gradient_support.rb:152:in `to_owg'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/sass_extensions/functions/cross_browser_support.rb:59:in`send'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/sass_extensions/functions/cross_browser_support.rb:59:in `prefix'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/sass_extensions/functions/cross_browser_support.rb:55:in`prefix'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/sass_extensions/functions/cross_browser_support.rb:54:in `map'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/sass_extensions/functions/cross_browser_support.rb:54:in`prefix'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/sass_extensions/functions/cross_browser_support.rb:41:in `_owg'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/script/funcall.rb:80:in`send'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/script/funcall.rb:80:in `_perform'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/script/node.rb:40:in`perform'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:215:in `visit_prop'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:37:in`send'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:18:in`visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:53:in `visit_children'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:53:in`map'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:53:in `visit_children'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:27:in`visit_children'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:39:in `with_environment'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:26:in`visit_children'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:127:in`visit_if'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:37:in `send'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:37:in`visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:18:in `visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:200:in`visit_mixin'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:200:in `map'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:200:in`visit_mixin'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:39:in `with_environment'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:200:in`visit_mixin'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:37:in `send'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:37:in`visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:18:in `visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:200:in`visit_mixin'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:200:in `map'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:200:in`visit_mixin'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:39:in `with_environment'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:200:in`visit_mixin'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:37:in `send'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:37:in`visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:18:in `visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:53:in`visit_children'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:53:in `map'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:53:in`visit_children'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:27:in `visit_children'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:39:in`with_environment'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:26:in `visit_children'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:37:in`visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:47:in `visit_root'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:37:in`send'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:18:in`visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:7:in `send'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/visitors/perform.rb:7:in`visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/tree/root_node.rb:20:in `render'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/engine.rb:291:in`_render'
/Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.253/lib/sass/../sass/engine.rb:238:in `render'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/compiler.rb:131:in`compile'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/compiler.rb:117:in `timed'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/compiler.rb:130:in`compile'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/logger.rb:45:in `red'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/compiler.rb:129:in`compile'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/compiler.rb:109:in `compile_if_required'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/compiler.rb:96:in`run'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/compiler.rb:94:in `each'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/compiler.rb:94:in`run'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/compiler.rb:117:in `timed'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/compiler.rb:93:in`run'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/commands/update_project.rb:36:in `perform'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/commands/base.rb:18:in`execute'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/commands/project_base.rb:19:in `execute'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/exec/sub_command_ui.rb:43:in`perform!'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/lib/compass/exec/sub_command_ui.rb:15:in `run!'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/bin/compass:25
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/bin/compass:39:in`call'
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.7.25.d845c4d/bin/compass:39
/usr/bin/compass:19:in `load'
/usr/bin/compass:19
*/
