### ISSUE TITLE
box-flex and display-box are order-dependent

### ISSUE THREAD

**Issue by bilts** [Compass/compass#344]
*Editing initial report.  I originally got the mixins wrong.

The box-flex sass mixin sets the element to be display:block.  If this comes after a display-box declaration, it overwrites the display: attribute.  It seems inappropriate for box-flex to declare display:block, since you'd very often want display:box in this case.

**Comment by mirisuzanne** [comment]
I don't see that reflected in the code anywhere. There should never be an output of `display: block` from any flex-box related mixin. Here's the code for those two:

```
@mixin display-box {
  @include experimental-value(display, box,
    -moz, -webkit, not -o, not -ms, not -khtml, official
  );
}

@mixin box-flex(
  $flex: $default-box-flex
) {
  @include experimental(box-flex, $flex,
    -moz, -webkit, not -o, not -ms, not -khtml, official
  );
}
```

Are you possibly overriding those mixins with some of your own?

**Comment by chriseppstein** [comment]
The box-flex mixin used to do that, but it's been removed in v0.11.
