### ISSUE TITLE
Allow comma-separated multiple values in CSS mixins to be nested

### ISSUE THREAD

**Issue by olivierlacan** [Compass/compass#345]
With the advent of multiple values in several CSS properties (text shadow, box shadow, background-images, etc) I find myself  driven to nest each value in order to increase future legibility.

This seems adequate for Compass & Sass since we tend to write longer properties with SassScript and the new CSS3 mixins.

This:

```
+background-image(
  linear-gradient(
    darken(desaturate($blue, 15%), 20%),
    darken(desaturate($blue, 10%), 5%)
  )
)

+box-shadow(
  rgba(0,0,0,.4) -1px 0px 2px inset,
  rgba(0,0,0,.4) 1px 0px 2px inset,
  rgba(0,0,0,.5) 0 1px 4px inset,
  rgba(0,0,0,.5) 0 -1px 2px inset
)
```

is much more legible than this:

```
+background-image(linear-gradient(darken(desaturate($blue, 15%), 20%), darken(desaturate($blue, 10%), 5%)))
+box-shadow(rgba(0,0,0,.4) -1px 0px 2px inset, rgba(0,0,0,.4) 1px 0px 2px inset, rgba(0,0,0,.5) 0 1px 4px inset, rgba(0,0,0,.5) 0 -1px 2px inset)
```

Thanks again for the great work on 0.11.

**Comment by scottdavis** [comment]
This is more of a sass issue then compass

Scott Davis

**Comment by olivierlacan** [comment]
I was wondering about that. Will post to Sass's Issues then.
