### ISSUE TITLE
add possibility to disable magic sprite selectors (hover, active, target)

### ISSUE THREAD

**Issue by aurelien-baudet** [Compass/compass#346]
Hi,

Could you add a configuration variable in order to disable the automatic inclusion of sprite-selectors in sprite (file _base.scss).
Indeed, for the project I am working on, the automatic selectors create problems with Dojo styles because :hover is more specific than .dijitTabHover.

Thank you

**Comment by scottdavis** [comment]
https://github.com/chriseppstein/compass/commit/6b884d34c3317bd845d6250e6ec41ed59df4d4bf
