### ISSUE TITLE
Blueprint framework incorrect import

### ISSUE THREAD

**Issue by adamsalter** [Compass/compass#35]
The code generated from the blueprint module is incorrect, it generates the following CSS:

<pre>
/* line 22, ../../../../../.gem/ruby/1.8/gems/chriseppstein-compass-0.8.8/frameworks/blueprint/stylesheets/blueprint/modules/_typography.sass */
body.bp body {
  line-height: 1.5;
  font-family: Helvetica Neue, Arial, Helvetica, sans-serif;
  color: #333333;
  font-size: 75%; }
</pre>

`body.bp body` can't be matched...

**Comment by chriseppstein** [comment]
fixed in v0.8.9

With a better fix in 0.10.0 coming.

**Comment by adamsalter** [comment]
ok thanx ;)
