### ISSUE TITLE
Transitions should accept multiple transitions separated by commas

### ISSUE THREAD

**Issue by Kronuz** [Compass/compass#350]
The css3/transitions are currently not accepting a comma separated list of multiple transitions...  I've created a patch to fix this, much in the same way shadow-box does it: https://gist.github.com/937098

**Comment by scottdavis** [comment]
can you fork and send a pull? its just easier to merge that way and you get credit =D

**Comment by Kronuz** [comment]
Sure, no problem... I've added a pull request :)

**Comment by scottdavis** [comment]
closed since new issue is open with pull request
