### ISSUE TITLE
Compass extension template defaults to .sass

### ISSUE THREAD

**Issue by imathis** [Compass/compass#351]
Should `compass create my_extension --using compass/extension` instead default to .scss? I think that's the standard we're pointing folks to.

**Comment by chriseppstein** [comment]
I suspect these users are savvy enough to know they can use both syntaxes. But if you'd like to change it, go ahead.

**Comment by scottdavis** [comment]
How about we ask?

**Comment by chriseppstein** [comment]
nah. at most, we should add a message that gets printed out as part of the installer

**Comment by scottdavis** [comment]
better yet i made it respond to -x so you can pass a syntax option 

830a44868a6dd2bc642a1f62b822e40e3d4f2a30
