### ISSUE TITLE
Extensions do not seem load from ~/.compass/extensions

### ISSUE THREAD

**Issue by imathis** [Compass/compass#353]
I followed the compass extension tutorial with the latest version of compass. I created a symlink ~/.compass/extensions/fancy-buttons which points to my local development directory for fancy-buttons. I've installed my gems with bundler such that I must prefix my commands with bundle exec (if that matters). When I type `bundle exec compass frameworks` I only see blueprint and compass being listed as available frameworks and patterns.

**Comment by imathis** [comment]
I'm an idiot. So that's good. I didn't realize I failed to change the line:

Compass::Frameworks.register('my_extension', :stylesheets_directory => stylesheets_dir, :templates_directory => templates_dir)
to:

Compass::Frameworks.register('fancy-buttons', :stylesheets_directory => stylesheets_dir, :templates_directory => templates_dir)

The way the framework is listed last and the fact that I wasn't looking for the `my_extension` framework caused me to believe that it wasn't being registered. All better now.

**Comment by scottdavis** [comment]
lol
