### ISSUE TITLE
Failing test after gradient refractor ruby

### ISSUE THREAD

**Issue by scottdavis** [Compass/compass#354]
https://gist.github.com/80eae6373e078393f408

<pre>
Sass::SyntaxError: wrong number of arguments (0 for 1) for `-svg'
    /Users/sdavis/Work/compass/frameworks/compass/stylesheets/compass/css3/_images.scss:21:in `background'
    test/fixtures/stylesheets/compass/sass/gradients.sass:8
</pre>

**Comment by chriseppstein** [comment]
fixed by 5962a85a99ba22b7332992e0c7f49576a95bd1a7
