### ISSUE TITLE
Compass not autocompiling with pow

### ISSUE THREAD

**Issue by johnrees** [Compass/compass#358]
I've noticed that when I run my development sites using a .dev domain with [pow](http://pow.cx) my .scss files aren't being auto compiled like they were with

```
rails s
```

Is there a quick/easy workaround for this?

Thanks

**Comment by chriseppstein** [comment]
are you using edge rails?

**Comment by johnrees** [comment]
Rails 3.0.5
and
Compass 0.11.1

Should I drop back a bit?

Thanks Chris

**Comment by johnrees** [comment]
Nevermind, reinstalling pow has fixed it. Sorry about that!

**Comment by chriseppstein** [comment]
And if you start via `rails s` now does it still work? If so, I would consider this to be a pow bug.

**Comment by chriseppstein** [comment]
ok :) Good to know.
