### ISSUE TITLE
sass files not being rendered.

### ISSUE THREAD

**Issue by maca** [Compass/compass#359]
I started a new rails 3.0.7 app and ran 

```
   $ compass init rails . -r susy -u susy
```

But no stylesheet is being rendered into public/stylesheets and I get this error:

```
   ActionController::RoutingError (No route matches "/stylesheets/screen.css"):
```

**Comment by chriseppstein** [comment]
sorry to ask the simple questions, but did you add compass to your gemfile? Did you restart your app? Did you make a request to a controller?

**Comment by maca** [comment]
Well first thing was adding compass and compass-susy-plugin to my gemfile, then I ran the generator (compass init), I've done that before for other apps an was enough to get me going.

I read a thread on the sass github page that informed me that the new convention is for sass files to go into app/views/stylesheets and have a controller and action for each sass template but the problem is though I had my sass templates in views/stylesheets named *.css.sass the controller couldn't render them because apparently there was no handler for sass:

```
      ActionView::MissingTemplate (Missing template stylesheets/screen with {:handlers=>[:erb, :rjs, :builder, :rhtml, :rxml, :haml], 
```

My next workaround was mounting a Sinatra app and using Tilt to render the sass templates, that kind of worked (The templates where compiled) allthough I was getting this error:

```
      Sass::SyntaxError - File to import not found or unreadable: susy.sass.
      Load path: .: 
```

Again I required compass and required susy in the config/compass file

**Comment by maca** [comment]
I ressorted to compass 0.10.4 and it is working now, with a few deprecation warnings.

**Comment by chriseppstein** [comment]
I asked three questions and you somehow avoided answering them.

**Comment by maca** [comment]
Yeah, I added compass and compass susy to my gemfile, restated the app and made a controller request

**Comment by chriseppstein** [comment]
It works for me. Here's a transcript of what I did: https://gist.github.com/943762

Please provide similar steps to reproduce if you continue to have the problem.

**Comment by maca** [comment]
Tomorrow I will try to replicate, thanks!
