### ISSUE TITLE
Merb: overwrites existing :template_location setting

### ISSUE THREAD

**Issue by merbjedi** [Compass/compass#36]
Compass seems to overwrite any existing Merb::Plugins.config[:sass][:template_location] settings. This is fine if its set to a string, however, if its set to another hash, it should retain those mappings.

**Comment by merbjedi** [comment]
Fixed here:
http://github.com/merbjedi/compass/commit/ad0cbee36bdc084871648705f3bd2203e3bbed78

**Comment by chriseppstein** [comment]
merged to edge for the next release.
