### ISSUE TITLE
Image doesn't fill sprite horizontally for repeat-x background

### ISSUE THREAD

**Issue by curvedmark** [Compass/compass#362]
If we have this code

```
$sprites: sprite-map("*.png", $new-position: 0%, $new-spacing: 0, $new-repeat: repeat-x);

div {
    background: sprite($sprites, my-bg) repeat-x;
}
```

and my-bg.png isn't the widest image in the sprite, it isn't filled horizontally in the sprite, which leaves transparent stripes in the background when repeated.

I guess this happens to repeat-y background as well (haven't tested).

Also, I'm wondering why the $new-repeat parameter is needed in the sprite-map function? I feel it makes a lot more sense to let the sprite function have it, so that compass can decide which image should be filled repeatedly and which shouldn't.

**Comment by scottdavis** [comment]
your going to have to be more specific are you upgrading from lemonaid?

**Comment by curvedmark** [comment]
No, never installed lemonaid. I first installed 0.11.beta.7 and then updated to 0.11.1.

**Comment by scottdavis** [comment]
can you try against master branch i just found a bug that was causing options to not get set on the image classes.

**Comment by curvedmark** [comment]
It seems nothing has changed.

I ran`./bin/compass create ~/test`, put previous code in screen.scss, put in images and then ran `./bin/compass compile ~/test`, and images were not filled horizontally.

But I guess I might have done something wrong. After I pulled the project, checked out master branch, running `./bin/compass --version` returns `Compass 0.11.1 (Antares)` which is same as my installed version of compass. Did i do something wrong?

**Comment by scottdavis** [comment]
no the version shouldn't have changed but the code should have if you pulled master. would you mind creating a spall test app that i can use in order to get this working? ive never actually generated a sprite in this way. which is embarising but hey everyday you learn something new heh

**Comment by scottdavis** [comment]
haha i just realized what you are doing wrong. $`<image-name>`-repeat. is your image named "new"? the docs need to be clearer

**Comment by curvedmark** [comment]
Oh, man. You are absolutely right! I didn't know the "new" part was for individual sprites. Now everything works perfectly. Thank you so much. :)

**Comment by curvedmark** [comment]
I'm sorry but I just find out one thing that is counter-intuitive:

```
$sprites: sprite-map("*.png", $bg-repeat: repeat-x);

div {
    background: sprite($sprites, bg) repeat-x;
}
```

Why is the "repeat-x" in div's background rule necessary? Since it's already specified in sprite-map.
In what circumstance would a user want to repeat the img in sprite map and at the same time don't want to that sprite map to be repeated in the page, knowing the fact that sprite map's dimension is variable?

Oh, another minor issue, `sprite-map("*.png")` throws `TypeError on line ["136"] of /usr/local/rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.1/lib/compass/sass_extensions/sprites/base.rb: can't convert nil into String`. It has to be `sprite-map("./*.png")`. Should I file a new issue for it or is it a correct behavior?

Thanks.

**Comment by scottdavis** [comment]
"Should I file a new issue for it or is it a correct behavior" please!

**Comment by scottdavis** [comment]
also, its probably a vocabulary problem and your right it is counter intuitive. Im totally open to suggestions on how to make this better. The docs are also horrible for the entire spiriting section mostly because i havent had time to work on them.

**Comment by scottdavis** [comment]
<pre>
Oh, another minor issue, sprite-map("*.png") throws TypeError on line ["136"] of /usr/local/rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.1/lib/compass/sass_extensions/sprites/base.rb: can't convert nil into String. It has to be sprite-map("./*.png"). Should I file a new issue for it or is it a correct behavior?
</pre>


This is a downfall of the way the current sprite globing works. the spiriting functions assume your sprites are going to be in a subdirectory of your image folder so that your sprite file will get written out to the root of the image folder.

**Comment by scottdavis** [comment]
also keep this issue open so i remember to update the documentation

**Comment by curvedmark** [comment]
```
also, its probably a vocabulary problem and your right it is counter intuitive. Im totally open to suggestions on how to make this better. The docs are also horrible for the entire spiriting section mostly because i havent had time to work on them.
```

Thank you. I would suggest that `sprite` function also outputs repeat parameter. Would it cause problems in other places?

**Comment by scottdavis** [comment]
@chriseppstein would need to comment on that

**Comment by chriseppstein** [comment]
It seems like a conflation to link the values together at the function level. But i'm not opposed to creating a new function like `sprite-repeat($map)` that returns a repeat value and could be used by mixins or other functions for generating a more complete declaration. Also, such a change would break backwards compatibility.

**Comment by curvedmark** [comment]
`sprite-repeat` is great.

But can we also introduce a new function that basically does `sprite` + `sprite-repeat`? Otherwise the code isn't going to be petty:

```
$sprites: sprite-map("./*.png", $bg-repeat: repeat-x);

div {
    background: sprite($sprites, bg) sprite-repeat($sprites, bg);
}
```

**Comment by curvedmark** [comment]
Or maybe we could just introduce a global variable like `$enable-output-sprite-repeat`, when set to `true`, `sprite` function will also output the repeat parameter. This variable is `false` by default, so it shouldn't break backwards compatibility.

**Comment by piouPiouM** [comment]
When I declare the variable `$rx-repeat: repeat-x;` or `$rx-header-repeat: repeat-x;` before a `@import "rx/*.png;", the property`background-repeat`is not applied _via_, for example, the call to`@include rx-sprite('header');`.

Is there a connection with this bug?

Note: I use Compass 0.11.5.

**Comment by scottdavis** [comment]
its not a bug its just a feature request =)

**Comment by scottdavis** [comment]
refresh my memory is this still an issue in 0.12 if it is please let me know and ill reopen this as a new feature request
