### ISSUE TITLE
Compass 0.11.1 no longer works for homeless root users

### ISSUE THREAD

**Issue by RISCfuture** [Compass/compass#364]
Deployed the latest Compass gem and got the following error upon starting my Resque worker:

```
rake aborted!
non-absolute home
/data/emaily/shared/bundle/ruby/1.9.1/gems/compass-0.11.1/lib/compass.rb:18:in `expand_path'
/data/emaily/shared/bundle/ruby/1.9.1/gems/compass-0.11.1/lib/compass.rb:18:in `shared_extension_paths'
/data/emaily/shared/bundle/ruby/1.9.1/gems/compass-0.11.1/lib/compass/configuration/helpers.rb:105:in `discover_extensions!'
/data/emaily/shared/bundle/ruby/1.9.1/gems/compass-0.11.1/lib/compass/app_integration/rails.rb:59:in `initialize!'
/data/emaily/shared/bundle/ruby/1.9.1/gems/compass-0.11.1/lib/compass/app_integration/rails/actionpack3/railtie.rb:43:in `block in <class:Railtie>'
```

The relevant code:

``` ruby
def shared_extension_paths
  [File.expand_path("~/.compass/extensions")]
end
```

The code is being run as root on a typically-configured Linux deploy target.

**Comment by chriseppstein** [comment]
Whoops!  We'll get that patched ASAP. 

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by scottdavis** [comment]
We have a outstanding grudge against homeless users

Scott Davis

**Comment by nel** [comment]
+1 got bitten in production cause my www-data is homeless, this will also probably also fail in various case on windows. expand_path with ~ should be avoided

**Comment by yfeldblum** [comment]
Is there an upcoming release which will include this fix?

**Comment by nel** [comment]
If you use bundler you can add:

```
 gem 'compass', :git => 'https://github.com/chriseppstein/compass.git', :ref => 'ea6e15b8a455'
```

But I am also waiting for a a bug-fix release

**Comment by chriseppstein** [comment]
There will be a release very soon, until then, using the above gem
configuration is acceptable.

**Comment by fearoffish** [comment]
I'm using 0.11.6 and I'm still seeing this error.

```
/a/aether/shared/bundle/ruby/1.9.1/gems/compass-0.11.6/lib/compass.rb:20:in `expand_path': non-absolute home (ArgumentError)
from /a/aether/shared/bundle/ruby/1.9.1/gems/compass-0.11.6/lib/compass.rb:20:in `shared_extension_paths'
```

Are we still having to use the above to fix it?

**Comment by fearoffish** [comment]
Okay, found my problem, I just have no fix for it.  Somewhere after rails initialises the HOME env variable is set to '.', I can't find where though.  Funny thing is, in 0.11.6 I see you wrap the call with a 'begin' so it should catch this, if I'm right?

**Comment by pivotal-casebook** [comment]
No the begin will not save it. You need a rescue.

The problem is if something or anything is setting HOME to a relative path (not an absolute path) then expand_path will blow up. The guard clause should not only check for home but also check to see if it is absolute.

See https://github.com/chriseppstein/compass/pull/761 for a possible resolution.

**Comment by scottdavis** [comment]
status on this?

**Comment by chriseppstein** [comment]
should be good.
