### ISSUE TITLE
Passing a list of arguments to single-box-shadow fails

### ISSUE THREAD

**Issue by jleider** [Compass/compass#369]
I have a list

```
$default-vars: (#C8C8C8, 2px, 2px, 2px);
```

that I pass to single-box-shadow

```
@include single-box-shadow($default-vars);
```

however the values im passing dont override the default values set by compass. 

Instead of generating: 

```
box-shadow: 2px 2px 2px #C8C8C8;
```

I get:

```
box-shadow: 0px 0px 5px #C8C8C8, 2px, 2px, 2px; 
```

Even when I pass in all 6 variables via list the default options dont get overridden.

**Comment by chriseppstein** [comment]
Right, that doesn't work because sass doesn't yet have list -> argument globbing.

Just do this:

```
$default-vars: #C8C8C8 2px 2px 2px;
.shadowed { @include box-shadow($default-vars); }
```

**Comment by jleider** [comment]
Thats odd because I can do this:

```
$default-button-border-radius: (3px 3px);
@include border-radius($default-button-border-radius);
```

And it works as expected.

**Comment by chriseppstein** [comment]
that's because it's exactly what I told you to do with `box-shadow` :) The issue here is that you're using `single-box-shadow` which calls out each argument where as `box-shadow` does not.

**Comment by jleider** [comment]
Ah, ha didnt catch that difference. Thanks.
