### ISSUE TITLE
blueprint_semantic examples missing class .left on the p img (dog)

### ISSUE THREAD

**Issue by swingerbone** [Compass/compass#37]
the image (of the dog) in the fancy_type and liquid blueprint_semantic example pages appears to be missing a class of .left - the style is there in the generated screen.css for body.blueprint p img.left - the version on compass-style.org applies the same styling to body.blueprint p img (so it defaults to floating an image in a paragraph to float left)

This has the effect of lacking the margin styles for the image (text butts against it) in fancy_type.html and without the float:left in liquid.html the image keeps the text from flowing around it.

I imagine this is a simple fix in the sass file - but I wanted to let you know.

**Comment by chriseppstein** [comment]
Actually, this one is still just a css class that is scoped by a paragraph... I changed the markup.
