### ISSUE TITLE
Provide an option to generate png24

### ISSUE THREAD

**Issue by l4u** [Compass/compass#371]
IE6 and photoshop cs3,4 don't support indexed png8

**Comment by chriseppstein** [comment]
I suppose this is regarding sprite generation?

I need to test it using our generated sprites, but I'm pretty sure png8 works fine in IE6 -- I've used them before. Regarding CS3/4, I don't really care about supporting them, they're not browsers and generated sprites don't need to be edited.

**Comment by l4u** [comment]
IE6 rendered my sprites in a poor quality
probably it is related to the png with alpha channels?

currently I convert the sprites to RGB instead of Indexed, and use a pngfix on ie6.

**Comment by scottdavis** [comment]
what about interlacing?

**Comment by scottdavis** [comment]
https://github.com/wvanbergen/chunky_png/issues/21

https://github.com/wvanbergen/chunky_png/blob/master/lib/chunky_png/canvas/png_encoding.rb#L69

**Comment by scottdavis** [comment]
db74d8bdb36de7a778ed2ecbfb194fbddf6ab508 in 0.11.4 you will be able to send chunky png the options you want

https://github.com/wvanbergen/chunky_png/blob/master/lib/chunky_png/canvas/png_encoding.rb#L69
