### ISSUE TITLE
Add an import path option to the command line tool

### ISSUE THREAD

**Issue by MoOx** [Compass/compass#375]
Compass should have a import path option like Sass does (-I).
We can do that with the configuration file, but cannot directly with the command line option.
Can we add this ?

**Comment by chriseppstein** [comment]
Compass has this property but it's not accessible on the command line. Would you like to make a patch?

**Comment by MoOx** [comment]
I'm not a ruby coder (my first ruby script was for my first ruby gem compass-recipes), but I can try

**Comment by chriseppstein** [comment]
@MoOx I like your attitude!

**Comment by HelloGrayson** [comment]
+1 for this
