### ISSUE TITLE
$HOME/.compass/extensions autodiscovery crashes Rails under init

### ISSUE THREAD

**Issue by tessro** [Compass/compass#376]
#242 (3272dc7e5a35316dc2dc29d18430e64ab139726c) introduced a dependency on the Unix environment.  If $HOME is not set, Compass fails to load.  We're loading Compass inside Unicorn through init, which is a common use case.  $HOME is unset.

For now we are reverting to 0.10 which works fine.

It seems to me that Compass extensions that are commonly needed should be rolled into gems of their own, and bundled into each application.  Introducing ~/.compass/extensions, and loading from it by default, seems like a regression against all the work that's been done by the Bundler team to eliminate differences in environment between different development and production machines.  It's opening the door to all sorts of fun-to-debug situations, where extensions present or missing, or versions differ between machines.

Here is the relevant part of the backtrace:

```
/home/deploy/site/shared/bundle/ruby/1.8/gems/compass-0.11.1/lib/compass.rb:18:in `expand_path': couldn't find HOME environment -- expanding `~/.compass/extensions' (ArgumentError)
        from /home/deploy/site/shared/bundle/ruby/1.8/gems/compass-0.11.1/lib/compass.rb:18:in `shared_extension_paths'
        from /home/deploy/site/shared/bundle/ruby/1.8/gems/compass-0.11.1/lib/compass/configuration/helpers.rb:105:in `discover_extensions!'
```

**Comment by tomtaylor** [comment]
I'm experiencing this issue too.

**Comment by paukul** [comment]
same here. Worked around it for now by adding

```
ENV["HOME"] ||= "/var/www"
```

at the very top of application.rb for now. But that's not a very satisfying "solution" in any way

**Comment by ryenski** [comment]
@paukul's solution worked for me. Except I put it in my production.rb file.

**Comment by MoOx** [comment]
I'm launching compass from a PHP called process, so I have the same issue.
For now I prefix my compass call with `'export HOME=' . $_SERVER['DOCUMENT_ROOT'] . ';'`

**Comment by bhollis** [comment]
This is a duplicate of https://github.com/chriseppstein/compass/issues/364 and it's already been fixed in master.

**Comment by tessro** [comment]
@bhollis thanks for the catch. Closing.
