### ISSUE TITLE
undefined method `find' for #<Compass::SpriteMap

### ISSUE THREAD

**Issue by l4u** [Compass/compass#379]
vendor/bundle/ruby/1.9.1/gems/sass-3.1.1/lib/sass/plugin/staleness_checker.rb:169:in `tree'
vendor/bundle/ruby/1.9.1/gems/sass-3.1.1/lib/sass/plugin/staleness_checker.rb:159:in`compute_dependencies'
vendor/bundle/ruby/1.9.1/gems/sass-3.1.1/lib/sass/plugin/staleness_checker.rb:142:in `dependencies'
vendor/bundle/ruby/1.9.1/gems/sass-3.1.1/lib/sass/plugin/staleness_checker.rb:119:in`dependencies_stale?'
vendor/bundle/ruby/1.9.1/gems/sass-3.1.1/lib/sass/plugin/staleness_checker.rb:154:in `block in dependency_updated?'
vendor/bundle/ruby/1.9.1/gems/sass-3.1.1/lib/sass/plugin/staleness_checker.rb:119:in`each'
vendor/bundle/ruby/1.9.1/gems/sass-3.1.1/lib/sass/plugin/staleness_checker.rb:119:in `any?'
vendor/bundle/ruby/1.9.1/gems/sass-3.1.1/lib/sass/plugin/staleness_checker.rb:119:in`dependencies_stale?'
vendor/bundle/ruby/1.9.1/gems/sass-3.1.1/lib/sass/plugin/staleness_checker.rb:154:in `block in dependency_updated?'
vendor/bundle/ruby/1.9.1/gems/sass-3.1.1/lib/sass/plugin/staleness_checker.rb:119:in`each'
vendor/bundle/ruby/1.9.1/gems/sass-3.1.1/lib/sass/plugin/staleness_checker.rb:119:in `any?'
vendor/bundle/ruby/1.9.1/gems/sass-3.1.1/lib/sass/plugin/staleness_checker.rb:119:in`dependencies_stale?'
vendor/bundle/ruby/1.9.1/gems/sass-3.1.1/lib/sass/plugin/staleness_checker.rb:154:in `block in dependency_updated?'
vendor/bundle/ruby/1.9.1/gems/sass-3.1.1/lib/sass/plugin/staleness_checker.rb:75:in`call'
vendor/bundle/ruby/1.9.1/gems/sass-3.1.1/lib/sass/plugin/staleness_checker.rb:75:in `stylesheet_modified_since?'
vendor/bundle/ruby/1.9.1/gems/sass-3.1.1/lib/sass/plugin/staleness_checker.rb:63:in`stylesheet_needs_update?'
vendor/bundle/ruby/1.9.1/gems/sass-3.1.1/lib/sass/plugin/compiler.rb:180:in `block (2 levels) in update_stylesheets'
vendor/bundle/ruby/1.9.1/gems/sass-3.1.1/lib/sass/plugin/compiler.rb:175:in`each'
vendor/bundle/ruby/1.9.1/gems/sass-3.1.1/lib/sass/plugin/compiler.rb:175:in `block in update_stylesheets'
vendor/bundle/ruby/1.9.1/gems/sass-3.1.1/lib/sass/plugin/compiler.rb:173:in`each'
vendor/bundle/ruby/1.9.1/gems/sass-3.1.1/lib/sass/plugin/compiler.rb:173:in `update_stylesheets'
vendor/bundle/ruby/1.9.1/gems/sass-3.1.1/lib/sass/plugin.rb:81:in`update_stylesheets'
vendor/bundle/ruby/1.9.1/gems/sass-3.1.1/lib/sass/plugin.rb:54:in `check_for_updates'
vendor/bundle/ruby/1.9.1/gems/sass-3.1.1/lib/sass/plugin/rack.rb:51:in`call'

**Comment by l4u** [comment]
when i restart webrick, it runs properly

**Comment by scottdavis** [comment]
are you on windows? or is there a reason you are running 1.9.1?

**Comment by l4u** [comment]
$ruby -v
ruby 1.9.2p180 (2011-02-18 revision 30909) [x86_64-linux]

compass-0.11.1

Sometimes when I add a graphic file in the sprite folder, this error occurs.
But I couldn't reproduce it.

**Comment by scottdavis** [comment]
compass standalone or rails integration?

**Comment by wuyuntao** [comment]
Same problem happens to me.

ree 1.8.7, rails 3.0.7 and compass 0.11.1

**Comment by scottdavis** [comment]
im getting this also now and im working on getting it fixed

**Comment by scottdavis** [comment]
try against the current master and see if you get the same error

**Comment by gumayunov** [comment]
It works from master branch! Thanks!

**Comment by scottdavis** [comment]
ok thanks closing this then!
