### ISSUE TITLE
remove "Loading haml-edge gem." message

### ISSUE THREAD

**Issue by patrickxb** [Compass/compass#38]
Is the

```
$stderr.puts "Loading haml-edge gem."
```

in dependencies.rb necessary?  If so, does it have to go to stderr?  Why not stdout?

It's making all my cron scripts that send emails if there are any errors send me emails constantly...and every time I run tests or anything I see it too...

Thanks.

**Comment by chriseppstein** [comment]
Now that we have [Bundler](http://github.com/wycats/bundler/tree/master), I think I can just make compass do a basic require of haml and leave what to load to the user...
