### ISSUE TITLE
compass init rails not asking anything

### ISSUE THREAD

**Issue by mvilrokx** [Compass/compass#383]
I just installed compass and I am trying to use it on a new rails (3.0.7) project.  I just ran (as per the doc):

$ gem install compass
$ rails new my_project
$ compass init rails my_project --using blueprint

Apparently this is suppose to ask me:

Compass recommends that you keep your stylesheets in app/stylesheets
  instead of the Sass default location of public/stylesheets/sass.
  Is this OK? (Y/n)

and

Compass recommends that you keep your compiled css in public/stylesheets/compiled/
  instead the Sass default of public/stylesheets/.
  However, if you're exclusively using Sass, then public/stylesheets/ is recommended.
  Emit compiled stylesheets to public/stylesheets/compiled/? (Y/n)

but it is asking neither.

I just get this:

Congratulations! Your rails project has been configured to use Compass.
Just a couple more things left to do.

Add the following to your Gemfile:

```
gem "compass", ">= 0.11.1"
```

Then, make sure you restart your server.

Sass will automatically compile your stylesheets during the next
page request and keep them up to date when they change.

Now add these lines to the head of your layout(s):

<head>
  <%= stylesheet_link_tag 'screen.css', :media => 'screen, projection' %>
  <%= stylesheet_link_tag 'print.css', :media => 'print' %>
  
</head>

It does put the scss files in my app folder, but it does not compile them into the public/stylesheets/compiled/ folder.

**Comment by chriseppstein** [comment]
Rails will compile your stylesheets when you make the first request to a controller. Why it didn't prompt you for directories is not clear. But you can edit your config if you want something different. 

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by mvilrokx** [comment]
So I don't need "compass watch"?  Is that just for non-rails projects?

**Comment by greenz** [comment]
I see the same issue. If i am outside of the rails project directory it will prompt me but once i do from the rails directory no prompt.

compass init rails . --syntax sass --using 960

**Comment by chriseppstein** [comment]
Sorry. I forgot that in rails 3, I have disabled these prompts. We use rails
3.1 conventions now.

**Comment by mvilrokx** [comment]
Could you please elaborate what those conventions are?

Also, do I need to run "compass watch"? Is that just for non-rails projects?

**Comment by chriseppstein** [comment]
Source files:

```
<Rails.root>/app/stylesheets
<Rails.root>/app/javascripts
```

Generated css:

```
<Rails.root>/public/stylesheets
```

And you can use compass watch if you want, but you should disable rails-based compilation using:

```
Sass::Plugin.options[:never_update] = true
```

Otherwise you'll be doing it twice.
