### ISSUE TITLE
"stack level too deep" error breaks sass --watch when adding @import "compass/css3/pie";

### ISSUE THREAD

**Issue by ghost** [Compass/compass#387]
I apologize in advance if this isn't in fact a Compass issue, but with so many moving parts I have to start somewhere.

While working with SASS I use the sass --watch command to automatically update my .css files as I edit the .scss files.

I already have the following in my base.scss file:

@import "compass/css3/border-radius";
@import "compass/css3/box-shadow";

As soon as I add:

@import "compass/css3/pie";

my sass --watch immediately breaks, with a "stack level too deep" error:

FSSM::CallbackError: update - //Users/me/project/static/scss/_base.scss: stack level too deep

Any clues?

Versions:
ruby 1.8.7

chunky_png (1.2.0)
compass (0.11.1)
fssm (0.2.7)
haml (3.1.1)
maruku (0.6.0)
rubygems-update (1.8.2)
sass (3.1.1 ruby)
syntax (1.0.0)
yard (0.6.8)

**Comment by ghost** [comment]
I've had problems in the past with duplicate gems being installed, and sure enough, I had duplicate sass gems. After some gem uninstalling, then re-installing based on the Compass/PIE group discussion at http://groups.google.com/group/compass-users/browse_thread/thread/5064e92d13285289?pli=1 my error seems to have simplified a bit to:

> > > Sass is watching for changes. Press Ctrl-C to stop.
> > > SystemStackError: stack level too deep
> > >   Use --trace for backtrace.

My local gems have changed. Do any of the following raise any flags?

**\* LOCAL GEMS ***

chunky_png (1.1.2)
compass (0.11.beta.7)
fssm (0.2.7)
haml (3.1.1)
maruku (0.6.0)
rubygems-update (1.8.2)
sass (3.2.0.alpha.4)
syntax (1.0.0)
yard (0.6.8)

**Comment by scottdavis** [comment]
have you run it with --trace?

**Comment by ghost** [comment]
This is the output with --trace. Does this imply I'm having trouble with the version of sass I'm running?

$ sass --watch --trace static/scss:static/css

> > > Sass is watching for changes. Press Ctrl-C to stop.
> > > /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.4/bin/../lib/sass/../sass/tree/import_node.rb:45:in `import': stack level too deep (SystemStackError)
> > >     from /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.4/bin/../lib/sass/../sass/tree/import_node.rb:25:in`imported_file'
> > >     from /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.4/bin/../lib/sass/../sass/tree/import_node.rb:34:in `css_import?'
> > >     from /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.4/bin/../lib/sass/../sass/tree/visitors/perform.rb:139:in`visit_import'
> > >     from /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.4/bin/../lib/sass/../sass/tree/visitors/base.rb:37:in `send'
> > >     from /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.4/bin/../lib/sass/../sass/tree/visitors/base.rb:37:in`visit'
> > >     from /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.4/bin/../lib/sass/../sass/tree/visitors/perform.rb:18:in `visit'
> > >     from /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.4/bin/../lib/sass/../sass/tree/visitors/perform.rb:145:in`visit_import'
> > >     from /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.4/bin/../lib/sass/../sass/tree/visitors/perform.rb:145:in `map'
> > >      ... 3002 levels...
> > >     from /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.4/bin/../lib/sass/../sass/exec.rb:21:in`parse!'
> > >     from /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.4/bin/sass:8
> > >     from /usr/bin/sass:19:in `load'
> > >     from /usr/bin/sass:19

**Comment by ghost** [comment]
I'm not even sure if this was the best place to ask, but I did want to report back that I've given up on this. PIE.htc is extremely easy to use without SASS (and Compass) but the environment I'm doing work in is all SASS'd out, so I was attempting to use PIE.htc "the Compass/SASS way".

For whatever reason, my original problem remains. The addition of "pie.scss" and a "@import "compass/css3/pie";" in my _base.scss immediately breaks my ability to use sass --watch.

Meanwhile, I can easily just add a reference to PIE.htc in my .scss files like so:

```
@include border-radius(5px);
@include box-shadow(#333, 0, 0, 20px, -6px);
behavior: url(/static/css/PIE.htc);
```
