### ISSUE TITLE
960.gs native support

### ISSUE THREAD

**Issue by greenz** [Compass/compass#389]
I would like to request a feature that enables 960.gs as a optional grid system when first installing initializing compass such as 
--using blueprint.

**Comment by scottdavis** [comment]
https://github.com/chriseppstein/compass-960-plugin

?

**Comment by greenz** [comment]
That is an additional gem that you have to download. When you do gem install compass it automatically comes with blueprint all you have to do is run --using blueprint when init your project. There is no seamless integration with 960.gs you have to d/l the plugin a) init the project b) edit the compass.rb file to include require 960 c) init the compass project again using 960. There are 3 additional steps you have to take in order to get 960 to function properly. Just thought I would ask as a beginner trying to learn css framework and noticing the additional steps needed to enable 960.gs

**Comment by nathos** [comment]
@greenz from the 960 plugin README, just use: 

`compass create -r ninesixty my_project --using 960`  to create a new 960.gs-based project.

**Comment by scottdavis** [comment]
This is not going to be included in compass and will remain a plugin

**Comment by albertovilla** [comment]
The project seems to have moved here: https://github.com/nextmat/compass-960-plugin
