### ISSUE TITLE
UTF-8 character in font-face mixin causing compile error

### ISSUE THREAD

**Issue by sullimander** [Compass/compass#390]
This was fixed in 0.10.6, but is back in 0.11.1.  Looks like the fix for the following issue was reverted somewhere along the line.

https://github.com/chriseppstein/compass/issues/196

The better fix would be to remove the UTF-8 character from the comment on line 40 of the file.

Thanks
Ryan

**Comment by morgoth** [comment]
duplicate of https://github.com/chriseppstein/compass/issues/377
