### ISSUE TITLE
Sass-cache location no longer customizable

### ISSUE THREAD

**Issue by sethbro** [Compass/compass#391]
Working on a Rails 3 project, I have tried to change the location of the sass-cache directory by setting both _cache_dir_ (as mentioned in 0.10.0 release notes) and _:cache_location_ in the _sass_options_ hash. Regardless, Compass stubbornly creates a .sass-cache file in the main project directory whenever it compiles.

**Comment by he8us** [comment]
Same for me.
Mac OS X w/ Compass 0.11.1

**Comment by he8us** [comment]
Correction: cache_path did the trick.

All xxx_dir were renamed to xxx_path in 0.10.5 (http://compass-style.org/CHANGELOG/)

**Comment by sethbro** [comment]
Good to know. Thanks, he8us.
