### ISSUE TITLE
typo on callback function

### ISSUE THREAD

**Issue by dryman** [Compass/compass#400]
lib/compass/compiler.rb
156:      Compass.configuration.run_callback(:styesheet_error, sass_filename, formatted_error)

styesheet_error
should be
stylesheet_error

There is a missing **l** at **stye**

**Comment by scottdavis** [comment]
sounds like yet another thing that needs a test written GAH i hate finding these ill get this fixed

**Comment by scottdavis** [comment]
i take that back there is a test its just commented out https://github.com/chriseppstein/compass/blob/stable/test/integrations/compass_test.rb#L31

**Comment by dryman** [comment]
Thanks for super fast reply!
BTW
'styesheet' typo only appears at this line. It is double checked via find and grep.
