### ISSUE TITLE
global configuration for sprite generation

### ISSUE THREAD

**Issue by naltatis** [Compass/compass#406]
is there a way to specify spacing between sprites globally?

If i read this correctly http://compass-style.org/reference/compass/helpers/sprites/#sprite-map I have to pass my options into every sprite-map.

Setting the default spacing globally would be nice.

**Comment by hagenburger** [comment]
How many sprite-maps do you have? Usually it’s 1 or 2 per project for me.

Setting the spacing globally would be possible. But this results in bigger file sizes and (more important) uncompressed memory usage in the browsers. You should set it per image (not per map) if possible to get the best results.

**Comment by naltatis** [comment]
I guess i will end up with 4-5 sprites.

Setting the spacing is necessary to support mobile webkit. When you zoom in or out, the browser uses the surrounding pixels to scale the background images. So you get a fine line at the top and bottom of your image.

I know that it uses more memory, but I guess there is no other way to avoid this effect.

**Comment by scottdavis** [comment]
seems justified ill add it to the list
