### ISSUE TITLE
cannot compile sass files with relative sass_dir.

### ISSUE THREAD

**Issue by Phize** [Compass/compass#409]
Compass(sass?) cannot compile sass files when relative path is set to sass_dir.

config.rb:
http_path = "/"
css_dir = "stylesheets"
sass_dir = "../sass"
images_dir = "images"
javascripts_dir = "javascripts"

command:
$ compass init

output:
directory ../sass/
   create ../sass/screen.scss
   create ../sass/print.scss
   create ../sass/ie.scss
Nothing to compile. If you're trying to start a new project, you have left off the directory argument.
Run "compass -h" to get help.

**Comment by scottdavis** [comment]
using the latest compass?

**Comment by Phize** [comment]
Yes, I'm using the latest release 0.11.1.
When I set absolute path to project_path, relative sass_dir also works well.
(But default project_path is '.', so relative sass_dir doesn't work alone.)

[added] sorry, I closed this thread by mistake, then I reopened.
