### ISSUE TITLE
Sass compliation error produces inifite loop in Windows locking the sass file

### ISSUE THREAD

**Issue by dotnetchris** [Compass/compass#41]
Anytime compass is set on watch mode and a sass file is updated that causes a sass compilation error compass will become locked in an infinite loop trying to compile the file. During this loop the file is locked for writing so it can never be fixed until ctrl+c is issued.

**Comment by chriseppstein** [comment]
Fixed in 0.8.13. Just released.

**Comment by dotnetchris** [comment]
I can confirm this issue is resolved.

**Comment by frostius** [comment]
I am having a very similar problem (Win7x64, sass v3.2.7) with the exception that the file is not locked. When the compile fails, the watch process loops infinitely attempting to compile it.  

The compile generates a .css file (containing the error message) that has a later timestamp than the .scss file, so its rather odd that the watch process keeps trying.
