### ISSUE TITLE
Sprite optimization

### ISSUE THREAD

**Issue by vad** [Compass/compass#410]
It seems impossible to run an image optimizer automatically on the generated sprites.

It would be handy to have a setting in config.rb to specify a CLI command (with interpolation for input name, output name)

**Comment by scottdavis** [comment]
when the new packing implementation goes live i have set up chunky png to use maximum compression so using a 3rd party will not be necessary. unless you think compression level should be an option?

**Comment by vad** [comment]
usually i use imgopt, which does a few optimization:

> My script piggybacks on the excellent work done by optipng, advpng and pngout. Now, I could go into a long explanation about how one of these (pngout) is good because it has a proprietary deflate algorithm that’s superior to zlib, while another is great at optimizing IDAT order (optipng), but the bottom line is that running all three of these utilities on your PNG files will produce smaller files than any one of them separately.

http://lyncd.com/2009/03/imgopt-lossless-optimize-png-jpeg/#whatwhy

Do you think is useless? I don't know what chunky_png does.

**Comment by scottdavis** [comment]
touche. chunky png uses zlib but in your compass.rb config file you can add

<pre>
on_sprite_saved do |filename|
  `run some command on #{filename}`
end
</pre>

**Comment by scottdavis** [comment]
http://compass-style.org/help/tutorials/configuration-reference/#callbacks

**Comment by scottdavis** [comment]
actually this would make a great extension

**Comment by vad** [comment]
thank you! it would be good to have an extension to do this, but i don't know ruby...

**Comment by verlok** [comment]
Is this thing of the callbacks still supported? I can't see the documentation page online anymore...
