### ISSUE TITLE
Request: Don't use paths for compass "built-in" mixins

### ISSUE THREAD

**Issue by timmfin** [Compass/compass#413]
We're using Compass for a relatively big web app with a few different developers. One thing that can be annoying is needless compiled CSS churn based on comment-only changes. Such as:

```
-/* line 22, ../../../../../../../../.gem/ruby/1.8/gems/compass-0.11.1/frameworks/compass/stylesheets/compass/utilities/general/_clearfix.scss */
+/* line 22, ../../../../../../../../../../Library/Ruby/Gems/1.8/gems/compass-0.11.1/frameworks/compass/stylesheets/compass/utilities/general/_clearfix.scss */
```

I assume this happened because different developers have installed Compass differently (globally vs in their home directory).

To prevent this from happening every commit, maybe it would be helpful to show a different kind of line number comment for all of the built in mixins. How about ....

```
/* From =clearfix  imported from @import "compass/utilities/general/clearfix" */
```

ps: Yes we check in the compiled CSS output. That way we don't have to make other non-UI developers have to install and run Compass to run the app. Also, it prevents us from having to run the compile step when we deploy to production.

**Comment by chriseppstein** [comment]
Line comments are a development feature. If you are checking in your CSS you should do so using the education environment which disables line comments by default
