### ISSUE TITLE
When using @media bubbling, @extend requires a local selector

### ISSUE THREAD

**Issue by imathis** [Compass/compass#416]
# articles {

  @media only screen and (min-width: 480px) { > article { @extend .foo; } } // works fine

>  article {
>     color: #333;
>    @media only screen and (min-width: 480px) { @extend .foo; } // breaks
>   }
> }

**Comment by chriseppstein** [comment]
Can you file this against sass plz?

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by imathis** [comment]
Duh, sorry. Doing it now.
