### ISSUE TITLE
Mixin for input placeholder

### ISSUE THREAD

**Issue by lexer** [Compass/compass#418]
At least 4 browser now partially support  input placeholder style (firefox 4, safari, chrome, opera 11). It is reasonable to include experimental mixin for this.

http://stackoverflow.com/questions/2610497/change-an-inputs-html5-placeholder-color-with-css

**Comment by mirisuzanne** [comment]
There is not a great way to do this in compass at the moment. One solution has been discussed here:

https://gist.github.com/923593

But using it would require overriding a mixin to set your own styles. Not an ideal solution. This could be fixed with the 'children' feature that has been discussed but never implemented:

https://gist.github.com/923780

**Comment by chriseppstein** [comment]
I have filed a feature request against sass: https://github.com/nex3/sass/issues/128

**Comment by ry5n** [comment]
Now that @content is available for use, does [this Gist](https://gist.github.com/2027364) help solve this issue?

**Comment by mirisuzanne** [comment]
Yes, care to submit a patch?

It seems to me that the first mixin there is the important one, and should be titled to match the selector ("placeholder" singular). Any additional shortcuts should be considered individually and be named to match their specific function (e.g. "placeholder-color").

**Comment by ry5n** [comment]
Good advice, thanks! I'll make that change and issue a pull request, but… I must admit, I'd still pretty new using Git/Github (been using Compass longer than version control, believe it or not). Which branch should I request against?

**Comment by mirisuzanne** [comment]
Probably "master" - http://compass-style.org/help/tutorials/contributing/#patches

**Comment by ry5n** [comment]
_facepalm_. Thanks :)

**Comment by alanhogan** [comment]
http://beta.compass-style.org/reference/compass/css3/user_interface/#mixin-input-placeholder for now

(will be at http://compass-style.org/reference/compass/css3/user_interface/#mixin-input-placeholder after 0.13, I understand)

**Comment by tobiasmuecksch** [comment]
Why is this feature 2 years later still not in the stable version?

**Comment by chriseppstein** [comment]
It's a long story. But it's neither here nor there. Sass 3.3 will be
released very soon and then we will release 1.0 of compass that will
include this.
