### ISSUE TITLE
@extend and ampersand

### ISSUE THREAD

**Issue by Ti-webdev** [Compass/compass#419]
SCSS:

<pre><code>.a { color: red; }
.b {
    &-c { @extend .a; }
}</code></pre>

Expected result:
`.a, .b-c { color: red; }`

 Actual result:
`.a, -c.b { color: red; }`

**Comment by chriseppstein** [comment]
Hi thanks for the bug report. Can you please file this against Sass? http://github.com/nex3/sass/issues
