### ISSUE TITLE
Output might be incorrect

### ISSUE THREAD

**Issue by powellnathanj** [Compass/compass#42]
In trying to add compass to a rails project, I get some output that says...

= stylesheet_link_tag 'compiled/partials/_base.css'

However, that is in a directory that is under app.  I was under the impressions that was to be mixed in, and I didn't need to link to it?

Or perhaps I totally misunderstand.  If I misunderstand, I apologize, however if it is incorrect, it's confusing.

Thanks.

**Comment by chriseppstein** [comment]
You're correct. That line is not needed. That it shows up is a bug.

I've fixed it on edge about a week ago and it will go out with the next release. Thanks for the report.

**Comment by chriseppstein** [comment]
This was fixed in v0.8.12.
