### ISSUE TITLE
blueprint showgrid mixin, horizontal line spacing

### ISSUE THREAD

**Issue by Jesse-Breuer** [Compass/compass#428]
Hello, I am working with blueprint via compass (scss syntax) on rails
3.1 rc1.
I am following the guidelines for blueprint on the compass site:
http://compass-style.org/reference/blueprint/grid/
http://compass-style.org/reference/blueprint/typography/

I was noticing that when using @include showgrid; the horizontal lines
in the generated background grid image line up with my text with font
size set $blueprint-font-size: 13.3px; whereas if I use the old static
image grid.png background, the text lines up when set to 12px.

Is there a way to change the spacing of the horizontal lines in that
generated grid? The vertical lines seem to be spaced according to how
I set the grid variables:

$blueprint-grid-columns: 24;
$blueprint-grid-width: 30px;
$blueprint-grid-margin: 10px;

however I haven't figured out if there is a setting for the spacing of
the horizontal lines. 

Here is my .scss if this is at all useful. (perhaps Im missing something)
@import "blueprint";
@import "blueprint/reset";
@import "blueprint/typography";

$blueprint-grid-columns: 24;
$blueprint-grid-width: 30px;
$blueprint-grid-margin: 10px;

$blueprint-font-family: Georgia, "Helvetica Neue", Arial, Helvetica, sans-serif;
$blueprint-font-size: 13.3px;

@include blueprint-typography;
# container {

@include container;
@include showgrid;

}
# header {

```
@include column(24, true);
```

}
# left-nav {

```
@include column(6);
```

}
# content {

```
@include column(12);
```

}
# side-bar {

```
@include column(6, true);
```

}
# footer {

```
@include column(24, true);
```

}

**Comment by chriseppstein** [comment]
This should be fixed in v0.11.4 by 8d8d3eecbc80ee0d55b077ddd3d6d56219b5bef3. Please verify.
