### ISSUE TITLE
Make append-bottom and prepend-top work

### ISSUE THREAD

**Issue by wycats** [Compass/compass#43]

**Comment by chriseppstein** [comment]
This was recently brought up on the [mailing list](http://groups.google.com/group/compass-users/browse_thread/thread/ebe46521f390a0cf/57215bdc0ef25d1d?lnk=gst&q=append-bottom#57215bdc0ef25d1d).

I will add it for the next release. Thanks!

**Comment by chriseppstein** [comment]
fixed in 0.8.13 -- just released.
