### ISSUE TITLE
compass command returns with exit status 0 even on errors

### ISSUE THREAD

**Issue by esamattis** [Compass/compass#432]
The compass command returns with exit status 0 even if compiling failed.  It should return non zero status if even one file fails to compile.

This is for scripting purposes. Exit status is an ideal way to detect errors and notify about them.

This is at least on Compass 0.11.1 (Antares).

**Comment by antonevane** [comment]
Latest Compass version is 0.11.3

**Comment by esamattis** [comment]
No difference on latest Compass.

**Comment by scottdavis** [comment]
noted and ill make sure this gets fixed

**Comment by peritus** [comment]
I want this, so rake fails if there is an error in the .scss source.
