### ISSUE TITLE
Better documentation for mixin box-shadow

### ISSUE THREAD

**Issue by amra** [Compass/compass#433]
In documentation for 'box-shadow' are parameters named like $shadow-1, $shadow-2, ...  
Each time I use it I must read the source code to get parameters right.
Please improve parameter names.

**Comment by scottdavis** [comment]
patches accepted =)

**Comment by imathis** [comment]
How are you using this mixin? I haven't had any problems using it. Perhaps we're using it differently.

For me it looks like this:

`@include box-shadow(#000 0 1px 2px, #fff 0 1px inset);`

When do you need to use named variables?

**Comment by amra** [comment]
Check the parameters description for mixin box-shadow (on http://compass-style.org/reference/compass/css3/box_shadow/#mixin-box-shadow): 
`box-shadow($shadow-1, $shadow-2, $shadow-3, $shadow-4, $shadow-5, $shadow-6, $shadow-7, $shadow-8, $shadow-9, $shadow-10)`

E.g. what should I use for `$shadow-4` parameter?

On same page is mixin single-box-shadow (http://compass-style.org/reference/compass/css3/box_shadow/#mixin-single-box-shadow). 
The mixin description is `single-box-shadow($color, $hoff, $voff, $blur, $spread, $inset)`. It's easier to understand for me.
