### ISSUE TITLE
Compass' _form.sass doesn't respect input[type=text] & input[type=password] as Blueprint does.  

### ISSUE THREAD

**Issue by mitchlloyd** [Compass/compass#44]
Hi.

I noticed that compass' _forms.sass doesn't put the same css around input[type=text] & input[type=password] that Blueprint does.  Blueprint has suff like (SHA: 63795c8bfe31cbbfad726f714bf8d22770adc7ad):

```
input[type=text], input[type=password],
input.text, input.title,
textarea, select {
  background-color:#fff;
  border:1px solid #bbb;
}
```

whereas Compass has stuff like:

```
input.text, input.title,
textarea,
select
  :border= 1px "solid" !unfocused_border_color
  &:focus
    :border= 1px "solid" !focus_border_color
```

I can create an easy patch to fix this, but I just wanted to make sure that that the project aims to copy blueprint very closely and that this would be a wanted patch.  Thanks!

**Comment by chriseppstein** [comment]
That change was introduced as part of the v0.9.1 release of blueprint. Compass is currently at v0.9.0. I would like to update to blueprint v0.9.1 as part of the compass v0.10 release. If you'd like to help with that effort, let me know. I'll file a separate issue for the v0.9.1 upgrade.
