### ISSUE TITLE
Only when Rails.env.production?: `clearfix': Undefined mixin 'clearfix'. (Sass::SyntaxError)

### ISSUE THREAD

**Issue by foca** [Compass/compass#440]
Our deploy recipes were running `Sass::Plugin.update_stylesheets` and everything worked fine when deploying to our staging server (`Rails.env == "staging"`) but when we configured a production server it started failing with the above error.

We haven't been able to figure out the exact problem (it might be in Sass, and not in Compass), so we're attaching the minimum Rails app that we were able to create that replicates this issue.

The important files are:

```
--- config/compass.rb
 |- app/stylesheets/screen.scss
 `- app/stylesheets/partials/danger.scss
```

The command we run to replicate the issue is:

`rm -rf tmp/sass-cache/ public/stylesheets/compiled/ && rails runner -e production 'Sass::Plugin.update_stylesheets'`

If we run the same command but with `-e development` everything works. It works with any environment that is _not_ production, in fact (it worked perfectly well in our application for the _staging_ environment as well.)

Prefixing the partial with _ makes it work, so we assume it's something related to load paths, but we're not sure since we haven't been able to pinpoint the exact place where the issue originates. The fact that it fails only in the production environment, though, leads us to think this is a bug (even if we _should_ have been using `_danger` instead of `danger` :))

The rails app is http://nicolassanguinetti.info/files/sass-compass-bug.zip

**Comment by scottdavis** [comment]
whats in your compass config file?

**Comment by foca** [comment]
``` ruby

project_type = :rails
project_path = Compass::AppIntegration::Rails.root
http_path = "/"
css_dir = "public/stylesheets/compiled"
sass_dir = "app/stylesheets"
environment = Compass::AppIntegration::Rails.env

if Compass::AppIntegration::Rails.env == :development
  output_style = :nested
else
  output_style = :compressed
end
```

One of the first things we thought was that the output_style could be the culprit, but since it works in environments that are not development (and not production) then we discarded that.

**Comment by scottdavis** [comment]
well first DRy this up some by replacing your if with this

<pre>
output_syle = (environment == :production ? :nested : :compressed)
</pre>

but im assuming this issue is that compass/sass only has 2 environments (:development, :production) but im not sure how or why thats effecting this

**Comment by chriseppstein** [comment]
This is not a bug. You're using a mixin that is not defined or imported. This works when used as a partial, because the dependency was already imported. You need to either make this file a partial or import the dependencies.
