### ISSUE TITLE
SystemStackError: stack level too deep

### ISSUE THREAD

**Issue by fbjork** [Compass/compass#441]
I'm getting SystemStackError: stack level too deep when I try Compass 0.11.3 in a Rails 3.0.9 + Ruby 1.9.2 app. Any idea how to debug this issue?

compass watch/compile works fine in the same app.

**Comment by chriseppstein** [comment]
I'm sure you've moved on, but if not, it would be great if you could provide a stack trace.

**Comment by fbjork** [comment]
I'm still stuck on this. I tried 0.11.4 but the problem persists. The only stack trace says is this:
activesupport (3.0.9) lib/active_support/callbacks.rb:421

I have to do compass clean then compass watch for it to work.

**Comment by chriseppstein** [comment]
@fbjork Only one line? That's not much to go on. Can you zip up a minimal rails app that reproduces the issue?
