### ISSUE TITLE
Make fssm dependency optional once Rails 3.1 support lands

### ISSUE THREAD

**Issue by josevalim** [Compass/compass#448]

**Comment by chriseppstein** [comment]
+1

**Comment by scottdavis** [comment]
+1 but wouldn't it or guard still have to be in the gemspec?

**Comment by chriseppstein** [comment]
It is a quandary. We might have to factor compass into several gems.

**Comment by chriseppstein** [comment]
This didn't make it into 0.12.

**Comment by scottdavis** [comment]
Yea it's on my list to remove Fssm and use the new listener gem

**Comment by chriseppstein** [comment]
We use listen in Sass now. It's not an explicit dependency.
