### ISSUE TITLE
Transitions css files typo

### ISSUE THREAD

**Issue by gastongamietea** [Compass/compass#457]
While I was building my scss files I found an issue in _transitions.css. There is a typo for variable $default-transition-function, it was written as **$default-transition-funciton**.

Once you have fix that typo it works with no issues.

Thanks,
Gaston

**Comment by chriseppstein** [comment]
This is fixed on stable, we need to cut a new release.

**Comment by gastongamietea** [comment]
Hi,

ok cool, I just wanted to point that out... :)

Thx

---

Gastn Gamietea

My profile at http://www.linkedin.com/in/gamietea

**Comment by HamptonMakes** [comment]
Please push a release for this! Teh pleaz!
