### ISSUE TITLE
on_sprite_saved callback throws an error

### ISSUE THREAD

**Issue by asciidisco** [Compass/compass#458]
Hey guys,

i´ve tried to use the "on_sprited_saved" callback in my config.rb,
but when i now try to compile or watch a directory, the following error occurs:

undefined method `on_sprite_saved' for #<Tray:0x12c08c7>
<script>:30:in`build_change_options_menuitem'
org/jruby/RubyKernel.java:1088:in `eval'
src/ui/tray.rb:147:in`build_change_options_menuitem'
src/ui/tray.rb:398:in `watch'
src/app.rb:170:in`try'
src/ui/tray.rb:357:in `watch'
src/ui/tray.rb:126:in`compass_switch_handler'
src/ui/tray.rb:56:in `run'
src/main.rb:44:in`(root)'
org/jruby/RubyKernel.java:1038:in `require'
<script>:1:in`(root)'

My impl. looks like this:
on_sprite_saved do |filename|
# Actually does nothing but throws an error

end

I´am currently using Sass Version 3.1.2 and Compass Version  0.11.3.
It would be awesome if any of you guys could help me out with this problem, or verify that it is really a compass bug...

Regards
Sebastian

**Comment by asciidisco** [comment]
Oh GitHub messed with my code...

``` ruby
on_sprite_saved do |filename|
# Actually does nothing but throws an error
end
```

**Comment by chriseppstein** [comment]
It looks like this config file is being evaluated in a strange context. Are you using compass.app?

**Comment by asciidisco** [comment]
Yes. I first tried it with compass.app and later on with another jRuby based installation on a different pc.
Maybe this is an jRuby related issue...

**Comment by scottdavis** [comment]
I'll investigate this today

**Comment by scottdavis** [comment]
can you post your config file compass.app version? please

**Comment by hlb** [comment]
Hello, I am from Compass.app team. Please provide your config.rb testcase, so we can dig into it.

BTW, it seems you are using Compass.app v1.5, please update to v1.6 first. (it has different sass/compass/jruby version)

**Comment by scottdavis** [comment]
no response from author closing this
