### ISSUE TITLE
incorrect output for enumerate in 960

### ISSUE THREAD

**Issue by dsutoyo** [Compass/compass#46]
enumerate outputs grid_-1, grid_-2, etc in the 960 plugin

**Comment by chriseppstein** [comment]
[Compass Core] The enumerate function now accepts an optional argument to specify the separator. Closed by e0732c8700c5903fac60074d0e6443105f48b550.

**Comment by chriseppstein** [comment]
Fixed. Please grab the latest versions of compass and the 960 plugin.
