### ISSUE TITLE
Ability to add images, fonts, etc. to extensions

### ISSUE THREAD

**Issue by chrisdrackett** [Compass/compass#460]
It would be great to add non-sass files to a compass extension without the files having to be copied into the project.

After using compass for about a year I've built up a good amount of "common" files that I use on most projects I work on. These files include sass files, images (arrows, etc.) and icon fonts currently.

Its become a bit of a burden to copy these assets into each project, and makes them very hard to keep under VC on their own. I've looked into making an extension for these files, but it seems that would only cover the sass files and not the images or fonts (from my understanding of the docs)

**Comment by chriseppstein** [comment]
I don't know how to do this in an app server agnostic way. I assume you're using rails, in this case, an Engine is probably more appropriate for your needs because the stylesheets can be shared without copying because rails know where to find them.

**Comment by chrisdrackett** [comment]
I'm actually doing mostly static sites and django. I guess there isn't really a clean way around this.

**Comment by alexcabrera** [comment]
If you're using Django, you could package all your common static files into an app, include the app in your INSTALLED_APPS, and then use `manage.py collectstatic` to automagically move all the static files from the app into your STATIC_ROOT. 

Then all you need to do is keep your new app under version control and install it into your virtualenv when you start a new project.

[edit] - You might want to check out this link https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#collectstatic

**Comment by chrisdrackett** [comment]
this is worth looking into for sure. I'm currently using webassets (https://github.com/miracle2k/webassets/) to compile compass and I'm not sure how these two approaches will interact (it just magically works right now ;)

**Comment by chrisdrackett** [comment]
@alexcabrera do you know if there is a good way to handle this when developing locally?
