### ISSUE TITLE
default to translate3d in safari

### ISSUE THREAD

**Issue by chrisdrackett** [Compass/compass#465]
in safari/mobile safari 3d transforms are hardware accelerated. Because of this I would suggest always using translate3d in safari.

right now compass does:

```
-moz-transform: translate(0, 100%);
-webkit-transform: translate(0, 100%);
-o-transform: translate(0, 100%);
-ms-transform: translate(0, 100%);
transform: translate(0, 100%);
```

I would suggest:

```
-moz-transform: translate(0, 100%);
-webkit-transform: translate3d(0, 100%, 0);
-o-transform: translate(0, 100%);
-ms-transform: translate(0, 100%);
transform: translate(0, 100%);
```

**Comment by scottdavis** [comment]
does this work in chrome?

**Comment by chrisdrackett** [comment]
yes, this works in chrome as well, I have an example here: http://tictok.net/ (click Log In, the slide is using translate3d for webkit.)

**Comment by scottdavis** [comment]
how about safari on windows? and andriod webkit?

**Comment by chrisdrackett** [comment]
yes, yes

**Comment by scottdavis** [comment]
so now that thats over =p this is going to be a hard change given the way that the browser support functions work. @chriseppstein

**Comment by chriseppstein** [comment]
Why is it hard?

**Comment by scottdavis** [comment]
Because in lazy

**Comment by doctyper** [comment]
While I like the idea, I would suggest that this feature be opt-in. There are scenarios where you don't necessarily want hardware-accelerated transforms. In some cases they behave weirdly; they can mess with your z-index values or even positioning.

Suggestion: have the translate3d mixin output 2d equivalents (or as close as you can get) to non-3d browsers. This would then imply that you are requesting a hardware-accelerated transform, and would degrade gracefully to other browsers.

Thoughts?

**Comment by millermedeiros** [comment]
translate3d messes with `background-position: fixed` and `z-index`.. it shouldn't be the default. maybe just add info on the docs that translate3d is hardware accelerated on iOS.

**Comment by chrisdrackett** [comment]
I think if anything this should be an option. We currently use 3D transforms 100% of the time on webkit and work around the issues above because the performance gains are so significant.

**Comment by chriseppstein** [comment]
The compass css3 mixins are low-level wrappers around browser prefixes and compatibility and are meant to be used in constructing more high-level mixins. So I agree they shouldn't do anything beyond that stated purpose if there are downsides to such a strategy. I suggest someone makes accellerated versions of these mixins and they can be another module.

**Comment by chriseppstein** [comment]
The transform module has 3d support: http://compass-style.org/reference/compass/css3/transform/ I'm not sure what else is needed here -- seems like you can opt-in to a 3d based approach with relative ease. Closing.

**Comment by cscott** [comment]
Not sure this bug has been resolved.  What's the preferred way to write "add a bogus translate3d(0,0,0) to every transform for webkit-based browsers only"?
