### ISSUE TITLE
elements-of-type(inline-block)

### ISSUE THREAD

**Issue by nathanbrauer** [Compass/compass#466]
Currently there is no inline-block type.  This should include img and I think two others (I forgot which ones off the top of my head).

**Comment by chriseppstein** [comment]
Please send a pull request when you remember :)

**Comment by nathanbrauer** [comment]
I was wrong-- it's just img

**Comment by chriseppstein** [comment]
I'm concerned about changing `img` from `inline` to `inline-block`. I added an inline-block entry with img in it though.
