### ISSUE TITLE
Transition mixin should generate shorthand syntax if possible

### ISSUE THREAD

**Issue by johanbrook** [Compass/compass#469]
Hi!

I've noticed that the `transition` mixin in Compass outputs separate properties, vendor prefixed:

**SCSS for including the transition mixin**

```
@include transition(color, 0.2s, ease-out);
```

**CSS output**

```
-moz-transition-property: color;
-webkit-transition-property: color;
-o-transition-property: color;
transition-property: color;
-moz-transition-duration: 0.2s;
-webkit-transition-duration: 0.2s;
-o-transition-duration: 0.2s;
transition-duration: 0.2s;
-moz-transition-timing-function: ease-out;
-webkit-transition-timing-function: ease-out;
-o-transition-timing-function: ease-out;
transition-timing-function: ease-out;
```

Lots of bloat, as you can see. This wouldn't bother if this behavior was consistent in Compass, but the construct for `box-shadow`, for instance, behaves different (and better). See below.

**SCSS for including the box shadow mixin**

```
@include box-shadow(rgba(255,255,255, 0.4) 0 1px 0);
```

**CSS output**

```
-moz-box-shadow: rgba(0, 0, 0, 0.1) 0 0 2px;
-webkit-box-shadow: rgba(0, 0, 0, 0.1) 0 0 2px;
-o-box-shadow: rgba(0, 0, 0, 0.1) 0 0 2px;
box-shadow: rgba(0, 0, 0, 0.1) 0 0 2px;
```

That's the shorthand syntax I'd like to see in the `transition` mixin output.

```
-moz-transition: color 0.2s ease-out;
-webkit-transition: color 0.2s ease-out;
-o-transition: color 0.2s ease-out;
transition: color 0.2s ease-out;
```

Is it doable to make the `transition` mixin output the above? Looked it up in past issues, but couldn't find something similar. If it's not possible technically to achieve this, I understand, but I just thought I'd bring this up.

Thanks!

**Comment by marvinahv** [comment]
You can have the shorthand css output, just omit the commas in your constructor.

@include transition(color 0.2s ease-out); //  Without the commas

will output:

-moz-transition: color 0.2s ease-out;
  -webkit-transition: color 0.2s ease-out;
  -o-transition: color 0.2s ease-out;
  transition: color 0.2s ease-out;

Hope that helps!

**Comment by johanbrook** [comment]
Actually, it does not for me.

Having this in the Sass file:

```
@include transition(opacity 0.2s ease-out);
```

.. produces this weird mess:

```
-moz-transition-property: opacity 0.2s ease-out;
-webkit-transition-property: opacity 0.2s ease-out;
-o-transition-property: opacity 0.2s ease-out;
transition-property: opacity 0.2s ease-out;
-moz-transition-duration: 1s;
-webkit-transition-duration: 1s;
-o-transition-duration: 1s;
transition-duration: 1s;
```

I'm on Compass 0.11.3. It should behave as you described it, but it simply doesn't.

**Comment by rawfolio** [comment]
Getting the same issue..

**Comment by marvinahv** [comment]
Maybe that. I am on Compass 0.11.5 and Sass 3.1.5 and it works fine with those versions. Have you tried upgrading to the new version?

**Comment by johanbrook** [comment]
Recently upgraded, and it seems this is fixed. Awesome!
