### ISSUE TITLE
Blueprint .container shouldn't be overflow: hidden

### ISSUE THREAD

**Issue by tomstuart** [Compass/compass#472]
Blueprint's clearfix works by setting `overflow: hidden` on both `.clearfix:after` and `.container:after`, but Compass's Blueprint `.container` uses the general Compass `clearfix` mixin, which sets `overflow: hidden` on the `.container` itself.

**Comment by mikker** [comment]
I agree. I always, always override this to `overflow: visible`.

**Comment by curvedmark** [comment]
Me too. Please consider using pie-clearfix by default.

**Comment by scottdavis** [comment]
is this already in blueprint? can you provide a link we only add things to blueprint that are in the official repo reopen it if thats the case

**Comment by tomstuart** [comment]
As explained, Blueprint sets `overflow: hidden` on `.clearfix:after` and `.container:after` but not on `.container`. You can see this in [Blueprint's grid.css](https://github.com/joshuaclayton/blueprint-css/blob/master/blueprint/src/grid.css).

**Comment by srvrguy** [comment]
The latest code still has this issue. The comment above explains the issue well enough, look at line 15 (main container definition) and line 267 (the overflow:hidden is set here).

Unfortunately, I can't re-open the issue, so I'm simply bumping it in hopes it can be re-opened and fixed.

**Comment by rkjaer** [comment]
+1

**Comment by atipugin** [comment]
+1
