### ISSUE TITLE
Blueprint documentation

### ISSUE THREAD

**Issue by tomstuart** [Compass/compass#473]
As a Blueprint user I'm interested in two things:
- Is Compass's blueprint/basic intended to be a fully-compatible drop-in replacement for Blueprint? (aka "Is it worth filing compatibility issues?")
- If so, what version of Blueprint is Compass's port supposed to be compatible with? (1.0.0? 1.0.1?)

It would be useful for answers to these questions to be documented somewhere; if somebody wants to answer authoritatively in the issue, I'll submit a pull request with the doc changes.

**Comment by chriseppstein** [comment]
Sounds great. Thanks!

**Comment by tomstuart** [comment]
Okay. So, what are the official answers? I already gather that, yes, Compass does intend to be 100% Blueprint-compatible. Exactly which Blueprint version is it currently trying to be 100% compatible with?

**Comment by chriseppstein** [comment]
Sorry. Yes. blueprint/basic should be drop-in compatible. We do upgrade our BP version periodically, but right now we're at 1.0

**Comment by tomstuart** [comment]
Thanks. I'll assume that means Blueprint 1.0.0 (September 30th, 2010), and that Blueprint 1.0.1 compatibility (May 14th, 2011) is not yet expected.
