### ISSUE TITLE
inline-font-files is not working

### ISSUE THREAD

**Issue by rolang** [Compass/compass#477]
Inline-font-files breaks the CSS. It seems like the encoding is wrong. I used UTF-8 and the base64 string seem strange. Like when you open a Word file with notepad.
Tested with sass version 3.1.4, compass version 0.11.5, on windows 7 and opensuse 11.3, with font-files ttf, eot and woff. Can't copy and paste the string here, it won't work.

**Comment by tyrinslys** [comment]
I see the same problem, and in addition the closing characters for the @font-face are not printed, so it breaks css for the rest of the file.

<pre>
$fontOstrich: "ostrich-bold.ttf";
@include font-face("ostrich", inline-font-files($fontOstrich, truetype));

yeilds:
@font-face {
font-family: "ostrich";
src: url('data:font/truetype;base64, [lots of font data here]
</pre>

expected to see these ending characters, but they were not present.

<pre>
')}
</pre>

**Comment by botandrose** [comment]
Turns out the font file wasn't being base64 encoded. I've sumitted a pull request to fix this: https://github.com/chriseppstein/compass/pull/520

**Comment by chriseppstein** [comment]
that landed a while ago. closing.
