### ISSUE TITLE
Compass Watch randomly quits.

### ISSUE THREAD

**Issue by dfischer** [Compass/compass#482]
I tried to run it with `compass watch --trace` to get some debug output but nada. It randomly quits during changes. My only sign of notification is browser not updating styling, so then I check terminal and compass watch isn't running anymore.

I have noticed it happen about 5 times during a hour.

Anything I can run to help debug this?

**Comment by scottdavis** [comment]
run guard compass =p

**Comment by dfischer** [comment]
So, `compass watch` is deprecated? Should --warn then.

// realized it's not default. nvm.

**Comment by scottdavis** [comment]
this still a problem?

**Comment by amwelles** [comment]
This issue can probably be closed out, yeah?
