### ISSUE TITLE
Problems with Sprites and URI Ouput

### ISSUE THREAD

**Issue by jonjaques** [Compass/compass#483]
Having some problems with css that is generated with the sprite system. Basically, it's outputting some wacky text in the url strings, and I think it's related to the paths set up in config.rb.

**My directory structure**

``` index.html
images/
 | search/
 | | searchbutton.png
 | | searchbutton_hover.png
 | search-sd69f6c250b.png
sass/
 | style.scss
css/
 | style.css
```

**My SASS config is this:**
`http_path = "/"
css_dir = "css"
sass_dir = "sass"
images_dir = "images"
javascripts_dir = "scripts"`

**My import directive**
`@import "../images/search/*.png";`

So my thought here, is that we're "in" the sass directory now, and we need to traverse up one level, go to images, search, and import the images. And it works! SASS successfully writes the "search-sd69f..." sprite image. However when using the newly generated "search-sprite" mixin `@include search-sprite(searchbar);`, it returns the following for the sprite url src:

/images/../images/search-sd69f6c250b.png

Although this technically makes sense, I need the path to be "../images/search-sd69f6c250b.png"
I've tried to fix this by using different values for the import directive, and the http_path & images_dir vars in config, but I can't seem to figure it out. Mostly it seems that if I don't use the exact import path mentioned above, SASS fails to find the image, and if the images_dir var is something other than what's posted, it won't find the images either. 

I'm kind of stumped, and any assistance you guys could grant me would be greatly appreciated!

Thanks,
Jon

**Comment by chriseppstein** [comment]
The import is relative to your images directory. the `../images/` part in your import is unnecessary.

**Comment by jonjaques** [comment]
Chris, thank you for the clarification. I suppose that's what I get for trying to implement sprites at 1AM.
