### ISSUE TITLE
Where is the "technical" documentation?

### ISSUE THREAD

**Issue by andrewhavens** [Compass/compass#484]
I'm trying to figure out how the compass gem works from a technical implementation perspective, but I can't find any general documentation on that. I have a PHP project that I would like to add Compass to, but I need to know what kind of directory structure is required, gem dependencies, what sorts of command line options are available, etc...

Where can I find that information? If it is available somewhere, it would be nice if there was a link to it in the readme, wiki, and/or docs.

Compass looks promising, but I still have too many questions before I can recommend it to my co-workers.

Thanks!

**Comment by chriseppstein** [comment]
Most of that should be covered here: http://compass-style.org/help/tutorials/

**Comment by andrewhavens** [comment]
Ah, nevermind...found it myself...in the readme. Now I feel dumb. =/

http://compass-style.org/help/tutorials/command-line/
