### ISSUE TITLE
Watch works only on first save

### ISSUE THREAD

**Issue by Uninen** [Compass/compass#487]
I'm using Compass to develop Django projects on Mac OS X using VMWare Fusion virtual machine running Ubuntu. Problem is, when mounting Ubuntu directories to Finder via SSHFS or Transmit, OS X makes all these '._filename' files on save and I believe these files mess with Compass watch.

When I start watch, it works fine for the first change, but after that it stops recognising changes. Everything works when I first manually remove the ._ -files and then run 'compass compile -e production --force'

I'm new to Compass but I believe this is a bug. This may be related to ticket #394

I'd be happy with a (non-manual) workaround for a problem or tips on how to fix the watch to not looking filenames starting with a dot or under, for example. ([These proposed workarounds](http://www.senchatouchbits.com/4/better-alternatives-to-compass-watch.html) don't work for me, unfortunately.)

**Comment by timkelty** [comment]
Had the same issue after upgrading to 0.13.

I was running on ruby 1.9.3. Switching to 2.0 fixed it.

**Comment by chriseppstein** [comment]
We use Sass's watcher now.
