### ISSUE TITLE
Can not use expression language

### ISSUE THREAD

**Issue by caboe** [Compass/compass#488]
When using expression language in JSF-projects, like this in the scss file:
background-image:url("#{resource['images/layout/help.png']}");
I get an error:
Invalid CSS after "...url("#{resource": expected "}", was "['images/layout...")

**Comment by chriseppstein** [comment]
This is not legal sass syntax. Please seek support on the mailing list.

**Comment by caboe** [comment]
But this is an typical pattern when using expression language... 
Why not simply ignore everything that is written in quotes?

**Comment by MarioRicalde** [comment]
Please note that I'm not an expert on the Expression Language. But I think you're taking the wrong approach here. To me it seems that you need to run the Expression Language (compiler?) before passing it to compass so: `resource['something']` is valid sass.

That's how Rails does it with `.scss.erb` I believe.

**Comment by caboe** [comment]
Thank you for your fast reply.
But sadly, this would be no solution. The aim is to replace the expression on run time, so the apllication can decide what to display. The solution in the mean time is a second (non-SCSS) CSS file, witch contains all URLs. But it is not very maintainable to have classes separated in two files.

**Comment by MarioRicalde** [comment]
Where are you getting resource['images/layout/help.png'] from? I'm assuming that you're tying to make that return some sort of path to the asset.

Did you know that compass provides with `image-url()` [1] which takes the configuration file image path?

 I mean you can even make your own @function if that's what you want.[2]

If you need more help, try reaching our mailing list [3]

[1] http://compass-style.org/reference/compass/helpers/urls/#image-url
[2] http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#functions
[3] http://groups.google.com/group/compass-users

**Comment by caboe** [comment]
The problem is, that I need "resource['images/layout/help.png']" in the generated CSS. The application decides on witch resource this expression maps. This could be for example different skins, depending on the user.

**Comment by caboe** [comment]
Found a solution. Not elegant, but it works:
$pre: 'url("#' + '{';
$post: '}")';
....
background-image: unquote($pre + "resource['images/layout_new/header_org.jpg' ]" + $post);

**Comment by caboe** [comment]
OK, it's time to use a mixin- it's more elegant:

@mixin background-image($url) {
   $pre: 'url("#' +  "{resource['";
   $post: ']}")';
   background-image: unquote($pre + $url + $post);
}
....
@include background-image("images/layout_new/header_org.jpg");

**Comment by chriseppstein** [comment]
You can escape sass's interpolation syntax with a `\` like this:

```
background-image:url("\#{resource['images/layout/help.png']}");
```

**Comment by caboe** [comment]
That was what I'm looking for. I always tried

background-image:url("#{resource\['images/layout/help.png']}");

because the error message complaints about the '[' bracket...

Thank you
