### ISSUE TITLE
remove FSSM and replace with GUARD

### ISSUE THREAD

**Issue by scottdavis** [Compass/compass#491]

**Comment by netzpirat** [comment]
FYI: FSSM uses the rb-fsevent and rb-inotify libraries, and has polling and FSEvent via RubyCocoa implemented. Guard also uses rb-fsevent and rb-inotify, and has polling implemented. In order to remove duplicate effort, the Guard team is planning to use FSSM and remove its own implementation and contribute to FSSM.

**Comment by scottdavis** [comment]
ugggg -1

**Comment by netzpirat** [comment]
We haven't decided anything yet, but we talked about testing FSSM on a separate branch and see how it behaves. Can you please give some more details why you wouldn't suggest FSSM?

**Comment by scottdavis** [comment]
well chris will need to comment more but from what i understand it hasn't been too actively maintained.

**Comment by netzpirat** [comment]
Ok, so no technical issue then. 

I spot travis (the maintainer of FSSM) as very competent and active in the area of file system notification. He put a lot of effort into rb-fsevent lately and improved it a lot! So he did in fact maintain it one layer deeper :P

**Comment by scottdavis** [comment]
OSS inception

**Comment by scottdavis** [comment]
so what we may do is use guard and let guard deal with fssm

**Comment by scottdavis** [comment]
using listen instead

**Comment by adius** [comment]
Everytime i start compass i get this message:

Dear developers making use of FSSM in your projects,
FSSM is essentially dead at this point. Further development will
be taking place in the new shared guard/listen project. Please
let us know if you need help transitioning! ^_^b
- Travis Tilley

**Comment by Anahkiasen** [comment]
Same here, latest versions (I'm using the git versions, latest commits) and I still get these messages.

**Comment by oskarrough** [comment]
Same here

**Comment by norberttamas** [comment]
Same here. Any suggestions?

**Comment by scottdavis** [comment]
Try the listen branch

**Comment by prembo** [comment]
Scott - which one is the 'listen branch'?

**Comment by tompave** [comment]
Getting the CLI warning too. Still, it does work, so it's not really a problem.
I was just wondering whether Compass has decided to stick with FSSM or it will switch to guard/listen.

**Comment by jbowtie** [comment]
This fix is present in master and will presumably become part of stable when 0.13 ships. In the meantime you can `gem install compass --pre` if you need the listen integration.
