### ISSUE TITLE
Link to screencast is missing in Rails integration wiki page

### ISSUE THREAD

**Issue by bvsatyaram** [Compass/compass#492]
The rails integration wiki page located at 
https://github.com/chriseppstein/compass/wiki/Ruby-on-Rails-Integration
says:
"Having issues? Watch this quick screencast on how to set everything up:"
But the link to screencast is missing.

**Comment by scottdavis** [comment]
that wiki page is old use the compass-style.org site: http://compass-style.org/help/

**Comment by MarioRicalde** [comment]
Updated the wiki, to link to http://compass-style.org/help/
