### ISSUE TITLE
extract blueprint into plugin

### ISSUE THREAD

**Issue by scottdavis** [Compass/compass#493]
move blueprint into its own package and out of core

**Comment by MarioRicalde** [comment]
After I'm done with the documentation for sprites if this is not done I'll go on ahead and tackle this guy, if you haven't began working on it that is ;)

**Comment by scottdavis** [comment]
this can't be started until after the extension repo

**Comment by chriseppstein** [comment]
why does this depend on the extension repo?

**Comment by scottdavis** [comment]
Because you depend on me!

**Comment by scottdavis** [comment]
closed by https://github.com/chriseppstein/compass/commit/0538c04ed31e40893ed0f4bd2505fca138beb6d2
