### ISSUE TITLE
developing documentation - bundle install --binstubs fails

### ISSUE THREAD

**Issue by krisbulman** [Compass/compass#497]
I'd like to contribute to documentation, however I'm having trouble getting started. 

RubyGems version 1.8.6 
Bundler version 1.0.15
OS X version 10.6.8

forked repo, cloned to local location, installed bundler, cd'd to doc-src, ran bundle install.. failed: 

<pre>
$ sudo bundle install --binstubs
Fetching git://github.com/chriseppstein/nanoc.git
remote: Counting objects: 18375, done.
remote: Compressing objects: 100% (13330/13330), done.
remote: Total 18375 (delta 5648), reused 16578 (delta 4754)
Receiving objects: 100% (18375/18375), 6.83 MiB | 1.51 MiB/s, done.
Resolving deltas: 100% (5648/5648), done.
fatal: Could not parse object '4eee0e60c5121b90498caa88605d416521553378'.
Git error: command `git reset --hard 4eee0e60c5121b90498caa88605d416521553378` in directory /Library/Ruby/Gems/1.8/bundler/gems/nanoc-4eee0e60c512 has failed.
If this error persists you could try removing the cache directory '/Library/Ruby/Gems/1.8/cache/bundler/git/nanoc-99d7231e55d841c8a1f5367bf250136d9895321e'
</pre>

tried removing cache as directed, and exact same error comes up subsequent times around

**Comment by scottdavis** [comment]
the documentation is a pita to get up and going and it shouldn't be im sorry =(

**Comment by krisbulman** [comment]
yeah, now i am getting

<pre>
LocalJumpError at /index.html
no block given
Ruby    layout /partials/example/: in render, line 7
Web     GET localhost/index.html
</pre>


after running nanoc3 aco & hitting http://localhost:3000/index.html

difficult to contrib

**Comment by scottdavis** [comment]
are you using ruby 1.9.2?

**Comment by krisbulman** [comment]
ruby 1.8.7 (on OS X Snow Leopard)

**Comment by scottdavis** [comment]
try using 1.9.2 i had issues with chris's version of nanoc on 1.8.7

**Comment by scottdavis** [comment]
also don't run bundler with sub when you create binstubs that will create a permissions nightmare

**Comment by scottdavis** [comment]
also ive changed the docs to use the vanilla version of nanoc so this shouldn't be an issue
