### ISSUE TITLE
functions cos, tan, sin broken

### ISSUE THREAD

**Issue by tyrinslys** [Compass/compass#498]
The functions cos, tan and sin are broken save when using radians.

The following scss:

<pre>
.trig-example {
  // the trig functions seem to be broken at the moment

  /* should be 0 */
  left:sin(0);
  left:sin(0deg);
  left:sin(0rad);

  /* should be 1 */
  left:sin(90);
  left:sin(90deg);
  left:sin(1.570796rad);

  /* should be 0*/
  left:sin(180);
  left:sin(180deg);
  left:sin(3.14159rad);
  
  /* should be -1*/
  left:sin(270);
  left:sin(270deg);
  left:sin(4.712388);

  /* should be 0*/
  left:sin(360);
  left:sin(360deg);
  left:sin(6.28318rad);
}
</pre>

Will produce:

<pre>
.trig-example {
  /* should be 0 */
  left: 0;
  left: 0;
  left: 0rad;
  /* should be 1 */
  left: 0.894;
  left: 0.707;
  left: 1.0rad;
  /* should be 0*/
  left: -0.801;
  left: 1;
  left: 0.0rad;
  /* should be -1*/
  left: -0.176;
  left: 0.707;
  left: -1.0;
  /* should be 0*/
  left: 0.959;
  left: 0.0;
  left: 0.0rad; }
</pre>

Similarly incorrect results are returned by the cos() and tan() functions.

**Comment by scottdavis** [comment]
these are directly using the ruby math functions i dont know what else to say:
https://github.com/chriseppstein/compass/blob/stable/lib/compass/sass_extensions/functions/trig.rb

**Comment by tyrinslys** [comment]
Thanks for the link. Look at line 21 of the link you provided. I think that '&&' should be an '||'

The [documentation reads](http://compass-style.org/reference/compass/helpers/trig/), "_If the number is unitless or has a unit of deg then it will return a unitless result. Degrees will first be converted to radians._" 

In other words if deg is the unit or has no units then do radian conversion else no conversion needed.

Also the formula to convert to radians is incorrect. These sources confirm that it should be **degrees \* PI / 180**:
http://www.teacherschoice.com.au/maths_library/angles/angles.htm
http://www.mathwarehouse.com/trigonometry/radians/convert-degee-to-radians.php
http://www.analyzemath.com/Calculators_2/convert_degrees_radians.html
http://www.ehow.com/video_4975008_convert-degrees-radians.html

**Comment by scottdavis** [comment]
you are correct working on a fix

**Comment by scottdavis** [comment]
since im super rusty at my trig does this test case look correct? https://github.com/chriseppstein/compass/blob/stable/test/units/sass_extensions_test.rb#L67

**Comment by tyrinslys** [comment]
I have grouped by degree for easy reading. There are cases where I don't know how the test should be handled (infinity and (neg)infinity for the tan functions and the rounding test) But other than that this should be a complete.

Update:
actually the last tests for rounding should be fine how you had them, so I am updating this post.

Another Update:
See this gist instead (I am still learning github) -- https://gist.github.com/1121574
