### ISSUE TITLE
Link order? (LVHFA)

### ISSUE THREAD

**Issue by fangamer** [Compass/compass#50]
Would it be possible to make a minor change to the +link-colors mixin so that it accepts link colors in the 'usual' order, which is LVHFA (link, visited, hover, focus, active)? Not sure if there was a specific reason for the existing order (LHAVF).

Thanks!

**Comment by chriseppstein** [comment]
The logic behind the current order is based on frequency of specification in my experience of common usage and the fact that if you don't specify an argument, no color is specified.

To be honest, I didn't know there was a color order convention, and if I had I probably would have followed that. It's hard to change this without forcing all current users to update their mixin calls when they upgrade.

Can you point me to a reference of some kind that I can use to see this convention?

Lastly, I want to add a feature to Sass that allows property style passing of arguments, then this kind of mixin would really clean up.

**Comment by fangamer** [comment]
Thanks for the quick response, Chris. The ordering is an informal convention which arose back in the day to address minor usability concerns, as well as inconsistencies with IE (surprise!). More information here:

http://meyerweb.com/eric/thoughts/2007/06/11/who-ordered-the-link-states/
http://www.mezzoblue.com/css/cribsheet/ (search for 'vader')
http://archivist.incutio.com/viewlist/css-discuss/40308

You're right that changing the order of the arguments might bork up a lot of existing installations, but it may be worthwhile to modify the order in which they're written to the stylesheet.

(And optional property style calls would, indeed, fix things up nicely -- the extra verbosity could really go a long way toward making calls to obscure mixins more self-explanatory.)

Anyway, I'm a Rails/HAML/SASS/Compass newbie, and I gotta say, I'm really digging Compass. I've been writing HTML (and later CSS) by hand since 1997, and Compass is making the Rails learning curve feel less steep. Great work :)

**Comment by chriseppstein** [comment]
I think the best approach is to leave this as-is and wait for keyword arguments to sass mixins.
