### ISSUE TITLE
Do not cache sprites in Rails 3.1 dev mode

### ISSUE THREAD

**Issue by snitko** [Compass/compass#501]
I'm experiencing a problem in Rails 3.1, supposedly after the most recent Compass update.

When the server is started and the page is loaded for the first time, sprites are generated. A file called `user_menu_icons-s06e7e31dcf.png` is placed under `app/assets/images` dir. Then, if I update the images under `app/assets/images/user_menu_icons` the sprite is not updated. Not until I restart Rails and manually delete the generated sprockets file. This was not the case not so long ago, before I updated Compass. Could you please explain how do I get the behavior I need? Thanks.

Using Rails 3.1.0.rc4, sprockets 2.0.0.beta.10

**Comment by chriseppstein** [comment]
if we didn't cache sprites, it would be unbearably slow.

As a work around if you change the file that imports the sprite it will rebuild the sprite.

**Comment by chriseppstein** [comment]
Related: I have a bug against sass to allow us to create non-stylesheet dependencies in sass: https://github.com/nex3/sass/issues/144

this is specifically to handle this issue.

**Comment by snitko** [comment]
No, wait, it wouldn't be slow. We do cache them, I probably gave a misleading title. We just rebuild them when one of the files in the sprite source did changed. And this is not what happens now. It is is somewhat broken to have to change the .scss file that imports the sprite.

**Comment by chriseppstein** [comment]
Agree that you shouldn't have to invalidate the importing stylesheet. But this is unlikely to change until the next major sass release.

**Comment by scottdavis** [comment]
did this get fixed in sass?

**Comment by chriseppstein** [comment]
no

**Comment by chriseppstein** [comment]
The compass-rails gem adds a depend_on call for each sprite so that it will invalidate now.
