### ISSUE TITLE
Blueprint @function reference throws Sass error

### ISSUE THREAD

**Issue by tdreyno** [Compass/compass#503]
With Compass 0.11.5 and Sass 3.1.6 (on both ruby 1.8.7 and 1.9.2), importing the blueprint framework via:

```
@import "blueprint"
```

Throws the following error (in Sinatra):

```
undefined method `args=' for [[]]:Sass::Tree::FunctionNode
file: deep_copy.rb location: visit_function line: 36
```

I've tracked down the error to blueprint/_grid.scss and the lines (112):

```
@function span($n) {
  @return $blueprint-grid-width * $n + $blueprint-grid-margin * ($n - 1);
}
```

If I comment that out, the error goes away.

**Comment by tdreyno** [comment]
Debugged further, the ONLY occurs on sass 3.1.6. Version 3.1.5 works fine.

**Comment by chriseppstein** [comment]
@nex3 ping
