### ISSUE TITLE
mysterious png error

### ISSUE THREAD

**Issue by rizkysyazuli** [Compass/compass#505]
i got this weird error:

```
error assets/sass/style.scss (Line 221: Unrecognized file type: png)
```

here's what i got on line 221:

```
#home .headerhome {
  padding-bottom:26px;
}
```

i'm on mac OS Lion, with ruby 1.8.7 and gem 1.8.6 installed. i've updated compass to the latest (0.11.5) but it still shows the same error.

**Comment by ramontayag** [comment]
Yeah I get this too when I try to `image_url("icons/dimensions_24/clock.png")`

I'm using `compass '0.12.0.alpha.0.22e2458'` on the `rails_31` branch.

**Comment by ramontayag** [comment]
Update: it seems my problem is because I'm using it to `replace-text-with-dimensions`

**Comment by lypanov** [comment]
I'm getting the same error with just one line in my .scss:
  @import "sprites/flags/*.png"; 

Ready. to give up.. :(

**Comment by lypanov** [comment]
Oh this is just plain weird!
  compass sprite app/assets/images/sprites/flags/de.png app/assets/images/sprites/flags/gb.png
     -> Please specify at least one image to sprite.
  file app/assets/images/sprites/flags/de.png
     -> app/assets/images/sprites/flags/de.png: PNG image, 16 x 11, 8-bit/color RGB, non-interlaced

With (Compass 0.12.alpha.0 (Alnilam), on Ubuntu, without oily_png, using REE)
