### ISSUE TITLE
Extend when used with sprites puts some classes out of order

### ISSUE THREAD

**Issue by Kevnz** [Compass/compass#506]
We are using the extend function with the spriting features of Compass and in IE6 the hover classes are wrong. What happens is the generated CSS has the hover style applied in the wrong order and since IE6 doesn't do multiple class selectors it applies the hover style to the default style.
So in our code we had

``` scss
@import "icon/*.png";
.add {
    @extend .icon-add;
}
```

But when changed back to using the icon sprite it works as expected.

I hope this makes sense.

**Comment by chriseppstein** [comment]
can you show the actual and expected output please?

**Comment by wrumsby** [comment]
Hey Chris, 

Actual output was:

```
.icon-add:hover, 
.add:hover,
.icon-add.add_hover, 
.add_hover.add,
.icon-add.add-hover, 
.add-hover.add  {
    ...
}
```

expected output for the above would be (unless we are misunderstanding):

```
.icon-add:hover, 
.add:hover,
.icon-add.add-hover, 
.add.add-hover {
    ...
}
```

So, sometimes `.add` is appearing as the second selector, rather than the first selector, which confuses IE6.

**Comment by scottdavis** [comment]
im really not sure what doto about this @chriseppstein ? is it seems like more of a sass issue

**Comment by chriseppstein** [comment]
It's hard to say if there is a sass issue here. But let's focus on the source of the issue: hover not working in some browsers. Is there a reasonable fix for that?
