### ISSUE TITLE
Sprite: unable to align right (100%)

### ISSUE THREAD

**Issue by piouPiouM** [Compass/compass#511]
If we have this code:

```
$sprites: sprite-map("sprites/*.png");
li {
  background: sprite($sprites, 'menu-separator', 100%) no-repeat;
}
```

and my `menu-separator` is not aligned right (100%).

How to align to right an image of a sprite? With lemonade it was enough to specify an offset-x 100% for the image to be generated at the right in the sprite.

Compass version: 0.11.5

**Comment by piouPiouM** [comment]
Same with this code:

```
$icon-home-spacing: 15px;
$icon-menu-expand-spacing: 20px;
@import "icon/*.png";
a {
  @include icon-sprite('menu-expand', false, 100%, 11px);
}
```

See the generate sprite:
![icon-s4a2e5f1182.png](http://farm7.static.flickr.com/6124/6032506114_26853aeb1c_o.png)
With lemonade, the last image (the arrow) was positioned on the right of the sprite.

**Comment by scottdavis** [comment]
<pre>
@include icon-sprite('menu-expand', false, 100%, 11px);
</pre>


setting this 3rd argument to 100% is not going to effect the output image generation the image generation is effected by the configuration variables. 

try setting the `$<map>-<sprite>-position` variable to 100%

**Comment by piouPiouM** [comment]
It's work fine (thx!) but the generate CSS is `background-position: -197px -125px;` and not `background-position: 100% -125px;`. Unfortunately, the image is displayed on the left and not right.

I test with `$icon-position: 100%` and `$icon-menu-expand-position: 100%` (I want to use).

**Comment by scottdavis** [comment]
this sounds like a bug lets bug @hagenburger and see what he says

**Comment by scottdavis** [comment]
try `icon-position($icon, 'menu-expanded', 100%);`

**Comment by timkelty** [comment]
I'm still having this problem, I'm not sure how @scottdavis 's last comment is meant to be used...is that a function or a magic mixin? I can't get either to work.

**Comment by scottdavis** [comment]
there is a fix for this in master i just did it yesterday

**Comment by timkelty** [comment]
Oh cool, is it in the stable gem release or do I need to --pre?

**Comment by hagenburger** [comment]
You need to set the `100%` two times:
1.  **For the generation of the sprite image (aligns the sprite on the right side in the PNG):**
   
   ```
   $icon-menu-expand-position: 100%;
   // variables must be defined before the next line
   @import "icon/*.png";
   ```
2.  **For the CSS output (sets background-position 100% -YYpx):**
   
   ```
   @include icon-sprite(menu-expand, $offset-x: 100%);
   ```

**Comment by scottdavis** [comment]
Neither it's in git but I'll release a pre today
