### ISSUE TITLE
<sprite>-sprite uses old non-existent sprite map

### ISSUE THREAD

**Issue by jenshedqvist** [Compass/compass#512]
I'm importing the same sprite generation include in two different SCSS files:

``` css
@import "../sprites";
```

The `_sprites.scss` contains:

``` css
/* 16x16 */
$icon16-sprite-dimensions: false;
$icon16-spacing: 50px;
@import "icons/icon16/*.png";
```

Everything works fine in `screen.scss` and it uses the new sprite-map "icon16-sbd1401becc.png". However, my `jquery.ui.selectmenu.theme.scss` tries to use the old <b>non-existent</b> sprite map "icon16-s171549091d.png".

I've tried removing the new sprite map and generate it again but with no avail. How to fix this? What needs flushing?

I'm using Compass 0.11.5.

**Comment by scottdavis** [comment]
run compass clean and try to recompile also mind posting the source snippets that are giving you issues it sounds like something is hard coded?

**Comment by jenshedqvist** [comment]
It worked after I restarted my computer which I seldom do. Nothing was hard coded, apparently sometimes something get's stuck in the pipes, maybe a Win 7 issue who knows.

**Comment by piouPiouM** [comment]
I encounter the same problem after renaming my directory "sprites" in another name.

Compass 0.11.5
ruby 1.9.2p180 (2011-02-18 revision 30909) [x86_64-darwin10.6.0]
Mac OS X

**Edit:** no improvement after reboot.
**Note:** the directory is under SVN

**Comment by emattias** [comment]
I have the same problem.

Why isn't just the query string cache busting method used? (Looks like in the [sprite example](http://compass-style.org/reference/compass/helpers/sprites/#sprite) it is used. Is there a setting to use the same filename, only change the querystring?)

So the first version of the sprite is

icons.png?1234

and the second is (still icons.png)

icons.png?4321

This would solve the problem where if you have the same sprite in several scss files and all references to the sprite in the other scss files aren't updated.

**Comment by scottdavis** [comment]
run `compass clean` and recompile

**Comment by emattias** [comment]
I tried that and that worked. But I would like to not need to run clean and compile everytime I (or somebody else) add a picture to a sprite in one of the scss files in the project.

Am I wrong in thinking that compass would keep track of all the scss files refering to a sprite and update them all when the sprite filename is changed? Because that would be awesome!

**Comment by scottdavis** [comment]
well it should regenerate a sprite when you remove or add a file to the folder for that sprite map what sass are you using thats causing the problem

**Comment by scottdavis** [comment]
query string cache busting is bad for cacheing inline cache busters are the future you can see more detailed examples here: http://compass-style.org/help/tutorials/spriting/

**Comment by emattias** [comment]
I'm using Sass version 3.1.10 (Brainy Betty)

Sass and compass are installed and running on my Snow Leopard mac and the compass project files are on a NFS mount on a ubuntu virtual machine run with virtualbox. Does that have something to do with it not recognizing changes in the sprite folder?

Could you elaborate on inline cache busting, please?

**Comment by scottdavis** [comment]
I assume compass watch is using polling over nfs? and when i said sass i ment your .(sass|scss) file sorry for the misunderstanding

and for cache busting this is a good read: http://eng.wealthfront.com/2011/02/bulletproof-rails-asset-caching.html

Also query string cache busting breaks down at the reverse proxy level when you run a site like ours and are pumping out millions of hits an hour cache busting is essential. We use squid for reverse proxy and squid ignores query strings and so does varnish (although you can enable it)

**Comment by emattias** [comment]
Yup it polls over nfs. As I tried to explain before, compass and sass is installed on my mac and the scss and css files are located on the nfs mount.

My compass version is Compass 0.11.5 (Antares) and ruby is 1.8.7 (2010-01-10 patchlevel 249) [universal-darwin10.0]

**Comment by scottdavis** [comment]
i just wanted to make sure you were not trying to use `rb-fsevent` over nfs

**Comment by scottdavis** [comment]
this also may be an FSSM bug which is the core of compass watcher it controlls the polling for changes? have you tried guard-compass? i wonder if you get the same problems

**Comment by chriseppstein** [comment]
Closing to due to inactivity.
