### ISSUE TITLE
Integrating what bourbon has that compass doesn't

### ISSUE THREAD

**Issue by ericdfields** [Compass/compass#514]
I'd like to pull in the few really nice Bourbon additions that compass doesn't have, I've identified the following as all the features from Bourbon that Compass _doesn't_ have in some form or another: 
## Functions

  compact(_args)
  golden-ratio(_args)
  shade(_args) 
  tint(_args)
## Mixins

  animation
## Addons

  animation-keyframes (fade-in, fade-out)
@ button(_args)
@ position(_args)

Which of these _aren't_ good candidates for compass? I'd argue golden-ratio is kind of meh (presumably used for typography, which can be handled with the modular scale plugin). 

I'm interested in seeing button, position, and animation for sure. Thoughts?

**Comment by chriseppstein** [comment]
Under what license is bourbon released?

**Comment by ericdfields** [comment]
MIT: https://github.com/thoughtbot/bourbon/blob/master/LICENSE

**Comment by chikamichi** [comment]
Hi. Any new insights on this?

**Comment by gavinhughes** [comment]
+1

**Comment by renemendoza** [comment]
+1

**Comment by chriseppstein** [comment]
Compass has a [compact method](https://github.com/chriseppstein/compass/blob/stable/lib/compass/sass_extensions/functions/lists.rb#L18-26)

`tint` & `shade` seem like a better fit for sass.

What does `golden-ratio` do and why is it important?

Can someone point me to docs or info on how these are implemented and what they do?
- `animation`
- `animation-keyframes(fade-in, fade-out)`
- `@button(*args)`
- `@position(*args)`

**Comment by ericdfields** [comment]
Looks like the [Bourbon site got updated quite a bit](http://thoughtbot.com/bourbon/) since I first posted this.

Tint and shade are simple enough: https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/functions/_tint-shade.scss

Golden ratio looks janky now that I investigate it: https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/functions/_golden-ratio.scss. Basically a quick number multiplier for the golden ratio. Let's pass.

Animation is a suite of mixing for creating CSS3 animations with sass:
https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/css3/_animation.scss

[@button](http://thoughtbot.com/bourbon/#buttons) provides a simple mixin to produce generic web buttons with one line. I think [sassy buttons](http://jaredhardy.com/sassy-buttons/) is an extension that handles this functionality better and also more appropriately: as an extension.

[@position](http://thoughtbot.com/bourbon/#position) I can still get behind. Something like

```
@include position(relative, 0 0 0 100px)
```

Outputs

```
position: relative;
top: 0;
left: 100px;
```

A handy timesaver, IMHO, since using position often precedes using top/bottom/left/right. [Here's their implementation](https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/addons/_position.scss).

**Comment by chriseppstein** [comment]
Tint/shade - since these are sass-based functions we can add them as useful shortcuts in compass. I think I remember @nex3 said he preferred these to be out of core.

Position - is already in compass. It's the stretching module.  http://compass-style.org/reference/compass/layout/stretching/

Animation - seems useful. I'd like to evaluate the API and get some feedback from people who have worked with css3 animation. The `@content` feature for mixins seems like a prerequisite to a proper API and was one of the main motivations for adding it.

**Comment by renemendoza** [comment]
I am sorry i think i just wanted a free ride to get this buttons: http://hellohappy.org/css3-buttons/ :)

**Comment by renemendoza** [comment]
i think i will try to port them to compass and learn some basic scs/sass along the way

**Comment by chriseppstein** [comment]
Tracking tint and shade at #770. The rest from this issue is dealt with.
