### ISSUE TITLE
Could not find compass (>= 0) amongst [actionmailer-3.1.0.rc5 etc]

### ISSUE THREAD

**Issue by murdoch** [Compass/compass#515]
I have just upgraded to rails3.1.rc5 and get the following error message when I run: compass init rails -r html5-boilerplate -u html5-boilerplate --force

/home/stephen/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find compass (>= 0) amongst [actionmailer-3.1.0.rc5, followed by every gem on my system]

I'm using the rails31 branch. Here's some of what's in my Gemfile:

group :assets do
  gem 'sass-rails', "~> 3.1.0.rc"
  gem 'coffee-rails', "~> 3.1.0.rc"
  gem 'uglifier'
  gem 'compass', :git => 'git://github.com/chriseppstein/compass.git', :branch => 'rails31'
  gem 'html5-boilerplate'
end

gem list does NOT return compass.... I guess this is because compass is being installed by rvm into a cache directory since it's coming from github and not rubygems.org.

How can I fix this? Do I need to install the stable version to run the init command? Should the compass init command work when installation is from github repo?

**Comment by murdoch** [comment]
ok, I managed to get the initializer to run by installing 0.11.5 stable gem.

I will figure the rest out from here/

**Comment by chriseppstein** [comment]
Use:

```
bundle exec compass
```

Instead of:

```
compass
```
