### ISSUE TITLE
Sprite creation deletes any images with that prefix

### ISSUE THREAD

**Issue by alibosworth** [Compass/compass#517]
Specifically I have a folder _images/clients/_  containing images which are sprited.

I also have a completely separate image _image/clients-background.png_

When compass sprites the _/clients/_ directory, it correctly creates _images/clients-sb7ab70ede7.png_, but it also deletes _image/clients-background.png_, presumably as part of its cleanup process

are sprite prefixes considered a reserved namespace?

**Comment by scottdavis** [comment]
no this is a bug and it was caused when we updated the sprite hash by prefixing it with -s the regex for clean up needs to be updated and ill do that now

**Comment by scottdavis** [comment]
this is the problem line: https://github.com/chriseppstein/compass/blob/master/lib/compass/sprite_importer.rb#L8 so whats fun here is background does satisfy the hex match

**Comment by scottdavis** [comment]
ok ive fixed this on master i hope

**Comment by chriseppstein** [comment]
No. This is a bug, the sprite code can be smarter :)
