### ISSUE TITLE
add sprites_path/sprites_dir configuration

### ISSUE THREAD

**Issue by brentkirby** [Compass/compass#518]
This one has been bugging my OCD for a while :)  Currently compass uses the images_dir/path for sprites, meaning by default both the sprite source files, and the resulting generated sprite files exist in the same path. 

When using `compass compile`, or `compass watch` on a static/standalone site you can configure css_path/dir etc to your public/root path and keep your sass/scss files separate, making it easy to keep source files out of the actual site root. It would be nice if sprite images could exist in another location as well, meaning your site root stays just that. Almost 100% of the time you don't need the original sprite images to be uploaded to production, only the resulting sprites. 

This would also be useful in Rails apps with the asset pipeline, since by default Rails seems to want to copy every image in your assets/images path upon pre-compiling. I understand compass would probably need the original images on disk somewhere to generate the sprite output, but it would make it easy to clean these up afterwards, and rails wouldn't copy them to your /assets folder.. 

Obviously you could skip uploading the sprites folders, manually cleanup etc, but I'm thinking adding a sprites_path/dir configuration is easier, and could simply default to images_path/dir for backwards compatability.

**Comment by scottdavis** [comment]
This is implemented in 0.12

**Comment by scottdavis** [comment]
https://github.com/chriseppstein/compass/blob/a82a3dd5d4a26d3716cedf7ead4690ae9ace4fef/doc-src/content/CHANGELOG.markdown

Also seams I can't spell search while drinking

**Comment by brentkirby** [comment]
nice! This makes my OCD is happy :)  Always drove me nuts they were in the same path.

**Comment by chriseppstein** [comment]
I added this on the rails31 branch earlier today :)

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by flomotlik** [comment]
Hey guys,

I somehow seem to not really get how this is supposed to work.

I have a standard rails asset pipeline project with compass-rails.
images are in app/assets/images

During asset compile on Heroku or locally the sprites are created correctly in public/assets/

While in development the sprites are created in app/assets/images. I would like to have them in public/assets though.

My compass.rb:

```
# Require any additional compass plugins here.
project_type = :rails
line_comments = false

sprite_search_path = ["app/assets/images"]
images_dir = "public/assets"
```

Now I simply do not get any images at all. 
I am using 0.12.rc.1

Any way to resolve this?

**Comment by chriseppstein** [comment]
I thought sprockets provides a controller in development that knows how to find requests for assets in the app/assets folder.

**Comment by flomotlik** [comment]
Sprockets includes app/assets and public/assets folders in development.

I would like compass to compile the sprites into public/assets, not into app/assets/images, so I can easily ignore the public/assets folder and not have any additional files in app/assets

**Comment by flomotlik** [comment]
Got it:
generated_images_dir in my compass.rb file solved this.

Forgot to flush the tmp directoy which resulted in the images not being built correctly.

Thx for this awesome project guys.
