### ISSUE TITLE
image-url/image_url failing to generate correct path in rails 3.1rc6

### ISSUE THREAD

**Issue by alanhogan** [Compass/compass#519]
All of a sudden… both `image-url` and `image_url` functions are generating URLs that omit the `/assets/*` prefix, resulting in 404-ing background image resources.

```
GIT
  remote: git://github.com/chriseppstein/compass.git
  revision: f23bf58e8db84e17e6fab37cc73e5a539924cca0
  branch: rails31
  specs:
    compass (0.12.0.alpha.0.f23bf58)
      chunky_png (~> 1.2)
      fssm (>= 0.2.7)
      sass (~> 3.1)

GIT
  remote: git://github.com/sstephenson/sprockets.git
  revision: e13d1e875f1dbd267e6da9705bda3a83ab397cdc
  specs:
    sprockets (2.0.0.beta.14)
      hike (~> 1.2)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)

GEM
...

    sass (3.1.7)
    sass-rails (3.1.0.rc.6)
      actionpack (~> 3.1.0.rc6)
      railties (~> 3.1.0.rc6)
      sass (>= 3.1.4)
```

**Comment by chriseppstein** [comment]
all of a sudden? What changed between before and after?

**Comment by alanhogan** [comment]
Seemingly nothing, but I did just update from Rails 3.1 rc5 to rc6 and do a `bundle update` (I noticed sprockets changed, but it looks like a trivial update).

**Comment by qnm** [comment]
It may be that compass is over-writing the image_url method from sass-rails. Look at https://github.com/chriseppstein/compass/issues/500 to see if it helps you.

**Comment by alanhogan** [comment]
Thanks, @qnm, but nothing in that issue helped.

✓ My config/application.rb begins:

```
require File.expand_path('../boot', __FILE__)

require 'rails/all'
require 'compass'
require 'sass-rails'
```

✓ Compass appears (as a Git reference) before `sass-rails` (as a gem) in my `gemfile`

✓ I have restarted the server after doing `rake assets:clean` and `rake tmp:clear`

✓ I have attempted both `image-url('facebook_16.png')` and `image_url('facebook_16.png')`

✗ Either way, I end up with references to `/facebook_16.png?1312430648` instead of `/assets/facebook_16.png`

Suggestions appreciated.

**Comment by dfischer** [comment]
I don't know if it's related but I'm getting odd paths like this ->
/app/assets/images/ui-xxx.png

Tried the above like @alanhogan poinrted out. I'm not sure why mine has full path and his removed everything.

**Comment by alanhogan** [comment]
@dfischer's comment gave me the idea of double-checking for maybe a stray Compass config file (`config.rb`, I believe) but I’ll be damned if I have one.

**Comment by dfischer** [comment]
Yeah no luck on that myself. I thought that's what it is... and I tried playing with a config.rb file to hack it to work with proper paths but no luck.

**Comment by alanhogan** [comment]
I guess the crazy thing is that it seems to be working for some (a majority of?) other people. It doesn’t for you or I, or my co-worker, though.

**Comment by sporkd** [comment]
I just ran into the same problem.  Had to change them all to `asset-url("filename.png", image)`

**Comment by alanhogan** [comment]
@sporkd Huh, thanks for the tip — it doesn’t work for me, though.

`asset-url('facebook_16.png', image)` ends up as literally `asset-url("facebook_16.png", image)` in my CSS.

**Comment by alanhogan** [comment]
I mean, do I have to make my `.css.scss` files `.css.scss.erb` files or something for this to work?

**Comment by sporkd** [comment]
Nope.  I believe that image-url is just a convenience method in sass-rails for calling asset-url.  And it works for me with just a .scss extension.  So whatever's causing image-url to not add `/asset` to the front, is not breaking asset-url.  At least for me.

**Comment by alanhogan** [comment]
What version of `sprockets` is everyone using? Me, I’m on `2.0.0.beta.15`. For those of you who do not have a problem — which version are you on?

**Comment by alanhogan** [comment]
I seem to still be having this problem after updating to Rails 3.1.0.rc8.

**Comment by chriseppstein** [comment]
just pushed a bunch of changes to the rails31 branch. please retest.

**Comment by alanhogan** [comment]
Sorry, @chriseppstein. Still not working.

A touch anxious about the fact no clear cause of the problem seems to have been found.

Thanks for looking into this…

**Comment by chriseppstein** [comment]
@alanhogan really looks like sass-rails is not even required. Please verify that it is or not.

**Comment by alanhogan** [comment]
Oops, I take it back. Most of the places the problem was occurring are now solved!

STRIKE: One background image is still failing to load because of a separate issue (the generated path begins with `/` and the page I was looking at was on a different subdomain, hence total failure to load the image. At least I think that is the problem. Suggestions to work around this? Can I force asset-url to generate fully qualified absolute URLs? /STRIKE

Sorry, seems to have been a cache error. My apologies

**Comment by alanhogan** [comment]
@chriseppstein Removing sass-rails from my `gemfile` and `application.rb` results in:

```
undefined method `sass' for #<Rails::Application::Configuration:0x000001036a17e8>
```

**Comment by alanhogan** [comment]
Updated previous comment. Absolutely everything seems to work now.

**Comment by chriseppstein** [comment]
@alanhogan any url that is fully qualified or root relative will be passed through directly to the output, but usually it's better to just use the css `url()` function in those cases.

with respect to your next comment please link to a gist with the stack trace.

**Comment by chriseppstein** [comment]
please close this when you're satisfied :)

**Comment by alanhogan** [comment]
@chriseppstein FWIW, the stack trace you requested:

https://gist.github.com/1179939
