### ISSUE TITLE
apply-side-rhythm-border mixin

### ISSUE THREAD

**Issue by silvenon** [Compass/compass#521]
This mixin relies on negative padding, which browsers don't allow, so it doesn't really work.

**Comment by mirisuzanne** [comment]
The padding will only be negative if you are using it wrong. You can't make the width of the border more than the number of rhythm-units you want to span. 

We can add a warning when your numbers don't work, but the basic functionality does not need to be changed.

**Comment by silvenon** [comment]
Yeah, you're right. Padding is negative only if you use 0 $lines, so maybe there should be a warning that $lines should be greater than 0.

**Comment by mirisuzanne** [comment]
added a note in the docs. closed by 7fced9373e
