### ISSUE TITLE
Is 0.12 supposed to be backwards compatible with 0.11?

### ISSUE THREAD

**Issue by lloydk** [Compass/compass#524]
Is Compass 0.12 supposed to be backwards compatible with 0.11?  After upgrading my Rails application to Rails 3.1 and Compass 0.12.alpha.0 the app/stylesheets directory is no longer in my load paths. Is this a bug or expected behavior?

**Comment by lloydk** [comment]
Closing this issue as it looks like more work needs to be done to support Rails 3.1 with the asset pipeline disabled.

**Comment by chriseppstein** [comment]
Did you enable the asset pipeline?

**Comment by lloydk** [comment]
Still disabled for now, was going to fallback to 0.11.5 but that didn't seem to work either. My goal was to port my app over to Rails 3.1 with the asset pipeline disabled but it looks like enabling the pipeline might be the quicker option. I'd like to see Compass revert back to the "old" behavior if the pipeline is disabled but I couldn't come up with a quick patch so I went to bed :)

**Comment by chriseppstein** [comment]
I have a idea for how it can work. Will try it soon.
