### ISSUE TITLE
LoadError: no such file to load -- ./config/compass.class with jruby and wirble

### ISSUE THREAD

**Issue by qichunren** [Compass/compass#525]
I deployed my rails project on JRuby.
rails 3.0.9
jruby 1.6.4
wirble (0.1.3)

my compass.rb file in config/ is:

```
  # This configuration file works with both the Compass command line tool and within Rails.
  # Require any additional compass plugins here.
  project_type = :rails

  # Set this to the root of your project when deployed:
  http_path = "/"

  # You can select your preferred output style here (can be overridden via the command line):
  # output_style = :expanded or :nested or :compact or :compressed
  output_style = :compressed

  # To enable relative paths to assets via compass helper functions. Uncomment:
  # relative_assets = true

  # To disable debugging comments that display the original location of your selectors. Uncomment:
  line_comments = false


  # If you prefer the indented syntax, you might want to regenerate this
  # project again passing --syntax sass, or you can uncomment this:
  # preferred_syntax = :sass
  # and then run:
  # sass-convert -R --from scss --to sass app/stylesheets scss && rm -rf sass && mv scss sass
```

I use warble war compand to generate .war file and deploy it with tomcat, but when I viist my app, got 500 error, and I found error mesage in tomcat log:

This is my log:

<pre>

lAug 31, 2011 6:38:23 AM org.apache.catalina.core.ApplicationContext log
INFO: Warning: no max runtimes specified.
Aug 31, 2011 6:38:23 AM org.apache.catalina.core.ApplicationContext log
INFO: jruby 1.6.4 (ruby-1.8.7-p330) (2011-08-23 17ea768) (OpenJDK 64-Bit Server VM 1.6.0_22) [linux-amd64-java]
Aug 31, 2011 6:38:23 AM org.apache.catalina.core.ApplicationContext log
INFO: Info: using runtime pool timeout of 30 seconds
Aug 31, 2011 6:38:23 AM org.apache.catalina.core.ApplicationContext log
INFO: Warning: no min runtimes specified.
Aug 31, 2011 6:38:23 AM org.apache.catalina.core.ApplicationContext log
INFO: Warning: no max runtimes specified.
Aug 31, 2011 6:38:24 AM org.apache.catalina.core.ApplicationContext log
INFO: ContextListener: contextInitialized()
Aug 31, 2011 6:38:24 AM org.apache.catalina.core.ApplicationContext log
INFO: SessionListener: contextInitialized()
Aug 31, 2011 6:39:15 AM org.apache.catalina.core.ApplicationContext log
INFO: Warning: no min runtimes specified.
Aug 31, 2011 6:39:15 AM org.apache.catalina.core.ApplicationContext log
INFO: Warning: no max runtimes specified.
Aug 31, 2011 6:39:15 AM org.apache.catalina.core.ApplicationContext log
INFO: An exception happened during JRuby-Rack startup
no such file to load -- ./config/compass.class
--- System
jruby 1.6.4 (ruby-1.8.7-p330) (2011-08-23 17ea768) (OpenJDK 64-Bit Server VM 1.6.0_22) [linux-amd64-java]
Time: Wed Aug 31 06:39:15 -0400 2011
Server: Apache Tomcat/6.0.33
jruby.home: file:/home/qichunren/www/ntdeck/WEB-INF/lib/jruby-stdlib-1.6.4.jar!/META-INF/jruby.home

--- Context Init Parameters:
public.root = /
rails.env = production

--- Backtrace
LoadError: no such file to load -- ./config/compass.class
            require at org/jruby/RubyKernel.java:1038
            require at /home/qichunren/www/ntdeck/WEB-INF/gems/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239
    load_dependency at /home/qichunren/www/ntdeck/WEB-INF/gems/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:227
            require at /home/qichunren/www/ntdeck/WEB-INF/gems/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239
            require at /home/qichunren/www/ntdeck/WEB-INF/gems/gems/compass-0.11.5/lib/compass/configuration/data.rb:122
       parse_string at ./config/compass.rb:20
               eval at org/jruby/RubyKernel.java:1088
       parse_string at /home/qichunren/www/ntdeck/WEB-INF/gems/gems/compass-0.11.5/lib/compass/configuration/serialization.rb:21
             _parse at /home/qichunren/www/ntdeck/WEB-INF/gems/gems/compass-0.11.5/lib/compass/configuration/serialization.rb:15
               open at org/jruby/RubyIO.java:1111
               open at org/jruby/RubyKernel.java:298
               open at file:/home/qichunren/www/ntdeck/WEB-INF/lib/jruby-stdlib-1.6.4.jar!/META-INF/jruby.home/lib/ruby/1.8/open-uri.rb:32
             _parse at /home/qichunren/www/ntdeck/WEB-INF/gems/gems/compass-0.11.5/lib/compass/configuration/serialization.rb:14
      new_from_file at /home/qichunren/www/ntdeck/WEB-INF/gems/gems/compass-0.11.5/lib/compass/configuration/file_data.rb:29
      with_defaults at /home/qichunren/www/ntdeck/WEB-INF/gems/gems/compass-0.11.5/lib/compass/configuration/inheritance.rb:96
      new_from_file at /home/qichunren/www/ntdeck/WEB-INF/gems/gems/compass-0.11.5/lib/compass/configuration/file_data.rb:28
  configuration_for at /home/qichunren/www/ntdeck/WEB-INF/gems/gems/compass-0.11.5/lib/compass/configuration/helpers.rb:42
            compass at /home/qichunren/www/ntdeck/WEB-INF/gems/gems/compass-0.11.5/lib/compass/app_integration/rails/actionpack3/railtie.rb:27
            Railtie at /home/qichunren/www/ntdeck/WEB-INF/gems/gems/compass-0.11.5/lib/compass/app_integration/rails/actionpack3/railtie.rb:43
      instance_exec at org/jruby/RubyKernel.java:2078
                run at /home/qichunren/www/ntdeck/WEB-INF/gems/gems/railties-3.0.9/lib/rails/initializable.rb:25
   run_initializers at /home/qichunren/www/ntdeck/WEB-INF/gems/gems/railties-3.0.9/lib/rails/initializable.rb:50
               each at org/jruby/RubyArray.java:1603
   run_initializers at /home/qichunren/www/ntdeck/WEB-INF/gems/gems/railties-3.0.9/lib/rails/initializable.rb:49
        initialize! at /home/qichunren/www/ntdeck/WEB-INF/gems/gems/railties-3.0.9/lib/rails/application.rb:134
               send at org/jruby/RubyKernel.java:2092
     method_missing at /home/qichunren/www/ntdeck/WEB-INF/gems/gems/railties-3.0.9/lib/rails/application.rb:77
             (root) at config/environment.rb:5
            require at org/jruby/RubyKernel.java:1038
            require at /home/qichunren/www/ntdeck/WEB-INF/gems/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239
    load_dependency at /home/qichunren/www/ntdeck/WEB-INF/gems/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:225
   new_constants_in at /home/qichunren/www/ntdeck/WEB-INF/gems/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:596
   new_constants_in at /home/qichunren/www/ntdeck/WEB-INF/gems/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:595
    load_dependency at /home/qichunren/www/ntdeck/WEB-INF/gems/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:225
            require at /home/qichunren/www/ntdeck/WEB-INF/gems/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239
   load_environment at file:/home/qichunren/www/ntdeck/WEB-INF/lib/jruby-rack-1.0.10.jar!/jruby/rack/rails.rb:169
             to_app at file:/home/qichunren/www/ntdeck/WEB-INF/lib/jruby-rack-1.0.10.jar!/jruby/rack/rails.rb:173
                new at file:/home/qichunren/www/ntdeck/WEB-INF/lib/jruby-rack-1.0.10.jar!/jruby/rack/rails.rb:193
             (root) at <web.xml>:1
      instance_eval at org/jruby/RubyKernel.java:2061
         initialize at file:/home/qichunren/www/ntdeck/WEB-INF/lib/jruby-rack-1.0.10.jar!/vendor/rack-1.3.2/rack/builder.rb:51
             (root) at <web.xml>:1

--- RubyGems
Gem.dir: /home/qichunren/.rvm/gems/ruby-1.9.2-p290
Gem.path:
/home/qichunren/www/ntdeck/WEB-INF/gems
/home/qichunren/.rvm/gems/ruby-1.9.2-p290
/home/qichunren/.rvm/gems/ruby-1.9.2-p290@global
Activated gems:
  bundler-1.0.18
  rake-0.9.2
  abstract-1.0.0
  activesupport-3.0.9
  builder-2.1.2
  i18n-0.5.0
  activemodel-3.0.9
  erubis-2.6.6
  rack-1.2.3
  rack-mount-0.6.14
  rack-test-0.5.7
  tzinfo-0.3.29
  actionpack-3.0.9
  mime-types-1.16
  polyglot-0.3.1
  treetop-1.4.9
  mail-2.2.19
  actionmailer-3.0.9
  arel-2.0.10
  activerecord-3.0.9
  activerecord-jdbc-adapter-1.1.3
  activeresource-3.0.9
  bouncy-castle-java-1.5.0146.1
  highline-1.6.2
  net-ssh-2.1.4
  net-scp-1.0.4
  net-sftp-2.0.5
  net-ssh-gateway-1.1.0
  capistrano-2.6.0
  chunky_png-1.2.1
  client_side_validations-3.1.0
  fssm-0.2.7
  sass-3.1.7
  compass-0.11.5
  ffi-1.0.9-java
  ffi-ncurses-0.3.3
  globalize3-0.0.11
  jdbc-mysql-5.1.13
  jdbc-sqlite3-3.7.2
  jruby-openssl-0.7.4
  json-1.5.0-java
  json-jruby-1.5.0-java
  redis-2.2.0
  juggernaut-2.0.3
  rdoc-3.8
  thor-0.14.6
  railties-3.0.9
  rails-3.0.9
  kaminari-0.12.4
  memcache-client-1.8.5
  meta_search-1.0.6
  net-ldap-0.2.2
  net-ping-1.5.0
  nokogiri-1.5.0-java
  paperclip-2.3.11
  rails-settings-cached-0.1.2
  tts-0.2.3
  yahoo_weatherman-1.1.3

--- Bundler
Bundler.bundle_path: /home/qichunren/.rvm/gems/ruby-1.9.2-p290
Bundler.root: /home/qichunren/www/ntdeck/WEB-INF
Gemfile: /home/qichunren/www/ntdeck/WEB-INF/Gemfile
Settings:
  without = development:test
  gemfile = /home/qichunren/www/ntdeck/WEB-INF/Gemfile
  bin_path = /home/qichunren/www/ntdeck/WEB-INF/gems/gems/bundler-1.0.18/bin/bundle

--- JRuby-Rack Config
background_spooling = false
compat_version = 
filter_adds_html = true
filter_verifies_resource = false
ignore_environment = false
initial_runtimes = 
jms_connection_factory = 
jms_jndi_properties = 
logger = org.jruby.rack.logging.ServletContextLogger@5000debb
logger_class_name = servlet_context
logger_name = jruby.rack
maximum_runtimes = 
memory_buffer_size = 65536
num_initializer_threads = 
rackup = 
rackup_path = 
rewindable = true
runtime_timeout_seconds = 
serial_initialization = false
servlet_context = org.apache.catalina.core.ApplicationContextFacade@69fe17d

--- $LOAD_PATH:
/home/qichunren/www/ntdeck/WEB-INF/lib
/home/qichunren/www/ntdeck/WEB-INF/vendor
/home/qichunren/www/ntdeck/WEB-INF/app/controllers
/home/qichunren/www/ntdeck/WEB-INF/app/models
/home/qichunren/www/ntdeck/WEB-INF/app/stylesheets
/home/qichunren/www/ntdeck/WEB-INF/app/helpers
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/client_side_validations-3.1.0/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/kaminari-0.12.4/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/yahoo_weatherman-1.1.3/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/tts-0.2.3/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/rails-settings-cached-0.1.2/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/paperclip-2.3.11/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/nokogiri-1.5.0-java/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/net-ping-1.5.0/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/net-ldap-0.2.2/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/meta_search-1.0.6/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/memcache-client-1.8.5/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/rails-3.0.9/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/railties-3.0.9/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/thor-0.14.6/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/rdoc-3.8/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/juggernaut-2.0.3/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/redis-2.2.0/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/json-jruby-1.5.0-java/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/json-1.5.0-java/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/jruby-openssl-0.7.4/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/jdbc-sqlite3-3.7.2/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/jdbc-mysql-5.1.13/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/globalize3-0.0.11/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/ffi-ncurses-0.3.3/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/ffi-1.0.9-java/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/compass-0.11.5/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/sass-3.1.7/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/fssm-0.2.7/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/chunky_png-1.2.1/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/capistrano-2.6.0/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/net-ssh-gateway-1.1.0/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/net-sftp-2.0.5/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/net-scp-1.0.4/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/net-ssh-2.1.4/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/highline-1.6.2/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/bouncy-castle-java-1.5.0146.1/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/activeresource-3.0.9/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.1.3/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/activerecord-3.0.9/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/arel-2.0.10/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/actionmailer-3.0.9/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/mail-2.2.19/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/treetop-1.4.9/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/polyglot-0.3.1/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/mime-types-1.16/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/actionpack-3.0.9/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/tzinfo-0.3.29/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/rack-test-0.5.7/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/rack-mount-0.6.14/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/rack-1.2.3/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/erubis-2.6.6/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/activemodel-3.0.9/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/i18n-0.5.0/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/builder-2.1.2/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/activesupport-3.0.9/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/abstract-1.0.0/lib
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/rake-0.9.2/lib
file:/home/qichunren/www/ntdeck/WEB-INF/lib/jruby-rack-1.0.10.jar!/vendor/rack-1.3.2
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/bundler-1.0.18/lib
file:/home/qichunren/www/ntdeck/WEB-INF/lib/jruby-stdlib-1.6.4.jar!/META-INF/jruby.home/lib/ruby/site_ruby/1.8
file:/home/qichunren/www/ntdeck/WEB-INF/lib/jruby-stdlib-1.6.4.jar!/META-INF/jruby.home/lib/ruby/site_ruby/shared
file:/home/qichunren/www/ntdeck/WEB-INF/lib/jruby-stdlib-1.6.4.jar!/META-INF/jruby.home/lib/ruby/1.8
.
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/actionpack-3.0.9/lib/action_controller/vendor/html-scanner
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/rack-mount-0.6.14/lib/rack/mount/vendor/multimap
/home/qichunren/www/ntdeck/WEB-INF/gems/gems/rack-mount-0.6.14/lib/rack/mount/vendor/regin

Aug 31, 2011 6:39:15 AM org.apache.catalina.core.ApplicationContext log
SEVERE: Application Error
org.jruby.rack.RackInitializationException: no such file to load -- ./config/compass.class
    from /home/qichunren/www/ntdeck/WEB-INF/gems/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in `require'
    from /home/qichunren/www/ntdeck/WEB-INF/gems/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:227:in `load_dependency'
    from /home/qichunren/www/ntdeck/WEB-INF/gems/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in `require'
    from /home/qichunren/www/ntdeck/WEB-INF/gems/gems/compass-0.11.5/lib/compass/configuration/data.rb:122:in `require'
    from ./config/compass.rb:20:in `parse_string'
    from org/jruby/RubyKernel.java:1088:in `eval'
    from /home/qichunren/www/ntdeck/WEB-INF/gems/gems/compass-0.11.5/lib/compass/configuration/serialization.rb:21:in `parse_string'
    from /home/qichunren/www/ntdeck/WEB-INF/gems/gems/compass-0.11.5/lib/compass/configuration/serialization.rb:15:in `_parse'
    from org/jruby/RubyIO.java:1111:in `open'
    from org/jruby/RubyKernel.java:298:in `open'
    from file:/home/qichunren/www/ntdeck/WEB-INF/lib/jruby-stdlib-1.6.4.jar!/META-INF/jruby.home/lib/ruby/1.8/open-uri.rb:32:in `open'
    from /home/qichunren/www/ntdeck/WEB-INF/gems/gems/compass-0.11.5/lib/compass/configuration/serialization.rb:14:in `_parse'
    from /home/qichunren/www/ntdeck/WEB-INF/gems/gems/compass-0.11.5/lib/compass/configuration/file_data.rb:29:in `new_from_file'
    from /home/qichunren/www/ntdeck/WEB-INF/gems/gems/compass-0.11.5/lib/compass/configuration/inheritance.rb:96:in `with_defaults'
    from /home/qichunren/www/ntdeck/WEB-INF/gems/gems/compass-0.11.5/lib/compass/configuration/file_data.rb:28:in `new_from_file'
    from /home/qichunren/www/ntdeck/WEB-INF/gems/gems/compass-0.11.5/lib/compass/configuration/helpers.rb:42:in `configuration_for'
    from /home/qichunren/www/ntdeck/WEB-INF/gems/gems/compass-0.11.5/lib/compass/app_integration/rails/actionpack3/railtie.rb:27:in `compass'
    from /home/qichunren/www/ntdeck/WEB-INF/gems/gems/compass-0.11.5/lib/compass/app_integration/rails/actionpack3/railtie.rb:43:in `Railtie'
    from org/jruby/RubyKernel.java:2078:in `instance_exec'
    from /home/qichunren/www/ntdeck/WEB-INF/gems/gems/railties-3.0.9/lib/rails/initializable.rb:25:in `run'
    from /home/qichunren/www/ntdeck/WEB-INF/gems/gems/railties-3.0.9/lib/rails/initializable.rb:50:in `run_initializers'
    from org/jruby/RubyArray.java:1603:in `each'
    from /home/qichunren/www/ntdeck/WEB-INF/gems/gems/railties-3.0.9/lib/rails/initializable.rb:49:in `run_initializers'
    from /home/qichunren/www/ntdeck/WEB-INF/gems/gems/railties-3.0.9/lib/rails/application.rb:134:in `initialize!'
    from org/jruby/RubyKernel.java:2092:in `send'
    from /home/qichunren/www/ntdeck/WEB-INF/gems/gems/railties-3.0.9/lib/rails/application.rb:77:in `method_missing'
    from config/environment.rb:5:in `(root)'
    from org/jruby/RubyKernel.java:1038:in `require'
    from /home/qichunren/www/ntdeck/WEB-INF/gems/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in `require'
    from /home/qichunren/www/ntdeck/WEB-INF/gems/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /home/qichunren/www/ntdeck/WEB-INF/gems/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from /home/qichunren/www/ntdeck/WEB-INF/gems/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:595:in `new_constants_in'
    from /home/qichunren/www/ntdeck/WEB-INF/gems/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /home/qichunren/www/ntdeck/WEB-INF/gems/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in `require'
    from file:/home/qichunren/www/ntdeck/WEB-INF/lib/jruby-rack-1.0.10.jar!/jruby/rack/rails.rb:169:in `load_environment'
    from file:/home/qichunren/www/ntdeck/WEB-INF/lib/jruby-rack-1.0.10.jar!/jruby/rack/rails.rb:173:in `to_app'
    from file:/home/qichunren/www/ntdeck/WEB-INF/lib/jruby-rack-1.0.10.jar!/jruby/rack/rails.rb:193:in `new'
    from <web.xml>:1:in `(root)'
    from org/jruby/RubyKernel.java:2061:in `instance_eval'
    from file:/home/qichunren/www/ntdeck/WEB-INF/lib/jruby-rack-1.0.10.jar!/vendor/rack-1.3.2/rack/builder.rb:51:in `initialize'
    from <web.xml>:1:in `(root)'

    at org.jruby.rack.DefaultRackApplicationFactory$4.init(DefaultRackApplicationFactory.java:204)
    at org.jruby.rack.DefaultRackApplicationFactory.getApplication(DefaultRackApplicationFactory.java:54)
    at org.jruby.rack.PoolingRackApplicationFactory.getApplication(PoolingRackApplicationFactory.java:95)
    at org.jruby.rack.DefaultRackDispatcher.process(DefaultRackDispatcher.java:28)
    at org.jruby.rack.RackFilter.doFilter(RackFilter.java:58)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:291)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:602)
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
    at java.lang.Thread.run(Thread.java:679)
Caused by: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- ./config/compass.class

</pre>

I found he also got this problem:

http://spin.atomicobject.com/2011/02/18/odd-warbler-compass-gem-interaction/

**Comment by scottdavis** [comment]
you may just want to run `compass compile` in a deploy hook before you package the app up im not really sure what warbler is but this seems to be out side the scope of compass
