### ISSUE TITLE
0.12.alpha.0 and "File to import not found..."

### ISSUE THREAD

**Issue by scottkf** [Compass/compass#526]
``` ruby
ActionView::Template::Error (File to import not found or unreadable: blueprint/grid.
```

It's actually true for every file I try to import. Solving this was simply adding

``` ruby
require 'compass'
require 'sass-rails'
```

to `application.rb`

However, is this something that should be done automatically, or, what am I missing here?

**Comment by scottdavis** [comment]
run `bundle exec compass frameworks` in curious what the output is

**Comment by bmaland** [comment]
I suspect this was due to only including the compass and sass-rails gems in the asset group in Gemfile, they have to be in development as well.

**Comment by steverandy** [comment]
I was having the same issue with Rails 3.1.0, but it was ok when I upgraded to Rails 3.1.1.rc1.

But now I’m getting the same error with Rails 3.1.1.rc2.

**Comment by rwz** [comment]
Same here. Worked on rc1, fails on rc2.

```
% bundle exec compass frameworks
Available Frameworks & Patterns:

  * blueprint
    - blueprint/basic      - A basic blueprint install that mimics the actual blueprint css.
    - blueprint/buttons    - Button Plugin
    - blueprint/link_icons - Icons for common types of links
    - blueprint/project    - The blueprint framework.
    - blueprint/semantic   - The blueprint framework for use with semantic markup.
  * compass
    - compass/ellipsis     - Plugin for cross-browser ellipsis truncated text.
    - compass/extension    - Generate a compass extension.
    - compass/pie          - Integration with http://css3pie.com/
    - compass/project      - The default project layout.
```
