### ISSUE TITLE
Rails 3.1 and @include all-<name>-sprites;

### ISSUE THREAD

**Issue by maxguzenski** [Compass/compass#528]
I've a issue when using compass (branch 3.1) with rails 3.1 that works in rails 3.0

//screen.css.scss at 
@import "icons/gray16x16/*.png";
@include all-gray16x16-sprites;

So, a got this error on reload my browser:

Sass::SyntaxError: Invalid CSS after ".icons": expected selector, was "/gray16x16-add"  (in /Users/max/projetos/d4swing/ app/assets/stylesheets/screen.css.scss)";

ps.:  when use ".class { @include gray16x16-sprite(add); }" it works well.

MY GEMFILE
# core dependencies

gem 'rails', '~> 3.1.0'
gem 'sprockets', '~> 2.0.0.beta.12'
gem 'mysql2'

group :assets do
  gem 'sass-rails', "  ~> 3.1.0.rc"
  gem 'coffee-rails', "~> 3.1.0.rc"
  gem 'uglifier'
  gem 'compass', :git => "git://github.com/chriseppstein/compass.git", :branch => "rails31"  
end

( ... more gems ... )

**Comment by chriseppstein** [comment]
This is likely because one of your filenames is not a legal CSS identifier. 

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by scottdavis** [comment]
@chriseppstein no it shouldn't be that i added a better error for that case:

https://github.com/chriseppstein/compass/blob/master/lib/compass/sprite_importer.rb#L81

it might be because you have a nested directory but im not sure. chris changed a lot of stuff and broke some things it seems

**Comment by maxguzenski** [comment]
My filenames at icons/gray16x16/ is:

add.png, calendar.png, close.png, edit.png, home.png, message.png, search.png, trash.png and user.png

sprit was generated ok (file with all icons together) but styles is not.

I think that something in compass is trying to generate a style with name "/gray16x16", but should be just "gray16x16"

remember, it works right in rails 3.0 and last compass from rubygems.org

**Comment by scottdavis** [comment]
would you mind making a small test project that i could play with?

**Comment by chriseppstein** [comment]
@maxguzenski please help us debug this

**Comment by scottdavis** [comment]
i bet this is related to the to_tree problem that nex3 just fixed

**Comment by maxguzenski** [comment]
Sorry, I'll try with last compass 3.1 branch

**Comment by scottdavis** [comment]
use master not 3.1 please

**Comment by scottdavis** [comment]
any update on this?

**Comment by maxguzenski** [comment]
Sorry, I was traveling...

My project is not using compass anymore, but I get my old branch back, put compass from master and with a simples:

@import "/assets/images/icons/color16x16/*.png";

I always get:

Sass::SyntaxError: File to import not found or unreadable: /assets/images/icons/color16x16/*.png

I tryied:

@import "/assets/images/icons/color16x16/_.png";
@import "/images/icons/color16x16/_.png";
@import "/icons/color16x16/*.png";

anyone works.

**Comment by maxguzenski** [comment]
My fault...

It is working!

gemfile:
gem 'compass', :git => "git://github.com/chriseppstein/compass.git"

sass:
@import "icons/color16x16/*.png";
@include all-gray16x16-sprites;
