### ISSUE TITLE
sprite position

### ISSUE THREAD

**Issue by sroussey** [Compass/compass#531]
From the docs:

$<map>-position -- The position of the sprite in the sprite map along the x-axis. Can be specified in pixels or percentage of the sprite map's width. 100% would cause the sprite to be on the right-hand side of the sprite map. Defaults to 0px. E.g. $icon-position: 100%.

Sadly, it simply does not work.

And if that does get fixed, I thing the magic :hover stuff wouldn't pick it up as they don't pass all the parameters.

**Comment by scottdavis** [comment]
Are you running the alpha I pretty sure I fixed this?

**Comment by sroussey** [comment]
The second part of the issue I created a different ticket for, and indeed it looks fixed in master though not stable. 

But the main part, setting position of 50% for example, doesn't seem to work in either case.

**Comment by scottdavis** [comment]
ok ill look into it

**Comment by chriseppstein** [comment]
@scottdavis ping

**Comment by scottdavis** [comment]
havent goten to it yet

**Comment by scottdavis** [comment]
so i found a inconsistant when we re did a lot of the core sprite code the docs sated `$<map>-<sprite>-postion` but the implementation was expecting `$<sprite>-position` im fixing the implementation to match the documentation as it does actually make sense.

note: `map` is the folder name and `sprite` is the individual filename

**Comment by scottdavis** [comment]
This should be now fixed in master if someone wants to verify a position of 50% works in my test app

**Comment by scottdavis** [comment]
@sroussey ping

**Comment by scottdavis** [comment]
no response works for me closing this

**Comment by jonjaques** [comment]
@scottdavis I've actually had some problems relating to this, but I'd like to make sure I know what I'm talking about before I post about it. Basically, I have an existing codebase using 0.11, with some heavy spriting options - but it doesn't seem to work 100% with 0.12 (Differences in the generated sprite image).

Do you know if the 0.11 documentation is deployed anywhere?

**Comment by theamnesic** [comment]
@scottdavis  This issue seems to have popped up again under 0.12 with position in px or %…

**Comment by FlyingDR** [comment]
Confirm existence of the problem in Compass 0.12.2, at least with this syntax (it was working properly in 0.11.x):

```
$sprites_map: sprite-map('sprites/*/*.png'
    ,$icons-link_arrow-position: 100%
);
```

switching from `$<map>-<sprite>-position` to `$<sprite>-position` doesn't work too.

**Comment by sunny** [comment]
Error pops up here with a position of `100%`.

**Comment by sunny** [comment]
On apps that used 0.11, we had to replace all our sprite code that used positions. Here is what fixes it : replacing `$<icon>-` by `$<map>-<icon>-`. E.g. :

``` diff
 $icons: sprite-map("sprites/icons/*.png",
   $spacing: 100px,
-  $arrow-position: 100%
+  $icons-arrow-position: 100%
 );
```

Too bad there was no deprecation handling.
