### ISSUE TITLE
sprite extra wordy for hover, etc

### ISSUE THREAD

**Issue by sroussey** [Compass/compass#532]
Instead of just adding :hover, it also add several other choices, making the css real big. 

.commerce-editor-tabbar .preview {
  background-position: 0 -480px;
}
.commerce-editor-tabbar .preview:hover, .commerce-editor-tabbar .preview.preview_hover, .commerce-editor-tabbar .preview.preview-hover {
  background-position: 0 -560px;
}

I would rather have:

.commerce-editor-tabbar .preview:hover, .commerce-editor-tabbar .preview.hover, .commerce-editor-tabbar .preview.hover {
  background-position: 0 -560px;
}

Who would ever create a script that adds class names like that? If I wanted a hover effect via adding a class name it would be "hover" not a different class name for each one of the sprites (which is already a different class name!)....

**Comment by scottdavis** [comment]
There are a few use cases where having the extra class name is helpful in case you need to @extend etc we didn't we didn't implement this blindly if you check prior tickets you can see the discussions

**Comment by sroussey** [comment]
I tried creating my own mixin to "fix" this issue, but neither including it before nor including it after seems to have much effect. How do others deal with this?

**Comment by scottdavis** [comment]
besides being a little verbose what exactly is the issue? if you don't want to extra classes you can turn off the magic selectors by setting the config option `$disable-magic-sprite-selectors` to `true`. but by doing this you will need to manualy create each state selector by using the `<whatever>-sprite` mixins
