### ISSUE TITLE
Magic Sprite Selectors not applying background position

### ISSUE THREAD

**Issue by sroussey** [Compass/compass#533]
From back in May:

http://groups.google.com/group/compass-users/browse_thread/thread/d2560d178f4518d8

It is pretty easy to see the bug in line 44:

https://github.com/chriseppstein/compass/blob/stable/frameworks/compass/stylesheets/compass/utilities/sprites/_base.scss#L44

It _does_ get passed otherwise:

https://github.com/chriseppstein/compass/blob/stable/frameworks/compass/stylesheets/compass/utilities/sprites/_base.scss#L28

So lines 33, 40, and 44 need to change to pass them around.

**Comment by scottdavis** [comment]
mind making a patch?

**Comment by sroussey** [comment]
Looking around I think this is fixed in master, likely a while ago. Just have to wait I guess.

**Comment by scottdavis** [comment]
master is pushed to the 0.12.alpha gem
