### ISSUE TITLE
Integration within Rails 3.1 and its Assert Pipeline

### ISSUE THREAD

**Issue by frarees** [Compass/compass#539]
I'm not a Guru on this topic, but: 

I've installed compass **0.12.alpha.0**, then typed `compass init rails /path/to/app`. What I see is that it generated those files: 

directory ./app/stylesheets/ 
   create ./config/compass.rb 
   create ./app/stylesheets/screen.scss 
   create ./app/stylesheets/print.scss 
   create ./app/stylesheets/ie.scss 

Following Rails' convention, shouldn't *.scss files renamed to *.css.scss? Shouldn't them be placed on `.lib/assets/stylesheets/` instead of `./app/stylesheets/`?

Thanks for reading, and I'll appreciate your criticism here (note that I'm a kind of beginner on this topic).

**Comment by ramontayag** [comment]
It's not completely supported yet. There's been development on this end. For now you'll need to [do some stuff manually](http://stackoverflow.com/questions/6480124/how-to-use-compass-with-rails-3-1).

**Comment by frarees** [comment]
Thanks for the info! Btw, I hadn't had to make any changes by myself, and I think everything is working out of the box! (Correct me if I'm wrong). 

Just installing the gem, then moving those files to the proper folder (to fit the assets pipeline, in my case in `lib/assets`) did. At least, I can access those 3 stylesheets properly.

**Comment by ramontayag** [comment]
Yup! It's not a lot of work to set it up manually.

**Comment by scottdavis** [comment]
you no longer need to compass init rails with rails 3.1 just add compass to your Gemfile if you do need a config file you can create one in app/config/compass.rb and you can over ride the railtie defaults. the compass init command should probably warn you about this.

**Comment by chriseppstein** [comment]
We need to deprecate that command for rails and emit a link to updated docs. Leaving this open to track those aspects.

**Comment by ChristianPeters** [comment]
Do you also have compass extensions on your radar?

`compass install my_extension` should copy templates into an `assets` folder.

**Comment by chriseppstein** [comment]
fixed in 0.12
