### ISSUE TITLE
compass install Doesn't Work if Not In Project Root

### ISSUE THREAD

**Issue by Snugug** [Compass/compass#541]
The title says it all. Compass installs, especially of the type where you are requiring a library and installing it at the same time, do not appear to work if you are not in the root of your project folder. It will appear to work and the command line will return that it's worked, but it doesn't touch the config.rb file and it creates the structure it needs from the folder you are in.

**Comment by chriseppstein** [comment]
compass install takes an argument to specify the directory.

**Comment by Snugug** [comment]
Didn't know that. Perhaps some better documentation on compass install, or if you could point me to the compass install documentation, would be ideal.

**Comment by chriseppstein** [comment]
all the cli is self documenting you can say `compass help <command>` or `compass <command> -h`

**Comment by Snugug** [comment]
Oh, well thanks! I'll close this now, answers my question.
Thanks much for your help on Twitter today, and love Compass
