### ISSUE TITLE
make new compilation helper functions

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#542]
- `compass-env()` - returns `production` or `development`
- `current-date($format)`
- `current-time($format)`
- `current-source-file()`
- `current-output-file()`

**Comment by scottdavis** [comment]
@chriseppstein did you implement this?

**Comment by chriseppstein** [comment]
I added `compass-env()`

**Comment by scottdavis** [comment]
what did you want the format to take the ruby? strftime arguments?

**Comment by chriseppstein** [comment]
@scottdavis is there some better known format we could use easily? I can't think of one.

**Comment by scottdavis** [comment]
We can make up one but that's hard

**Comment by scottdavis** [comment]
or make macros

**Comment by chriseppstein** [comment]
let's go with ruby's format syntax this is not a major feature and they're well documented.

**Comment by scottdavis** [comment]
2cbeb25

**Comment by scottdavis** [comment]
60ed958

**Comment by scottdavis** [comment]
81d2a44

**Comment by chriseppstein** [comment]
Looks great. Needs some docs tho.

**Comment by scottdavis** [comment]
Yea I noted that in the google doc
