### ISSUE TITLE
font_files helper requires font types to be named explicitly

### ISSUE THREAD

**Issue by ravinggenius** [Compass/compass#544]
Is this by design? I'd like to be able to leave off the font type if it could be inferred by the extension. I don't mind refactoring this myself. Any comments?

**Comment by ravinggenius** [comment]
I went ahead and made the changes. Feel free to adjust if necessary.

**Comment by scottdavis** [comment]
looks fine to me

**Comment by ravinggenius** [comment]
I added a pull request (issue #545).
