### ISSUE TITLE
Recompilation of a single scss file with 30+ includes now takes 15 mins on Rails 3.1

### ISSUE THREAD

**Issue by mwawrusch** [Compass/compass#546]
I do not preload mongoid models, I added rails-dev-tweaks but still got that lousy response time of 15 minutes per change in my css file. Interestingly precompilation does take seconds at most.

Not sure if this is compass' fault or sprockets's but I guess I start at the top of the food chain... In any case I could use some creative ideas how to speed that up.

**Comment by chriseppstein** [comment]
sorry I didn't reply sooner. Can you move your stylesheets to a fresh app and reproduce this issue? If you can, please email that app to me for testing. chris@eppsteins.net

**Comment by mwawrusch** [comment]
no problem. I try to get you something, but will take some time.

**Comment by scottdavis** [comment]
also are you using sprites?

**Comment by mwawrusch** [comment]
Hi Chris, Scott
actually everything is fine now. Some changes between then and now in
Compass or Rails fixed it. Super fast now. And I don't use sprites (well I
do, but I export them from fireworks directly, not using the compass
version)

Thanks
Martin
