### ISSUE TITLE
Allow --debug-info from command line

### ISSUE THREAD

**Issue by timkelty** [Compass/compass#552]

**Comment by scottdavis** [comment]
can you be a bit more descriptive?

**Comment by timkelty** [comment]
Sorry, yes.

I'd like to be able to invoke sass's --debug-info flag, but from compass watch/compile.

Currently in config.rb I can do:
`sass_options = {
  :debug_info => true
}`
But I'd also like to be able to do this, from the command line:
`compass compile --debug-info` or `compass compile --no-debug-info`

**Comment by gcpantazis** [comment]
Just a note to the admins that this appears to have been resolved; I can run `--debug-info` on my `compass compile` commands, works as desired.
