### ISSUE TITLE
appearance mixin doesn't work with 'field' param value for an input[type=search] in webkit for mac

### ISSUE THREAD

**Issue by joiggama** [Compass/compass#553]
When trying to use:

```
input[type=search] {
  @include appeareance('field');
   ...
}
```

Does not actually makes my `input` element look like a normal field while browsing with chrome for mac (I guess it's the same for Safari). Playing with the DOM I saw `-webkit-appearance:  field` crossed. But it works with:

```
input[type=search] {
  @include appearance('textfield');
}
```

**Comment by chriseppstein** [comment]
@ericam ping

**Comment by mirisuzanne** [comment]
If I understand right, this is simply a change to the docs? does 'textfield' work in place of 'field' on all browsers, or do we need both when 'field' is passed?

**Comment by joiggama** [comment]
Yes, I suposse it would work. I don't actually use appearance mixin that much. I had to use it because of webkit for mac, wasn't getting my styles right. Any other browser was working just fine.

**Comment by mirisuzanne** [comment]
Updated the docs: 

6ad3bd73a7085f2a9edb09671e2b952647055c2f
2af118ec83b78b97a2c64a86e113ea30ebc8854e
