### ISSUE TITLE
sprite tests broken in jruby for smart layout

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#555]
http://travis-ci.org/#!/chriseppstein/compass/builds/165943

**Comment by chriseppstein** [comment]
same issue in rbx it seems: http://travis-ci.org/#!/chriseppstein/compass/builds/165944

**Comment by scottdavis** [comment]
yea im not sure what the deal is i don't know enough about jruby.. i donno if they are broken or just things are getting calculated differently in jruby, rbx

**Comment by scottdavis** [comment]
i did a manual test and they are working fine in jruby, rbx the scan packer when using smart layout is just doing things differently for some reason I asked @johnbintz to look at it when he had time since he wrote 90% of that at railsconf

**Comment by johnbintz** [comment]
@scottdavis, try this: https://github.com/johnbintz/compass/commit/c9593794bdfab5f7ce5edecd8d12f988c3741450
