### ISSUE TITLE
_reset.css body line-height should not be in ems

### ISSUE THREAD

**Issue by gpbmike** [Compass/compass#56]
Should be:
line-height: 1;

Not:
line-height: 1em;

see http://meyerweb.com/eric/thoughts/2007/05/01/reset-reloaded/

**Comment by chriseppstein** [comment]
Interesting. Aren't these the same?

**Comment by gpbmike** [comment]
I thought they were the same too until just now. I changed it from 1em to 1 in firebug and saw the computed line-height change from 12px to 24px which is what I had expected. Learn something new every day.

**Comment by chriseppstein** [comment]
fixed. Thanks for the patch.
