### ISSUE TITLE
Git tag should be "v0.12.alpha.0"

### ISSUE THREAD

**Issue by yfeldblum** [Compass/compass#561]
The git tag for `v0.12.alpha.0` should be `v0.12.alpha.0` to be consistent with all the other version tags, which have a leading `v`.

**Comment by scottdavis** [comment]
typo? "The git tag for v0.12.alpha.0 should be v0.12.alpha.0"

**Comment by yfeldblum** [comment]
> The git tag, for what is in fact actually `v0.12.alpha.0` (short for `version 0.12.alpha.0`), should be the text '`v0.12.alpha.0`'.

**Comment by jaylevitt** [comment]
... so that it doesn't show up all the way in the bottom of the github menu, for one thing.

**Comment by chriseppstein** [comment]
Fixed. Committers should run the following or else the tag will reappear if they push any tags:

```
git tag -d 0.12.alpha.0
```
