### ISSUE TITLE
erb in partials not rendering

### ISSUE THREAD

**Issue by anathematic** [Compass/compass#563]
Hello!
It looks like I've run into an issue with Rails 3.1 + 0.12.alpha.0, erb snippets in partials are not rendering when pulled into the main files via @import

Some example codes:
`background-image: url('<%= asset_path "application/fancy-button-background-blue.png" %>');`

Renders as :
`background-image: url('<%= asset_path "application/fancy-button-background-blue.png" %>');`

Any thoughts?

Cheers!

**Comment by scottdavis** [comment]
why are you using erb in partials? the sass image_path function should do what you need

**Comment by anathematic** [comment]
Aha! I wasn't actually aware of the image_path function which resolved my issue, for others:
`background-image: url(image_path("application/fancy-button-background-blue.png"));`

Is an example of using image_path function.

Thanks Scott!

**Comment by chriseppstein** [comment]
Just use `image-url` which obviates the need for wrapping with url.
