### ISSUE TITLE
Replace Text With Sprite

### ISSUE THREAD

**Issue by ultimatedelman** [Compass/compass#566]
I came across an issue where I wanted to use "replace-text-with-dimensions" and sprites and discovered there's no built in way to do it. So I created a mixin :)

```
@mixin sprite-replace-text ($sprite, $img-name){    
    @include hide-text;
    background: sprite($sprite, $img-name) no-repeat;
    display: block;
    width: image-width(sprite-file($sprite, $img-name));
    height: image-height(sprite-file($sprite, $img-name));
}
```

To use, first, create your sprite outside of the mixin (to pass in):

`$social: sprite-map('social/*.png');`

Then call the mixin like so:

```
.twitter    {@include sprite-replace-text($social, twitter);}
.facebook   {@include sprite-replace-text($social, facebook);}
```

where "twitter" and "facebook" are the names of the images in the sprite folder.

**Comment by scottdavis** [comment]
+1 mind making a pull request?

**Comment by chriseppstein** [comment]
+1

**Comment by ultimatedelman** [comment]
I've forked the repo... Where should I put this mixin? I was thinking about putting it in the `sprites/_base.scss` but I'm not sure exactly.

EDIT: I decided that is probably the best spot to put it. Committed, pull request sent! :)

**Comment by scottdavis** [comment]
closing since theres a pr
