### ISSUE TITLE
pretty-bullets not properly resolving long image path

### ISSUE THREAD

**Issue by davidortinau** [Compass/compass#570]
My assets are buried in a themes package, so my SASS looks like:

ul.nav
+pretty-bullets("/themes/lifepoint/assets/images/small_bullet.png")

The Compass process spits out the error:

Errno::ENOENT on line 30 of /Users/dave/.rvm/gems/ruby-1.8.7-p302/gems/compass-0.11.5/lib/compass/sass_extensions/functions/image_size.rb: No such file or directory - /work/lifepointplano/themes/lifepoint/assets/images/themes/lifepoint/assets/images/small_bullet.png

Dunno why it's doubling up the path. If I amend the path to:

ul.nav
+pretty-bullets("small_bullet.png")

it converts fine, however the resulting CSS is looking for the image in the root (/images/small_bullet.png).

**Comment by chriseppstein** [comment]
Can I see your compass config?

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by davidortinau** [comment]
Here you go:

http_path = "/"
css_dir = "stylesheets"
sass_dir = "sass"
images_dir = "images"
javascripts_dir = "javascript"

preferred_syntax = :sass

**Comment by chriseppstein** [comment]
Are all your images in that folder? If so set images_dir = "themes/lifepoint/assets/images". 

you can also set http_images_path to the location where images are served if it doesn't match after that. 

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by davidortinau** [comment]
Yes, most of my images are there, so I'll go ahead and do that.

What do you think about having pretty-bullets recognize the leading / (and other path related starters) and override the images_dir default for that path? I may have some images here, and other images on S3, etc.

**Comment by chriseppstein** [comment]
Any image URL that starts with / is passed thru. But keep in mind you can always just use normal URL references. 

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by chriseppstein** [comment]
With respect to pretty bullets, the mixin uses the image dimension helpers so it has to find the image on disk. You can copypasta the mixin and tweak it if you have other needs. 

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by davidortinau** [comment]
Gotcha. Thanks for the info and quick replies. 

I did some digging last night through the source, but I'm still getting my bearings. I hate bringing up issues without seeing the code and being able to offer some kind of half-baked solution.

**Comment by chriseppstein** [comment]
Closing.
