### ISSUE TITLE
transition-duration mixin doesn't support multiple arguments

### ISSUE THREAD

**Issue by davidchambers** [Compass/compass#575]
From the documentation:

> One or more durations in seconds
> - for multiple, use a comma-delimited list
> - these durations will affect the properties in the same list position

---
### foo, bar, baz

```
+transition-duration(0.2s, 0.5s, 0.2s)
```

gives…

```
error sass/screen.sass (Line {n}: Mixin transition-duration takes 1 argument but 3 were passed.)
```

---
### foo bar baz

```
+transition-duration(0.2s 0.5s 0.2s)
```

produces…

```
-moz-transition-duration: 0.2s 0.5s 0.2s;
-webkit-transition-duration: 0.2s 0.5s 0.2s;
-o-transition-duration: 0.2s 0.5s 0.2s;
transition-duration: 0.2s 0.5s 0.2s;
```

---
### "foo, bar, baz"

```
+transition-duration("0.2s, 0.5s, 0.2s")
```

produces…

```
-moz-transition-duration: 0.2s, 0.5s, 0.2s;
-webkit-transition-duration: 0.2s, 0.5s, 0.2s;
-o-transition-duration: 0.2s, 0.5s, 0.2s;
transition-duration: 0.2s, 0.5s, 0.2s;
```

---

Is this correct behaviour? As a new Compass user, I expected `+transition-duration(0.2s, 0.5s, 0.2s)` to work.

**Comment by chriseppstein** [comment]
seems like a bug. workaround is an extra set of parenthesis:

```
+transition-duration((0.2s, 0.5s, 0.2s))
```

**Comment by davidchambers** [comment]
Oh, yep. I've been wrapping `0.2s, 0.5s, 0.2s` in quotes, which also works.

**Comment by scottdavis** [comment]
I don't think this is a bug since sass doesn't support literal arguments the same way ruby does so passing the extra set of parenthesis is needed for now. what would be nice is if sass had:
<pre>
@mixin foo($bar: ...) {
  @each $argument in $bar {
    //do something with $argument
  }
}
</per>
