### ISSUE TITLE
URIs unnecessarily quoted

### ISSUE THREAD

**Issue by davidchambers** [Compass/compass#576]
From [section 4.3.4](http://www.w3.org/TR/CSS2/syndata.html#uri) of the CSS2 spec (emphasis mine):

> The format of a URI value is 'url(' followed by optional [white space](http://www.w3.org/TR/CSS2/syndata.html#whitespace) followed by an _optional_ single quote (') or double quote (") character followed by the URI itself, followed by an optional single quote (') or double quote (") character followed by optional white space followed by ')'.

There may be a good reason that Compass includes quotation marks. If not, perhaps we could omit them.

---

Note: I'm writing this having just tried the (extremely cool) `inline-image` function. I don't know whether similar functions also output quotation marks.

**Comment by chriseppstein** [comment]
url is a special case function that acts like a quotation in css. all other functions take strings unless they accept a simple identifier. I use quotes for consistency. are you worried about extra bytes?

**Comment by davidchambers** [comment]
> are you worried about extra bytes?

Nope. I was simply keen to learn the reasoning behind the quotation marks' inclusion. Having done so I can sleep peacefully. :)
