### ISSUE TITLE
Adjacent Sibling Selectors being interpreted as compass functions

### ISSUE THREAD

**Issue by daflip** [Compass/compass#578]
This didn't happen previously:

  error sass/application.scss (Line 92: Invalid CSS after "  input.checkbox+": expected number or function, was "label ..")

Related scss code:

input.checkbox+label { text-transform: none; } 

Version:

`--> gem list|grep compa
compass (0.11.5, 0.11.1)

**Comment by daflip** [comment]
Sorry, my bad this is actually a problem with the sass dependency and not compass itself. https://github.com/nex3/sass/pull/182

**Comment by chriseppstein** [comment]
Please define "previously".

**Comment by daflip** [comment]
"previously": before sass version 3.1.8. As mentioned the issue stems from a regressional bug in sass, not compass itself.
