### ISSUE TITLE
Error compiling asset on blueprint button plugin

### ISSUE THREAD

**Issue by pabloalr** [Compass/compass#579]
Rails 3.1, Compass v0.12.alpha.0, Blueprint Button plugin.

`Sass::SyntaxError: Invalid CSS after "  *": expected identifier, was ":first-child+ht..."`

I'm really clueless on how to fix this.

**Comment by scottdavis** [comment]
can you provide an example? of the steps needed to get to this point so we can trouble shoot?

**Comment by pabloalr** [comment]
I'm only doing a regular @import buttons.

Looks like it's a syntax issue on frameworks/blueprint/stylesheets/blueprint/_buttons.scss:98

**Comment by chriseppstein** [comment]
this is a regression in sass. I think there will be a fix by @nex3 soon.

**Comment by pabloalr** [comment]
ok, w'll wait before moving to production. Thanks!

**Comment by onelson** [comment]
fwiw, I ran into this the yesterday and the error went away when I downgraded sass from 3.1.8 to 3.1.4 (to match another working environment I have here). There might be a higher version of sass that still works, but I didn't have time to dig in and find out.

**Comment by pzgz** [comment]
FYI, I have exactly same issue. Apparently @nex3 has fixed it in the new sass commits, I upgraded my rails to 3.1.1 and sass has been changed to 1.3.10, verified the issue is gone.

**Comment by jgn** [comment]
Does anyone know a prior working compass / sass combination? I.e., versions of the two that worked together without generating this error? I've downgraded through a variety of versions but haven't hit a good combination yet.
