### ISSUE TITLE
Problem with paths calculation for cache buster in image-url()

### ISSUE THREAD

**Issue by FlyingDR** [Compass/compass#583]
Project layout:

```
/scss
/public
    /css
    /images
        bg.png
```

Compass project resides in `/scss`, images are in `public/images`, compiled CSS is expected to be in `public/css`.

Contents of config.rb:

``` ruby
project_type = :stand_alone
http_path = "/"
sass_dir = "."
css_path = "../public/css"
css_dir = "css"
images_path = "../public/images"
images_dir = "images"
```

Contents of test.scss:

```
.test {
    background-image: image-url('bg.png');
}
```

Compilation process (Compass v0.11.5):

```
D:\project>cd test

D:\project\test>compass compile
WARNING: 'bg.png' was not found (or cannot be read) in D:/project/test/images
   create test.css

D:\project\test>
```

Please notice "File not found" warning and invalid path, image is searched in.

Resulted CSS:

```
.test {
  background-image: url('/images/bg.png');
}
```

Small research shows that problem is in `lib/compass/sass_extensions/functions/urls.rb` lines 73-76:

``` ruby
# Compute the real path to the image on the file stystem if the images_dir is set.
real_path = if Compass.configuration.images_dir
  File.join(Compass.configuration.project_path, Compass.configuration.images_dir, path)
end
```

 As can be seen - real path calculation uses `project_path` configuration variable as base path, but Compass documentation ( http://compass-style.org/help/tutorials/configuration-reference/#configuration-properties ) says that `project_path` is ignored when `project_type = :stand_alone`. Hence this expression leads to invalid path which results in above warning.

Quick fix which works fine for me is to check if `images_path` configuration variable is defined and use it for path calculation if it is:

``` ruby
# Compute the real path to the image on the file system if the images_dir is set.
real_path = if Compass.configuration.images_path
  File.join(Compass.configuration.project_path, Compass.configuration.images_path, path)
elsif Compass.configuration.images_dir
  File.join(Compass.configuration.project_path, Compass.configuration.images_dir, path)
end
```

However I may be wrong in my proposed fix since I don't know project codebase well.

**Comment by scottdavis** [comment]
feel like making a pull request / tests?

**Comment by FlyingDR** [comment]
I'm not a Ruby developer at all, not sure if I will be able to create proper tests for it, especially for Rails type of projects, simply have no experience with it

**Comment by scottdavis** [comment]
no problem ill add this to the 0.12 milestone and ill do it

**Comment by scottdavis** [comment]
oh this is a configuration issue not a compass issue you need to set your image_dir relative to your project config file so in this case it would be the same as image_path

**Comment by dey-dey** [comment]
Uh I'm still having the same issue

proj/scss
img/l.jpg

images_dir = "../img"

error:

WARNING: 'l.jpg' was not found (or cannot be read) in /images
