### ISSUE TITLE
 `method_missing': undefined method `sass' 

### ISSUE THREAD

**Issue by markmcdonald51** [Compass/compass#584]
I wanted to use compass and blueprint for a project...

ran: compass init rails .  --using blueprint

then added to mt Gemfile:
gem "compass", ">= 0.12.alpha.0"

bundle install

rails s returns this:

home/mark/.rvm/gems/ruby-1.9.2-head/gems/railties-3.1.0/lib/rails/railtie/configuration.rb:78:in `method_missing': undefined method`sass' for #Rails::Application::Configuration:0x000000027afb28 (NoMethodError)
    from /home/mark/.rvm/gems/ruby-1.9.2-head/gems/compass-0.12.alpha.0/lib/compass/configuration/helpers.rb:82:in `block in configure_rails!'
    from /home/mark/.rvm/gems/ruby-1.9.2-head/gems/compass-0.12.alpha.0/lib/compass/configuration/helpers.rb:81:in`each'
    from /home/mark/.rvm/gems/ruby-1.9.2-head/gems/compass-0.12.alpha.0/lib/compass/configuration/helpers.rb:81:in `configure_rails!'
    from /home/mark/.rvm/gems/ruby-1.9.2-head/gems/compass-0.12.alpha.0/lib/compass/app_integration/rails/actionpack31/railtie.rb:86:in`block in class:Railtie'
    from /home/mark/.rvm/gems/ruby-1.9.2-head/gems/railties-3.1.0/lib/rails/initializable.rb:25:in `instance_exec'
    from /home/mark/.rvm/gems/ruby-1.9.2-head/gems/railties-3.1.0/lib/rails/initializable.rb:25:in`run'
    from /home/mark/.rvm/gems/ruby-1.9.2-head/gems/railties-3.1.0/lib/rails/initializable.rb:50:in `block in run_initializers'
    from /home/mark/.rvm/gems/ruby-1.9.2-head/gems/railties-3.1.0/lib/rails/initializable.rb:49:in`each'
    from /home/mark/.rvm/gems/ruby-1.9.2-head/gems/railties-3.1.0/lib/rails/initializable.rb:49:in `run_initializers'
    from /home/mark/.rvm/gems/ruby-1.9.2-head/gems/railties-3.1.0/lib/rails/application.rb:92:in`initialize!'
    from /home/mark/.rvm/gems/ruby-1.9.2-head/gems/railties-3.1.0/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /home/mark/RailsProjects/two_factor_auth_rails/config/environment.rb:5:in`<top (required)>'
    from /home/mark/.rvm/gems/ruby-1.9.2-head/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in `require'
    from /home/mark/.rvm/gems/ruby-1.9.2-head/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in`block in require'
    from /home/mark/.rvm/gems/ruby-1.9.2-head/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `block in load_dependency'
    from /home/mark/.rvm/gems/ruby-1.9.2-head/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:640:in`new_constants_in'
    from /home/mark/.rvm/gems/ruby-1.9.2-head/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `load_dependency'
    from /home/mark/.rvm/gems/ruby-1.9.2-head/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in`require'

**Comment by MarioRicalde** [comment]
This should be relevant to you:

https://gist.github.com/1184843

This works with Rails 3.1

```
gem 'compass', '~> 0.12.alpha'
```

**Comment by yhslai** [comment]
Same problem.

**Comment by kjf** [comment]
Same issue here with rails 3.1.1 in production.

``` ruby
group :assets do
  gem 'sass-rails', ' ~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'compass', '~> 0.12.alpha'
end
```

**Comment by scottdavis** [comment]
whats the status on this?

**Comment by iamademar** [comment]
Any updates on this one?

**Comment by iamademar** [comment]
Here's a fix, on your application.rb:

```
# if you prefer `.sass` over `.scss`.
# config.sass.preferred_syntax = :sass
config.generators.stylesheet_engine = :sass
```

**Comment by ntreadway** [comment]
Moving gem 'sass-rails' out of the :asset group resolves this issue.
