### ISSUE TITLE
use external project

### ISSUE THREAD

**Issue by aurelien-baudet** [Compass/compass#587]
Hi,

I have 2 projects:

<ul>
<li>the first is a library of widgets that also contains a compass project . In this compass project, there are many variables that I can override. I also use sprites for the images</li>
<li>the second is a project that uses this library. I want to have my own compass project and import the compass project described above with specific variable values (override)</li>
</ul>

<br/>

Here is the folder tree:

<ul><li>root<ul><li>im<ul><li>compass<ul><li>images</li><li>src<ul><li>im.scss</li></ul></li></ul></li></ul></li><li>xmpp<ul><li>compass<ul><li>images<ul><li>orange<ul><li>avatar_40x40.png</li></ul></li></ul></li><li>src<ul><li>orange<ul><li>orange.scss</li></ul></li></ul></li></ul></li></ul></li></li></ul>

<br/>

I have tried:

<ul>
  <li>add in the command line the path to the xmpp library: compass watch -c watch.rb --force src/*.scss ../../xmpp/compass/src/orange/orange.scss<ul><li>The command line displays the error: You must compile individual stylesheets from the project directory.</li></ul></li>
  <li>use the add_import_path directive in configuration file<ul><li>It fails with error: Errno::ENOENT on line ["30"] of D: No such file or directory - root/im/compass/images/orange/avatar_40x40.png<br/>it's normal because this image is not in im project but in xmpp project</li></ul></li>
<li>in the file im.scss, I have added: @import "../../../xmpp/compass/src/orange/orange.scss";<ul><li>It fails with error: Errno::ENOENT on line ["30"] of D: No such file or directory - root/im/compass/images/orange/avatar_40x40.png<br/>it's normal because this image is not in im project but in xmpp project</li></ul></li>
</ul>

<br />

Is there any way to do what I want ?
Have I to transform xmpp compass project into extension ?

Thanks for help

**Comment by MarioRicalde** [comment]
I suggest you look into the [Configuration Reference](http://compass-style.org/help/tutorials/configuration-reference/). 

What you want to do can be done. You just need to run compass watch in the "first project" and make it include the other files.

You can see I do it [Here](https://github.com/kuroir/Survival-Kit/tree/master/src/stylesheets).

**Comment by aurelien-baudet** [comment]
I don't understand, you have only ONE compass project with only ONE src folder.

In my case, the project 'im' depends on the project 'xmpp'. Moreover, I want to override some variables (of 'xmpp' project) before importing/using it. So I can't generate xmpp css file and import the generated css because variables won't have the override.

**Comment by MarioRicalde** [comment]
What I'm saying is that you're thinking it wrong. Split your secondary project into different importable files. And reuse them across both projects...

**Comment by aurelien-baudet** [comment]
I found the problem: when using sprites accross projects, the sprite utility is looking for images in the folder where the compass watch is launched even if the sprite import is done in the other compass project.

I have made an example:
There are 2 projects 'a' and 'b'. 'b' contains images and the sprite information. 'a' imports 'b'.
I launch compass watch -c config.rb in 'a' folder.

If there are no sprites at all => it works well.
If there are sprite declaration in' b' and images ONLY in 'b' => it fails (see http://www.2shared.com/file/HF4vDuph/failure.html)
If there are sprite declaration in 'b' and images moved or duplicated in 'a' => it works (see http://www.2shared.com/file/UsIi6cCU/working.html)

How can I manage this problem ?

**Comment by scottdavis** [comment]
This is actually a documentation issue (I made a new ticket) for sprites you need to get the `sprite_load_path` to an array of search paths that may contain sprites ex:

In your compass.rb

<pre>
sprite_search_path = ['somepath/files', 'myotherpath/files']
</pre>

**Comment by aurelien-baudet** [comment]
Thanks for the reply.

I have tried it but doesn't seem to work. I have tried with relative paths and also with absolute paths.

I use compass version 0.11.5. Is a version problem ?

**Comment by scottdavis** [comment]
Yes importer paths are in the 0.12 beta

**Comment by aurelien-baudet** [comment]
I have installed the pre version using gem and it has installed the version 0.12.alpha.0. With this version, it doesn't work. How can I install the beta version or when will it be available through gem install ?

**Comment by scottdavis** [comment]
I know it should work with alpha because I'm using it it production post your configuration please

**Comment by aurelien-baudet** [comment]
Thanks for help, I have zipped all files so you can try it by launching OWI/im/compass/watch.bat

http://www.2shared.com/file/X_bUXzfC/owi.html

**Comment by scottdavis** [comment]
oh your using windows this could possibly be a bug ill check it out

**Comment by nealstammers** [comment]
Hi Scott, did you ever get to the bottom of this? I'm also on a Windows box trying to use absolute paths for the sprite_load_path array.

The error message includes the absolute directory in the 'Your current load paths are: N:\path' but doesn't seem to see the folder containing the sprites.

Thanks in advance, Neal.

**Comment by scottdavis** [comment]
Yes try the current master branch

**Comment by sashasklar** [comment]
Hi Scott, I'm having issues getting this to work as well, and I was wondering if there was a working example posted that we could use as a reference. I can post an example configuration if needed, here's some details about my environment:
- I'm developing locally on a Mac (OS X 10.7.5)
- It's a static project, non-Rails. I'm using Scout 0.7.0 which uses compass 0.12.2 and sass 3.2.1
- The issue is the same as @nealstammers above, load paths seem to be set but it can't find the images.

Here's my config.rb, I've also tried absolute paths:
sass_dir = "sass"
add_import_path "../../common/sass"
http_path = "/"
css_dir = "css"
images_dir = "img"
http_generated_images_path = "/apps/global-nav/img"
sprite_load_path = ["img", "../../common/img"]

**Comment by scottdavis** [comment]
try upgrading compass to the current master branch sprite_load_path matured between 0.12 and 0.13
