### ISSUE TITLE
[Rails 3.1] Sprites in shouldn't generate combined sprite images in app/assets/images

### ISSUE THREAD

**Issue by avocade** [Compass/compass#589]
Only be generated when running rake assets:precompile. Should be generated/rendered on the fly when running in development. 

Might be too expensive to run on every reload, though, lot more work to do than compiling coffee/sass. So this is more of a convenience issue. It's just a bit weird getting the final uistuff-digest1-digest2.png filenames in the final precompiled output.

**Comment by scottdavis** [comment]
I donno if this is really the best option since regenerating them each time and serving this is going to be very costly and you will be waiting awhile especially if you have multiple sprites. I think this would severely hinder development time

**Comment by avocade** [comment]
You're probably right if one has lots of sprites. Just wanted to get the idea out there. 

Not a huge problem, as I said more of a convenience/niceness issue. I'll close the ticket.
