### ISSUE TITLE
transition missing -ms- prefix

### ISSUE THREAD

**Issue by paulirish** [Compass/compass#590]
MSFT has committed to transitions in IE10 but they havent shipped yet.

So we don't know whether they will be prefixed or not.

Currently anyone using compass will not having working transitions in IE10 if it ships with a prefix.
Of course the beta cycle is long so there's that.

But there are some projects that SHIP AND SIT and nobody recompiles their sheets after a compass upgrade that would address this.

**Comment by paulirish** [comment]
mostly this is a policy issue.

**Comment by scottdavis** [comment]
did we fix this i can't remember?

**Comment by paulirish** [comment]
unfixed. this could just wait a little bit until the next platform preview which may have transitions. then we can add the prefix or leave it out.
so.. right now.. open as a tracking issue.

**Comment by paulirish** [comment]
They shipped transition with a prefix. http://blogs.msdn.com/b/ie/archive/2011/11/21/adding-personality-with-css3-transitions-and-animations.aspx

this need to be added.

**Comment by scottdavis** [comment]
Thanks paul I'll get this in soon

**Comment by scottdavis** [comment]
@paulirish take a look at that commit and make sure that covers it if it does close the issue thanks for reporting on this!

**Comment by paulirish** [comment]
lookin sharp! thx scott! :)
