### ISSUE TITLE
Global control over vertical-offset of Sprite Images

### ISSUE THREAD

**Issue by Rocketpilot** [Compass/compass#592]
One of my most frequently used design patterns is to apply a small icon background-image to the left padding-space of headings, like so: http://cl.ly/1f293A2Z0y2h2V1z0B1h

To make the image sit on the text's baseline I generally adjust the y-position of the background image. 

In using Compass's spriting features, I've noticed that the default positioning of the background image is for the y-position to be fixed to the top of the heading's box. I've discovered there are ways to create a y-offset to alter this, but ideally a simple config variable could be used to give a global y-offset so I don't have to set the offset manually for every different heading icon I apply.

Scott Davis supplied me with a useful workaround to solve the issue here https://gist.github.com/1269229, but I do think a config variable would be useful for the less programmatically inclined Compass users (I'm more of a dabbler than anything else!)

**Comment by dip00dip** [comment]
Vote +1 for this.

**Comment by patrickkettner** [comment]
I would love to see something like this, its bit me a couple times. Is there any chance a config option will make its way in?

**Comment by patrickkettner** [comment]
Sorry to spam up the issues, but I had a hard time finding out how to add this vertical offset to sprites with magic selectors, so I thought I would add it here.

I had this folder structure 

```
-folder
  |— image
  |— image_active
  |— image_checked
```

and this sass

``` scss
 .checkbox {
  @include folder-sprite(image);
 }
```

and I replaced it with this

``` scss
 .checkbox {
  @include folder-sprite(image, false, 0, 3px);
 }
```

to make the sprite be 3px lower than it was previously.
