### ISSUE TITLE
how to make sprite png works with ie6

### ISSUE THREAD

**Issue by doabit** [Compass/compass#596]
I found the sprite creates image with 256bit.it can not work with ie6,is there a way to create png with indexed mode?

**Comment by scottdavis** [comment]
set the `chunky_png_options` in your config file here is a link to the available options https://github.com/wvanbergen/chunky_png/wiki/Constraints

**Comment by doabit** [comment]
Thank you,i have set 

```
chunky_png_options={:color_mode => ChunkyPNG::COLOR_INDEXED,:compression => Zlib::BEST_COMPRESSION}
```

in config/compass.rb and got error

```
can't convert nil into Integer
(in /Users/doabit/Practice/rails3.1/sprite/app/assets/stylesheets/posts.css.scss)
```

**Comment by scottdavis** [comment]
Im getting this error also:

<pre>
TypeError on line ["157"] of /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/chunky_png-1.2.5/lib/chunky_png/canvas/png_encoding.rb: can't convert nil into Integer
Run with --trace to see the full backtrace
</pre>


This may be a chunky_png bug or a configuration issue lets ping @wvanbergen

**Comment by doabit** [comment]
Thanks,i will.

**Comment by wvanbergen** [comment]
Can you get me the full stack trace by running the rake task with --trace?

**Comment by scottdavis** [comment]
<pre>TypeError on line ["157"] of /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/chunky_png-1.2.5/lib/chunky_png/canvas/png_encoding.rb: can't convert nil into Integer
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/chunky_png-1.2.5/lib/chunky_png/canvas/png_encoding.rb:157:in `encode_png_pixelstream'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/chunky_png-1.2.5/lib/chunky_png/canvas/png_encoding.rb:85:in `to_datastream'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/chunky_png-1.2.5/lib/chunky_png/image.rb:62:in `to_datastream'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/chunky_png-1.2.5/lib/chunky_png/canvas/png_encoding.rb:35:in `write'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/chunky_png-1.2.5/lib/chunky_png/canvas/png_encoding.rb:43:in `block in save'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/chunky_png-1.2.5/lib/chunky_png/canvas/png_encoding.rb:43:in `open'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/chunky_png-1.2.5/lib/chunky_png/canvas/png_encoding.rb:43:in `save'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/sass_extensions/sprites/engines/chunky_png_engine.rb:37:in `save'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/sass_extensions/sprites/sprite_methods.rb:103:in `save!'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/sass_extensions/sprites/sprite_methods.rb:70:in `generate'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/sass_extensions/functions/sprites.rb:98:in `sprite_url'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/sass_extensions/sprites/sprite_map.rb:51:in `method_missing'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/sass_extensions/sprites/sprite_map.rb:42:in `to_s'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/script/list.rb:44:in `block in to_s'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/script/list.rb:44:in `map'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/script/list.rb:44:in `to_s'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:215:in `visit_prop'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/base.rb:37:in `visit'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:18:in `visit'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/base.rb:53:in `map'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/base.rb:53:in `visit_children'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:27:in `block in visit_children'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:39:in `with_environment'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:26:in `visit_children'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/base.rb:37:in `block in visit'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:234:in `visit_rule'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/base.rb:37:in `visit'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:18:in `visit'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:144:in `block in visit_import'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:144:in `map'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:144:in `visit_import'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/base.rb:37:in `visit'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:18:in `visit'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/base.rb:53:in `map'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/base.rb:53:in `visit_children'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:27:in `block in visit_children'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:39:in `with_environment'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:26:in `visit_children'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/base.rb:37:in `block in visit'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:47:in `visit_root'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/base.rb:37:in `visit'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:18:in `visit'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:7:in `visit'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/root_node.rb:20:in `render'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/engine.rb:300:in `_render'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/engine.rb:247:in `render'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/compiler.rb:136:in `block (2 levels) in compile'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/compiler.rb:122:in `timed'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/compiler.rb:135:in `block in compile'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/logger.rb:45:in `red'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/compiler.rb:134:in `compile'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/compiler.rb:114:in `compile_if_required'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/compiler.rb:99:in `block (2 levels) in run'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/compiler.rb:97:in `each'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/compiler.rb:97:in `block in run'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/compiler.rb:122:in `timed'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/compiler.rb:96:in `run'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/commands/update_project.rb:37:in `perform'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/commands/base.rb:18:in `execute'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/commands/project_base.rb:19:in `execute'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  ../compass/bin/compass:25:in `block in <main>'
  ../compass/bin/compass:39:in `call'
  ../compass/bin/compass:39:in `<main>'TypeError on line ["157"] of /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/chunky_png-1.2.5/lib/chunky_png/canvas/png_encoding.rb: can't convert nil into Integer
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/chunky_png-1.2.5/lib/chunky_png/canvas/png_encoding.rb:157:in `encode_png_pixelstream'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/chunky_png-1.2.5/lib/chunky_png/canvas/png_encoding.rb:85:in `to_datastream'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/chunky_png-1.2.5/lib/chunky_png/image.rb:62:in `to_datastream'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/chunky_png-1.2.5/lib/chunky_png/canvas/png_encoding.rb:35:in `write'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/chunky_png-1.2.5/lib/chunky_png/canvas/png_encoding.rb:43:in `block in save'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/chunky_png-1.2.5/lib/chunky_png/canvas/png_encoding.rb:43:in `open'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/chunky_png-1.2.5/lib/chunky_png/canvas/png_encoding.rb:43:in `save'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/sass_extensions/sprites/engines/chunky_png_engine.rb:37:in `save'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/sass_extensions/sprites/sprite_methods.rb:103:in `save!'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/sass_extensions/sprites/sprite_methods.rb:70:in `generate'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/sass_extensions/functions/sprites.rb:98:in `sprite_url'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/sass_extensions/sprites/sprite_map.rb:51:in `method_missing'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/sass_extensions/sprites/sprite_map.rb:42:in `to_s'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/script/list.rb:44:in `block in to_s'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/script/list.rb:44:in `map'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/script/list.rb:44:in `to_s'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:215:in `visit_prop'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/base.rb:37:in `visit'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:18:in `visit'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/base.rb:53:in `map'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/base.rb:53:in `visit_children'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:27:in `block in visit_children'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:39:in `with_environment'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:26:in `visit_children'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/base.rb:37:in `block in visit'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:234:in `visit_rule'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/base.rb:37:in `visit'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:18:in `visit'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:144:in `block in visit_import'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:144:in `map'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:144:in `visit_import'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/base.rb:37:in `visit'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:18:in `visit'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/base.rb:53:in `map'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/base.rb:53:in `visit_children'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:27:in `block in visit_children'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:39:in `with_environment'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:26:in `visit_children'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/base.rb:37:in `block in visit'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:47:in `visit_root'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/base.rb:37:in `visit'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:18:in `visit'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/visitors/perform.rb:7:in `visit'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/tree/root_node.rb:20:in `render'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/engine.rb:300:in `_render'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.10/lib/sass/engine.rb:247:in `render'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/compiler.rb:136:in `block (2 levels) in compile'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/compiler.rb:122:in `timed'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/compiler.rb:135:in `block in compile'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/logger.rb:45:in `red'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/compiler.rb:134:in `compile'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/compiler.rb:114:in `compile_if_required'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/compiler.rb:99:in `block (2 levels) in run'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/compiler.rb:97:in `each'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/compiler.rb:97:in `block in run'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/compiler.rb:122:in `timed'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/compiler.rb:96:in `run'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/commands/update_project.rb:37:in `perform'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/commands/base.rb:18:in `execute'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/commands/project_base.rb:19:in `execute'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /Users/sdavis/.rvm/gems/ruby-1.9.3-rc1/gems/compass-0.11.5/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  ../compass/bin/compass:25:in `block in <main>'
  ../compass/bin/compass:39:in `call'
  ../compass/bin/compass:39:in `<main>'
</pre>

**Comment by wvanbergen** [comment]
Do you have the same error with different ruby versions?
I can't actually look to this during the next two weeks, as I am on vacation. The more information you can give me before then, the better :)

**Comment by doabit** [comment]
I tried 1.9.2-p180 and got same error .

**Comment by wvanbergen** [comment]
Final question: are you sure you are not using more than 256 colors?

**Comment by doabit** [comment]
I'm sorry, my mistake,i modified all images to 8bit and indexed mode,now it works well.

-----------update--------

Now,if i have one image with rgb mode,it will got the error.Do i must modify all image to 8bit and indexed mode??

**Comment by doabit** [comment]
I still get same error if i set :color_mode => ChunkyPNG::COLOR_INDEXED, all images modified to 8bit and indexed mode.

Update----

I got error like 

```
This palette has too many colors!
```

I wil modify all images again.

**Comment by wvanbergen** [comment]
The images may use different colors, so the total number of colors of the combined image may still exceed 256. 

ChunkyPNG will automatically use indexed colors if possible.

**Comment by doabit** [comment]
Thanks,i also think so,is there a way to make it work? I have modified all images to 8bit and indexed mode with fireworks.

**Comment by wvanbergen** [comment]
You must reduce the number of colors you are using to 256 if you want to use indexed colors. ChunkyPNG doesn't come with something to reduce the number of colors, so you have to preprocess your input images to all use the same palette of 256 colors. You can do this in Photoshop.

**Comment by doabit** [comment]
Thanks,i have switch to use rbg mode and use pie to set png works in ie6. Thank you very much.
