### ISSUE TITLE
remove khtml prefix

### ISSUE THREAD

**Issue by paulirish** [Compass/compass#598]
I have not found a legit use of the khtml prefix ever.

I think we could drop it. :)

**Comment by scottdavis** [comment]
never user Konqueror?

**Comment by paulirish** [comment]
me? no. I don't know anyone that has either. Do you test your sites in Konqueror? I'd wager that nobody uses compass does.

Regardless of whether we test are two issues..

1) does konqueror use any khtml prefixes (now or recently) and on what properties?
2) if konqueror is actively using khtml vendor prefixes, does their market share warrant support?

on 1) http://www.konqueror.org/css/ indicates `box-sizing` is the only worthwhile property that could use a kthml prefix. I just asked in #khtml and they don't know anything beyond this page either.

on 2) the only stats I have seen regarding Konqueror (and the other linux variety's browser shares) put them at _under 3% of Linux users_, cumulatively.

**Comment by paulirish** [comment]
http://gitorious.org/dbusmenu/kdelibs/blobs/master/khtml/css/cssproperties.c#line703 if anyone wanted to know konqueror's support of css props

**Comment by scottdavis** [comment]
how about we just turn it off by default? https://github.com/chriseppstein/compass/blob/master/frameworks/compass/stylesheets/compass/_support.scss

**Comment by paulirish** [comment]
works for me

**Comment by scottdavis** [comment]
ping: @chriseppstein

**Comment by chriseppstein** [comment]
+1

**Comment by scottdavis** [comment]
I say we remove it if its no longer a valid prefix

**Comment by dangayle** [comment]
I just put in a tutorial on how to turn -khtml and -o prefixes off, so +1

**Comment by chriseppstein** [comment]
I'd like `-o` to stay on by default.

**Comment by scottdavis** [comment]
yes i agree `-o` on by default lots of mobile browsers are opera

**Comment by MarioRicalde** [comment]
+1 to this (passes out)

**Comment by soffes** [comment]
+1 `-khtml` off be default

**Comment by chriseppstein** [comment]
seems like we can just remove `-khtml` altogether. billions of bytes xferred will be saved.

**Comment by scottdavis** [comment]
<img src="http://i372.photobucket.com/albums/oo166/agtman/nuke-it-from-orbit.jpg" border="0">

**Comment by alanhogan** [comment]
Is that… Andromeda Strain?

I think `-o` on and `-khtml` off by default would be a very _gut_ option.

Konquerer is not commonly tested, in my experience, and never shows up on marketshare reports. Opera, however…

**Comment by soffes** [comment]
Personally, I would turn off `-o` as well. I don't know anyone that uses it.

**Comment by yatil** [comment]
+1 for getting rid of -khtml-
-1 for getting rid of -o-

**Comment by paulirish** [comment]
Opera's prefix presence is out of the scope of this ticket. If you would like to be the **jerk** that files a ticket proposing removing Opera support, feel free...... **jerk**

:)

**Comment by chriseppstein** [comment]
@samsoffes a very scientific approach. I asked around my office and no one here uses it either!

**Comment by scottdavis** [comment]
+1 for jerks

**Comment by soffes** [comment]
@chriseppstein I mean I know it has a very small market share, but I have never met anyone that uses it. I figure we're the kind of people that would know people that use it being engineers and all.

I checked for [my blog](http://samsoff.es) it has 0.41%. [At work](http://hipstamaticapp.com) it has 0.92%. So some people are using it, but personally, I don't care about those users :)

**Comment by scottdavis** [comment]
opera is the fat kid in gym class lets now pick on him ok!

**Comment by alanhogan** [comment]
Let’s not be cruel.

Opera has (had?) some very unique and compelling UI innovations (Quick Dial, for example, was pioneering; and Fast Forward). 

It is also _the_ viable browser on feature phones.

It’s also the only Proprietary But Good Browser not maintained by MSFT, and generally very standards-compliant.

**Comment by scottdavis** [comment]
ok so removing khtml all together and leaving opera seems to be the consensus

**Comment by rwz** [comment]
+1 for `-khtml` off by default

**Comment by kristerkari** [comment]
-khtml is not needed, but please keep -o on by default

**Comment by ZeeAgency** [comment]
+1, -khtml off by default but keep -o

**Comment by MarioRicalde** [comment]
I agree: `-o` by default is a good call and like @paulirish said it's not the reach of this ticket so we shouldn't even be talking about it.

@chriseppstein Think also about the tons of CO₂ we'll be saving the world from.

![](http://www.greenpeace.org/eastasia/Global/eastasia/planet-2/External/image/2004/9/cover-of-the-book-greenpeace.jpg)

**Comment by jonassmedegaard** [comment]
it is _decrease_ in bytes :-P

Thanks for the change - I fully agree.

**Comment by scottdavis** [comment]
increase in free bytes!
