### ISSUE TITLE
Blueprint Fancy-Type Syntax Error

### ISSUE THREAD

**Issue by acroterra** [Compass/compass#60]
=dquo(!offset = 0.5em)
  margin-left: -!offset

margin-left: -!offset should be margin-left= -!offset or margin-left: #{-!offset}

**Comment by chriseppstein** [comment]
Thanks. I'll get that into the next release.

**Comment by chriseppstein** [comment]
[Blueprint] Bug Fix: variable referenced in a non-script context within
the dquo mixin in the fancy_type module. Closed by 5f32043c29062abba261d5b38d8ac66ec277a186.
