### ISSUE TITLE
Sprites by names false or true

### ISSUE THREAD

**Issue by jacmoe** [Compass/compass#602]
I discovered that you can't sprite pngs with the names 'false.png' or 'true.png' - that's probably a bug?

It took me only an hour to discover. :P

Compass kept telling me this:
    error sass/style.sass (Line 58: The second argument to sprite() must be a sprite name.

It works great - both command line compass sprite command and the magical include - but it fails when I use the all sprites mixin.
I guess that false and true is not escaped properly in the mixin?
Pretty new to all of this, so just a wild guess.
I'll just avoid using those names for now. :)

**Comment by chriseppstein** [comment]
I guess we should make these names strings instead of identifiers.

**Comment by scottdavis** [comment]
i can fix this just like i fixed colors so shouldn't be a problem
