### ISSUE TITLE
Box-Shadow not working with compass 0.12.alpha.0

### ISSUE THREAD

**Issue by scottmessinger** [Compass/compass#604]
The following code

``` css
@import "compass/utilities/sprites"
@import "compass/css3/images"
@import "compass/css3/text-shadow"
@import "compass/css3/box-shadow"
@import "compass/css3/opacity"
.left_arrow
  @include single-box-shadow(red 2px 2px 10px )
```

produces the following bug:

``` shell
Syntax error: Mixin box-shadow is missing parameter $blur. 
on line 91 of /Users/ScottMessinger/.rvm/gems/ruby-1.9.2-p180-patched@rails31/gems/compass-0.12.alpha.0/frameworks/compass/stylesheets/compass/css3/_box-shadow.scss, in `box-shadow' 
from line 91 of /Users/ScottMessinger/.rvm/gems/ruby-1.9.2-p180-patched@rails31/gems/compass-0.12.alpha.0/frameworks/compass/stylesheets/compass/css3/_box-shadow.scss, in `single-box-shadow' 
from line 750 of /Users/ScottMessinger/code/hlavka/app/assets/stylesheets/useful.sass
```

I'm using Rails 3.1.1

In my gem file:

```
  gem 'rails', '~> 3.1.0'
  gem 'sass', '~> 3.1.10'
  gem 'sass-rails', "~> 3.1.4"
  gem 'compass', "0.12.alpha.0"
```

Any ideas why this would be?

Thanks in advance!

**Comment by scottdavis** [comment]
possibly because you are missing the comma's `single-box-shadow($color, $hoff, $voff, $blur, $spread, $inset)` the single-box-shadow mixin was set to be deprecated anyway i believe

http://compass-style.org/reference/compass/css3/box_shadow/

**Comment by scottmessinger** [comment]
Hi Scott! Thanks for the response. I get the same error with or without the commas. This problem seems to effect gems like fancy-buttons, as I get the same error message.

What method should I use if single-box-shadow is set to be deprecated?

**Comment by scottdavis** [comment]
which version of fancy-buttons?

**Comment by scottdavis** [comment]
ping @imathis

**Comment by scottmessinger** [comment]
@imathis using the fancy-buttons gem isn't working, I get "File not found or unreadable: fancy-buttons" error. But that's a separate matter. When I copy the fancy-button sass files into my project directory and import them, I get the error about missing the blur param. Any ideas what's going on?

**Comment by scottmessinger** [comment]
It's version 1.1.2 of fancy-buttons.

**Comment by scottdavis** [comment]
aginst the latest master using the code you posted im compiling fine

<pre>

.left_arrow {
  -moz-box-shadow: 0px 0px 5px red 2px 2px 10px;
  -webkit-box-shadow: 0px 0px 5px red 2px 2px 10px;
  -o-box-shadow: 0px 0px 5px red 2px 2px 10px;
  box-shadow: 0px 0px 5px red 2px 2px 10px;
}
</pre>

**Comment by scottmessinger** [comment]
It's super weird. I think it has to be some weird conflict with one of my gems or something....I'll keep looking into it.

**Comment by scottmessinger** [comment]
I figured out the problem. Before compass started using PIE, I had created a box_shadow mixin using PIE called "box_shadow" That was conflicting with compass (though I thought compass used 'box-shadow' with a dash). Thanks for the looking into the issue. Knowing that it wasn't the framework helped me pinpoint where the problem was coming from.
