### ISSUE TITLE
Syntax error: Undefined mixin 'adjust-font-size-to'

### ISSUE THREAD

**Issue by brandon-rhodes** [Compass/compass#605]
I just pulled a project off the shelf, ran its install script which in turn ran "gem install -i Gem compass" and "gem install -i Gem compass-susy-plugin", and then tried recompiling my project's CSS. I got the error:

```
Syntax error: Undefined mixin 'adjust-font-size-to'
```

But the source file compass-0.11.5/frameworks/compass/stylesheets/compass/typography/_vertical_rhythm.scss in my Gem directory still seems to define this mixin. An aside: when I tried to fix the situation by explicitly including the file, I not only found no @import line that would make the mixin start working:

```
/* none of these help*/
@import "compass/typography/vertical_rhythm";
@import "compass/typography/_vertical_rhythm";
@import "vertical_rhythm";
```

But I also found that none of the above @import statements give error messages! This is a bit troubling — I can have a bad filename in an @import statement, and Sass will not complain to let me know? That could make it hard to diagnose misspellings that result in missing mixins etcetera.

**Comment by brandon-rhodes** [comment]
And I keep seeing mailing list messages trumpeting syntax like:

```
@import susy
```

but I always have to put double quotes around it or I get:

```
error src/screen.scss (Line 4: Invalid CSS after "@import ": expected uri, was "susy")
```

Am I running into a difference between Sass and Scss, or something else?

**Comment by barraponto** [comment]
See http://sass-lang.com/docs/yardoc/file.INDENTED_SYNTAX.html#id25

**Comment by brandon-rhodes** [comment]
barraponto — ah, so the mailing list messages were for people writing Sass rather than Scss? Fair enough. Now I am just confused about my initial two issues: (a) why imports of non-existent files result in no error messages, and (b) why a crucial directive that I need to compile my web site's Scss seems to be missing or deactivated in the most recent Compass version.

**Comment by scottdavis** [comment]
`gem install -i Gem compass` is wrong i think you just need to run `gem install compass` makesure after running this you can run `compass version`  im thinking compass isn't actually installed. what command are you using to compile the stylesheets?

**Comment by scottdavis** [comment]
closing this for now unless this is still an issue repoen it

**Comment by brandon-rhodes** [comment]
The problem seems to have been that I was installing Compass _then_ installing Susy, which did not give Susy the chance to demand exactly the version of Compass that it is compatible with. So now I just install Susy and, it turns out, it brings along the correct Compass version as a dependency as part of its install. So everything seems to be working for me — thanks!
