### ISSUE TITLE
unable to compile sass

### ISSUE THREAD

**Issue by madhums** [Compass/compass#606]
First of all, thanks for the awesome plugin!! 

Its a weird problem, I am using compass with rails. Its not able to compile sass files.

I can see nothing in the logs, there is only this [stacktrace](https://gist.github.com/1310287) in the compiled css file. It gets a SIGTERM signal exception which doesn't kill the process and the CPU usage goes to 95% ! 

Then I tried running the command line tool with `--trace` and could get this [stacktrace](https://gist.github.com/1310214). Its not able to compile sass files when they are changed.

The version of compass I am using is 0.11.5 (also tried with 0.11.4). I was not able to test it with a different version of chunky_png as the dependency restricts it to use with chunky_png v1.2.0.

Its related to chunky_png too, but I don't know whether this is a problem with compass or chunky_png.

If it helps I am using ruby v ree 1.8.7 also tried with mri 1.8.7

Appreciate your help.

**Comment by madhums** [comment]
Ok, I updated to chunky_png 1.2.5 using bundle update and that fixed the issue. Probably some bug with chunky_png v1.2.0.

**Comment by madhums** [comment]
This is really weird, it worked only for once, when I updated the gem. Just logged out and logged back in and its happening again!

**Comment by scottdavis** [comment]
what version of ruby and what platform?

**Comment by madhums** [comment]
Ruby version - ree-1.8.7-2011.02 [ x86_64 ]
Platform - ubuntu 11.10

I updated chunky_png to 1.2.5 and removed v1.2.0 - that fixed the above issue, but now I am getting this error in one of the css files. `Errno::ENOENT: No such file or directory - getcwd`. Full [stacktrace](https://raw.github.com/gist/1310214/2460e14b9d3369a5da3ac636b99a304da8b4dd99/getcwd_error)

**Comment by scottdavis** [comment]
also forgot to ask which version of rails

**Comment by madhums** [comment]
2.3.11 

No issues in rails 3.

**Comment by scottdavis** [comment]
chris just pushed a patch the other day for rails 2.3.x mind trying the master?

**Comment by madhums** [comment]
sure, give me sometime

**Comment by chriseppstein** [comment]
@madhums any update?
