### ISSUE TITLE
Allow cache-busting params to be added to CSS output files

### ISSUE THREAD

**Issue by jpcody** [Compass/compass#608]
Perhaps this is already available, but it seems it'd be valuable to extend the asset_cache_buster for images to the compiled CSS files Compass/SASS creates. This would look like simply outputting to path_to_compile_to.css?timestamp.

It makes sense to me to provide an option to do this on the Compass end because Compass is acutely aware of when CSS changes, thus, the cache needs to be busted. Additionally, a Compass project could be as simple as a standalone HTML site to a full-blown Rails app that'd have this functionality pre-baked.

And hey, maybe it's a terrible idea, but I wanted to bring it up. If it sounds like a good idea, I'd be happy to try my hand and submit a pull request, but you might have some code to rewrite :)

**Comment by chriseppstein** [comment]
it's not the filename that forces caches to invalidate. It's the link to them. Compass doesn't own that part so we can't provide this feature. If you use rails with compass, it does this for you -- other frameworks might as well.

**Comment by scottdavis** [comment]
using `path_to_compile_to.css?timestamp` is a bad idea since it will not be picked up my reverse proxy caches you should instead put the hash in the filename when you push to production ex: `myfile-38q56q0865.css`
