### ISSUE TITLE
Sass SyntaxError: Undefined Variable... but it still works fine

### ISSUE THREAD

**Issue by gpbmike** [Compass/compass#61]
This is just more of an annoyance since it works anyway. 

```
overwrite media/vine/css/skin_black.css
Sass::SyntaxError on line 7 of /Users/gpbmike/vines/sass/././_default.sass: Undefined variable: "!primary_copy_color".
```

I'm pretty sure it has to do with the way I'm importing files.

**skin_black.sass**: defines color variables, imports _base.sass_ at the end

**base.sass**: imports a bunch of things, including _default.sass_

**default.sass**: uses _!primary_copy_color_ variable

I can change _!primary_copy_color_ in _skin_black.sass_ and it shows up fine in _skin_black.css_, so I probably shouldn't be getting the error.

I don't get the error if I use `sass` to compile instead of `compass -w`.

**Comment by chriseppstein** [comment]
Can you post the relevant bits of the files to a gist and link it here, from this description I can't diagnose the issue.

**Comment by gpbmike** [comment]
You got it! http://gist.github.com/247826

**Comment by chriseppstein** [comment]
I had to move the comment, but once I did that I get the following:

```
$ compass
   exists stylesheets
  compile src/skin_black.sass
   create stylesheets/skin_black.css

$ compass -v
Compass 0.10.0 [2465bab]
Copyright (c) 2008-2009 Chris Eppstein
Released under the MIT License.
```

As you can see, it works fine. Perhaps you can tell me more about your environment? Are you using compass stand alone or with another framework?

**Comment by gpbmike** [comment]
I'm going to see if I can reproduce it without my crazy huge files.

**Comment by gpbmike** [comment]
Chris, I found the problem. For some reason I had a _vine.sass and a vine.sass that were identical. They were both importing _default.sass so when I saw the error I didn't realize it was being generated from vine.sass. I removed vine.sass and everything is right in the world again.

Sorry to bug you!

**Comment by chriseppstein** [comment]
glad you got it sorted out.
