### ISSUE TITLE
http_images_path not working in 0.12.alpha.0?

### ISSUE THREAD

**Issue by benjohnson** [Compass/compass#618]
Hi there,

I'm attempting to get 0.12.alpha.0 working with a standalone install of sprockets. Almost everything works with help from  sprockets-sass and sprockets-helpers, but I think I'm seeing a bug where http_images_path just doesn't work in 0.12.alpha.0.

Can anyone confirm that it's not just me? Is this intentional?

Thanks.

**Comment by benjohnson** [comment]
From the changelog:

Added a new set of configuration properties for generated images. generated_images_dir, generated_images_path, http_generated_images_dir, and http_generated_images_path can now be set to control where generated images are written and how they are served. Added a corresponding generated-image-url() helper function. These should rarely be needed and will default to your corresponding image directories and paths.

**Comment by nicolasgarnil** [comment]
Thanks ben for this... almost gone crazy... I had to add http_generated_images_dir and http_generated_images_path because compass was trying to find the sprites images in images_dir (in my case /public/images) and not in http_images_path (/images).
