### ISSUE TITLE
Where does the output of `compass watch` go?

### ISSUE THREAD

**Issue by timmolendijk** [Compass/compass#619]
I'm trying to run `compass watch` from a `Cakefile` (CoffeeScript's Node.js-based build system). When I spawn a new process (`require('child_process').spawn 'compass', ['watch']`) it will indeed watch changes and recompile them. In that sense it works. But I cannot seem to catch the process's output. Nothing comes in over `stdout`.

This problem only applies to `compass watch`, output of other commands such as `compass compile` passes `stdout` as expected.

What is so special about `compile watch` that it behaves differently, and how can I get hold of the process's output?

Why doesn't its output go through `stdout` as most people would expect?

**Comment by chriseppstein** [comment]
It outputs to stdout like all the rest of the commands. If it didn't you wouldn't see it in the terminal output. 

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by timmolendijk** [comment]
Yeah, that's what I was thinking. Node.js's spawn method doesn't seem to agree though.

It turns out to be even weirder. With `--boring` nothing comes in over stdout or stderr for sure. Without `--boring` some data seems to come in but it is incapable of making something of it. Whatever you do it prints as empty string (but some coloring seems to make it through).

_Any_ clue what's different in `watch` compared to `compile` that might be causing this difference in behavior?? Like I said when running `compile` all works perfect -- with and without `--boring`, including colors.

Also, what strikes me as odd is that any output starting with `>>>` (for example `>>> Compass is polling for changes. Press Ctrl-C to Stop.`) is nowhere to be found in either scenario. Not even with `compile`, in which case all the other output (like `unchanged sass/style.scss`) _does_ make it through. There must be a difference in how these strings are being evoked from `compass`?!?

**Comment by timmolendijk** [comment]
P.S. The same behavior exists when spawning `compass` in a plain Node.js script, so Cake(file)/CoffeeScript has nothing to do with this.

**Comment by timmolendijk** [comment]
More analysis:
- forked processes shouldn't be problematic: https://twitter.com/#!/ejpbruel/status/136636397246353408
- Node's `child_process.exec` experiences similar problems: https://twitter.com/#!/ejpbruel/status/136639257161900032

Really _really_ curious what `compass` is doing internally... Any thoughts? My Ruby skills are non-existent unfortunately.

**Comment by timmolendijk** [comment]
[Issue report over at Node.js](https://github.com/joyent/node/issues/2127)

**Comment by chriseppstein** [comment]
If you identify something that we're doing wrong. please let us know.

**Comment by timmolendijk** [comment]
Bleh, yeah I don't know. Can't make much of the source code.

**Comment by hybrist** [comment]
Not an expert on Ruby myself - but it looks like stdout isn't flushed after writing to it. And... yes. So spending the last hour learning how Ruby and Gems work weren't a total waste of time. ^^

I fixed it by adding "$stdout.flush" after almost every puts "X" in watch_project.rb. Now everything gets channeled through and I can finally have one cake file for watching Coffeescript, Handlebars and Compass. I'm too tired to fork right now - fastest hack for others who want it:
1. clone compass into some directory (let's say: ~/gems/compass)
2. patch lib/compass/commands/watch_project.rb by adding "$stdout.flush" after every puts-line you wanna see
3. "sudo gem uninstall compass"
4. run "gem build compass.gemspec" in ~/gems/compass - this will create a .gem file
5. "sudo gem install --local ./compass-X.gem"

So, @chriseppstein : I don't think flushing stdout will do much harm for normal use - so maybe you could include it in the next release? Would love to switch back to the official version ASAP.

**Comment by scottdavis** [comment]
@JKrems can you file another bug so I can get this fixed please
