### ISSUE TITLE
Ruby 1.9.1 on Windows

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#62]
Bug report is here:
http://groups.google.com/group/compass-users/browse_thread/thread/8093c2fe96d4050d?hl=en

**Comment by charlesroper** [comment]
It's working fine for me with 0.10.0.pre5:

http://gist.github.com/306558

**Comment by charlesroper** [comment]
... although it requires the latest prerelease of win32console, otherwise it explodes:

http://blog.mmediasys.com/2009/12/29/win32console-1-3-0-prerelease/

**Comment by chriseppstein** [comment]
closing.
