### ISSUE TITLE
CSS3 transitions missing -o- vendor prefix

### ISSUE THREAD

**Issue by shaun-floss** [Compass/compass#623]
The -o- prefix isn't being set for transitions. I'm using a transition like this: `@include transition(all, 2s, ease, 0);` I've tried explicitly setting: `$experimental-support-for-opera: true;` but that doesn't seem to work. Am I missing something?

**Comment by GirlBossRush** [comment]
I too am facing this issue. The problem only came up after switching from SCSS to Sass. All other usual vendor prefixes are created except Opera. Running 0.12.alpha

**Comment by nir0** [comment]
same here, didn't use scss though

**Comment by roytomeij** [comment]
I assume this is not an issue anymore? I checked against Compass 0.11.7 and the stable branch, and I get the `-o-` prefix when using `@include transition()` (without doing anything with `$experimental-support`)? If correct, this issue can be closed.

**Comment by shaun-floss** [comment]
Yes, I just verified. Indeed, the -o- prefix is being included now. Closing this issue.

**Comment by nir0** [comment]
+transition
and
@include transition()
have different behaviour, is that right??
