### ISSUE TITLE
config.sass_dir configuration is ignored

### ISSUE THREAD

**Issue by ronnqvist** [Compass/compass#624]
config.sass_dir setting according to wiki/Sinatra-Integration doesn't seem to affect anything, "views" remains the place where Sinatra looks for sass-files.

**Comment by scottdavis** [comment]
Mind making me a test app i don't work with sinatra much

**Comment by ronnqvist** [comment]
I'm referring to the example at https://github.com/chriseppstein/compass/wiki/Sinatra-Integration just try changing the sass_dir setting to something else.

**Comment by scottdavis** [comment]
the wiki is in the process of being depreciated there are more up to date examples on the compass website: http://compass-style.org/help/tutorials/integration/ that being said it looks to be the same. I know none of the core team use Sinatra often and we got that example from a user you may have to experiment. It looks like that is using the sass rack app and passing the compass options along? alternitivy you cna use compass command line and use `compass watch` (which is what i would do even in rails)
