### ISSUE TITLE
Remove -ms-box-sizing

### ISSUE THREAD

**Issue by necolas** [Compass/compass#627]
IE8+ implemented `box-sizing` without prefix, so it serves no purpose.

https://github.com/chriseppstein/compass/blob/stable/frameworks/compass/stylesheets/compass/css3/_box-sizing.scss

**Comment by paulirish** [comment]
:+1:

**Comment by paulirish** [comment]
also compass needs a policy for retiring dead prefixes too. like a moz prefix that only affects pre 3.6..

**Comment by scottdavis** [comment]
fixed: 6c98ff1d5c
