### ISSUE TITLE
Compass watch not working with scss syntax 

### ISSUE THREAD

**Issue by alexkehayias** [Compass/compass#629]
I recently tried switching to the scss syntax, but any project created using this syntax will not work with "compass watch." I thought I had messed up my setup, but when I go back to my sass syntax projects, compass watch works fine. Any new project created with sass syntax also works with compass watch. I've also tried compass watch --poll and even compass compile doesn't always work with an scss project. 

Mac OSx Lion
Compass 0.11.5 (Antares)

**Comment by leopic** [comment]
Can you post an example of the scss syntax that's not working? What does compass watch --trace outputs?

**Comment by scottdavis** [comment]
Can you post the error

**Comment by alexkehayias** [comment]
there were no errors, it just would not detect the changes. --trace does not reveal any new output. I've tried purposely adding errors and it would not catch it. I have double checked that I am watching the correct directory and have tried it with specifying a specific folder. 

Here's the .scss file that it should be detecting changes to. I tried simple little changes like adding an h2 or changing the color:
'''
@import "globals.scss";
@import "ie.scss";

@import "typography.scss";
@import "ui.scss";
@import "forms.scss";
@import "grid.scss";
@import "mobile.scss";
@import "orbit.scss";
@import "reveal.scss";

@import "compass/layout.scss";
@include sticky-footer(72px, "#layout", "#layout_footer", "#footer");

h1 {
    font-size: 54px;
    color: blue;
}
'''

**Comment by scottdavis** [comment]
Run compass config --debug from the project root

**Comment by alexkehayias** [comment]
Here's the debug. The paths look ok to me, but maybe I'm missing something. 

'''
Configuration sources:
command_line, /Users/alexkehayias/Dropbox/Private/Python/foundation/config.rb, stand_alone, implied, defaults
****\* asset_cache_buster = nil *****
default: -, -, -, -, -
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: -, -, -, -, -
****\* additional_import_paths = nil *****
default: -, -, -, -, -
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: -, -, -, -, -
****\* javascripts_dir = "javascripts" *****
default: -, -, -, -, -
value: "javascripts", "javascripts", "javascripts", -, -
raw: -, "javascripts", -, -, -
resolved: "javascripts", "javascripts", "javascripts", -, -
****\* http_images_path = "/images" *****
default: "/images", "/images", "/images", "/images", "/images"
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: "/images", "/images", "/images", "/images", "/images"
****\* css_path = "/Users/alexkehayias/Dropbox/Private/Python/foundation/stylesheets" *****
default: "/Users/alexkehayias/Dropbox/Private/Python/foundation/stylesheets", "/Users/alexkehayias/Dropbox/Private/Python/foundation/stylesheets", "/Users/alexkehayias/Dropbox/Private/Python/foundation/stylesheets", "/Users/alexkehayias/Dropbox/Private/Python/foundation/stylesheets", "/Users/alexkehayias/Dropbox/Private/Python/foundation/stylesheets"
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: "/Users/alexkehayias/Dropbox/Private/Python/foundation/stylesheets", "/Users/alexkehayias/Dropbox/Private/Python/foundation/stylesheets", "/Users/alexkehayias/Dropbox/Private/Python/foundation/stylesheets", "/Users/alexkehayias/Dropbox/Private/Python/foundation/stylesheets", "/Users/alexkehayias/Dropbox/Private/Python/foundation/stylesheets"
****\* extensions_dir = "extensions" *****
default: "extensions", "extensions", "extensions", "extensions", "extensions"
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: "extensions", "extensions", "extensions", "extensions", "extensions"
****\* preferred_syntax = :scss *****
default: :scss, :scss, :scss, :scss, :scss
value: :scss, :scss, -, -, -
raw: -, :scss, -, -, -
resolved: :scss, :scss, :scss, :scss, :scss
****\* javascripts_path = "/Users/alexkehayias/Dropbox/Private/Python/foundation/javascripts" *****
default: "/Users/alexkehayias/Dropbox/Private/Python/foundation/javascripts", "/Users/alexkehayias/Dropbox/Private/Python/foundation/javascripts", "/Users/alexkehayias/Dropbox/Private/Python/foundation/javascripts", "/Users/alexkehayias/Dropbox/Private/Python/foundation/javascripts", "/Users/alexkehayias/Dropbox/Private/Python/foundation/javascripts"
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: "/Users/alexkehayias/Dropbox/Private/Python/foundation/javascripts", "/Users/alexkehayias/Dropbox/Private/Python/foundation/javascripts", "/Users/alexkehayias/Dropbox/Private/Python/foundation/javascripts", "/Users/alexkehayias/Dropbox/Private/Python/foundation/javascripts", "/Users/alexkehayias/Dropbox/Private/Python/foundation/javascripts"
****\* images_path = "/Users/alexkehayias/Dropbox/Private/Python/foundation/images" *****
default: "/Users/alexkehayias/Dropbox/Private/Python/foundation/images", "/Users/alexkehayias/Dropbox/Private/Python/foundation/images", "/Users/alexkehayias/Dropbox/Private/Python/foundation/images", "/Users/alexkehayias/Dropbox/Private/Python/foundation/images", "/Users/alexkehayias/Dropbox/Private/Python/foundation/images"
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: "/Users/alexkehayias/Dropbox/Private/Python/foundation/images", "/Users/alexkehayias/Dropbox/Private/Python/foundation/images", "/Users/alexkehayias/Dropbox/Private/Python/foundation/images", "/Users/alexkehayias/Dropbox/Private/Python/foundation/images", "/Users/alexkehayias/Dropbox/Private/Python/foundation/images"
****\* line_comments = true *****
default: true, true, true, true, true
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: true, true, true, true, true
****\* cache = true *****
default: true, true, true, true, true
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: true, true, true, true, true
****\* extensions_path = "/Users/alexkehayias/Dropbox/Private/Python/foundation/extensions" *****
default: "/Users/alexkehayias/Dropbox/Private/Python/foundation/extensions", "/Users/alexkehayias/Dropbox/Private/Python/foundation/extensions", "/Users/alexkehayias/Dropbox/Private/Python/foundation/extensions", "/Users/alexkehayias/Dropbox/Private/Python/foundation/extensions", "/Users/alexkehayias/Dropbox/Private/Python/foundation/extensions"
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: "/Users/alexkehayias/Dropbox/Private/Python/foundation/extensions", "/Users/alexkehayias/Dropbox/Private/Python/foundation/extensions", "/Users/alexkehayias/Dropbox/Private/Python/foundation/extensions", "/Users/alexkehayias/Dropbox/Private/Python/foundation/extensions", "/Users/alexkehayias/Dropbox/Private/Python/foundation/extensions"
****\* http_fonts_path = "/stylesheets/fonts" *****
default: "/stylesheets/fonts", "/stylesheets/fonts", "/stylesheets/fonts", "/stylesheets/fonts", "/stylesheets/fonts"
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: "/stylesheets/fonts", "/stylesheets/fonts", "/stylesheets/fonts", "/stylesheets/fonts", "/stylesheets/fonts"
****\* http_stylesheets_dir = "stylesheets" *****
default: "stylesheets", "stylesheets", "stylesheets", "stylesheets", "stylesheets"
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: "stylesheets", "stylesheets", "stylesheets", "stylesheets", "stylesheets"
****\* disable_warnings = nil *****
default: -, -, -, -, -
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: -, -, -, -, -
****\* http_javascripts_dir = "javascripts" *****
default: "javascripts", "javascripts", "javascripts", "javascripts", "javascripts"
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: "javascripts", "javascripts", "javascripts", "javascripts", "javascripts"
****\* images_dir = "images" *****
default: -, -, -, -, -
value: "images", "images", "images", -, -
raw: -, "images", -, -, -
resolved: "images", "images", "images", -, -
****\* css_dir = "stylesheets" *****
default: -, -, -, -, -
value: "stylesheets", "stylesheets", "stylesheets", -, -
raw: -, "stylesheets", -, -, -
resolved: "stylesheets", "stylesheets", "stylesheets", -, -
****\* cache_path = "/Users/alexkehayias/Dropbox/Private/Python/foundation/.sass-cache" *****
default: "/Users/alexkehayias/Dropbox/Private/Python/foundation/.sass-cache", "/Users/alexkehayias/Dropbox/Private/Python/foundation/.sass-cache", "/Users/alexkehayias/Dropbox/Private/Python/foundation/.sass-cache", "/Users/alexkehayias/Dropbox/Private/Python/foundation/.sass-cache", "/Users/alexkehayias/Dropbox/Private/Python/foundation/.sass-cache"
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: "/Users/alexkehayias/Dropbox/Private/Python/foundation/.sass-cache", "/Users/alexkehayias/Dropbox/Private/Python/foundation/.sass-cache", "/Users/alexkehayias/Dropbox/Private/Python/foundation/.sass-cache", "/Users/alexkehayias/Dropbox/Private/Python/foundation/.sass-cache", "/Users/alexkehayias/Dropbox/Private/Python/foundation/.sass-cache"
****\* fonts_path = "/Users/alexkehayias/Dropbox/Private/Python/foundation/stylesheets/fonts" *****
default: "/Users/alexkehayias/Dropbox/Private/Python/foundation/stylesheets/fonts", "/Users/alexkehayias/Dropbox/Private/Python/foundation/stylesheets/fonts", "/Users/alexkehayias/Dropbox/Private/Python/foundation/stylesheets/fonts", "/Users/alexkehayias/Dropbox/Private/Python/foundation/stylesheets/fonts", "/Users/alexkehayias/Dropbox/Private/Python/foundation/stylesheets/fonts"
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: "/Users/alexkehayias/Dropbox/Private/Python/foundation/stylesheets/fonts", "/Users/alexkehayias/Dropbox/Private/Python/foundation/stylesheets/fonts", "/Users/alexkehayias/Dropbox/Private/Python/foundation/stylesheets/fonts", "/Users/alexkehayias/Dropbox/Private/Python/foundation/stylesheets/fonts", "/Users/alexkehayias/Dropbox/Private/Python/foundation/stylesheets/fonts"
****\* sass_dir = "sass" *****
default: -, -, -, -, -
value: "sass", "sass", "sass", -, -
raw: -, "sass", -, -, -
resolved: "sass", "sass", "sass", -, -
****\* cache_dir = ".sass-cache" *****
default: ".sass-cache", ".sass-cache", ".sass-cache", -, -
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: ".sass-cache", ".sass-cache", ".sass-cache", ".sass-cache", ".sass-cache"
****\* http_javascripts_path = "/javascripts" *****
default: "/javascripts", "/javascripts", "/javascripts", "/javascripts", "/javascripts"
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: "/javascripts", "/javascripts", "/javascripts", "/javascripts", "/javascripts"
****\* chunky_png_options = {:compression=>9} *****
default: {:compression=>9}, {:compression=>9}, {:compression=>9}, {:compression=>9}, {:compression=>9}
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: {:compression=>9}, {:compression=>9}, {:compression=>9}, {:compression=>9}, {:compression=>9}
****\* color_output = true *****
default: true, true, true, true, true
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: true, true, true, true, true
****\* environment = :development *****
default: :development, :development, :development, :development, :development
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: :development, :development, :development, :development, :development
****\* output_style = :compressed *****
default: :expanded, :expanded, :expanded, :expanded, :expanded
value: :compressed, :compressed, -, -, -
raw: -, :compressed, -, -, -
resolved: :compressed, :compressed, :expanded, :expanded, :expanded
****\* sass_path = "/Users/alexkehayias/Dropbox/Private/Python/foundation/sass" *****
default: "/Users/alexkehayias/Dropbox/Private/Python/foundation/sass", "/Users/alexkehayias/Dropbox/Private/Python/foundation/sass", "/Users/alexkehayias/Dropbox/Private/Python/foundation/sass", "/Users/alexkehayias/Dropbox/Private/Python/foundation/sass", "/Users/alexkehayias/Dropbox/Private/Python/foundation/sass"
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: "/Users/alexkehayias/Dropbox/Private/Python/foundation/sass", "/Users/alexkehayias/Dropbox/Private/Python/foundation/sass", "/Users/alexkehayias/Dropbox/Private/Python/foundation/sass", "/Users/alexkehayias/Dropbox/Private/Python/foundation/sass", "/Users/alexkehayias/Dropbox/Private/Python/foundation/sass"
****\* http_stylesheets_path = "/stylesheets" *****
default: "/stylesheets", "/stylesheets", "/stylesheets", "/stylesheets", "/stylesheets"
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: "/stylesheets", "/stylesheets", "/stylesheets", "/stylesheets", "/stylesheets"
****\* sass_options = nil *****
default: -, -, -, -, -
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: -, -, -, -, -
****\* fonts_dir = "stylesheets/fonts" *****
default: "stylesheets/fonts", "stylesheets/fonts", "stylesheets/fonts", "stylesheets/fonts", "stylesheets/fonts"
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: "stylesheets/fonts", "stylesheets/fonts", "stylesheets/fonts", "stylesheets/fonts", "stylesheets/fonts"
****\* project_path = "/Users/alexkehayias/Dropbox/Private/Python/foundation" *****
default: ".", ".", ".", ".", "."
value: "/Users/alexkehayias/Dropbox/Private/Python/foundation", "/Users/alexkehayias/Dropbox/Private/Python/foundation", "/Users/alexkehayias/Dropbox/Private/Python/foundation", "/Users/alexkehayias/Dropbox/Private/Python/foundation", -
raw: -, -, -, "/Users/alexkehayias/Dropbox/Private/Python/foundation", -
resolved: "/Users/alexkehayias/Dropbox/Private/Python/foundation", "/Users/alexkehayias/Dropbox/Private/Python/foundation", "/Users/alexkehayias/Dropbox/Private/Python/foundation", "/Users/alexkehayias/Dropbox/Private/Python/foundation", "."
****\* project_type = :stand_alone *****
default: :stand_alone, :stand_alone, :stand_alone, :stand_alone, :stand_alone
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: :stand_alone, :stand_alone, :stand_alone, :stand_alone, :stand_alone
****\* sprite_engine = :chunky_png *****
default: :chunky_png, :chunky_png, :chunky_png, :chunky_png, :chunky_png
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: :chunky_png, :chunky_png, :chunky_png, :chunky_png, :chunky_png
****\* relative_assets = true *****
default: -, -, -, -, -
value: true, true, -, -, -
raw: -, true, -, -, -
resolved: true, true, -, -, -
****\* http_images_dir = "images" *****
default: "images", "images", "images", "images", "images"
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: "images", "images", "images", "images", "images"
****\* asset_host = nil *****
default: -, -, -, -, -
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: -, -, -, -, -
****\* http_fonts_dir = "stylesheets/fonts" *****
default: "stylesheets/fonts", "stylesheets/fonts", "stylesheets/fonts", "stylesheets/fonts", "stylesheets/fonts"
value: -, -, -, -, -
raw: -, -, -, -, -
resolved: "stylesheets/fonts", "stylesheets/fonts", "stylesheets/fonts", "stylesheets/fonts", "stylesheets/fonts"
****\* http_path = "/" *****
default: -, -, -, -, -
value: "/", "/", "/", "/", "/"
raw: -, "/", -, -, -
resolved: "/", "/", "/", "/", "/"
'''

**Comment by scottdavis** [comment]
have you tried `compass clean` and then run watch

**Comment by alexkehayias** [comment]
Yes, it finds the first change, but subsequent changes are not seen when the .scss file is modified.

**Comment by scottdavis** [comment]
Weird

**Comment by alexkehayias** [comment]
lol agreed. Tried restarting and reinstalling the gem too. Guess I'll just stick with sass syntax for now.

**Comment by scottdavis** [comment]
its weird because i have an intern using this now with scss and its working

**Comment by alexkehayias** [comment]
Yeah not sure what it is. I tried updating everything to the latest versions too. Next will have to try to completely remove it and reinstall.

**Comment by stefl** [comment]
Could it be that because you're using Dropbox it has some kind of virtual file system so the usual "file changed" events don't fire? Try copying these files out of the Dropbox directory to somewhere else on your system?

**Comment by ttilley** [comment]
Dropbox doesn't come with an update mechanism, and some versions are absolutely horrific. When growl 1.3 broke notifications with dropbox and people made a point of upgrading to fix that one thing, my bug report rate for rb-fsevent dropped from "OMG please stab me in the face" to practically zero. Yes, zero. If you have dropbox installed, I would **STRONGLY** suggest either upgrading or nuking it then testing your bug again. If nothing else, it's another variable out of the way, right?

**Comment by ttilley** [comment]
Err... by "nuking" I mean both stopping the visible part from running and making sure `dbfsevents`, installed by dropbox, isn't running. Not necessarily uninstalling anything.

**Comment by alexkehayias** [comment]
I was able to start a project from scratch and use scss syntax with compass watch working. I tried the above with Dropbox, but I've noticed a problem with another compass plugin I'm using compass-foundation. I've determined that the problem lies there. Thanks for all your help!
