### ISSUE TITLE
opacity 0.5 results in css 0.005

### ISSUE THREAD

**Issue by JeanMertz** [Compass/compass#632]
When I use

``` css
@include opacity(0.5);
```

The result I get is a css file which sets `opacity: 0.005;`. Only after changing `0.5` to `50` it gives the desired result (`0.5`).

I tested this in the latest Safari and Chrome browsers.

**Comment by scottdavis** [comment]
which version of compass?

**Comment by scottdavis** [comment]
also are you sure the opacity mixin isn't being over ridden someplace? the source indicates 0.5 === 0.5 

hit view source: http://compass-style.org/reference/compass/css3/opacity/

**Comment by Keytwo** [comment]
I'm experiencing the same behavior on 0.12.alpha 2.

**Comment by chriseppstein** [comment]
It's just not possible -- the code is very straightfoward. Please provide a stylesheet that reproduces the issue. Until then I'm closing this.

**Comment by JeanMertz** [comment]
I must've moved on to other projects as I am not sure when and where I had this problem. I'll report back if I ever get this problem again, but for now I guess it was just a fluke in my codebase somewhere.

**Comment by Keytwo** [comment]
Same as JeanMertz here, seems to me that I had some dirty in the project tree. It doesn't happen anymore.
Bests

**Comment by jmccartie** [comment]
We ran into this problem when using the Twitter Bootstrap SASS files -- they were overriding "opacity" inside _mixins.scss (line 299):

```
// Opacity
@mixin opacity($opacity: 100) {
  opacity: $opacity / 100;
   filter: alpha(opacity=$opacity);
}
```

To get around this, you can either remove this bit, or just include bootstrap before compass.
