### ISSUE TITLE
SASS deprecation warning for on_updating_stylesheet

### ISSUE THREAD

**Issue by schnittchen** [Compass/compass#635]
With sass 3.1.11, I get

Sass::Compiler#on_updating_stylesheet callback is deprecated and will be removed in a future release. Use Sass::Compiler#on_updated_stylesheet instead, which is run after stylesheet compilation.

This is called from lib/compass/configuration/helpers.rb:70:in `configure_sass_plugin!'

**Comment by scottdavis** [comment]
Known issue but ill leave this open as a reminder thanks!
