### ISSUE TITLE
Documentation typo for the reset utilities

### ISSUE THREAD

**Issue by bzerangue** [Compass/compass#637]
Here's the page, http://compass-style.org/reference/compass/reset/utilities/#mixin-reset-display

`!important` arguments in the mixin should be `$important`

```@mixin reset-display($selector: "", !important: false) {
  #{append-selector(elements-of-type("inline"), $selector)} {
    @if !important {
      display: inline !important; }
    @else {
      display: inline; } }
  #{append-selector(elements-of-type("block"), $selector)} {
    @if !important {
      display: block !important; }
    @else {
      display: block; } } }

```
```

**Comment by scottdavis** [comment]
thanks

**Comment by stefl** [comment]
I thought I'd see if I could fix this. I've taken a look in the source for this method here:

https://github.com/chriseppstein/compass/blob/stable/frameworks/compass/stylesheets/compass/reset/_utilities.scss

and it doesn't seem to be reflected in the docs. I think I'm missing something...

**Comment by stefl** [comment]
Ah. It's fixed in the "beta" documentation. Suggest this issue is closed...

http://beta.compass-style.org/reference/compass/reset/utilities/#mixin-reset-display
