### ISSUE TITLE
output css filename is missing first character on Ubuntu

### ISSUE THREAD

**Issue by trotzig** [Compass/compass#638]
We are using:
Compass version 0.11.5
Ruby 1.9.1

On Windows using this configuration, "compass compile" is generating correct output. On Ubuntu, running the same Compass and Ruby versions and same *.scss files, output css filename is corrupt. What we see is that the contents of the file is correct, but the first character of the filename is missing. 

Here's an example:
(Windows) file **./scss/web.scss** is correctly outputted to **./css/web.css**
(Ubuntu) file **./scss/web.scss** is incorrectly outputted to **./css/eb.css**
Note the missing "w" in the filename. 
The issue is consistent with all our *.scss files. Output file is always missing the first character.

If we downgrade to 0.11.4, everything works fine.

**Comment by scottdavis** [comment]
is there a reason you are still running ruby 1.9.1? it had a lot of issues with file paths if i remember correctly

**Comment by trotzig** [comment]
No reason other than that it came pre-installed on Ubuntu. We had problems with the RVM. 

...and we're Java developers :)

I'll see if we can find time to upgrade and get back to you on this issue with the results.

**Comment by scottdavis** [comment]
have you tried using jruby? its all javay and cool

**Comment by scottdavis** [comment]
in fact if you developing in java you could probably write a direct integration

**Comment by chriseppstein** [comment]
I run 1.9.1 on ubuntu and have never seen this issue. If you can provide an environment with a shell account I will log in and try to diagnose it. email chris@eppsteins.net. Closing for now.
