### ISSUE TITLE
compass/reset is preventing Google fonts from loading

### ISSUE THREAD

**Issue by unikitty37** [Compass/compass#639]
My `application.css.scss` contains this:

```
/*
 *= require_self
*/

@import "bourbon";
@import "compass/reset";

@import "common";
```

with `common.css.scss` starting:

```
@import url(http://fonts.googleapis.com/css?family=Rokkitt:700|Lato:400italic,400,700,700italic|Inconsolata);

body, p, ol, ul, td {
  font-family: 'Lato', 'Calibri', 'Helvetica', 'Arial', sans-serif;
}
```

The body text displays in Calibri. If I remove the include of compass/reset, the body text correctly displays in Lato — but then the page layout gets destroyed, of course.

Examining the Resources tab in Safari's element inspector shows the fonts aren't even loaded when compass/reset is included.

It worked fine when the require_tree was still in place, rather than loading the stylesheets individually, but I wanted to use bourbon and this doesn't work with require_tree.

I really don't want to have to include all the resets at http://compass-style.org/reference/compass/reset/utilities by hand, bar the one that's causing the problem (and especially since that page isn't exactly clear on how to load individual resets!) Is it just that I'm loading things in the wrong order? I can't be the first to use compass/reset with Google fonts :)

I'm using Rails 3.1.3, sass-rails 3.1.5, compass 0.11.5 and sass 3.1.11.

**Comment by unikitty37** [comment]
Even more bizarrely, if I replace the `@import url(http://fonts.googleapis.com/css?family=Rokkitt:700|Lato:400italic,400,700,700italic|Inconsolata);` with the content of the imported URL, the web fonts load fine.

This happens in Safari 5.1.2 and Firefox 8.0.1.

Why would adding a reset break an import command?

**Comment by scottdavis** [comment]
can you post the full compiled output with and without the reset in a gist?

**Comment by unikitty37** [comment]
https://gist.github.com/1564467

Thanks

**Comment by scottdavis** [comment]
ok thanks will look into it

**Comment by rvock** [comment]
Your example including the reset has the import-rule in the middle of the (compiled css) stylesheet.
This is not allowed:
http://www.w3.org/TR/CSS2/cascade.html#at-import

```
The '@import' rule allows users to import style rules from other style sheets. In CSS 2.1, any @import rules must precede all other rules (except the @charset rule, if present).
```

**Comment by unikitty37** [comment]
Thanks — the problem was that the Google fonts @import was in the middle of a bunch of sass @import commands, and they get replaced with compiled CSS. Moving the Google fonts @import to the top of application.css.scss fixed the issue.
