### ISSUE TITLE
Compass with debug_info => true kills CSS3 Keyframe animations in Webkit

### ISSUE THREAD

**Issue by RyanHavoc** [Compass/compass#640]
Hi Guys,

Just wanted to report this issue.

I run Compass with the debug_info => true parameter set in my config.rb.

I've just been styling some CSS3 keyframe animation to be using in Firefox and Webkit browser and discover that with the debug_info turned on the animations work in Firefox but not in Webkit.

I edited my compiled stylesheet directly and removed the debug_info from the keyframe declaration and the animation started working in Safari/Chrome.

I then compiled the styles without debug_info turn on and all my animation work fine in Webkit.

Stumped me for a while. Thought I'd let everyone know there's an issue there.

Cheers

Ryan

**Comment by scottdavis** [comment]
this sounds more like a webkit issue closing this unless it is truly a problem with the debug output then that may be a sass issue
