### ISSUE TITLE
Bloated Gem

### ISSUE THREAD

**Issue by aaronchi** [Compass/compass#644]
I only realized this because I'm deploying on heroku where large gems contribute to your slug size which needs to be managed, but compass seems to add a lot of additional files to the compiled gem which makes it rather hefty.

Most gems exclude the tests/features. The compass gem also ships with an examples folder that is adds an additional 1MB.

I vendored a slimmed version of the gem into my project but thought I would post here to see if there was any interest in cleaning up the gemspec to make it smaller.

**Comment by scottdavis** [comment]
the examples probably do need to be extracted out

**Comment by chriseppstein** [comment]
Slimming down the gem file would be good. @aaronchi would you like to submit a patch?

**Comment by aaronchi** [comment]
I'd rather leave this to the maintainers to figure out what they want to include and exclude. IMO, the tests, features and examples don't need to be packaged with the gem unless there is some way they are being used.

Also, the compass gem creates a bunch of .rbc files and I don't know what those are or what they are for.

**Comment by kgrz** [comment]
I extracted the docs to a seperate repo: https://github.com/kgrz/compass-docs. If this is okay, then I'll edit any links pointing to the "doc-src" folder from the main README. I left out the examples directory out of this however.

**Comment by scottdavis** [comment]
The docs shouldn't be bundled when the gem is built

**Comment by scottdavis** [comment]
Yep they are excluded https://github.com/chriseppstein/compass/blob/stable/compass.gemspec

**Comment by kgrz** [comment]
Right. So that means deleting the "doc-src" folder from the main repo can be done right away isn't it?

**Comment by scottdavis** [comment]
no it means it doesn't need to be moved? its not packaged in the gem so i don't see what the issue is? we have enough problems with people updating the docs (I'm guilty of this myself). Moving them outside the repo isn't going to help that problem.
