### ISSUE TITLE
File to import not found or unreadable: compass in Rails 3.2.0beta (master)

### ISSUE THREAD

**Issue by masterkain** [Compass/compass#645]
Hello,
on the latest rails master compass cannot be loaded. Works in 3.1.3.
# app/assets/stylesheets/application.css.scss

```
@import "compass";
```
# Gemfile

```
group :assets do
  gem 'sass-rails',   :git => 'git://github.com/rails/sass-rails.git'
  gem 'coffee-rails', :git => 'git://github.com/rails/coffee-rails.git'
  gem 'uglifier', '>= 1.0.3'
  gem 'compass',      :git => 'git://github.com/chriseppstein/compass.git'
end
```
# Error

```
Error compiling CSS asset

Sass::SyntaxError: File to import not found or unreadable: compass.
Load Path: /Users/kain/Sites/my
    (in /Users/kain/Sites/my/app/assets/stylesheets/application.css.scss)

/Users/kain/Sites/my/app/assets/stylesheets/application.css.scss:1
```

**Comment by masterkain** [comment]
Spent some good hours diving into the problem and apparently it does seems related to the sprockets, because:

1) it also happens with another gem
2) rails ships different sprockets versions (~> 2.0.3 for 3-1-stable, 2.1.2 for master)

So perhaps I assume something broke in sprockets between 2.0.3 and 2.1.2.

Feel free to close if it's not related.

**Comment by scottdavis** [comment]
Ugh and we haven't even finished rails 3.1 integration

**Comment by masterkain** [comment]
I hear you,
in Rails 3.2 there are some important features I'd like not to miss for this project, however every so often the asset pipeline breaks. I probably have to submit a bug to sprockets as I found some evidence for it being the culprit, but I'm not sure 100% still.

It seems that only the root asset path gets picked up, like they are being filtered. I remember a ticker in sprockets which seems similar, although I'm on Lion and not Windows: https://github.com/rails/rails/issues/3679

/cc @josh

**Comment by masterkain** [comment]
Nothing to do, forcing sprockets to 2.0.3 in master does not fix anything, therefore at the moment I'm short of places where I have to look. Any help is welcome.

**Comment by morgoth** [comment]
I have the same problem with rails 3.2.0.rc1, compass-0.12.alpha.2, sprockets 2.1.2

**Comment by tricomsol** [comment]
I have the same problem with rails 3.2.0.rc1, compass-0.12.alpha.2, sprockets 2.1.2

**Comment by scottdavis** [comment]
if someone wants to step up and do a patch to get this working that would be great we are still struggling with rails 3.1 problems

**Comment by masterkain** [comment]
Perhaps related: https://github.com/rails/rails/issues/4041

**Comment by aaronchi** [comment]
I feel like compass is becoming a second class citizen in the Rails world since the asset pipeline was introduced. Is it worth trying to get in touch with Joshua Peek or other Rails core devs to troubleshoot this?

**Comment by phoet** [comment]
the asset-pipeline is the most time consuming rails feature/bug EVER!

**Comment by aaronchi** [comment]
temp fix here: https://github.com/rails/sass-rails/issues/81

**Comment by scottdavis** [comment]
"the asset-pipeline is the most time consuming rails feature/bug EVER!" i can't agree more but when it works im fairly happy with it the problems are all in implementation and not idea

**Comment by morgoth** [comment]
Temporary fix from @aaronchi is working.

Fix for this issue was just added to rails-sass: https://github.com/rails/sass-rails/commit/f8faec5e54b61dccc5cd11022c408ff1e20a40de

It should be enough to use sass-rails from master now

**Comment by imeos** [comment]
What really helped me out, after some good hours of trial and error, was to add this line to my Gemfile:
`gem 'compass', git: 'git://github.com/chriseppstein/compass', branch: 'master'`
... and to comment out the original compass dependency of course

**Comment by scottdavis** [comment]
if you want to live on the bleeding edge use this in your gemfile 

https://gist.github.com/9d27ab854dfadca917f1

**Comment by trevor** [comment]
@scottdavis i needed to capitalize the 'c' in compass:
`git://github.com/Compass/compass-rails.git` works
`git://github.com/compass/compass-rails.git` didn't work

**Comment by futura** [comment]
I just upgraded to Rails 3.2.1 and began getting the missing file error. Partial Gemfile:

```
...
gem 'rails', '~> 3.2'
gem 'sass-rails'
gem 'coffee-rails'
gem 'compass'
...
```

I get:

```
File to import not found or unreadable: blueprint/reset.
Load path: Sass::Rails::Importer(/Users/dwayne/Sites/casehandler_rails/app/assets/stylesheets/application.scss)
(in /Users/dwayne/Sites/casehandler_rails/app/assets/stylesheets/application.scss)
```

The backtrace shows the problem comes here:

```
app/assets/stylesheets/compass/screen.scss:5
```

Line 5 of that file looks like this:

```
@import "blueprint/reset";
```

Is this a path issue (because my Compass files are one level below application.scss), or is it the sprockets issue above?

Also, when I assign the gems like @scottdavis (Jan 21) says, the app won't start, and I get on my Passenger startup error page:

```
no such file to load -- compass/app_integration/rails
```

Thanks for any help.

**Comment by scottdavis** [comment]
Install compass-rails

**Comment by futura** [comment]
To install compass-rails, do I have to do anything other than add it to my Gemfile? My assets group:

```
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier',           '>= 1.0.3'
  gem 'execjs'
  gem 'therubyracer'
  gem 'compass', :git => 'git://github.com/chriseppstein/compass.git', :branch => 'no_rails_integration'
  gem 'compass-rails', :git => 'git://github.com/Compass/compass-rails.git'
end
```

My stylesheets are in app/assets/stylesheets.

My config/compass.rb file has:

```
sass_dir = "app/stylesheets"
```

When I restart the Rails server, I get:

```
no such file to load -- compass/app_integration/rails
```

**Comment by scottdavis** [comment]
No need to install it from git anymore the gem is released

**Comment by futura** [comment]
Yes, thank you, Scott! Now working with a simple:

```
gem 'compass'
gem 'compass-rails'
```

**Comment by masterkain** [comment]
@futura perhaps you can write only `gem 'compass-rails'`

**Comment by gotchahn** [comment]
With just gem 'compass-rails' makes works everything to me

**Comment by jwmount** [comment]
After I put  gem 'compass' and gem 'compass-rails' in Gemfile AND deleted gemfile.lock and ran $ bundle,  all OK.

**Comment by shoppyonline** [comment]
This is all confusing, I just want to style my Sencha-Touch components. 
I installed Ruby on my windows OS
I installed Compass
I got my sencha environment to play along 
and now I'm getting a "File to import not found or readable error" 
Whats that about? I've been at this for a week and a half now.

**Comment by adrianbinah** [comment]
what about compass-960 plugin, i have my refinery project running and the core of compass work great, but the import for 960 grid won't work.

i have add the gem in the gemfile and the require 'ninesixty' in the compass.rb, what am i missing

**Comment by ahx** [comment]
I just had the same problem and solved it by renaming the manifest file from *.css to *.css.scss. I am so smart.

**Comment by bluebird-communication** [comment]
I had the same problem.
I noticed that since several monthes, the Blueprint has been removed from Compass.
Thanks God, someone created a Gem, that solve this.

I just had to add this line to my Gemfile, then run `bundle` and it was OK :

```
# http://compass-style.org/blog/2012/05/20/removing-blueprint/
gem 'compass-blueprint'
```
