### ISSUE TITLE
Sprite: enhance the sprite function 

### ISSUE THREAD

**Issue by maddesigns** [Compass/compass#649]
Now I have this @mixin:

@mixin filetypes($map) {
    $sprite-map-name: sprite-map-name($map);
    @each $sprite-name in [list] {
          a[href $=".#{$sprite-name}"] {
               @extend .#{$sprite-map-name}-sprite;
               @extend .#{$sprite-map-name}-#{$sprite-name};
          }
     }
}

I want to fill the **[list]** automatically with the imported filenames like <code>$sprite-name in txt,zip,mov,... </code>.

**Comment by scottdavis** [comment]
dup of #620
