### ISSUE TITLE
Blueprint Reset Bug

### ISSUE THREAD

**Issue by philk** [Compass/compass#65]
This may be a feature and not a bug or an intentional change but either way it's a change from compass to compass-edge that surprised me.

Create a new Blueprint project.
Write up a new html file with a table (thead/tbody style) in it.
Load the page and notice the th/td fields sticking right together.
Run compass-edge on the same directory.
Load the page and notice the th/td fields now have 2px of spacing.

Commenting out @import blueprint/modules/reset.sass causes compass to behave like edge (extra padding between th's/td's).

Adding:
+blueprint-global-reset
+blueprint
to screen.sass fixes it in compass-edge.

**Comment by chriseppstein** [comment]
The only change I can see that might be doing it is this was added to the blueprint reset:

html
   font-size: 100.01%

The blueprint changeset was http://github.com/joshuaclayton/blueprint-css/commit/9be685760014b3258dcd83913b9b19f130551b2f

And it doesn't give an exact reason for the change. This is why granular commits are helpful :-P

I have sent an email to the blueprint mailing list to understand this change better.

http://groups.google.com/group/blueprintcss/browse_thread/thread/310c177ec4ec4d83

**Comment by chriseppstein** [comment]
I tried to get some details from the blueprint folks, but failed. Compass is a port of Blueprint, so if you coordinate a fix with them, I'll make the corresponding change on my end. Going to close this issue for now.
