### ISSUE TITLE
Circular or self reference exhausts resources

### ISSUE THREAD

**Issue by Pichirho** [Compass/compass#650]
If you import a self referencing file, compass may exhaust all memory.
### _self.scss

```
@import "compass/css3"; // get something BIG to parse
@import "self";
/* Put here lots of css/sass/scss if you want to exhaust all memory */
```
### crasher.scss

```
@import "self";
```
## Expected results

The parser should notice a self reference or a circular reference and stop parsing with an error.
## Actual results

When compass detects a change in crasher.scss, it includes _self.scss until it fails with `SystemStackError on line ["10"] of C: stack level too deep` or the OS crashes if the available memory is exhausted before that.

**Comment by Pichirho** [comment]
Forgot the important details:
- 64 bit Win7 Professional
- Rails 3.0.7
- sass 3.1.10
- compass 0.11.5

**Comment by scottdavis** [comment]
this is an issue with sass not compass. compass only uses what sass provides please file the issue there

**Comment by Pichirho** [comment]
To me it was an issue with compass. I only use what sass compass made me have.

(I'm ok with no further actions with compass as I know what was wrong. Let's just say I'm lazy, too, and not filing it again to another project.)

**Comment by chriseppstein** [comment]
Thanks for filing the bug, I have opened a [new issue against sass](https://github.com/nex3/sass/issues/227)
