### ISSUE TITLE
Sass::SyntaxError: File to import not found or unreadable: compass/reset back with Rails 3.2.RC1

### ISSUE THREAD

**Issue by wleeperogs** [Compass/compass#654]
With the release of rails 3.2.RC1 compass can't find the scss files again.  

I have:

"@import 'compass/reset'" in one of my css files and it give the error in the subject line.

I have tried the alpha2 as well as the Master branch with no help.

**Comment by aaronchi** [comment]
this seems to be an issue with sass-rails... we'll probably need to wait for a fix from the core rails team

**Comment by aaronchi** [comment]
temp fix here: https://github.com/rails/sass-rails/issues/81

**Comment by joemsak** [comment]
I have this exact issue on Rails 3.2.1 and Sass-Rails 3.2.3, and compass 0.12.rc.1

**Comment by joemsak** [comment]
_bump_ Edited versions in comment above

**Comment by scottdavis** [comment]
did you install compass-rails?

**Comment by joemsak** [comment]
Hey

I just found this http://blog.55minutes.com/post/16586931456/getting-compass-to-work-with-rails-3-1-and-3-2 and I'm following it now

Thanks!

**Comment by scottdavis** [comment]
http://beta.compass-style.org/blog/2012/02/01/compass-0-12-is-released/

**Comment by joemsak** [comment]
Looks like it came down to this solution

https://github.com/plataformatec/devise/commit/96f55a7ac7a61effd03a7f43dbbdfb6af8894579#diff-1

**Comment by felipecsl** [comment]
For me, the fix was simply taking `gem 'compass/rails'` out of `group :assets` in the Gemfile.

**Comment by scottdavis** [comment]
im having zero issues on 3.2.2

**Comment by pjammer** [comment]
@felipecsl you are da man.  That fix worked for me too. Now if we could only know why (or if we had the time to spelunk!)

**Comment by elado** [comment]
I just had the same problem and a quick google brought me here.

I used on a different project `gem 'compass'` and on a new one it gave me this error. I should've used `gem 'compass-rails'`

The reason it worked on the previous project was because I had

```
config.sass.load_paths << Compass::Frameworks['compass'].stylesheets_directory
```

under application.rb, but `gem 'compass-rails'` takes care of that.
