### ISSUE TITLE
IE8: Add a way to fall back to url when size of datauri exceeds 32KB

### ISSUE THREAD

**Issue by barkan** [Compass/compass#655]
Feature request:

Since IE8 can only do data uris that are 32kb or less, you have to keep track of image size outside your CSS, and choose when to adjust it.

It would be great if there was a way to query the file size of something before proceeding, or pass an argument to the mixin, automating this process.

**Comment by scottdavis** [comment]
so you want an `image-size('filename.png')` sass function?

**Comment by barkan** [comment]
Perhaps file-size so it can be used with fonts, too.

**Comment by richardaday** [comment]
Should the inline-image() function do one of the following?
- Check whether the image is >32kb and if true, use a URL instead
- Check whether the image is >32kb and warn the developer

**Comment by barkan** [comment]
The function, were it added, should probably be file-type agnostic, as it could be used for fonts, other file types, or whatever designers think of. Also, the function taking a specified action probably limits it, as there's just one browser (right now) with the 32KB constraint. And (as far as I know) SASS+Compass stay pretty browser agnostic.

As an off-the-cuff example: in your development css, you might put an orange outline around background images whose size exceeds 100KB, to draw attention to them for human review before deploying. No matter what browser they're using.

Perhaps it should simply return a number of the specified file: @if file-size(some.png) > 32 {...}

Then it's pretty easy to write whatever functions you want to use on your own. Especially since there'd be a lot of overhead to make the function happy for general release. It brings in needing to track browser type and version, etc.

**Comment by chriseppstein** [comment]
You shouldn't inline images that are so big. If you do, I don't think it's onerous to create a mixin to do both of these for you.
