### ISSUE TITLE
What about Client Side compilation?

### ISSUE THREAD

**Issue by umrashrf** [Compass/compass#656]
I was wondering if Compass supports client side compiling using Javascript? If not I would love to get my hands on it.

**Comment by scottdavis** [comment]
No and never will sass is implemented in ruby and compass builds on top of that. I take the stance that compiling assets on the client side is an unnecessary burdon for an end user to experience. If you need yourself seeing this functionality try less

**Comment by umrashrf** [comment]
I am working on SenchaFiddle.com and because Sencha Touch uses Compass for compiling scss to css, I have 2 options for the users to compile scss to css on the go.
1. They run the app, the SCSS is compiled over server.
2. They run and SCSS is compiled on the client side.

The point 1 is not good option because assuming if 1000 users request to compile SCSS at the same second, the server would queue all request and if a single request take 3 seconds to compile the last queued user would have to wait 3 minutes to get a single app running. I am interested to use Compass for compiling at the client side so every user resource is at their disposal.

Any suggestion?

**Comment by scottdavis** [comment]
well the only thing i can offer since this is an edge case use is your going to need to throw hardware / worker queues at this to make it work

**Comment by umrashrf** [comment]
Can you elaborate "need to throw hardware / worker queues"?

**Comment by scottdavis** [comment]
Well it depends on your server side technology 
here's an example in rails http://railscasts.com/episodes/243-beanstalkd-and-stalker
