### ISSUE TITLE
replace-text() image not found

### ISSUE THREAD

**Issue by ijy** [Compass/compass#660]
# The Problem

When using the replace-text() mixin:

```
@include replace-text("logo");
```

 the image is not being found with the message:

```
WARNING: 'logo' was not found (or cannot be read) in /Users/user/path/to/templates/assets/images
```
# The Test

When analysing with Firebug I can see the location of the image is correct: http://cl.ly/CyxW but the extension is not being added. As a test if I write the background rule out manually pointing to the same location with the image extension (.png) added the image is found and displayed correctly. The only difference when looking in firebug is the image extension: http://cl.ly/Cyf4

I have also confirmed that the image itself is readable.
# The Setup

I'm using this as a plain standalone project. No Rails/Ruby integration.
- **Ruby:** ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-darwin10.8.0]
- **Sass :** Sass 3.1.10 (Brainy Betty)
- *_Compass: *_ Compass 0.11.5 (Antares)

**Comment by chriseppstein** [comment]
You have to provide the extension of the image.

**Comment by ijy** [comment]
I had tried that before but was getting an error like this:

```
 error sass/screen.scss (Line 47: Invalid CSS after "...ge-replace(logo": expected ")", was ".png, 170px, 54...")
```

However having tried again I've just figured out the error of my ways. I just needed to wrap it in quotes. I was just passing it as a normal variable without quotes. Gah! Sorry about the false issue. It works fine when wrapped with quotes.

**Comment by chriseppstein** [comment]
Ya. That the url() "function" acts as a kind of quote in CSS is very strange. Sass functions do not have this property. 

Hunt & pecked on my iPhone... Sorry if it's brief!
