### ISSUE TITLE
Multi box shadow broken?

### ISSUE THREAD

**Issue by ericdfields** [Compass/compass#669]
Compass 0.12.alpha.4 (Alnilam)

Using the example from the [compass docs](http://beta.compass-style.org/examples/compass/css3/box_shadow/):

```
.test {
  @include box-shadow(rgba(blue, 0.4) 0 0 25px, rgba(green, 0.2) 0 0 3px 1px inset);
}   
```

Watcher says:
    Compilation took 1.282s
        error app/stylesheets/dashboard/dashboard.scss (Line 215: Mixin box-shadow takes 1 argument but 2 were passed.)
    overwrite public/stylesheets/dashboard/dashboard.css

**Comment by chriseppstein** [comment]
It works for me. I think you've got something wrong on your end. Maybe an old version you're picking up or maybe you've defined your own box-shadow mixin?

**Comment by ericdfields** [comment]
yup. overwritten elsewhere. sorry about that.
