### ISSUE TITLE
@import not working as expected

### ISSUE THREAD

**Issue by Nkburdick** [Compass/compass#670]
All, I apologize if I'm missing something super easy, but I've been hitting my head against wall trying to do get my Rails 3.1 app working and I feel like I've tried everything.  I have structured my stylesheet directory so that my application.css just loads screen.css.scss.  

```
// Application.css
/*
*= require_self
*= require "screen"
*= require_directory ../../../vendor/assets/stylesheets/
*/
```

Then, screen.css.scss looks ("something") like this:

```
// screen.css.scss

@import "blueprint/reset";
@import "partials/base";
@import "blueprint";
@import "blueprint/scaffolding";

@import "compass";

// partials in a partial subdirectory 
@import "style_guide";
@import "partials/header";
// .... other Sass partials
@import "partials/footer";
```

The footer and header partials use the Compass column mixins and the border-radius mixin.  However, I have NOT @import "compass" or @import "blueprint" in either of those partials because I assumed that it would import and use the @import references above, is that wrong?  Do you have to @import "compass" again in every partial? It works great as is in development.. but....

In my app, when I try in vain to precompile assets, it breaks on the css view partials because it says that there is no "column" mixin. What's odd too is that it seems like it's trying to compile in alphabetical file order, not based on the @import calls. Thanks for all the help!

**Comment by Nkburdick** [comment]
I wanted to update that the only way I can seem to get it to work is to move the partial subdirectory out of the assets/stylesheets directory and into another (or on it's own), similar to what is referenced in issue 337 by @introspectif

https://github.com/chriseppstein/compass/issues/337#issuecomment-1231693

**Comment by scottdavis** [comment]
You should avoid using the sprockets require syntax with sass in stead use the _filename.scss partial method define partials and import them using @import. use an application.scss to @import all partials

**Comment by scottdavis** [comment]
now that im at a computer... you need to have a file structure that looks like this

<pre>
- app/assets/stylesheets
  - application.scss
  - _styleguide.scss
  - partials
    - _footer.scss
    - _header.scss
</pre>


then just put this code in your application.scss

<pre>
// screen.css.scss

@import "blueprint/reset";
@import "partials/base";
@import "blueprint";
@import "blueprint/scaffolding";

@import "compass";

// partials in a partial subdirectory 
@import "style_guide";
@import "partials/header";
// .... other Sass partials
@import "partials/footer";
</pre>


you can replicate this line with a sass import: 

<pre>
*= require_directory ../../../vendor/assets/stylesheets/
</pre>


to

<pre>
@import "the specific file in vendor"
</pre>


As a recap the sprockets based requires are a very bad idea with sass they "break" sass by not allowing it to resolve its own dependency tree and are a magnitude slower I avoid them at all costs and this should be better documented in sprockets

**Comment by Nkburdick** [comment]
Thanks much for the help, but it's still breaking when I run `rake assets:precompile`.  It breaks on footer on an `@include  border-radius` call.  I don't have an`@import "compass"`in that footer partial because.

It works great in development, but I'm trying to get the assets to compile to push to Heroku on Cedar which runs an assets:precompile command prior to launch.  

One note, in my gemfile I have  `gem 'compass', '~> 0.12.alpha'`

**Comment by scottdavis** [comment]
You may have to import compass in that file

**Comment by Nkburdick** [comment]
Whew, got it figured out!!!

@scottdavis,  I wondered if that was the case, but in a new rails app that I created, this wasn't the case.  In addition, my app was compiling all the various partials into their own stylesheets, which isn't what was intended.  But I figure it out.  Per the gist that Chris wrote, https://gist.github.com/1184843, I had added this line into application.rb `config.assets.precompile << /(^[^_]|\/[^_])[^\/]*/`.  My new rails app didn't have that, but it compile almost perfectly.  I say almost because the application .css worked fine, but it missed compiling ie.css and print.css (I'm using blueprint framework).  To repair this, I added the following:

```
# production.rb

# Precompile additional assets (application.js, application.css, and all non-JS/CSS are already added)
  config.assets.precompile += %w( print.css ie.css )
```

Now, when I precompile assets, or push to Heroku, I only end up with the clean 3 css files in my public/assets directory where before I was getting all the files compiled, including the partials directory.

That said, I will admit that I was approaching it for the wrong reasons.  I am still new to Sass and mistakenly thought that if I @import "compass" into each partial, I would get the whole Compass framework every time.  I know understand that mixins aren't compiled until they are @include.  However, I think I still had the right idea to look into it because with that `config.assets.precompile << /(^[^_]|\/[^_])[^\/]*/` command, I was getting too many assets compiled.  Am I the only one?
