### ISSUE TITLE
Retrieving Specific Background Position (x/y)

### ISSUE THREAD

**Issue by dannygarcia** [Compass/compass#674]
According to the documentation it's possible to retrieve the background position of a sprite like so:

```
$icons: sprite-map("icons/*.png");
background-position: sprite-position($icons, new);
// background-position: 0 -34px;
```

It would be great to be able to specify which position to retrieve because some browsers lack support for `background-position-x` and `background-position-y`.

This could look like:

```
$icons: sprite-map("icons/*.png");
background-position: sprite-position-x($icons, new) center;
// background-position: 0 center;
```

or

```
$icons: sprite-map("icons/*.png");
background-position: center sprite-position-y($icons, new);
// background-position: center -34px;
```

**Comment by rvock** [comment]
You can add your own functions in your Scss-File, which use the sprite-position() function to create those functions:

```
@function sprite-position-x($map, $sprite, $offset-x: 0) {
    @return nth(sprite-position($map, $sprite, $offset-x, 0), 1);
}

@function sprite-position-y($map, $sprite, $offset-y: 0) {
    @return nth(sprite-position($map, $sprite, 0, $offset-y), 2);
}
```

Explanation: The sprite-position() function returns a sass-list with two entries: the x and y value. The nth() function returns an entry of a list (unlike some other languages, the first item is 1 and not 0)

I haven't tested the function yet, but it should work :)

**Comment by rubiii** [comment]
fyi: i tested sprite-position-y and it works great. thank you very much!
