### ISSUE TITLE
Smush sprites and images with Smusher

### ISSUE THREAD

**Issue by heygrady** [Compass/compass#676]
https://github.com/grosser/smusher

The sprites generated by Compass could be made smaller using a tool such as smoosher. It typically will remove as much as 25% from the size of the generated sprite. This is a necessary optimization for making the generated sprite as small as possible. This could be problematic since smoosher relies on a webservice so an internet connection is required for it to work.

Bonus: it would be nice to also smoosh all of the files in the configured images directory but that isn't really Compass's concern (and it would probably make Compass too slow).

**Comment by scottdavis** [comment]
This will never be a core feature but feel free to create a plugin that does this. I specifically added callbacks for this use case
