### ISSUE TITLE
Rails 3.2.0.rc.2 / Compass 0.12.alpha.4 - Sass not compiling

### ISSUE THREAD

**Issue by msp** [Compass/compass#678]
Hi there

I'm not getting any compiled css, not seen any errors. Superficial test with `compass watch' doesn't seem to have probs so that'll suffice in the meantime.

How can I dig further?

$ bundle show rails
ruby-1.9.2-p290@dis11/gems/rails-3.2.0.rc2

$ bundle show compass
ruby-1.9.2-p290@dis11/gems/compass-0.12.alpha.4

$ bundle show sass-rails
ruby-1.9.2-p290@dis11/gems/sass-rails-3.2.3

Compass.rb

preferred_syntax = :sass

css_dir = "app/assets/stylesheets"
sass_dir = "app/assets/stylesheets/sass"

Best

**Comment by joliss** [comment]
No advice on the digging, just wanted to say it's working fine for me with the exact same versions.

Perhaps you can describe what you mean by "not getting any compiled css". 404 errors on the asset URLs?

**Comment by msp** [comment]
Good to know.

Not working as in not creating css files in css_dir.

**Comment by joliss** [comment]
Hm, I'm not sure that it's supposed to compile them to css_dir.

With me they end up in tmp/cache/assets.

You should perhaps check this: http://guides.rubyonrails.org/asset_pipeline.html

**Comment by scottdavis** [comment]
i havent even begun to test with rails 3.2 im still trying to get rails 3.1.x working so bare with us

**Comment by msp** [comment]
Thanks Scott, I understood that from another thread. Let me know where to start digging so I can feed more usual info back..

**Comment by scottdavis** [comment]
should probaly move these conversations over to the compass-rails gem issue tracker github.com/compass/compass-rails

**Comment by chriseppstein** [comment]
The asset pipeline doesn't generate css files unless you call `rake assets:precompile`. For more information on the asset pipeline, please read the [rails guide](http://guides.rubyonrails.org/asset_pipeline.html).

**Comment by msp** [comment]
Hi Chris - you'd only need to do the rake precompile in prod. I guess this raises a more general question about how the two options integrate - seems a little unclear to me. i.e. before the asset pipeline, compass just took care of my sass. Now with the pipeline it seems we have 2 options to do the same job? Or has the pipeline superseded the old method?

**Comment by scottdavis** [comment]
The reason this exists is that using the assest pipeline cna be very slow in development but using watch you will gain a pretty decent speedup
