### ISSUE TITLE
Add documentation for image functions

### ISSUE THREAD

**Issue by joliss** [Compass/compass#679]
Image functions (like radial-gradient) are only documented by example on http://compass-style.org/examples/compass/css3/gradient/ -- there is no "proper" reference documentation.
On http://compass-style.org/reference/compass/css3/images/ only the mixins are documented, but not the functions.

Before we can write docs, I suspect we'll need to figure out how to make this fit with the documentation system.

(If I read the source correctly, the functions are defined in files like lib/compass/sass_extensions/functions/gradient_support.rb, and there is no existing documentation.)

**Comment by chriseppstein** [comment]
These functions use the standard css3 notation so they don't require compass-specific documentation. Our custom functions are documented in the "helpers" section of the docs. http://compass-style.org/reference/compass/helpers/
