### ISSUE TITLE
Add text-overflow mixin

### ISSUE THREAD

**Issue by Ahrengot** [Compass/compass#682]
Couldn't find it in the documentation and I think it would be a nice feature.

**Comment by mirisuzanne** [comment]
Would you like to submit a patch?

**Comment by Ahrengot** [comment]
Would love to, but don't really know how to mess around with the main compass files. I have no experience at all with ruby stuff.

**Comment by chriseppstein** [comment]
It already exists: http://compass-style.org/reference/compass/typography/text/ellipsis/
