### ISSUE TITLE
0.12.rc.0 - File to import not found or unreadable: compass/css3 

### ISSUE THREAD

**Issue by sujithrs** [Compass/compass#692]
With 0.12.rc.0 branch, I get the following error with rails 3.1 (jruby 1.6.4). It works fine with 0.12.alpha.4.

ActionView::Template::Error (File to import not found or unreadable: compass/css3...

Please let me know if you need more details.

**Comment by georgetogo** [comment]
Ditto.

**Comment by chriseppstein** [comment]
It it reproducible in the same stack in a fresh application?

**Comment by chriseppstein** [comment]
Did you follow the upgrade instructions? https://github.com/Compass/compass-rails/blob/stable/README.md

**Comment by rmm5t** [comment]
I'm seeing the same problem with 0.12.rc.0 in a Rails 2.3.1 app. Confirmed that it used to work in 0.12.alpha.4.

`File to import not found or unreadable: compass.`

I'll try in a fresh Rails 3.2.1 app.

**Comment by chriseppstein** [comment]
Please confirm that you have installed the compass-rails gem.

**Comment by rmm5t** [comment]
I was able to reproduce this problem in a fresh Rails 2.3.1 app where I only added compass to the `Gemfile` and supplied a simple import in `application.css.sass`.

Added to `Gemfile` (in assets group):

```
gem "compass", "~> 0.12.rc.0"
```

Added to `app/assets/stylesheets/application.css.sass`:

```
@import compass
```

The problem manifests itself during `rake assets:precompile` and happens in either a development or production environment.

**Comment by chriseppstein** [comment]
@rmm5t Please confirm that you have installed the compass-rails gem and followed the upgrade instructions in the compass-rails [README](https://github.com/Compass/compass-rails/blob/stable/README.md)

**Comment by rmm5t** [comment]
@chriseppstein Ah! Thanks. That's it. I guess I found myself "bundle updating" gems today without realizing the new compass-rails gem.  Also, sorry for the back-n-forth. I must have been commenting against a cached github page or something and didn't see your comments about the upgrade instructions or the compass-rails gem.

**Comment by chriseppstein** [comment]
@georgeplendl @sujithrs Ditto for you two...

**Comment by sujithrs** [comment]
It works fine with compass-rails gem. Thanks @chriseppstein!
