### ISSUE TITLE
release canidate.0 brakes ror_ecommerce

### ISSUE THREAD

**Issue by drhenner** [Compass/compass#693]
Take a look at this thread.
https://github.com/drhenner/ror_ecommerce/issues/27

I actually had a different side effect.  

my stack trace looked like this:

Started GET "/login" for 127.0.0.1 at 2012-02-01 12:13:30 -0500
Processing by UserSessionsController#new as HTML
  Rendered user_sessions/new.html.erb within layouts/application (6.5ms)
Completed 500 Internal Server Error in 71ms

ActionView::Template::Error (File to import not found or unreadable: compass.
Load path: Sass::Rails::Importer(/Users/davidhenner/projects/delete/app/assets/stylesheets/main.css.scss)
  (in /Users/davidhenner/projects/delete/app/assets/stylesheets/main.css.scss)):
    6:   </title>
    7:   <%#= stylesheet_link_tag :all %>
    8:   <%= stylesheet_link_tag 'sprite.css' %>
    9:   <%= stylesheet_link_tag 'application' %>

---

main.css.scss just does this:

@import "compass";
@import "blueprint";
@import "app_mixins";
@import "main_header";
@import "main_footer";
@import "sub_header";
@import "address_form";

@import "main_product_tabs";
@import "widget";
@import "app";

---

Thanks for all the work.

**Comment by scottdavis** [comment]
install compass-rails and report back

**Comment by drhenner** [comment]
Oddly enough:  If I install alpha.4 then upgrade to rc.0 everything works.  If I start with rc.0 is when I have issues.  I'll try the compass-rails thing now.

**Comment by scottdavis** [comment]
compass no longer has rails integration baked in moving forward you will need compass rails http://beta.compass-style.org/blog/2012/02/01/compass-0-12-is-released/

**Comment by drhenner** [comment]
Now I see what the other person reported on ror-e

David-Henners-MacBook-Pro:delete davidhenner$ rails s
./config/compass.rb:4:in `get_binding': uninitialized constant Compass::AppIntegration::Rails (NameError)
    from /Users/davidhenner/.rvm/gems/ruby-1.9.2-p290/gems/compass-0.12.rc.0/lib/compass/configuration/serialization.rb:24:in`eval'
    from /Users/davidhenner/.rvm/gems/ruby-1.9.2-p290/gems/compass-0.12.rc.0/lib/compass/configuration/serialization.rb:24:in `parse_string'
    from /Users/davidhenner/.rvm/gems/ruby-1.9.2-p290/gems/compass-0.12.rc.0/lib/compass/configuration/serialization.rb:15:in`block in _parse'
    from /Users/davidhenner/.rvm/gems/ruby-1.9.2-p290/gems/compass-0.12.rc.0/lib/compass/configuration/serialization.rb:14:in `open'
    from /Users/davidhenner/.rvm/gems/ruby-1.9.2-p290/gems/compass-0.12.rc.0/lib/compass/configuration/serialization.rb:14:in`_parse'
    from /Users/davidhenner/.rvm/gems/ruby-1.9.2-p290/gems/compass-0.12.rc.0/lib/compass/configuration/file_data.rb:7:in `block in new_from_file'
    from /Users/davidhenner/.rvm/gems/ruby-1.9.2-p290/gems/compass-0.12.rc.0/lib/compass/configuration/inheritance.rb:204:in`with_defaults'
    from /Users/davidhenner/.rvm/gems/ruby-1.9.2-p290/gems/compass-0.12.rc.0/lib/compass/configuration/file_data.rb:6:in `new_from_file'
    from /Users/davidhenner/.rvm/gems/ruby-1.9.2-p290/gems/compass-0.12.rc.0/lib/compass/configuration/helpers.rb:42:in`configuration_for'
    from /Users/davidhenner/.rvm/gems/ruby-1.9.2-p290/gems/compass-rails-1.0.0.rc.1/lib/compass-rails.rb:183:in `boot_config'
    from /Users/davidhenner/.rvm/gems/ruby-1.9.2-p290/gems/compass-rails-1.0.0.rc.1/lib/compass-rails.rb:201:in`<top (required)>'
    from /Users/davidhenner/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.21/lib/bundler/runtime.rb:68:in `require'
    from /Users/davidhenner/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.21/lib/bundler/runtime.rb:68:in`block (2 levels) in require'
    from /Users/davidhenner/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.21/lib/bundler/runtime.rb:66:in `each'
    from /Users/davidhenner/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.21/lib/bundler/runtime.rb:66:in`block in require'
    from /Users/davidhenner/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.21/lib/bundler/runtime.rb:55:in `each'
    from /Users/davidhenner/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.21/lib/bundler/runtime.rb:55:in`require'
    from /Users/davidhenner/.rvm/gems/ruby-1.9.2-p290/gems/bundler-1.0.21/lib/bundler.rb:122:in `require'
    from /Users/davidhenner/projects/delete/config/application.rb:9:in`<top (required)>'
    from /Users/davidhenner/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.2.1/lib/rails/commands.rb:53:in `require'
    from /Users/davidhenner/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.2.1/lib/rails/commands.rb:53:in`block in <top (required)>'
    from /Users/davidhenner/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.2.1/lib/rails/commands.rb:50:in `tap'
    from /Users/davidhenner/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.2.1/lib/rails/commands.rb:50:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

**Comment by scottdavis** [comment]
wants in your compass config file?

**Comment by drhenner** [comment]
project_type = :rails
project_path = Compass::AppIntegration::Rails.root
 # Set this to the root of your project when deployed:
http_path = "/"
css_dir = "public/stylesheets"
sass_dir = "app/stylesheets"
environment = Compass::AppIntegration::Rails.env
 # To enable relative paths to assets via compass helper functions. Uncomment: 
 # relative_assets = true
preferred_syntax = :scss

**Comment by scottdavis** [comment]
change environment = Compass::AppIntegration::Rails.env
to

``` ruby
project_path = CompassRails.root
environment = CompassRails.env
```

**Comment by drhenner** [comment]
sass_dir = "app/stylesheets"    

might be an issue

**Comment by scottdavis** [comment]
but i want ot note that doing this is a bad idea
while rails supports n environments compass only has 2 development and production if you have any custom rails environments compass will default to development and that may not be the intended result

you also shouldn't need to explicitly get the project path this should be done for you already

**Comment by drhenner** [comment]
should I change 

```
project_path = Compass::AppIntegration::Rails.root
```

also?

**Comment by scottdavis** [comment]
yes are you using asset pipeline?

**Comment by drhenner** [comment]
but i want ot note that doing this is a bad idea..

what is "doing this"

**Comment by drhenner** [comment]
Just moved to the asset pipeline Looking at this file I assume I need to change to:

sass_dir = "app/assets/stylesheets"

**Comment by scottdavis** [comment]
just remove the line the defaults will take over
and "doing this"

``` ruby
environment = CompassRails.env
```

**Comment by drhenner** [comment]
https://github.com/drhenner/ror_ecommerce/blob/master/config/compass.rb

**Comment by scottdavis** [comment]
basically you can just delete your compass config file and everything will be ok

**Comment by drhenner** [comment]
Well I have things working now.  I'll try deleting the file and report back.... I'll give a summary in a final comment so other people can read the thread more easily.  You are da man!  Heck, I thought I gave good support by answering within an hour.... now I look bad!  Thanks

**Comment by drhenner** [comment]
So in conclusion for those of you that are reading this thread....

1)  Compass was upgraded from 0.12.alpha.4 to 0.12.rc.0
2)  I needed to remove config/compass.rb in rails
3)  I needed to add "gem 'compass-rails'" in my gemfile

After that everything appeared to work.
