### ISSUE TITLE
Assets:precompile of generated sprites

### ISSUE THREAD

**Issue by Bazai** [Compass/compass#694]
If i make sprite generation from my /assets/image/sprite folder, and then plug it with:
```@import "sprite/*.png";

``````
And if i run:
```rake assets:precomile
``````

I'll obtain application.css file with link to sprite-_.png file inside *_root of public/ folder**, but my sprite-_.png file will be inside *_public/assets folder**

But we all need right mapping css - png.
Please, help. Is it my mistake or is it global?

**Comment by scottdavis** [comment]
rails version? are you using compass-rails?

**Comment by Bazai** [comment]
Yes, compass-rails. Rails 3.2.1.

**Comment by scottdavis** [comment]
i just realized about 20 minutes ago i forgot to include the monkey patch in the rails 3.1/3.2 railtie can you try aginst the master using 

``` ruby
gem 'compass-rails', :git => 'git://github.com/Compass/compass-rails.git'
```

in your gemfile

**Comment by Bazai** [comment]
Yes, now it works. Merge it, pls :) Thanks a lot.

**Comment by scottdavis** [comment]
ok pushing within the hour thanks for verifying
