### ISSUE TITLE
generated sprites are larger than neccessary

### ISSUE THREAD

**Issue by sgalinski** [Compass/compass#697]
I really love the new smart spriting of 0.12rc, but the generated sprite files seems not to be crushed. I often get savings around 20% while using punypng afterwards on the generated file. I know that punypng can't be used, but maybe something like pngcrush?

http://www.punypng.com/
http://pmt.sourceforge.net/pngcrush/

**Comment by scottdavis** [comment]
This is outside the scope of compass if you want to crush your sprites you should do this on deployment compass has call back hooks on sprite generator just for this reason.

http://beta.compass-style.org/help/tutorials/configuration-reference/#callbacks
