### ISSUE TITLE
0.12.rc.0 breaks dev asset pipeline (rails 3.1-3.2.1)

### ISSUE THREAD

**Issue by codegoblin** [Compass/compass#698]
Hey guys,

I upgraded from '0.12.alpha.4' to '0.12.rc.0'
and now I get the following error when I attempt to reload the app:

@import "_blueprint";
File to import not found or unreadable: _blueprint

Here is my application.css.scss (where the error is being generated from):
/*
- This is a manifest file that'll automatically include all the stylesheets available in this directory
- and any sub-directories. You're free to add application-wide styles to this file and they'll appear at
- the top of the compiled file, but it's generally better to create a new file per style scope.
  *= require_self
  */

/\* Welcome to Compass.
- In this file you should write your main styles. (or centralize your imports)
- Import this file using the following HTML or equivalent:
- <link href="/stylesheets/application.css" media="screen, projection" rel="stylesheet" type="text/css" /> */

/\* Blueprint
----------------------------------------------------------------------------------------------------*/

/\* Grid */
$blueprint-grid-columns: 24;
$blueprint-container-size: 950px;
$blueprint-grid-margin: 10px;
$blueprint-grid-width: ($blueprint-container-size + $blueprint-grid-margin) / $blueprint-grid-columns - $blueprint-grid-margin;

/\* Fonts */
$blueprint-font-family: "Cabin", Helvetica, Arial, sans-serif;
$blueprint-fixed-font-family: "andale mono", "lucida console", monospace;
$blueprint-font-size: 14px;

/\* Imports */
@import "_blueprint";
@include blueprint;

Here is the full stacktrace:

File to import not found or unreadable: _blueprint.
Load path: Sass::Rails::Importer(/app/assets/stylesheets/application.css.scss)
  (in /app/assets/stylesheets/application.css.scss)

Extracted source (around line #9):

6:  
7:     %title Media
8:  
9:     = stylesheet_link_tag    'application'
10:  
11:     = javascript_include_tag 'application'
12:     = yield :head

app/assets/stylesheets/application.css.scss:28
sass (3.1.12) lib/sass/tree/import_node.rb:64:in `rescue in import'
sass (3.1.12) lib/sass/tree/import_node.rb:42:in`import'
sass (3.1.12) lib/sass/tree/import_node.rb:25:in `imported_file'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:149:in`rescue in visit_import'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:154:in `visit_import'
sass (3.1.12) lib/sass/tree/visitors/base.rb:37:in`visit'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:18:in `visit'
sass (3.1.12) lib/sass/tree/visitors/base.rb:53:in`block in visit_children'
sass (3.1.12) lib/sass/tree/visitors/base.rb:53:in `map'
sass (3.1.12) lib/sass/tree/visitors/base.rb:53:in`visit_children'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:27:in `block in visit_children'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:39:in`with_environment'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:26:in `visit_children'
sass (3.1.12) lib/sass/tree/visitors/base.rb:37:in`block in visit'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:47:in `visit_root'
sass (3.1.12) lib/sass/tree/visitors/base.rb:37:in`visit'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:18:in `visit'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:7:in`visit'
sass (3.1.12) lib/sass/tree/root_node.rb:20:in `render'
sass (3.1.12) lib/sass/engine.rb:300:in`_render'
sass (3.1.12) lib/sass/engine.rb:247:in `render'
sass-rails (3.1.0) lib/sass/rails/template_handlers.rb:75:in`evaluate'
tilt (1.3.3) lib/tilt/template.rb:76:in `render'
sprockets (2.0.3) lib/sprockets/context.rb:175:in`block in evaluate'
sprockets (2.0.3) lib/sprockets/context.rb:172:in `each'
sprockets (2.0.3) lib/sprockets/context.rb:172:in`evaluate'
sprockets (2.0.3) lib/sprockets/bundled_asset.rb:171:in `build_dependency_context_and_body'
sprockets (2.0.3) lib/sprockets/bundled_asset.rb:135:in`dependency_context'
sprockets (2.0.3) lib/sprockets/bundled_asset.rb:194:in `build_dependencies_paths_and_assets'
sprockets (2.0.3) lib/sprockets/bundled_asset.rb:141:in`dependency_paths'
sprockets (2.0.3) lib/sprockets/bundled_asset.rb:61:in `mtime'
sprockets (2.0.3) lib/sprockets/asset.rb:58:in`block in encode_with'
sprockets (2.0.3) lib/sprockets/asset.rb:57:in `each'
sprockets (2.0.3) lib/sprockets/asset.rb:57:in`encode_with'
sprockets (2.0.3) lib/sprockets/bundled_asset.rb:43:in `encode_with'
sprockets (2.0.3) lib/sprockets/caching.rb:52:in`cache_asset'
sprockets (2.0.3) lib/sprockets/environment.rb:82:in `build_asset'
sprockets (2.0.3) lib/sprockets/trail.rb:102:in`find_asset_in_path'
sprockets (2.0.3) lib/sprockets/base.rb:101:in `find_asset'
sprockets (2.0.3) lib/sprockets/environment.rb:72:in`find_asset'
sprockets (2.0.3) lib/sprockets/base.rb:110:in `[]'
actionpack (3.1.0) lib/sprockets/helpers/rails_helper.rb:124:in`asset_for'
actionpack (3.1.0) lib/sprockets/helpers/rails_helper.rb:50:in `block in stylesheet_link_tag'
actionpack (3.1.0) lib/sprockets/helpers/rails_helper.rb:49:in`collect'
actionpack (3.1.0) lib/sprockets/helpers/rails_helper.rb:49:in `stylesheet_link_tag'
app/views/layouts/application.html.haml:9:in`_app_views_layouts_application_html_haml__4522494100393773421_70256629608040'
actionpack (3.1.0) lib/action_view/template.rb:144:in `block in render'
activesupport (3.1.0) lib/active_support/notifications.rb:55:in`instrument'
actionpack (3.1.0) lib/action_view/template.rb:142:in `render'
actionpack (3.1.0) lib/action_view/renderer/template_renderer.rb:52:in`render_with_layout'
actionpack (3.1.0) lib/action_view/renderer/template_renderer.rb:38:in `render_template'
actionpack (3.1.0) lib/action_view/renderer/template_renderer.rb:12:in`block in render'
actionpack (3.1.0) lib/action_view/renderer/abstract_renderer.rb:22:in `wrap_formats'
actionpack (3.1.0) lib/action_view/renderer/template_renderer.rb:9:in`render'
actionpack (3.1.0) lib/action_view/renderer/renderer.rb:36:in `render_template'
actionpack (3.1.0) lib/action_view/renderer/renderer.rb:17:in`render'
actionpack (3.1.0) lib/abstract_controller/rendering.rb:120:in `_render_template'
actionpack (3.1.0) lib/action_controller/metal/streaming.rb:250:in`_render_template'
actionpack (3.1.0) lib/abstract_controller/rendering.rb:114:in `render_to_body'
actionpack (3.1.0) lib/action_controller/metal/renderers.rb:30:in`render_to_body'
actionpack (3.1.0) lib/action_controller/metal/compatibility.rb:43:in `render_to_body'
actionpack (3.1.0) lib/abstract_controller/rendering.rb:99:in`render'
actionpack (3.1.0) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (3.1.0) lib/action_controller/metal/instrumentation.rb:40:in`block (2 levels) in render'
activesupport (3.1.0) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/benchmark.rb:310:in`realtime'
activesupport (3.1.0) lib/active_support/core_ext/benchmark.rb:5:in `ms'
actionpack (3.1.0) lib/action_controller/metal/instrumentation.rb:40:in`block in render'
actionpack (3.1.0) lib/action_controller/metal/instrumentation.rb:78:in `cleanup_view_runtime'
activerecord (3.1.0) lib/active_record/railties/controller_runtime.rb:24:in`cleanup_view_runtime'
actionpack (3.1.0) lib/action_controller/metal/instrumentation.rb:39:in `render'
devise (1.5.2) lib/devise/controllers/scoped_views.rb:28:in`render_with_scope'
devise (1.5.2) app/controllers/devise/sessions_controller.rb:10:in `block in new'
actionpack (3.1.0) lib/action_controller/metal/responder.rb:231:in`call'
actionpack (3.1.0) lib/action_controller/metal/responder.rb:231:in `default_render'
actionpack (3.1.0) lib/action_controller/metal/responder.rb:160:in`to_html'
actionpack (3.1.0) lib/action_controller/metal/responder.rb:153:in `respond'
actionpack (3.1.0) lib/action_controller/metal/responder.rb:146:in`call'
actionpack (3.1.0) lib/action_controller/metal/mime_responds.rb:238:in `respond_with'
devise (1.5.2) lib/devise/controllers/internal_helpers.rb:148:in`respond_with_navigational'
devise (1.5.2) app/controllers/devise/sessions_controller.rb:10:in `new'
actionpack (3.1.0) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
actionpack (3.1.0) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.1.0) lib/action_controller/metal/rendering.rb:10:in`process_action'
actionpack (3.1.0) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.1.0) lib/active_support/callbacks.rb:434:in`_run__1546434007887477273__process_action__3868187672892300422__callbacks'
activesupport (3.1.0) lib/active_support/callbacks.rb:386:in `_run_process_action_callbacks'
activesupport (3.1.0) lib/active_support/callbacks.rb:81:in`run_callbacks'
actionpack (3.1.0) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.1.0) lib/action_controller/metal/rescue.rb:17:in`process_action'
actionpack (3.1.0) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.1.0) lib/active_support/notifications.rb:53:in`block in instrument'
activesupport (3.1.0) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (3.1.0) lib/active_support/notifications.rb:53:in`instrument'
actionpack (3.1.0) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.1.0) lib/action_controller/metal/params_wrapper.rb:201:in`process_action'
activerecord (3.1.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (3.1.0) lib/abstract_controller/base.rb:121:in`process'
actionpack (3.1.0) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.1.0) lib/action_controller/metal.rb:193:in`dispatch'
actionpack (3.1.0) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.1.0) lib/action_controller/metal.rb:236:in`block in action'
actionpack (3.1.0) lib/action_dispatch/routing/route_set.rb:65:in `call'
actionpack (3.1.0) lib/action_dispatch/routing/route_set.rb:65:in`dispatch'
actionpack (3.1.0) lib/action_dispatch/routing/route_set.rb:29:in `call'
actionpack (3.1.0) lib/action_dispatch/routing/mapper.rb:41:in`call'
rack-mount (0.8.3) lib/rack/mount/route_set.rb:152:in `block in call'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:96:in`block in recognize'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:75:in `optimized_each'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:95:in`recognize'
rack-mount (0.8.3) lib/rack/mount/route_set.rb:141:in `call'
actionpack (3.1.0) lib/action_dispatch/routing/route_set.rb:531:in`call'
airbrake (3.0.9) lib/airbrake/rack.rb:27:in `call'
sass (3.1.12) lib/sass/plugin/rack.rb:54:in`call'
warden (1.1.0) lib/warden/manager.rb:35:in `block in call'
warden (1.1.0) lib/warden/manager.rb:34:in`catch'
warden (1.1.0) lib/warden/manager.rb:34:in `call'
actionpack (3.1.0) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
rack (1.3.6) lib/rack/etag.rb:23:in `call'
rack (1.3.6) lib/rack/conditionalget.rb:25:in`call'
actionpack (3.1.0) lib/action_dispatch/middleware/head.rb:14:in `call'
actionpack (3.1.0) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
actionpack (3.1.0) lib/action_dispatch/middleware/flash.rb:243:in `call'
rack (1.3.6) lib/rack/session/abstract/id.rb:195:in`context'
rack (1.3.6) lib/rack/session/abstract/id.rb:190:in `call'
actionpack (3.1.0) lib/action_dispatch/middleware/cookies.rb:326:in`call'
activerecord (3.1.0) lib/active_record/query_cache.rb:62:in `call'
activerecord (3.1.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:477:in`call'
actionpack (3.1.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (3.1.0) lib/active_support/callbacks.rb:392:in`_run_call_callbacks'
activesupport (3.1.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.1.0) lib/action_dispatch/middleware/callbacks.rb:28:in`call'
actionpack (3.1.0) lib/action_dispatch/middleware/reloader.rb:68:in `call'
rack (1.3.6) lib/rack/sendfile.rb:101:in`call'
actionpack (3.1.0) lib/action_dispatch/middleware/remote_ip.rb:48:in `call'
actionpack (3.1.0) lib/action_dispatch/middleware/show_exceptions.rb:47:in`call'
railties (3.1.0) lib/rails/rack/logger.rb:13:in `call'
rack (1.3.6) lib/rack/methodoverride.rb:24:in`call'
rack (1.3.6) lib/rack/runtime.rb:17:in `call'
activesupport (3.1.0) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
rack (1.3.6) lib/rack/lock.rb:15:in `call'
actionpack (3.1.0) lib/action_dispatch/middleware/static.rb:53:in`call'
airbrake (3.0.9) lib/airbrake/user_informer.rb:12:in `call'
railties (3.1.0) lib/rails/engine.rb:455:in`call'
railties (3.1.0) lib/rails/railtie/configurable.rb:30:in `method_missing'
/Users/gregipp/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/lib/nack/server.rb:146:in`handle'
/Users/gregipp/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/lib/nack/server.rb:99:in `rescue in block (2 levels) in start'
/Users/gregipp/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/lib/nack/server.rb:96:in`block (2 levels) in start'
/Users/gregipp/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/lib/nack/server.rb:86:in `each'
/Users/gregipp/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/lib/nack/server.rb:86:in`block in start'
/Users/gregipp/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/lib/nack/server.rb:66:in `loop'
/Users/gregipp/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/lib/nack/server.rb:66:in`start'
/Users/gregipp/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/lib/nack/server.rb:13:in `run'
/Users/gregipp/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/bin/nack_worker:4:in`<main>'

please let me know what additional information you need.

\- codegoblin

**Comment by tysonmote** [comment]
+1

Temporary fix is including something like this in `application.rb`:

```
if const_defined?( :Compass )
  config.sass.load_paths << Compass::Frameworks['compass'].stylesheets_directory
end
```

I'm pretty sure this is an old issue that was supposed to be fixed in 0.12... At least that's what my note to myself said for the above code. :)

**Comment by scottdavis** [comment]
install compass-rails and report back

http://beta.compass-style.org/blog/2012/02/01/compass-0-12-is-released/

**Comment by codegoblin** [comment]
DOH! Thanks so much you guys for the prompt, informative responses. If it hasn't been mentioned yet, perhaps it would be worth it to update the rails-integration wiki or perhaps the main README to mention the new gem? Thanks again!
