### ISSUE TITLE
No files were found in the load path matching "icons/*.png".

### ISSUE THREAD

**Issue by shaun-floss** [Compass/compass#699]
My sprites were working fine in Rails 3.1; I just upgraded to Rails 3.2, now I'm getting an error.

Compass::SpriteException

No files were found in the load path matching "icons/*.png".

The line that is generating this error is:
`$icons: sprite-map("icons/*.png", $spacing: 50px);`

Any ideas? Something to do with the asset pipeline?

**Comment by chriseppstein** [comment]
please test using compass-rails: http://beta.compass-style.org/blog/2012/01/29/compass-and-rails-integration/

**Comment by shaun-floss** [comment]
Perfect, the compass-rails gem fixed it.

Thanks chriseppstein!

**Comment by bigboss234** [comment]
please can you tell me how you do because i'm getting the same problem with livereload
