### ISSUE TITLE
compass watch doesn't notice changes in some cases. 

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#70]
Thread:
http://groups.google.com/group/compass-users/browse_thread/thread/71ff401ffbc574aa

**Comment by chriseppstein** [comment]
fixed in 0.10.0.pre5. I think.

**Comment by SahilMepani** [comment]
I know this is a very old thread. But lately I'm facing the same issue. I have been working with compass for almost an year now. It was working like charm. But then, unfortunately one day it suddenly stopped watching files after first successful attempt as mentioned in the google group by the previous user.

I'm using Windows7 64B
Sass 3.2.10
Compass Version: 0.12.0

Please help me out!
