### ISSUE TITLE
Upgraded From 0.11.7 to 0.12.rc.0 Errors

### ISSUE THREAD

**Issue by jessepinuelas** [Compass/compass#701]
When I try to watch files with compass using the following command: 
compass watch [path/to/project]

I get the following error:
No application integration exists for rails

I ran all the steps you have listed and also tried the rails integration steps on http://compass-style.org. Am I missing something here?

This is what my gemfile looks like:

``` ruby
source 'http://rubygems.org'

gem 'rails', '3.1.3'
#gem "compass", ">= 0.11.7"
gem "compass", ">= 0.12.rc.0"

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'mysql2'
gem 'jquery-rails'
gem 'json'
gem 'sprockets'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'compass-rails'
  gem 'sass-rails',   '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'
```

**Comment by chriseppstein** [comment]
During the RC period you need to follow the instructions from our beta site: http://beta.compass-style.org/install/

They say to use:

```
bundle exec compass watch
```

**Comment by jessepinuelas** [comment]
Thanks for the details. I reviewed the instructions from your beta site: http://beta.compass-style.org/install/
and I did not see any details about the bundle exec compass watch or compile.
