### ISSUE TITLE
Unable to fix typo in beta documentation

### ISSUE THREAD

**Issue by nathggns** [Compass/compass#702]
I found a 404 caused by a typo in the [**beta**](http://beta.compass-style.org) documentation for [spriting](http://beta.compass-style.org/help/tutorials/spriting). I am unable to find the correct branch to edit to fix this typo. Is it private?

**Comment by scottdavis** [comment]
no its in the doc-src directory on master

**Comment by nathggns** [comment]
Thank You, I don't know why I failed to find this before.

## 

Nathaniel Higgins
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
