### ISSUE TITLE
Need moz support for transform-style

### ISSUE THREAD

**Issue by benjamincharity** [Compass/compass#705]
Again, Firefox has begun supporting these newer CSS3 items and I am currently still forced to manually add the moz prefixed versions. 

Possibly a configuration option would be good to allow users to specify which browsers should be supported.

**Comment by scottdavis** [comment]
feel like making a patch?

**Comment by roytomeij** [comment]
Something went wrong in the above, please ignore. Will make a pull request with the proper code.

**Comment by ai** [comment]
Fix with another 3D styles in pull request #793

**Comment by chriseppstein** [comment]
@ai nailed it. closing.
