### ISSUE TITLE
Add 'column-break-before' property

### ISSUE THREAD

**Issue by leopic** [Compass/compass#709]
The current CSS Multi-column Layout draft mentions a property called: 'column-break-before', aimed to give developers more flexibility on where their columns should begin/stop.

It's currently supported by Webkit browsers and Opera 11.10 (no prefix needed).
- Opera: http://www.opera.com/docs/specs/presto28/css/multicolumnlayout/
- http://caniuse.com/multicolumn
- http://html5please.us/ 

Spec info here: http://www.w3.org/TR/css3-multicol/#column-breaks
Working example: http://kmsm.ca/2010/an-almost-complete-guide-to-css3-multi-column-layouts/

Thank you in advance,
Leo

**Comment by mirisuzanne** [comment]
Can you submit a pull request for this?

**Comment by nickcooley** [comment]
Hi Eric -- It's part of https://github.com/chriseppstein/compass/pull/827 Pull request #827  Thanks.  There was originally a rebase issue with it, but I think all should be good now.  Please see link above for more info on that pull request.
