### ISSUE TITLE
Blueprint Form Style Not Applied to Password Fields

### ISSUE THREAD

**Issue by threadhead** [Compass/compass#71]
In 'frameworks/blueprint/stylesheets/blueprint/modules/_form.sass' consistant input styling is not applied to password fields.

line 24:
---     &.text, &.title, &[type=text]
+++    &.text, &.title, &[type=text], &[type=password]

**Comment by chriseppstein** [comment]
This has already been fixed in v0.10. you can install it like so:

```
sudo gem install compass --pre
```
