### ISSUE TITLE
Bug in the backface-visibility and perspective mixins

### ISSUE THREAD

**Issue by ansman** [Compass/compass#711]
They only produce `backface-visibility: ...;` and `perspective: ...`, not any vendor specific prefixes.

**Comment by barraponto** [comment]
Just tested with Compass 0.11.7, Sass 3.1.10 and Ruby 1.9.2. Works fine.
Also tested with Compass 0.12.0, Sass 3.1.15 and Ruby 1.9.3. Works fine as well.

**Comment by chriseppstein** [comment]
Thanks @barraponto. Closing. Please provide a reproducible test case if you'd like us to re-open.
