### ISSUE TITLE
error in rgba after compile

### ISSUE THREAD

**Issue by SanderElias** [Compass/compass#713]
HI all,

I'm using compass 0.11.7 and ran into this problem.
If I create an .scss file with this content:

@import "compass/css3";

.another {
      background: rgba(254, 254, 254, 0.8);
  }

the result is:

/\* line 3, ../sass/test.scss */
.another {
  background: rgba(254, 254, 254, 0);
}

(note the last parameter off the rgba function being 0 in stead off 0.8)

As this is my first SCSS trail, it might be someting I'm doing wrong, but I have no clue whatsoever.

with kind regards
Sander Elias

**Comment by chriseppstein** [comment]
I cannot reproduce this result. I get `rgba(254, 254, 254, 0.8)` in the output running the latest sass stable and master releases. What version of sass are you running?

**Comment by SanderElias** [comment]
Hi Chris,

this is a cut and past form the command line. (I'm on windows 7, perhaps that has something to do with it!)

[E:\cristal\www_root]sass --version
Sass 3.1.15 (Brainy Betty)

[E:\cristal\www_root]compass --version
Compass 0.11.7 (Antares)

So I giess I'm on the latest versions.

regards
Sander Elias

**Comment by SanderElias** [comment]
Sorry, for closing, 
clearly I clicked the wrong button :)

regards
Sander

**Comment by chriseppstein** [comment]
What version of ruby are you running?

**Comment by chriseppstein** [comment]
On windows running ruby 1.9.2-p290:

```
C:\Users\Chris Eppstein>scss --compass
@import "compass/css3";

.another {
background: rgba(254, 254, 254, 0.8);
}
^Z
.another {
  background: rgba(254, 254, 254, 0.8); }
```

**Comment by SanderElias** [comment]
Ok, I seem to have an somewhat more recent ruby version:
[E:\cristal\www_root]ruby --version
ruby 1.9.3p0 (2011-10-30) [i386-mingw32]

**Comment by chriseppstein** [comment]
Can you see if downgrading fixes it?

**Comment by SanderElias** [comment]
removed everything, got the same ruby version as you have, and now it works.
So there is a small issue with the new ruby release. 
Not a problem for me, as I only need ruby for compass, so I will be happy on this version. But I guess this need some attention nevertheles.

**Comment by chriseppstein** [comment]
Thanks for confirming. I will investigate.

**Comment by jensgro** [comment]
I can confirm this issue. I used both the box-shadow-mix of Compass and two or three other mixins for box-shadow. Somehow the alpha is rendered and the next time it isn't. So most of the time "rgba(0,0,0,0.5)" in a mixin renders to "rgba(0,0,0,0)". 

This is not only a problem of Compass.
My new mixin was straight and rendered with the wrong alpha-value:

@mixin box-s($x: 1px, $y: 1px, $blur: 3px, $color: rgba(0, 0, 0, 0.5)) {
    -webkit-box-shadow: $x $y $blur $color;
       -moz-box-shadow: $x $y $blur $color;
            box-shadow: $x $y $blur $color;
}

There must be something strange in the background (Sass) working.

I am running ruby 1.8.7, Compass 0.11.7 and Sass 3.1.12

**Comment by jensgro** [comment]
It gets nicer. In my view it is no Compass-Issue, but a Sass-Issue. 
I erased all mixins in my SCSS-file and included this snippet:

```
    -webkit-box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.5);
       -moz-box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.5);
           box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.5);
```

In the end, Compass/Sass rendered this:

```
    -webkit-box-shadow: 1px 1px 3px rgba(0, 0, 0, 0);
       -moz-box-shadow: 1px 1px 3px rgba(0, 0, 0, 0);
           box-shadow: 1px 1px 3px rgba(0, 0, 0, 0);
```

Something very strange is happening.

**Comment by jensgro** [comment]
Sorry for commenting this much. In the end it seems to be a problem of the tool "Scout" that I used to make my life a little bit easier. I guess I return to the Terminal again.

After configuring Compass via terminal and letting it watch via terminal all problems disappeared. Very strange.

**Comment by chriseppstein** [comment]
Please file a bug with Scout. If they need help diagnosing, I'll be happy to assist.

**Comment by laurodm** [comment]
this worked

@mixin dropshdow_padrao {
-webkit-box-shadow: 0px 3px 20px #{'rgba(0, 0, 0,.35)'};
-moz-box-shadow: 0px 3px 20px #{'rgba(0, 0, 0,.35)'}; 
box-shadow: 0px 3px 20px #{'rgba(0, 0, 0,.35)'}; 
}

@mixin degrade_padrao($cor_bg){ 
background: -moz-linear-gradient(90deg, #{'rgba(0, 0, 0, .09)'} 30%, #{'rgba(255, 255, 255,.09)'} 70%),$cor_bg;
background: -webkit-linear-gradient#{'(90deg, #{'rgba(0, 0, 0, .09)'} 30%, #{'rgba(255, 255, 255,.09)'} 70%)'},$cor_bg;
background: -o-linear-gradient(90deg, #{'rgba(0, 0, 0, .09)'} 30%, #{'rgba(255, 255, 255,.09)'} 70%),$cor_bg;
background: -ms-linear-gradient(90deg, #{'rgba(0, 0, 0, .09)'} 30%, #{'rgba(255, 255, 255,.09)'} 70%),$cor_bg;
background: #{'linear-gradient(180deg, rgba(255, 255, 255, .09) 30%, #{rgba(0, 0, 0,.09)} 70%)'},$cor_bg;
}

**Comment by marcofugaro** [comment]
I've come across the same issue recently, hot to reproduce it:

Compile 'box-shadow: 0 0 10px rgba(0, 0, 0, 0.1)' the first time and it works normally, then change any other thing in the scss file or any other partial file and compile, it now compiles to 'box-shadow: 0 0 10px rgba(0, 0, 0, 0)'

System: Windows 7 64bit
