### ISSUE TITLE
$relative-font-sizing: false does not change unit to px

### ISSUE THREAD

**Issue by bookcasey** [Compass/compass#716]
I'm struggling with a problem using [$relative-font-sizing](http://compass-style.org/reference/compass/typography/vertical_rhythm/#const-relative-font-sizing).

This:

``` sass
@import compass/reset
@import compass/typography/vertical_rhythm

$base-font-size: 16px
$base-line-height: 24px
$relative-font-sizing: false

+establish-baseline()

h1
  +adjust-font-size-to(48px)
```

Outputs:

``` css
h1 {
  font-size: 3em;
  line-height: 4.5em;
}
```

Which I find inexplicable. It only differs in `line-height` from `$relative-font-sizing: true` when it should output _absolute [pixes](http://compass-style.org/reference/compass/typography/vertical_rhythm/#const-relative-font-sizing)_ [sic].

**Comment by chriseppstein** [comment]
Ah, you need to set configuration variable before you import. http://compass-style.org/help/tutorials/configurable-variables/
