### ISSUE TITLE
Error in partial generates error message with incorrect filename

### ISSUE THREAD

**Issue by sentience** [Compass/compass#720]
I can reproduce this problem in Compass 0.11.7. It did not exist in 0.11.1 (which I was running previously).

When there is a syntax error in an imported partial, the error message reported by Compass contains the filename of the including file where it should cite the filename of the partial.

For example, if I have screen.scss that imports _partial.scss, and in _partial.scss, there is a syntax error on line 10. When I ask Compass to compile my project, I get an error like this:

```
error assets/sass/screen.scss (Line 10: Incompatible units: 'px' and 'pxx'.)
```

Note that the line number is correct (the problem is on line 10 of _partial.scss), but the filename is not (in my case, screen.scss doesn’t even contain 10 lines!).

**Comment by andreyvit** [comment]
@chriseppstein This is actually the report I emailed you about. I checked 0.11.7, 0.11.5 and 0.10.x (0.10.6, I think), and it existed there.

I've currently patched the version of Compass bundled with LiveReload like this:

```
--- lib/compass/lib/compass/lib/compass/compiler.rb    2012-02-04 11:25:30.000000000 +0700
+++ lib/compass/lib/compass/compiler.rb    2012-02-15 08:48:39.000000000 +0700
@@ -156,6 +156,9 @@
   # formatted to display in the browser (in development mode)
   # if there's an error.
   def handle_exception(sass_filename, css_filename, e)
+      if ENV['COMPASS_FULL_SASS_BACKTRACE'] && e.respond_to?(:sass_backtrace_str)
+        $stderr.puts e.sass_backtrace_str()
+      end
     formatted_error = "(Line #{e.sass_line}: #{e.message})"
     file = basename(sass_filename)
     logger.record :error, file, formatted_error
```

I'd be glad to discuss some ways to contribute a similar functionality into the mainline. Maybe an additional command-line flag to get a full back-trace? How will that interact with the logger system? On the other hand, I don't see any cases when people would NOT want an actual error location.

The way I consume it is by parsing the output with regexps. That's not the point, however; I need `compass compile` to output the correct error location in any way, and then I will figure a way to extract it.

**Comment by chriseppstein** [comment]
Fixed. If the file the error occurred in was not the primary file, compass now displays the file name the error originated in.
