### ISSUE TITLE
Sprite mixin does not honor config image folder value

### ISSUE THREAD

**Issue by madewithsalt** [Compass/compass#723]
Hello!

I found that using both the following sprite import method:

``` sass
@import "icons/*.png"
@include all-icons-sprites
```

as well as the compass command line equivalent `compass sprite "icons/*.png"` does not honor my custom image folder name `"img/"`. It instead searches for the sprite PNG inside the path starting with `"images/"`.

The sprite image DOES save to the correct folder (in my case `"img"`) but the generated CSS does not point there. It points to `"images"`.

example from my generated CSS:

```
/* line 183, icons */
.icons-sprite, .icons-accept, ... {
  background: url('/images/icons-s45be9254d5.png') no-repeat;
}
```

**Comment by chriseppstein** [comment]
Pretty sure this is a configuration problem. Since this issue is pretty old, I'm closing it. If you still want help, please show me your configuration and I'll take a look.
