### ISSUE TITLE
Mixins not at document root

### ISSUE THREAD

**Issue by chrisdrackett** [Compass/compass#724]
I just updated sass and compass and am now getting the following when I try and compile:

sass/main.sass (Line 26: Mixins may only be defined at the root of a document.)

I do have mixin's in files that are imported, but this hasn't even been an issue in the past. Just curious what is going on!

**Comment by mirisuzanne** [comment]
It's actually referring to the root of that file. You can't define a mixin nested inside an element.

Wrong:

```
#foo { @mixin bar($value) { property: $value; } }
```

Right:

```
@mixin bar($value) { property: $value; }

#foo { @include $bar($baz); }
```

**Comment by chriseppstein** [comment]
Root of the document means its not nested in a selector.  Are your imports nested? If so, move the the mixins to a different file. There was a bug in the sass validator that caused this issue to not be detected until recently -- this resulted in unpredictable behavior as it was never intended. 

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by chrisdrackett** [comment]
heh, I use this all over the place. Guess I never knew it wasn't valid ;) I'm also nesting imports in mixins. This is going to be fun! :(
