### ISSUE TITLE
--no-cache on starting project

### ISSUE THREAD

**Issue by aleksandargosevski** [Compass/compass#727]
It would be nice if you could add --no-cache option on starting a new project in command line.

**Comment by chriseppstein** [comment]
Seems ok, but I'm curious why you don't want the cache and why it's important to have this on the project creation step.

**Comment by aleksandargosevski** [comment]
That option isn't of crucial importance, but I dont know whats purpose of cache? Maybe is important, but i don't use it. :) Reason why I asked for is because i don't need one extra folder in my project folder.

**Comment by chriseppstein** [comment]
The sass cache provides substantial performance improvements when recompiling unchanged files/partials.

**Comment by aleksandargosevski** [comment]
Oh, now I undestand. Thanks. :)
