### ISSUE TITLE
replace-text and text alignment

### ISSUE THREAD

**Issue by pixelmatrix** [Compass/compass#73]
The replace-text mixin should include text-align: left in order to make the -9999em text indent work. 

I experienced an issue where the text kept showing through with objects that inherited text-align: right from the container until I solved it by changing the text-align. Another solution is to use 9999em instead of -9999em since the text-indent is applied from the other side of the container when text-align: right is in use. I think the first suggestion is the simplest though.

**Comment by chriseppstein** [comment]
Would you like to submit a patch for this?

**Comment by chriseppstein** [comment]
patch applied and fixed in v0.10.0.pre3
