### ISSUE TITLE
Documentation on running tests needs updating

### ISSUE THREAD

**Issue by roytomeij** [Compass/compass#731]
See http://groups.google.com/group/compass-users/browse_thread/thread/a19fda0dbba5a137

@scottdavis said: "That documentation is old can you open a gut hub issue?"

**Comment by scottdavis** [comment]
GUT HUB IS THE BEST HUB!

**Comment by scottdavis** [comment]
in the mean time if you need help my gtalk / aim is: jetviper21

**Comment by roytomeij** [comment]
http://guthub.com/ actually works :P

I'll take you up on that one probably tonight (which is your afternoon).

**Comment by JohnAlbin** [comment]
I'd consider myself a Sass master, but Ruby novice. My dev environment doesn't have "bundle" in its binary $PATH, so I can't even get as far as Roy did.

I'd love to contribute to Compass, but the docs for "writing tests" has even less text than the "running tests" section.

**Comment by JohnAlbin** [comment]
Figured out that I needed to run `sudo gem install bunder` based on the opaque link saying “In a bundled enviroment…”

Make sure that's in the docs too!

**Comment by roytomeij** [comment]
I'm in a Ruby shop, so I'm used to using RVM, Bundler, etc. I have the project on Ruby 1.8.7 using RVM (bundler couldn't install some gems on 1.9.2 and 1.9.3 because of compatibility issues with rcov I believe). For me it starts failing when trying to run the tests.

I didn't have time to talk to @scottdavis yet, but would greatly appreciate any help in the meantime (and fix the documentation afterwards). Open source projects are so much better when people can actually contribute :-)

**Comment by JohnAlbin** [comment]
Here's the steps I've run so far:
- sudo gem install bundler
- change to the root directory of a git checkout of Compass
- bundle install --binstubs devbin
- bundle exec rake test features

That's when I see the same errors that Roy sees. My text editor's syntax highlighter is showing what looks like a run-on string starting at line 141 of lib/compass/commands/watch_project.rb:

```
puts ">>> Change detected at "+Time.now.strftime("%T")+" to: #{relative || compiler.relative_stylesheet_name(file)}
```

**Comment by silvenon** [comment]
The rcov issue has been fixed 3 days ago. I had troubles with installing gherkin too, the fix was to add this to the Gemfile:

```
gem "gherkin", :git => "git://github.com/RKelln/gherkin.git"
```

For me the tests are still full of warnings and stuff, but it's now possible to execute them (using `bundle exec rake test features`). Will you contribute to the docs?

**Comment by roytomeij** [comment]
Seems to be working now on `stable` on RMV with Ruby 1.9.3. I do get a lot of warnings, but just one error (about "Get stats for my project" not passing). Is this a good basis to start working on Compass with and base the documentation changes on?

```
WARNING: cannot load such file -- rcov/rcovtask
/Users/roy/.rvm/rubies/ruby-1.9.3-p0/bin/ruby -I"lib:lib:test" -I"/Users/roy/.rvm/gems/ruby-1.9.3-p0@compass/gems/rake-0.9.2.2/lib" "/Users/roy/.rvm/gems/ruby-1.9.3-p0@compass/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb" "test/integrations/compass_test.rb" "test/integrations/sprites_test.rb" "test/units/actions_test.rb" "test/units/command_line_test.rb" "test/units/compass_png_test.rb" "test/units/compiler_test.rb" "test/units/configuration_test.rb" "test/units/sass_extensions_test.rb" "test/units/sprites/engine_test.rb" "test/units/sprites/image_row_test.rb" "test/units/sprites/image_test.rb" "test/units/sprites/importer_test.rb" "test/units/sprites/layout_test.rb" "test/units/sprites/row_fitter_test.rb" "test/units/sprites/sprite_command_test.rb" "test/units/sprites/sprite_map_test.rb" 
Loaded suite /Users/roy/.rvm/gems/ruby-1.9.3-p0@compass/gems/rake-0.9.2.2/lib/rake/rake_test_loader
Started
.............WARNING on line 40 of /Users/roy/OpenSource/compass/test/fixtures/stylesheets/compass/sass/gradients.sass:
This selector doesn't have any properties and will not be rendered.
Cannot determine the opposite position of: -45deg
Cannot determine the opposite position of: -45deg
Cannot determine the opposite position of: -45deg
Cannot determine the opposite position of: -45deg
WARNING: The linear-gradient mixin is deprecated. Instead use: @include background-image(linear-gradient(#dddddd, #aaaaaa))
         on line 49 of /Users/roy/OpenSource/compass/frameworks/compass/stylesheets/compass/css3/_gradient.scss, in `linear-gradient'
         from line 91 of /Users/roy/OpenSource/compass/test/fixtures/stylesheets/compass/sass/gradients.sass
```
