### ISSUE TITLE
Error when installing CSS3 PIE 

### ISSUE THREAD

**Issue by gasatrya** [Compass/compass#735]
I got this error message

D:\xampp\htdocs\mixins>compass install compass/pie
Errno::EACCES on line ["38"] of C: Permission denied - D:/xampp/htdocs/mixins//P
IE.htc
Run with --trace to see the full backtrace

**Comment by chriseppstein** [comment]
Please confirm that you have write permissions on the `D:/xampp/htdocs/mixins` directory.

**Comment by gasatrya** [comment]
Sorry for my stupid question, how can I do "confirm that you have write permissions on the <code>D:/xampp/htdocs/mixins</code> directory." ?

Thanks

**Comment by chriseppstein** [comment]
![Like this?](https://img.skitch.com/20120227-bhr319bcn32ht1ywybap9ibm5y.png)

**Comment by chriseppstein** [comment]
You need to find the folder in windows explorer and then right click it and select properties. Then click the security tab and check that users can write there.

**Comment by gasatrya** [comment]
Ok, I found the folder properties, and edited it so users can write. But I'm still got an error message whe installed the PIE :( ,

**Comment by chriseppstein** [comment]
Please ensure that your system has the correct permissions for all folders -- this doesn't seem to be related to compass.
