### ISSUE TITLE
Validate sprite css in mixins not helpers

### ISSUE THREAD

**Issue by zanker** [Compass/compass#738]
Currently, Compass will validate the CSS of a sprite as soon as the image is imported.  The problem with this is that it makes it impossible to use images with numbers at the start because it's an invalid CSS tag.

This only causes invalid CSS  if you use the mixins referenced on the [spriting tutorial](http://compass-style.org/help/tutorials/spriting/), but if you use the [advanced helpers](http://compass-style.org/reference/compass/helpers/sprites/) then there are no actual validation errors.

Unless this is intentional, I would be happy to write a pull request to accomplish this, but I was unable to find the exact portion that defines all of the CSS generating helpers in the tutorial.

**Comment by scottdavis** [comment]
This is intentional.

**Comment by chriseppstein** [comment]
Note, you can use sprites without using the "magic" import. I did this recently for my app:

``` sass

@import "compass/utilities/sprites/base"

$step-sprites: sprite-map("local_wizard/step/*.png", $layout: vertical, $cleanup: true)
.step-sprite
  background: white $step-sprites no-repeat

body.dumbledore
  #app-collection-wrapper.who
    @extend .step-sprite
    +sprite($step-sprites, lilacs)
  #app-collection-wrapper.what
    @extend .step-sprite
    +sprite($step-sprites, heart)
  #app-collection-wrapper.where
    @extend .step-sprite
    +sprite($step-sprites, flowerbox)
  #app-collection-wrapper.when
    @extend .step-sprite
    +sprite($step-sprites, stairs)
  #app-collection-wrapper.payment
    @extend .step-sprite
    +sprite($step-sprites, orangeflower)
  #app-collection-wrapper.contact-info
    @extend .step-sprite
    +sprite($step-sprites, letter)
```

If you take this approach, the naming requirements are not necessary to enforce strictly. Changing the way this error is raised seems reasonable.

**Comment by zanker** [comment]
Sorry the original description should have included an example for clarity. How I was calling it is identical to your example.

Was able to track down the files I needed, I'll see about getting a pull request up tomorrow.

**Comment by chriseppstein** [comment]
@zanker sounds good.

**Comment by zanker** [comment]
https://github.com/chriseppstein/compass/pull/739
