### ISSUE TITLE
Animate mixin

### ISSUE THREAD

**Issue by aleksandargosevski** [Compass/compass#741]
This is the good thing to insert in compass/css3 set of mixins.

http://thecssguru.freeiz.com/animate/

**Comment by MoOx** [comment]
This is too huge & complex to be added as is.
But maybe a animation mixin & some timing function preset will be great (like bourbon does).
I've done some stuffs here https://github.com/MoOx/compass-recipes/tree/master/stylesheets/recipes/animation

**Comment by wyuenho** [comment]
Eric Meyer already has an animation plugin for the next version of SASS and Compass. It is a much better alternative than _animate.sass for it actually uses keyframes and doesn't have all the mixin conflicts.

https://github.com/ericam/compass-animation

**Comment by chriseppstein** [comment]
Ayup. We've got this running on sass 3.2 right now: https://gist.github.com/1943798 It's pretty hot.

**Comment by paulirish** [comment]
@ericam now that 9b924243ff7fb543ea8fdce572cf3fc94ef147ba is in.. fixed?

**Comment by mirisuzanne** [comment]
Yes, thanks.
