### ISSUE TITLE
Interpolation fails when using margin shorthand

### ISSUE THREAD

**Issue by jenshedqvist** [Compass/compass#742]
This SCSS:

`margin: -#{$module_padding + 1} -#{$module_padding + 1} 0 -#{$module_padding + 1};`

Outputs to:

`margin: -15px-15px 0-15px;`

It does the same thing with positive margins.

I'm using Win 7 64 bit and Sublime Text as editor. I've created an issue for this in SASS github as well.

**Comment by nex3** [comment]
This is definitely a Sass issue, not a Compass issue, so I'm closing it here.
