### ISSUE TITLE
Undefined mixin 'single-transition' v0.12.rc.1

### ISSUE THREAD

**Issue by DavidOliver** [Compass/compass#745]
```
+single-transition(all, 0.4, ease, false)
```

gives me:

```
Syntax error: Undefined mixin 'single-transition'
```

**Comment by DavidOliver** [comment]
Apologies. I realised there was a separate compass watch process running, and I didn't have the `s` for seconds. Seems to be fine now.

**Comment by chriseppstein** [comment]
wierd. That message would not have come from missing the `s`. Were you missing an `@import` statement?

**Comment by DavidOliver** [comment]
No, `@import` was there, and another mixin was working.

I think (but am not totally sure) it was to do with me using RVM, with varying Gem sets. I'd previously run a launcher for the `watch` command, and when running `watch` again from the command line Compass was behaving inconsistenly, sometimes not picking up on changes or compiling with line number comments even though I'd turned them off in my projects config.rb. I then searched for processes called compass - there was one. After killing it (and noticing the missing `s`), things seemed fine again.
