### ISSUE TITLE
Compass watch silenty crashes (0.11.7)

### ISSUE THREAD

**Issue by billyvg** [Compass/compass#747]
Compass watch "silenty" crashes -- it seems random, not sure how to debug and provide a more helpful ticket.  It crashes without any errors, and nothing in terminal.  

OS is OSX 10.7.3

**Comment by chriseppstein** [comment]
Ruby rarely "silently" crashes. can you run compass with the `--trace` option set? I'm on the same OS version and have never experienced this.

**Comment by billyvg** [comment]
Crashes have seemed to stop since upgrading to 0.17rc1 -- however if I'll start running with --trace, thanks!
