### ISSUE TITLE
Calling the config file config.rb is not optimal

### ISSUE THREAD

**Issue by e0da** [Compass/compass#751]
Something like `Compassfile` or `compass.rb` would be better. If I follow the most common practices, I'm putting a config.rb file in my project root. That seems like it would have a high incidence of collision with other project files.

**Comment by chriseppstein** [comment]
As seen here: https://github.com/chriseppstein/compass/blob/stable/lib/compass/configuration/helpers.rb#L136

You can use any of the following names (the first found in this order will be used):
- `config/compass.rb`
- `.compass/config.rb`
- `config/compass.config`
- `config.rb`
- `src/config.rb` (for legacy support -- don't use this)

**Comment by scottdavis** [comment]
It can be called compass.rb also

**Comment by chriseppstein** [comment]
@scottdavis Well you can call it anything you want with the `-c` option but that is not one of the paths we recognize by default.

**Comment by e0da** [comment]
That's great news! Clearly, I was mistaken. I really appreciate your response.
