### ISSUE TITLE
Sprite direction

### ISSUE THREAD

**Issue by aleksandargosevski** [Compass/compass#760]
Hello.

Is it possible to change the direction of icons inside sprite from y-axis to x-axis?

I have a problem. When I have title with 2 rows, on more icon inside sprite is loaded. You can see example on http://d.pr/E89r

Is there any other css solution, or I must to change direction of icons inside sprite?

**Comment by chriseppstein** [comment]
If you install the pre-release you can set the sprite layout to horizontal. 

```
gem install compass --pre
```

http://beta.compass-style.org/help/tutorials/spriting/sprite-layouts/

**Comment by aleksandargosevski** [comment]
Thank you very much. You are great.
