### ISSUE TITLE
Add tint and shade functions

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#770]
These appear to be quite popular and are fairly trivial.

**Comment by barraponto** [comment]
I have set up a comparison of lighten(), scale-color() and mix(): http://barraponto.blog.br/tryscale/tryscale.html
Here is the SCSS I wrote for the comparison, might be useful to integrate in the docs: https://gist.github.com/211d390300a011c0be3a/962774d6ba38f968ca5e52ce9e6f58745912c7a4

**Comment by mirisuzanne** [comment]
I've been using this:

https://gist.github.com/2023622

I based it off http://pastie.org/1230161 by Josh Goebel - but moved it into Sass. We might want to add units to that (%) or switch to a 0 -> 1 system. Not sure.

**Comment by jhilden** [comment]
So, what is the current state and the plan for this?

**Comment by chriseppstein** [comment]
just needs to get built.

**Comment by chriseppstein** [comment]
and by built I mean, documented and tested too.

**Comment by jhilden** [comment]
I could take a stab at it.  I guess the functions would live in Compass Color Helpers (http://compass-style.org/reference/compass/helpers/colors/), yes?

**Comment by chriseppstein** [comment]
Yep!

**Comment by jhilden** [comment]
Thanks for merging my patch.  I think this issue can be closed now.
