### ISSUE TITLE
rack, sprockets, compass

### ISSUE THREAD

**Issue by paolochiodi** [Compass/compass#772]
Hi, I may need some help.

I just created a simple rack app that is serving stylesheets through sprockets, and I'm using compass as in https://gist.github.com/2022093 (relevant part only)

Everything is working ok, except when I try to do @import "sprite/*.png";

"sprite" folder is located in public/images and compass version 0.12

thank you

**Comment by paolochiodi** [comment]
ops, i forgot to point out the error:

Sass::SyntaxError: File to import not found or unreadable: sprite/*.png

**Comment by scottdavis** [comment]
you need something that will tie sprockets and compass together there is a sass-sprockets i think

**Comment by scottdavis** [comment]
also what you have in your gist isn't going to work since the compass sass extension are not getting loaded

**Comment by paolochiodi** [comment]
thank you for the quick answer... coming from rails applications I were not aware of sprockets-sass.
how can get the compass sass extension to load?

**Comment by paolochiodi** [comment]
btw, adding sprockets-sass the error is different: 
Sass::SyntaxError: File to import not found or unreadable: utilities/color
Load paths:
  /Users/chiodi84/.rvm/gems/ruby-1.9.3-preview1@redmoon/gems/compass-0.12.0/frameworks/blueprint/stylesheets
  /Users/chiodi84/.rvm/gems/ruby-1.9.3-preview1@redmoon/gems/compass-0.12.0/frameworks/compass/stylesheets
  Compass::SpriteImporter

**Comment by paolochiodi** [comment]
never mind, I solved removing the line 
assets.append_path(File.join(compass_gem_root, 'frameworks', 'compass', 'stylesheets'))

it seem it is better to leave sprockets-sass alone in charge of managing sass and compass

**Comment by chriseppstein** [comment]
Someone should write a compass-sprockets gem. All the knowledge for how to do this can be found in the compass-rails gem.

**Comment by paolochiodi** [comment]
sprockets-sass claims "Automatic integration with Compass" as a feature, and for me is working well
