### ISSUE TITLE
Several ressources folders

### ISSUE THREAD

**Issue by Anahkiasen** [Compass/compass#781]
I'm using Compass as part of a self-coded framework. In that framework there can be several structures for the assets folder but for the biggest projects it goes like this :

```
assets
    framework
        css
        img
        js
        sass

    template1
        css
        coffee
        img
        js
        sass
```

framework refers to the file proper to the framework itself, needed librairies and base stylesheet for error codes etc.
template1 is one of what can be many template folders, one for each possible design for the current website

As you can see my main problem is that I don't have one css_dir nor one img_dir, I have serveral. And while you can set several sass_dir via the additional_import_paths variable, you can't do the same for the rest.

For the moment the only way I'm using compass is via the --compass flag of the sass gem. But that's missing on a lot of the great aspects of Compass.
My question is the following : is there - or would it be possible to add - some way to define several import/export paths by setting the whole thing via an array ? There has to be a way to use Compass on some bigger scale projects than just one css/sass folder.

Like you have you css_dir, sass_dir, img_dir etc. variables set, and then you set a main array like this `[assets/framework, assets/template1]` and it executes Compass in each of these folders basing itself on the defined variables (assets/framework/img_dir, assets/framework/sass_dir, etc/).

The point being that you can use the img_path functions and all and it would go looking for images in the respectives img folders.

**Comment by chriseppstein** [comment]
Better to just have two compass projects in this case. Or you can introduce a common parent folder.

I just can't justify introducing this complexity to the project for such a rare use case.

**Comment by Anahkiasen** [comment]
Can I have different config files in one folder and load each one individually when I need ?

**Comment by chriseppstein** [comment]
yep. you can just be in that directory or you can pass the `-c` option to compass to tell it where your configs are.

**Comment by Anahkiasen** [comment]
Ok, I made a little bit in my framework that generates a config.rb in each template folder and then I just `compass watch` when I work on one. Perfect, thanks :)
