### ISSUE TITLE
One click installer - thats a lot of percents!

### ISSUE THREAD

**Issue by kaelig** [Compass/compass#784]
Here is a link to a screenshot of the installer showing more than 100% completion: http://dl.dropbox.com/u/72735/temp/Capture%20d%E2%80%99%C3%A9cran%202012-03-14%20%C3%A0%2014.07.53.png

This happened during the install.

Config: OS XLion (latest), macbook pro core i7, rvm installed.

**Comment by chriseppstein** [comment]
Thanks. I noticed that too and already filed a bug on the tool I used to build the package: https://github.com/wagenet/packager/issues/7
