### ISSUE TITLE
mother-effing hyphenation

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#788]
http://blog.kenneth.io/blog/2012/03/04/word-wrapping-hypernation-using-css/

Get in my library.

**Comment by nickcooley** [comment]
Added with [bbdd701]    

Chris, please let me know if you had something else in mind for this... 

Thanks,

**Comment by ry5n** [comment]
@nickcooley You beat me to this! One thing I was considering was whether there should be some way to have word-break without hyphenation, and possibly (?) the other way round, eg. bare urls in a hyphenated passage probably should break, but hyphenation would be bad… I think I would have leaned to two mixins, +word-break and +hyphens, named the same as the css props, and maybe a third to include them both? @chriseppstein?

**Comment by nickcooley** [comment]
Ryan -- 

Thx for the feedback!  Much appreciated!  So, the initial inspiration for the mixin was blog post listed above.  I think you make a really good point though and that is to create mixins for the lower level elements as well... I'll get cracking on that (as well as adding other mixins based on the CSS Text Level 3 spec while I'm at it: http://www.w3.org/TR/css3-text/#word-break).  

To stay consistent with the spec, I may rename the partial to "_text" as all of these features fall under the CSS3 "Text" spec.

Thoughts on that?

**Comment by ry5n** [comment]
@nickcooley Awesome! Let me know if I can help further. As for where this should go in Compass, it’s Chris’ call.

**Comment by nickcooley** [comment]
@chriseppstein -- Do you have any thoughts about where this fits into existing mixin structure?  Technically, like I said, word-breaks and hyphenation is all part of the CSS Text Lvl3 spec.  But so are things like text-shadow (which has its own mixin.) or text-outline which technically could fall into it too...

**Comment by chriseppstein** [comment]
where you have it seems ok

**Comment by ry5n** [comment]
@chriseppstein Should this be closed now that it's been committed? @nickcooley Was there more work to do on this?

**Comment by nickcooley** [comment]
@ryanfrederick -- I didn't have any further activities to complete this ticket, so IMO once it was committed, the issue can be closed -- Obviously I will defer to @chriseppstein on that though.

Thanks,
nc
