### ISSUE TITLE
inline-block mixin (and others) should also respect "$experimental-support-for-..." settings

### ISSUE THREAD

**Issue by okonet** [Compass/compass#794]
Right now even if 

$experimental-support-for-mozilla: false

the mixin produces -moz specific rules such as:

display: -moz-inline-box;
-moz-box-orient: vertical;

**Comment by scottdavis** [comment]
mind making a patch?

**Comment by okonet** [comment]
Sure! Will submit soon.

## 

Sincerely yours,

Andrey Okonechnikov

@okonetchnikov
http://okonet.ru

**Comment by ry5n** [comment]
@okonet Hey! Just skimming through the queue and it looks like this has been taken care of (patched and merged). Would you mind closing the issue if that's the case? Thanks!
