### ISSUE TITLE
Span mixin deprecation warnings for Blueprint grid

### ISSUE THREAD

**Issue by billsaysthis** [Compass/compass#796]
Using @import "blueprint/grid" should not generate deprecation warnings as I see (in 0.12 and 0.12.1), as shown below. This may only be a warning but its annoying to see on every compile and makes it harder to see errors or warnings coming from my code.

```
WARNING: The span mixin is deprecated. Please use the span function instead. E.g. width: span(6)
         on line 123 of /Users/billlazar/.rvm/gems/ruby-1.9.3-p125/gems/compass-0.12.1/frameworks/blueprint/stylesheets/blueprint/_grid.scss, in `span'
```

**Comment by chriseppstein** [comment]
It was deprecated in 0.11 actually. https://github.com/chriseppstein/compass/commit/136954561f1c541f19549dde962c81a310c276bb

**Comment by billsaysthis** [comment]
I see, thought this was coming from the gem but now I see better. Sorry for the interruption.
