### ISSUE TITLE
Enable 3d transform prefixes for -ms- and -o-

### ISSUE THREAD

**Issue by paulirish** [Compass/compass#797]
As discussed in #793 : https://github.com/chriseppstein/compass/pull/793#issuecomment-4527675

> I would suggest enabling the opera and MS prefixes.
> 
> Opera will probably end up not shipping with a prefix. But better safe than broken.
> 
> IE announced their 3d transform support so http://blogs.msdn.com/b/ie/archive/2012/02/02/css3-3d-transforms-in-ie10.aspx unless you want this stuff to fail in IE10 it should definitely be added.

Assigned to you, @ai  :)

**Comment by ai** [comment]
Opera 12 doesn’t use 3D transformations. In caniuse.com http://caniuse.com/transforms3d 12 alpha-version is marked as unknow, but in Opera dev changelog only WebGL in annonced http://my.opera.com/ODIN/blog/2011/10/13/opera-12-alpha-released

**Comment by ai** [comment]
I already add `-ms-` prefix in `moz3d` branch 439959d47d3d3c1cda48f189e04c2b04922ad16a

**Comment by paulirish** [comment]
I dont understand. you're saying you want everyone that uses compass now to not have Opera compatibility?

People are not going back to update their compass and recompile their stylesheets when Opera announces their support.

The only responsible thing to do is to use the o prefix until either Opera sunsets it or they announce they'll just use the unprefixed version.

**Comment by ai** [comment]
Ouh, there is really something wrong with prefixes :). Main idea behind prefixes is allow browser to have issues in their properties. Opera may have different implementation, when release 3D transform. Or willn’t have any 3D tranform. Or will read non-prefixed version (they do this very often, because they popular only in Norway and Russian developers). So if we implement it now, result CSS maybe broken for Opera.

Anyway, I understand your opinion and add Opera commit soon.

**Comment by ai** [comment]
And why noone didn’t pull `-moz-` prefix commit? There are any problem with `-moz-` and Mozilla? Nope ;)

**Comment by ai** [comment]
Also, why Compass have `experimental` mixin with custom list of prefixes. By your logic every css3-mixin should use every prefixes for future.

**Comment by ai** [comment]
OK, I add `-o-` prefix 436a2575e13892d4735aa772fb4aa335adee75c0

But I still think that is like a become a criminal, because current laws (browser prefix policy) is bad.

**Comment by paulirish** [comment]
> Ouh, there is really something wrong with prefixes :)

[I agree.](http://paulirish.com/2012/vendor-prefixes-are-not-developer-friendly/)

> By your logic every css3-mixin should use every prefixes for future.

Yup. They should. :)  We should only deprecate use of prefixes on an opt-in basis, but never opt-in to using them.

cc @chriseppstein @scottdavis 

Thx @ai

**Comment by miketaylr** [comment]
+1 (from a flight heading to Norway right now). 3D is on our roadmap so adding them now will save headaches in the future.

**Comment by ai** [comment]
@miketaylr answer from Opera – very cool! :)

**Comment by scottdavis** [comment]
merged

**Comment by chriseppstein** [comment]
I merged this to stable and it will be released in 0.12.2.
