### ISSUE TITLE
"compass --boring" still outputs color control strings

### ISSUE THREAD

**Issue by bangpound** [Compass/compass#80]
I don't know what these strings are called, but I can see them when I run compass from a web application that can't handle the color information. The --boring option does work (in that it doesn't return an error), but it doesn't turn off all the color.

[compass --boring in my web app](http://skitch.com/bangpound/ntcba/compass-boring)  
[compass --boring from my terminal](http://skitch.com/bangpound/ntcnj/terminal-bash-95x25)

color_output = false worked in pre3 perfectly, but now it behaves identically to --boring.

**Comment by chriseppstein** [comment]
What version of compass is installed? pre5 ?

**Comment by bangpound** [comment]
gem list:
compass-0.10.0.pre5

output from compass -v:
Compass 0.10.0 [9503512]
Copyright (c) 2008-2009 Chris Eppstein
Released under the MIT License.

**Comment by chriseppstein** [comment]
Yep, I missed a place in the code. This commit fixes it:
http://github.com/chriseppstein/compass/commit/1eef589c29c86672174ee3c27f7450cd6d7ac91e

expect this fix in the next release.
