### ISSUE TITLE
[Sprites] Layout: smart with repeating sprite

### ISSUE THREAD

**Issue by jurriaan** [Compass/compass#804]
If sprites layout is set to smart. Compass ignores the repeat-x setting.

I have something like this in my stylesheet:

$icon-layout: smart;
$icon-background-repeat: repeat-x;

Without the first line it stretches the background perfectly..

Is this the expected behavior?

**Comment by scottdavis** [comment]
Yes smart ignores all configuration

**Comment by scottdavis** [comment]
http://compass-style.org/help/tutorials/spriting/sprite-layouts/
