### ISSUE TITLE
Sprite output folder

### ISSUE THREAD

**Issue by Anahkiasen** [Compass/compass#809]
I can't seem to set properly the sprite output folder. My folder organization is the following :

```
assets
    css
    img
    sass
```

From a stylesheet in sass/ I'm taking images from img by doing `@import ../img/*.png` to output them as a sprite. The problem is, although the documentation says the sprite should be default output to `<img_folder>` (here set to "img"), the created .png keeps getting saved in assets/
Am doing something wrong or something ?

**Comment by Anahkiasen** [comment]
Helluw ?

**Comment by agross** [comment]
Try setting `generated_images_path` and `http_generated_images_path` in your compass config.

**Comment by HNygard** [comment]
Have a look a my config.rb in #951. I'm setting `generated_images_dir` and `http_generated_images_path` to get the sprites in the correct folder and to get path in the CSS file correct.

**Comment by jhilden** [comment]
@Anahkiasen could the provided answers fix your issue?
