### ISSUE TITLE
bang-hack has logic reversed

### ISSUE THREAD

**Issue by mrajcok** [Compass/compass#81]
If http://www.webdevout.net/css-hacks#in_css-important is correct, then it appears the bang-hack mixin http://github.com/chriseppstein/compass/blob/master/frameworks/compass/stylesheets/compass/utilities/general/_hacks.sass
has the logic reversed.  IE6 will _not_ let the !important property win, whereas other browsers _will_ let it win. 
I would also suggest that the normal value come before the IE6 value in the list of arguments.  Suggested rewrite:

//**
  IE6 (and below) will ignore the !important property
  while all the other browsers won't.
  TODO: link to blog post
=bang-hack(!property, !value, !ie6_value)
  #{!property}: #{!value} !important
  #{!property}: #{!ie6_value}

Maybe also consider renaming it ie6-bang-hack so that we know what browser the hack is targeting... although the "ie6_value" parameter name is probably sufficient.

**Comment by chriseppstein** [comment]
Good catch. Looks like I screwed that up. I'd rather not rename the mixin, but the other changes you suggested look good. Would you like to submit a patch?

**Comment by chriseppstein** [comment]
merged into .pre6
