### ISSUE TITLE
Possible to add sprite mixin to support sliding doors?

### ISSUE THREAD

**Issue by ghost** [Compass/compass#813]
I am using Compass 0.12.1 and am loving it so far :)

I am almost successful in implementing [sliding door buttons](http://filamentgroup.com/lab/update_styling_the_button_element_with_css_sliding_doors_now_with_image_spr/) with sprites:

```
$buttons-sprite-dimensions: true;
$buttons-spacing: 30px;
@import "buttons/*.png";
@include all-buttons-sprites;

ul .button{
  @extend .buttons-left;
} 

ul .submit input{
  @extend .buttons-right;
  //some other styles
}
```

Compass is able to generate sprites with background positions:

```
.buttons-right {
  background-position: 0 0;
  height: 38px;
  width: 316px;
}
```

This is nice, but for the sliding doors to work, I need to be able to set:

```
background-position: right 316px;
```

Does compass have a way to extract the individual values of the background-position property for a sprite image?

**Comment by hagenburger** [comment]
Add before `@import ...`:

```
$buttons-right-position: 100%;
```

Use instead of `@extend .buttons-right;`:

```
@include buttons-sprite(right, $offset-x: 100%);
```

Btw. never use `right 316px`, prefer `100% 316px`.

**Comment by ghost** [comment]
That works perfectly :)

Could you link me to documentation for  <sprite-map>-sprite()? I couldn't find it anywhere.

**Comment by hagenburger** [comment]
Actually this seems to be missing. You’ll find the few options in the code:

https://github.com/chriseppstein/compass/blob/stable/lib/compass/sprite_importer/content.erb#L69
