### ISSUE TITLE
Generated Sprite ignores Configuration variables

### ISSUE THREAD

**Issue by avclark** [Compass/compass#817]
I cannot figure out why this is happening. My sprites get generated fine, but all the configuration variables are ignored. 

Here's my code: 

$sub-nav-layout: horizontal;
$sub-nav-spacing: 10px;
@import "sub-nav/*.png";
@include all-sub-nav-sprites;

Am I missing something?

Thanks.

**Comment by scottdavis** [comment]
I just implemented global spacing on master over the weekend

**Comment by avclark** [comment]
Why would the layout variable not work? Also, do I need to update compass then?

Thanks.

**Comment by avclark** [comment]
Also (I'm still new to this), how do I update to the latest version from github?

**Comment by scottdavis** [comment]
What you have should work using the latest compass from git (master)

**Comment by avclark** [comment]
I just updated via "gem install compass --pre" and I now have compass 0.12.rc.1. However, it seems to still be ignoring the spacing variable when creating the sprite.

**Comment by scottdavis** [comment]
the easiest way would be to use http://gembundler.com/ and git http://gembundler.com/git.html

**Comment by avclark** [comment]
Thanks. So you're saying that with the version of Compass I am running, the spacing will not work?

**Comment by scottdavis** [comment]
Correct

**Comment by avclark** [comment]
Thanks for the help. I must be doing something wrong. I've successfully updated to compass to the latest master from github, however, this code still does not work: 

$sub-nav-spacing: 10px;
@import "sub-nav/*.png";
@include all-sub-nav-sprites;

Any ideas?

Thanks.

**Comment by avclark** [comment]
I got it to work. Another mixing I was using was causing a conflict. Thanks for the help.

**Comment by scottdavis** [comment]
np
