### ISSUE TITLE
Imported files not always ending up in compiled result

### ISSUE THREAD

**Issue by roytomeij** [Compass/compass#818]
Sorry for the shitty title.

In my modular approach I have an `application.css.sass` in a Rails 3.2.1 which imports a bunch of partials, for variables, modules, etc. My `application.css.sass` looks like this:

```
@import "base/variables"
@import "base/compass_framework"
@import "base/mixins"
@import "generic/*"
@import "modules/*"
```

This works well _most of the time_. Sometimes newly added files inside the modules directory (e.g. `modules/_foo.css.sass`) aren't added at all to the compiled result, and sometimes changes made to existing files aren't included. There doesn't seem to be a way to fix this, but what seems to "help" is restarting Thin, remove a `"` somewhere in `application.css.sass` to trigger an error and then fix the error. That often means spending 5 minutes to see a change, after first trying to figure out what _I_ did wrong.

As @scottdavis said on Twitter, it might be Sprockets & depend_on. I myself have absolutely no clue (what else is new).

**Comment by roytomeij** [comment]
Also, this one should probably have been in the compass-rails project. Also 2, I was still running on version 1.0.0.rc2 of compass-rails. Let's see how things work out on 1.0.1 ;)

**Comment by scottdavis** [comment]
@roy you may want to file this on sass rails since that is where the glob importer is

**Comment by jhilden** [comment]
We are having the same issue.  Where could I track progress on this?

**Comment by scottdavis** [comment]
@roy did you make an issue on sass-rails?

**Comment by roytomeij** [comment]
No, I was too lazy. Not sure if this problem still existed in newer versions of sass-rails though. Which version are you using, other person with issues (sorry, via mail so no thread)?

**Comment by jhilden** [comment]
It occured in version 3.2.4 and the remedy was to change something in the `application.css.sass` in order for it to reload.  Updating to 3.2.5 now to see if it still happens.
