### ISSUE TITLE
Changes to come ?

### ISSUE THREAD

**Issue by Anahkiasen** [Compass/compass#822]
In another issue you said the gradients syntax (or background-image syntax in general) was supposed to be changed in the future. I just wanted to know if you could give more details on this since I was supposed to code an ensemble of shortcuts for basic gradients, and I wouldn't want to do something that will be done in the short future or that will have to be remade.
That applies to a lot of ideas I have for Compass recipes, so is there some details you can give on changes to expect to Compass in the near future ?

**Comment by scottdavis** [comment]
The `@include background(linear-gradient($some-color, $other-color));` is the new and supported syntax for gradients in the future questions like this are better asked on the google group: http://groups.google.com/group/compass-users

**Comment by scottdavis** [comment]
The `@include background(linear-gradient(...` format is the new gradient format going forward with 0.12.x. In the future questions like this are better posted on the google group: http://groups.google.com/group/compass-users
