### ISSUE TITLE
"No application integration exists for rails"

### ISSUE THREAD

**Issue by EthanMichaels** [Compass/compass#823]
Installed Compass Gem by adding "compass" to my Rails project gemfile and running `bundle install`.

I have this version:

```
$ bundle exec compass version
Compass 0.12.1 (Alnilam)
```

Try to follow instruction on [this page](http://compass-style.org/help/) of the compass website to perform the "Rails Setup" "Using Blueprint with Rails".

```
$ bundle exec compass init rails ~/path/to/my/project --using blueprint
No application integration exists for rails
```

**Comment by chriseppstein** [comment]
You need the  `compass-rails` gem

**Comment by scottdavis** [comment]
You need to use the compass-rails gem

**Comment by atroche** [comment]
I've installed the compass-rails gem, and I'm still getting this error. Any clues?

**Comment by chriseppstein** [comment]
are you bundle exec'ing?

**Comment by chanced** [comment]
Yea, I'm getting the same problem and I am bundle exec'ing.

**Comment by atroche** [comment]
I solved it by putting 'compass' and 'compass-rails' in the 'assets'
group in my Gemfile.

On 17 April 2012 21:00, Chance
reply@reply.github.com
wrote:

> Yea, I'm getting the same problem.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/chriseppstein/compass/issues/823#issuecomment-5184396

## 

-- Alistair

**Comment by chanced** [comment]
Yep, that worked for me too. I didn't even recognize that the project/gemfile was missing an assets group.

Thanks man!

**Comment by lrsbt** [comment]
I removed the "gem 'compass-rails'" from my config file and it disappeared.

**Comment by stoikerty** [comment]
I had the same problem, was getting "No application integration exists for rails" when typing "compass watch ." even with the compass-rails gem installed under the assets group.
My config/compass.rb only contains the line "project_type = :rails" and after various tries of bundling and initializing new compass projects I was still getting the same message.

[Luckily](https://groups.google.com/forum/?fromgroups=#!topic/compass-users/oaI4meEp9Hs) I found out that running **"bundle exec compass watch"** instead, does work.

**Comment by scottdavis** [comment]
`bundle exec compass watch` this is the correct command with compass-rails

**Comment by kimchouard** [comment]
I'm getting the `No application integration exists for rails` error on running `bundle exec compass watch` with Rails 4 and v2.0.alpha.0. Unless I put my compass and compass-rails gem into the assets group... Is it normal even for a Ruby 4 app?

Tks scott though! :+1:

**Comment by scottdavis** [comment]
@kimchouard file a bug on compass the compass executable was rigged to require an assets group
