### ISSUE TITLE
Broken sass dependency

### ISSUE THREAD

**Issue by vad** [Compass/compass#825]
With sass 3.1.1 i got the following error using the transition-property mixin:

```
error src/screen.scss (Line 126 of _transition.scss: "index(all, transform-origin)" is not a number for `nth')
```

I updated sass to 3.1.15 and everything works. It works on 3.1.7 too.

ATM compass depends on sass 3.1, but 3.1.1 is broken.

**Comment by darlanalves** [comment]
This bug is fixed in 0.12.2 version
