### ISSUE TITLE
PNG Generation

### ISSUE THREAD

**Issue by Anahkiasen** [Compass/compass#829]
I just wanted to know if there was any mixin or function in SASS to do rgba(black, .2) and it generates a 1x1 20% opacity black pixel. I know about [compass-rgbapng](https://github.com/aaronrussell/compass-rgbapng) but it looks pretty much abandoned and since Lemonade was integrated into Compass, I was wondering if rgbapng was in Compass somewhere under a name I wouldn't have thought about.
In my mind that's an incredibly useful function, it brings the flexibility and easiness of using rgba() and fade functions without having to worry about older browsers choking on it.

**Comment by scottdavis** [comment]
i don't really have any older brothers to choke on it

**Comment by Anahkiasen** [comment]
Ahahaha. Dammit. Sorry.

**Comment by chriseppstein** [comment]
There is this plugin -- I use it with great success: https://github.com/aaronrussell/compass-rgbapng

**Comment by Anahkiasen** [comment]
I know, I'm quoting it in the main post. I'm just asking why after two years it's still not part of Compass, I mean it's a simple mixin, very useful, half of it is already in Compass (inline data). Is there a particular reason or ?

**Comment by chriseppstein** [comment]
Ah sorry -- only skimmed the original post. I like having lots of plugins that people are proud of making, not every good thing that people make needs to become core. We just need to make it easier to discover and install plugins.

**Comment by Anahkiasen** [comment]
Fair enough ; a better way to find and update plugins would be nice indeed. It's just that when like me you use several plugins on a lot of different computers it's always kind of a drag to install, manage and update everything everytime, so when I can try and slip one of those plugins into the core, you know...
