### ISSUE TITLE
The installer script needs fixing

### ISSUE THREAD

**Issue by anshul** [Compass/compass#83]
[This wiki page](http://wiki.github.com/chriseppstein/compass/ruby-on-rails-integration) recommends  using this [installer script](http://compass-style.org/rails/installer) for integrating compass with a rails install.  Running this script with `960` as framework results  in the following lines in `config/environment.rb`

```
  config.gem 'compass-960-plugin', :lib => 'ninesixty'
  config.gem 'compass', :version => '>= 0.8.17'
```

This results in compass being required twice via different paths and creates a warning while running `script/generate`.   This can be resolved by calling these gems in the reverse order.

**Comment by chriseppstein** [comment]
I think this is a side effect of how the installer works. I took the 960 plugin support out. we'll have a better solution for plugins in v1.0.
