### ISSUE TITLE
File to import not found or unreadable: compass/css3 with rc1

### ISSUE THREAD

**Issue by tvdeyen** [Compass/compass#830]
I just updated from v0.12.alpha.4 to v0.12.rc.1 and suddenly `@import "compass/css3";` doesn't work anymore.

Downgrading (Upgrading to a more familiar experience ^_^) to v0.12.alpha.4 fixes this.

Using a Rails 3.1.3 project with sass-rails 3.1.5 and compass using:

`gem 'compass', :git => 'git://github.com/chriseppstein/compass.git', :tag => 'v0.12.rc.1'` in my `Gemfile`

**Comment by chriseppstein** [comment]
Compass 0.12 is fully released now. no need to use git. but you do need to use the new [compass-rails gem](https://github.com/compass/compass-rails). Please follow the instructions there.

**Comment by tvdeyen** [comment]
Ok, that works. Great. Thanks
