### ISSUE TITLE
'Smart' sprite layout doesn't work for me.

### ISSUE THREAD

**Issue by enagorny** [Compass/compass#831]
I'm new compass user. And I'm trying to use sprite plugin. It works, but generating always vertical layout sprite and omits 'smart' config.

``` sass
@orange-layout:smart
@import "orange/*.png"
@include all-orange-sprites

```

I'll try to generate it by command `compass compile test`

But it doesn't work for me. I'm still receiving 'vertical' sprite.

Either it doesn't work or it is error in the tutorial http://compass-style.org/help/tutorials/spriting/sprite-layouts/

**Comment by hagenburger** [comment]
Try `$` instead of `@`:

```
$orange-layout: smart
```

**Comment by enagorny** [comment]
Awesome. Thanks. It works!
(Sorry for posting it here.)

**Comment by scottdavis** [comment]
$orange-layout:smart;
