### ISSUE TITLE
Iconv deprecated

### ISSUE THREAD

**Issue by kud** [Compass/compass#835]
Everytime I compile, I've got this error:

```
Users/xxx/.rbenv/versions/1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': iconv will be deprecated in the future, use String#encode instead.
```

**Comment by kud** [comment]
**\* LOCAL GEMS ***

actionmailer (3.2.3)
actionpack (3.2.3)
activemodel (3.2.3)
activerecord (3.2.3)
activeresource (3.2.3)
activesupport (3.2.3)
albino (1.3.3)
annotate (2.4.1.beta1)
arel (3.0.2)
bcrypt-ruby (3.0.1)
bigdecimal (1.1.0)
bootstrap-sass (2.0.0)
bootstrap-will_paginate (0.0.5)
builder (3.0.0)
bundler (1.1.3)
capybara (1.1.2)
childprocess (0.3.1)
chunky_png (1.2.5)
classifier (1.3.3)
coffee-rails (3.2.2)
coffee-script (2.2.0)
coffee-script-source (1.2.0)
compass (0.12.1)
devise (2.0.4)
diff-lcs (1.1.3)
directory_watcher (1.4.1)
erubis (2.7.0)
execjs (1.3.0)
factory_girl (2.3.2)
factory_girl_rails (1.4.0)
faker (1.0.1)
fast-stemmer (1.0.0)
ffi (1.0.11)
fssm (0.2.8.1)
hike (1.2.1)
i18n (0.6.0)
io-console (0.3)
jekyll (0.11.2)
journey (1.0.3)
jquery-rails (2.0.2, 2.0.1, 2.0.0)
json (1.6.6, 1.5.4)
kramdown (0.13.5)
liquid (2.3.0)
mail (2.4.4)
maruku (0.6.0)
mime-types (1.18)
minitest (2.5.1)
multi_json (1.2.0)
nokogiri (1.5.2)
orm_adapter (0.0.7)
pg (0.12.2)
polyglot (0.3.3)
posix-spawn (0.3.6)
rack (1.4.1)
rack-cache (1.2)
rack-ssl (1.3.2)
rack-test (0.6.1)
rails (3.2.3)
railties (3.2.3)
rake (0.9.2.2)
rdoc (3.12, 3.9.4)
rspec (2.9.0)
rspec-core (2.9.0)
rspec-expectations (2.9.0)
rspec-mocks (2.9.0)
rspec-rails (2.9.0)
rubygems-update (1.8.21)
rubyzip (0.9.6.1)
sass (3.1.15)
sass-rails (3.2.5, 3.2.4)
selenium-webdriver (2.20.0)
sprockets (2.1.2)
sqlite3 (1.3.5)
syntax (1.0.0)
thor (0.14.6)
tilt (1.3.3)
treetop (1.4.10)
tzinfo (0.3.32)
uglifier (1.2.4, 1.2.3)
warden (1.1.1)
will_paginate (3.0.3)
xpath (0.1.4)

**Comment by kud** [comment]
```
$ rbenv versions                                                                                                                 
* 1.9.3-p0 (set by /Users/xxx/.rbenv/version)
```

**Comment by chriseppstein** [comment]
Must be a Sass issue. Sass handles all the i18n stuff. Can you file the bug over there?

**Comment by kud** [comment]
Sure, thank you for your support. ;)
