### ISSUE TITLE
colborder mixin should include change for box-sizing

### ISSUE THREAD

**Issue by chrissloan** [Compass/compass#841]
Just ran into this with FF and IE using colborder mixin for blueprint grid. When zooming in with browser on a floated column using colborder, the floats break because the box-sizing was still set to standard box-model. Instead, it might be helpful to override this within the mixin by outputting something like:

box-sizing: border-box;
-moz-box-sizing: border-box;
-ms-box-sizing: border-box;
-webkit-box-sizing: border-box;

**Comment by chriseppstein** [comment]
Compass is a port of blueprint, not a fork. Changes need to start with blueprint.
