### ISSUE TITLE
Vertical Rhythm mixins should allow unit-less line-heights

### ISSUE THREAD

**Issue by timkelty** [Compass/compass#845]
Why? Cause unit-less line heights are better!

It appears that the vertical rhythm mixins don't really allow for setting a unit-less line-height, which is always my preference of the time, and has been for a long time.

It seems I'm not alone in this:
http://meyerweb.com/eric/thoughts/2006/02/08/unitless-line-heights/
http://www.lifeathighroad.com/web-development/css-web-development/using-a-unitless-line-height-to-enhance-your-typography/
https://developer.mozilla.org/en/CSS/line-height#Avoid_unexpected_results.2C_use_unitless_line-height!

I'll can fork and change this when I get time, but as a long time Compass user, but first time `compass/typography/vertical_rhythm` user, I was surprised this didn't work. Until then I'll continue rolling my own vertical rhythm settings.

Surely I can't be alone here?

**Comment by mirisuzanne** [comment]
You're not alone in wanting unitless line-heights, but the purpose of doing that is so contrary to the purpose of vertical-rhythms that we didn't combine them. Unitless line-heights ensure that your rhythm will change with the font-size. This module ensures that they don't.

That said, maybe it's time for the type module to have more than simply vertical-rhythms. What exactly do you need to accomplish?

**Comment by timkelty** [comment]
You're right, I guess if I'm using unitless line-heights, the vertical-rhythms module isn't really what I need.

I wasn't really trying to accomplish anything specific, I just hasn't used it yet and was looking for a standardized way to set/reset heights and define things in terms of lines of text.

I suppose for now I'll just use the $base-font-size and $base-line-height vars and stick to my own stuff. I noticed there were a couple of recipes for sizing in rems, maybe I'll check that out.

**Comment by mirisuzanne** [comment]
Makes sense. Let us know if you do write some mixins that are useful in your use case, I'd be glad to see them.
