### ISSUE TITLE
background:-moz-element(#element);

### ISSUE THREAD

**Issue by soluml** [Compass/compass#849]
Hey All,

On a project I'm trying to set the background of a div to an element on the page via <a href="https://developer.mozilla.org/en/CSS/-moz-element">-moz-element</a>.  When I compile the code I get an invalid CSS error.

Here's the line that's causing this issue: <code>background:-moz-element(#source) bottom left no-repeat;</code>

I believe this is Sass related, but just in case I wanted to send this your way as well.

Thanks guys, love what you do!

**Comment by chriseppstein** [comment]
You're right, this is a sass issue, we'll track it via the [issue you opened there](https://github.com/nex3/sass/issues/355).

**Comment by soluml** [comment]
Sounds good, thanks Chris!

For anyone who comes across this issue via Google search or something, here's a workaround using interpolation:
<code>
$moz:"-moz-element(#source) bottom left no-repeat";
background:#{$moz};
</code>
