### ISSUE TITLE
Sprites are defaulting to repeat not no-repeat

### ISSUE THREAD

**Issue by ramaboo** [Compass/compass#851]
Version 0.12.1

I have the following code in a sass file:

```
$admin-sprite: sprite-map('sprites/admin/*.png')

#foo
  background: sprite($admin-sprite, dashboard)
```

When I look at the generated stylesheet I see this:

```
#foo {
  background: url(/assets/sprites/admin-s483476d433.png) 0 -112px;
}
```

From the documentation http://compass-style.org/reference/compass/helpers/sprites/ I would have expected it to include no-repeat.

I tried passing in options for no-repeat but could not get any of them to work as expected.

David

**Comment by ajmorris** [comment]
I too am having this problem. Anyone got a way to get this to work?

**Comment by chriseppstein** [comment]
I am not seeing this. Can you make a small compass project that reproduces this issue and send it to me?

**Comment by MoOx** [comment]
It's true we can see `no-repeat` into compass source https://github.com/chriseppstein/compass/blob/stable/frameworks/compass/stylesheets/compass/utilities/sprites/_sprite-img.scss#L41
