### ISSUE TITLE
Firefox Ignores font-size in font_reset mixin.

### ISSUE THREAD

**Issue by farmdawgnation** [Compass/compass#852]
I'm talking about the mixin located here:
https://github.com/chriseppstein/compass/blob/stable/frameworks/compass/stylesheets/compass/reset/_utilities.scss#L69

It seems that when you specify `font-size` followed by `font`, Firefox ignores the shorthand property overrides the `font-size` property, causing it to be ignored, as shown by this Firebug screenshot:

![Example of Issue](https://www.dropbox.com/s/ee86qyctfi78nc0/ff11fontproperty.png?dl=1)

This was tested against Firefox 11, Windows and Mac versions. Let me know if I can provide you guys with any more details.

**Comment by mirisuzanne** [comment]
Thanks! Are you willing to do some tests and submit a patch?

I'd expect that to work if you switched the order of the two properties.

**Comment by farmdawgnation** [comment]
I am more than happy to do that!

**Comment by mirisuzanne** [comment]
Thanks again!

**Comment by farmdawgnation** [comment]
So, for some reason reversing these causes the `assert_renders_correctly` test to fail for blueprint. Any thoughts on that? Heh.

**Comment by mirisuzanne** [comment]
you're changing the output of a common mixin, so the change may show up in several tests. Check the css output files in the blueprint tests, and change the order of the expected output. Does that make sense?

**Comment by farmdawgnation** [comment]
Aha. I was wondering how you guys would check for correct rendering. Having a cached copy makes sense. Found it and changed and now that test is passing. I'll proceed to make sure the fix actually works in Firefox.

As a side point to this, I don't know if you're aware of this or not but the stable branch tests are currently throwing a stack size error as well. It was happening before my change so it wasn't introduced by me, but just thought you should know if you didn't already.

**Comment by mirisuzanne** [comment]
Care to file a bug about the failing test while you're at it? Thanks! :)

**Comment by farmdawgnation** [comment]
Your fix worked as expected. Pull request opened. :)

**Comment by farmdawgnation** [comment]
Also, yes, I can file a bug about the stack error.

**Comment by mirisuzanne** [comment]
thanks, and thanks. great work.
