### ISSUE TITLE
@extend and input::-webkit-input-placeholder in Firefox

### ISSUE THREAD

**Issue by nikofangohr** [Compass/compass#858]
Firefox ignores the entire css statement (line) if one selector is unknown. That leads to hard to find bugs.
For example:

``` css
input::-webkit-input-placeholder {
 @extend .foo
}
```

``` css
.bar{
 @extend .foo
}
```

.bar is not being styled at all in Firefox since compass produces

``` css
input::-webkit-input-placeholder, bar {
 // whatever is in .foo stated
}
```

It would be nice if compass distinguishes while putting @extends together and separates browser specific selectors into a separate css statement. 

Thanks

**Comment by chriseppstein** [comment]
This is not a bug. this is just a fact of life. We can't make a rule that this is illegal because there are valid use cases.

That said, If there's any change, it would need to happen in Sass, not compass.
