### ISSUE TITLE
TypeError: can't convert nil into String

### ISSUE THREAD

**Issue by threadhead** [Compass/compass#86]
compass (0.10.0.pre5)

If you add compass to a rails app:
http://gist.github.com/299830

Sass is not compiled and the generated css file errors with a 'TypeError: can't convert nil into String':
http://gist.github.com/299832

The fix is to add: 'cache_dir = "tmp/sass-cache"' to config/compass.rb

**Comment by threadhead** [comment]
Duplicate

**Comment by chriseppstein** [comment]
Fixed in .pre6
