### ISSUE TITLE
Compass compile sprite generation doesn't obey -q/--quiet flag.

### ISSUE THREAD

**Issue by stevelacey** [Compass/compass#862]
Whilst quiet will surpress the log messages regarding CSS compilation sprite generations still output e.g.

$ compass compile -q --force

   remove web/images/sprite-sd4f18125d0.png
   create web/images/sprite-sd4f18125d0.png

**Comment by bps4484** [comment]
I've also observed this.  Just wanted to add that it appears this only happens in force mode.  if you remove the --force flag the -q flag works properly.  From some non-related poking around it looks as though :quiet property is being unset in the options variable somewhere (I'm just not knowledgable enough with the codebase to know where).

**Comment by chriseppstein** [comment]
Eh, in 1.0 sprites are not even logged anymore. seems bad.

**Comment by chriseppstein** [comment]
Enjoy the sounds of silence.
