### ISSUE TITLE
FF3/FF12 separation

### ISSUE THREAD

**Issue by Anahkiasen** [Compass/compass#864]
With the recent dropped support for Firefox 3.6, is it planned to break the current $experimental-support-for-mozilla variable into two branches : one for Firefox 3 and one for the current Firefox ? There are a few properties that needed -moz in FF3 that don't require it now.

**Comment by mirisuzanne** [comment]
I would expect that this is a new form of "legacy support" we'll be running into regularly, so should move into the system we already have established for that.

At what market share do we drop support for browsers entirely? Did we make that decision in relation to IE6?

**Comment by chriseppstein** [comment]
I've added a legacy configuration flag for mozilla:

https://github.com/chriseppstein/compass/blob/stable/frameworks/compass/stylesheets/compass/_support.scss#L19-21

I'm of the opinion that we can drop support when it gets down to ~1% of users. Sites that need to support such a small number of legacy users probably don't have to upgrade compass.
