### ISSUE TITLE
Images_dir problem

### ISSUE THREAD

**Issue by aleksandargosevski** [Compass/compass#865]
Hello,

I am trying for 2 days to make compass generate path for images in url. I enabled relative paths, and set images path. Do i need to do something else?

When i add to scss: background-image: url(logo.png); it's generate same thing, not adding ../img/ to url. :\

This is my config.rb file:

http_path = "/"
css_dir = "assets/css"
sass_dir = "sass"
images_dir = "assets/img"
javascripts_dir = "assets/js"

output_style = :nested
relative_assets = true
line_comments = false

It works when i use background-image: image-url(logo); but when i add .png to image name it gives an error: Syntax error: Invalid CSS after "...l(logo": expected ")", was ".png);".

And when i put image name under single quote (background-image: image-url('logo.png'); ) it generate: background-image: url('../img/logo.png?1335519883');

**Comment by mirisuzanne** [comment]
Try putting "logo.png" in quotes.

@chriseppstein I've run into the same thing and it seems unnecessary. Is there a reason it has to be that way?

**Comment by chriseppstein** [comment]
CSS treats url() as a kind of quote. Sass does not special case any sass functions like that.

**Comment by jhilden** [comment]
What is the status of this issue?  Is there anything left to change or explain?

**Comment by chriseppstein** [comment]
Well, currently, the fact `url()` is a string quote is [hard-coded in the Sass parser](https://github.com/nex3/sass/blob/stable/lib/sass/script/parser.rb#L146). The Sass parser would need to be changed to allow arbitrary functions to declare that they are string quotes and then we'd have to decide how this would work for functions that take multiple arguments. I wouldn't want to introduce a behavior into sass that would require quotes to be added just to introduce a second argument. So I think I will just close this.
