### ISSUE TITLE
Transparentize images

### ISSUE THREAD

**Issue by Anahkiasen** [Compass/compass#871]
One thing I find myself regularly looking for is the ability to change the opacity of a particular picture directly in my stylesheet. There is already a way to generate repeatable PNG colors with compass-rgbapng (which I maintain _should_ be part of the core considering how useful and small it is, 1 mixin and one function), but nothing for more complex pictures.

I don't think it would be that hard, the method used would be the same as for sprites, take a picture and save a modified version in a generated_images/ folder. Difference being an opacity change would be applied to it which if I recall there is a function for (but on that point I may just be plain wrong, in that case, please excuse me).

To me this is important because I envision Sass as one of the key in making a website easy to change, like for sprites. If you change one picture of a sprite, you don't have to go back through the whole process in Photoshop, Compass does it for you. This is kind of the same.

**Comment by mirisuzanne** [comment]
I like this idea, whether it happens in Compass core, or as a plugin. I don't know anything about implementation though...

**Comment by Anahkiasen** [comment]
Well I don't think we should be so afraid of adding more to what is considered the Compass core. Of adding elements that may not seem like they belong at first and yet that could really profit to everyone. Look at the Sprite extension – I'm sure at first it seemed like it was way too big and a little far from the core to be a part of Compass. But look at it now, in 90% of the cases when people try to share and help discover Compass it end up being one of its key features and one of the most impressives ones.

Against a lot of suggestions I see thrown the argument that one can easily extend Compass with new plugins and extensions – but that's a lie. That is not what easy is, and to most of the people trying to discover Compass, the extensions are a hard to get notion.
Sass is currently undergoing the tremendous task of having to catch up on Less on the user-friendly field. I'm a PHP developper and I've found Sass hard to get the hang of. Compass was another big thing to get and wrap my mind around. And now people say to every corner that you need even more plugins to put on top of that toolkit ?

I understand the approach and will to separate ; to keep out and let people do our business and pick what they want. But the time when Sass/Compass was a little community of Ruby developpers changed, a lot of people are interested by preprocessors and the more difficult it is to implement in a work environnement, the less likely they'll be to actually even bother.
And when I say hard, I'm not kidding. My current work environnement includes Sass, Compass, and _seven_ Compass plugins, ranging from minor to major functions – a lot of those plugins being functions that could very well be in Compass.
The excess of compartimenting Compass is an enormous problem when working on multiple stations, the differences of versions, of environnement. Furthermore when, again, some of those adds could easily be part of the core, or at least replace some of it. Because let's be honest nobody uses Blueprint anymore with things like HTML5 Boilerplate, Twitter Bootstrap or Susy out there.  But the base idea was good, for me Compass should have a grid system, it should be ready from the start to do most of what 75% of the webdesigners will want to do with.

This whole diatribe may seem like it comes from nowhere but I guess I've been thinking about it for a while and it just had to get out. I guess I've just seen to many projects that just stopped evolving because of some sort of do-it-yourselfitis where just because people could extend the base themselves, ended up leaving every addition to the user.
Again I'm not critizing either the direction or behavior of the Compass Team, I'm here referring to other projects, all I'm hoping is that the features that are being turned down are legitimately not worth adding.

Again, sorry for the sudden outburst.

**Comment by chriseppstein** [comment]
If you would like to suggest some existing plugins to be brought into the core, please do so as separate issues -- We'll consider them on a case-by-case basis.

As for this issue, it seems like a neat idea. It will make a good plugin while you develop the API and get user feedback. Once it is mature, if many projects would benefit from bringing it into the core we will consider it.
