### ISSUE TITLE
Sprite writing fails silently 

### ISSUE THREAD

**Issue by akahn** [Compass/compass#872]
With the following setting: `generated_images_dir = "public/images/generated"`, where public/images/generated is a symlink, Compass doesn't output sprite images and doesn't print an error message. Adding a trailing slash to the string resolves the issue.

**Comment by scottdavis** [comment]
what os and ruby version

**Comment by akahn** [comment]
Ruby version 1.9.2p190. OS X 10.6.8 and CentOS 6.2.

**Comment by scottdavis** [comment]
are you positive its not getting written out to some other location? if it was truly failing to write the file functions would throw a file pointer exception

**Comment by akahn** [comment]
I'm no longer able to reproduce the issue. Sorry.

**Comment by akahn** [comment]
Just encountered this again, but for `css_dir` (which also points to a symlink). Added a trailing slash and the CSS was rebuilt. Before, nothing was happening. Still can't reproduce this consistently. 

Two details that may help: it seems like when the command runs successfully, I get output like

```
   remove tmp/sass-cache/ 
   remove public/stylesheets/styleguide.css 
   remove public/stylesheets/pages.css 
   remove public/stylesheets/ie/ie6.css 
   remove public/stylesheets/screen.css 
```

whereas when the command runs unsuccessfully, there is no such output.

The other thing is that I am building our stylesheets using a rake task that calls `Sass::Plugin.update_stylesheets`. I thought this could be relevant.

**Comment by chriseppstein** [comment]
Some of the output you're seeing is compass noticing that you have an updated configuration file and automatically running a `clean` to make sure things are properly built.
