### ISSUE TITLE
improvement request for the interactive mode

### ISSUE THREAD

**Issue by danielpuglisi** [Compass/compass#874]
At the moment I'm working on a new html/css template for a client. The problem is, I can't use compass or sass out of the box.
So I looked if there is a way to quickly compile css3 mixins of compass. I found the interactive shell mode, but unfortunately you can't call compass css3 mixins in it. 

So I have a feature request. Is it possible to compile mixins in the interactive mode in the future and maybe copy it right away into the clipboard?

**Comment by scottdavis** [comment]
you should beable to pipe sass like so `pbpaste | sass --compass | pbcopy` if you are on a mac. that should take the sass from your clipboard compile it and put it back in your clipboard

**Comment by chriseppstein** [comment]
The interactive mode is only for Sass Script so far. Compass uses the REPL that comes with Sass, so if you want you can file a bug against sass and ask for this support. @nex3 might want it.
