### ISSUE TITLE
@include columns($width-and-count) not working

### ISSUE THREAD

**Issue by mursco** [Compass/compass#878]
From the documentation: http://compass-style.org/reference/compass/css3/columns/

@include columns(20em 2) should work to style text, though it throws an undefined mixin error.

In the Examples, only @include column-count() and  @include column-rule(); are used.  They work properly.  I had someone else test this in IRC and they were able to repeat the issue.

**Comment by chriseppstein** [comment]
are you importing the module?

**Comment by mursco** [comment]
Yes.

**Comment by chriseppstein** [comment]
can you please provide a simple stylesheet that reproduces this issue?

**Comment by jacmoe** [comment]
To reproduce, just replace 'width: 300px' with @include column-width(300px)' and the official example stops working.

**Comment by chriseppstein** [comment]
Damnit, this code exists on stable but the docs slipped onto the main website before the release went out. Sorry for the confusion. It will work with the next release.
