### ISSUE TITLE
Too many png crashes Compass

### ISSUE THREAD

**Issue by kud** [Compass/compass#879]
I'm trying to make a sprite from 320 images and I've got a crash. If you have any idea:

test ❯ compass compile --trace                                                                                                                                                                 ⏎
ruby(85850,0x7fff75b9c960) malloc: **\* mmap(size=2251737429704704) failed (error code=12)
**\* error: can't allocate region
**\* set a breakpoint in malloc_error_break to debug
ruby(85850,0x7fff75b9c960) malloc: **\* mmap(size=2251737429704704) failed (error code=12)
**\* error: can't allocate region
**\* set a breakpoint in malloc_error_break to debug
NoMemoryError on line ["87"] of /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/chunky_png-1.2.5/lib/chunky_png/canvas.rb: failed to allocate memory
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/chunky_png-1.2.5/lib/chunky_png/canvas.rb:87:in `new'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/chunky_png-1.2.5/lib/chunky_png/canvas.rb:87:in`initialize'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/chunky_png-1.2.5/lib/chunky_png/image.rb:23:in `initialize'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/sass_extensions/sprites/engines/chunky_png_engine.rb:13:in`new'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/sass_extensions/sprites/engines/chunky_png_engine.rb:13:in `construct_sprite'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/sass_extensions/sprites/sprite_methods.rb:62:in`generate'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/sass_extensions/functions/sprites.rb:122:in `sprite_url'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/sass_extensions/sprites/sprite_map.rb:72:in`method_missing'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/sass_extensions/sprites/sprite_map.rb:63:in `to_s'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/script/list.rb:44:in`block in to_s'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/script/list.rb:44:in `map'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/script/list.rb:44:in`to_s'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:217:in `visit_prop'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:37:in`visit'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:18:in `visit'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:53:in`block in visit_children'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:53:in `map'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:53:in`visit_children'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:27:in `block in visit_children'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:39:in`with_environment'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:26:in `visit_children'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:37:in`block in visit'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:238:in `visit_rule'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:37:in`visit'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:18:in `visit'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:53:in`block in visit_children'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:53:in `map'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:53:in`visit_children'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:27:in `block in visit_children'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:39:in`with_environment'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:26:in `visit_children'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:37:in`block in visit'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:125:in `visit_if'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:37:in`visit'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:18:in `visit'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:128:in`visit_if'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:37:in `visit'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:18:in`visit'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:146:in `block in visit_import'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:146:in`map'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:146:in `visit_import'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:37:in`visit'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:18:in `visit'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:53:in`block in visit_children'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:53:in `map'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:53:in`visit_children'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:27:in `block in visit_children'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:39:in`with_environment'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:26:in `visit_children'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:37:in`block in visit'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:47:in `visit_root'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:37:in`visit'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:18:in `visit'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:7:in`visit'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/tree/root_node.rb:20:in `render'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/engine.rb:299:in`_render'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/sass-3.1.17/lib/sass/engine.rb:246:in `render'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/compiler.rb:140:in`block (2 levels) in compile'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/compiler.rb:126:in `timed'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/compiler.rb:139:in`block in compile'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/logger.rb:45:in `red'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/compiler.rb:138:in`compile'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/compiler.rb:118:in `compile_if_required'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/compiler.rb:103:in`block (2 levels) in run'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/compiler.rb:101:in `each'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/compiler.rb:101:in`block in run'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/compiler.rb:126:in `timed'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/compiler.rb:100:in`run'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/commands/update_project.rb:45:in `perform'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/commands/base.rb:18:in`execute'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/commands/project_base.rb:19:in `execute'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/exec/sub_command_ui.rb:43:in`perform!'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/bin/compass:29:in`block in <top (required)>'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/bin/compass:43:in `call'
  /Users/xxx/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.12.1/bin/compass:43:in`<top (required)>'
  /Users/xxx/.rbenv/versions/1.9.3-p194/bin/compass:23:in `load'
  /Users/xxx/.rbenv/versions/1.9.3-p194/bin/compass:23:in`<main>'

**Comment by kud** [comment]
Okay, my bad. After some hours of trying to find a solution (divide the sprite in some sprites) I've found that it's one of my png was corrupted. Without it, it works perfectly. Thanks anyway.

**Comment by chriseppstein** [comment]
hmmm. still seems like we can give better error messages.

**Comment by kud** [comment]
True, true. But glad it was my fault and not yours ;)

I wasn't able to open it with fireworks and photoshop and other stuff. I did to open it with open office, export it in png and work it again with fireworks to have a correct png. Now the sprite is perfect.

**Comment by scottdavis** [comment]
we would need to know the max heap size to guess how many png's it can store in memory? or are you thinking we just impose a hard # limit

**Comment by kud** [comment]
@scottdavis It wasn't a memory storage trouble. It was just one of my files which was corrumpted. The best message should be "Watch your files, it seems to be that one is corrumpted".

**Comment by scottdavis** [comment]
i think there was another ticket related to this. let me find it

**Comment by scottdavis** [comment]
sorta dup of #860

**Comment by kud** [comment]
Perfect. Obrigado.
