### ISSUE TITLE
Can't load compass --pre from config.gems

### ISSUE THREAD

**Issue by noctivityinc** [Compass/compass#88]
There doesnt appear to be a way to effectively install compass --pre from config.gem.  

I have:

config.gem 'compass', :lib => 'compass', :source => "http://gems.github.com", :version => ">=0.10.0.pre5"

But a rake gems:install fails.  

Any thoughts?

-jl

**Comment by chriseppstein** [comment]
Compass is hosted on gemcutter now. take out the :source and it should work.
