### ISSUE TITLE
bootstrapping framework installs

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#880]
We should try to avoid the `-r` option by using the framework name in the template as a require if the framework is not found.

**Comment by Snugug** [comment]
+1 for this

**Comment by chriseppstein** [comment]
Compass 1.0 automatically loads any framework that has a ruby file in it's main library path that conforms to "compass-*.rb".

Added docs for this in 7d570c818847fcb0d6c2e96d7f16db2fcd58f24d.
