### ISSUE TITLE
Drupal App Integration

### ISSUE THREAD

**Issue by Snugug** [Compass/compass#887]
Drupal operates a little bit differently than Ruby et all so it's integration is going to be a little bit different. In practice, you'd never be building a full Drupal project with Sass/Compass, but rather an individual module or theme file, and most commonly a theme file. There are only a handful of changes that would need to be made, and they are as follows:
### config.rb

http_path: Because Drupal can have modules or themes, and their path is dependent on the individual install, this can mostly be ignored, but relative assets needs to be true
fonts_dir becomes "fonts" instead of "stylesheets/fonts"
javascripts_dir becomes "js" instead of "javascripts"
CSS, Sass, and Images can all stay the same.
### .info file

An additional file would need to be created to tell Drupal that this is a module/theme; the .info file.
{project-name}.info
The .info file differs whether you are writing a module or a theme, so there would need to be an option to choose which one you're writing (ideally).
.info files differ between Drupal 6 and Drupal 7, and I would suggest supporting both.
#### Drupal 6 Module .info

Full (Drupal.org Documentation)[http://drupal.org/node/231036]
Of this, all that is truly needed is name and core; everything else would be put in by hand
#### Drupal 7 Module .info

Full (Drupal.org Documentation)[http://drupal.org/node/542202]
Of this, all that is truly needed is name, core, and files; everything else would be put in by hand
#### Drupal Theme .info

Full (Drupal.org Documentation)[http://drupal.org/node/171205]
Of this, all that is truly needed is name, core, and engine (should default to phptemplate). (Stylesheets)[http://drupal.org/node/171205#stylesheets] and (Scripts)[http://drupal.org/node/171205#scripts] should also be added through the build. 

If you need any more information, or if you can point me to some quick documentation for doing this myself, let me know!

**Comment by JohnAlbin** [comment]
Here's a link to the config.rb file that comes with sub-themes of the Zen theme for Drupal 7. http://drupalcode.org/project/zen.git/blob/refs/heads/7.x-5.x:/STARTERKIT/config.rb

And a link to an real .info file (for a Zen sub-theme under Drupal 7), if that helps. http://drupalcode.org/project/zen.git/blob/refs/heads/7.x-5.x:/STARTERKIT/STARTERKIT.info.txt

**Comment by scottdavis** [comment]
This may get a better response on the google group im not sure where to point you. Specific application integrations were removed with the release of 0.12 so any integration that you need will need to be created. Using the register method here:

https://github.com/chriseppstein/compass/blob/stable/lib/compass/app_integration.rb#L31

**Comment by Snugug** [comment]
@scottdavis I'd request you reopen this as this was opened at the behest of @chriseppstein who, when I asked if there was a tutorial anywhere about doing app integration, he told me, and I'm quote/paraphrasing, "just let me write it".
I'm happy, oh so happy, to write this on my own, but when asked how, I was told to let it be, it'd get handled.

**Comment by Snugug** [comment]
Specifically around distributing the app integration as well.

**Comment by scottdavis** [comment]
reopened and assigned

**Comment by Snugug** [comment]
Thank you much.

**Comment by chriseppstein** [comment]
@Snugug We got this working for you as a plugin at sassconf right?

**Comment by Snugug** [comment]
I believe you had, but I don't remember the URL.

I think you wrote up a comprehensive project explaining how to do it.

**Comment by chriseppstein** [comment]
you suck. I don't know where it is.

**Comment by Snugug** [comment]
I love you too.

It doesn't look as if you wrote a custom plugin, but you did create a writeup on how to create your own.

https://gist.github.com/chriseppstein/6965538
