### ISSUE TITLE
YUI Grids 2.6.0 mixin irregularity: gd nested in ge

### ISSUE THREAD

**Issue by davidrivers** [Compass/compass#89]
Attempting to replicate a 25% | 50% | 25% grid as shown here: http://nate.koechley.com/dev/2009/grids-3col-gd-in-ge.html

```
.yui-ge
  .yui-u.first
    .yui-gd
      .yui-u.first First Column (25%)
      .yui-u 2nd Column (50%)
  .yui-u 3rd Column (25%)
```

Within the nested gd I am getting a 74.2% unit and a 24% one, as shown in Firebug:

> .yui-ge div.first, .yui-gf .yui-g, .yui-gf .yui-u {
>   width:74.2%;
> }
> 
> .yui-gd div.first, .yui-gb .yui-gd div.first {
>   <del>width:32%;</del>
> }
> 
> .yui-ge .yui-u, .yui-ge .yui-g, .yui-gf div.first {
>   width:24%;
> }
> 
> .yui-g .yui-gc div.first, .yui-gc div.first, .yui-gd .yui-g, .yui-gd .yui-u {
>   <del>width:66%;</del>
> }

After viewing the source, Nate Koechley appears to be using the same 2.6.0 version of Grids, as documented by Compass's _grids.sass mixin, albeit while admitting that the styles therein are not tested.  This appears to be a bug with them.

As in _grids.sass:

```
// This is a port of YUI Grids version 2.6.0
// Note: This is not really tested yet. Use at your own risk.
```

**Comment by chriseppstein** [comment]
There were some bug fixes for v0.10 and now that code is a plugin:
http://github.com/chriseppstein/yui-compass-plugin

Can you verify that the bug is still there and submit a patch if you're up to the task? Also, I'd like to track the bug from that repo. Would you mind opening a new issue and referencing this one? Thanks!

**Comment by davidrivers** [comment]
Sure thing! I should make my changes and then do a pull request?

**Comment by chriseppstein** [comment]
Yes please!
