### ISSUE TITLE
Only one "-" available in filename

### ISSUE THREAD

**Issue by kud** [Compass/compass#890]
Hey,

I'm using Compass for generating some sprites. I've got my files like that:

```
/icons/menu-home.png
/icons/menu-home-hover.png
```

Compass generates correctly the sprite but doesn't insert the `.icons-menu-home-hover`. Only `.icons-menu-home` was generated.

To resolve this problem, I had to name it `/icons/menu-homehover.png` and I had `.icons-menu-homehover`

**Comment by scottdavis** [comment]
thats because magic selectors is the default im pretty sure its generating `.icons-menu-home:hover`

**Comment by kud** [comment]
Gotta have a look but i'm not sure, coz /icons/menu-home-h.png didn't work too apparently.

**Comment by scottdavis** [comment]
make me an example project as a test case and ill look into it further

**Comment by kud** [comment]
Well, I've tried some cases, and it seems to be ok. Though I've updated SASS between the init of this issue and now.

```
.test-hover-sprite, .test-hover-test-hello-hover, .test-hover-test-hover, .test-hover-this-is-a-test, .test-hover-this-is-another-test {
  background: url('../img/design/test-hover-se122e216f6.png') no-repeat;
}

.test-hover-test-hello-hover {
  background-position: 0 0;
}

.test-hover-test-hover {
  background-position: 0 -17px;
}

.test-hover-this-is-a-test {
  background-position: 0 -34px;
}

.test-hover-this-is-another-test {
  background-position: 0 -51px;
}

```

**Comment by kud** [comment]
Well, I come back with this same trouble.

I've got for instance :
- firefox.png
- firefox-hover.png
- chrome.png
- chrome-hover. png

I have this code:

```
$browser-sprite-dimensions: true;
@import "design/browser/*.png";
@include all-browser-sprites;
```

It will generate the sprite will ALL images but about the css, it won't have any .firefox-hover and .chrome-hover classes.

It's like "-hover" is a magick word but will generate nothing, contrary to "_hover" which works perfectly.
