### ISSUE TITLE
upgrade css3pie to 1.0

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#891]
also need to consider what would be required to extract this to a plugin.

**Comment by scottdavis** [comment]
i think we should extract and find a maintainer

**Comment by chriseppstein** [comment]
I would like to explore what would be required to accomplish this. I
remember thinking that it wasn't doable back when I first added support.

**Comment by scottdavis** [comment]
now that we have @content it shouldn't be to bad

**Comment by chriseppstein** [comment]
we've removed css3pie
