### ISSUE TITLE
When generating a sprite, I can't get a reference to it after @import

### ISSUE THREAD

**Issue by lifeiscontent** [Compass/compass#899]
I would like to get a reference to an image-map on import of the sprite, but there doesn't seem to be a way without regenerating the image with the sprite-map function....

**Comment by scottdavis** [comment]
you should be able to access it via 

https://github.com/chriseppstein/compass/blob/stable/lib/compass/sprite_importer/content.erb#L26

**Comment by chriseppstein** [comment]
Yep, you can access it as `$<name>-sprites`.
