### ISSUE TITLE
Better scoping for horizontal-list

### ISSUE THREAD

**Issue by marnen** [Compass/compass#9]
I just sent you a pull request for http://github.com/marnen/compass/commit/572291d9993e83314354148be3beb1b322534bf7 , which adds better scoping to horizontal-list so that it can apply (if desired) to one level of li, not the whole list tree. This is good for making dropdown menubars.

**Comment by chriseppstein** [comment]
I agree that a change would be useful here to control the scoping of LI for nested lists. Please see [my comment](http://github.com/marnen/compass/commit/572291d9993e83314354148be3beb1b322534bf7#comment_21884) for more details.

**Comment by marnen** [comment]
Here's another try. Check out http://github.com/marnen/compass/blob/cf9050857adee8770d4b3a2a92322293c2ddc25d/frameworks/compass/stylesheets/compass/utilities/lists/_horizontal_list.sass .

**Comment by chriseppstein** [comment]
[Compass Core] Extracted two new mixins from +horizontal-list. Closed by faadde2379a05c3c002a1de76a47b170dadff776.
The new +horizontal-list-container and +horizontal-list-item mixins can
be used to build your horizontal list when you need more control over
the selectors (E.g. when working with nested lists).

**Comment by chriseppstein** [comment]
Thanks for your patches, but I decided to fix this using a different approach altogether This approach gives more control to the user when the default mixin doesn't work.
