### ISSUE TITLE
ANSI escape codes showing on Windows

### ISSUE THREAD

**Issue by charlesroper** [Compass/compass#90]
I have win32console installed and colours are appearing (green is, at least) but there are still some glitches. Here's a screenshot to demonstrate: http://i.imgur.com/di3UU.png

**Comment by chriseppstein** [comment]
Charles, any chance that you can debug this and submit a patch?

**Comment by charlesroper** [comment]
Sure. Where in the code does the colouring action happen?

**Comment by chriseppstein** [comment]
Right [here](http://github.com/chriseppstein/compass/blob/master/lib/compass/logger.rb#L47-57)

**Comment by charlesroper** [comment]
It's caused by writing to $stderr in Logger#red; currently win32console doesn't wrap $stderr and so the escape sequences appear. I can easily add a fix to Compass's code, but Luis is going to add $stderr support directly to win32console, so it's probably not worth it. I'll close this once Luis's update lands.

**Comment by chriseppstein** [comment]
closing
