### ISSUE TITLE
Is there a way to only watch one specific file?

### ISSUE THREAD

**Issue by danielpuglisi** [Compass/compass#903]
Hello there.

I'm setting up my GitHub Pages and I want to use compass for this. The thing is, I'm used to split up my sass files into different folders and include them all in one file, the `application.sass` file. 

But when I do this and watch the files with `compass watch`, the files in the subdirectories also get compiled, but I just want the `application.sass` file to be compiled.

I could easily avoid this by setting up an extra folder, move the `application.sass` file to this folder, change the relatives in the sass file and adjust the `config.rb` file. Before I do this, I wanted to ask if there is a simple way to just watch one file with the compass cli tool?

**Comment by Anahkiasen** [comment]
You can always do `sass --compass --watch stylesheet.css:stylesheet.sass` no ?
This could also come from the fact that your imported file aren't recognized as partials, do they all have an underscore at the beginning of their name ?

**Comment by mirisuzanne** [comment]
If you prefix your partial files with an underscore (`_base.scss`, `_fonts.scss`, `_widget.scss`) they wont be compiled. And that doesn't even effect how you call them: `@import base.scss` will import `_base.scss`.

**Comment by danielpuglisi** [comment]
@ericam Thanks, that's what I've been searching for.
