### ISSUE TITLE
SCSS syntax error messages are sometimes inserted in the wrong CSS file and not removed when the syntax error is fixed.

### ISSUE THREAD

**Issue by patreeceeo** [Compass/compass#904]
I'm perplexed as to how compass is even inserting these error messages in the document as they don't appear to be in either the HTML source nor the DOM, but nonetheless appear on the page and f*\* up the layout. This would be okay if they always went away when the error is corrected, but I've had a couple experiences where they don't and when they do go away there's no reason I can discern. 

**I've tried:**
- correcting the syntax error (obviously)
- deleting the .sass-cache directory 
- killing compass
- restarting compass
- clearing my browser cache
- viewing the page in a different browser
- intentionally inserting other syntax errors
- removing the at-import directive of the offending stylesheet

The only other thing I can think of is restarting my machine, I'll do that next and let you know how it goes. 

**Some info about my situation:**

This only seems to happen when the error is in SCSS files, not SASS files.

**The latest error message is:** 
   Syntax error: Invalid CSS after "     font-size:": expected psuedoclass or psuedoelement, was " 1em !important"

**I'm using:**
- sass-twitter-bootstrap
- sinatra
- adamstac's sinatra-bootstrap
- ubuntu 12.04
- ruby 1.9.3p194
- haml 3.1.4

**Possible resolutions include:**
- Making the error messages go away when the error is corrected
- Not (mysteriously) showing error messages in the generated document

Maybe I'm missing something blindingly obvious here, but I'm completely stupefied.

Thanks,
Patrick

**Comment by patreeceeo** [comment]
Also, the latest error message occurred in lib/_carousel.scss of sass-twitter-bootstrap, if that helps.

**Comment by patreeceeo** [comment]
Restarting my machine did not help.

**Comment by patreeceeo** [comment]
The zombie error message is there in the production version of the site, too.

**Comment by patreeceeo** [comment]
http://helcross.heroku.com

**Comment by patreeceeo** [comment]
Okay. I see that the error messages are inserted using the content property in the generated CSS, but I'm not sure where the CSS file with the content property is in this case.

**Comment by patreeceeo** [comment]
After grepping around a bit, I found the content property that creates this zombie error message to be in what seems to be a **completely unrelated file** (public/stylesheets/lib/responsive.css). Deleting that file seems to fix the issue for now. This definitely seems like a bug!

**Comment by scottdavis** [comment]
this may actually be a bug in sass if it is a bug

**Comment by chriseppstein** [comment]
This seems like user error from checking in compiled CSS which then got concatenated or linked somehow.

If you can provide a reproducible set of step, please let us know.
