### ISSUE TITLE
@font-face mixin fails in IE8

### ISSUE THREAD

**Issue by magalhini** [Compass/compass#906]
Hello,

I recently noticed on a work project, which is using Compass and loading font-faces using the provided 'font-face' mixin, that every custom font was failing in IE8 (IE9 was fine).

Removing the mixin and writing the recommended syntax for loading custom font-faces (more on this by Paul Irish!) made them work fine, so I went ahead to debug it.

Here's the mixin in the .scss file:
`
@include font-face('TerminalDosisLight',
    font-files(
        'terminal/terminaldosis-light-webfont.eot',
        'terminal/terminaldosis-light-webfont.eot?#iefix',
        'terminal/terminaldosis-light-webfont.woff',
        'terminal/terminaldosis-light-webfont.ttf',
        'terminal/terminaldosis-light-webfont.svg#TerminalDosisBold'
    )
);`

Which outputs this:
`
@font-face {
    font-family: "TerminalDosisLight";
    src: url('terminal/terminaldosis-light-webfont.eot'),
         url('terminal/terminaldosis-light-webfont.eot?#iefix') format('embedded-opentype'),
         url('terminal/terminaldosis-light-webfont.woff') format('woff'),
         url('terminal/terminaldosis-light-webfont.ttf') format('truetype'),
         url('terminal/terminaldosis-light-webfont.svg#TerminalDosisLight') format('svg');
}`

However, **using only one src attribute** makes IE8 ignore the next fix for the .eot file. This one should also be presented to the browser on a separate source, like this:
`
@font-face {
    font-family: "TerminalDosisLight";
    src: url('terminal/terminaldosis-light-webfont.eot');
    src: url('terminal/terminaldosis-light-webfont.eot?#iefix') format('embedded-opentype'),
         url('terminal/terminaldosis-light-webfont.woff') format('woff'),
         url('terminal/terminaldosis-light-webfont.ttf') format('truetype'),
         url('terminal/terminaldosis-light-webfont.svg#TerminalDosisLight') format('svg');
}`

This way IE8 is able to read the file and display the custom font-faces.

Cheers!

**Comment by mirisuzanne** [comment]
You're not using the mixin correctly. This is the proper use:

``` scss
@include font-face('TerminalDosisLight',
  font-files(
    'terminal/terminaldosis-light-webfont.woff', 'woff',
    'terminal/terminaldosis-light-webfont.ttf', 'truetype',
    'terminal/terminaldosis-light-webfont.svg#TerminalDosisBold', 'svg',
  ),
  'terminal/terminaldosis-light-webfont.eot'
);
```

That will output the correct Paul Irish / FontSpring syntax.

**Comment by emarchak** [comment]
This code fails if you have an extra comma after the last element in an array (e.g. `'svg',`). 

The following works for me:

```
@include font-face('TerminalDosisLight',
  font-files(
    'terminal/terminaldosis-light-webfont.woff', 'woff',
    'terminal/terminaldosis-light-webfont.ttf', 'truetype',
    'terminal/terminaldosis-light-webfont.svg#TerminalDosisBold', 'svg'
  ),
  'terminal/terminaldosis-light-webfont.eot'
);
```
