### ISSUE TITLE
JPG sprites support

### ISSUE THREAD

**Issue by josefrichter** [Compass/compass#907]
Please, would it be possible to implement support for JPG sprites, too? Sprites are being used much more widely these days than just for small PNG icons. But I don't have the skills to implement it.

**Comment by chriseppstein** [comment]
The image manipulation library we use is pure-ruby which makes it very easy for us to support it on all platforms. However, it's possible to support this use case if you use https://github.com/Compass/compass-rmagick-engine or if we can find a pure-ruby implementation of jpeg.

**Comment by scottdavis** [comment]
the rmagick engine only does pngs also its just a bit faster ... the importer it self verifys that all images are png's and alot of png assumptions are taken within the spirite image class methods. TL;DR version this will take some rewriting to impliment

**Comment by scottdavis** [comment]
also if anyone wants to write a jpeg library in pure ruby alot of people would be excited

**Comment by robwierzbowski** [comment]
With jpegs there's also a background color issue — no transparency, so the element containing the sprite has to be exactly the correct size, or a background color needs to be passed into the sprite generator. This is one of the reasons sprites are generally pngs only, and IMO one of the good reasons to keep them so.

**Comment by chriseppstein** [comment]
I agree with @robwierzbowski, JPEG sprites are not a sprite-friendly image format. However, SVG and GIF are viable.

**Comment by beatak** [comment]
this may be a bit out of context, but @scottdavis I saw https://github.com/chriseppstein/compass/commit/520c950f7d9a9bf7d5cf99842e898feec8aa7364 and it seems this will let me order the sprite file by file name or file size?  that looks very very interesting and I wish it'll be merged to master!

**Comment by scottdavis** [comment]
520c950 is on master
