### ISSUE TITLE
Adding image_height and image_width functions to Compass core

### ISSUE THREAD

**Issue by deepakjois** [Compass/compass#91]
[Divya Manian](http://nimbu.in) asked me to help her create a couple of functions she can use to find out the height and width of an image. Here is the [commit on my fork](http://github.com/deepakjois/compass/commit/f9d75b3bcecc89cf7100111690aefbb6d0b95ef6).

Here is a sample usage :

```
=background_image(!imageurl)
  background = image_url(!imageurl) "no-repeat"
  width = image_width(!imageurl)
  height = image_height(!imageurl)

a.download
  +background_image("download.png")

a.subscribe
  +background_image("subscribe.png") 
```

I have included pure Ruby code to calculate dimensions for GIFs and PNGs. JPGs is a little complicated, but doable. If there is interest in including this in Compass, I can write the code for the JPG image calculation too.

**Comment by richardaday** [comment]
Hey deepakjois, I'm glad you got around to doing this.  Here is a gist I was talking to Chris about that contains some code on how to find image sizes for different formats: https://gist.github.com/cc7a6206d5d4d45e15d5

Can you integrate the missing file types into your fork?

Disclaimer: The logic on how to find the size from different files was found online.

**Comment by deepakjois** [comment]
I have updated my fork with the code you provided, to add support for JPG and BMP.

**Comment by chriseppstein** [comment]
I like this feature. But I cannot accept the patch without tests. Please see this test case for an example of what is needed:
http://github.com/chriseppstein/compass/tree/master/test/fixtures/stylesheets/image_urls/
and this:
http://github.com/chriseppstein/compass/blob/master/test/compass_test.rb#L49-56

**Comment by chriseppstein** [comment]
I added tests and fixed some bugs, the code is merged. Thanks!
