### ISSUE TITLE
Sprite name causes error with color.rb

### ISSUE THREAD

**Issue by autumnsm** [Compass/compass#910]
When running "@include all-*-sprites;", if your icon images are named after colors(red.png), it will cause a conflict with color.rb

NameError on line 2590 of org/jruby/RubyModule.java: uninitialized constant Sass::Script::Color::HTML4_COLORS_REVERSE

**Comment by scottdavis** [comment]
what is color.rb?

**Comment by autumnsm** [comment]
It's one of the SASS files
https://github.com/nex3/sass/blob/master/lib/sass/script/color.rb

Conflicts with this line
COLOR_NAMES_REVERSE = map_hash(hash_to_a(COLOR_NAMES)) {|k, v| [v, k]}

**Comment by scottdavis** [comment]
can i see a full stack trace or can you create an example?

**Comment by chriseppstein** [comment]
This is fixed in the next release. It's because some Sass constants have changed in a recent release. Compass picks the right constant now.
