### ISSUE TITLE
Globbing sprites creates invalid line comments

### ISSUE THREAD

**Issue by maxbeatty** [Compass/compass#911]
If you use a glob pattern to import sprites and have line comments enabled, the outputted CSS comments are broken.

Example globbing using `**/*` pattern:

``` sass
@import "sprites/icons/**/*.png"
```

Example CSS output:

``` css
/* line 186, sprites/icons/**/*.png */
```

**Comment by scottdavis** [comment]
oh joy this sounds fun! ill get it patched

**Comment by chriseppstein** [comment]
beat ya to it, @scottdavis.

**Comment by scottdavis** [comment]
Good work now do it again but better
