### ISSUE TITLE
Question about IE support

### ISSUE THREAD

**Issue by kud** [Compass/compass#913]
As you can read on this page: http://paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/, using css hacks aren't the good way.

So, do you think it could be a good idea to support special IE classes in compass?

Instead of using \* or _, we generate .lt-ie9 or .ie9?

Tell me what do you think.

**Comment by mirisuzanne** [comment]
I agree with Paul completely, but things are a bit different with Compass. For one, hacks aren't quite as dangerous when they are so easily managed and updated. 

More to the point, though, it would add a dependency that we can't track. In order for Compass mixins to work across browsers, you would have to set up conditional classes in your HTML that match some pre-determined set exactly. We can't really count on that as a default setting for all our users. The default needs to "just work".

I would be very interested in ideas for how we might implement that as an optional alternative. I would use it on all my projects.

(Also: any attempt at this will run into limitations with the current Sass handling of the "&" selector. But I hear that is getting fixed.)

**Comment by chriseppstein** [comment]
@ericam nailed it.

To follow on, the hacks are just a tool. One that works with minimal complexity and in reality has caused zero problems.

CSS currently lacks any formal feature detection to manage features correctly, but they are working on it: http://www.w3.org/TR/css3-conditional/ and when that lands and becomes commonplace, Compass will have a powerful and reliable tool at our disposal.
