### ISSUE TITLE
Import directory as variable

### ISSUE THREAD

**Issue by aleksandargosevski** [Compass/compass#914]
Is it possible to make a directory that we import as a variable? Something like this:

`@import #{$partials-dir}/"header";`

**Comment by scottdavis** [comment]
not possible its a limitation built into sass

**Comment by chriseppstein** [comment]
Unless you install this plugin: https://github.com/chriseppstein/sass-globbing

**Comment by chriseppstein** [comment]
Sorry. That's for globbing. Scott is right, you can't use variables. I suck at reading.

**Comment by aleksandargosevski** [comment]
Hehe, okay. It's not important, I just wondered if is possible. Thanks for quick reply. Cheers
