### ISSUE TITLE
Installing ZURB-foundation (2.2.1.3) causes issue

### ISSUE THREAD

**Issue by StevenLangbroek** [Compass/compass#919]
Hey guys,

I just tried to install ZURB-foundation on a project, and am getting a weird error:

```
error static/sass/foundation.scss (Line 126 of _transition.scss: "index(background-color, transform-origin)" is not a number for `nth')
Sass::SyntaxError on line 126 of /Library/Ruby/Gems/1.8/gems/compass-0.12.1/frameworks/compass/stylesheets/compass/css3/_transition.scss: "index(background-color, transform-origin)" is not a number for `nth'
```

Any thoughts on this?

Thanks,
- Steven

**Comment by chriseppstein** [comment]
Very strange. The index function is in sass proper, I don't know how it could have been interpreted as a CSS function. Will need steps to reproduce.

**Comment by StevenLangbroek** [comment]
- Installed ZURB-foundation in terminal by `sudo gem install ZURB-foundation` as per instructions on http://foundation.zurb.com/docs/gems.php.
- Created compass-project in Codekit
- added `require "/Library/Ruby/Gems/1.8/gems/ZURB-foundation-2.2.1.2/lib/ZURB-foundation.rb"` to config.rb file
- navigated to folder in terminal and ran `compass install ZURB-foundation` 
- Also tried creating a new compass-project through command-line instead of codekit, same results...

**Comment by StevenLangbroek** [comment]
Is there a way to completely remove compass's files and then reinstall?

**Comment by chriseppstein** [comment]
foundation 3 is coming soon and it's properly built on sass.
