### ISSUE TITLE
Compass not noticing changes.

### ISSUE THREAD

**Issue by andrewhathaway** [Compass/compass#920]
So as usual I head in terminal to the folder where the project I created had been created in the previous session of me being on my computer. I type compass watch, as normal, and no changes are picked up upon save. However if I CTRL+C and then type compass watch it will 'compile' the last change, yet will not compile any other changes after that, until I 'restart' the watch.

I am using OSX 10.6.8, I have tried things like restarting and re initiating but still no luck. Any clues?

Thanks.

**Comment by chriseppstein** [comment]
does passing the `--poll` option to the watch command help?
