### ISSUE TITLE
compass watch broken on Ubuntu 12.04

### ISSUE THREAD

**Issue by ramaboo** [Compass/compass#922]
david@birthday:/var/www/v5.ucrave.com/themes/ucrave$ gem list

**\* LOCAL GEMS ***

bundler (1.1.4)
chunky_png (1.2.5)
compass (0.12.1)
fssm (0.2.9, 0.2.7)
rake (0.9.2.2)
rubygems-bundler (1.0.2)
rvm (1.11.3.3)
sass (3.1.19)
david@birthday:/var/www/v5.ucrave.com/themes/ucrave$ compass watch --trace
LoadError on line ["70"] of /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/gems/compass-0.12.1/lib/compass/commands/watch_project.rb: no such file to load -- fssm
  /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/gems/compass-0.12.1/lib/compass/commands/watch_project.rb:70:in `perform'
  /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/gems/compass-0.12.1/lib/compass/commands/base.rb:18:in`execute'
  /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/gems/compass-0.12.1/lib/compass/commands/project_base.rb:19:in `execute'
  /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/gems/compass-0.12.1/lib/compass/exec/sub_command_ui.rb:43:in`perform!'
  /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/gems/compass-0.12.1/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/gems/compass-0.12.1/bin/compass:29:in`block in <top (required)>'
  /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/gems/compass-0.12.1/bin/compass:43:in `call'
  /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/gems/compass-0.12.1/bin/compass:43:in`<top (required)>'
  /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/bin/compass:19:in `load'
  /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/bin/compass:19:in`<main>'
  /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/bin/ruby_noexec_wrapper:14:in `eval'
  /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/bin/ruby_noexec_wrapper:14:in`<main>'

**Comment by parkr** [comment]
Do you have the `fssm` gem installed?

**Comment by ramaboo** [comment]
Yes
**\* LOCAL GEMS ***

bundler (1.1.4)
chunky_png (1.2.5)
compass (0.12.1)
fssm (0.2.9, 0.2.7)
rake (0.9.2.2)
rubygems-bundler (1.0.2)
rvm (1.11.3.3)
sass (3.1.19)
david@birthday:/var/www/v5.ucrave.com/themes/ucrave$ compass watch
LoadError on line ["70"] of /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/gems/compass-0.12.1/lib/compass/commands/watch_project.rb: no such file to load -- fssm
Run with --trace to see the full backtrace
david@birthday:/var/www/v5.ucrave.com/themes/ucrave$ 

I even installed it outside of RVM for kicks and no luck.

I noticed fssm spits out this message:
Dear developers making use of FSSM in your projects,
FSSM is essentially dead at this point. Further development will
be taking place in the new shared guard/listen project. Please
let us know if you need help transitioning! ^_^b
- Travis Tilley

**Comment by parkr** [comment]
What do you get if you run it with `--trace`? Any other information? The [`require 'fssm'`](https://github.com/chriseppstein/compass/blob/stable/lib/compass/commands/watch_project.rb#L70) is causing the error but I'm not sure why, as you have **fssm** installed.

**Comment by ramaboo** [comment]
david@birthday:/var/www/v5.ucrave.com/themes/ucrave$ compass watch --trace
LoadError on line ["70"] of /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/gems/compass-0.12.1/lib/compass/commands/watch_project.rb: no such file to load -- fssm
  /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/gems/compass-0.12.1/lib/compass/commands/watch_project.rb:70:in `perform'
  /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/gems/compass-0.12.1/lib/compass/commands/base.rb:18:in`execute'
  /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/gems/compass-0.12.1/lib/compass/commands/project_base.rb:19:in `execute'
  /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/gems/compass-0.12.1/lib/compass/exec/sub_command_ui.rb:43:in`perform!'
  /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/gems/compass-0.12.1/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/gems/compass-0.12.1/bin/compass:29:in`block in <top (required)>'
  /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/gems/compass-0.12.1/bin/compass:43:in `call'
  /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/gems/compass-0.12.1/bin/compass:43:in`<top (required)>'
  /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/bin/compass:19:in `load'
  /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/bin/compass:19:in`<main>'
  /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/bin/ruby_noexec_wrapper:14:in `eval'
  /home/david/.rvm/gems/ruby-1.9.2-p320@wordpress/bin/ruby_noexec_wrapper:14:in`<main>'
david@birthday:/var/www/v5.ucrave.com/themes/ucrave$ 

I find the error strange because the require 'fssm' should work. I googled and could not find much though there seemed to be sporadic reports of fssm not working in Ubuntu. Given Ubuntu 12.04 is newer than the last fssm update and that fssm is basically dead its not entirely surprising it does not work. I also tried running it under 1.8.7 but that did not work either.

After much trial and error I have solved the problem. It seems its a problem with fssm and RVM gemsets. The following made it work

rvm use system --default
sudo gem install compass #seemed to need to sudo to put gems in /var/lib/gems
cd <project path>
compass watch

my guess is for whatever reason the require 'fssm' looks for a system gem rather than an gem inside RVM. Even with the gem installed on the system it still wont run in RVM. Very strange.

**Comment by scottdavis** [comment]
fssm is slowly being beaten to death with a large mallet. I hope to have it replaced with listen come the final release of 0.13 hang tight!

**Comment by junghokim** [comment]
I'm getting the same error w/RVM + ruby 1.9.3. I've resorted to just using $ rvm default for the time being.

**Comment by stefankendall** [comment]
This is still an issue for me. Can this get any traction?

**Comment by scottdavis** [comment]
Try the listen branch

**Comment by stefankendall** [comment]
Works. I'll wait for the master merge.

Sent from my iPhone

On Oct 24, 2012, at 6:45 PM, Scott Davis notifications@github.com wrote:

Try the listen branch

Sent from my iPhone

On Oct 24, 2012, at 5:47 PM, Stefan Kendall notifications@github.com
wrote:

> This is still an issue for me. Can this get any traction?
> 
> —
> Reply to this email directly or view it on GitHub.

—
Reply to this email directly or view it on
GitHubhttps://github.com/chriseppstein/compass/issues/922#issuecomment-9759826.

**Comment by scottdavis** [comment]
Awesome

**Comment by tomkiss** [comment]
I can't seem to get to the listen branch, is there another one to use now?

I'm still getting the same error as above. Somewhat of a rubynewbie too so I'm struggling a little!

I'm using compass with a custom made rack app (custom made not by myself, ahem).

Here's some info incase it's helpful.

```
compass watch --trace 

LoadError on line ["70"] of /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.2/lib/compass/commands/watch_project.rb: cannot load such file -- fssm
  /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.2/lib/compass/commands/watch_project.rb:70:in `perform'
  /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.2/lib/compass/commands/base.rb:18:in `execute'
  /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.2/lib/compass/commands/project_base.rb:19:in `execute'
  /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.2/bin/compass:30:in `block in <top (required)>'
  /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.2/bin/compass:44:in `call'
  /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.2/bin/compass:44:in `<top (required)>'
  /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/bin/compass:19:in `load'
  /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/bin/compass:19:in `<main>'
  /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/bin/ruby_noexec_wrapper:14:in `eval'
  /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/bin/ruby_noexec_wrapper:14:in `<main>'
```

Also noticing an error with validating:

```
compass validate --trace

LoadError on line ["32"] of /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.2/lib/compass/commands/validate_project.rb: cannot load such file -- compass/validator
  /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.2/lib/compass/commands/validate_project.rb:32:in `perform'
  /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.2/lib/compass/commands/base.rb:18:in `execute'
  /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.2/lib/compass/commands/project_base.rb:19:in `execute'
  /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.2/bin/compass:30:in `block in <top (required)>'
  /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.2/bin/compass:44:in `call'
  /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.2/bin/compass:44:in `<top (required)>'
  /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/bin/compass:19:in `load'
  /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/bin/compass:19:in `<main>'
  /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/bin/ruby_noexec_wrapper:14:in `eval'
  /Users/mmtom/.rvm/gems/ruby-1.9.3-p327/bin/ruby_noexec_wrapper:14:in `<main>'
```

Gems info:

```
gem list

*** LOCAL GEMS ***

bundler (1.2.3, 1.2.1)
chunky_png (1.2.7, 1.2.6)
compass (0.12.2)
createsend (2.5.0, 1.1.0)
daemon_controller (1.1.1)
diff-lcs (1.2.0, 1.1.3)
fastthread (1.0.7)
fssm (0.2.9)
haml (3.1.7, 3.1.6)
hashie (1.2.0)
httparty (0.10.0, 0.8.3)
improved-rack-throttle (0.7.0)
jammit (0.6.5)
json (1.7.6, 1.7.3)
listen (0.7.2)
modular-scale (1.0.6, 1.0.2)
multi_json (1.5.0, 1.3.6)
multi_xml (0.5.2, 0.5.1)
mustache (0.99.4)
nokogiri (1.5.6, 1.5.5)
open4 (1.3.0)
passenger (3.0.19)
Platform (0.4.0)
POpen4 (0.1.4)
rack (1.4.4, 1.4.1)
rack-protection (1.3.2, 1.2.0)
rack-test (0.6.2)
rake (10.0.3, 0.9.2.2)
redis (3.0.2)
rspec (2.12.0, 2.11.0)
rspec-core (2.12.2, 2.12.0, 2.11.1)
rspec-expectations (2.12.1, 2.12.0, 2.11.3)
rspec-mocks (2.12.1, 2.12.0, 2.11.3)
rubygems-bundler (1.1.0)
rvm (1.11.3.5)
sass (3.2.5, 3.2.3)
sassy-math (1.5, 1.2)
sinatra (1.3.3)
tilt (1.3.3)
webrat (0.7.3)
yui-compressor (0.9.6)
zurb-foundation (3.2.4, 3.2.2)
```

**Comment by tomkiss** [comment]
Ok, I missed the bottom of ramaboo's post above - this solution seems to be working for me, hope my info was useful in some way. Ahem.

**Comment by scottdavis** [comment]
it seems you are using compass 0.12 from your stack trace. The listen branch was merged into master a few months ago but hasn't been released yet.

**Comment by loudin** [comment]
Any update on this? I'm running into the same issue with compass 0.12.

**Comment by scottdavis** [comment]
upgrade to `gem install compass --pre`

**Comment by markalanevans** [comment]
I just did the gem update compass --pre

and am still having issues

```
compass watch --trace
```

```
ArgumentError on line ["742"] of /Users/mevans/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/pathname.rb: different prefix: "/" and "."
  /Users/mevans/.rvm/gems/ruby-1.9.2-p320/gems/compass-0.13.alpha.2/lib/compass/watcher/project_watcher.rb:55:in `block in create_sass_watchers'
  /Users/mevans/.rvm/gems/ruby-1.9.2-p320/gems/compass-0.13.alpha.2/lib/compass/watcher/project_watcher.rb:51:in `map'
  /Users/mevans/.rvm/gems/ruby-1.9.2-p320/gems/compass-0.13.alpha.2/lib/compass/watcher/project_watcher.rb:51:in `create_sass_watchers'
  /Users/mevans/.rvm/gems/ruby-1.9.2-p320/gems/compass-0.13.alpha.2/lib/compass/watcher/project_watcher.rb:25:in `initialize'
  /Users/mevans/.rvm/gems/ruby-1.9.2-p320/gems/compass-0.13.alpha.2/lib/compass/commands/watch_project.rb:64:in `new'
  /Users/mevans/.rvm/gems/ruby-1.9.2-p320/gems/compass-0.13.alpha.2/lib/compass/commands/watch_project.rb:64:in `perform'
  /Users/mevans/.rvm/gems/ruby-1.9.2-p320/gems/compass-0.13.alpha.2/lib/compass/commands/base.rb:18:in `execute'
  /Users/mevans/.rvm/gems/ruby-1.9.2-p320/gems/compass-0.13.alpha.2/lib/compass/commands/project_base.rb:19:in `execute'
  /Users/mevans/.rvm/gems/ruby-1.9.2-p320/gems/compass-0.13.alpha.2/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /Users/mevans/.rvm/gems/ruby-1.9.2-p320/gems/compass-0.13.alpha.2/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Users/mevans/.rvm/gems/ruby-1.9.2-p320/gems/compass-0.13.alpha.2/bin/compass:30:in `block in <top (required)>'
  /Users/mevans/.rvm/gems/ruby-1.9.2-p320/gems/compass-0.13.alpha.2/bin/compass:44:in `call'
  /Users/mevans/.rvm/gems/ruby-1.9.2-p320/gems/compass-0.13.alpha.2/bin/compass:44:in `<top (required)>'
  /Users/mevans/.rvm/gems/ruby-1.9.2-p320/bin/compass:19:in `load'
  /Users/mevans/.rvm/gems/ruby-1.9.2-p320/bin/compass:19:in `<main>'
  /Users/mevans/.rvm/gems/ruby-1.9.2-p320/bin/ruby_noexec_wrapper:14:in `eval'
  /Users/mevans/.rvm/gems/ruby-1.9.2-p320/bin/ruby_noexec_wrapper:14:in `<main>'
```

```
gem list
```

```
*** LOCAL GEMS ***

activemodel (3.2.11)
activerecord (3.2.11)
activesupport (3.2.11)
arel (3.0.2)
backports (2.8.2)
builder (3.0.0)
bundler (1.2.4)
chunky_png (1.2.7)
compass (0.13.alpha.2, 0.12.2)
createsend (2.5.1)
dalli (2.6.2)
eventmachine (1.0.0)
fssm (0.2.10)
google_hash (0.8.0)
hashie (1.2.0)
htmlentities (4.3.1)
httparty (0.10.2)
i18n (0.6.1)
json (1.7.7, 1.7.6)
listen (0.5.3)
minitest (4.6.1, 1.6.0)
multi_json (1.5.0)
multi_xml (0.5.3)
mysql (2.9.1)
os (0.9.6)
rack (1.4.3)
rack-protection (1.3.2)
rack-test (0.6.2)
rake (10.0.3, 0.8.7)
rdoc (3.12.1, 2.5.8)
rubygems-bundler (1.1.0)
rubygems-update (1.8.25)
rvm (1.11.3.6)
sane (0.25.6)
sass (3.2.5)
sinatra (1.3.3)
sinatra-contrib (1.3.2)
sparsehash (0.1.1)
tilt (1.3.3)
tzinfo (0.3.35)
zip (2.0.2)
```

**Comment by scottdavis** [comment]
It should be fixed in the master branch ill do another alpha this weekend

**Comment by markalanevans** [comment]
Ok. In the mean time i went back a version or so and then changed some of the autoload commands in the fssm::watch_project.rb file to be require. 

Its got me back up and running for now...

**Comment by robtarr** [comment]
I was having this same issue. I tried `gem install compass --pre`

but now I'm getting

```
$ compass watch --trace
LoadError on line ["31"] of /Users/rob/.rvm/gems/ruby-1.9.3-p125/gems/listen-0.5.3/lib/listen.rb: cannot load such file -- listen/listener
  /Users/rob/.rvm/gems/ruby-1.9.3-p125/gems/compass-0.13.alpha.2/lib/compass/watcher/project_watcher.rb:40:in `setup_listener'
  /Users/rob/.rvm/gems/ruby-1.9.3-p125/gems/compass-0.13.alpha.2/lib/compass/watcher/project_watcher.rb:27:in `initialize'
  /Users/rob/.rvm/gems/ruby-1.9.3-p125/gems/compass-0.13.alpha.2/lib/compass/commands/watch_project.rb:64:in `new'
  /Users/rob/.rvm/gems/ruby-1.9.3-p125/gems/compass-0.13.alpha.2/lib/compass/commands/watch_project.rb:64:in `perform'
  /Users/rob/.rvm/gems/ruby-1.9.3-p125/gems/compass-0.13.alpha.2/lib/compass/commands/base.rb:18:in `execute'
  /Users/rob/.rvm/gems/ruby-1.9.3-p125/gems/compass-0.13.alpha.2/lib/compass/commands/project_base.rb:19:in `execute'
  /Users/rob/.rvm/gems/ruby-1.9.3-p125/gems/compass-0.13.alpha.2/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /Users/rob/.rvm/gems/ruby-1.9.3-p125/gems/compass-0.13.alpha.2/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Users/rob/.rvm/gems/ruby-1.9.3-p125/gems/compass-0.13.alpha.2/bin/compass:30:in `block in <top (required)>'
  /Users/rob/.rvm/gems/ruby-1.9.3-p125/gems/compass-0.13.alpha.2/bin/compass:44:in `call'
  /Users/rob/.rvm/gems/ruby-1.9.3-p125/gems/compass-0.13.alpha.2/bin/compass:44:in `<top (required)>'
  /Users/rob/.rvm/gems/ruby-1.9.3-p125/bin/compass:19:in `load'
  /Users/rob/.rvm/gems/ruby-1.9.3-p125/bin/compass:19:in `<main>'
  /Users/rob/.rvm/gems/ruby-1.9.3-p125/bin/ruby_noexec_wrapper:14:in `eval'
  /Users/rob/.rvm/gems/ruby-1.9.3-p125/bin/ruby_noexec_wrapper:14:in `<main>'
```

Mac OS X 10.8.2

**Comment by loudin** [comment]
Just to confirm, I'm getting the same issue as robtarr above. Anyone know what version I can rollback to so I can get things working again?

**Comment by markalanevans** [comment]
I ended up rolling back to the 0.12.1 

However, I found that by doing this 

```
compass watch --trace 
```

There was a problem i was getting within the fssm gem.

but with a few modifications to fssm.

I found that there was some weird issue with files not being found etc

seems like there is some weird issue for me going on w/ "autoload" not sure what but either way

I replaced "autoload" with "require" in this file

```
~/.rvm/gems/ruby-1.9.2-p320/gems/fssm-0.2.9/lib/fssm.rb 
```

```
dir = File.expand_path(File.dirname(__FILE__))
$LOAD_PATH.unshift dir unless $LOAD_PATH.include?(dir)

require 'thread'

module FSSM

  FSSMError         = Class.new(StandardError)
  FileNotFoundError = Class.new(FSSMError)
  FileNotRealError  = Class.new(FSSMError)
  CallbackError     = Class.new(FSSMError)

  require        'fssm/version'
  require       'fssm/pathname'
  require        'fssm/support'
  require           'fssm/tree'
  require           'fssm/path'
  require        'fssm/monitor'

  module State
    require    'fssm/state/directory'
    autoload :File,         'fssm/state/file'
  end

  module Backends
    require      'fssm/backends/polling'
    autoload :FSEvents,     'fssm/backends/fsevents'
    autoload :RBFSEvent,    'fssm/backends/rbfsevent'
    autoload :Inotify,      'fssm/backends/inotify'

```

And here are the versions of the gems i have

```
 []gem list

*** LOCAL GEMS ***

activemodel (3.2.11)
activerecord (3.2.11)
activesupport (3.2.11)
arel (3.0.2)
backports (2.8.2)
builder (3.0.0)
bundler (1.3.0, 1.2.4)
chunky_png (1.2.7, 1.1.2)
compass (0.12.1)
createsend (2.5.1)
dalli (2.6.2)
ethon (0.5.9)
eventmachine (1.0.0)
ffi (1.2.1)
fssm (0.2.9)
google_hash (0.8.0)
hashie (1.2.0)
htmlentities (4.3.1)
httparty (0.10.2)
i18n (0.6.1)
json (1.7.7, 1.7.6)
listen (0.5.3)
mime-types (1.21)
minitest (4.6.1, 1.6.0)
multi_json (1.5.0)
multi_xml (0.5.3)
mysql (2.9.1)
nokogiri (1.5.6)
os (0.9.6)
rack (1.4.3)
rack-protection (1.3.2)
rack-test (0.6.2)
rake (10.0.3, 0.8.7)
rdoc (3.12.1, 2.5.8)
rubygems-bundler (1.1.0)
rubygems-update (1.8.25)
rvm (1.11.3.6)
sane (0.25.6)
sass (3.2.5)
sinatra (1.3.3)
sinatra-contrib (1.3.2)
sparsehash (0.1.1)
tilt (1.3.3)
typhoeus (0.6.1)
tzinfo (0.3.35)
zip (2.0.2)
```

Along with my ruby version.

```
ruby -v
ruby 1.9.2p320 (2012-04-20 revision 35421) [x86_64-darwin10.8.0]
```

**Comment by markalanevans** [comment]
Also FYI:

I was having some issues since i recently upgraded bundler.

Running 

```
rubygems-bundler-uninstaller
```

Got rid of an error I was having that looked something like this:

```
/gems/bundler-1.1.3/lib/bundler/shared_helpers.rb:22:in `default_gemfile': Could not locate Gemfile (Bundler::GemfileNotFound)
...
```

**Comment by robtarr** [comment]
Running `rubygems-bundler-uninstaller` fixed my issue as well. Thanks.

**Comment by rafaelgoulart** [comment]
+1 for <code>rubygems-bundler-uninstaller</code>. Thank you guys!

**Comment by isuhendro** [comment]
+1 for rubygems-bundler-uninstaller. Thanks a lot!

**Comment by jklegseth** [comment]
+1 for rubygems-bundler-uninstaller. Thanks.

**Comment by eboyer** [comment]
+1 for rubygems-bundler-uninstaller. YES.

**Comment by jkneb** [comment]
+1 YES!! Thank you.

**Comment by nbyarnell** [comment]
rubygems-bundler-uninstaller did the trick, thanks!

**Comment by gvinter** [comment]
+1 for `rubygems-bundler-uninstaller`
