### ISSUE TITLE
Sass compiler can't see Compass

### ISSUE THREAD

**Issue by ilyador** [Compass/compass#925]
I have compass installed but when I try to watch the SASS file I get:
`Line 1: File to import not found or unreadable: compass/css3.`
Is there a way I should reference to compass?
(using Windows 7)

**Comment by parkr** [comment]
What command are you using? Make sure you're using the `compass` command. The `sass` command doesn't include/know about the `compass` libraries (only `compass` knows about these).

`compass watch` with the compass config file (`config.rb`) in the cwd, you will be able to use `compass/css3`.

**Comment by ilyador** [comment]
Thanx, I did try to use sass command.

**Comment by parkr** [comment]
Great! Please close this when you get the chance.
