### ISSUE TITLE
How to use css 3 PIE / background(rgba())

### ISSUE THREAD

**Issue by ni-ka** [Compass/compass#928]
Hey,

I'm trying to use css 3 PIE to enable transparent backgrounds on IE.

I've run the install command for pie, included the generated css (  and added some mixins that should be using PIE to my code:

```
  @include pie;
  @include background(rgba(255,255,255,0.75));
```

However, the -pie-background css is never included into the page. It is added by the following lines in frameworks/compass/stylesheets/compass/css3/_images.scss (around line 20).

```
$backgrounds: compact($background-1, $background-2, $background-3, $background-4, $background-5,
                    $background-6, $background-7, $background-8, $background-9, $background-10);
$mult-bgs: -compass-list-size($backgrounds) > 1;
$add-pie-bg: prefixed(-pie,   $backgrounds) or $mult-bgs;
@if $experimental-support-for-svg          and prefixed(-svg,    $backgrounds) {      background:    -svg($backgrounds); }
--- SNIP ---
@if $experimental-support-for-pie          and $add-pie-bg                     { -pie-background:    -pie($backgrounds); }
                                                                                    background:         $backgrounds ;
}
```

The PIE behavior is imported correctly and fetched by IE.

$experimental-support-for-pie is correctly set to true. But the correct code is only generated if I remove the and $add-pie-ng - which calls prefixed(-pie,   $backgrounds).

How can I ensure that the prefixed call returns true? Am I using the right syntax?

Best,

Nils

**Comment by chriseppstein** [comment]
The `-pie` property is only set when it needs to be based on the arguments. Does PIE have an alpha shim now?

/cc @lojjic

**Comment by lojjic** [comment]
Yes it will render the rgba alpha.

**Comment by chriseppstein** [comment]
CSS3 Pie was removed.
