### ISSUE TITLE
Rails3 bug: image_url_with_rails_integration no longer works

### ISSUE THREAD

**Issue by merbjedi** [Compass/compass#93]
NameError Exception: undefined local variable or method `controller' for #Sass::Script::Functions::EvaluationContext:0x00000103ea6768

Full backtrace: http://gist.github.com/309883

Removing app_integration/rails/urls.rb fixes the problem

I think we're going to need another solution for Rails3. Maybe a separate rails3 app_integration folder that does things differently?

**Comment by chriseppstein** [comment]
That's a bit over-the-top. The goal is to gain access to the code that generates asset timestamps. We should detect which codebase is in use and make the appropriate changes at runtime in the same. For now, it's sufficient to disable this particular feature in a rails3 context while we devise a new strategy

**Comment by merbjedi** [comment]
Yep, agreed. This should work for now till we figure out how to get the .controller to respond correctly within the Sass Evaluation context when using Rails3 http://github.com/merbjedi/compass/commit/719cd980ae438093d33876a06c956ce388ee78d1

**Comment by chriseppstein** [comment]
please see my comment on the changeset.

**Comment by chriseppstein** [comment]
merged. Thanks!
