### ISSUE TITLE
better error message for color-stops()

### ISSUE THREAD

**Issue by mirisuzanne** [Compass/compass#94]
Current error for calling color-stop() (no 's') is:

NoMethodError on line 157 of /Library/Ruby/Gems/1.8/gems/compass-0.10.0.pre6/lib/compass/sass_extensions/functions/gradient_support.rb: undefined method `values' for "color_stop(#ff8b3d, #ff8b3d 48%, #ff7c23 50%, #ff6700)":Sass::Script::String

Could have more detail on the required change

**Comment by chriseppstein** [comment]
Ok you'll get something like this now:

```
error src/screen.sass (Line 33: "color_stop(white, #cccccc)" is not a list of color stops. Expected: color_stops(<color> <number>?, ...) for `grad_color_stops')
```
