### ISSUE TITLE
diagonal sprites

### ISSUE THREAD

**Issue by pdewouters** [Compass/compass#940]
Hi

this is just a feature idea. It would be nice to have an option for diagonal sprites
http://www.aaronbarker.net/2010/07/diagonal-sprites/

I know there's the padding option that works quite well, but here's another option.

**Comment by chriseppstein** [comment]
There are 4 supported [sprite layouts](http://compass-style.org/help/tutorials/spriting/sprite-layouts/):
- `vertical` (default)
- `horizontal`
- `diagonal`
- `smart`

**Comment by pdewouters** [comment]
awesome!
