### ISSUE TITLE
IE 8/9, ellipsis, and word-wrap

### ISSUE THREAD

**Issue by necolas** [Compass/compass#941]
IE 8/9 won't respect the `white-space: nowrap` declaration in the ellipsis mixin when there is a parent that has `word-wrap: break-word`. The result is that no ellipsis is shown and the text will get broken and wrap across multiple lines.

The fix is simple, add `word-wrap: normal` to the ellipsis mixin to act as a guard against this IE 8/9 behaviour. This seems like it would be a fairly safe thing to do, but could benefit from a little more exploration.

Test case & fix: http://jsfiddle.net/P2v4c/

(Thanks to everyone below who helped identify the extent of this bug in various versions of IE)

**Comment by nathancrank** [comment]
I can confirm your fix works in IE 8.

And that it doesn't work without your fix.

**Comment by Boldewyn** [comment]
The issue also appears in our IE9, Win7. The proposed solution fixes it.

**Comment by necolas** [comment]
Thanks Nathan, so I'm assuming you see the same bug in IE8 too (the first paragraph wrapping onto multiple lines)?

**Comment by bjornjohansen** [comment]
The fix works in IE8 (and IE7, but doesn't seem to need it):
IE8: http://yfrog.com/khi2xmnbj
IE7: http://yfrog.com/j263kkhj

**Comment by csscallum** [comment]
I can confirm what Bjørn has reported. In XP, IE8 fix works for the second line whereas IE7 requires no such fix.

**Comment by necolas** [comment]
Thanks :)

**Comment by derekjohnson** [comment]
I've tested in IE7 and IE8 and got the same results as Bjorn.

**Comment by nathanieldeal** [comment]
I got the same results at Bjorn as well.

**Comment by nathancrank** [comment]
Yes Necolas, that is correct. It's totally busted without your fix! Also, Its IE8 on XP, forgot to mention the OS...

**Comment by devinfd** [comment]
Does one more vote of confirmation matter? If so, Yes I confirm Bjorn's readings.

**Comment by scottdavis** [comment]
would you mind making a pull request?

**Comment by makangus** [comment]
Just ran into the same issue, put in #1199
