### ISSUE TITLE
Sprite file is overwritten when multiple scss files import same sprite with different options

### ISSUE THREAD

**Issue by jpitzo** [Compass/compass#943]
Currently, if you have multiple scss files importing the same sprite file, but with different options, the sprite will be overwritten by the second file and the first file will point to a missing sprite.  Doing this would be an error on the users part, but right now compass does not throw any errors alerting the user of the problem. An example would be:

lightbulb.scss has the lines

``` scss
$lightbulb-spacing: 15px;
@import "lightbulb/*.png";
@include all-lightbulb-sprites;
```

main.scss has the lines

``` scss
@import "lightbulb/*.png";
@include all-lightbulb-sprites;
```

The generated sprite name will be correct for main.css, but lightbulb.css will reference a non-existing sprite file.  I would think it might be helpful if compass could provide an error in this scenario as troubleshooting this can be very difficult.

**Comment by chriseppstein** [comment]
You need to set `$lightbulb-clean-up` to `false`.
