### ISSUE TITLE
Show warning/error on unknown function

### ISSUE THREAD

**Issue by tholewebgods** [Compass/compass#946]
Compass should show warning/error on unknown functions.

Recently I've checked out styles that has been modified by a colleague which was using compass-0.12.2 while I was using compass-0.11.5 which was not ware of the new `image-height()` functions. Compile/watch run perfectly without errors but some styles were broken. Nothing showed that there was an error.

Not sure which sass version I was using that time.

This .scss code has been written to the .css file:

```
height: image-height(sprite-file($btnsprite, diashownavi-download));
```

**Comment by chriseppstein** [comment]
This is how sass works in order to be future friendly. There are too many CSS functions for us to try to know which functions should be passed thru to CSS and which are typos of sass functions. 

Hunt & pecked on my iPhone... Sorry if it's brief!
