### ISSUE TITLE
Deprecate $use-mozilla-ellipsis-binding

### ISSUE THREAD

**Issue by necolas** [Compass/compass#950]
[Firefox 4 disabled XUL for websites](https://groups.google.com/forum/?fromgroups#!topic/mozilla.dev.platform/MnnmjYlm2jY) and apparently stopped this hack from having any effect. Firefox 7 supports `text-overflow:ellipsis`.

So this hack is only, probably, useful for Firefox 3.6. But #229 suggests it isn't working in 3.6 anyway.

The current compass docs are a bit misleading in that they state:

> To get full firefox support, you must install the ellipsis pattern

But actually, it seems that the installable ellipsis pattern is going to have no effect at all. The poor souls on Firefox 4, 5, and 6 won't have any ellipsis support. Issue #229 suggests 3.6 doesn't either, even with the hack. And everyone else has Firefox 7+ with (at least) basic `text-overflow` support.

So, maybe it should just be removed altogether.

**Comment by chriseppstein** [comment]
Agree. This needs an overhaul or to be removed.
