### ISSUE TITLE
Compass doesn't detect image change

### ISSUE THREAD

**Issue by kud** [Compass/compass#952]
If I have already generated a sprite and I modify an image without changing its name, Compass won't regenerate the sprite, seen as unchanged.

And I didn't find any solution to generate it again except changing the scss calling it (by adding a space and removing it).

**Comment by MoOx** [comment]
Feature request ?
(btw, with SublimeText2, no need to add/remove space, just save - automatically force save & send fs event)

**Comment by DanielHeath** [comment]
Surely we could compare the mtime for the sprite with the mtime of the source files to check whether the sprite needs regenerating?

**Comment by chriseppstein** [comment]
In theory, we could remember which images were referenced in the last compile and watch those for changes which would trigger the recompile of the referencing stylesheet.

Or a more brute force approach: we could just monitor the whole images directory and recompile whenever any image changes.
