### ISSUE TITLE
stand-alone compass question

### ISSUE THREAD

**Issue by resistorsoftware** [Compass/compass#96]
Hi,

I like to generate css where compass writes out something like 

```
#header .logo h1 { background-image: url('logo.jpg'); }
```

But no matter what I try in config.rb I am getting a '/logo.jpg' or a '../logo.jpg'

Is there a way to get an image asset to be generated just as is?

Thanks

**Comment by chriseppstein** [comment]
yes, this is possible. Please send an email to the mailing list for support.

http://groups.google.com/group/compass-users

Also, please include some snippet of sass code.
