### ISSUE TITLE
Sprite layout variable failing (for a specific use case, anyway)

### ISSUE THREAD

**Issue by t1to98** [Compass/compass#963]
So the new variable that allows you to choose the layout of your sprites is awesome. However it isn't working for me under a particular circumstance:

• When I'm creating a sprite of retina icons AND
• I create a map of those icons

It works fine when I generate a sprite from the same set of smaller files for regular displays. So perhaps the size of the files has something to do with it. We found something interesting while debugging, though ...

The layout variable works for the retina images if I choose not to make a sprite map from it. So it works when removing this line:

$retina: sprite-map("retina/*.png");

Of course, I need that variable to reference the sprite elsewhere. So my solution in the interim is to have two identical folders holding the retina images. From one I generate the sprite itself (which outputs the correct layout), from the other I generate the map and sprite URL. Then, as a final step before production, I take the retina sprite with the correct layout and overwrite the image with the incorrect layout. 

Here's a gist of an instance where the layout variable works and one where it doesn't: https://gist.github.com/3123449

Thanks for the help here!

tito.

p.s. - That gist might make a little more sense if I explain my overall approach to serving both retina and regular sprites.  Basically, I simply replace the regular sprite image with the retina image using a mediaquery. I use the magic import and retain all the original mapping/positioning from the regular sprite -- only the image and the background size changes for retina. That's why it's important to retain an identical layout between the original and the retina sprite.

**Comment by noAlvaro** [comment]
Yup, same here for the first time.

In my case I have four 1px height images, and layout variable is defined to horizontal.
It actually work for the sprite generated at first time. But after changing other scss on project compass watch compile it again to vertical layout.

A bug, I presume.

**Comment by chriseppstein** [comment]
are you sure you don't have the same sprite created from several files but configured differently?

**Comment by t1to98** [comment]
Hope I understand your question correctly, Chris. I feel sure that I'm creating to distinctly different sprites because I've opened both generated sprites in Photoshop to compare the sizes. Sure enough, the retina one is bigger.

That said, I don't feel like I completely understood your question. If I missed something, please elaborate.

**Comment by eliten00b** [comment]
i don't get the layout option working in both cases, sprite-map and @import.

**Comment by chriseppstein** [comment]
Pretty sure this is because you are calling `sprite-map()` directly -- this is only necessary when you're not using the `@import`-based approach.

```
$sprite: sprite-map("sprite/*.png");
$retina: sprite-map("retina/*.png");
```

The imports themselves call `sprite-map` and define `$sprite-sprites` and `$retina-sprites` for you.

This happens because the sprite-map() function is what generates the file as a side-effect and since you're calling it with different parameters in two different places (one in the import, once in your file for each sprite) it cleans up (removes) the previously generated sprite image on the previous call.

**Comment by t1to98** [comment]
Thanks, Chris. You nailed it. I removed those calls, used the variables you suggested, and boom, it worked. I somehow missed that in the Spriting documentation.

**Comment by noAlvaro** [comment]
Thats right. I was calling it again.

Although the documentation highlight the _@import_ approach as "the easiest way to work sprites", I didn't realized that the map was already available, from the import. That's great!

Thanks for explaining.

**Comment by noAlvaro** [comment]
By the way, is there a chance for us to access that map variable (the one created within the "import") for other purpose around the project?
