### ISSUE TITLE
undefined method `first' for 0:Fixnum for linear-gradient in webkit

### ISSUE THREAD

**Issue by adamlogic** [Compass/compass#964]
I'm getting the error when using a pixel measurement for my color stops:

```
+background(linear-gradient(0, rgba(0,0,0,.2) 0px, transparent 1px)
```

However, if I change the gradient starting point from `0` to `left`, it works:

```
+background(linear-gradient(left, rgba(0,0,0,.2) 0px, transparent 1px)
```

Not a big deal to use the alternate syntax, but I wanted to have this documented for the next person who encounters this error. Commit 9940ee8cbbe52e217a88b9a46ae5074790eea129 implements pixel stops for webkit, but notice the tests only use "top" and "left" for the starting point.

I'm using Chrome and Compass 0.12.1

**Comment by chriseppstein** [comment]
this is not legal css syntax for gradients. [spec](http://www.w3.org/TR/css3-images/#linear-gradients)
