### ISSUE TITLE
Compass watch Problems on Win7 with mklink

### ISSUE THREAD

**Issue by jpgerdeman** [Compass/compass#968]
I'm using compass on Windows 7 and created symlinks from my source to a target via mklink. Compass fails to recognize changes in source.

Compass Version:

```
Compass 0.12.1 (Alnilam)
```

Links were created using 

```
mklink /d C:\target c:\source
```

I've mapped C:\source and C:\target as follows

```
target =>(points to) source
C:\target\stylesheets\source ==> C:\source\stylesheets
C:\target\images\source ==> C:\source\images
C:\target\javascripts\source ==> C:\source\javascripts
```

I start compass from C:\source as follows `compass watch`, it starts polling but never discovers a change I make. When calling `compass watch --force` the stylesheets are compiled once at startup, but every subsequent change stays undetected.

When I remove the symbolic links everything works as expected..

**Comment by chriseppstein** [comment]
We use the sass watcher now. If this issue is present in Sass with the compass 1.0 release, please file a bug there.
