### ISSUE TITLE
Compass watch is not catching changes to new .sass files

### ISSUE THREAD

**Issue by Mrduckie** [Compass/compass#972]
I'm new to Compass and Sass, and I've recently just started to dabble in ruby, so sorry for any lack of information. But recently compass watch has stopped catching changes I've made to certain .sass files. It is able to see changes done to screen.sass but when changes are made to newer .sass files (such as front.sass), compass watch won't react. If I create a new .sass file it will recognize the first save but any save after that it will not see. Compass watch works fine with .scss files.

I'm running Compass 0.12.2 (Alnilam), Sass 3.1.20 (Brainy Betty), Haml 3.1.6 (Separated Sally), and ruby 1.9.3p194 (2012-04-20) [i386-mingw32]  on Windows 7.

Any help is appreciated, thanks.

**Comment by chriseppstein** [comment]
We're dropping FSSM for Listen. I think this will be fixed by #983
