### ISSUE TITLE
Methods provided in urls.rb not respecting arguments when supplied with a relative URL

### ISSUE THREAD

**Issue by charlietoleary** [Compass/compass#980]
Methods provided in the urls.rb file do not seem to be respecting their two arguments: $only-path & $cache-buster when called with a relative url.

This includes the image-url() function, which we can use as an example of the problem.

Example:

``` css
image_url("/sub-images/image.png", true, true);
```

Returns:

``` css
url(/sub-images/image.png);
```

Expected result:

``` css
/sub-images/image.png?cache-key
```

There is a line handling relative paths in each function that looks somewhat like this:

``` ruby
# Short curcuit if they have provided an absolute url.
if absolute_path?(path)
  return Sass::Script::String.new("url(#{path})")
end
```

As you can see, this causes each function to include url(): regardless of the passed in $only-path argument, and also does not append the cache buster.

Please let me know if i am missing something here, or have spotted an issue.

Cheers - Charlie.

**Comment by chriseppstein** [comment]
The path you provide should be relative to your images directory. You've provided an http root-relative path, so compass assumes you don't want help making the url. This is by design.

**Comment by chriseppstein** [comment]
In other words just do:

``` scss
div { background: image-url("sub-images/image.png"); }
```

**Comment by charlietoleary** [comment]
@chriseppstein I would still like to raise the use-case in that I am utilizing the image-url() function (or any other URL helper) solely for the fact that I am wishing to generate the url with a cache buster prefix.

If I call image-url() with the cache_buster parameter shouldn't this still be respected regardless of what type of path I am providing.

Secondly, if I am specifying that I wish to return only the path - yet the function is returning the path wrapped in url() - this is an error in the function?

If my project relied on me calling image-url() with a root-relative path - what other methods are available to prefix this path with a cache buster?

Sorry for being a hassle haha - Cheers, Charlie.
