### ISSUE TITLE
With Compass watch on OS X, Sublime Text 2 Save on Focus Lost Sometimes Causes "NoMethodError" in Sass

### ISSUE THREAD

**Issue by kohlmannj** [Compass/compass#981]
On OS X, Sublime Text 2's "Save on Focus Lost" feature appears to sometimes cause problems with Sass by way of Compass, which as of 0.13 alpha, still uses FSSM.

Steps to Reproduce:
1. Test on a Mac running:
   - OS X 10.8
   - ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0]
   - Compass 0.13.alpha.0 (Markab)
   - Sass 3.2.0.alpha.247 (Bleeding Edge)
2. Create a Compass project.
3. Create a partial file, such as "_test.scss".
4. Open the Sass files in this Compass project in Sublime Text 2 on OS X 10.8.
5. Enable Sublime Text 2's Save on Focus Lost feature by adding <code>"save_on_focus_lost": true</code> to Preferences.sublime-settings.
6. Import the partial file in "screen.scss".
7. Open Terminal, change directories to the Compass project's directory, and run <code>compass watch --trace</code>
8. Add changes to both screen.scss and _test.scss, and allow Sublime Text 2 to save on defocus, rather than pressing Command + S.

Eventually you may see some output like what I've included below. This appears to be related to files starting with an underscore; I've never seen the error occur after a change to "screen.scss" was detected. The only other note about my system—it uses a SSD for internal storage, and the directories/files mentioned in the trace, including the OS X, Compass, Ruby, and Sass installations are all on this SSD.

<pre>
magellan:workspace kohlmannj$ compass watch --trace

Dear developers making use of FSSM in your projects,
FSSM is essentially dead at this point. Further development will
be taking place in the new shared guard/listen project. Please
let us know if you need help transitioning! ^_^b
- Travis Tilley

>>> Compass is watching for changes. Press Ctrl-C to Stop.
>>> Change detected at 17:43:59 to: _home.scss
identical css/screen.css 
>>> Change detected at 17:44:23 to: _home.scss
overwrite css/screen.css 
>>> Change detected at 17:44:34 to: _home.scss
overwrite css/screen.css 
>>> Change detected at 17:44:47 to: screen.scss
identical css/screen.css 
>>> Change detected at 17:45:26 to: screen.scss
overwrite css/screen.css 
>>> Change detected at 17:45:59 to: _base.scss
NoMethodError on line 94 of /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/visitors/deep_copy.rb: undefined method `deep_copy' for #<Array:0x1055c22f8>
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/visitors/base.rb:37:in `send'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/visitors/deep_copy.rb:6:in `visit'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/visitors/deep_copy.rb:10:in `visit_children'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/visitors/deep_copy.rb:10:in `map'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/visitors/deep_copy.rb:10:in `visit_children'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/visitors/base.rb:39:in `visit'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/visitors/deep_copy.rb:6:in `visit'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/visitors/base.rb:24:in `send'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/visitors/base.rb:24:in `visit'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/node.rb:175:in `deep_copy'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/cache_stores/memory.rb:32:in `retrieve'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/cache_stores/chain.rb:25:in `retrieve'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/script/number.rb:394:in `each_with_index'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/cache_stores/chain.rb:24:in `each'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/cache_stores/chain.rb:24:in `each_with_index'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/cache_stores/chain.rb:24:in `retrieve'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/engine.rb:327:in `_to_tree'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/engine.rb:309:in `_render'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/engine.rb:256:in `render'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:140:in `compile'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:126:in `timed'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:139:in `compile'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/logger.rb:45:in `red'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:138:in `compile'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:118:in `compile_if_required'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:103:in `run'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:101:in `each'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:101:in `run'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:126:in `timed'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:100:in `run'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/commands/watch_project.rb:147:in `recompile'
  /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `to_proc'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/path.rb:73:in `call'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/path.rb:73:in `run_callback'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/path.rb:55:in `callback_action'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/path.rb:35:in `update'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/state/directory.rb:39:in `modified'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/state/directory.rb:37:in `each'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/state/directory.rb:37:in `modified'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/state/directory.rb:18:in `refresh'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/backends/rbfsevent.rb:30:in `temporary_multipath_handler'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/backends/rbfsevent.rb:27:in `each'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/backends/rbfsevent.rb:27:in `temporary_multipath_handler'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/backends/rbfsevent.rb:17:in `run'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/backends/rbfsevent.rb:16:in `each'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/backends/rbfsevent.rb:16:in `run'
  /Library/Ruby/Gems/1.8/gems/rb-fsevent-0.9.1/lib/rb-fsevent/fsevent.rb:43:in `call'
  /Library/Ruby/Gems/1.8/gems/rb-fsevent-0.9.1/lib/rb-fsevent/fsevent.rb:43:in `run'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/backends/rbfsevent.rb:20:in `run'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/monitor.rb:26:in `run'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm.rb:70:in `monitor'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/commands/watch_project.rb:87:in `perform'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/commands/base.rb:18:in `execute'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/commands/project_base.rb:19:in `execute'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/bin/compass:29
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/bin/compass:43:in `call'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/bin/compass:43
  /usr/bin/compass:19:in `load'
  /usr/bin/compass:19
>>> Change detected at 17:48:45 to: _media.scss
overwrite css/screen.css 
>>> Change detected at 17:49:21 to: screen.scss
overwrite css/screen.css 
>>> Change detected at 17:49:27 to: _base.scss
NoMethodError on line 94 of /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/visitors/deep_copy.rb: undefined method `deep_copy' for #<Array:0x1055ea8e8>
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/visitors/base.rb:37:in `send'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/visitors/deep_copy.rb:6:in `visit'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/visitors/deep_copy.rb:10:in `visit_children'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/visitors/deep_copy.rb:10:in `map'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/visitors/deep_copy.rb:10:in `visit_children'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/visitors/base.rb:39:in `visit'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/visitors/deep_copy.rb:6:in `visit'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/visitors/base.rb:24:in `send'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/visitors/base.rb:24:in `visit'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/tree/node.rb:175:in `deep_copy'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/cache_stores/memory.rb:32:in `retrieve'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/cache_stores/chain.rb:25:in `retrieve'
  /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/fileutils.rb:243:in `each_with_index'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/cache_stores/chain.rb:24:in `each'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/cache_stores/chain.rb:24:in `each_with_index'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/cache_stores/chain.rb:24:in `retrieve'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/engine.rb:327:in `_to_tree'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/engine.rb:309:in `_render'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.0.alpha.247/lib/sass/../sass/engine.rb:256:in `render'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:140:in `compile'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:126:in `timed'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:139:in `compile'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/logger.rb:45:in `red'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:138:in `compile'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:118:in `compile_if_required'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:103:in `run'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:101:in `each'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:101:in `run'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:126:in `timed'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:100:in `run'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/commands/watch_project.rb:147:in `recompile'
  /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `to_proc'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/path.rb:73:in `call'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/path.rb:73:in `run_callback'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/path.rb:55:in `callback_action'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/path.rb:35:in `update'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/state/directory.rb:39:in `modified'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/state/directory.rb:37:in `each'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/state/directory.rb:37:in `modified'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/state/directory.rb:18:in `refresh'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/backends/rbfsevent.rb:30:in `temporary_multipath_handler'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/backends/rbfsevent.rb:27:in `each'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/backends/rbfsevent.rb:27:in `temporary_multipath_handler'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/backends/rbfsevent.rb:17:in `run'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/backends/rbfsevent.rb:16:in `each'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/backends/rbfsevent.rb:16:in `run'
  /Library/Ruby/Gems/1.8/gems/rb-fsevent-0.9.1/lib/rb-fsevent/fsevent.rb:43:in `call'
  /Library/Ruby/Gems/1.8/gems/rb-fsevent-0.9.1/lib/rb-fsevent/fsevent.rb:43:in `run'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/backends/rbfsevent.rb:20:in `run'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm/monitor.rb:26:in `run'
  /Library/Ruby/Gems/1.8/gems/fssm-0.2.9/lib/fssm.rb:70:in `monitor'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/commands/watch_project.rb:87:in `perform'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/commands/base.rb:18:in `execute'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/commands/project_base.rb:19:in `execute'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/bin/compass:29
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/bin/compass:43:in `call'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/bin/compass:43
  /usr/bin/compass:19:in `load'
  /usr/bin/compass:19
>>> Change detected at 17:49:41 to: screen.scss
overwrite css/screen.css 
</pre>

**Comment by nex3** [comment]
Sass 3.2.247 is old. Can you reproduce with the latest alpha release?

**Comment by kohlmannj** [comment]
Will _check_… Sorry; didn't realize Sass was out of date on my system.

**Comment by kohlmannj** [comment]
Happily, this issue hasn't re-appeared yet in more than an hour of using <code>compass watch</code> and Sass 3.2.alpha.277. We'll call it closed for now. Thanks for the help, Nathan.
