### ISSUE TITLE
With jruby and compass 0.10--css-dir parameter doesn't make any effect

### ISSUE THREAD

**Issue by edvinasbartkus** [Compass/compass#99]
Using 0.10.0(pre)
jRuby 1.4

Parameter --css-dir doesn't make any effect and is being exported to stylesheets/sass directory.
It was all ok with earlier release.

**Comment by chriseppstein** [comment]
1. Are you using compass stand alone or in an application?
2. What is the full command that you issued?

**Comment by edvinasbartkus** [comment]
I am using compass standalone. The command is such:
jruby -S compass -w --css-dir web-app/css --sass-dir src/sass

Output:
  directory stylesheets/sass/
    compile src/sass/main.sass
      create stylesheets/sass/main.css

The files are being exported to stylesheets/saas/

**Comment by edvinasbartkus** [comment]
I have tried to debug the problem. Sadly, didn't managed to find what causes it. Not enough time. It is only clear that default value is used. The argument is parsed successfully. But later is not written to Configuration class parameters. Instead, default is used.

**Comment by chriseppstein** [comment]
Can you reproduce the issue using normal ruby?

**Comment by edvinasbartkus** [comment]
Yes. same happens on other computer on ubuntu with ruby 1.9.1 installed.

**Comment by chriseppstein** [comment]
Add the options from the command line into the configuration stack. Closed by 6c9244ec14f9a5b03d1995120bbb0fb3277d76cb.
