### ISSUE TITLE
`compass watch` sometimes switches between printing absolute and relative pathnames in compiled .css

### ISSUE THREAD

**Issue by dunn** [Compass/compass#991]
This might be a bit of a corner case, but I found myself in it recently.  To reproduce this behavior (I'm using sass 3.2.0 and compass 0.12.2):
1. `mkdir test; cd test`
2. `compass install compass`
3. `compass watch`
4. `echo '@import "import"; ' > sass/screen.scss`
5. `echo 'body { color: black; }' >> sass/screen.scss`
6. `echo 'p { color: black; }' > sass/_import.scss`

In the compiled screen.css, the pathname for styles from _import.scss will be absolute, while those from screen.scss will be relative.  If you make any changes to one or the other .scss file, _both_ pathnames in screen.css will be relative.  But if you make any change to screen.scss, and _then_ make any change to _import.scss, the screen.css will again have some absolute and some relative pathnames.

**Comment by idflood** [comment]
It looks like a possible duplicate of #989

**Comment by dunn** [comment]
Yeah, it looks like the Sass fix that closed that issue dealt with this problem too.
