### ISSUE TITLE
Compass spriting

### ISSUE THREAD

**Issue by andersonaguiar** [Compass/compass#992]
I have an example:

In the images folder for sprite has:

plus.png

and

plus-hover.png

The bug: It generates the sprite normally the problem is the output of the CSS. The  'hover' is not referenced in CSS, but if I change for 'over' its works perfectly.

**Comment by scottdavis** [comment]
http://compass-style.org/help/tutorials/spriting/magic-selectors/

**Comment by scottdavis** [comment]
please reopen if this doesn't explain what you were seeing.
