### ISSUE TITLE
`compass compile` wrong exit code?

### ISSUE THREAD

**Issue by sindresorhus** [Compass/compass#993]
`compass compile` exits with exit code 1 when there are no nothing to compile: 

> Nothing to compile. If you're trying to start a new project, you have left off the directory argument.

That isn't really an error, so shouldn't it exit with 0?

Since actual errors also makes it exit with 1, it's hard to distinguish them.

I suggest you either make it exit with 0 when there is nothing to compile, or create an higher exit number for when there are actual errors.

**Comment by sindresorhus** [comment]
ping

**Comment by sja** [comment]
me too: ping!

**Comment by scottdavis** [comment]
let me fix this right now while its on my mind. Its because it raises a ruby exception

**Comment by scottdavis** [comment]
Although this technically is an error because it can't find your project config. Ive changed it but expect it to change again once the command interface gets rebuilt and error codes will have more meaning.

**Comment by sindresorhus** [comment]
Don't care as long as it's not 1

**Comment by chriseppstein** [comment]
@sindresorhus I don't understand why you'd want this to not be considered a failure. I added this message because compass used to fail silently and people were very confused. It was usually due to a misconfiguration. Please explain your use case.

**Comment by sindresorhus** [comment]
@chriseppstein failing when there is nothing to compile is like failing when running `compass -h`. It's just some information.

I shell out to Compass in [grunt-contrib-compass](https://github.com/gruntjs/grunt-contrib-compass) and needed to detect when it failed, but not fail on "nothing to compile", which was hard since the error codes were the same.

**Comment by chriseppstein** [comment]
@sindresorhus Why are you compiling nothing? It seems to me that this is a misconfiguration. I'm trying to understand what is the use case around compiling compass with no sass files?

**Comment by sindresorhus** [comment]
@chriseppstein the user might not have any sass files yet while still wanting the compass task in their Gruntfile for later use. In Yeoman we add in support for Compass, but not everyone uses it right away or at all.

**Comment by chriseppstein** [comment]
@sindresorhus That's reasonable, but shouldn't the grunt task simply check if there's any sass files before invoking the compiler?

**Comment by sindresorhus** [comment]
@chriseppstein the task just passes the src/dest folders to Compass and doesn't know about the files. I could of course search before, but that would means two searches (grunt and compass) which would make it even slower to run.

**Comment by chriseppstein** [comment]
@sindresorhus I assume you show them the output of the compass command. Even without the exit code issue, showing a weird compass message to users who aren't using compass, or slowing down the build for users who aren't using compass seems equally bad. Please fix this issue on your end -- I would like to keep considering this to be an error for compass users for the time being.

**Comment by sindresorhus** [comment]
The grunt task is just a thin wrapper to trigger Compass so I don't see how that message is weird for any users. Can you at least consider changing the error code to something higher than 1? Like 2. So it's easier to detect it.

**Comment by chriseppstein** [comment]
I fail to understand why doing this simple check before invoking compass is such a hurdle. You can solve this issue in an hour or wait weeks for a release and still have past version compatibility issues. I'm open to thinking about our exit codes but its something I'd want to be thought out and documented and frankly, this is low priority right now. We have dozens of more pressing issues.

**Comment by sindresorhus** [comment]
> I fail to understand why doing this simple check before invoking compass is such a hurdle

You answered that yourself:

> slowing down the build for users who aren't using compass seems equally bad

Traversing the folder structure for .sass files before running Compass which is quite slow itself is not an option.

> You can solve this issue in an hour or wait weeks for a release and still have past version compatibility issues

I already [worked around](https://github.com/gruntjs/grunt-contrib-compass/blob/master/tasks/compass.js#L29-L37) it a long time ago, but would like it to be fixed eventually for the good of everyone else using Compass.

## 

Please consider reopening this ticket or referring to another one that's about fixing exit codes.

**Comment by chriseppstein** [comment]
> Traversing the folder structure for .sass files before running Compass which is quite slow itself is not an option.

I don't buy this. Running compass is much slower than a simple filesystem check.

```
$ time ruby -e "puts Dir.glob(\"app/stylesheets/*.s[ac]ss\").any?"
true
0.05s user 0.03s system 95% cpu 0.083 total
```

This started ruby and globbed a a very large sass project and checked if it found anything. It took 5 milliseconds to run.

As I said, I'm open to doing an exit code thing, but it's not high on my list given this simple workaround.
