### ISSUE TITLE
Questions about add_import_path and possibly a better approach.

### ISSUE THREAD

**Issue by garand** [Compass/compass#997]
My journey with Compass thus far has been uninhibited, but I've ran into an issue that I would like your input on.

I am working on a fairly large WordPress site with the concept of asset packages, there is a master asset package that is loaded across the entire site, and sub-packages that are loaded on each respective section of the site individually. In the master package I have a variety of imported files, one including a list of variables for the site's design, brand colors, widths, etc. The (simplified) structure is as follows:

```
/assets
        /master
                /css
                /scss
                        master.scss
                        base.scss
                        theme.scss
                config.rb
        /other-package
                /css
                /scss
                        master.scss
                config.rb
```

You can see, currently I have a config.rb file in each directory, I'm not sure if this is the best approach, or if you would do it differently. What it comes down to, is I would like the ability to include files from the master asset package in each other individual asset package.

**Comment by Nilegfx** [comment]
look .. i'm not sure if i did understand you correctly, but What i do in the same case is that i will depend on one css root (with one config file) which will contain all of my assets & packages then i count on the sub folders and a little trick ( underscore before any file or folder will compile this file/folder and uses it without creating a css file for it). then i can import or call any file from any file easily.
